goalgorilla/open_social

- composer.json
[Story](https://goalgorilla.cloudshards.net/browse/DS-1856)
**Background info**
1. On the alpha (Groups version alpha 3) whenever we delete a group we get redirected to /admin/group with a group overview, this redirect is fixed in the Beta 1 release see [drupal.org](https://www.drupal.org/node/2731157), but that wasn't on the PSH environment at the time it was tested last sprint. It is in the distribution now, so we can't really reproduce this workflow. 
2.  So the admin/group is a list of all groups with Title / Author etc. But since there is no author for this user there is a error that they encounter because it tries to get the label from the user that created it. 
The only way to get this error is to login as a user who has the permission to view the admin/group list. …
> DS-1710 unexpected error on group delete

- modules/custom/activity_viewer/src/Plugin/views/filter/ActivityPostVisibilityAccess.php
- themes/socialbase/socialbase.libraries.yml
Two fixes.
One was that for posts and comments the submit button could create multiple entities if pressed multiple times. This was fixed by loading the form.js of drupal core on every page (see core/misc/form.js formSingleSubmit).
Second fix was in the joins in the query. What happened was that activities were joined with node, comment and post specific tables which resulted in sometimes that the ID of a post was returned by matching it to a nid in the node access table. This was fixed by adding extra fields to the join queries.
> DS-1724 fixed multiple activities shown in the stream and submit form js

- themes/socialbase/templates/event/node--event--small-teaser.html.twig
**Try the following as onnevanveldhuizen and jorikscholten**
> DS-1717 - Wrong date in event

- modules/social_features/social_post/src/Form/PostDeleteForm.php
- modules/social_features/social_post/src/PostViewBuilder.php
HTT:
Check that you can delete posts in the home stream / group stream and profile stream and that you get redirected to the correct stream.
Check the destination in the url.
Check that you get redirected to the front page when you remove the destination from the url on a group stream and refresh the page.
Check code
> DS-1734 by nielsvandermolen: Fixed redirect issue when deleting posts

- composer.json
The view 'search_groups' could not be imported due to the missing patch, see also: https://www.drupal.org/node/2778227
In addition to this I removed the double patch for Drupal Core.
> Patches in composer.json for Geolocation grouped filters and Drupal core Grouped filters

- composer.json
Issue:
- Installation is done in the /html directory, this is actually OK if you need to use the https://github.com/goalgorilla/drupal_social developer workflow or if you want to use the composer template on https://github.com/goalgorilla/social_template. But we should not enforce this in the composer.json in the distribution.
Solution:
- Remove the directory settings in composer.json in open_social repo.
- If developers use composer template to install the platform at least it can be set according to your specific needs (e.g. public_html or docroot instead of html)
> DS-1937 / #2792543 - do not set any directory settings in composer.json

- modules/custom/download_count/download_count.install
- modules/social_features/social_book/config/install/core.entity_view_display.node.book.default.yml
- modules/social_features/social_core/social_core.info.yml
- modules/social_features/social_download_count/social_download_count.info.yml
- modules/social_features/social_download_count/social_download_count.services.yml
- modules/social_features/social_download_count/src/SocialDownloadCountConfigOverride.php
- modules/social_features/social_event/config/install/core.entity_view_display.node.event.default.yml
- modules/social_features/social_event/config/install/field.storage.node.field_files.yml
- modules/social_features/social_event/social_event.info.yml
- modules/social_features/social_page/config/install/core.entity_view_display.node.page.default.yml
- modules/social_features/social_page/social_page.info.yml
- modules/social_features/social_topic/config/install/core.entity_view_display.node.topic.default.yml
- modules/social_features/social_topic/social_topic.info.yml
- modules/social_features/social_topic/social_topic.install
- tests/behat/features/bootstrap/SocialDrupalContext.php
- tests/behat/features/capabilities/topic/topic-create.feature
- tests/behat/features/capabilities/topic/topic-download-count.feature
- Removed dependencies from topic, event, book, page features, set default file widget and public FS by default.
- Created new module `social_download_count` with just config overrides.
> DS-1945: Make download_count module optional, override file fields config in social_download_count module

- modules/social_features/social_book/social_book.module
- modules/social_features/social_event/social_event.module
- tests/behat/features/capabilities/event/event-create.feature
- tests/behat/features/capabilities/topic/topic-create.feature
> DS-1722 - Remove enrollment tab form edit pages

- modules/social_features/social_profile/social_profile.install
The permission is necessary to prevent wsod when creating a users profile as sm, cm.
> DS-2070 by jaapjan: add any profile permission for sm, cm

- modules/social_features/social_core/templates/page-hero-data.html.twig
- modules/social_features/social_topic/src/Controller/SocialTopicController.php
- tests/behat/features/capabilities/group/group-create-open.feature
- themes/socialbase/socialbase.theme
- themes/socialbase/templates/node/event/node--event--teaser.html.twig
- themes/socialbase/templates/node/topic/node--topic--teaser.html.twig
> DS-839 by ronaldtebrake: add group to events and topics teaser

- modules/custom/activity_creator/activity_creator.links.menu.yml
- modules/custom/activity_creator/src/ActivityHtmlRouteProvider.php
- modules/social_features/social_event/social_event.links.menu.yml
- modules/social_features/social_event/src/EventEnrollmentHtmlRouteProvider.php
- modules/social_features/social_post/social_post.links.task.yml
- modules/social_features/social_post/src/PostHtmlRouteProvider.php
`git checkout 8.x-1.x;`
`sreset;`
`git checkout feature/DS-1358;`
`drush updb -y;`
`drush fra -y;`
`drush cr`
- Posts are available at http://nightly_build.socialci.goalgorilla.com/admin/content
- Activities are available at http://nightly_build.socialci.goalgorilla.com/admin/structure
- Event enrollments are available at http://nightly_build.socialci.goalgorilla.com/admin/structure
- Posts is available at http://social.dev/admin/content/post
- Activities at: http://social.dev/admin/structure/activity
- Event enrollments at: http://social.dev/admin/structure/event_enrollment
> DS-1358 by ronaldtebrake: removed entity list overview for our custom entities

- modules/custom/activity_creator/src/ActivityFactory.php
This PR fix localization warning: https://localize.drupal.org/translate/projects/social/releases/468365#source-warnings
`The first parameter to t() should be a literal string. There should be no variables, concatenation, constants or other non-literal strings there. At t($value[1],$arguments) in social/modules/custom/activity_creator/src/ActivityFactory.php on line 127. Read more at http://drupal.org/node/322732`
> DS-1946 by ribel: As admin I want the whole interface to be translatable 

- composer.json
- modules/social_features/social_group/social_group.install
HTT:
https://www.drupal.org/project/group/releases/8.x-1.0-beta4
> DS-1677 by nielsvandermolen: Update the group module

- modules/social_features/social_profile/social_profile.install
Made sure we have the image profile only when it's not available in the database. 
When checking opensocial @ gg / and y4p we noticed there wasn't an entry for the default profile picture in the database.. But it is there in the config.
`SELECT * FROM file_managed WHERE filename = 'default-profile-picture.png';` Gave a 0.
That's why we will update the config / database (by doing the file save) only when needed in the update hook. Since probably several installs already have it correctly.
`/admin/config/people/profiles/types/manage/profile/fields/profile.profile.field_profile_image`
> DS-2035 add default profile image.

- modules/social_features/social_profile/social_profile.install
This PR fix and replace `social_profile_update_8001` with `social_profile_update_8002`.
The issue with removing default image was caused because status of file was set to 0, and image was removed after 6 hours by cron.
File status was set to `1` in `_social_profile_add_default_profile_image()`
`/admin/config/people/profiles/types/manage/profile/fields/profile.profile.field_profile_image`
> DS-2035 by ribel: Fix status of default profile image file

- modules/social_features/social_comment/social_comment.install
- modules/social_features/social_comment/social_comment.module
- modules/social_features/social_comment/social_comment.permissions.yml
- modules/social_features/social_comment/src/SocialCommentFieldItemList.php
- Add new permission `administer own comments`
- Enable `administer own comments` permission for authenticated users.
- Alter the default `list_class` for fields of type `comment`
> DS-2175 by ribel: As a LU I can't select if Comments should be open or closed anymore 

- modules/social_features/social_search/config/install/search_api.index.social_content.yml
- modules/social_features/social_search/config/install/search_api.index.social_groups.yml
- modules/social_features/social_search/config/install/search_api.index.social_users.yml
- modules/social_features/social_search/config/install/views.view.search_content.yml
- modules/social_features/social_search/config/install/views.view.search_groups.yml
- modules/social_features/social_search/config/install/views.view.search_users.yml
There was an issue with changes not being displayed correctly in the teaser. The only place I could reproduce it was in the search pages.
The fix was to disable caching for the views page. the render cache for the individual teasers should still apply. Changing the views caching to tag based also did not solve the issue. 
HTT:
> DS-2206 by nielsvandermolen: Disable views caching for search views

- modules/social_features/social_core/social_core.module
- Added button "Read More" to the "activity_comment" view mode.
> DS-2234 by alex.ksis: Fix the missing button "read more"

- modules/custom/activity_send/modules/activity_send_email/activity_send_email.module
- modules/custom/activity_send/modules/activity_send_email/src/Plugin/QueueWorker/ActivitySendEmailWorker.php
- Enabled email notification by default on Edit account form (http://www.screencast.com/t/p9N7vz8kK)
- Enabled email notifications by default in ActivitySendEmailWorker.php
> DS-2259 by ribel: Enable all email notifications by default

- modules/social_features/social_activity/config/install/message.template.create_comment_community_post.yml
- modules/social_features/social_activity/config/install/message.template.create_comment_group_node.yml
- modules/social_features/social_activity/config/install/message.template.create_comment_group_post.yml
- modules/social_features/social_activity/config/install/message.template.create_comment_post_profile.yml
- modules/social_features/social_activity/config/install/message.template.create_event_group.yml
- modules/social_features/social_activity/config/install/message.template.create_post_group.yml
- modules/social_features/social_activity/config/install/message.template.create_topic_group.yml
- modules/social_features/social_core/social_core.module
- tests/behat/features/capabilities/activity-stream/activity-stream-comments.feature
- tests/behat/features/capabilities/activity-stream/create_topic_event.feature
- themes/socialbase/socialbase.theme
Check that on the pages below, the mentioned blocks in the complementary area have the correct subtitle and the links are also correct
Home stream >> 'in the community'
Group stream >> 'in the group'
Profile stream >> 'for this user'
- Upcoming events
- Newest topics
- Newest groups
- Newest members
- Upcoming events
- Newest topics
- Newest members
- Upcoming events
- Recently created topic
- Recently joined groups
> DS-2304 - Remove 'in the group' from activity stream items

- modules/social_features/social_core/config/install/block.block.anhomepageheroblock.yml
- modules/social_features/social_event/config/install/block.block.views_block__upcoming_events_block_community_events.yml
- modules/social_features/social_event/config/install/block.block.views_block__upcoming_events_block_my_upcoming_events.yml
- modules/social_features/social_group/config/install/block.block.views_block__newest_groups_block_newest_groups.yml
- modules/social_features/social_post/src/Form/PostDeleteForm.php
- modules/social_features/social_profile/config/install/block.block.views_block__newest_users_block_newest_users.yml
- modules/social_features/social_topic/config/install/block.block.views_block__latest_topics_default.yml
- Change visibility settings of homepage blocks from `<front>` to `/stream` in order to have ability create different home page
- Change redirect after post delete from `<front>` to `/stream`, as stream can be not always a homepage
> SSGT-157 by ribel: Change page settings in blocks config from <front> to /stream

- composer.json
See: https://www.drupal.org/node/2822309
I'm not sure what would be the side effect of using this patch with library version 0.7.3. But I guess if you would run composer update on your project it should automatically update to the latest version of commerceguys/intl as well.
> DS-2157: patch address module - fix installation error due to access level

- modules/social_features/social_core/config/install/block.block.socialbase_local_tasks.yml
Right now the local tasks are not shown to the Anonymous user. Developers should just be able to change permissions and tabs should be shown accordingly.
> DS-2157: add local tasks for anonymous user

- modules/social_features/social_follow_content/social_follow_content.install
Fix issue when there are some additional roles on the site:
`TypeError: Argument 2 passed to user_role_grant_permissions() must be of the type array, null given, called in /app/html/profiles/contrib/social/modules/social_features/social_follow_content/social_follow_content.install on line 31`
> SSGT-107 by ribel: Fix setting permissions to follow content when there are some additional roles

- composer.json
- drupal-org.make
- Fixed calling the cache in Group module.
Here the patch: https://www.drupal.org/node/2793621#comment-11753511
> DS-2292 by alex.ksis: Add patch to fix fatal error when uploading files

- themes/socialbase/templates/field/field.html.twig
When adding a link as header in the descriptive text of a book page: it is reflecting in the teaser.
> DS-2285 by ribel: Disallow <a> tags from body fields in teasers

- modules/social_features/social_group/social_group.install
- modules/social_features/social_search/social_search.install
Necessary to prevent system_update_8200 errors because of deleted modules. As you can see in release notes in beta4 https://www.drupal.org/project/social/releases/8.x-1.0-beta4 we ask to run updatedb twice. Lets try and prevent that for everyone updating from beta2 => beta5.
HTT:
Now try again with this branch by:
> DS-2298 by jaapjan: change order of update hooks 

- themes/socialbase/components/asset-builds/css/dropdowns.css
- themes/socialbase/components/components/dropdowns/dropdowns.scss
How to test: Replace any string in a dropdown with a very long string such as "Global Research Consortium on Economic Structural Transformation (GReCEST)" for the user dropdown in the navbar.
> SSGT-254 by maikelkoopman: truncate long names in user dropdown

- modules/social_features/social_core/social_core.module
1. Go to register / login / passreset and see that the secondary navbar is gone as on nightly_build.socialci.goalgorilla.com/user/login
2. See that when logging in everything is fine
3. See that when users for the Distro still want to add custom links to the menu, they will be rendered.
> DS-2331 Remove user local tasks for AN on user register/login/pass reset

- themes/socialbase/templates/form/fieldset--radios.html.twig
The story described the topic type field. Next to that one the visibility field had the same issue (although a value is preselected).
> DS-2183 by jochemvn: Add the required asterisk for required radio button

- modules/social_features/social_group/social_group.module
- modules/social_features/social_group/src/Plugin/Block/GroupHeroBlock.php
1. Added the same cache tag as on the hero block (see GroupHeroBlock.php) where it adds `$tags[] = 'group_block:' . $group->id();`
2. Created a new form submit to make sure that when users delete a member from a group, the `'group_block:' . $group->id();` is also cleared.
3. Also added the group_block to the common use case for clearing cache on adding / joining / leaving to make it consistent. 
4. Unfortunately the group patch in https://www.drupal.org/node/2753629 didn't work. Mainly because this patch re saves the group membership and in turn this invalidates the tags for group content instead of our group tags.
> DS-2185 Members counter is not updating after deleting a member

- modules/social_features/social_event/config/install/views.view.events.yml
- modules/social_features/social_event/config/install/views.view.upcoming_events.yml
- modules/social_features/social_event/social_event.module
- modules/social_features/social_event/src/Plugin/views/sort/EventPassedDesc.php
- modules/social_features/social_group/config/install/views.view.group_events.yml
- tests/behat/features/capabilities/event/homepage-community-events.feature
> DS-2074 by ribel: Add Views sort plugin for passed and upcoming events

- modules/social_features/social_book/config/install/core.entity_view_display.node.book.teaser.yml
A bit difficult to test, since in the theme it's already fixed in beta 7 and already the body text is no longer displayed. This story is basically a clean up, since we also don't want to send the body to the teaser if we're not going to display it.
> DS-2691 by jochemvn: Remove body from book teaser

- modules/social_features/social_event/modules/social_event_managers/social_event_managers.module
- tests/behat/features/capabilities/event-management/event-management.feature
See: https://www.drupal.org/node/2840421
Fixed it per your suggestion to implement the same hook as we do for the enrollments tab. Also added a regression test.
HTT:
> Issue #2840421 - (event) Managers tab is also shown on other content types

- modules/custom/entity_access_by_field/entity_access_by_field.install
- modules/custom/entity_access_by_field/entity_access_by_field.links.menu.yml
- modules/custom/entity_access_by_field/entity_access_by_field.module
- modules/custom/entity_access_by_field/entity_access_by_field.permissions.yml
- modules/custom/entity_access_by_field/entity_access_by_field.routing.yml
When public visibility is disabled for LU, the CM and SM should be able to override this.
> #2842079 - Override disabled public visibility

- modules/social_features/social_user/social_user.module
When registering on OS with an existing e-mail or username. A message states that that username or e-mail is already in use. In order not to directly disclose such data, a more general message is being show.
`Due to privacy concerns, the policy of this web site is not to disclose the existence of registered email addresses or usernames. However, if you entered an email address or username that already exists, you will not be able to continue. Please try again, or request a new password. Contact the site administrator if there are any problems.`
> #2842068 by jochemvn: Alter signup message for existing name or mail

- modules/custom/social_admin_menu/social_admin_menu.info.yml
- modules/custom/social_admin_menu/social_admin_menu.module
- modules/custom/social_admin_menu/social_admin_menu.services.yml
- modules/custom/social_admin_menu/src/Menu/SocialAdminMenuAdministratorMenuLinkTreeManipulators.php
Currently the admin menu contains a lot of broken links. This is due to issues:
https://www.drupal.org/node/296693
https://www.drupal.org/node/2673914
I think the solution I'm proposing is not the best solution, but it's a good start. I'm hiding some level 0 items to make sure it only contains items a certain role needs. In the future we need to make it a bit smarter and turn the logic around by showing only allowed items.
> DS-2431 - Social Admin Menu alterations

- modules/social_features/social_activity/config/install/message.template.create_comment_author_node_post.yml
- modules/social_features/social_activity/config/install/message.template.create_comment_post_profile.yml
- modules/social_features/social_activity/config/install/message.template.create_comment_reply.yml
- themes/socialbase/templates/views/views-view-unformatted--activity-stream-notifications--block.html.twig
See DS-2150
- 'Notification' should be renamed to 'Notification Centre' in navbar (dropdown)
- Email notifications that have been build so far, should also be in your Notification Centre
- If the person is currently active on the platform, he will only receive a notification in the Centre, and not via e-mail.
> DS-2150 Notification centre improvements

- themes/socialbase/socialbase.info.yml
See: https://www.drupal.org/node/2844611
This will fix the CKEditor since modals doesnt work. 
Solution is to extend the bootstrap modal library with our own implementation.
> 2844611 - Modals dont work after update to beta 9

- modules/social_features/social_event/config/install/views.view.upcoming_events.yml
- modules/social_features/social_event/modules/social_event_type/config/install/views.view.group_events.yml
- modules/social_features/social_event/modules/social_event_type/config/install/views.view.upcoming_events.yml
- modules/social_features/social_group/config/install/views.view.group_events.yml
- modules/social_features/social_group/config/install/views.view.group_topics.yml
- modules/social_features/social_profile/config/install/views.view.newest_users.yml
- modules/social_features/social_topic/config/install/views.view.latest_topics.yml
See https://www.drupal.org/node/2835114#comment-11858863
Topics that are posted in a group are presented twice in the group.
Login in as user1 I do not see the duplicated topics, but login in as a normal user (wether I am a member of the group or not) I do see them duplicated. Same goes for SM.
And one last thing, I also see duplicated events in the group. So not just topics.
Make sure there are no duplicates in the group overviews or in any of the streams (LU / Profile / Group stream), also check explore.
> #2835114 Group overviews & Blocks have duplicates

- modules/social_features/social_follow_content/config/install/flag.flag.follow_content.yml
- themes/socialbase/assets/css/badges.css
- themes/socialbase/assets/css/meta.css
- themes/socialbase/assets/css/teaser.css
- themes/socialbase/components/02-atoms/badges/badges.scss
- themes/socialbase/components/03-molecules/teaser/teaser.scss
- themes/socialbase/components/04-organisms/meta/meta.scss
- themes/socialbase/includes/node.inc
- themes/socialbase/templates/node/event/node--event--full.html.twig
- themes/socialbase/templates/node/node--full.html.twig
- themes/socialbase/templates/node/node--teaser.html.twig
- themes/socialblue/assets/css/badges.css
- themes/socialblue/components/02-atoms/badges/badges.scss
@MaikelGG Communication as per DS-2957: 
Please see if these changes have big impact on the enterprise themes. 
@ronaldtebrake Development as per DS-2955: 
**Likes count badge:** Can you guys see if we can extract the count of the like on that level? I can only manage to print the count inside the like_and_dislike template itself, not in the parent node--full template. I can only print the full widget there.
**Follow button:** Also the button should contain the text "follow content" instead of "follow".
**Date and location formatting:** Frank will let us know tomorrow if the current implementation of the design is feasible. If not (when looking at event_date and event_location strings) then we need a custom formatting function for both event_location and event_date to place the values in …
> DS-2956 - Implemented design for top of content detail pages.

- modules/custom/activity_creator/activity_creator.tokens.inc
- modules/social_features/social_activity/config/install/message.template.create_post_profile.yml
- modules/social_features/social_activity/config/install/message.template.create_post_profile_stream.yml
(make sure you updatedb / drush fra -y --bundle=social)
1. Login as Chrishall
2. In an incognito browser login as admin
3. go to /user/7/stream with both browsers
4. Place a post as Chrishall, see you still see the correct post on the activity stream
5. Place a post on chrishalls stream as admin, see you now have Admin > Chris Hall 
6. See that the notification in the centre & email still see "Admin posted on your profile" 
Also test this scenario: https://www.drupal.org/node/2851040
1. Click on the notification in the notification centre
2. Check that the notification is marked as 'seen' no more backgroudn color.
> DS-3010 - As a LU, I want to see an Arrow when I post on another users profile.

- modules/social_features/social_group/src/Plugin/Block/GroupAddBlock.php
- modules/social_features/social_user/src/Plugin/Block/AccountHeaderBlock.php
Related issue: [2852308](https://www.drupal.org/node/2852308)
When there is more than one group type available, the url to create a new group directs the user to an overview with group types.
> Issue #2852308 by frankgraave: adjust "new group" when there is more than one group type

- modules/social_features/social_like/social_like.tokens.inc
1. Create a post as Chrishall
2. Comment on this post as chrishall
3. Login as admin and like both the post_comment and the post
4. See that as chrishall you get a notification admin likes your comment and admin likes your post
5. Also check that for nodes you still see event/topic
> #2856934 - wrong notification text for comments on posts

- modules/social_features/social_mentions/config/install/message.template.create_mention_comment.yml
- modules/social_features/social_mentions/config/install/message.template.create_mention_comment_stream.yml
- modules/social_features/social_mentions/config/install/message.template.create_mention_post.yml
- modules/social_features/social_mentions/config/install/message.template.create_mention_post_stream.yml
- modules/social_features/social_mentions/social_mentions.module
- modules/social_features/social_mentions/social_mentions.tokens.inc
- tests/behat/features/capabilities/mention/mention-comment.feature
- tests/behat/features/capabilities/mention/mention-post.feature
As a LU, I want to see a logical sentence for all activity items (no more pronouns "you", but only username)
> DS-3189 by frankgraave: more logical scentence for activity items

- modules/custom/improved_theme_settings/improved_theme_settings.module
- modules/custom/social_font/social_font.module
- themes/socialblue/assets/css/brand.css
- themes/socialblue/components/02-atoms/brand/brand.scss
- themes/socialblue/theme-settings.php
Made sure all the modules now also accept socialsaas as option for the color palette and font / borderradius settings.
> DS-3164 Improved theme settings also for socialsaas

- themes/socialbase/templates/node/event/node--event--full.html.twig
Make sure the event location is shown when the address is empty
> Fix bug in event location display

- composer.json
- drupal-org-core.make
https://www.drupal.org/SA-2017-001
We could also consider merging to a separate branch, but considering the sprint is just started 8.x-1.x is still identical to 1.0.0-beta13
> Core update 8.2.7

- modules/social_features/social_post/social_post.module
- tests/behat/features/capabilities/like/like-post-stream.feature
- tests/behat/features/capabilities/mention/mention-post.feature
- tests/behat/features/capabilities/post/post-comments.feature
- tests/behat/features/capabilities/post/post-create.feature
- tests/behat/features/capabilities/post/post-group.feature
On home page and own profile: Say something to the community
On a group page: Say something to the group
On other profile: Leave a message to [name of the user]
> DS-2866 by ronaldtebrake: Change placeholder text for posts based on context

- modules/social_features/social_post/social_post.module
On home page and own profile: Say something to the community
On a group page: Say something to the group
On other profile: Leave a message to [name of the user]
On own profile: Say something to the community
> DS-2866 by frankgraave: Change placeholder text for posts based on context

- modules/social_features/social_core/social_core.install
- modules/social_features/social_core/social_core.module
- modules/social_features/social_event/config/install/views.view.upcoming_events.yml
- modules/social_features/social_group/config/install/views.view.group_members.yml
- modules/social_features/social_group/config/install/views.view.groups.yml
- modules/social_features/social_group/config/install/views.view.newest_groups.yml
- modules/social_features/social_profile/config/install/views.view.newest_users.yml
- modules/social_features/social_profile/social_profile.install
- modules/social_features/social_topic/config/install/views.view.latest_topics.yml
- modules/social_features/social_topic/config/install/views.view.topics.yml
- modules/social_features/social_topic/config/optional/block.block.exposedformlatest_topicspage_latest_topics.yml
- modules/social_features/social_topic/config/optional/block.block.socialblue_exposedformlatest_topicspage_latest_topics.yml
- modules/social_features/social_topic/social_topic.install
- modules/social_features/social_topic/src/Controller/SocialTopicController.php
- tests/behat/features/capabilities/group/group-create-open.feature
- tests/behat/features/capabilities/like/like-create-topic.feature
- tests/behat/features/capabilities/profile/hide-profile-email.feature
- tests/behat/features/capabilities/profile/newest-members.feature
- tests/behat/features/capabilities/topic/newest-topics.feature
- themes/socialbase/templates/block/block--views-block--sidebar.html.twig
_Because all these buttons will lead users to an overview where all the topics, groups and users will be shown. It is more logical to name the buttons also the page title in the way it is. So users don't have wrong expectations._
> DS-2905 by frankgraave: Rename 'see all' buttons in side blocks

- themes/socialbase/templates/file/file-link.html.twig
The file icon doesn't display on retina screen, because the src is missing the correct path.
> Correct path for retina version of file icon

- themes/socialbase/assets/css/layout.css
- themes/socialbase/components/05-templates/layout/layout.scss
1. Log in as admin after fresh install (no admin content) 
2. Go to profile page
3. Click topic in the secondary menu and see that the width of the page is just as wide as the window (as big as the content in it, apart from the menu that is full width)
> Issue #2845363 by peterpolman: Screen squeezed in a profile or a group

- themes/socialbase/includes/page.inc
Make sure you have a sitemanager, check that with this new code and the permission "use the administration toolbar" enabled.. site managers actually get the correct library attached. This library makes sure the social menu plays nicely with the admin toolbar.
> SaaS bug - where SM does not get zeh library attached

- social.profile
See: https://www.drupal.org/node/2873894
There are two little typos in our social.profile seen when installing Open Social through the UI.
> #2873894 by diamondsea, ronaldtebrake: updated typos 

- modules/custom/entity_access_by_field/entity_access_by_field.module
Problem: If the author edits his content (which was made public by a CM) the content is set to 'community' upon save.
Solution: Instead of hiding the public option, we disable it and we make sure we don't set the default_value on node edit anymore just on node add. This will ensure that a user knows what happens to their content, he can't change it back from public to community (he can still delete the content though) and the users with the correct permissions can actually do change it. 
1. Login as SM and set the visibility setting correctly at social.dev/admin/config/opensocial/visibility
2. Login as LU, create a new topic and see that you can't select the public visibility and community is enabled by default.
3. Login as SM and edit the node you just created, make sure you set it to …
> #2842079 visibility regression

- modules/social_features/social_user_export/social_user_export.module
**Some background:** In SaaS we alter the view so user1 is not shown here anymore. The custom count on the select all button then shows too many results. By using the amount on the already executed view we fix this.
> 2871729 by jochemvn: Fetch the amount of rows directly from the already executed view

- social.profile
Creation of demo content during UI installation is not working, see: https://www.drupal.org/node/2870066 
This is due to this pull request 
https://github.com/goalgorilla/open_social/pull/291 which refactors the demo content creation.
Solution is to move to this new Plugin system in social.profile so we support this during the (UI) installation as well.
HTT:
> Issue #2870066 by jaapjan: fix demo content via UI install

- modules/social_features/social_profile/social_profile.module
- modules/social_features/social_profile/src/Form/SocialProfileSettingsForm.php
> #2872565 by jochemvn: Make email privacy settings a bit more understandable

- modules/social_features/social_user/src/Plugin/Block/AccountHeaderBlock.php
https://www.drupal.org/node/2820234
it makes sense to check for access in these blocks. I've copied the code from this PR https://github.com/goalgorilla/open_social/pull/157 from @spuky and let's see what our test suite does.
> Issue #2820234 : Check for access in create content/groups links in header

- modules/social_features/social_post/src/Form/PostDeleteForm.php
This was added by @AntonMartyniuk in PR 
https://github.com/goalgorilla/open_social/pull/354
See Drupal issue for more context: https://www.drupal.org/node/2875275
The cancel button needs to redirect to a page the LU has access to. We should use the post/x/edit page or if the destination is already set we can use the destination provided in the url.
> Issue #2875275: redirect destination cancel button post form

- tests/behat/features/capabilities/group/group-create-open.feature
HTT:
This test was disabled because of issues in Travis. We forgot to remove the double step for when creating events in an Open Group
> by nielsvandermolen: Fix issue with the create open group Behat test

- modules/custom/improved_theme_settings/improved_theme_settings.module
- themes/socialbase/assets/css/admin-toolbar.css
- themes/socialbase/components/04-organisms/admin-toolbar/admin-toolbar.scss
> Admin toolbar bug fixes

- modules/social_features/social_group/social_group.info.yml
- modules/social_features/social_group/social_group.install
See:
https://www.drupal.org/node/2882738
I think it is safe to remove the dependency since the module should not be used anymore since the latest update anyway. I was not able to reproduce the issue reported though. I think it has to do with YAMLParser used and the commented lines in the .yml files in the grolesync module.
HTT:
> #2882738: Remove grolesync as dependency and uninstall

- modules/social_features/social_post/src/PostAccessControlHandler.php
- tests/behat/features/bootstrap/FeatureContext.php
- tests/behat/features/capabilities/group/group-create-closed.feature
Problem report:
Posts in a closed group where not accessible for other group members (other than the author) because there was no support for Visibility type "3". I've added support for this and added a lot of test steps to the Behat test including a custom one in FeatureContext.php which loops through all the group content and make sure the access is as expected. You can run the test and check with VNC viewer to make sure the output is expected.
HTT:
> DS-3763 - Make sure content is visible for group members in closed group

- modules/custom/social_file_private/social_file_private.services.yml
- modules/custom/social_file_private/src/SocialFilePrivateTextEditorConfigOverride.php
- tests/behat/config/behat.yml
- tests/behat/features/bootstrap/FeatureContext.php
- tests/behat/features/capabilities/security/private-file-uploads.feature
> DS-3731 - add support for private file uploads in WYSIWYG

- modules/custom/improved_theme_settings/improved_theme_settings.module
- themes/socialbase/assets/css/button.css
- themes/socialbase/components/02-atoms/button/button.scss
- themes/socialbase/includes/input.inc
- themes/socialbase/src/Plugin/Preprocess/BootstrapDropdown.php
- themes/socialbase/src/Plugin/Preprocess/InputButton.php
- themes/socialbase/templates/form/bootstrap-dropdown.html.twig
- themes/socialbase/templates/form/input.html.twig
- themes/socialbase/templates/system/table.html.twig
> Issue #2884358 by maikelkoopman: Set brand-primary class back on node save form

- modules/custom/social_demo/content/entity/topic.yml
- modules/custom/social_demo/src/Plugin/DemoContent/Topic.php
Original PR: #409 
Original issue: https://www.drupal.org/node/2884811
Fixed topic.yml field_topic_type values to be same as term names.
Changed prepareTopicType() function to work with term names.
- run demo content as usual.
- go to _admin/content_ and edit some Topic content.
- topic type should be selected.
> Issue 2884811 by kedramon: Demo Content for Topics needs topic type field selected

- modules/custom/social_demo/content/entity/topic.yml
- modules/custom/social_demo/src/Plugin/DemoContent/Topic.php
This issue is mentioned here: [https://www.drupal.org/node/2884811](https://www.drupal.org/node/2884811)
Fixed topic.yml field_topic_type values to be same as term names.
Changed prepareTopicType() function to work with term names.
- run demo content as usual.
- go to _admin/content_ and edit some Topic content.
- topic type should be selected.
> 2884811 Demo Content for Topics needs topic type field selected

- modules/custom/social_tour/js/social_tour.js
- modules/custom/social_tour/src/SocialTourController.php
**Original PR:** #412
**Original issue:** https://www.drupal.org/node/2884351
**Solution**:
Fixed redirect after tour has been disabled, removed hardcoded URL '/user' & added destination parameter for the '/user/tour/disable' URL.
**HTT**:
> Issue 2884351 by ozin: Fixed redirect after tour disable

- modules/custom/social_tour/js/social_tour.js
- modules/custom/social_tour/src/SocialTourController.php
**Original issue:** https://www.drupal.org/node/2884351
**Solution**:
Fixed redirect after tour has been disabled, removed hardcoded URL '/user' & added destination parameter for the '/user/tour/disable' URL.
**HTT**:
> Issue 2884351 by ozin: Fixed redirect after tour disable.

- .travis.yml
- modules/custom/activity_viewer/src/Plugin/views/filter/ActivityPostVisibilityAccess.php
The issue was that the ActivityPostVisibility always assumed that at least 1 group was available on the platform. This is not the case sometimes. The fixed conditions failed in those cases.
> #2884590 - No need to filter on groups in the stream when no groups exist in the platform (yet).

- modules/social_features/social_book/config/install/field.field.node.book.body.yml
> #2876613 - Make book node body field a non optional field 

- modules/custom/social_auth_extra/config/install/social_auth_extra.mail.yml
- modules/custom/social_auth_extra/social_auth_extra.install
- modules/social_features/social_user/src/Plugin/Block/AccountHeaderBlock.php
- tests/behat/features/capabilities/profile/hide-profile-email.feature
Edit account has been changed to Settings as per https://jira.goalgorilla.com/browse/DS-3620. This story can be reviewed after RC6.
> DS-3620 by jochemvn: Change 'edit account' into 'settings'

- modules/custom/social_auth_extra/social_auth_extra.module
- modules/social_features/social_user/social_user.module
**Description:**
Users signing up to the platform with one of the social authentication methods don't need to set their password after registering. Instead we will redirect these users to the edit profile page. In addition to this the social login buttons on the top of the register page were still shown after selecting one of the social authentication methods. This could be confusing to the user.
**Solution:**
Redirect users registering with social authentication to the user edit profile form. Hide the icons after the user is redirected from the selected authenticated method. The behaviour did not change for normal registrations.
I've used an unset in the form_alter. I think this is save since most of the logic is in separate Services anyways.
**How to test:**
> DS-3623 - Redirect LU Registering with Social Login To Edit Profile

- modules/social_features/social_core/social_core.install
See: https://www.drupal.org/node/2887361
HTT:
> Issue #2887361: account header block hidden in custom themes

- modules/social_features/social_group/social_group.module
Related issue: https://www.drupal.org/node/2875633
> Issue #2875633 by alex.ksis: Add a new cache context for group teasers

- modules/social_features/social_comment/social_comment.module
This code was rewritten a while back (an if then else to a switch). A default action was added to the switch statement to handle cases that were not handled in the previous if .. else situation. Another issue as tried to fix with redirecting after posting. The goto URL of the comment form in the stream would be: 'post/12/comment'. This was changed to the url of the stream '/'. This is an issue, because the 12 is needed to attach the comment to the correct post.
> #2888140 - Comments shows up in a wrong post in activity stream

- modules/social_features/social_event/config/install/views.view.event_enrollments.yml
Related issue: https://www.drupal.org/node/2889920
> Issue #2889920 by robertragas: Set events enrollments block pager to 12

- modules/social_features/social_mentions/src/Plugin/ActivityContext/MentionActivityContext.php
When replying on a comment you were mentioned in, you'd get a notification that someone (you yourself in this case) replied on a comment you were mentioned in. This is not really necessary to notify about, since you are probably aware of that fact that you (just) did this
> #2858502 by jochemvn: Don't send notifications of replies on mentions to the acting user himself

- modules/custom/activity_logger/activity_logger.tokens.inc
Full description of the issue here: https://www.drupal.org/node/2892737#comment-12157370
You can test it by checking out the stream on the nightly or on your local:
1. Login as chrishall
2. Check the democontent and see that when you hover over groups in activities it has a query parameter (?) behind it. 
3.Checkout this branch - Rerun the demo content and see that it works now. Or make sure a new activity get's aggregated so the token is created again.
> #2892737 by ronaldtebrake: Render token for message:gurl

- modules/social_features/social_core/src/Plugin/Block/SocialPageTitleBlock.php
- modules/social_features/social_group/social_group.module
Currently, when creating content in a group, the group hero is shown together with the Joined button. This button is really prominent and it is not relevant to the function of content creation page.
It causes confusion to users, and it makes the intention of the page unclear.
> DS-3034 by frankgraave: disable group hero block on create group content page

- modules/social_features/social_group/social_group.module
**Related issue:** https://www.drupal.org/node/2888005
> Issue #2888005 by frankgraave: hide the admin role upon adding user to open group

- themes/socialbase/includes/form.inc
**Description:**
When users try to save an event in some cases there is an error. Especially on mobile devices. This has to do with the validation of the date widget. Peter and I discussed and decided that the HTML5 validation is too device-specific for now and we determined to turn it off for all the forms. Our Drupal validation will catch any errors.
**How to test:**
Test in Xcode simulator and notice it works. Even though the widget says "12 July" it will still validate on save.
Notice that all the tests are green :-)
> Issue #2889883: novalidate on all forms

- modules/social_features/social_profile/social_profile.module
Since we implemented the private file system, anonymous users no longer have access to view profile pictures. So on pages where we show profile pictures, such as the stream. We need to check if the current user has access to the related file and if not, replace it with the default image, or hide the image entirely.
> #2893858 - Profile picture access

- modules/social_features/social_comment_upload/social_comment_upload.module
For description see: https://www.drupal.org/node/2890000
> #2890000 - When deleting a comment, also remove any attached files

- modules/social_features/social_swiftmail/social_swiftmail.module
When receiving an email from OS, only the system emailaddres is included. The sitename should we in there as well. This makes the emails more friendly.
Related issue: https://www.drupal.org/node/2895824
> Issue #2895824 by frankgraave: added mail alter to append the site name

- modules/social_features/social_core/config/install/core.entity_form_display.block_content.hero_call_to_action_block.default.yml
- modules/social_features/social_core/config/install/core.entity_view_display.block_content.hero_call_to_action_block.default.yml
- modules/social_features/social_core/config/install/crop.type.hero_an.yml
- modules/social_features/social_core/config/install/field.field.block_content.hero_call_to_action_block.field_hero_image.yml
- modules/social_features/social_core/config/install/image.style.social_an_hero.yml
- modules/social_features/social_core/social_core.install
The image style used for the AN Homepage Hero block was the same as for hero images on for example event pages. This is incorrect as the image on the AN homepage is wider than on event pages.
In order to fix this new a new image style and cropping configuration was made.
> DS-3949 by bramtenhove: Improve cropping and imagestyle for AN Homepage Hero block

- themes/socialbase/templates/post/post--activity-comment.html.twig
- themes/socialbase/templates/post/post--activity.html.twig
How to test:
- This bug only occurs when there is no comment in the stream yet.
- Log in as normal user
- Create a new group
- Post something in the group
- The comment form with this new post (only item in the stream) show only the icon on mobile and only the text on desktop (aka it loads the library)
> DS-3993 by maikelkoopman: include comment library in post template

- composer.json
- modules/custom/group_core_comments/group_core_comments.info.yml
Updated the following things: 
-  Drupal core to 8.3.6
- Dynamic entity reference to 1.4
- Override node options to 2.1
- Search API to 1.3
- Update manager no longer checks updates for group_core_comments. This is a contrib module so no need to check
> DS-4036 Distro maintenance

- modules/social_features/social_book/config/optional/block.block.booknavigation.yml
- modules/social_features/social_book/config/optional/block.block.booknavigation_2.yml
The sidebar first region only shows up if the complementary area's are empty. The table of content block from the book module is setup to ALWAYS show up in the complementary top area. This is changed, so it only shows up for books.
https://www.drupal.org/node/2901465
> 2901465 - Book table of contents should only show up for node type book

- themes/socialbase/assets/css/comment.css
- themes/socialbase/assets/css/like.css
- themes/socialbase/assets/css/modal.css
- themes/socialbase/components/00-config/_mixins.scss
- themes/socialbase/components/00-config/mixins/_ellipsis.scss
- themes/socialbase/components/03-molecules/like/like.scss
- themes/socialbase/components/04-organisms/comment/comment.scss
- themes/socialbase/components/04-organisms/modal/modal.scss
Test on mobile:
Run yarn install from the socialbase theme folder.
- On your gulpfile set the correct value on line 42 (options.drupalURL). eg: options.drupalURL = 'http://social.dev:32787'
Run `gulp watch`
You should see an external URL, use this url on your mobile device. 
The following things have changed:
Make sure icon to like and number of likes have enough space to tap on them:
> Follow up: improve see who liked content on mobile

- modules/social_features/social_profile/social_profile.module
Sometimes people choose to enable profile fields during registration. This leads to a user having 2 pofile after registration
https://www.drupal.org/node/2900630
> 2900630 - Prevent a user form having two profiles, if profile fields are already asked during registration

- modules/social_features/social_core/social_core.info.yml
- modules/social_features/social_event/social_event.info.yml
- modules/social_features/social_group/social_group.info.yml
- modules/social_features/social_post/social_post.info.yml
- modules/social_features/social_profile/social_profile.info.yml
- modules/social_features/social_search/social_search.info.yml
- modules/social_features/social_topic/social_topic.info.yml
- modules/social_features/social_user/social_user.info.yml
Using Drush to update features probably made it so that some features are now dependent on self. This is an issue as there is no way modules or features can ever be disabled.
It was fixed before, but reintroduced, see https://www.drupal.org/node/2761799.
> Issue #2761799 by bramtenhove: Social Search and other features are dependent on self

- tests/behat/features/capabilities/profile/hide-profile-email.feature
There were two behats excluded since January 2017. One (`DS-811`) was already fixed, but now only the `DS-2082` remains. I ran the test locally and it seems to be running just fine. However it seems to fail on Travis, I looked at the behat and rewrote a small part since we don't need to go to the user information by using `"/all-members"` and clicking an username in there (where the test seemed to fail on Travis). Instead we now use `"I am on the profile of "user"`, this should now not only work locally, but also on Travis of course. Related issue: https://www.drupal.org/node/2840680
1. Create a branch on the https://github.com/goalgorilla/open_social_scripts repo where the `DS-2082` test is no longer excluded from the `behatstability.sh` file. Checkout to this branch in the open_social …
> Issue #2840680 by frankgraave: fix the behat for profile privacy setting

- modules/social_features/social_comment/social_comment.module
Issue:
https://www.drupal.org/node/2907049
The bug is introduced in: https://github.com/goalgorilla/open_social/pull/448
HTT:
**Without social_comment_upload:**
**With social_comment_upload:**
> Issue #2907049 - fix posting comments without attachment

- modules/social_features/social_user/config/install/core.entity_form_display.user.user.default.yml
When a user h as the permission to change his/her timezone it does not show up on the user edit form. Let's add this field to the form display of account settings.
HTT:
> DS-4076: add timezone settings in user profile if enabled in settings

- modules/social_features/social_page/config/install/core.entity_view_display.node.page.search_index.yml
- modules/social_features/social_search/config/install/search_api.index.social_all.yml
- modules/social_features/social_search/config/install/search_api.index.social_content.yml
- modules/social_features/social_search/config/install/views.view.search_all.yml
- modules/social_features/social_search/social_search.install
When searching for content on the 'all' tab in OS, book pages and basic pages don't show up. This is now fixed.
https://www.drupal.org/node/2900982
> #2900982 - Search 'all' tab won't show pages and books

- modules/social_features/social_search/social_search.install
Issue https://www.drupal.org/node/2906090 was created after the 1.4 release. Apparently the social_search feature had an update hook containing drush commands. These work fine when updating via drush, but not if you use the interface.
See https://github.com/goalgorilla/open_social/pull/494 for the original pull request.
Easiest way is to fake the update system that there is a new update hook. For this change the number of `social_search_update_8103()` to `social_search_update_8104()`, etc.
> Issue #2906090 by bramtenhove: Remove drush dependency when updating to 1.4

- modules/social_features/social_event/config/install/core.entity_form_display.node.event.default.yml
- modules/social_features/social_group/config/install/core.entity_form_display.group.closed_group.default.yml
- modules/social_features/social_group/config/install/core.entity_form_display.group.open_group.default.yml
- modules/social_features/social_profile/config/install/core.entity_form_display.profile.profile.default.yml
- modules/social_features/social_profile/social_profile.module
- themes/socialbase/templates/field/address-plain.html.twig
> DS-4076 by bramtenhove: For address fields set the site default country as default value

- modules/social_features/social_comment/social_comment.tokens.inc
- modules/social_features/social_post/src/Entity/Post.php
This is a duplicate of #490 because it had issues with feature states even though this issue doesn't touch those features. This code has been reapplied to the tip of the 8.x-1.x branch (unfortunately, merging did not work correctly). Original issue follows.
When someone comments on a post that has no photo attached to it, the author gets a notification that someone commented on his/her photo. To make sure it fits both cases with and without photo, we've changed it back to 'post'
https://www.drupal.org/node/2894160
> #2894160 by jochemvn, Kingdutch: Change 'comment on a photo' into 'comment on a post'

- modules/custom/activity_viewer/activity_viewer.module
- modules/custom/activity_viewer/src/Plugin/views/filter/ActivityFilterPersonalisedHomepage.php
- modules/social_features/social_activity/config/install/message.template.create_comment_group_post.yml
- modules/social_features/social_activity/config/install/views.view.activity_stream.yml
- tests/behat/features/capabilities/activity-stream/activity-stream-comments.feature
- tests/behat/features/capabilities/activity-stream/create_topic_event.feature
Changes I've made:
- Created a custom filter which is designed especially for the homepage stream:
-- Shows nodes outside groups user has access to
-- Shows nodes inside groups user is a member of and has access to
-- Shows posts inside groups user is a member of
-- Shows posts outside groups and user has access to
-- Shows comments on nodes inside groups user is a member of
- Disabled comment on posts in group in the homepage stream since this clutters the homepage too much imho.
- Behat tests.
HTT:
> Issue #2839327 - personalised homepage

- modules/social_features/social_profile/social_profile.install
HTT
1. Create fictional users, around 50k would crash the update in the old situation. Now it should not.
> Issue #2906572 by robertragas : create profiles with batch

- modules/custom/improved_theme_settings/improved_theme_settings.module
- enable improved_theme_settings module
- Change value of border radius in theme settings
- Post button above activity streams should get the border-radius that is set in the form
> Issue #2907955  rounded corners on post button should be respected

- modules/custom/dropdown/src/Plugin/Field/FieldType/Dropdown.php
- modules/social_features/social_profile/social_profile.module
Put the following line in your local settings:
`$config['system.logging']['error_level'] = 'verbose';`
Log in as admin
You should get warnings like:
`Warning: array_flip(): Can only flip STRING and INTEGER values! in Drupal\Core\Entity\EntityStorageBase->loadMultiple() (line 227 of core/lib/Drupal/Core/Entity/EntityStorageBase.php).`
and 
`Notice: Undefined index: value in Drupal\dropdown\Plugin\Field\FieldType\Dropdown->isEmpty() (line 135 of profiles/contrib/social/modules/custom/dropdown/src/Plugin/Field/FieldType/Dropdown.php).`
on the home page / stream pages
Warnings should be gone
> DS-4194 - fix dev warnings

- modules/social_features/social_mentions/src/Controller/AutocompleteController.php
- modules/social_features/social_mentions/src/SocialMentionsConfigOverride.php
- modules/social_features/social_search/src/Form/SearchContentForm.php
The constants that were moved during previous coding standards fixes, were moved to the wrong class. This is now fixed. Besides that the search was not working since it had the wrong dependeny, also fixed.
> Maintenance - Bugfixes that were caused by coding standards

- modules/social_features/social_topic/src/Controller/SocialTopicController.php
- tests/behat/features/capabilities/topic/topic-overview.feature
The /all-topics page has a filter for topic type in the right sidebar. Select any topic type and click apply. This resulted in an error. Related issue: https://www.drupal.org/node/2914304
> Issue #2914304 by frankgraave: fixed the filter for the topic types

- modules/social_features/social_post/social_post.module
- themes/socialbase/templates/block/block--social-post.html.twig
The profile image next to the post box was sometimes malformed. We've solved this by moving the layout of this item into twig and out of the back-end code. This way the layout is fixed and not dependant on code execution!
https://www.drupal.org/node/2914807
> #2914807 Fix profile image issue next to post box in twig. Not in code

- tests/behat/features/capabilities/activity-stream/create_topic_event.feature
This behat had a weird step at the last section where CreateUser is creating an event inside an new open group, then SeeUser logs in and wants to click CreateUser. Instead I chose to make it:
And I am on the profile of "CreateUser" so that SeeUser doesn't have to click CreateUser (when it sometimes can't click for some reason).
> DS-4253 by frankgraave: make this behat more consistent

- composer.json
- modules/social_features/social_swiftmail/social_swiftmail.install
When sending emails as an admin, the theme used for the emails would be the admin theme.. This is now changed to the default theme.
> DS-3906 - Themed mails when send mails from admin theme

- modules/social_features/social_group/config/install/group.type.open_group.yml
- tests/behat/features/capabilities/activity-stream/create_topic_event.feature
- tests/behat/features/capabilities/group/group-create-open.feature
https://www.drupal.org/node/2900559
When creating a group, the Open Group option says "This is a open group. Users may join without approval and all content added in this group will be visible for non members as well."
Only LUs can see the Topics and Events, so when you say "non members" you're referring to the Group rather than to the community, which isn't immediately obvious. Perhaps to "This is an open group. Users may join without approval and all content added in this group will be visible to all community members."
> Issue #2900559 by Kingdutch: clarify content reach of open groups

- modules/social_features/social_group/config/install/views.view.groups.yml
https://github.com/goalgorilla/open_social/pull/596
https://www.drupal.org/node/2896185
When you visit 'my groups' on from your profile, the sorting order for the groups is ascending, where descending makes more sense
> 2896187 by valgibson: Reverted the sort order on my groups page

- modules/custom/improved_theme_settings/improved_theme_settings.module
- modules/custom/social_font/social_font.module
For new subthemes, after enabling it, colors can be changed, but the border-radius and font definitions cannot.
This is due to an explicit check in the `improved_theme_settings` and `social_font` modules.
Drupal issue: https://www.drupal.org/node/2907743.
> Issue #2907743 by slowflyer: Custom Font and border radius not working on subtheme

- .travis.yml
- travis-fail.sh
Currently, if the feature state is incorrect or the unit tests fail, the Behat tests will still run. This has a big impact on build time, in the end the job fails anyway.
Basically by adding `set -e` if one task exits with something other than `0` the rest of them are not run and the job fails. I also added `fast-finish`, although that won't do much at the moment.
In the future we will probably want https://github.com/travis-ci/travis-ci/issues/2062 as this allows us to cancel all the jobs if one fails. This comes with pros and cons, but in our case I think the pros outweigh the cons.
> DS-4398 by bramtenhove: Fail Travis job immediately if task fails

- themes/socialbase/src/Plugin/Preprocess/Page.php
- themes/socialbase/src/Plugin/Preprocess/SocialBasePage.php
- themes/socialbase/templates/layout/page.html.twig
As was described in https://www.drupal.org/node/2907221 there is no way to change content_attributes classes array as they are pre-populated in template.
All logic was moved to preprocess, so now user can alter in own theme this classes like this:
```
use Drupal\Core\Template\Attribute;
function THEME_preprocess_page(&$variables){
if ($variables['content_attributes'] instanceof Attribute) {
if (SOME_CONDITION) {
$variables['content_attributes']->removeClass('layout--with-complementary')
}
}
}
```
Also <section> is now in a twig block.
> Move content attribute classes to preprocess function

- themes/socialbase/src/Plugin/Preprocess/Page.php
- themes/socialbase/src/Plugin/Preprocess/SocialBasePage.php
- themes/socialbase/templates/layout/page.html.twig
As was described in https://www.drupal.org/node/2907221 there is no way to change content_attributes classes array as they are pre-populated in template.
All logic was moved to preprocess, so now user can alter in own theme this classes like this:
```
use Drupal\Core\Template\Attribute;
function THEME_preprocess_page(&$variables){
if ($variables['content_attributes'] instanceof Attribute) {
if (SOME_CONDITION) {
$variables['content_attributes']->removeClass('layout--with-complementary')
}
}
}
```
Also `<section>` is now in a twig block.
> Move content attribute classes to preprocess function.

- social.info.yml
Because we removed the project: social in social.info.yml the Composer-based Drupal installations never phoned home to drupal.org to do the update check. This has impact on the usage stats of d.o (which is why they are relatively low) and it has impact on the update status page because Open Social does not appear there even when you are running an older version.
Versions affected:
1.4 - 1.6
> Fix the project usage stats and update status of Open Social

- modules/social_features/social_event/config/install/field.field.node.event.field_event_date.yml
- modules/social_features/social_event/config/install/field.field.node.event.field_event_date_end.yml
- themes/socialbase/assets/css/form-elements.css
- themes/socialbase/components/03-molecules/form-elements/form-elements.scss
- themes/socialbase/src/Plugin/Preprocess/FormElementLabel.php
- themes/socialbase/templates/form/form-element-label.html.twig
- In user testing, it is shown that there is not indication at all on event start/end time.
- The label of the field should be changed to "End" and "Start" since the fieldset title already reflects that it's about the Event date AND time.
- Force labels to be shown on these event date fields
- Change labels by removing "date"
> DS-2976 by maikelkoopman: put labels above date fields

- modules/social_features/social_comment_upload/social_comment_upload.install
- modules/social_features/social_comment_upload/social_comment_upload.links.menu.yml
- modules/social_features/social_comment_upload/social_comment_upload.module
- modules/social_features/social_comment_upload/social_comment_upload.permissions.yml
- modules/social_features/social_comment_upload/social_comment_upload.routing.yml
- modules/social_features/social_comment_upload/src/Form/SocialCommentUploadSettingsForm.php
- modules/social_features/social_comment_upload/src/SocialCommentUploadConfigOverride.php
When enabled we cannot disable the comment upload feature. This is needed for our SaaS product
Added a settings form and a new permission for SM to disable this. Default it's always enabled. Also when the setting is disabled, it's no longer possible to add files to comments, nor is it possible to view them.
- https://jira.goalgorilla.com/browse/DS-4408
> DS-4408 - Add possibility to disable comments upload feature

- modules/social_features/social_user/src/Routing/RouteSubscriber.php
As a SM I want to use the default SaaS theme when I edit my profile
Set admin theme to false when editing your account (for all roles)
> DS-4471 by maikelkoopman: set socialblue as theme for SM+ user edit page

- themes/socialbase/assets/css/modal.css
- themes/socialbase/components/04-organisms/modal/modal.scss
jQuery dialog suddenly has a label next to the close button
Update CSS selectors to match update in jQuery UI
https://www.drupal.org/project/social/issues/2924082
> #2924082 by maikelkoopman: update css for jquery UI close button

- .travis.yml
by only running coding standards, unit tests and feature-state test when needed.
There is no reason to run the same coding standards, unit tests and feature-state test multiple times. This makes it harder to understand why certain jobs are failing in a specific build.
I suggest to only run:
- Coding standards 1 time in install_stability_1
- Unit tests 1 time in install_stability_1
- Feature state test in install_stability_1 and install_update.
- I checked quickly if there is a way to cancel jobs within a build if a job fails (e.g. if install_stability_1 fails lets just cancel all other jobs within that build). Does not seem possible.
- I think we should consider moving to a structure like this: https://docs.travis-ci.com/user/build-stages/ This would allow fast feedback for coding …
> Speed up Travis a little bit

- .travis.yml
Travis builds are taking forever and are becoming increasingly unreliable.
Change PHP to version 7.1 to increase speed. Also when running the update from 1.0 to `current_version`, only run the stability tests from the 1st group.
- All pull requests basically :(
> Move to PHP 7.1 and on install_update only run stability test from group 1 

- tests/behat/features/bootstrap/SocialMinkContext.php
Currently tests are quite difficult to find if you aggregate all
the CI screenshots in a centralised storage. We can tweak the names
slightly by adding today's date and by adding the name of the
feature that the screenshot corresponds to.
> Improve screenshot naming for failed behat tests

- modules/social_features/social_activity/config/install/message.template.create_comment_author_node_post.yml
- modules/social_features/social_comment/social_comment.tokens.inc
- modules/social_features/social_core/social_core.links.menu.yml
- modules/social_features/social_core/social_core.routing.yml
- modules/social_features/social_topic/config/install/core.entity_form_display.node.topic.default.yml
- modules/social_features/social_topic/config/install/field.field.node.topic.field_topic_type.yml
- modules/social_features/social_topic/config/install/views.view.latest_topics.yml
Also included a fallback in the message template for retrieving node bundle label for commented entities.
The field labels "Topic type" and field group titles "Topic description" and filter "Topic type" were too specific on platforms where the social_renamer is used. The social_renamer does not currently support the renaming of these items.
Propose to change this to a more generic names. See commit. In addition I've also found a way to retrieve the Node bundle's display name which can be used in the token in the comment message template.
- DS-4344
> DS-4344 by jaapjan: more generic terms for everything topics and message template

- modules/social_features/social_book/config/install/field.field.node.book.field_book_image.yml
- modules/social_features/social_core/social_core.module
- modules/social_features/social_event/config/install/field.field.node.event.field_event_image.yml
- modules/social_features/social_group/config/install/field.field.group.closed_group.field_group_image.yml
- modules/social_features/social_group/config/install/field.field.group.open_group.field_group_image.yml
- modules/social_features/social_page/config/install/field.field.node.page.field_page_image.yml
- modules/social_features/social_topic/config/install/field.field.node.topic.field_topic_image.yml
- themes/socialbase/README.md
- themes/socialbase/assets/css/image-widget.css
- themes/socialbase/components/03-molecules/form-elements/image-widget/image-widget.scss
- themes/socialbase/config/install/socialbase.settings.yml
- themes/socialbase/socialbase.info.yml
- themes/socialbase/socialbase.libraries.yml
- themes/socialbase/templates/file/file-upload-help.html.twig
Currently there is no image upload requirements shown next to the image upload field. The user doesn't know what sizes and images formats are allowed. Also the popover component with field_files does not work
- Change order of javascript for tooltip and popover (solves popover)
- Move description to crop the image to description field of images, so it can co-exist with upload requirements (previously in the form alter we removed it)
- Repeat above mentioned steps for creating and editing event, page, book page and profile
> DS-4123 by maikelkoopman: display popover with upload requirement

- themes/socialbase/assets/css/comment.css
- themes/socialbase/components/04-organisms/comment/comment.scss
When you click a link that goes to a comment (for example in an e-mail notification) then the top of the comment (its author) will be obscured by fixed navigation. This is because the anchor is moved to the top of the screen by the browser.
Add an offset to all comment anchors to compensate for the navigation. 
https://www.drupal.org/project/social/issues/2919653
> #2919653 Comment anchors obscured by main navigation

- modules/custom/social_demo/content/entity/user.yml
- modules/social_features/social_private_message/config/install/core.entity_form_display.private_message_thread.private_message_thread.default.yml
- modules/social_features/social_private_message/src/Plugin/Field/FieldWidget/SocialPrivateMessageThreadMemberWidget.php
- modules/social_features/social_profile/social_profile.module
- social.info.yml
- tests/behat/features/capabilities/private-message/create-private-message.feature
- themes/socialbase/templates/profile/profile--profile--hero.html.twig
- themes/socialbase/templates/profile/profile--profile--teaser.html.twig
I should be able to send a user private message directly from his/her profile without having to go first to my inbox. 
I should be able to send a user private message directly from teaser. 
Change one link in profile teaser, only when PM module is enabled.
Add button to profile hero, only when PM module is enabled
> LU should be able to send private message to a user from their profile.

- modules/custom/social_admin_menu/social_admin_menu.module
- modules/custom/social_admin_menu/src/Menu/SocialAdminMenuAdministratorMenuLinkTreeManipulators.php
After update from 8.x-1.7 to 8.x-1.8 the social_admin_menu causes an error using #pre_render.
Replaced #pre_render syntax with #lazy_builder
- https://www.drupal.org/project/social/issues/2930298
> removed #pre_render

- modules/social_features/social_tagging/config/install/taxonomy.vocabulary.social_tagging.yml
- modules/social_features/social_tagging/social_tagging.features.yml
- modules/social_features/social_tagging/social_tagging.info.yml
- modules/social_features/social_tagging/social_tagging.install
- modules/social_features/social_tagging/social_tagging.links.menu.yml
- modules/social_features/social_tagging/social_tagging.module
- modules/social_features/social_tagging/social_tagging.permissions.yml
- modules/social_features/social_tagging/social_tagging.routing.yml
- modules/social_features/social_tagging/social_tagging.services.yml
- modules/social_features/social_tagging/src/Form/SocialTaggingSettingsForm.php
- modules/social_features/social_tagging/src/SocialTaggingService.php
This is a new feature
Created a taxonomy where you can only go 2 levels deep (main items and sub items)
- https://jira.goalgorilla.com/browse/DS-4351
> DS-4351 - As SM I want to be able to administer the tags on the platform.

- themes/socialbase/templates/like/like-and-dislike-icons.html.twig
When using Open Social in Dutch the like counter shows 1 like when there are 0 likes. 
The main problem was that the plural-forms was not correct for the Dutch translation.
It was set to:
`"Plural-Forms: nplurals=2; plural=(n > 1);\n"`
And it should be:
`"Plural-Forms: nplurals=2; plural=(n != 1);\n"`
According to these specs: http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html?id=l10n/pluralforms Also we should include the amount of likes in the singular translation to accommodate for languages wo use the plural=(n > 1) setting.
- DS-4405
> DS-4405 - Fix singular translation for amount of likes

- modules/social_features/social_user/social_user.install
- modules/social_features/social_user/src/Form/SocialUserNavigationSettingsForm.php
- modules/social_features/social_user/src/Plugin/Block/AccountHeaderBlock.php
Using CMI with Open Social caused the following error:
`The import failed due for the following reasons:                         [error]
Configuration <em
class="placeholder">social_user_navigation.settings</em> depends on
the <em class="placeholder">social_user_navigation</em> extension
that will not be installed after import.`
Reason is that this particular piece of configuration now thinks it's part of a module called 'social_user_navigation'. This module does not exist.
Migrated settings from social_user_navigation to social_user.navigation. Now it's part of the social_user module.
- https://www.drupal.org/project/social/issues/2929208
> 2929208 - Migrate social_user_navigation.settings > social_user.navigation.settings

- modules/custom/improved_theme_settings/improved_theme_settings.install
- modules/custom/social_demo/eaa/content/entity/system.yml
- modules/custom/social_demo/src/DemoSystem.php
When updating form OS 1.7 to 1.8 with custom colors in your DEFAULT theme. The colors are not migrated. This causes the new settingsform not to load any of the color fields.
Migrate the settings in an update hook
> Create update hook to reset the existing theme setting colors to the new layout

- modules/custom/alternative_frontpage/alternative_frontpage.info.yml
- modules/custom/alternative_frontpage/alternative_frontpage.links.menu.yml
- modules/custom/alternative_frontpage/alternative_frontpage.routing.yml
- modules/custom/alternative_frontpage/alternative_frontpage.services.yml
- modules/custom/alternative_frontpage/config/install/alternative_frontpage.alternativefrontpagesettings.yml
- modules/custom/alternative_frontpage/src/EventSubscriber/RedirectHomepageSubscriber.php
- modules/custom/alternative_frontpage/src/Form/AlternativeFrontpageSettings.php
- modules/social_features/social_activity/config/install/views.view.activity_stream.yml
- modules/social_features/social_landing_page/config/install/core.entity_view_display.node.event.featured.yml
- modules/social_features/social_landing_page/config/install/core.entity_view_display.node.landing_page.default.yml
- modules/social_features/social_landing_page/config/install/core.entity_view_display.node.landing_page.teaser.yml
- modules/social_features/social_landing_page/config/install/core.entity_view_display.node.topic.featured.yml
- modules/social_features/social_landing_page/config/install/field.field.node.landing_page.field_content_visibility.yml
- modules/social_features/social_landing_page/config/install/field.field.paragraph.block.field_block_reference.yml
- modules/social_features/social_landing_page/config/install/field.field.paragraph.block.field_block_reference_secondary.yml
- modules/social_features/social_landing_page/config/install/field.storage.paragraph.field_block_reference.yml
- modules/social_features/social_landing_page/config/install/field.storage.paragraph.field_block_reference_secondary.yml
- modules/social_features/social_landing_page/config/install/views.view.community_activities.yml
- modules/social_features/social_post/modules/social_post_photo/src/Plugin/Block/PostPhotoBlock.php
- modules/social_features/social_post/modules/social_post_photo/src/Plugin/Block/PostPhotoGroupBlock.php
- modules/social_features/social_post/modules/social_post_photo/src/Plugin/Block/PostPhotoProfileBlock.php
- modules/social_features/social_post/social_post.views.inc
- modules/social_features/social_post/src/Plugin/Block/PostBlock.php
- modules/social_features/social_post/src/Plugin/Block/PostGroupBlock.php
- modules/social_features/social_post/src/Plugin/Block/PostProfileBlock.php
- modules/social_features/social_post/src/Plugin/views/area/SocialPostPostForm.php
- social.info.yml
- tests/behat/features/bootstrap/SocialDrupalContext.php
- tests/behat/features/capabilities/alternative-frontpage/alternative-frontpage.feature
- themes/socialbase/src/Plugin/Preprocess/Block.php
Anonymous and logged-in users frontpages are currently not very flexible. It is virtually impossible to feature content. It would be an option to be able to use the landingpage feature for this since it will give the SM the possibility to create a visually appealing site and feature content, groups.
The landingpage can not be set as the homepage on "/stream" currently since it will add new blocks automatically. Actually when using a landingpage it should not add any blocks to the hero, content area or sidebars. 
DS-4638
https://www.drupal.org/project/social/issues/2931507
> DS-4637 - Use Landingpage as replacement of homepage

- modules/social_features/social_private_message/src/Plugin/Block/PmAddBlock.php
When looking at the Private Message functionality everything is written out full, so I search for "Private Message". I have no easy way of knowing that for the "Private Message Add Block" we suddenly use the abbreviation "PM". We should just write it out in full.
We should probably also do this for the class names and ids but if we've already marked this module as stable then that would break backwards compatibility. If we haven't marked the module as stable yet it's a change still work making.
This single line change has no Drupal.org issue associated with it.
> Don't use an abbreviation for the PmAddBlock

- modules/custom/activity_send/src/Plugin/SendActivityDestinationBase.php
- modules/custom/download_count/download_count.module
- modules/custom/mentions/mentions.module
- modules/custom/social_demo/src/DemoComment.php
- modules/custom/social_demo/src/DemoNode.php
- modules/custom/social_demo/src/DemoSystem.php
- modules/custom/social_demo/src/DemoTaxonomyTerm.php
- modules/custom/social_demo/src/DemoUser.php
- modules/custom/social_demo/src/Plugin/DemoContent/EventEnrollment.php
- modules/custom/social_demo/src/Plugin/DemoContent/Like.php
- modules/custom/social_font/social_font.install
- modules/social_features/social_private_message/social_private_message.services.yml
- modules/social_features/social_private_message/src/Service/SocialPrivateMessageService.php
As REQUEST_TIME deprecated, usage of this constant should be replaced by @datetime.time service.
Replaced the REQUEST_TIMEs with the new service.
- https://www.drupal.org/project/social/issues/2939961
- More info: https://www.drupal.org/node/2785211
> Issue #2939961 by kala4ek: replace deprecated constant REQUEST_TIME

- modules/custom/activity_creator/activity_creator.module
- modules/custom/activity_creator/src/ActivityFactory.php
- modules/custom/activity_logger/activity_logger.tokens.inc
- modules/custom/activity_send/modules/activity_send_email/src/Plugin/ActivityDestination/EmailActivityDestination.php
- modules/custom/activity_send/modules/activity_send_email/src/Plugin/EmailFrequency/Immediately.php
- modules/custom/activity_send/modules/activity_send_email/src/Plugin/QueueWorker/ActivityDigestWorker.php
In the activity stream it is currently not possible to have the message displayed in the language of the user. If an user has selected the Dutch language or is visiting the Dutch website the notification is still shown in English (e.g. "User x created an event in group Y").
In emails there is a similar problem, but other texts are also not translated in the language of the recipient user.
Translating the message template text upon **display** of the item. Basically this means we retrieve the message template and generate the output text (with tokens replaced) on an entity view. And the same happens when sending notifications in emails.
_As an added bonus I fixed the URL in email notifications for groups. This was, as far as I could tell, the only item which was using a relative URL (which …
> DS-4491 activity stream multilingual

- modules/social_features/social_group/src/Form/SocialGroupAddForm.php
Group type labels and group type descriptions are not translatable.
Enable translations of this texts.
https://jira.goalgorilla.com/browse/DS-4765
> DS-4765 Interface translations should work for configuration

- themes/socialbase/templates/post/post--activity-comment.html.twig
- themes/socialbase/templates/post/post--activity.html.twig
- themes/socialbase/templates/post/post.html.twig
Custom fields not showing up in custom post type
In template replace exact fields to print with all fields to print. Then exclude the fields that are printed on other places in the template
https://www.drupal.org/project/social/issues/2921723
- This doesn't include theming of course. If a developer add new fields, they need to add theming for it in a subtheme.
> #2921723 by maikelkoopman: show custom fields for posts by default

- modules/custom/activity_send/modules/activity_send_email/activity_send_email.module
Private message email notification configuration not rendered.
Add the key value to the list, but needs a more flexible solution to see if all items from $email_message_templates are assigned to a category.
https://www.drupal.org/project/social/issues/2938779#comment-12445743
> 2938779 by robertragas: Add key value of private message notification

- modules/social_features/social_core/social_core.module
This is a copy of the original pullrequest #727 and the issue can be found here: https://www.drupal.org/project/social/issues/2944419
If you use a custom content type (not provided by Open Social) and happens to have a long name, the validation above will fail because machine names can only be 26 characters long.
In order to at least have the possibility of having an image set, new code needs to load an image field as hero, as long as it has the word "image" on its field name and it is an image field.
I've written code to handle this special case
Created the issue directly on GitHub
> #2944419 - Hero images for custom content types when machine name is too long

- modules/social_features/social_search/config/install/search_api.index.social_all.yml
When you search for a user in the "All" tab then a user name bears no more importance than other content (that might be published by this user). This causes the user searched for to end up on the last page of "Search All". This was experienced by one of our enterprise clients.
Boost the username importance from 1 to 2. This ensures that if a user is matched in a "Search All" search it is displayed first. (User)names are usually quite unique and when searched for they are usually the goal (if searching for an article, other terms would be used). Therefor having any users come up first in a query has probably no or little downside and a lot of upside
https://www.drupal.org/project/social/issues/2939371
> Issue #2939371 by Kingdutch: Boost user names in all search

- modules/custom/entity_access_by_field/entity_access_by_field.module
Fail to build inline form for an entity with a field for controlling visibility.
Check if a referenced entity has a field for controlling visibility.
https://www.drupal.org/project/social/issues/2935632
> InvalidArgumentException: Field field_content_visibility is unknown. in Drupal\Core\Entity\ContentEntityBase->getTranslatedField() (line 509 of /var/www/html/core/lib/Drupal/Core/Entity/ContentEntityBase.php).
> 2935632 Fail to build inline form for an entity with a field for controlling visibility

- modules/social_features/social_post/social_post.module
This patch was delivered by Namzhilma Zhambalova in https://www.drupal.org/project/social/issues/2940839
When creating a custom view with URL '/group/%group/photos' with posts you will see the mentioned warning. It is also reproducible by going to /admin/group/types/manage/open_group/permissions as user 1.
Check if the group is an id or a Group object, if it's an id load the group before calling the hasPermission() method.
- https://www.drupal.org/project/social/issues/2940839
> Issue #2940839 : Call to a member function hasPermission() on string in social_post_comment_create_access()

- modules/social_features/social_tagging/social_tagging.module
When social tagging is enabled and you create a topic from a group Topics overview page you will see this error:
`The website encountered an unexpected error. Please try again later.
Error: Call to a member function bundle() on null in social_tagging_form_node_form_alter() (line 116 of profiles/contrib/social/modules/social_features/social_tagging/social_tagging.module).`
The bug was introduced in https://github.com/goalgorilla/open_social/pull/706 so no reason to create a new bugreport on d.o just yet.
Find a better way to retrieve the node_type. There is no reason to depend on the route parameters when you can get the node object from the form state directly.
- https://github.com/goalgorilla/open_social/pull/706
> Issue #2936748 : prevent warning when adding node from group page with tagging

- modules/social_features/social_group/social_group.tokens.inc
When you create a post in the group, the notifcation mail that is being sent has a malformed link to the 'post' entity.
Fix the link of the post entity to its canonical
- https://www.drupal.org/project/social/issues/2937077
> 2937077 by jochemvn: Make sure 'post' link works when sending group messages

- modules/custom/activity_send/modules/activity_send_email/activity_send_email.module
In #702 we introduced a bug that when the module private message is not enabled there would be a Notice on the account settings form:
`Notice: Undefined offset: 9 in activity_send_email_form_user_form_alter() (line 146 of /var/www/html/profiles/contrib/social/modules/custom/activity_send/modules/activity_send_email/activity_send_email.module) `
Add a check to make sure the module exists and the key of the messages.
- N/A, but you can see pullrequest #702 
No changes needed since it was already added to the release notes and this bug is solved before the release.
> Issue #2938779 - add the PM e-mail notification setting only when module is enabled

- modules/social_features/social_post/src/Form/PostForm.php
- tests/behat/features/capabilities/group/group-create-public.feature
Posts in public group are not public.
I've improved the way we retrieve the visibility options for all the groups by using the re-usable `function social_group_get_allowed_visibility_options_per_group_type($group_type_id);` to retrieve all the allowed visibilty options for the given group type. Because I rewrote the code a bit it makes sense to test all the group types.
- https://www.drupal.org/project/social/issues/2937659
> Issue #2937659 : post in a public group should always have public visibility

- composer.json
- drupal-org-core.make
- social.info.yml
Security update for Drupal core 8.4.5 is out, but we're on 8.4.4.
Update Drupal Core to 8.4.5.
> DS-4880 - Update to Drupal 8.4.5

- modules/social_features/social_profile/social_profile.module
With Social Private Files turned on the profile images are saved in the private files folder. This works ok, but for some display modes the profile image is not replaced by the default image.
When it is not replaced with the default image a request is done for the normal image. But this one is not accessible and thus results in a missing image.
The check is currently on `compact` and `compact_notification` display modes. However we already have `small_teaser` display mode and possibly more in the future.
By adding a check for the `field_profile_image` being used in a display mode, instead of checking for specific display modes this is easily solved.
- https://www.drupal.org/project/social/issues/2949101
> #2949101: Fix missing profile images for anonymous visitors

- modules/social_features/social_user/social_user.install
- modules/social_features/social_user/social_user.permissions.yml
- modules/social_features/social_user/social_user.routing.yml
SocialUserNavigationSettingsForm uses the 'administer site configuration' permission. We don't want to give this permission to the SM since it has side effects.
This needs to be made a custom permission so it can be given to SMs.
- https://www.drupal.org/project/social/issues/2925751
> Issue #2925751: add custom permission for administering navigation

- modules/custom/activity_send/modules/activity_send_email/activity_send_email.install
- modules/custom/activity_send/modules/activity_send_email/activity_send_email.module
- modules/social_features/social_like/config/install/message.template.create_like_node_or_post.yml
User settings page does not have a field for controlling e-mail notification which you received when someone liking your post, comment, etc.
Implement possibility to control e-mail notifications about liking my stuff.
- https://www.drupal.org/project/social/issues/2925592
- https://jira.goalgorilla.com/browse/DS-4477
> 2925592 Disable e-mail notifications of people liking my comments

- modules/social_features/social_user_export/src/ExportUser.php
The social_user_export module gives the ability to export all users over all pages on /admin/people. The code for that functionality is in src/ExportUser.php. It uses the uid to determine the next user to export in the batch. However this does not work when the view query is already altered in another hook. 
Let's use the offset method instead.
- https://www.drupal.org/project/social/issues/2950391
> Issue #2950391 by jaapjan: user export should use offset method instead

- modules/social_features/social_group/config/install/field.field.group.closed_group.field_group_address.yml
State field is not available for Closed Group Location field.
Let's add it to the field.field.group.closed_group.field_group_address.yml file.
- https://www.drupal.org/project/social/issues/2950411
> Issue #2950411 by jaapjan: make state field available for closed group location

- modules/social_features/social_landing_page/templates/profile--featured.html.twig
- modules/social_features/social_mentions/templates/profile--profile--autocomplete_item.html.twig
- themes/socialbase/templates/profile/profile--profile--compact_teaser.html.twig
- themes/socialbase/templates/profile/profile--profile--hero.html.twig
- themes/socialbase/templates/profile/profile--profile--medium_teaser.html.twig
- themes/socialbase/templates/profile/profile--profile--small_teaser.html.twig
- themes/socialbase/templates/profile/profile--profile--table.html.twig
- themes/socialbase/templates/profile/profile--profile--teaser--anonymous.html.twig
- themes/socialbase/templates/profile/profile--profile--teaser.html.twig
There are multiple places with code `{{ profile_name|render }}`. Render filter in twig templates is useful for if statements, but it's redundant in normal output cases.
It could cause issues like this if you want for example use tags in username output: http://prntscr.com/imrp67
Remove not needed `|render` filter after profile_name in twig templates.
Profile names with additional tags will look like this after that: http://prntscr.com/imrowl
- https://www.drupal.org/project/social/issues/2949847
- https://jira.goalgorilla.com/browse/ECI-691
```
function user_hooks_test_user_format_name_alter(&$name, $account) {
if (\Drupal::state()
->get('user_hooks_test_user_format_name_alter', FALSE)) {
if (\Drupal::state()
->get('user_hooks_test_user_format_name_alter_safe', FALSE)) {
$name = …
```
> Issue #2949847 by ribel: Remove not needed |render filters in twig templates

- social.profile
Drupal Core has the awesome inline form error module which makes it much easier to notice within a form which form elements need direct attention.
Let's enable it for all new Open Social instances but leave it like it is for existing distro & enterprise installs.
As @left23 pointed out already:
1. Inline form errors are not visible until the form is being sent. HTML5 errors come before Inline Form Errors and this may cause confusion.
2. Loss of uniform and exhaustive error representation. Some elements have HTML5 validation and others don’t.
- DS-4503
> DS-4503: enable inline form errors for new installs

- modules/custom/activity_creator/js/notifications.js
- modules/social_features/social_user/src/Plugin/Block/AccountHeaderBlock.php
- modules/social_features/social_user/templates/account-header-links.html.twig
- themes/socialbase/assets/css/dropdown.css
- themes/socialbase/assets/css/navbar.css
- themes/socialbase/components/03-molecules/dropdown/dropdown.scss
- themes/socialbase/components/03-molecules/navigation/navbar/navbar.scss
- themes/socialblue/assets/css/brand.css
- themes/socialblue/assets/css/dropdown.css
- themes/socialblue/assets/css/navbar.css
- themes/socialblue/assets/css/preview.css
- themes/socialblue/components/03-molecules/dropdown/dropdown.scss
- themes/socialblue/components/03-molecules/navigation/navbar/navbar.scss
- themes/socialblue/components/brand.scss
Currently, on small screens such as iphone 5, the header menu becomes 2 rows which takes a lot of space for mobile user and the menu looks 'broken'. 
Also for enterprise team, when the add google translate icon to the header menu, on mobile the space is not enough, even for large phones. 
When the screen is small, such as iphone 5, the user menu should become a dropdown menu. 
When there is new notification for private message or notificaiton center, the dropdown icon will reflect there is new things unread. 
There should not be a configuration interface to decide which icon will be in dropdown on mobile. (We only take care of the icons provided in distro, not other customised icons.)
https://jira.goalgorilla.com/browse/ECI-702
> ECI-702 by serhiy-chornobay: Make the user menu like dropdown on mobile

- themes/socialbase/templates/private_message/field--private-message-thread--members.html.twig
The names are all on a new line, they should be on a single div, comma, seperated
Fix template for private-message-thread--members.
- https://jira.goalgorilla.com/browse/ECI-706
> ECI-706: Fix template for private's message members

- modules/social_features/social_activity/config/install/views.view.activity_stream_notifications.yml
The title of the "Notifications" page (/notifications) is now "Activity Stream". 
I think this is due to the configuration yml having being copied and these strings were overlooked
Title should be "Notifications" 
https://www.drupal.org/project/social/issues/2931336
> Issue #2931336 replace string for page title and config description

- modules/social_features/social_activity/config/install/message.template.create_comment_group_node.yml
- modules/social_features/social_activity/config/install/message.template.create_comment_group_post.yml
- modules/social_features/social_activity/config/install/views.view.activity_stream_group.yml
- tests/behat/features/capabilities/activity-stream/activity-stream-comments.feature
The problem is that there is a lot of duplicate information when people comment on a post in a group stream.
Hide all activities about the commented post on group stream page.
https://jira.goalgorilla.com/browse/DS-4886
> DS-4886 As a LU I want to see a clear activity stream without duplicate info regarding posts + comments

- themes/socialbase/assets/css/form-controls.css
- themes/socialbase/components/02-atoms/form-controls/_input.scss
Event date and time field has gradient on mobile on iOS. This is default behaviour but is inconsistent with the design.
For iOS temporal fields only, set appearance to none, and add background svg icons to indicate it is a select element
https://www.drupal.org/project/social/issues/2925994
> Issue #2925994 temporal fields ios

- .travis.yml
Currently forks don't run automated tests due to the nature of the .travis.yml file where we hardcore `goalgorilla/open_social` as repo name.
By setting the forked repository as a Composer git repo we can overwrite the goalgorilla/open_social package which is pulled in and build.
Also we adjusted the commit has and branch as these are different for PR's.
> DS-4680 -Allow Travis CI test for forked repositories

- modules/social_features/social_post/src/Form/PostForm.php
When the entitybundle is NULL the id() method shouldn't be used.
Let's make this code a bit more defensive by adding a check for NULL.
- https://www.drupal.org/project/social/issues/2930174
> Issue #2930174: Fatal error: Call to a member function id() on NULL

- themes/socialbase/templates/profile/profile--profile--hero.html.twig
The text "Edit profile information" in the profile hero is not translatable currently.
Let's make it translatable with Twig!
- https://www.drupal.org/project/social/issues/2948237
> Issue #2948237: "Edit profile information" is not translatable

- modules/custom/social_auth_extra/social_auth_extra.module
When users have Russian names the automated generation of a username after signup with social network does not work.
Use the `transliterate` method from Drupal Core.
https://www.drupal.org/project/social/issues/2941204
```
<?php
use Drupal\bootstrap\Utility\Unicode;
// After patch.
$names = [
'Александр Альберт',
'Jochem van Nieuwenhuijsen',
];
foreach ($names as $name) {
echo "INPUT: " . $name . "\n";
// Translate to lowercase and remove unnecessary symbols.
$name = Unicode::strtolower($name);
$name = \Drupal::transliteration()->transliterate($name);
$name = str_replace('  ', ' ', $name);
$name = preg_replace('/[^0-9a-z]/si', '_', $name);
echo "OUTPUT: " . $name . "\n";
}
echo "< BEFORE PATCH: > \n\n";
foreach ($names as $name) {
echo "INPUT: " . $name . "\n";
// Translate to lowercase …
```
> Issue #2941204: Incorrect username when registering via social networks

- modules/custom/social_admin_menu/social_admin_menu.module
Originally reported by @Kingdutch 
PHP Error in Social admin Menu when social_admin_menu is enabled.
We have to "nuke" the array.
https://www.drupal.org/project/social/issues/2954924
> Issue #2954924: lazy_builder in social_admin_menu_toolbar_alter causes DomainException

- themes/socialbase/templates/node/event/node--event--small-teaser.html.twig
Socialbase theme breaks quick edit
Add attributes for node small teasers
- https://www.drupal.org/project/social/issues/2956419
> DS-5265 Socialbase theme breaks quick edit

- modules/social_features/social_group/src/Plugin/Field/FieldWidget/SocialGroupSelectorWidget.php
Checks for moving content between groups can be improved.
The access checks have been improved for when there is just a single group type available on the site.
- DS-5279
> DS-5279 by Kingdutch, bramtenhove: Better checks for moving content between groups

- themes/socialbase/assets/css/block--informblock.css
- themes/socialbase/assets/js/informblock.min.js
- themes/socialbase/components/03-molecules/blocks/block--informblock/block--informblock.scss
- themes/socialbase/components/03-molecules/blocks/block--informblock/informblock.js
- themes/socialbase/socialbase.libraries.yml
- themes/socialbase/templates/block/block--gdpr-consent.html.twig
The new [GDPR inform & consent module](https://github.com/goalgorilla/gdpr_consent) is blank of styling by default. But for Open Social we require it to have styling that fits the Distribution.
Added a custom template and styling for the Inform blocks provided by the module.
> DS-4891 by bramtenhove: Add default styling for the GDPR inform block

- modules/social_features/social_mentions/js/social_mentions.js
The Mentions highlighter does not respond (well) to resize events for the textarea. With multiple rows the visual indicator disappears.
Adding the autoresize trigger for the textarea field means it again listens to resize events. From there the original code picks it up just fine.
- https://www.drupal.org/project/social/issues/2964627
> Issue #2964627 by Kingdutch, bramtenhove: Makes sure Mentions highlighter responds to textarea resize events

- modules/social_features/social_post/modules/social_post_photo/config/install/core.entity_view_display.post.photo.default.yml
On post detail page the image does not enlarge when clicking on it.
Because there is a double `a` the library does not work. Remove that link to the image and it should work.
- https://www.drupal.org/project/social/issues/2962434
> Issue #2962434: Not able to click on a post image on the post detail page

- modules/social_features/social_landing_page/src/Plugin/Field/FieldWidget/BlockFieldWidget.php
We received feedback that the changed names for the landing pages blocks do not reflect their function very well. See #798.
Changes the names for the blocks to what is suggested in the issue tracker.
- https://www.drupal.org/project/social/issues/2965041
> Issue #2965041 by bramtenhove: Change landing page block names to better reflect their function

- modules/social_features/social_landing_page/config/install/core.entity_view_display.profile.profile.featured.yml
- modules/social_features/social_landing_page/templates/profile--featured.html.twig
Whenever you feature users in the landing page, the picture links to the profile entity rather then the user entity. In OS we don't really user the profile page.
Make sure we don't link the profile picture to the entity and make a link in the template to the user
- https://www.drupal.org/project/social/issues/2960382
- https://jira.goalgorilla.com/browse/ECI-738
> #2960382: Make features profiles in landing page link to the user not the profile

- modules/custom/activity_creator/activity.page.inc
- themes/socialbase/src/Plugin/Preprocess/Activity.php
I have the fatal error after creating messages (notifications):
```
Error: Call to undefined method Drupal\Core\StringTranslation\TranslatableMarkup::toString() in Drupal\socialbase\Plugin\Preprocess\Activity->preprocess() (line 28 of profiles/contrib/social/themes/socialbase/src/Plugin/Preprocess/Activity.php).
```
See: https://www.drupal.org/project/social/issues/2956971
As I see, `$variables['date'] `will have different types - string or object, which needs special methods before rendering.
The patch from the current issue creates `$variables['date']` with renderable data.
- https://www.drupal.org/project/social/issues/2956971
> Issue #2956971: TranslatableMarkup::toString - undefined function

- modules/social_features/social_topic/config/install/core.entity_form_display.node.topic.default.yml
On platforms with a lot of users, the select list with an unordered list of users just isn't usable.
We have a great entity_reference_autocomplete widget that's already in use on the following content types: Book, Event, Landing Page, Basic Page
However it's not in use on the following content type: Topic
https://www.drupal.org/project/social/issues/2961977
> Issue #2961977 by Makishima: Use autocomplete widget for topic authored by field

- modules/social_features/social_landing_page/social_landing_page.module
- modules/social_features/social_landing_page/templates/field--paragraph--field-hero-buttons.html.twig
When creating a landing page with a hero and adding buttons to that hero. If you create a button that is only visible for logged in users then when anonymous users view the page there is still a field-item output with a few spaces. In some cases (for example 3 long buttons with 1 "inaccessible button" in between) this can cause an unnecessary overflow.
Add checking if item.content is empty
- https://www.drupal.org/project/social/issues/2956718
> Issue #2956718: Unavailable links in landing page hero still produce output

- modules/social_features/social_post/src/PostAccessControlHandler.php
`PostGroupBlock` placed at the pages like this `group/[group-id]/anything` cause the error:
> Error: Call to a member function hasPermission() on string in Drupal\social_post\PostAccessControlHandler->checkCreateAccess() (line 135 of profiles/contrib/social/modules/social_features/social_post/src/PostAccessControlHandler.php).
Replace direct execute of `\Drupal::routeMatch()->getParameter('group');` by `_social_group_get_current_group();`
- https://www.drupal.org/project/social/issues/2950337
> #2950337 by kala4ek: checkCreateAccess failed at PostAccessControlHandler

- modules/custom/social_gdpr/social_gdpr.module
For users it is useful to know when the data policy was updated and to receive a clear message about it.
Added a status message that the policy was updated.
- DS-5174
> DS-5174 by chmez, bramtenhove: Add message that policy is updated

- modules/social_features/social_post/src/Form/PostForm.php
When editing a post that was placed on a user's timeline the value for the field_recipient_user gets lost. This causes the activity that's displayed on the users stream to display the [activity:field_activity_recipient_user_display_name] token because the activity_creator_tokens has no value to replace it with.
Ensure the post edit form doesn't change values that are not exposed to the editing user.
https://www.drupal.org/project/social/issues/2962077#comment-12595445
When editing a post that was placed on a user's timeline, the user context is gone when saving. This causes the activity that's displayed on the users stream to display the [activity:field_activity_recipient_user_display_name] token since it did not understand what user information to replace it with.
> Value for post recipient get lost

- modules/social_features/social_user/social_user.module
When a user posted in the stream and then cancels his account the tokens are no longer being replaced correctly.
This is part one of the solution, basically creating a fallback for when these "empty" author tokens cannot be replaced by normal token hooks.
Part two of the solution involves some more work, which is defining hooks for cancel accounts and assigning content for several entities (e.g. activities or messages) to for example the anonymous user. This is a follow-up.
- DS-5049
> DS-5049 - Set a default for "empty" author tokens in stream posts when it cannot be replaced

- themes/socialbase/assets/css/comment.css
- themes/socialbase/components/04-organisms/comment/comment.scss
When you click a link that goes to a comment (for example in an e-mail notification) then the top of the comment (its author) will be obscured by fixed navigation. This is because the anchor is moved to the top of the screen by the browser.
Extend styles for comment anchors as are for node comments.
- https://www.drupal.org/project/social/issues/2960310
> Issue #2960310: Post comment anchors obscured by main navigation

- themes/socialbase/assets/css/cards.css
- themes/socialbase/assets/css/ckeditor.css
- themes/socialbase/components/02-atoms/cards/cards.scss
Embedding for example youtube in the stream goes full width because in the templates it gets wrapped in the class "iframe-container".
When embedding the same url within a content-type using the media embed then it will not get the class resulting in not being 100%.
In the spirit of being consistent I think these 2 should have the same behaviour.
Dublicate styles for iframe in card body
- https://www.drupal.org/project/social/issues/2952190
Iframes (and media objects) in nodes are now full-width as well, just like in posts.
> Issue #2952190: Social Embed iFrame width consistency

- themes/socialbase/assets/css/base.css
- themes/socialbase/assets/css/ckeditor.css
- themes/socialbase/assets/css/hero.css
- themes/socialbase/assets/css/nav-tabs.css
- themes/socialbase/assets/css/teaser.css
- themes/socialbase/components/04-organisms/hero/hero.scss
There is the bug with vertical alignment for text in hero banner.
Set height for bannet text only for IE11
..
> IE11 by serhiy-chornobay: Fix styles for hero in IE11

- modules/social_features/social_group/social_group.install
- modules/social_features/social_group/social_group.module
- modules/social_features/social_group/src/Plugin/Block/GroupAddEventBlock.php
- modules/social_features/social_group/src/Plugin/Block/GroupAddTopicBlock.php
- modules/social_features/social_group/src/Plugin/Field/FieldWidget/SocialGroupSelectorWidget.php
- modules/social_features/social_post/src/PostAccessControlHandler.php
See issue: https://www.drupal.org/project/social/issues/2972959
When public visibility is disabled we need to make sure that users can not create public groups, public content in public groups anymore. I've added all the necessary access hooks and made sure that public groups are not shown for LU anymore in the create content group selector widget.
- https://www.drupal.org/project/social/issues/2972959
> Issue #2972959: disable public group permissions when public visibility is turned off

- modules/custom/social_demo/content/entity/event.yml
- modules/custom/social_demo/content/entity/group.yml
- modules/custom/social_demo/content/entity/page.yml
- modules/custom/social_demo/content/entity/topic.yml
- modules/custom/social_demo/content/entity/user.yml
- modules/custom/social_demo/eaa/content/entity/book.yml
- modules/custom/social_demo/eaa/content/entity/event.yml
- modules/custom/social_demo/eaa/content/entity/group.yml
- modules/custom/social_demo/eaa/content/entity/page.yml
- modules/custom/social_demo/eaa/content/entity/topic.yml
- modules/custom/social_demo/eaa/content/entity/user.yml
- modules/custom/social_demo/src/DemoContent.php
- modules/custom/social_demo/src/DemoGroup.php
- modules/custom/social_demo/src/DemoSystem.php
- modules/custom/social_demo/src/DemoUser.php
- modules/custom/social_demo/src/Plugin/DemoContent/Book.php
- modules/custom/social_demo/src/Plugin/DemoContent/Event.php
- modules/custom/social_demo/src/Plugin/DemoContent/Page.php
- modules/custom/social_demo/src/Plugin/DemoContent/Topic.php
Images alternative text is not present in demo content
1. Check demo content module and add alternative text for all images.
2. Change demo content parser for this alternative text values
- https://www.drupal.org/project/social/issues/2975731
- https://jira.goalgorilla.com/browse/ECI-686
> Issue #2975731: Add alt text to demo content images

- modules/social_features/social_profile/social_profile.module
Currently the admin/people overview does not make a distinction between the edit account page and the edit profile page. On the account settings form you can edit the username, e-mail and user's settings. On the edit profile page you can edit the profile information including the first name, last name and organisation.
A site manager now has to click on the profile first and then on the pencil to edit the profile and this breaks the flow since the ?destination=admin/people is not added to the link.
Add the "Edit profile" link to the operations and change the current edit link title to "Edit account".
- https://www.drupal.org/project/social/issues/2975745
> Issue #2975745 : Add possibility to edit profile directly from People overview

- social.profile
Page Cache and Dynamic Page Cache modules are not enabled by default for Open Social. Enabling them instantly gives a better site performance.
Enable the two modules on install.
- https://www.drupal.org/project/social/issues/2975145
> #2975145 by bramtenhove: Enable Page Cache and Dynamic Page Cache by default

- modules/social_features/social_profile/src/Plugin/EntityReferenceSelection/UserSelection.php
When enabling the social_profile_fields module, searching on nickname in entity references does not work.
The new created entityreference for users is now updated with the nickname field (if it exists)
- https://jira.goalgorilla.com/browse/SHN-96
This entityreference is now using a selectQuery instead of a entityQuery (which is normal for an entityreference). We need to reconsider this approach. One of the issues is that you cannot change this query with a hook_query_alter for instance. (the query is overriden)
> SHN-96: Make sure the user entityreference also works with nickname

- modules/custom/sitewide_js/sitewide_js.module
The sitewide JS doesn't render the output raw
Make sure JS is outputted as raw
- https://www.drupal.org/node/2920717
> 2920717 by jochemvn, bramtenhove: Fix SitewideJS module

- modules/social_features/social_core/src/Plugin/Block/SocialPageTitleBlock.php
- tests/behat/config/behat.yml
- tests/behat/features/capabilities/landing-page/landing-page-as-404.feature
When a landing page is used as a 404 or 403 page then the page title block is shown but this conflicts with landing page's own heroes.
Let the page title block check if it's being rendered in a 404 or 403 context that uses a landing page.
- https://www.drupal.org/project/social/issues/2976549
Landing pages can now be used to retain users on Page not found pages!
> Issue #2976549 by Kingdutch, bramtenhove, robertragas: Page title block should not be shown on landing page 404 or 403 pages

- tests/behat/features/bootstrap/SocialDrupalContext.php
Got this warning when running tests:
`Interacting directly with the RawDrupalContext::$user property has been deprecated. Use RawDrupalContext::getUserManager->getCurrentUser() instead.`
Use RawDrupalContext::getUserManager->getCurrentUser() instead.
- OSSUPPORT-904
> OSSUPPORT-904: Use RawDrupalContext::getUserManager->getCurrentUser() 

- modules/social_features/social_embed/social_embed.services.yml
- modules/social_features/social_profile/modules/social_profile_fields/src/SocialProfileFieldsOverride.php
HTT:
Login as LU on the SaaS environment
Go to `node/add/topic`
Click on the Embed button
Note that nothing happens
Apparently this happens when some other modules are enabled with the same config override priority. E.g. `SocialMentionsConfigOverride`
I've increased the priority of this module's configoverrides. 
- DS-5713
> DS-5713:make sure embed for LU works for all combinations of modules

- modules/social_features/social_activity/config/install/message.template.create_comment_group_node.yml
- tests/behat/features/capabilities/activity-stream/activity-stream-comments.feature
Currently when someone comments on a node in the group this is not showing in the activity stream of that group. This is not correct and it should always display in the group stream.
In https://github.com/goalgorilla/open_social/pull/803/files this template was also changed:
message.template.create_comment_group_node.yml this was a mistake and that change should be reverted.
- https://www.drupal.org/project/social/issues/2976036
> #2976036 - Add comment on node in group to activity stream (again)

- modules/custom/activity_send/modules/activity_send_email/activity_send_email.module
The digest selects digest items based on if their timestamp has passed (for example) 24 hours. This is not correct as it should just select anything available.
Simply remove the check on timestamp.
- https://www.drupal.org/project/social/issues/2932250
> #2932250 by bramtenhove: Remove the interval check for items in the daily digest

- modules/social_features/social_activity/config/install/views.view.activity_stream_group.yml
- modules/social_features/social_activity/config/install/views.view.activity_stream_notifications.yml
- modules/social_features/social_activity/config/install/views.view.activity_stream_profile.yml
Pagers are not consistent across the activity streams.  There are currently 2 different pagers on 5 'stream' pages:
- group stream
- profile stream
- explore stream
- homepage stream
- all notifications (stream)
Homepage and explore have the 1 button 'older items', while the other 3 still have a numbered pager. 
I suggest we change the all notifications, group and profile to use the same pager as the 2 other pages.
- https://www.drupal.org/node/2840694
> Issue #2840694: update activity stream pager types to mini pagers

- themes/socialbase/assets/css/block--informblock.css
- themes/socialbase/components/03-molecules/blocks/block--informblock/block--informblock.scss
The text is currently aligned to the center. This is not looking very nice.
Text is now aligned to the left as it should be.
https://www.drupal.org/node/2976351
> #2976351: Make the text align to the left for the inform block text

- modules/social_features/social_landing_page/config/install/core.entity_view_display.node.page.featured.yml
- modules/social_features/social_landing_page/social_landing_page.module
- modules/social_features/social_landing_page/templates/node--landing-page--featured.html.twig
Landing pages had no image if you'd feature them in a landing page. Pages did have an image, but it was not clickable
Featured landing pages will now try to use the image of the first hero section (if available) and render that image with the correct link. Also featured images of pages now have a link to the content.
- https://www.drupal.org/project/social/issues/2942350
- https://jira.goalgorilla.com/browse/OSSUPPORT-493
- https://jira.goalgorilla.com/browse/ECI-799
When you add a featured block to a landing page, now when you choose to feature another landing page, the first hero section image will be used as the image in the featured section. 
When you feature a page, the featured image is now clickable and leads to the page content item.
> 2942350: Pages and Landing page as featured in landing pages

- tests/behat/features/bootstrap/SocialMinkContext.php
Getting lot's of errors related to this on Shippable builds. The directory does not exist. So it throws errors like this:
`Warning: file_put_contents(/var/www/travis_artifacts/20180627-05_33_27-enroll-for-an-event-error.jpg): failed to open stream: No such file or directory in /var/www/html/profiles/contrib/social/tests/behat/features/bootstrap/SocialMinkContext.php line 58`
Let's make this code a bit more defensive and check for the directory before trying to save the screenshot.
- n/a
> Only create Travis screenshots if the directory exists

- composer.json
- drupal-org-core.make
Drupal Core 8.5.5 is just out!
Updated to 8.5.5. Composer goes automatically, but it is important for the .make files.
> DS-5716: Update Drupal core to 8.5.5 [2.x]

- composer.json
- drupal-org-core.make
Drupal Core 8.5.5 is just out!
Updated to 8.5.5. Composer goes automatically, but it is important for the .make files.
See https://github.com/goalgorilla/open_social/pull/942 for 2.x branch.
> DS-5716 by bramtenhove: Update Drupal core to 8.5.5 [1.x]

- modules/social_features/social_core/config/optional/block.block.socialblue_local_actions.yml
The local actions block is displayed on admin/reports. In some cases (analytics) a sidebar second is being rendered, but only if both complementary area's are empty. Since this block was always rendered, those blocks were never considered empty
Make sure the block is not rendered on admin/reports pages
- https://www.drupal.org/project/social/issues/2936738
- https://jira.goalgorilla.com/browse/DS-4662
- https://jira.goalgorilla.com/browse/SHN-141
The Primary admin actions block is always shown in the 'Complementary Top' region. Most of the times it's empty and that's the issue. Some pages use the 'Sidebar first' and 'Sidebar second' layout. However when there are blocks shown in the 'Complementary Top', the 'Sidebar Second' region will not show up. We’ve made sure to have great default …
> 2936738: Make sure the local actions block is not displayed on admin/reports pages

- modules/social_features/social_comment/social_comment.module
String "Add a comment" can be translated but the translation is not shown.
Add the placeholder text with t() around it as is done at other places in the same function.
- https://www.drupal.org/project/social/issues/2984864
The translation for the  placeholder text at the comment form for nodes was not shown. We made sure the placeholder text passes the translation function.
> Issue #2984864 by bramtenhove: Fix untranslatable string at comment form

- themes/socialblue/color/css/preview-base.css
On preview and theme settings pages, buttons text color is different as on site.
Fix styles for buttons text color in preview-base.css
- https://jira.goalgorilla.com/browse/DS-5802
> DS-5802 by serhiy-chornobay: Fix links color for preview pages

- composer.json
- drupal-org.make
- modules/social_features/social_group/social_group.install
- modules/social_features/social_group/social_group.module
- modules/social_features/social_group/src/Controller/SocialGroupListBuilder.php
The content manager is able to edit and delete groups. However, due to the Group module not having granular permissions the overview was not reachable for that role.
This made managing groups harder for the content manager.
There is a patch from the Group module that introduces a new permission to visit the group overview page. This has been granted to the CM and SM roles.
Next to that I took the opportunity to make the Group overview a bit more useful by removing the Group ID and introducing the numbers of members as well as the creation date.
Also I made these columns sortable!
- https://jira.goalgorilla.com/browse/DS-5502
The group overview page is now accessible for the Content Manager role. The overview is also improved as the number of members and creation date are now in there. You …
> DS-5502 - Group overview available for Content Manager

- themes/socialbase/assets/css/dropdown.css
- themes/socialbase/assets/css/modal.css
- themes/socialbase/components/04-organisms/modal/modal.scss
The Bootstrap update to 3.11 breaks the Data Policy revert button in the modal
Fix styles for modal buttons
- https://www.drupal.org/node/2982250
The data policy revert button was not visible anymore due to a update in the Bootstrap theme. We updated the styles and the revert button functions again as it is supposed to.
> #2982250: Fix styles for modal buttons

- modules/social_features/social_profile/src/SocialProfileTrait.php
With the social_profile_fields module enabled and the nickname people enabled it's not possible to mention people based on their nickname
Make sure you can mention people based on their nickname
- https://www.drupal.org/project/social/issues/2985342
With the social_profile_fields module enabled and the nickname people enabled it's now possible to mention people based on their nickname.
> 2985342 by jochemvn: Make sure mentioning works with the nickname field

- modules/custom/mentions/mentions.module
- modules/social_features/social_comment/social_comment.install
- modules/social_features/social_comment/src/Form/SocialCommentAdminOverview.php
- modules/social_features/social_comment/src/Routing/RouteSubscriber.php
Currently both the content manager and site manager do not have access to the comment overview page. However they are able to edit and delete comments.
It would be much more useful if you had access to the comment overview page.
Grant access to content manager and site manager to access the comment overview page.
Make the comment overview page a bit more useful by removing the _Subject_ and _Posted on_ columns. Also added more buttons as well as showing the actual comment text in the table for quick access.
- https://jira.goalgorilla.com/browse/DS-3488
The comments overview page is now accessible for the Content Manager and Site Manager roler. The overview is also improved as the comment text is now in there. The default columns 'subject' and 'posted on' have been removed.
> DS-3488 - Comment overview available for CM and SM

- modules/social_features/social_group/social_group.module
- modules/social_features/social_group/src/Plugin/Field/FieldWidget/SocialGroupSelectorWidget.php
Content types with the group field (mostly accidental, or upgrades), didn't check if the content type was installed in the group. When trying to add such a content type in a group you'd get a WSOD 
Make sure the group widget only shows group types that are have the current content type installed
- https://www.drupal.org/project/social/issues/2965655
The group field would in some cases appear on node add/edit screens of content types that are not installed in the group type. Would you then select a group and submit, it would crash because of a `Pluginnotfoundexception`. 
This fix makes sure the widget checks if the current content type is installed in any of the group types. If not, the group type and all of its groups are removed from the widget.
> 2965655 by jochemvn: Make the group widget check for installed plugins.

- modules/social_features/social_profile/social_profile.module
Editing profile from profile admin page results in WSOD
If the account cannot be retrieved from the URL, we assume the owner of the profile.
- https://www.drupal.org/project/social/issues/2885189
- http://drupal.org/node/2988074
Editing a profile from the profile admin overview resulted in a WSOD. This fix makes sure you can now also edit someone's profile from that admin page.
> 2988074 by jochemvn: Add fallback way to get the account

- modules/social_features/social_core/social_core.install
In this [PR](https://github.com/goalgorilla/open_social/pull/916) we updated to the latest version of r4032login. Settings file was changed in this module, but there was no update hook. I've compared an Open Social install which had r4032login installed before this update and looked at the settings in the module. There are two settings missing:
* redirect_to_destination
* destination_parameter_override
I've created an update hook which adds the default value of these settings IF they are missing.
- DS-5827
In Open Social installations with the r4032login module enabled which were installed before the beta version of this module did not have the correct settings. The r4032login module did not supply an update hook for this. This caused some redirects after user login to not work anymore. …
> DS-5827 by jaapjan: update r4032login settings for destination parameter

- themes/socialbase/templates/comment/links--comment.html.twig
- themes/socialbase/templates/system/links.html.twig
The 'v' button for edit and delete my own post is not positioned correctly.( only if Big Pipe module is enabled)
Fix templates for comment actions block
- https://jira.goalgorilla.com/browse/DS-5892
> DS-5892 by serhiy-chornobay: Fix position for comment actions

- tests/behat/features/capabilities/landing-page/landing-page-create.feature
The following tests are failing sometimes, ordered by # of occurrences:
- landing-page-create 
- create-private-message
- topic-download-test
Added `@javascript` tag to make sure there is full javascript support for the test.
Will follow
Will follow
- DS-5768
> DS-5768 - Fix false negative Behat test: Landing-page-create

- modules/social_features/social_private_message/src/Plugin/UserExportPlugin/UserAnalyticsPrivateMessage.php
- modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserAnalyticsCommentsCreated.php
- modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserAnalyticsEventEnrollments.php
- modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserAnalyticsGroupsCreated.php
- modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserAnalyticsLikes.php
- modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserAnalyticsPostsCreated.php
- modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserAnalyticsTopicsCreated.php
- modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserProfileTag.php
- modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserRoles.php
- modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserSelfIntroduction.php
The self introduction field can be useful for measuring community activity. We did not include it in the [other PR](https://github.com/goalgorilla/open_social/pull/987) that introduces a lot of new fields to the export.
Added the _Self introduction_ to the export and changed the weights of the plugins so it fits nicely somewhere at the end.
The output of the _Self introduction_ field is automatically escaped, just like the rest of the fields. This means that links and images are stripped. I don't think this is an issue.
- https://www.drupal.org/project/social/issues/2990176
n/a
> Issue #2990176 by bramtenhove: Add self introduction as field to the export

- modules/custom/activity_logger/activity_logger.tokens.inc
- modules/social_features/social_activity/config/install/message.template.create_comment_author_node_post.yml
- modules/social_features/social_activity/config/install/message.template.create_comment_reply.yml
- modules/social_features/social_activity/config/install/message.template.create_content_in_joined_group.yml
- modules/social_features/social_comment/social_comment.tokens.inc
- modules/social_features/social_follow_content/config/install/message.template.create_comment_following_node.yml
- modules/social_features/social_group/social_group.tokens.inc
- modules/social_features/social_like/config/install/message.template.create_like_node_or_post.yml
- modules/social_features/social_like/social_like.tokens.inc
- modules/social_features/social_mentions/config/install/message.template.create_mention_comment.yml
- modules/social_features/social_mentions/social_mentions.tokens.inc
See full overview here:
https://docs.google.com/spreadsheets/d/16NdIBG8GZXaXQV5YpCfp17yKm7RshArRs_goKZNlU5E/edit?usp=sharing
Not clear about which topics/events/groups etc the notification is about.
If we know the title of the node, let's show it in the (e-mail) notification.
- DS-5933
Will follow.
> DS-5933 by jaapjan: add more context to e-mails

- modules/social_features/social_group/src/Plugin/Field/FieldWidget/SocialGroupSelectorWidget.php
When creating content that uses the group selector widget (EG: topic/event) an error occurs. A value is being passed through in the form. This should be done slightly different, to make sure the form doesn't think it's a key it should render.
Create a 'value' #type, which the form renderer does not try to render. 
- https://www.drupal.org/project/social/issues/2990496
The HTT of #969 still applies here:
Fixed error "standard_default" is an invalid render array
> 2990496 by jochemvn: Better passthrough of variable in the form (static)

- modules/social_features/social_profile/src/Plugin/EntityReferenceSelection/UserSelection.php
If you want to select yourself in a Entity reference selecter you get filtered out. Imagine for example wanting to select yourself as an Event organizer. It got filtered out as part of #884 where it never was a requirement as far as I can tell.
By removing the filter from the User EntityReferenceSelection the current logged in user is not filtered out anymore. This also makes sure it becomes available for private message & mentions. Added benefits here is that sending yourself a private message works well and has its use cases (sending yourself an reminder). Mentions work as well but the need for this is not that clear for me so we might be able to fix this in a follow up. 
- https://www.drupal.org/node/2989176
It is now possible to find yourself when you are searching for users in an …
> Issue #2989176 : Can't select myself in user reference fields / mentions

- modules/social_features/social_event/src/Plugin/Block/EventAddBlock.php
- modules/social_features/social_group/src/Plugin/Block/GroupAddBlock.php
- modules/social_features/social_group/src/Plugin/Block/GroupAddEventBlock.php
- modules/social_features/social_group/src/Plugin/Block/GroupAddTopicBlock.php
- modules/social_features/social_post/src/Plugin/Block/PostGroupBlock.php
- modules/social_features/social_topic/src/Plugin/Block/TopicAddBlock.php
The "Add a group", "Add topic" and "Add event" Button show allways up on the related page of the user profile, even if the user has no permission to create the related group/content.
Added related permission to check if block is displayed or not
- https://www.drupal.org/project/social/issues/2989731
> Issue #2989731 : Added related "Create" permissions for block display

- modules/social_features/social_search/social_search.install
- modules/social_features/social_search/social_search.module
Blocked users are still in the search results (on All and on Users tab). This is happening because the change is in the User entity while the Profile entity is being indexed.
When the user entity is updated, let's trigger a re-index of the related Profile entity. In some cases we need to add or remove the Profile from the index.
- https://www.drupal.org/project/social/issues/2992979
-See old (related) PR: https://github.com/goalgorilla/open_social/pull/854
Blocked users were still showing up in search results. When a user is blocked they should never be in the search results.
> Issue #2992979 : Blocked users should NOT be in the search

- modules/social_features/social_profile/modules/social_profile_fields/src/SocialProfileFieldsOverride.php
The SocialProfileFieldsOverride class adds the field_profile_nick_name to the group_profile_names_image group. However, if that group is not present then the override will cause a group with malformed properties to be created which crashes the field_group module.
This makes it impossible for a user to edit their profile.
Only override the configuration if the field is actually present.
- https://www.drupal.org/project/social/issues/2991128
Removing the Names and Profile Image (group_profile_names_image) field group with the social_profile_fields module enabled would make the user profile uneditable. This has been fixed by checking for the group's existence before overriding the configuration.
>  Issue #2991128 by Kingdutch: Check that the group_profile_names_image field_group exists before overriding.

- tests/behat/features/capabilities/group/group-edit-content-in-group.feature
There is currently a race condition in the group-edit-content-in-group.feature between selecting the discussion and the AJAX request for changing a group which could undo that selection.
To fix it the order is changed so the topic type is selected first and is included in the pre-AJAX state so the race condition is avoided.
- https://www.drupal.org/project/social/issues/2994271
> Fix race condition in group edit content test

- themes/socialblue/assets/css/brand.css
- themes/socialblue/assets/css/preview.css
- themes/socialblue/components/brand.scss
External Social Vote module can't use theme settings colours.
Add styles for Social Vote module in socialblue brand styles.
See: https://prnt.sc/kl3oym
- https://jira.goalgorilla.com/browse/FOR-101
> FOR-101 by serhiy-chornobay: Fix brand color for Social Vote widget

- tests/behat/features/bootstrap/FeatureContext.php
- tests/behat/features/capabilities/alternative-frontpage/alternative-frontpage.feature
- tests/behat/features/capabilities/event-management/event-management.feature
- tests/behat/features/capabilities/group/group-create-public.feature
- tests/behat/features/capabilities/post/post-comments.feature
- tests/behat/features/capabilities/post/post-create.feature
- tests/behat/features/capabilities/post/post-photo-create.feature
Behat tests are not generic enough
Use given more so we don't depend on demo content. Also added a new function where you can call the css in a certain region.
We improved the behat tests by making the steps more specific, making it less dependent on a certain set of demo content.
> by robertragas: make behat tests more generic

- themes/socialblue/assets/css/button.css
- themes/socialblue/assets/css/cards.css
- themes/socialblue/assets/css/ckeditor.css
- themes/socialblue/assets/css/like.css
- themes/socialblue/assets/css/preview.css
- themes/socialblue/components/02-atoms/cards/cards.scss
Socialblue centers the titles on cards that are on the default stream. This style does not apply when those same blocks are placed on a stream that is built in a landing page.
Ensure that the styling applies to both equally.
- https://www.drupal.org/project/social/issues/2992753
When creating a stream on a landing page the informational blocks such as "New groups" now look the same as they do on the default Open Social streams.
> Issue #2992753 by Kingdutch: landing page block styling

- modules/social_features/social_group/social_group.install
- modules/social_features/social_group/social_group.module
- tests/behat/features/capabilities/post/post-group.feature
In PR #994 a default statement was added to make sure custom group types have all the visibility settings giving distro users more flexibility. However as you can see in the switch statement open_group wasn't covered in this scenario. This meant that "public" became an option in the visibility selector for Posts in streams for open groups and "public" was the default value. This is something we don't allow. 
By adding a switch statement we provide the available options for posts in open groups. Only community is allowed in this case. We also made a data alteration that ensures all the posts created, that have visibility "Public" become "Community". By checking the timestamp of when #994 landed in the Distro we ensure not to many posts are loaded and changed.  
- …
> #2992332 by ronaldtebrake: Default visibility fix for Open Groups

- modules/social_features/social_event/social_event.install
The JSON API user will be using the SM perm. We also want the api to retrieve all the event enrolments. The permission to view the event enrolments was not yet assigned to sitemanagers.
I propose to enable this for NEW installations. For existing installations we can enable the permission in the install hook of the social json api.
- DS-5960
n/a
> DS-5960 - Missing permission(s) for API

- composer.json
Difference between the versions is **2 bug fixes**.
- #2975802: Undefined offset: 0 in Drupal\csv_serialization\Encoder\CsvEncoder->extractHeaders()
- #2980321: README configs and useful links
- https://www.drupal.org/project/social/issues/3004858
Updated csv_serialization 1.3 to 1.4.
> Issue #3004858 by truls1502: Update csv_serialization 1.3 to 1.4

- modules/social_features/social_group/config/optional/block.block.socialblue_groupheroblock.yml
- tests/behat/features/capabilities/group/group-create-closed.feature
- tests/behat/features/capabilities/group/group-create-open.feature
- tests/behat/features/capabilities/group/group-create-public.feature
This is my first issue I'm taking on with this project so please let me know if I've missed anything in terms of the workflow, and pull request information below. I also don't know if you require an install hook or some other automated way to import the updated feature configuration, other than manually importing the feature with drush, as indicated below.
The hero can push simple action forms (such as join group/leave group) below the fold on smaller screens. This makes it more difficult for users to perform the action. Because of this we've decided to remove the hero on the join group screen. However, this causes the experience between leaving a group and joining a group to be inconsistent, as the hero still appears on the leave group screen.
The "Leave group" page path has been removed …
> Issue #3005537 by Kingdutch: Remove hero from "leave group" page

- composer.json
Since we allow core to be updated with a composer update and not locking the version, one of the patches that we apply don't work. Yesterday a new core version was released which broke the patch compatibility and it's unfortunately not in core yet. 
Updated the patch to the latests version in the comments. See what it does :). 
- 
Since we allow core to be updated with a composer update and not locking the version, one of the patches that we apply don't work. A new core version was released which broke the patch when using composer update and it's unfortunately not in core yet.
> Update patch after core update - lets see what it does

- modules/custom/social_auth_extra/social_auth_extra.module
When Data Policy consent is checked on signup form after signup with one of the social networks, you need to agree with consent again.
Save consent when it was checked on the signup form.
- https://www.drupal.org/project/social/issues/3010525
- https://jira.goalgorilla.com/browse/HGT-25
> Issue #3010525 by ribel: Fix double accept of data policy when using Social GDPR together with Social SSO

- modules/social_features/social_sso/social_sso.module
In most cases, if you use the Nickname (provided by Social Profile Fields module) you usually want to populate it as well after signup with social networks.
If Nickname is used prefill it, together with First and Last name.
- https://www.drupal.org/project/social/issues/3010526
- https://jira.goalgorilla.com/browse/HGT-26
When the Nickname field is available and people sign up via Social Login, we now populate that field with the First and Last Name received from the social networks.
> Issue #3010526 by ribel: Prefill Nickname together with First and Last name during social signup

- modules/social_features/social_event/src/Form/EnrollActionForm.php
- modules/social_features/social_group/config/install/group.role.closed_group-outsider.yml
- modules/social_features/social_group/modules/social_group_quickjoin/social_group_quickjoin.features.yml
- modules/social_features/social_group/modules/social_group_quickjoin/social_group_quickjoin.info.yml
- modules/social_features/social_group/modules/social_group_quickjoin/social_group_quickjoin.install
- modules/social_features/social_group/modules/social_group_quickjoin/social_group_quickjoin.links.menu.yml
- modules/social_features/social_group/modules/social_group_quickjoin/social_group_quickjoin.permissions.yml
- modules/social_features/social_group/modules/social_group_quickjoin/social_group_quickjoin.routing.yml
- modules/social_features/social_group/modules/social_group_quickjoin/social_group_quickjoin.services.yml
- modules/social_features/social_group/modules/social_group_quickjoin/src/Controller/SocialQuickJoinController.php
- modules/social_features/social_group/modules/social_group_quickjoin/src/EventSubscriber/RedirectSubscriber.php
- modules/social_features/social_group/modules/social_group_quickjoin/src/Form/SocialGroupQuickjoinSettings.php
- modules/social_features/social_group/social_group.module
When joining a group there's an unnecessary threshold of a 2 step verification. This is not always needed. Also CTA links to joining a group create a threshold with the confirmation step
On a group type basis it's now possible to override the 'Join' link to join a group instantly. Also sitebuilder can now make CTA links (EG: in landing pages) like: `/group/1/quickjoin` in order to allow users to join a group with a single click.
In order to make this feature work I made a change to the permissions of an outsider of closed groups. The issue was that the `join group` permission was enabled on those groups and that the code made sure we weren't able to join closed groups anyway. This has changed a but. In practice this doesn't make any difference, apart from the fact that the permissions are …
> SHN-226: Quickjoin groups

- modules/custom/activity_basics/src/Plugin/ActivityContext/GroupActivityContext.php
- modules/social_features/social_group/social_group.module
- modules/social_features/social_group/src/SocialGroupHelperService.php
- themes/socialbase/socialbase.theme
As part of customer support we've been doing some profiling of a well filled Open Social site and have discovered a few critical paths that lend themselves to optimisations. 
Please see the issue for a full description of the changes that were made.
With all the changes we measured a performance improvement of 15-20%
- https://www.drupal.org/project/social/issues/3008497
In an ongoing effort to make Open Social sites zoom across the internet we've retrained some of our functions and have measured a collective improvement of roughly 20%.
As part of this clean-up the `SocialGroupHelperService::getGroupFromEntity` method is no longer static as it's an anti-pattern to have static methods on services. If you previously called this method statically you should replace your code with …
> Issue #3008497 by Kingdutch, bramtenhove: Landing page performance research

- modules/custom/social_gdpr/social_gdpr.install
Opened in favor of #1014.
When enabling the GDPR you can also set data usage blocks to inform the user about GDPR. Sitemanagers cannot edit these texts.
Give sitemanagers more permissions for GDPR.
https://www.drupal.org/project/social/issues/2995247
The GDPR permissions have been updated to allow sitemanager to add descriptive text  about the data usage in a block.
> #2995247 by robertragas, bramtenhove: change GDPR site manager permission so they can edit the data block inform texts

- modules/social_features/social_core/social_core.module
<code>social_core_menu_local_tasks_alter</code> removes the <code>entity.node.edit_form</code> tab to force editing through the floating edit button. Before doing this it checks whether we're currently viewing a node of any valid node type. This logic isn't needed because if we weren't viewing a node then we wouldn't have the <code>entity.node.edit_form</code> task present.
Just remove the edit form tab if it's set (less computations => more performance!)
- https://www.drupal.org/project/social/issues/3010784
> Issue #3010784: Remove unnecessary Node checks from social_core_menu_local_tasks_alter

- modules/social_features/social_event/modules/social_event_an_enroll/social_event_an_enroll.routing.yml
The AN Event Enrollment settings currently use the broad "access administration pages" permission, a permission that the Content Manager role has. But, content managers should not actually have the permission to change these settings.
To prevent Content Managers from accessing the AN Event Enrollment configuration settings, the permission should be changed from 'access administration pages' to 'administer social_event settings'. (AN event enrollment is part of configuring how events work so it makes sense to reuse the "Administer Event Settings" permission).
If a user needs to change these settings, then they should probably be a site manager (or a separate role can be created).
The access permission to route social_event_an_enroll.settings with path …
> Issue #3008921 by Kingdutch: Anonymous (AN) Event enrollment settings should use "Administer Event Settings" permissions

- modules/social_features/social_landing_page/social_landing_page.module
<h3>Problem</h3>
Issue [#3002541] moved the classes from a template's wrapping div onto the link using a preprocess hook. While doing this the button class was changed from <code>btn-lg</code> to <code>btn-large</code>. The former is the correct class for a large button (the large one worked in Bootstrap 2.x but does not work in Bootstrap 3.x and is not used in Open Social).
<h3>Solution</h3>
Change the class back to <code>btn-lg</code> what it should be.
This is a potential breaking change if users have come to rely on the <code>btn-large</code> class for styling this specific element but the button is currently incorrectly styled because it does not have the <code>btn-lg</code> class.
- https://www.drupal.org/project/social/issues/3013128
Due to an incorrect classname the size for …
> Issue #3013128 by Kingdutch: Wrong button class causes incorrect sizing for landing pages

- modules/social_features/social_group/social_group.module
The Manage members tab is not showing up for Advanced outsider permissions roles.
We should instead check if user don't have the Administer group members permission and remove the tab.
- https://www.drupal.org/project/social/issues/2993854
The manage members tab on a group was not showing when an outsider has the "Administer group permissions"  permission. The tab is now only removed when a user does not have this permission. Note: this issue did not happen on default Open Social installations as all the necessary outside roles have the "Administer group" permission already.
> Issue #2993854: Group manage members tab not display correctly

- themes/socialbase/templates/system/status-messages.html.twig
Alert classes leak between messages
Set variable classes empty for each cycle
- https://jira.goalgorilla.com/browse/DS-5916
- https://www.drupal.org/project/social/issues/2980980
Test by applying for example:
```
diff --git a/modules/social_features/social_core/src/Controller/SocialCoreController.php b/modules/social_features/social_core/src/Controller/SocialCoreController.php
index c8592a013..4027d54d8 100644
--- a/modules/social_features/social_core/src/Controller/SocialCoreController.php
+++ b/modules/social_features/social_core/src/Controller/SocialCoreController.php
@@ -27,6 +27,9 @@ class SocialCoreController extends ControllerBase {
* Empty page for the homepage.
*/
public function stream() {
+    drupal_set_message(t('An error occurred and processing did not complete.'), 'error'); …
```
> Issue #2980980: Set correct classes for alert messages

- .travis.yml
Installing all composer dependencies can take 3-5 minutes per Travis run. 
Use hirak/prestissimo. The package parallelises downloads ahead of time instead of downloading
packages one by one. This can speed up package installs by about 60-80%.
No issue for this single line CI change.
N.A.
> Use hirak/prestissimo for faster composer installs

- modules/social_features/social_mentions/js/jquery.mentions.ckeditor.js
Failed to load resource: the server responded with a status of 404 (Not Found) https://mysite.com/user/11/jquery.mentions.js.map
I get the above error on Safari.
profiles/contrib/social/modules/social_features/social_mentions/js/jquery.mentions.ckeditor.js:528://# sourceMappingURL=jquery.mentions.js.map
Remove this line
https://www.drupal.org/project/social/issues/2969028
Prevent Safari from trying to load jquery.mentions.js.map.
> Issue #2969028: Failed to load resource: jquery.mentions.js.map

- themes/socialbase/templates/group/group--hero.html.twig
Some terms (link titles) in the socialbase theme templates are not translatable. For example the title of the "Edit group" button.
Let's make them translatable.
https://www.drupal.org/project/social/issues/3010322
Some link titles in the group hero area were not translated correctly.
> Issue #3010322 by ZeppinM: "Edit group" button not translatable

- modules/custom/activity_creator/activity_creator.tokens.inc
- modules/custom/activity_logger/activity_logger.tokens.inc
In some cases, the entity type of the activity message is empty, therefore, the site encounters an error.
We can make the code more defensive to prevent this type of error.
https://www.drupal.org/project/social/issues/2993086
In some cases, the entity type of the activity message is empty for customised sites, therefore, the site encounters an error. We've rewritten the code a bit to make this more defensive.
> Issue #2993086: Message related object entity type is empty

- modules/social_features/social_group/src/Controller/DeleteGroup.php
Non-static method Drupal\social_group\Controller\DeleteGroup::deleteGroupAndContentFinishedCallback() should not be called statically in _batch_finished()
Method is made static.
https://www.drupal.org/project/social/issues/2952504
Non-static method was called statically in DeleteGroup class which is called when deleting a (closed) group. This method is now made static.
> Issue #2952504: Deprecated function: Non-static method should not be called statically

- modules/custom/mentions/src/Form/MentionsSettingsForm.php
Strict warnings during cache rebuild.
Remove the StringTranslationTrait.
https://www.drupal.org/project/social/issues/2980079 (also related issues)
StringTranslationTrait define the same [error] property.
> Issue #2980079: StringTranslationTrait define the same [error] property

- modules/social_features/social_event/modules/social_event_type/social_event_type.module
We should only use getEditable when we plan to edit the config settings. In social_event_type_widget_alter.
Get the normal read-only config object using \Drupal::config()
https://www.drupal.org/project/social/issues/2985350
Code refactoring to Config read instead of getting the editable config in the social event type widget.
> Issue #2985350: Don't use Config getEditable for social_event_type_widget_alter

- composer.json
- drupal-org-core.make
Original PR: #976 
Support special characters in image names.
When restrict images text format filter is on and there are images with special characters in them, it fails the search indexing which also will crash the cronjob.
Bump up the patch number to 47 which includes support for special characters
https://www.drupal.org/project/social/issues/2988332#comment-12706997
Updated the restrict images patch that will prevent crashes during reindexing of search results when images had special characters in them.
> Issue #2988332 by robertragas, jaapjan: bump up restrict images patch

- modules/social_features/social_user/src/Plugin/Block/SocialUserLoginBlock.php
Whenever I try to place the Social user login block in an active region such as content region or footer region, the homepage becomes in accessible. It gives a message "an unexpected error occured...". It happens with and without configuring social login configurations.
The UrlGeneratorTrait is removed which is causing this issue.
The issue seems to be introduced in: https://www.drupal.org/node/2867703. You can see the diff here: https://github.com/drupal/drupal/commit/dcec8637914897589f9e0c736b71d5169e7ccfc7#diff-2bd8cf9c6914a40c4877e15defd96498
We could have just added the UrlGeneratorTrait but I think it's better to implement the same logic as in the core <a href="https://api.drupal.org/api/drupal/core%21modules%21user%21src%21Plugin%21Block%21UserLoginBlock.php/8.6.x">UserLoginBlock.ph …
> Issue #3002195 by jaapjan: updating SocialUserLoginBlock to prevent errors

- modules/social_features/social_profile/src/SocialProfileTrait.php
- themes/socialbase/assets/css/autocomplete.css
- themes/socialbase/components/03-molecules/form-elements/autocomplete/autocomplete.scss
On platforms which multiple users it is hard to find the correct user in user reference fields or in the mentions. This is already partly improved in PR #1082 but this is only part of the solution. If your platform has more than 50 John's it is still hard to find `John Doe` as there is no sorting by relevance and it is not possible to search for space-separated strings.
- [#2965717 - When searching for a user to mention the suggestions should sort by relevance](https://www.drupal.org/project/social/issues/2965717)
- [#3005538 - When searching for a user to mention the suggestions should sort by relevance](https://www.drupal.org/project/social/issues/3005538)
The solution is two-fold. 
By providing better sorting it is easier to find a given user. Let's say you have the following users:
- …
> DS-6236, #3005538, 2965717: Mention improvements

- modules/social_features/social_private_message/src/Service/SocialPrivateMessageService.php
**Performance issue**
On every page load the private message unread count indicator in the header is checking for well, unread private messages.
Considering you have 86 private message threads, it will execute 86 queries to determine how many unread private messages you have. This is not ok and should be limited to one query for all threads.
**Query error**
Also fixed an issue where a query was not using table placeholders and thus breaking sites with a database with a prefix.
**Performance issue**
Rewrote the logic to determine the count of unread private messages. It now uses a single query.
Tested with a user that has approximately 90 PM threads, for users with less threads impact will be lower.
**Query error**
Rewrote the query to use table placeholders.
- …
> #3015692 -  #3009970 Performance PM and database prefix fix

- modules/social_features/social_event/modules/social_event_managers/src/SocialEventManagersAccessHelper.php
When using the social_event_managers module and creating an event as a LU (non-SM/CM) with the option to automatically add the user as an event manager disabled then the edit event screen throws an error because an empty value is stored in the `field_event_managers`.
Add a check to see if we can possibly match a value. Also cleaned up a call to a function in the class.
- https://www.drupal.org/node/3010275
An error is no longer thrown on the edit event screen for the Social Event Managers module when the option to automatically add the user as an event manager was disabled and no other event managers were set.
> #3010275 by Kingdutch, bramtenhove: Added check to prevent undefined index

- tests/behat/features/capabilities/topic/newest-topics.feature
So basically this test would create two topics with a mandatory topic_type and then check on these in the homepage a.k.a. /stream. In _social_topic_install_ there are three _topic_types_ already predefined and shipped with OS. However, if you would run this test on a platform where the initial _topic_types_ are different or gone, this test fails. The test should be flexible enough to create these taxonomy terms inside the test, and then test on them.
The provided solution makes use of the standard DrupalContext step **createTerms** where we would create these initial values inside the test. This way the functionality as intended in OS can be tested on platforms where the _topic_types_ differ from the terms that are pre-defined in _social_topic_install_ but may have been altered on a …
> OSSUPPORT-1473 - Adjust newest-topics.feature test to be used more generally

- modules/social_features/social_group/config/optional/block.block.groupheroblock.yml
The socialblue_groupheroblock has the following pages listed: 
`/group/*/stream\r\n/group/*/about\r\n/group/*/events\r\n/group/*/topics\r\n/group/*/members\r\n/group/*/membership\r\n/group/*/leave\r\n/group/*/content/*`
Meanwhile groupheroblock has only `/group/*`
Copy the pages of socialblue_groupheroblock to groupheroblock in the social_group module.
- https://www.drupal.org/project/social/issues/2989988
`/group/*/stream
/group/*/about
/group/*/events
/group/*/topics
/group/*/members
/group/*/membership
/group/*/content/*` 
in the textarea.
This should match what's in the socialblue_groupheroblock (/admin/structure/block/manage/socialblue_groupheroblock?destination=/admin/structure/block).
Group Hero block (groupheroblock) will no longer display on all group/* pages, only those …
> Issue #2989988 by KingDutch: socialbase grouphero block is outdated

- modules/social_features/social_landing_page/config/install/views.view.community_activities.yml
Block community activities doesn't have a pager.
Add a mini pager just like the (personalised) activity stream block.
https://www.drupal.org/project/social/issues/2976046
The community activities block on a landing page now has a pager when there are more than the set amount of activities available in the stream.
>  Issue #2976046: add pager to community activities block in landing page

- modules/social_features/social_search/src/Form/SearchContentForm.php
- modules/social_features/social_search/src/Form/SearchHeroForm.php
On the search page the `page=x` parameter is preserved causing a user to end up on page X after entering a new search term. It makes more sense to serve the user the first page of the results.
Rewrote the query parameters to exclude the `page` parameter in SearchContentForm.php and SearchHeroForm.php.
https://www.drupal.org/project/social/issues/2976018
Whenever a user enters a new search term in the search form the user is now always directed to the first page of the search results.
> Issue #2976018 by jaapjan: reset page number when searching

- modules/social_features/social_activity/config/install/views.view.activity_stream.yml
- modules/social_features/social_activity/config/install/views.view.activity_stream_notifications.yml
I've been profiling the activity stream and noticed a significant performance gain when decreasing the amount of activities shown.
Tests were run on an Open Social installation with a normal amount of activities (15k). But can also be reproduced with less activities or much more.
Activity streams are slow.
Showing less items in the stream results in significant performance gains:
30 items = 7.23 seconds - default
20 items = 5.01 seconds - approx. 30% of default
10 items = 3.56 seconds - approx. 50% of default
I suggest to decrease the amount of activities shown to 20. This still gives a feeling of a full stream, but reduces page load by 30%.
Also reduced the amount of notifications shown on the notifications overview page from 30 to 20.
- …
> #3017264 by bramtenhove: Reduce the amount of activity stream items

- modules/social_features/social_activity/social_activity.module
- modules/social_features/social_user/src/Element/AccountHeaderElement.php
- themes/socialbase/templates/views/views-view--activity-stream-notifications--page.html.twig
- themes/socialbase/templates/views/views-view.html.twig
In 4.0 the AccountHeaderBlock got a massive overhaul. This resulted in the count indicator moving from the Top of the icon to the bottom.
Also the notification reading results in an JS error resulting in messages not being marked as "read" therefore the counter remains the same even after reading the notifications.
1. We will update the count to make sure accessibility stays in place and the count shows on top again.
2. We will fix the JS issue that marks messages as read.
- https://www.drupal.org/node/3018168
In 4.0 the AccountHeaderBlock got an overhaul. This overhaul resulted in two bugs which we managed to fix and release in this hotfix. The count indicator should now be updated again once you click on the Notification Centre icon. And the indicator is shown on the top part of the …
>  #3018168 - Hotfix 4.1 - Fix read count placement and updateReadCount on click.

- modules/social_features/social_group/social_group.module
Manage members is now the first tab in the group local tabs. Due to #3010778.
Made sure that we set the weight only when the tab is available.
https://www.drupal.org/project/social/issues/3020038
The order of the Group tabs is now fixed so Manage Members is right after Members.
> #3020038 - Group content manage members tab order weight

- themes/socialbase/templates/profile/profile--profile--default.html.twig
Reorder default profile display fields 'Expertise' and 'Interests' so that the order is consistent with the edit profile form, in which 'Expertise' comes first.
Expertise and Interests' order in the edit profile form does not match that of the profile display. On the edit form, 'Expertise' appears first, while when displayed, 'Interests' is first.
Changed the order in the default profile twig template, so that 'Expertise' is now first, to match the order of the edit profile form.
https://www.drupal.org/project/social/issues/2986249
Moved the display of the 'Expertise' field in the default profile twig template so that it appears above 'Interests', to match the order of the profile edit form.
> Move profile display 'Expertise' field above 'Interests'

- modules/social_features/social_editor/config/install/editor.editor.full_html.yml
Users sometimes find it difficult to create nice content from the CKeditor.
Added some predefined styles such as the buttons, so user can create a link and simple set the styl with the dropdown.
- https://jira.goalgorilla.com/browse/SHN-267
When editing text as a CM+ there's now an extra dropdown in the editor, that allows you to create nicer links and add some other special Open Social styling to your text.
> #3022657 / SHN-267: Add some predefined styles to the CKEditor (full_html)

- modules/social_features/social_core/social_core.links.menu.yml
- modules/social_features/social_core/social_core.routing.yml
The config > open social settings page is empty. This is especially annoying when you've enabled a lot of extra open social modules and the sub-menu list gets too long. 
Add the systemcontroller on the route, that is reponsible for building the default main category pages
https://www.drupal.org/project/social/issues/2928228
The main category page of Open Social Settings now renders all the subitems that are part of the Open Social Settings eco-system
> 2928228 - Open Social (admin) configuration page category page

- tests/behat/features/capabilities/group/group-edit-type.feature
The test breaks on some MOSS platforms because there are many groups/topics on the overview.
This tries to avoid the group and topic overviews to visit a group
because this may not work in some scenarios on some platforms.
n.a.
internal, n.a.
> Refactor Group Edit Test

- modules/social_features/social_landing_page/templates/node--event--featured.html.twig
- modules/social_features/social_landing_page/templates/node--landing-page--featured.html.twig
- modules/social_features/social_landing_page/templates/node--page--featured.html.twig
- modules/social_features/social_landing_page/templates/node--topic--featured.html.twig
- modules/social_features/social_landing_page/templates/profile--featured.html.twig
The "Read More" link is shown twice in Featured blocks on the Social Landing Page. This is happening because certain template files in the social_landing_page module are extended from node--featured.html.twig where the this one already has the card__actionbar with the card__link. These elements were also in the extended template file, which caused it to show twice.
Remove the card__link element from node--topic--featured.html.twig and node-landing-page--featured.html.twig since only these two had the duplicate elements.
https://www.drupal.org/project/social/issues/3020522
Fixed an issue where featured blocks in landing pages showed the Read More link twice.
> Issue #3020522: Read more link is shown twice in featured

- tests/behat/features/capabilities/gdpr/create-data-policy.feature
- themes/socialbase/templates/block/block--data-policy-page-title-block.html.twig
Data policy has no editable title and is fixed to "Data policy"
Replace the hardcoded string with an already existing variable, so it can be changed by SM
- https://www.drupal.org/project/social/issues/3020084
- https://www.drupal.org/project/data_policy/issues/3020081
- https://jira.goalgorilla.com/browse/HGT-40
> Issue #3020084 by ribel: Replace hardcoded 'Data policy' page title with value from variable

- modules/social_features/social_page/config/install/core.entity_form_display.node.page.default.yml
PR for https://www.drupal.org/project/social/issues/3020575
The configuration value core.entity_form_display.node.page.default.content.status.settings.display_label was installed as an integer but it is now converted to a boolean.
> #3020575: Fix configuration schema for modules/social_features/social_page/config/install/core.entity_form_display.node.page.default.yml

- modules/social_features/social_post/src/PostListBuilder.php
If the field `field_post` does not exist on a post it throws an error on `admin/content/post`.
Let's check if the entity has the field before trying to get the field value from the entity.
https://www.drupal.org/project/social/issues/3020007
The `admin/content/post` overview only worked if all the post entities had the field `field_post. Now it checks if the field exists before trying to display the field value.
> Issue #3020007 : prevent error on post list when field_post does not exist

- modules/social_features/social_landing_page/social_landing_page.module
Featuring a landing page without hero causes the image to show "Array"
Let's check first if we actually have an image object before trying to render it. 
https://www.drupal.org/project/social/issues/3021176
When you featured a landing page without a hero section on another landing page you could see the text "Array" on top of the teaser. This is now fixed to prevent this from happening again.
> #3021176 : Featuring a landing page without hero causes the image to show "Array"

- modules/social_features/social_like/src/Plugin/ActivityContext/VoteActivityContext.php
You get a notification when liking your own entity.
Let's implement the same solution as we did in #464 this will prevent an actor from being marked as recipient.
https://www.drupal.org/project/social/issues/3018268
From now on you will not receive notifications when you like your own comment or post.
> Issue #3018268 by jaapjan: don't send notification for liking own content

- modules/social_features/social_search/config/install/search_api.index.social_content.yml
When going to the fields section of then 'social_content' search api index, you can add fields. However when saving this you get a 'search_api_node_grants is a reserved value and cannot be used as the machine name of a normal field. validation message. 
- Change search_api_node_grants to node_grants in the configuration file
- Importing of the configuration (`drush fra`) automatically triggers a reindex, so update hook isn't necessary.
https://www.drupal.org/project/social/issues/2936146
Administrators were unable to save the Fields configuration for the Search API index social_content because of a malformed configuration. This should be solved now!
> Issue #2936146: Cannot save 'social_content' search_api index fields

- modules/custom/improved_theme_settings/improved_theme_settings.module
- themes/socialbase/assets/css/button.css
- themes/socialbase/assets/css/ckeditor.css
- themes/socialbase/components/02-atoms/button/button.scss
- themes/socialblue/assets/css/button.css
- themes/socialblue/assets/css/ckeditor.css
- themes/socialblue/assets/css/preview.css
- themes/socialblue/components/02-atoms/button/button.scss
Switching from AddToAny to Shariff caused a visual regression because the styling that was present in the AddToAny button was not replicated for Shariff.
Related PR: #1100 
See: https://www.drupal.org/files/issues/2019-01-14/Screenshot%202019-01-14%20at%2012.44.10.png
The Shariff buttons don't have rounded corners or centered icons by
default which causes a regression compared to the previously present
addtoany buttons.
Add the centering of icons to Socialbase and the default border-radius to Socialblue. Also ensure that this changes with the button rounding setting in the theme settings.
Result: https://www.drupal.org/files/issues/2019-01-14/Screenshot%202019-01-14%20at%2012.44.30.png
This commit adds a default border-radius for the socialblue theme and …
> Fix styling for social sharing buttons

- modules/custom/social_auth_extra/social_auth_extra.module
- modules/social_features/social_profile/modules/social_profile_organization_tag/social_profile_organization_tag.module
When administrator approval is needed (setting in Account settings) and a user signs up via a Social account (e.g. Google) it would get the approved status immediately, thus skipping administrator approval.
Ensuring that users get the correct status depending on the registration setting, also when signing up via one of the social accounts.
https://www.drupal.org/project/social/issues/3017245
When administrator approval is needed (setting in Account settings) and a user signs up via a Social account (e.g. Google) it would get the approved status immediately, thus skipping administrator approval. This issue is solved by ensuring that users get the correct status depending on the registration setting, also when signing up via one of the social accounts.
> Issue #3017245: set correct user status for new users when signing up via social login

- modules/custom/activity_creator/activity.page.inc
Call to function isAnonymous() on null in template_preprocess_activity()
Only run the code when the `$account` is set.
https://www.drupal.org/project/social/issues/3027247
Generation/displaying of activity items could in some cases result in an error on page, this is now solved by adding some more defensive coding.
> Issue #3027247: Call to function isAnonymous() on null in template_preprocess_activity()

- social.info.yml
All dependencies must be prefixed with the project name, for example "drupal:"
https://www.drupal.org/project/social/issues/2936477
- Verify installation works still as expected, wait for Travis to be completed.
(developer) All dependencies in social.info.yml are now with the project name, for example "drupal:".
> Issue #2936477 : dependency declaration in social.info.yml

- modules/social_features/social_profile/modules/social_profile_organization_tag/social_profile_organization_tag.services.yml
When social comment upload is enabled I can't see the attachment upload on the comment form. This happens when social_profile_organization_tag is enabled.
The social_profile_organization_tag.services.yml contains a service which already exist. I've renamed this to a different override function.
https://www.drupal.org/project/social/issues/3024352
The attachment upload are not working correctly when the optional Profile Organization Tag was also enabled. This has been solved now.
> Issue #3024352 - do not override existing services as it will break comment upload

- themes/socialbase/templates/group/group--hero.html.twig
- themes/socialbase/templates/group/group--teaser.html.twig
The string Joined in the codebase needs a context such as "Became member" to avoid a translation collision with "(date) joined" which is a header used elsewhere in Drupal.
https://www.drupal.org/project/social/issues/2948330
(developer) The string Joined in the codebase now has a translation context such as "Became member" to avoid a translation collision with "(date) joined" which is a header used elsewhere in Drupal.
> Issue #2948330: Distinguish between "Date Joined" and "Has joined"

- modules/social_features/social_search/social_search.links.task.yml
The items in this render array should have #weight properties that are properly spaced (e.g. 10, 20, 30, 40) so that their order remains consistent across releases and other modules can easily add their own items in the desired place.
Add the correct weight for search related links to the following .yml files:
- social_search.links.task.yml
https://www.drupal.org/project/social/issues/3010782
(developer) Tabs on the search pages now have a default weight with some spacing in between. This allows other modules to easily add their own these local tasks.
> Issue #3010782 Ensure search menu local tasks have proper weights

- modules/social_features/social_group/social_group.module
- tests/behat/features/capabilities/group/group-edit-open.feature
https://www.drupal.org/project/social/issues/2968506
When a group of any type (closed, open, public) is deleted the posts and content in this group are also deleted.
> Issue #2968506 by uros.ceh, jaapjan, truls1502: When group is deleted the posts in this group should be deleted as well

- modules/social_features/social_editor/config/install/editor.editor.full_html.yml
After configuring text into 'pill badge' style in text editors, it shows blank white after saving it. So the text is actually not visible anymore.
This is due to the fact the incorrect classes are applied.
Use other CSS classes for **Pill badge** CKEditor style for fix showing text with this style as invisible.
https://www.drupal.org/project/social/issues/3027339
Make text visible when it used "Pill badge" CKEditor style.
> Issue #3027339: The 'pill badge' style is not working properly in text editors

- modules/social_features/social_profile/social_profile.module
- modules/social_features/social_profile/src/Plugin/Field/FieldWidget/CategorizedOptionsbuttonsWidget.php
- modules/social_features/social_search/config/install/views.view.search_users.yml
- modules/social_features/social_search/social_search.module
- themes/socialbase/assets/css/base.css
- themes/socialbase/assets/css/ckeditor.css
- themes/socialbase/assets/css/dropdown.css
- themes/socialbase/assets/css/form-elements.css
- themes/socialbase/assets/css/nav-tabs.css
- themes/socialbase/assets/css/teaser.css
- themes/socialbase/components/03-molecules/form-elements/form-elements.scss
Taxonomy terms sorting by IDs.
Sort taxonomy terms by weight and name.
https://www.drupal.org/project/social/issues/3028153
It's now possible to create multiple levels of Profile Tags. Similarly to content tagging the top level taxonomy term can now be used as a category by giving it children. When only a single level of profile tags exist the current behaviour will be preserved. When a user receives a taxonomy term in a category then they will also receive the tag of the category itself to facilitate searching.
> Issue #3028153: Profile Tag List not displaying correctly in filter on user search page

- modules/social_features/social_group/social_group.module
- modules/social_features/social_group/social_group.services.yml
- modules/social_features/social_group/src/Plugin/Action/AddMembersToGroup.php
- modules/social_features/social_group/src/SocialGroupAdminPeopleConfigOverride.php
There is no easy way for a SiteManager to quickly add multiple people to a group. 
Add a new VBO plugin for the `admin/people` overview which enables adding one or more users to a group.
https://jira.goalgorilla.com/browse/DS-6367
As a Site Manager you are now able to add users to a group directly from the People overview.
> DS-6367 - Adding members to groups in bulk #52395

- modules/social_features/social_event/social_event.tokens.inc
When you create an event as LU, enrol to the event yourself, let some other people enrol to your event, run the cron and then delete the event you will receive a 500 error when trying to load your notification bar resulting in a non-working website.
Let's add an extra check before blindly calling the toUrl() method on an object which might be NULL.
https://www.drupal.org/project/social/issues/3035592
If an event was deleted and an event organizer received a notification for it this could result in an error on the page/your stream not loading correctly. This is now solved.
> Issue #3035592: make sure event exists before calling toUrl method on it

- modules/social_features/social_event/config/optional/message.template.activity_on_events_im_organizing.yml
- tests/behat/features/capabilities/group/group-edit-open.feature
Group edit open failed.
Fix group-edit-open, we used to press delete but didnt check if the batch was finished and if the success message was displayed. This could potentially cause an issue where the test was green, which means the AfterScenario ` /**
* Remove any groups that were created.
*
* @AfterScenario
*/
public function cleanupGroups(AfterScenarioScope $scope) {
if (!empty($this->groups)) {
foreach ($this->groups as $group) {
$group->delete();
}
}
}` 
was called but in the meantime the batch job deleting the group was deleting all of the Group Content. Due to that the cachetags are duplicating in insertion instead of an update.
The solution is to wait for the job to finish, for all the Group and Group content to be deleted correctly and after that the AfterScenario step can kick …
> Lets make travis green again!

- themes/socialbase/templates/node/event/node--event--teaser.html.twig
- themes/socialbase/templates/node/topic/node--topic--teaser.html.twig
When a body text is enabled in the teaser display of an event or topic it is not displayed in the actual teaser. The field is missing in the twig template.
Add the field in the twig file.
https://www.drupal.org/project/social/issues/3029643
When a body text is enabled in the teaser display of an event or topic it is now displayed in the actual teaser as it is added in the teaser template.
> Issue #3029643: teasers for topics and event body text.

- modules/social_features/social_like/social_like.module
The bundle in the title in the like modal window is untranslatable.
Let's make it translatable. Best is to retrieve the bundle settings and retrieve the label from there. The bundle settings label respect the current active language and the label is always the label from the configuration translation of the current bundle.
https://www.drupal.org/project/social/issues/2992737
The entity type in a like modal window is now showing the translated word in multi-language sites.
> Issue #2992737: fix translation of the bundle in like modal title

- themes/socialbase/src/Plugin/Preprocess/Block.php
For the social geolocation module some code was added to load a replacement search block if the module was enabled. This search block has been removed long ago but the code was never removed. This now causes the search to be come unavailable in the menu bar when the social_geolocation module is enabled.
Remove the logic for replacing the search block and always load the theme's search block.
This code was added long ago in 09319ab but the module has since been
removed from Open Social and used in another project. In this other
project the block that was referenced to has been removed because it was
no longer needed. Finally the module was re-introduced as a stand-alone
extension when it was extracted from the project. This has surfaced the
bug that this …
> Remove geolocation code for search block

- modules/social_features/social_event/modules/social_event_an_enroll/src/Form/EventAnEnrollActionForm.php
HTML in pop-up for anonymous event enrolment. 
I followed this solution in Core
https://www.drupal.org/project/drupal/issues/2568149#comment-10327469
https://www.drupal.org/project/social/issues/3024448
If an event title included any special characters (for example an apostrophe `) it would not display correctly in the pop-up window which anonymous users see after clicking on the "Enrol" button. This is now solved.
> Issue #3024448: html in pop-up for anonymous event enrolment

- composer.json
Update to the latest version
https://www.drupal.org/project/social/issues/3038770
Update bower-asset/bootstrap from v3.4.0 to v3.4.1
> Issue #3038770 by truls1502: Update bower-asset/bootstrap from v3.4.0 to v3.4.1

- themes/socialbase/includes/form.inc
The content_lock module adds an "unlock" action to nodes. This should be styled like the other secondary actions.
Add the btn, btn-flat classes to the "unlock" link in socialbase if the link exists.
https://www.drupal.org/project/social/issues/3039063
The unlock link added by the content_lock module will now be correctly styled when used with a theme inheriting from socialbase.
> Issue #3039063 by Kingdutch: Add styling for node content_lock unlock button

- composer.json
Since we didnt specify which version `twig/twig` we use `composer update` updates to the latest version which causes a fatal error. 
Core is trying to patch using: https://www.drupal.org/project/drupal/issues/3039408
this however results in a patch which doesnt work since core needs to patch composer.lock files we don't use. Custom copying that pach results in errors in Open Social with twig caching. 
We will open up a separate issue for that. First lets go for green on the tests again.
- None.
None
> #3039585 - Composer updates cause twig to fail.

- themes/socialbase/templates/system/pager.html.twig
The default pager buttons on overviews (first, next, previous, last) aren't translatable due to an issue in the descovery of these items. 
Make sure we work around the twig discovery so potx is aware of these strings. See: https://www.drupal.org/project/potx/issues/2816601
https://www.drupal.org/project/social/issues/3040183
The buttons on pagination are now translatable. These being _first, next, previous, last_
> #3040183 by ronaldtebrake: update translations for pagers

- modules/social_features/social_group/config/install/views.view.group_members.yml
Whenever a group has more than 10 people, pagination appears. However when you go to the next page, a couple of the same users appears as on the first page. Seems to be a bit random. Maybe something with sorting?
I turned out to be related to the create date of the group content (mass added users). Since that creation data of the group content (the membership) was the same for almost all members, views is kind of clueless. I've added an additional sorting on name (label of the group content)
- https://www.drupal.org/project/social/issues/3039042
- https://jira.goalgorilla.com/browse/YANG-757
In some rare cases when a lot of users were added to a group in bulk, the pagination of the members in a group would show the same results on the second page of the group members page. This is now …
> 3039042: Member tab in group shows the same members on the second page

- modules/social_features/social_event/modules/social_event_managers/social_event_managers.routing.yml
- modules/social_features/social_event/modules/social_event_managers/social_event_managers.services.yml
- modules/social_features/social_event/modules/social_event_managers/src/EventSubscriber/RouteSubscriber.php
- modules/social_features/social_group/social_group.install
- modules/social_features/social_user/social_user.install
Problem with the current implementation is the forms that are written for the social_event_managers module. Those extend some forms from views_bulk_operations. When you don't have the social_event_managers enabled there's no problem, since it now has a dependency towards views_bulk_operations. However if you had already enabled social_event_managers and you take this code, you get an error, because the autoloader is not yet aware of the extended 'Drupal\views_bulk_operations\Form\ConfigureAction', causing a fatal error.
Turns out a solution was already made in #1250 
http://www.drupal.org/node/3021721
...
> 3021721 by jaapjan: Create routes only after the vbo module is installed

- .travis.yml
- composer.json
Since Drupal has released [8.6.11](https://www.drupal.org/project/drupal/releases/8.6.11), this composer-file has a conflict with OpenSocial's composer-file. 
https://www.drupal.org/project/social/issues/3042537
Removed twig/twig on OpenSocial
> Issue #3042537: Remove twig/twig on 8.x-3.x

- modules/social_features/social_like/social_like.module
In #2992737: The bundle inside the like modal title is not translatable the bundle name was retrieved and lowercased to be able to translate the bundle name in the like message. However, in some languages such as German the bundle name is a noun that should start with an uppercase letter.
Remove the strtolower that was added in the PR for #2992737: The bundle inside the like modal title is not translatable: https://github.com/goalgorilla/open_social/pull/1234/files#diff-7a427f5a...
https://github.com/goalgorilla/open_social/pull/new/feature/3042115
The bundle name in the Like modal window title was retrieved and lowercased to be able to translate the bundle name in the like message. However, in some languages such as German the bundle name is a noun that should start with an uppercase …
> Issue #3042115: lowercase bundle can be incorrect in some languages

- modules/social_features/social_profile/social_profile.module
We're getting notices on form with fieldsets. EG: /admin/config/opensocial/navigation-settings
Defensive check on attributes in the array
- https://www.drupal.org/node/3028153
Nothing to add, since it was introduced in 8.x-5.x
> 3028153 by jochemvn: Fix notice

- themes/socialbase/src/Plugin/Preprocess/Html.php
Based on socialbase\src\Plugin\Preprocess\Html.php the .page-node-edit class is only added to the body tag on node add not on node edit.
If you need a css class indicating node editing it should be consistent
Add a check for a "edit" as well
https://www.drupal.org/project/social/issues/3043426
- edit any node content and check that the body tag contains css class "page-node-edit"
The `page-node-edit` class is now also added to the node edit form. Previously it was only added on the node add form. Now the name matches the behaviour.
> Issue #3043426 by slowflyer: page-node-edit css class is missing for node edit

- modules/social_features/social_tagging/social_tagging.services.yml
- modules/social_features/social_tagging/src/SocialTaggingOverrides.php
Problem occured on platforms that have the social tagging enabled (and potentially language is also involved). A circular reference occurs because:
1. The SocialTagService requires config
2. Config checks for overrides....
3. SocialTagsConfigOverride requires SocialTagService.
This results in a chicken and egg scenario. 
Remove the injection of the tagservice (and config) in the configoverride.
Not needed. ISsue found during 5.0 testing day.
> Fix circular reference dependency injection

- modules/social_features/social_profile/social_profile.module
In some cases a notice is thrown in the social_profile module.
`Notice: Undefined index: field_profile_profile_tag in social_profile_form_profile_profile_edit_form_alter() (line 108 of profiles/contrib/social/modules/social_features/social_profile/social_profile.module).`
Add an extra check to prevent a notice being thrown.
https://www.drupal.org/project/social/issues/3043086
A notice could be thrown in the `social_profile` module when trying to unset the profile tag field when it was already not available. With an extra check this will no longer happen.
> Issue #3043086 by bramtenhove: Add extra check to prevent notice thrown in social_profile module

- modules/custom/activity_logger/src/Service/ActivityLoggerFactory.php
In some cases it is possible that, when preparing to generate activities a fatal error can occur. This is usually not noticeable for the user as it is most likely something that is happening when processing a queue item.
In the `ActivityLoggerFactory.php` the code assumes the owner of the entity is available, this is however not always the case. Next to that `getOwner()` method does not always exist for an entity.
Add a check to make sure `getOwner()` method exists and the value is not `null`.
https://www.drupal.org/project/social/issues/3045199
In some cases it was possible that, when the system is preparing to generate activities an error could occur. By adding an extra check we prevent the error from occurring.
> Issue #3045199 by bramtenhove: Fix possible fatal error can occur while generating activities

- modules/social_features/social_private_message/social_private_message.module
- modules/social_features/social_profile/social_profile.module
When a user deletes a private message thread the contact url on the profile of participants in the thread doesn't work anymore (access denied).
We check for access before returning the URL. In addition the cache tag is invalidated for every participant to always ensure the latest url.
https://www.drupal.org/project/social/issues/2961232
When a user deletes a private message thread the contact url on the profile of participants in the thread didn't work in some cases. This issue is now solved.
> Issue #2961232 change private message contact url when thread is deleted

- modules/custom/social_language/social_language.module
When social_language is enabled you could select the Translate tab as landing tab of a group.
Let's remove that tab and use the alter function provided.
N/A (but check the testing 5.0 doc)
Not necessary, because it is just introduced in this release.
> Issue #3027295: remove Translate tab from Tab management landing tab on Group

- modules/social_features/social_landing_page/social_landing_page.module
- themes/socialbase/src/Plugin/Preprocess/Node.php
When you add a featured content section to a landing page and in that section, you link to another landing page, you see a big SVG icon over the image.
Only show if the landing page has no image.
https://www.drupal.org/project/social/issues/3047076
When featuring a landing page on another landing page, a big SVG Icon would display over the landing page image. This is now fixed.
> #3047076: Featuring landing pages on a landing page, shows svg icon over the image

- modules/social_features/social_group/social_group.services.yml
- modules/social_features/social_group/src/SocialGroupAdminPeopleConfigOverride.php
The new and improved group management overview doesn't work for group types other than those that come with Open Social. 
We've implemented the `social_group_types_alter` hook in such a way that custom group builder can now use that hook to enable the group management overview.
http://www.drupal.org/node/3019370
Part of the other story: #1153
> #3019370: Use hook system for group management overview

- modules/social_features/social_event/modules/social_event_an_enroll/templates/event-an-enroll-dialog.html.twig
- tests/behat/features/capabilities/event-an-enroll/event-an-enroll.feature
From a customer
<blockquote>I have discovered that the wording on the buttons when an AN tries to enroll in an event can be confusing. Some people interpret "Sign up" to mean sign up for the event rather than sign up for Open Social, and members who have accounts have encountered difficulty by clicking that option.
What do you think about changing the design to have buttons that say something like "Create an Account" "Log In" "Enroll as a Guest" and removing the "Enroll with account" and "Enroll without account" headings?</blockquote>
Change "Sign up" in the modal to "Create an account" and change "Sign up as guest" to "Enroll as guest".
As discussed with Xinyu and Natasha:
<blockquote>I think the problem is the sign up button. I agree that we should …
> Issue #3045772: Alter anonymous enrollment button texts

- modules/custom/social_file_private/src/SocialFilePrivateFieldsConfigOverride.php
Private file system should be used for any image provided by us.
I've added it to the social private files configuration.
n/a because 5.0 isn't released yet.
n/a because 5.0 isn't released yet.
> Use private file system for images in landing page

- modules/custom/activity_logger/src/Service/ActivityLoggerFactory.php
- modules/custom/mentions/src/Entity/Mentions.php
- modules/custom/mentions/src/MentionsInterface.php
We should encourage the use of Interfaces (this is exactly what they're for) instead of checking whether the method exists.
Performance wise the difference is negligible (<a href="https://stackoverflow.com/a/29496479/576060">instanceof is even slightly faster</a>). However, <code>instanceof</code> more clearly communicates intent because we're looking to use the <code>getOwner</code> function in the way that it's defined in that interface. When using <code>method_exists</code>, if someone were to implement <code>getOwner</code> but not return an instance of <code>UserInterface</code> then our code would still fall apart.
https://www.drupal.org/project/social/issues/3047142
The check in `ActivityLoggerFactory` to detect whether an entity has an owner now uses the `instanceof` method to …
> Issue #3047142: Prefer instanceof over method_exists in ActivityLoggerFactory::createMessages

- themes/socialbase/templates/system/pager.html.twig
After updating to OS 4.9 the pager only shows "First" on all positions (See iamge on https://www.drupal.org/project/social/issues/3047646)
Adjust labels
https://www.drupal.org/project/social/issues/3047646
- create enough users that the pager shows up on fe. /all-members page. All pager items show "First"
- install the patch
- pager will show up correct
> "Only First page" Pager

- modules/social_features/social_event/modules/social_event_managers/social_event_managers.module
- tests/behat/features/capabilities/event/eventenrollment.feature
- Make sure the all enrollments link now goes to the new enrollments
Made sure we alter the views link.
Nope
- all 5.0 releases so nothing here :)
> Event improvements after Event Manager & Max attendees are merged.

- modules/social_features/social_event/modules/social_event_managers/src/Form/SocialEventManagersAddEnrolleeForm.php
- modules/social_features/social_event/social_event.module
For non event organizers (CM/SM) we show "your event" as part of the submit message, which is a little confusing.
We now check if it's actually an organizer or manager. If that is the case we show this message. Of it's someone else we make it this event as a better descriptive message.
https://jira.goalgorilla.com/browse/DS-6569
```
$singular = '@count new member is enrolled to this event.';
$plural = '@count new members are enrolled to this event.';
```
```
$singular = '@count new member is enrolled to your event.';
$plural = '@count new members are enrolled to your event.';
```
Only Event Organisers see the your event context, since it's theirs.
> DS-6569 Minor textual change on Adding event enrollee submit message.

- modules/social_features/social_profile/modules/social_profile_privacy/social_profile_privacy.module
On the profile privacy settings page (/admin/config/people/social-profile) it is not clear that the setting to "Limit search and mention" only has effect on people who actually filled in their nickname.
This is the current description for this setting.
```Enabling this setting causes users' full name to be hidden on the platform. Users with the '%display_name' permission will still see the full name whenever available. Only users with the '%search_name' permission will find users using their full name through search or mentions.```
Let's change the description text to make this clearer:
```Enabling this setting causes users' full name to be hidden on the platform when the user has filled in their nickname. This setting won't hide the full name of users who didn't fill in a nickname. Users …
```
> Issue #3052391 by jaapjan: make privacy setting description clearer

- modules/social_features/social_core/src/Entity/EntityAutocompleteMatcher.php
- modules/social_features/social_event/modules/social_event_managers/src/Form/SocialEventManagersAddEnrolleeForm.php
We noticed the Add Enrollee autocomplete input field doesn't behave the same as the others for lets say adding members to a group.
We forgot to use the custom selection handler which ensures the correct Social EntityAutocompleteMatcher is used.
In this case:
`social_features/social_core/src/Entity/EntityAutocompleteMatcher.php`
https://jira.goalgorilla.com/browse/DS-6570
The behavior for adding Enrollee's to an event is now similar as the one for adding members to a group.
> DS-6570 - Improvement - Can’t find someone for adding to event

- composer.json
- drupal-org.make
On Course and Challenge group stream and about pages there we see notices:
`Notice: Undefined index: value in MessageTemplate->getText()`
I found the related issue on drupal.org (https://www.drupal.org/project/message/issues/3000026) and applied patch
- https://www.drupal.org/project/message/issues/3000026
This issue reproduced on enterprise projects (ECI demo).
Fix notice caused by message module (Undefined index: value in MessageTemplate->getText()) on custom group types.
> Issue #3000026 by mdeny: Add patch for message to fix Notice: 'Undefined index: value in MessageTemplate->getText()'

- modules/social_features/social_event/modules/social_event_managers/social_event_managers.module
Sometimes non-external Urls are still not routed. This can lead to a hard crash of the platform.
Check if an Url is routed before fetching the routename and parameters.
https://www.drupal.org/project/social/issues/3050192
Sometimes non-external Urls are still not routed. This can lead to a hard crash of the platform. This is fixed now
> 3050192: Check if Url is instanceof Url and check if the Url is routed

- modules/custom/improved_theme_settings/improved_theme_settings.module
The usage of the gradient parameter in the theme settings does not properly check for a non existent theme setting. This causes output to be generated even when the setting is not set. Because the default output with a non-existent value results in the values used for 0, there is no hero gradient being applied.
An <code>isset</code> check is performed but the variable is set a line earlier so this check will always be true.
This change was introduced in [#3044302]. #1282 
Properly utilise the return value of the get-theme setting to check whether we have a usable value instead of using isset. The cast to integer is also not needed because it will be output as string.
https://www.drupal.org/project/social/issues/3051436
The new adjustable hero background …
> Issue #3051436 by Kingdutch: Sub-theme hero gradient broken

- modules/social_features/social_comment_upload/js/comment-upload.js
We encountered issues on SaaS (but could also be on other platforms) where the image gallery in a comment upload would not open anymore after closing.
This was caused by the good old JS firing multiple times. Which would always reopen the modal after closing. You wouldnt be able to see this unless directly but when inspecting the code you would see it being fired several times (up to 15x). This caused a transparent overlay to appear which made sure the images weren't clickable anymore.
- https://jira.goalgorilla.com/browse/DS-6572
In 5.0 we added a nice image upload possibility for attachments in comments. Sometimes the image gallery would not be able to open up anymore after closing. This should now work as supposed to.
> DS-6572 in remembrance of Allo Allo - I shall attach the gallery / click handlers only ONCE

- themes/socialbase/assets/css/cards.css
- themes/socialbase/components/02-atoms/cards/cards.scss
- themes/socialbase/templates/views/views-view.html.twig
When you have no upcoming events and use the site in another language then English that has a longer phrase to describe the absence of events, the texts doesn't wrap as it should. Unsure if it's just this block or more blocks.
Add the ability to move the text to a new line in the card block.
https://www.drupal.org/project/social/issues/3035614
When you have no upcoming events and use the site in another language than English that has a longer phrase to describe the absence of events, the long texts now move to a new line and displayed correctly.
> Issue #3035614 by agami4: Add the ability to move the text to a new line in the card block

- modules/social_features/social_user/src/Form/SocialUserSettingsForm.php
The default settings works fine, switching from the default (stream) to the information page also works. However when switching back to the default the profile page redirect breaks and you end up on an empty profile page.
This feature and the issue was introduced in #1284.
Changed the default route in the settings form from the entity canonical url to `social_user.stream`.
https://www.drupal.org/project/social/issues/3053234
Switching back to the default profile landing page setting now delivers the expected page result to users.
> #3053234: Replaced incorrect route for default profile landing page at user settings

- modules/social_features/social_event/modules/social_event_an_enroll/social_event_an_enroll.module
- modules/social_features/social_event/modules/social_event_an_enroll/social_event_an_enroll.services.yml
- modules/social_features/social_event/modules/social_event_an_enroll/src/EventAnEnrollService.php
- modules/social_features/social_event/modules/social_event_an_enroll/src/Form/EventAnEnrollActionForm.php
- modules/social_features/social_event/modules/social_event_max_enroll/social_event_max_enroll.module
The enroll button for anonymous users is never showing the 'no spots left' disabled button when there was at least one anonymous enrollment.
There was only a check if the current user had an event enrollment. But when there was already one anonymous enrollment, this would always be positive for anonymous visitors as the user ID would be 0.
Refactored the check for authenticated enrollments and added a new one for anonymous enrollments if the module was enabled.
Also moved AN enroll functions to a service, where I also added a function to see if there was a "logged-in" visitor looking at the event.
https://www.drupal.org/project/social/issues/3050760
The event enroll button is now respecting the maximum enrollment limit of events for anonymous visitors.
> Issue #3050760: Ensure event max enroll limit takes anonymous enrollments into account

- modules/custom/activity_basics/activity_basics.api.php
- modules/custom/activity_basics/src/Plugin/ActivityContext/OrganizerActivityContext.php
- modules/custom/activity_basics/src/Plugin/ActivityContext/OwnerActivityContext.php
- modules/social_features/social_event/modules/social_event_managers/social_event_managers.module
When an Event organiser Enrolls to his / her own event they get a notification. Whether that is through the Enroll button or through the "Add Enrollees" management function doesn't matter.
We filter out the actor, we don't want them to receive notifications from actions they did themselves. 
- https://www.drupal.org/project/social/issues/3034356
- https://jira.goalgorilla.com/browse/DS-6568
As an Event Creator or Organiser you accidentally received notifications when you would add or enroll yourself to an event yourself.
> #3034356 - Event Organiser receives notification when (s)he enrolls in his/her own event

- tests/behat/features/capabilities/event-an-enroll/event-max-enroll.feature
- tests/behat/features/capabilities/topic/topic-download-count.feature
1. When Sitemanager does not have permission to go to `admin/config/opensocial` the test is failing.
2. Topic download count test seems to fail if other humans.txt files were already uploaded.
1. Let's go to the configuration page directly.
2. Make the check a bit smarter so we don't care if somebody uploads human 0.txt or humans 200.txt or humans.txt.
not needed
not needed...
> Improve event-max-enroll and topic-download-count test

- modules/social_features/social_user_export/social_user_export.module
When the event export is enabled it gives the event manager the possibility to download the event enrollees, but this fails giving the user an access denied page.
Fix the social_export file download hook to give permission to the author of the file to download it.
https://www.drupal.org/project/social/issues/3053953
We have fixed an issue where the event managers were not able to export the enrollees of their events because of a permissions issue.
> Issue #3053953 by robertragas: fix enrollments export for event managers

- modules/social_features/social_search/src/Form/SearchContentForm.php
- modules/social_features/social_search/src/Form/SearchHeroForm.php
- themes/socialbase/templates/form/form-element--search-input-content.html.twig
Text filed of search form do not have a label describing what kind of textarea it is.
Added label for text field on search forms.
https://www.drupal.org/project/social/issues/3045770
Added label to search form to improve accessibility
> Issue #3045770 by agami4: Add label to search forms

- themes/socialbase/assets/css/message.css
- themes/socialbase/components/04-organisms/message/message.scss
Colors are reserved for the socialblue theme which is good. However, the unread-thread class for the private message module contains no color changes at all in the socialbase theme which can lead to UX issues.
Let socialbase change:
- The background card color to be slightly off-white (from it's default, white).
- The read-indicator a background-color of something like rgba(0,0,0,0.2)
https://www.drupal.org/project/social/issues/2949011
Added new styles for unread thread:
- The background card color to be slightly off-white 
(from it's default, white) background: rgba(0, 0, 0, .02);.
- The read-indicator a background-color of something like rgba(0,0,0,0.2)
> Issue #2949011 by agami4: Add new styles for unread thread card on social base theme

- modules/custom/activity_creator/src/ActivityNotifications.php
When a user marks notifications as read (automatically) this will load activity entities one by one.
Load all activity entities at once.
https://www.drupal.org/project/social/issues/3053668
By refactoring old code we improved the performance of the "mark as read" functionality of the notification centre.
> Issue #3053668: Load all activity entities at once instead of one by one

- themes/socialbase/templates/profile/profile--profile--default.html.twig
Currently when you change display settings of the profile to display more fields these are not displayed without making any required changes to the template.
Add content variable without default fields
https://www.drupal.org/project/social/issues/2975701
When you change display settings of the profile to display more fields these are not displayed without making changes to the profile template. The content variable is now also rendered without default fields so that when you add new fields they will display
> Issue #2975701 by agami4: Add content variable without default fields

- themes/socialbase/templates/node/node--full.html.twig
likes is missing translation in node--full.html.twig from socialbase theme
changed to {% trans %}likes{% endtrans %}
https://www.drupal.org/project/social/issues/3055336
The text indicating the number of likes or comments on content is now translatable even when no Javascript is used.
~Translation for "likes" in node--full.html.twig from socialbase theme was added.~
> Bug 3055336 likes translation

- modules/social_features/social_event/modules/social_event_managers/js/frontUi.js
- modules/social_features/social_group/js/frontUi.js
VBO Javascript for Manage Members and Enrollees is attached too often
Take context into account
The click handlers were added many times because the context of the
attach method was not taken into account.
Additionally the action button was before the temporary placeholder in
the DOM order which caused it to be unclickable.
https://www.drupal.org/project/social/issues/3054601
<h2>Release notes</h2>
An over eager attaching of click handlers in the group member and event enrollee management interfaces caused some duplicate messages when all items were selected. We've had a chat with the click handler and it's no longer overly attached.
> Issue #3054601: VBO Javascript for Manage Members and Enrollees is attached too often

- modules/custom/activity_creator/js/notifications.js
The notification centre in Open Social has a bell with the unread notifications. There is some Javascript code that, when clicked on the notification centre icon, sends a request to the back-end. In the back-end all unread notifications are then marked as read.
First of all there is no check that determines if the notification centre was closed and opened again. In that case no request has to be send as we can assume the notifications are already marked as unread anyway.
Next to that there is no limit on the amount of click handlers attached to the notification centre icon. When using BigPipe there are easily 30 click handlers assigned which all do requests to the back-end to mark notifications as read.
Demonstration of the problem: …
> Issue #3056603: Increased performance for marking notifications as read

- themes/socialbase/yarn.lock
- themes/socialblue/yarn.lock
We got a notification of our libraries being outdated.
Updated all our libraries in the yarn.lock files for social blue and social base.
-
- not needed.
> Update libraries in our yarn.lock files 

- modules/social_features/social_group/social_group.module
Counting group members originally had to load the user profiles of members to make sure the calculation matched the actual members within the group.
Removed custom group membership calculation which isn't necessary any more as it has been fixed within groups. Also generated group operation urls based on routes instead of custom paths.
https://www.drupal.org/project/social/issues/3056651
> #3056651 - Performance optimisation for counting group members

- modules/custom/alternative_frontpage/alternative_frontpage.info.yml
- modules/social_features/social_event/modules/social_event_an_enroll/social_event_an_enroll.info.yml
- modules/social_features/social_event/modules/social_event_an_enroll_enrolments_export/social_event_an_enroll_enrolments_export.info.yml
- modules/social_features/social_event/modules/social_event_max_enroll/social_event_max_enroll.info.yml
I noticed that Social prefix is missing for **Max Event Enroll** module and second word for **Alternative frontpage** is in lowercase.
Add Social prefix and use Uppercase to be consistent.
- None
I think it's not needed.
> Fix Social module names for better consistency

- modules/custom/social_path_manager/social_path_manager.module
1. When the social_group_default_route module is enabled the canonical of groups is changed. The social path module depends on the canonical to be /stream.
2.When a group is saved the tabs are updated, but not showing on the front, only after a cache clear
1. Don't rely on the canonical to be /stream, but get the url based on the canonical, so it can be anything.
2. Also clear the cache tag route_match so they are refreshed.
https://www.drupal.org/project/social/issues/3060880
1.
2. 
1.
We have fixed a bug in the social path manager where it would conflict with the Social Group Default Route module, resulting in group url all having the prefix "steam" after bulk generating the new aliases.
2.
We have fixed a bug in the social path manager where after saving a group, the tabs would still …
> Social Path Manager issues

- modules/social_features/social_landing_page/templates/node--featured.html.twig
- themes/socialbase/templates/node/node--teaser.html.twig
With the growing flexibility in Content visibility, due to the flexible group types, it's more and more important to show what visibility your content has. Posts already show it, now it will also be available in teasers.
Updated the teaser & featured section to show the content visibility label.
- https://www.drupal.org/project/social/issues/3062164
- https://jira.goalgorilla.com/browse/DS-6635
We now clearly indicate the selected visibility for content in overviews and on the stream, this to indicate which users might be able to see the content.
Previews of my local installation:
> DS-6635 - As a AN/LU I want to see the visibility type of content in overviews

- modules/social_features/social_profile/modules/social_profile_fields/src/SocialProfileFieldsBatch.php
Deprecated function: Non-static method Drupal\social_profile_fields\SocialProfileFieldsBatch::performFlushFinishedCallback() should not be called statically in _batch_finished() (line 454 of core/includes/batch.inc)
I added the static keyword to the callback function, because this function is always called statically.
https://www.drupal.org/project/social/issues/3059892
- Go to `/admin/config/opensocial/profile-fields`;
- Deselect fields and save them;
- Flush the profiles. See that the deprecation warning is not shown in the logs.
Updated the static function call.
> Issue #3059892: Added the static keyword to the statically called function

- modules/social_features/social_search/config/install/search_api.index.social_all.yml
- modules/social_features/social_search/config/install/search_api.index.social_content.yml
- modules/social_features/social_search/config/install/search_api.index.social_groups.yml
- modules/social_features/social_search/config/install/search_api.index.social_users.yml
- modules/social_features/social_search/config/install/views.view.search_all.yml
- modules/social_features/social_search/config/install/views.view.search_content.yml
- modules/social_features/social_search/config/install/views.view.search_groups.yml
- modules/social_features/social_search/config/install/views.view.search_users.yml
- modules/social_features/social_search/modules/social_search_autocomplete/config/install/views.view.search_all_autocomplete.yml
Search relevancy sorting should be improved.
Let's work within the limitation of database search and add the following:
* Fallback for creation date (descending = newest on top) after relevancy sort.
* Boost the title 21 times
* Add content type to the index to enable searching for `Pizza event` when searching for events about Pizza.
We also wanted to include Prioritising intact phrases over separate words (e.g. when searching for "Intro call" any exact matches with "Intro call" should prioritise over "Let's plan a call for an introduction.") However that is not possible it seems. We should start with this and in case we want to add this prioritisation later we should consider using Apache SOLR.
https://www.drupal.org/project/social/issues/2948979
title `monthly welcome march 2019`) and …
> Issue #2948979 - Improve search relevancy (node type, creation date and title boost)

- modules/social_features/social_group/social_group.routing.yml
- modules/social_features/social_group/src/Controller/SocialGroupController.php
When you select a group in autocomplete it shows page not found
The group is now redirected to the stream
https://www.drupal.org/project/social/issues/3061282
> Issue #3061282 by albertoalaejos: fix group redirecting issue

- themes/socialbase/assets/css/ajax.css
- themes/socialbase/assets/css/comment.css
- themes/socialbase/assets/css/form-controls.css
- themes/socialbase/assets/css/form-post-create.css
- themes/socialbase/components/02-atoms/form-controls/_input.scss
- themes/socialbase/components/03-molecules/form-elements/autocomplete/ajax.scss
- themes/socialbase/components/04-organisms/comment/comment.scss
- themes/socialbase/components/04-organisms/forms/form-post-create.scss
When loading image from any input form (stream, topic etc.) there's no loader indicating to wait.
Show loading indicator when loading image
https://www.drupal.org/project/social/issues/2984283
When uploading an image in any file attachment form (post, comment and topic for example) there is now a loader which indicate that the user should wait for the image to upload.
> Issue #2984283 by agami4: Add loader indicator when loading image

- modules/social_features/social_event/modules/social_event_managers/social_event_managers.module
When selecting all entities of a view (event enrollments or group memberships) and performing a bulk action on them you end up on a 404 or 403 page.
By adding an extra check in the custom batch callback function for views that are executed, rather than just checking for the final batch, we can make it work. We have to also add the custom batch callback function for this second batch job after the first pre-populating one is finished.
https://www.drupal.org/project/social/issues/3063713
We have created a fix for the views bulk operations module which is used to execute actions on multiple people throughout multiple pages such as exporting event enrollees. Normally when selecting all members across al pages you would end up on a 404/403 page when trying to export, but this has been solved.
> #3063713 - bulk actions on all pages fails for event enrollments

- modules/social_features/social_event/modules/social_event_managers/social_event_managers.routing.yml
- modules/social_features/social_event/modules/social_event_managers/social_event_managers.services.yml
- modules/social_features/social_event/modules/social_event_managers/src/Access/AddEnrolleeAccessCheck.php
Event Organisers get an access denied on adding enrollees, also the Add Enrollee button is gone.
I've created a custom access check that doens't look at Roles & Permissions alone but uses the Service that already was available that checks whether or not a user is able to add enrollees to an event.
https://www.drupal.org/project/social/issues/3066600
There was an issue where Event Organisers weren't able to add people to their events. This is now solved so next to Site Managers & Content Managers, Event Organisers can fully manage their events as well.
> Issue #3066600 make sure EO can add enrollees to their event

- modules/custom/activity_send/modules/activity_send_email/activity_send_email.module
- modules/custom/activity_send/modules/activity_send_email/src/Plugin/EmailFrequency/Immediately.php
- modules/custom/activity_send/modules/activity_send_email/src/Plugin/QueueWorker/ActivityDigestWorker.php
- modules/custom/activity_send/modules/activity_send_email/templates/digestmail.html.twig
- modules/custom/activity_send/modules/activity_send_email/templates/directmail.html.twig
- modules/social_features/social_swiftmail/config/schema/social_swiftmail.schema.yml
- modules/social_features/social_swiftmail/social_swiftmail.install
- modules/social_features/social_swiftmail/social_swiftmail.module
- modules/social_features/social_swiftmail/src/Form/SocialSwiftmailSettingsForm.php
- themes/socialbase/templates/swiftmailer.html.twig
Multiple problems occurred with the custom e-mail settings.
1. The applied text format settings in the template configuration of the Social Swiftmail are not saved correctly.
2. Custom headers and/or footer were not always displayed when set.
3. The setting for removal of the Open Social branding in e-mails wasn't respected.
4. Permissions for the custom e-mail template settings aren't set.
1. The text format settings are added to the form submit and configuration. The settings are now also added to the form and checked if they are set for a before applying the default when they aren't. The settings is also checked when building the e-mail markup.
2. Both the header and footer configuration settings are now checked in the _social_swiftmail.module_ if they are set and the header/footer are …
> Issue #3019458 by royharink: Issue with Custom email header footer settings page

- modules/social_features/social_search/modules/social_search_autocomplete/config/install/views.view.search_all_autocomplete.yml
- modules/social_features/social_search/modules/social_search_autocomplete/social_search_autocomplete.post_update.php
If you have more than 1000 users
and if you search for a user who has nid 1006
the search result displays /user/1,006
Make sure there is no separator. 
https://www.drupal.org/project/social/issues/3067525
If you have more than 1000 users, groups or pieces of content the search autocomplete has a comma in the URL which causes a wrong link to the piece of content.
> Issue #3067525 search autocomplete separator comma

- composer.json
- drupal-org.make
When a message is rendered on the cron using a filter format that has lazy loading enabled it will reach function `lazy_disabled_by_path`
`$path_alias = \Drupal::service('path.alias_manager')->getAliasByPath($current_path);`
if `$current_path` doesn't start with a slash it will result in a `InvalidArgumentException: Source path has to start with a slash. in Drupal\Core\Path\AliasManager->getAliasByPath() (line 186 of /app/html/core/lib/Drupal/Core/Path/AliasManager.php).`
In our case it's because a message is rendered with a token as part of the href. 
See part of the configuration below
```
value: '<p><a href="[social_event:enrolled_event_url]">[social_event:enrolled_user]</a> has enrolled to the event [social_event:event_iam_organizing] you are organizing</p>'
format: full_html
``` …
> Issue #3071335 by ronaldtebrake: implement patch for lazy loading

- modules/custom/social_lazy_loading/README.txt
- modules/custom/social_lazy_loading/composer.json
- modules/custom/social_lazy_loading/social_lazy_loading.install
- modules/custom/social_lazy_loading/social_lazy_loading_images/social_lazy_loading_images.info.yml
- modules/custom/social_lazy_loading/social_lazy_loading_images/social_lazy_loading_images.services.yml
- modules/custom/social_lazy_loading/social_lazy_loading_images/src/SocialLazyLoadingImageDisplayOverride.php
Images that aren't necessarily shown to a user are loaded on a full page load. We can also load them after the page is shown. Here comes the lazy loading!
We use the lazy loading module to override our image fields and add the lazy loading capability to it.
For all of the above the images should be lazy loaded with exception of the images in your viewport or those that are background urls (like the hero).
We have a new addition to our lazy loading module, images that are provided by Open Social can be lazy loaded now by enabling the social_lazy_loading_images module.
> #3065010 - Lazy load images

- modules/social_features/social_search/src/Plugin/views/filter/SocialDate.php
When going to the user search and not using the filter you get a lot of notices.
We should not call parent::acceptExposedInput when operator is NULL.
https://www.drupal.org/project/social/issues/3073513
Not necessary since the filter is not yet released (still only in dev branch)
> Issue #3073513 : prevent notices in the search when filter isn't used

- .browserslistrc
Passing <code>browsers</code> configuration to tools such as Autoprefixer and Babel is deprecated. Instead it is recommended to either add a <code>browsers</code> key to a <code>package.json</code> file or add a <code>.browserslistrc</code> file. This file can be in any directory above where the tools are run.
Since we have many modules and themes in Open Social that should all support the same browser set I suggest adding a <code>.browserslistrc</code> to the root of the project. This will then be picked up by any tool that needs it that works on code for Open Social. 
The alternative of adding an entry to <code>package.json</code> files is harder to maintain and can lead to inconsistencies between features.
The chosen value in the file is similar to …
> Issue #3067268: Add a .browserslistrc file to the repository

- tests/behat/features/capabilities/like/like-post-stream.feature
- tests/behat/features/capabilities/post/post-comments.feature
- tests/behat/features/capabilities/post/post-create.feature
- tests/behat/features/capabilities/post/post-photo-create.feature
Four behat tests are failing on all enterprise sites on step: _And I should be on "/stream"_ .
- like-post-stream.feature
- post-comments.feature
- post-create.feature
- post-photo-create.feature
This problem occurs when the Redirect module is enabled (social_path_manager module requires it in the dependencies)
Fix those behat tests in distro by removing step: _And I should be on "/stream"_
- https://jira.goalgorilla.com/browse/YANG-1265
- like-post-stream.feature
- post-comments.feature
- post-create.feature
- post-photo-create.feature
Improve behat tests related with /stream
> Issue by makishima: Fix failing behat tests related with /stream on enterprise sites

- modules/social_features/social_activity/social_activity.tokens.inc
Error in notification window when group or groupcontent is missing (still to be determined what exact root cause is).
Let's make the token handling a bit more defensive.
https://www.drupal.org/project/social/issues/3075854
If there is a notification in the notification bar for a group or group content item which does not exist anymore the token replacement code should not crash. The code is now more defensive and thus will prevent the site from breaking on the menu bar resulting in missing content and blocks.
not needed
> Issue #3075854 by jaapjan: defensive coding in the activity token handling

- modules/custom/download_count/download_count.module
A triple foreach loop was getting used for extracting the file's parent properties like type and id.
Replace with a database query.
https://getopensocial.atlassian.net/browse/TB-2773
1. Download a file and observe the **download_count** table. The download count for that file id should increase upon each download.
N.A
N.A
> TB-2773: Replaced triple for each loop with a database query to extract file's parent properties.

- modules/custom/activity_creator/src/ActivityFactory.php
- modules/social_features/social_event/social_event.tokens.inc
When using the JSON API you could encounter some error messages like:
```
The controller result claims to be providing relevant cache metadata, but leaked metadata was detected. Please ensure you are not rendering content too early.
This has to do with early rendering. Most likely in the toUrl->toString calls on entities.
```
Let's rewrite the code.
https://www.drupal.org/project/social/issues/3081555
In the token handling of event enrolments there was some leaked cacheable metadata. This has now been solved.
n/a
> Issue #3081555 by jaapjan: add BubbleableMetadata.

- .travis.yml
1. We still use PHP 7.1 instead of PHP 7.3 in Travis set-up.
2. Install update is failing on OS 5.0.0.
1. Let's update. It shouldn't have any effect other than on the composer install.
2. Let's use OS 6.0.0 instead.
n/a
N/a
> Update php in Travis configuration to 7.3.

- modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_view_display.group.flexible_group.hero.yml
- modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_view_display.group.flexible_group.small_teaser.yml
- modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_view_display.group.flexible_group.stream.yml
- modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_view_display.group.flexible_group.teaser.yml
- modules/social_features/social_group/modules/social_group_flexible_group/config/install/field.field.group.flexible_group.field_group_address.yml
- modules/social_features/social_group/modules/social_group_flexible_group/config/install/field.field.group.flexible_group.field_group_description.yml
- modules/social_features/social_group/modules/social_group_flexible_group/config/install/field.field.group.flexible_group.field_group_image.yml
- modules/social_features/social_group/modules/social_group_flexible_group/config/install/field.field.group.flexible_group.field_group_location.yml
- modules/social_features/social_group/modules/social_group_flexible_group/config/install/field.field.group_content.flexible_group-group_membership.group_roles.yml
- modules/social_features/social_group/modules/social_group_flexible_group/config/install/group.role.flexible_group-83776d798.yml
- modules/social_features/social_group/modules/social_group_flexible_group/config/install/group.role.flexible_group-a416e6833.yml
- modules/social_features/social_group/modules/social_group_flexible_group/config/install/group.role.flexible_group-anonymous.yml
- modules/social_features/social_group/modules/social_group_flexible_group/config/install/group.role.flexible_group-ba5854c29.yml
- modules/social_features/social_group/modules/social_group_flexible_group/config/install/group.role.flexible_group-group_admin.yml
- modules/social_features/social_group/modules/social_group_flexible_group/config/install/group.role.flexible_group-group_manager.yml
- modules/social_features/social_group/modules/social_group_flexible_group/config/install/group.role.flexible_group-member.yml
- modules/social_features/social_group/modules/social_group_flexible_group/config/install/group.role.flexible_group-outsider.yml
- modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.api.php
- modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
- modules/social_features/social_group/modules/social_group_flexible_group/src/Access/FlexibleGroupContentAccessCheck.php
- modules/social_features/social_group/modules/social_group_flexible_group/src/SocialGroupFlexibleGroupConfigOverride.php
- modules/social_features/social_group/modules/social_group_secret/social_group_secret.module
- modules/social_features/social_group/modules/social_group_secret/src/SocialGroupSecretConfigOverride.php
- social.profile
Flexible group and secret group are not available to enable during installation. Mostly curious to see if there are any regressions with these module(s) enabled.
Let's add those options and let's install flexible group by default.
https://www.drupal.org/project/social/issues/3081610
https://www.drupal.org/project/social/issues/3074028
https://www.drupal.org/project/social/issues/3074032
We have fixed several individual tickets and have added flexible groups to the profile for installation through UI.
> Flexible group several fixes see issue for d.org issues & Optional UI install.

- modules/social_features/social_group/social_group.module
- modules/social_features/social_group/social_group.services.yml
- modules/social_features/social_group/src/Controller/SocialGroupListBuilder.php
- modules/social_features/social_group/src/SocialGroupMembersCount.php
Currently there are two places in Open Social where a count is being done for the amount of members in a group. This shows up in the group overview, but also on user profiles or wherever a group teaser shows up.
The other one is in the admin page of groups.
What it does is get all the member entities of a group and then does a count on this. When a group has over 30k members this will cause a timeout.
Query the database, only getting the information you need instead of all the entities and then counting them which is very heavy.
https://www.drupal.org/project/social/issues/3084268
We changed the way we count the group members making it more performant. Because groups are used in a lot of places of Open Social the difference should be noticeable for everybody, but especially for Open …
> Issue #3084268 by robertragas: Optimize group membership count

- themes/socialbase/assets/css/dropdown.css
- themes/socialbase/components/03-molecules/dropdown/dropdown.scss
If dropdown of notification menu does not have messages, arrow on 'All notifications' button jumps to a new row
Should increase width for this dropdown
https://www.drupal.org/project/social/issues/3076279
Update 'min-width' for all dropdown.
> Issue #3076279 by agami4: Update dropdown width

- modules/social_features/social_group/social_group.module
Secret group doenst have defaults for visibility settings, also added a defensive check for when other group types, it needs to have the field available on the entity for us to check it.
https://www.drupal.org/project/social/issues/3077289
We have made sure there are sane defaults for the secret group which is now available in Open Social.
> #3077289 - Secret group doesnt have defaults for visbility settings

- themes/socialblue/assets/css/brand.css
- themes/socialblue/components/brand.scss
Geolocation Maps colors can't be configured
- Change the use of #1f7ea7 to $brand-secondary
- Remove the opacify usage which changes the color to something that won't be replaced.
https://www.drupal.org/project/social/issues/3071038
You can change color of clusters on the map
> Issue #3071038 by agami4: Update color for clusters

- tests/behat/features/capabilities/group/group-edit-type.feature
We are not testing the text. I think we should just remove this actually. It might have failed because the batch processed too quickly. Important thing is that the type is changed. That is what we are testing.
Commented step and text is removed.
Not necessary.
> Issue #3047912 by jaapjan: remove check text step in group-edit-type.feature

- modules/custom/social_file_private/social_file_private.services.yml
- modules/custom/social_file_private/src/SocialFilePrivateTextEditorConfigOverride.php
Configuration service is injected via Drupal service class.
Is injected via dependency injection now.
https://www.drupal.org/project/social/issues/3030233
will follow
> Issue #3030233 Don't use existing configuration on Private text editor override class

- modules/custom/social_demo/developer/content/entity/event.yml
- modules/custom/social_demo/developer/content/entity/topic.yml
When you need to test certain use-cases it can be handy to have demo content ready. Example is testing the [search relevancy](https://github.com/goalgorilla/open_social/pull/1431) sorting.
Let's add a developer content folder in social_demo.
You can now create demo content with `drush sda topic event --profile=developer`
n/a
Not necessary.
> Add developer demo content folder and some demo files [skip ci]

- modules/social_features/social_post/social_post.install
- modules/social_features/social_post/social_post.post_update.php
The function social_post_update_8601 is being executed with every database update. Because the module is called social_post Drupal actually thinks its a hook_post_update. See: https://www.drupal.org/project/drupal/issues/2880361
It’s changing configuration, this should happen in a post_update hook and not an update hook. So moving it to social_post_post_update_8601_administer_post_permissions in social_post.post_update.php solves the issue for now.
https://www.drupal.org/project/social/issues/3085176
Due to naming conventions the social_post_update_8601 was being executed in every database update. We've moved the function to a post_update so it should only execute once.
> Issue #3085176: move social_post_update hook to post_update

- modules/social_features/social_profile/modules/social_profile_privacy/social_profile_privacy.module
In social_profile_privacy_form_alter(), $account is not checked for being NULL when the parameter user is not found in URL. This blocks any user to edit profiles.
Add a null check.
https://www.drupal.org/project/social/issues/3085803
Introduces an empty check in social_profile_privacy_form_alter in social_profile_privacy module.
N.A
> Added conditional check to account object to be null.

- modules/custom/social_lazy_loading/social_lazy_loading_images/social_lazy_loading_images.services.yml
- modules/custom/social_lazy_loading/social_lazy_loading_images/src/SocialLazyLoadingImageDisplayOverride.php
- modules/custom/social_lazy_loading/src/SocialLazyLoadingTextFormatOverride.php
The `SocialLazyLoadingImageDisplayOverride` and `SocialLazyLoadingTextFormatOverride` are checking for existing config. This is adding an extra few 100ms to a page request as this code is executed via `lazy_is_enabled()` in `lazy.module`.
Let's remove the configfactory injects inside these overrides and simplify the code a bit.
https://www.drupal.org/project/social/issues/3085504
The configuration overrides in Social Lazy Load are optimised by removing existing configuration checks.
> Issue #3085504: Improve performance of ConfigOverrides in Social Lazy Load

- modules/social_features/social_group/modules/social_group_secret/social_group_secret.module
When you edit a node which is posted in the community (so not in any group) and the secret group module is enabled you'll see a notice on every edit node page.
```
Notice: Undefined offset: 0 in social_group_secret_form_node_form_alter() (line 168 of profiles/contrib/social/modules/social_features/social_group/modules/social_group_secret/social_group_secret.module).
```
Made the code defensive.
https://www.drupal.org/project/social/issues/3086219
When a node wasn't posted in any group and the secret group module is enabled there was be a notice on the node form. This has now been solved.
> Issue #3086219: Prevent notice in social_group_secret_form_node_form_alter()

- modules/social_features/social_profile/modules/social_profile_privacy/social_profile_privacy.install
- modules/social_features/social_profile/modules/social_profile_privacy/social_profile_privacy.module
- modules/social_features/social_profile/modules/social_profile_privacy/social_profile_privacy.post_update.php
- modules/social_features/social_profile/modules/social_profile_privacy/social_profile_privacy.services.yml
- modules/social_features/social_profile/modules/social_profile_privacy/src/EventSubscriber/ConfigEventsSubscriber.php
- modules/social_features/social_profile/modules/social_profile_privacy/src/Plugin/search_api/processor/RestrictedNameProcessor.php
- modules/social_features/social_profile/modules/social_profile_privacy/src/RestrictedNameProcessorOverride.php
- modules/social_features/social_search/config/install/search_api.index.social_all.yml
- modules/social_features/social_search/config/install/search_api.index.social_content.yml
- modules/social_features/social_search/config/install/search_api.index.social_groups.yml
- modules/social_features/social_search/config/install/search_api.index.social_users.yml
- tests/behat/features/capabilities/profile/restricted-full-name.feature
The Social Profile Privacy allows hiding of real names in search for users that have a nickname filled in. This is currently implemented using some quite complex query conditions. This leads to some edge cases where this malfunctions.
Re-implement as a Search API processor. This allows us to create a field that contains the value for restricted users and allows the value for unrestricted users to live next to it. In the query alter we can then simply disable fields the user does not have access to. This creates a more robust solution.
https://www.drupal.org/project/social/issues/3084948
- See `restricted-full-name.feature` behat test.
The real name restriction has been reworked to provide a more performant and robust solution.
> TB-2352 Move to Search API Processor for restricted names

- tests/behat/features/capabilities/private-message/create-private-message.feature
Create private message gives false negative many times.
```
Scenario: Successfully send a private message to another user.                                                           # /var/www/html/profiles/contrib/social/tests/behat/features/capabilities/private-message/create-private-message.feature:8
Given I enable the module "social_private_message"                                                                     # Drupal\social\Behat\SocialDrupalContext::iEnableTheModule()
Given users:                                                                                                           # Drupal\social\Behat\SocialDrupalContext::createUsers()
| name        | mail                  | status |
| PM User One | pm_user_1@example.com | 1      |
| PM User Two | pm_user_2@example.com | …
```
> Fix behat test create private message false negatives

- modules/custom/download_count/download_count.module
In download count module we implement hook_ENTITY_TYPE_access for files which adds a file download count for every downloaded file. However this code is also triggered for comment attachments. Depending on the settings or user permissions some files are excluded and the download count won't be adjusted. The file cache tags are invalidated for every file download.
Let's do the invalidating of the cache tags only when the file download count is actually changed.
https://www.drupal.org/project/social/issues/3086229
The download count should only invalidate the file cache for a file download if the file download usage is updated.
> Issue #3086229: Download count: Invalidate file cache tags only when needed

- modules/social_features/social_landing_page/social_landing_page.module
- themes/socialbase/src/Plugin/Preprocess/Page.php
Currently, it is not possible to override or add attributes (classes) to page template from modules like landing page or courses.
Allow adding page content attributes from modules by checking if attributes already exist in theme preprocess. 
https://www.drupal.org/project/social/issues/3087021
We allow to add attributes (classes) to page template from modules and it will be not overridden by theme.
> Issue #3087021: Allow to add page content attributes from modules

- modules/social_features/social_search/social_search.services.yml
- modules/social_features/social_search/src/EventSubscriber/RedirectSubscriber.php
When using the pagination in the search Users page you see an error: "An illegal choice has been detected. Please contact the site administrator." It most likely has to do with the exposed filters.
Steps to reproduce are:
- Go to search/users
- Click on page 2
- You’ll see an error and no results: An illegal choice has been detected. Please contact the site administrator.
Look into the issue and make sure there is proper default filter available so the error will be resolved.
https://www.drupal.org/project/social/issues/3085806
follows
> Issue #3085806: Temporary solution pagination search users

- modules/social_features/social_search/src/Plugin/views/filter/SocialDate.php
When filtering on Event, adding a start date exposed filter value and then switching to topic/event ensures this filter also applies to the others.
We now check this in the AcceptedExposed input to ensure we only allow these values as input when "event" is selected.
We ensure that searching for something else than Events in the search now gives the expected results.
> Issue #3087098: Event date filter shouldn't apply to others. 

- modules/social_features/social_event/modules/social_event_an_enroll/social_event_an_enroll.module
- modules/social_features/social_event/modules/social_event_an_enroll/src/EventAnEnrollOverride.php
- modules/social_features/social_event/modules/social_event_an_enroll_enrolments_export/social_event_an_enroll_enrolments_export.module
- modules/social_features/social_event/modules/social_event_an_enroll_enrolments_export/src/SocialEventAnEnrollEnrolmentsExportOverrides.php
- modules/social_features/social_event/modules/social_event_managers/social_event_managers.module
- modules/social_features/social_group/modules/social_group_members_export/src/SocialGroupMembersExportOverrides.php
1.  Issues with installation caused a lot of the issues to appear.
2. When the Social AN Enrollment is enabled you see two "Send Email" actions on event enrollment management pages. Due to a form_alter that doesn't apply.
1. Updated the release branch with a new composer.lock file
2. Make sure we skip the form alter, instead we use config override. This is much more stable since the form render array could change easily (let's say on a VBO update). The id of the Plugin action doesn't change unless we change our plugin.
https://www.drupal.org/project/social/issues/3087004#comment-13293889
https://getopensocial.atlassian.net/browse/DS-6930
https://getopensocial.atlassian.net/browse/DS-6912
https://getopensocial.atlassian.net/browse/DS-6911
https://getopensocial.atlassian.net/browse/DS-6915 …
> Issue #3087004: VBO - 7.0 - Updates

- modules/custom/social_demo/src/Plugin/DemoContent/EventType.php
When running command drush sda event_type you will see fatal error:
Fatal error: Declaration of Drupal\social_demo\Plugin\DemoContent\EventType::createContent() must be compatible with Drupal\social_demo\DemoTaxonomyTerm::createContent($generate = false, $max = NULL) in /var/www/html/profiles/contrib/social/modules/custom/social_demo/src/Plugin/DemoContent/EventType.php on line 18
Make the method compatible with parent method.
https://www.drupal.org/project/social/issues/3088530
Generating demo event types did not work because of a fatal error. This has now been resolved by making the method compatible with the parent method.
> Issue #3088530: make EventType::createContent() compatible with parent method

- modules/social_features/social_comment_upload/js/comment-upload.js
Likes are not available for several users on IE11
Remove duplicate entries from the js options (`modules/social_features/social_comment_upload/js/comment-upload.js`), because it's broke other scripts.
https://www.drupal.org/project/social/issues/3090562
https://getopensocial.atlassian.net/browse/YANG-1360
* Go to the site by IE11
* Go to any page with comments and like/dislike functionality
* The likes/dislike functionality should work correctly
A duplicate value in the Javascript for Social Comments caused scripts to stop working in Internet Explorer 11. The duplicate values have been removed.
> Issue #3090562 by rolki: Likes are not available for several users on IE11

- translations.php
Sometimes the latest version of Open Social changes strings. These
strings will be picked up in the translation workflow. However, the old
strings that were changed or removed will be removed from translation
source files. This can cause translations to go missing for platforms
running older version.
To fix this we create this dummy file that can hold the old versions of
these strings so that they'll remain translatable in Weblate.
[ Internal quick-fix, no issue created ] 
Not applicable
Not needed.
> Add file that can store legacy translations

- .github/PULL_REQUEST_TEMPLATE.md
For more info, check #1600.
No one knows about the `translations.php` file and what it is for.
By adding a step to the PR template, people will (likely) no longer forget it.
n/a
n/a
n/a
> Update PR template to mention `translations.php`

- themes/socialbase/templates/form/input--form-control--date.html.twig
When creating an event you have the option to select a date. This date nicely shows a pop-up calendar, but this is not visible at first because of the autocomplete completely blocking it. This is very annoying and easily fixable but turning off the autocomplete for this field.
Disable autocomplete for date field
https://www.drupal.org/project/social/issues/3005853
The autocomplete was disabled for a date field.
> Issue #3005853 by agami4: Disable autocomplete for date field

- modules/social_features/social_comment/src/Form/SocialCommentAdminOverview.php
On the admin comment overview page we show all the comments.
We also try to render a "translate" operations link if the content translation is turned on. However when a content item is deleted, but the reference for some reason stays behind in the comment an access check for the translate link will fail.
An extra check is added to make sure the commented entity still exists.
https://www.drupal.org/project/social/issues/3091105
In a rare occasion where the commented entity no longer exists, but the reference to it in the comment does, a fatal error might occur on the comment admin overview page.
> #3091105: Prevent fatal error by checking if the commented entity still exists

- .travis.yml
We don't lock a core version, which means when core releases updates our patches on 6.0.0 might fail. Which usually isn't an issue because we can control it ourselves in updates, but with travis we test the update path of Open Social and do this from a tagged version. 
Therefor it will always fail on the composer install with the latest core version.
Test the update path from 8.x-6.x-dev, allowing us to backport any core patches when necessary.
- not needed
Not needed
> Travis issues occured due to core patch not working - Make it green again!

- modules/social_features/social_event/src/Controller/SocialEventController.php
- modules/social_features/social_group/social_group.routing.yml
- modules/social_features/social_group/src/Controller/SocialGroupController.php
- modules/social_features/social_topic/social_topic.routing.yml
- modules/social_features/social_topic/src/Controller/SocialTopicController.php
Currently, User Groups and Topics pages URLs can be accessed only with URLs in the format: `/user/ID/groups`, `/user/ID/topics`, in this way it is not possible to place them on landing pages or menu links.
Add redirect URLs: `/my-groups`, `/my-topics`, similar like we have for `/my-events`
- https://www.drupal.org/project/social/issues/3087870
Add redirect URLs: `/my-groups`, `/my-topics` for redirect to the user groups and topics overview pages.
> Issue #3087870 by ribel: Add routes for redirect to the user groups and topics overview pages

- modules/social_features/social_event/modules/social_event_managers/src/Plugin/views/field/SocialEventManagersViewsBulkOperationsBulkForm.php
- modules/social_features/social_group/src/Plugin/views/field/SocialGroupViewsBulkOperationsBulkForm.php
- translations.php
The text "Select / unselect all @count results in this view'" and "Clear selected Members" in Manage members tab in groups are a bit misleading and can be improved for better reading.
//s "Select / unselect all @count results in this view'" to "Select / unselect all @count members across all the pages"
//s "Clear all selected members" to "Clear selection"
https://www.drupal.org/project/social/issues/3094403
N.A
N.A
> Improved the bulk operation actions description text.

- themes/socialblue/assets/css/brand.css
- themes/socialblue/components/brand.scss
I want to change the color scheme but it doesn't affect some particular parts of the ideation module
Add particular parts of the ideation module to the brand file
https://www.drupal.org/project/social/issues/3087741
The ideation extension now properly respects theme color settings set by sitemanagers.
**Maintainer note:** The ideation extension is not currently public so this probably doesn't affect distribution users.
> Issue #3087741: Color scheme should apply to ideation module

- modules/social_features/social_landing_page/css/social_landing_page.section.hero_small.css
- modules/social_features/social_landing_page/css/social_landing_page.section.hero_small.scss
The small hero landing page spacing of elements is off
Add more spaces between subtitle and buttons
https://www.drupal.org/project/social/issues/3087778
Add space between subtitle and button for the small hero banner on the landing page
> Issue #3087778 by agami4: Add space between subtitle and buttons for the small hero banner

- modules/custom/social_language/src/Plugin/UserExportPlugin/UserLanguage.php
- modules/custom/social_language/src/Plugin/UserExportPlugin/UserLanguageCode.php
The user export does not contain the users (preferred) language. Specially for multilingual platforms this is useful information.
Added the preferred language of the user to the export. Defaults to the site default when it is not known.
https://www.drupal.org/project/social/issues/3098456
It's important to know which language your users prefer in your communication to them. We now add the language, if known, to the user export.
n/a
n/a
> #3098456: Add language as a column to the user export

- translations.php
"Names and profile image" is not yet translatable
Adding this string to the translations.php file makes it indexable by Weblate and eventually translatable on the website.
n/a
n/a
n/a
n/a
n/a
> Add untranslatable string to the list

- modules/custom/activity_creator/activity.page.inc
- modules/custom/activity_creator/src/ActivityNotifications.php
- modules/custom/activity_creator/src/Controller/NotificationsController.php
Notifications stay grey even after you have seen them. This is confusing and disables user to differentiate b/w new notification and old notification.
Change the logic for background colour in https://github.com/goalgorilla/open_social/blob/8.x-8.x/modules/custom/activity_creator/activity.page.inc#L113
1. Read status from activity_notification_status table
2. Notifications with status 1 will have grey colour
3. Others should have white colour
https://www.drupal.org/project/social/issues/3098141
N.A
N.A
N.A
> Updated the logic to render notification colors and added a method in notifications service to get status of a notification.

- modules/social_features/social_event/modules/social_event_managers/social_event_managers.module
- translations.php
Strings related to the bulk operations cannot be translated.
Added the strings to the `translations.php` file as a work-around for now.
n/a
n/a
n/a
n/a
> Add untranslatable strings to work-around

- modules/social_features/social_user/src/Plugin/Action/SocialSendEmail.php
- translations.php
When sending an email to a group of people from within groups, the following text is the description of the Reply-to field:
`A Reply-To address is the email address that receives messages sent from those who select Reply in their email clients.`
For users with smaller technical knowledge, this could be confusing or not sufficient enough.
Change the translatable to be more explanatory about what the field is about:
`The email you are about to send is sent from the platform's email address. If you wish to receive replies on this email on your own email address, please specify your email address in this field.`
[https://www.drupal.org/project/social/issues/3100539]
(https://www.drupal.org/project/social/issues/3100539)
> Issue #3100539 by sjoerdvandervis: Make the description of the Reply-to field more explanatory

- themes/socialblue/assets/css/brand.css
- themes/socialblue/assets/css/page-node.css
- themes/socialblue/components/05-templates/page-node/page-node.scss
- themes/socialblue/components/brand.scss
The links in the description of the paragraphs on the landing page don't have styles if you use custom font
Add primary color for all links
https://www.drupal.org/project/social/issues/3095296
https://getopensocial.atlassian.net/browse/YANG-1620
All links have a primary color on the description of the paragraphs on the landing page
> Issue #3095296 by agami4: Add primary color for links on the paragraphs on the landing page

- modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_form_display.group.flexible_group.default.yml
- modules/social_features/social_landing_page/config/optional/core.entity_view_display.group.flexible_group.featured.yml
When a Flexible group is added as featured content on a landing page, the image is not displayed correctly.
The flexible group had no display mode for Featured. This is fixed by adding an optional configuration to the social_landing_page module, which defines that the image, address and location name are shown when the flexible group is used as featured content. Furthermore, a crop type is added when adding a new flexible group (`hero_small`), as this is used as image when using the flexible group as featured content.
https://www.drupal.org/project/social/issues/3086434
> Issue #3086434 by sjoerdvandervis: Flexible groups on landing pages

- themes/socialbase/assets/css/admin-toolbar.css
- themes/socialbase/assets/css/navbar.css
- themes/socialbase/components/04-organisms/admin-toolbar/admin-toolbar.scss
The explore dropdown menu is shown behind the event map when it's enabled (see screenshot below).
Adjust our manual z-index on the navbar so that both the admin toolbar and the regular OS menu are shown correctly.
https://www.drupal.org/project/social/issues/3106782
> Issue #3106782 by robertragas, sjoerdvandervis: Changed z-index to be able to use the admin toolbar

- modules/social_features/social_landing_page/css/social_landing_page.section.accordion.css
- modules/social_features/social_landing_page/css/social_landing_page.section.accordion.scss
<h2>Problem:</h2>
Including the Accordion section in a landing page takes up huge chunks of empty space. This is disruptive to the page flow and causes the need for excessive scrolling.
<h2>Solution:</h2>
Reduce the top and bottom space around accordions
https://www.drupal.org/project/social/issues/3102298
The top and bottom spacing for accordion blocks have been reduced because it was taking up excessive space on landing pages.
> Issue #3102298 by agami4: Update top and bottom spaces for the accordion block

- modules/social_features/social_private_message/config/install/core.entity_view_display.private_message_thread.private_message_thread.default.yml
Can't see a list all messages in private channel
Change `message_count` limit from 7 to 30 messages
https://getopensocial.atlassian.net/browse/YANG-1254
https://www.drupal.org/project/social/issues/3098067
Create a private channel with somebody and try to write more than 7 messages
The number of messages has been increased, because version 1.2 and 1.3 of the `https://www.drupal.org/project/private_message` module does not provide the ability to load old messages, but only shows the last 7.
Such functionality is provided in version 2.0, but version 2.0 is not compatible with social_private_messages, and additional time is required to fix the problems. And this is the simplest and fastest solution.
> Issue #3098067 by rolki: Only the last 7 private messages are displayed

- themes/socialbase/assets/css/teaser.css
- themes/socialbase/components/03-molecules/teaser/teaser.scss
Title cropped in the teasers
Add more max height for the title on the teasers
https://www.drupal.org/project/social/issues/3087783
The title does not crop in the teaser on the Landing page
> Issue #3087783 by agami4: Add more max height for the title on the teasers

- modules/social_features/social_landing_page/social_landing_page.module
Landing Page Template is not picked up when using it as 404 page.
Use hook_theme_suggestions_HOOK_alter() to use page__node__landing_page as template.
https://www.drupal.org/project/social/issues/3105639
**Before**:
**After**:
N.A
N.A
N.A
> Issue #3105639: Added hook_theme_suggestions_alter to add landing page template on 404.

- modules/social_features/social_user_export/config/features_removal/system.action.user_export_user_action.yml
- modules/social_features/social_user_export/social_user_export.features.yml
See problem definition in [#3092272: [Meta] [PP-1] Moving away from features.](https://www.drupal.org/project/social/issues/3092272)
Remove the `module.features.yml` file
- Move the default editable config from `hook_install()` into a module's `config/install/*.yml` file.
- If `hook_install` alters configuration from other modules, consider whether we should include the config file in the profile's `config/install` folder to overwrite it instead
- Remove any `_module_set_defaults` function
https://www.drupal.org/project/social/issues/3102806
> Issue #3102806 by Kingdutch: Remove features from Social User Export

- modules/social_features/social_editor/config/features_removal/editor.editor.basic_html.yml
- modules/social_features/social_editor/config/features_removal/editor.editor.full_html.yml
- modules/social_features/social_editor/config/features_removal/editor.editor.mail_html.yml
- modules/social_features/social_editor/config/features_removal/filter.format.basic_html.yml
- modules/social_features/social_editor/config/features_removal/filter.format.full_html.yml
- modules/social_features/social_editor/config/features_removal/filter.format.mail_html.yml
- modules/social_features/social_editor/config/features_removal/filter.format.restricted_html.yml
- modules/social_features/social_editor/config/features_removal/filter.format.simple_text.yml
- modules/social_features/social_editor/social_editor.features.yml
Removes the features file and adds default configuration as settings
file in the config/install folder.
See problem definition in #3092272: [Meta] Moving away from features. 
Remove the social_editor.features.yml file
https://www.drupal.org/project/social/issues/3098051
https://getopensocial.atlassian.net/browse/TB-3522
The social_editor module is no longer managed by features.
> Removed features.yml file from Social Editor.

- modules/social_features/social_content_report/config/features_removal/core.entity_form_display.flagging.report_comment.default.yml
- modules/social_features/social_content_report/config/features_removal/core.entity_form_display.flagging.report_node.default.yml
- modules/social_features/social_content_report/config/features_removal/core.entity_form_display.flagging.report_post.default.yml
- modules/social_features/social_content_report/config/features_removal/core.entity_view_display.flagging.report_comment.default.yml
- modules/social_features/social_content_report/config/features_removal/core.entity_view_display.flagging.report_node.default.yml
- modules/social_features/social_content_report/config/features_removal/core.entity_view_display.flagging.report_post.default.yml
- modules/social_features/social_content_report/config/features_removal/field.field.flagging.report_comment.field_other_reason.yml
- modules/social_features/social_content_report/config/features_removal/field.field.flagging.report_comment.field_reason.yml
- modules/social_features/social_content_report/config/features_removal/field.field.flagging.report_comment.field_status.yml
- modules/social_features/social_content_report/config/features_removal/field.field.flagging.report_node.field_other_reason.yml
- modules/social_features/social_content_report/config/features_removal/field.field.flagging.report_node.field_reason.yml
- modules/social_features/social_content_report/config/features_removal/field.field.flagging.report_node.field_status.yml
- modules/social_features/social_content_report/config/features_removal/field.field.flagging.report_post.field_other_reason.yml
- modules/social_features/social_content_report/config/features_removal/field.field.flagging.report_post.field_reason.yml
- modules/social_features/social_content_report/config/features_removal/field.field.flagging.report_post.field_status.yml
- modules/social_features/social_content_report/config/features_removal/field.storage.flagging.field_other_reason.yml
- modules/social_features/social_content_report/config/features_removal/field.storage.flagging.field_reason.yml
- modules/social_features/social_content_report/config/features_removal/field.storage.flagging.field_status.yml
- modules/social_features/social_content_report/config/features_removal/flag.flag.report_comment.yml
- modules/social_features/social_content_report/config/features_removal/flag.flag.report_node.yml
- modules/social_features/social_content_report/config/features_removal/flag.flag.report_post.yml
- modules/social_features/social_content_report/config/features_removal/message.template.content_reported.yml
- modules/social_features/social_content_report/config/features_removal/taxonomy.vocabulary.report_reasons.yml
- modules/social_features/social_content_report/config/features_removal/views.view.report_overview.yml
- modules/social_features/social_content_report/social_content_report.features.yml
- modules/social_features/social_content_report/social_content_report.install
Removes the features file and adds default configuration as settings
file in the config/install folder.
See problem definition in #3092272: [Meta] Moving away from features. The fact that this configuration is in a feature means that login help text gets overwritten.
Remove the social_content_report.features.yml file
Move the default editable config from hook_install() into a config/install/*.yml file.
Remove any _module_set_defaults function
https://www.drupal.org/project/social/issues/3096748
https://getopensocial.atlassian.net/browse/TB-3460
The social_content_report module is no longer managed by features.
> Replace features with config management for Social Content Report

- modules/social_features/social_book/config/features_removal/core.base_field_override.node.book.promote.yml
- modules/social_features/social_book/config/features_removal/core.entity_form_display.node.book.default.yml
- modules/social_features/social_book/config/features_removal/core.entity_view_display.node.book.activity.yml
- modules/social_features/social_book/config/features_removal/core.entity_view_display.node.book.activity_comment.yml
- modules/social_features/social_book/config/features_removal/core.entity_view_display.node.book.default.yml
- modules/social_features/social_book/config/features_removal/core.entity_view_display.node.book.search_index.yml
- modules/social_features/social_book/config/features_removal/core.entity_view_display.node.book.teaser.yml
- modules/social_features/social_book/config/features_removal/field.field.node.book.body.yml
- modules/social_features/social_book/config/features_removal/field.field.node.book.field_book_comments.yml
- modules/social_features/social_book/config/features_removal/field.field.node.book.field_book_image.yml
- modules/social_features/social_book/config/features_removal/field.storage.node.field_book_comments.yml
- modules/social_features/social_book/config/features_removal/field.storage.node.field_book_image.yml
- modules/social_features/social_book/config/features_removal/node.type.book.yml
- modules/social_features/social_book/social_book.features.yml
Removes the features file and adds default configuration as settings
file in the config/install folder.
See problem definition in #3092272: [Meta] Moving away from features. The fact that this configuration is in a feature means that login help text gets overwritten.
Remove the social_book.features.yml file
Move the default editable config from hook_install() into a config/install/*.yml file.
Remove any _module_set_defaults function
https://www.drupal.org/project/social/issues/3096747
https://getopensocial.atlassian.net/browse/TB-3459
The social_book module is no longer managed by features.
> Replace features with config management for Social Book

- modules/social_features/social_comment/config/features_removal/comment.type.comment.yml
- modules/social_features/social_comment/config/features_removal/core.entity_form_display.comment.comment.default.yml
- modules/social_features/social_comment/config/features_removal/core.entity_view_display.comment.comment.activity.yml
- modules/social_features/social_comment/config/features_removal/core.entity_view_display.comment.comment.activity_comment.yml
- modules/social_features/social_comment/config/features_removal/core.entity_view_display.comment.comment.default.yml
- modules/social_features/social_comment/config/features_removal/core.entity_view_mode.comment.activity.yml
- modules/social_features/social_comment/config/features_removal/core.entity_view_mode.comment.activity_comment.yml
- modules/social_features/social_comment/config/features_removal/core.entity_view_mode.comment.full.yml
- modules/social_features/social_comment/config/features_removal/field.field.comment.comment.field_comment_body.yml
- modules/social_features/social_comment/config/features_removal/field.storage.comment.comment_body.yml
- modules/social_features/social_comment/config/features_removal/field.storage.comment.field_comment_body.yml
- modules/social_features/social_comment/config/features_removal/system.action.comment_publish_action.yml
- modules/social_features/social_comment/config/features_removal/system.action.comment_save_action.yml
- modules/social_features/social_comment/config/features_removal/system.action.comment_unpublish_action.yml
- modules/social_features/social_comment/social_comment.features.yml
Removes the features file and adds default configuration as settings
file in the config/install folder.
See problem definition in #3092272: [Meta] Moving away from features. The fact that this configuration is in a feature means that login help text gets overwritten.
Remove the social_comment.features.yml file
Move the default editable config from hook_install() into a config/install/*.yml file.
Remove any _module_set_defaults function
https://www.drupal.org/project/social/issues/3096746
https://getopensocial.atlassian.net/browse/TB-3458
The social_comment module is no longer managed by features.
> Replace features with config management for Social Comment

- modules/custom/social_font/social_font.module
- themes/socialblue/assets/css/base.css
- themes/socialblue/components/01-base/text/_text.scss
When the custom font doesn't have a font-weight 500, bold (strong HTML element) text looks like a simple text.
Remove font-weight 500 for the strong HTML tag
https://www.drupal.org/project/social/issues/3103209
> Issue #3103209 by agami4: Remove styles for the strong HTML tag

- modules/social_features/social_user/social_user.module
Once a CM, SM or admin goes to `/admin/people` , the filter for Group is ordered by the group ID. This makes it hard for a community with a lot of groups to find the users in the groups you are looking for.
Order the groups alphabetically.
https://www.drupal.org/project/social/issues/3108050
Groups on the site manager people overview are now ordered alphabetically. This makes it easier to find the right group to filter on.
> Issue #3108050 by sjoerdvandervis: Order groups alphabetically on people overview

- themes/socialbase/templates/system/links--language-block.html.twig
The language switch block is a dropdown when placed in the menu, but it is not really clear that it actually is a dropdown.
Add a dropdown caret to the block heading, so that it's clear that this is a dropdown menu.
https://www.drupal.org/project/social/issues/3108292
> Issue #3108292 by sjoerdvandervis: Add caret to language switcher

- modules/social_features/social_search/social_search.module
- modules/social_features/social_tagging/config/features_removal/taxonomy.vocabulary.social_tagging.yml
- modules/social_features/social_tagging/config/install/social_tagging.settings.yml
- modules/social_features/social_tagging/config/schema/social_tagging.schema.yml
- modules/social_features/social_tagging/social_tagging.features.yml
- modules/social_features/social_tagging/social_tagging.install
See problem definition in [#3092272]. The fact that this configuration is in a feature means that site managers can't change the name of the taxonomies.
<ul>
<li>Remove the <code>social_tagging.features.yml</code> file</li>
<li>Move the default editable config from <code>social_tagging_install()</code> into a <code>config/install/*.yml</code> file.
<li>Remove the _social_tagging_set_defaults function</li>
</ul>
https://www.drupal.org/project/social/issues/3092275
-  [ ] Enable the Social Tagging module
-  [ ] Change the name of the content tags vocabulary
-  [ ] Revert features
The social_tagging module is no longer managed by features. This fixes an issue where the Content Types vocabulary could not be changed.
> Issue #3092275 by Kingdutch: Remove features from Social Tagging module

- themes/socialbase/socialbase.theme
With the Social Ajax comments and the Social Comment Update modules enabled, adding a comment with an image to a thread without previous comments that contained an image, the icon placeholders from the gallery (modal) are visible. 
The socialbase/photoswipe.image library is loaded in template files, instead of on page load, this isn't added correctly when adding your first comment through Ajax, it is usually because without ajax the entire page is loaded. 
https://www.drupal.org/project/social/issues/3108614
Make sure social_ajax_comments is enabled.
Make sure social_comment_upload is enabled
We have ensured the image gallery icons aren't shown after adding a comment with Ajax.
> Issue #3108614 by ronaldtebrake: Ensure correct photoswipe library is added

- modules/custom/social_ajax_comments/social_ajax_comments.module
When you want to edit a comment through Ajax, it results in UX issues. It tries to load the Author, comment section, creation date etc. So the entire edit form. This needs to be a follow up where we load this in a modal popup. 
We ensure that the Edit link still points to the old edit form page, instead of making it an Ajax link.
https://www.drupal.org/project/social/issues/3108601
None needed, since this is a regression of Ajax comments and the scope of that story already was limited to only adding and deleting of comments through Ajax.
> Issue #3108601 by ronaldtebrake, royharink: Ensure editting for comments through AJAX is not enabled

- modules/social_features/social_user/social_user.module
Whenever a SM creates a new user, at the bottom of the form there's a message asking if the user already has an account with a link to the login page. This is weird since the user is already logged in. This message is for anonymous users only
Make sure the message is only shown to anonymous users
- https://www.drupal.org/project/social/issues/3105096
If this Pull Request makes visual changes then please include some screenshots that show what has changed here. 
As a SM I no longer see a message and a link to the login form whenever I was adding a new user.
> 3105096 - make sure to only show the login message for an anonymous user

- themes/socialbase/templates/comment/form--comment.html.twig
The mention doesn't work consistently when Ajax Comments is enabled, although this wasn't the actual issue.
Due to the creation of Ajax Comments we noticed we rendered attributes for the _form--comments_ twice. 
I reverted that part and only added my own class to the list.
https://www.drupal.org/project/social/issues/3109067 
It was noticed in there, but mentions not working was a side effect.
> #3109067 - @mention doest not work correctly due to attributes being rendered.. twice.

- modules/social_features/social_post/js/keycode-submit.js
Since the introduction of Ajax comments, the quickpost functionality was not working anymore (Cmd / Ctrl + Enter).
The `click()` function is not possible to be used as it seems, as it triggers an ajax call. When using a `mousedown()` function, it does trigger the quickpost action.
https://www.drupal.org/project/social/issues/3108558
> Issue #310855 by sjoerdvandervis: Quickpost with ctrl/cmd + enter

- modules/custom/group_core_comments/src/Plugin/Field/FieldFormatter/CommentGroupContentFormatter.php
When a user can't directly join a group (e.g. Closed groups, or flexible groups without the "join directly" setting enabled) it doesn't make sense to redirect them to the canonical url of the group, which in our case is the stream.
For that case, we can just do what the teaser does, so for consistency we will redirect to the about page which is reachable for Closed groups and flexible groups for outsiders :) 
https://www.drupal.org/project/social/issues/3109192
> #3109192 - Better redirecting on View group in group core comments link

- modules/social_features/social_private_message/social_private_message.module
After enabling social_group_welcome_message. 
1. Create an open group and also enable the welcome message.
2. Leave the group
3. Re-join the group
4. Visit your inbox.
Add a check on profile picture and display_name variables to avoid the errors and unlawful assignment of values.
https://www.drupal.org/project/social/issues/3108504
N.A
N.A
N.A
N.A
> Issues #3108504: Added empty check on profile picture and display name to prevent ambiguous variables assignment.

- themes/socialblue/assets/css/hero--sky.css
- themes/socialblue/components/04-organisms/hero/hero--sky.scss
The Event title doesn't scale well on mobile
Rewrite styles for the title on the hero banner. (max-height: none)
https://www.drupal.org/project/social/issues/3109183
> Issue #3109183 by agami4:  Fix title of the event page on mobile

- themes/socialblue/assets/css/cards--sky.css
- themes/socialblue/components/00-config/mixins/_card--sky.scss
- themes/socialblue/components/02-atoms/cards/cards--sky.scss
The grey line that separates different sections of the left sidebar on profiles and groups should be clearer. At the moment it is a bit hard to scan.
Change the line color into #adadad.
https://www.drupal.org/project/social/issues/3109206
> Issue #3109206 by agami4: Change color separate line between sections on the sidebar on the profile and groups pages

- themes/socialblue/assets/css/cards--sky.css
- themes/socialblue/components/02-atoms/cards/cards--sky.scss
Go to your Groups tab on your profile and see as below, the add group button is not aligned correctly on mobile
Update align 'Add' button on the desktop and mobile modes
https://www.drupal.org/project/social/issues/3109237
> Issue #3109237 by agami4: Fix aligned "Add" button on the sidebar on the profile and group page

- modules/social_features/social_event/modules/social_event_managers/css/vbo_form.css.map
- modules/social_features/social_event/modules/social_event_managers/css/vbo_form.scss
UI issue with text overlapping on the Event page, Manage enrollments tab
Fix position form-item-select-all block on the manage enrollments tab of the event page
https://getopensocial.atlassian.net/browse/YANG-2102
> YANG-2102: Fix position form-item-select-all block on the manage enrollments tab of the event page

- themes/socialblue/assets/css/offcanvas--sky.css
- themes/socialblue/components/04-organisms/offcanvas/offcanvas--sky.scss
The <Filter> button is overlapping a phase number on a mobile screen
Change position for the 'Filter' button on the group pages on the mobile/tablet modes
https://getopensocial.atlassian.net/browse/YANG-2120
> YANG-2120: Fix position "Filter" button on the group page on the mobile/tablet modes

- themes/socialbase/assets/css/navbar.css
- themes/socialbase/components/03-molecules/navigation/navbar/navbar.scss
- themes/socialblue/assets/css/layout--sky.css
- themes/socialblue/components/05-templates/layout/layout--sky.scss
Search does not show the tab options to search for Content, Groups or Users on mobile.
Add width 100% to the secondary navigation region
https://www.drupal.org/project/social/issues/3109198
> Issue #3109198 by agami4: Fix display tab options on the search page on mobile mode

- modules/social_features/social_book/config/install/core.entity_view_display.node.book.hero.yml
- modules/social_features/social_page/config/install/core.entity_view_display.node.page.hero.yml
Book and basic pages do not show the banner hero image
Add hero view modes with image for those content types
https://www.drupal.org/project/social/issues/3109065
> Issue #3109065 by ribel: Fix hero image display for book and basic pages

- themes/socialblue/assets/css/cards--sky.css
- themes/socialblue/components/02-atoms/cards/cards--sky.scss
There is an issue with the <Edit profile> button, it has a wrong high and a label almost invisible.
Fix height of the <Edit profile> button
https://getopensocial.atlassian.net/browse/YANG-2121
> YANG-2121: Fix height of edit button on the profile page on the ipad

- modules/social_features/social_group/modules/social_group_welcome_message/social_group_welcome_message.module
When you create a group and set a welcome message you will receive the welcome message as well.
Check if the welcome message is about to be send to the group owner. If so, don't bother sending it as the group owner probably knows that they created the group.
https://www.drupal.org/project/social/issues/3109219
N/a, is fixing a bug in #1673.
> Issue #3109219 by bramtenhove: Prevent a welcome message being sent to the owner of the group

- themes/socialbase/assets/css/form-controls.css
- themes/socialbase/components/02-atoms/form-controls/_select.scss
The custom styles of the select widget do not work on the IE11 browser
Add reset styles of the select widget on the IE11 browser
https://getopensocial.atlassian.net/browse/YANG-2111
before: ![Screenshot at Feb 03 12-53-00](https://user-images.githubusercontent.com/16086340/73647535-60177980-4684-11ea-8445-d9c5d4148480.png)
after: <img width="415" alt="Screenshot at Feb 03 12-53-50" src="https://user-images.githubusercontent.com/16086340/73647559-6d346880-4684-11ea-8d6d-ed43b71a17ad.png">
> YANG-2111: Add reset styles for the select widget on the IE11 browser

- themes/socialblue/assets/css/cards--sky.css
- themes/socialblue/components/02-atoms/cards/cards--sky.scss
The 'Edit Profile' button has the wrong styles on the IE11 browser
Update styles for the  'Edit Profile' button on the IE11 browser
https://getopensocial.atlassian.net/browse/YANG-2107
- before: ![Image_00115291580131109](https://user-images.githubusercontent.com/16086340/73838039-70ae2800-481b-11ea-84fc-2321917356a8.png)
- after: ![Image_00115481580131188](https://user-images.githubusercontent.com/16086340/73838060-7dcb1700-481b-11ea-9ebe-88a97eef74de.png)
> YANG-2107: Update "Edit profile" button on the IE11

- .travis.yml
Merge after: https://github.com/goalgorilla/open_social_scripts/pull/30/files
We want to run tests using all the optional modules by default, to ensure we encounter issues in our stability tests with everything enabled, but also ensure we test at least stability-1 using no optional modules. To test scenario's that might have misplaced config etc.
1. Updated the scripts in https://github.com/goalgorilla/open_social_scripts/pull/30/files
That will give us the flag --with-optional
2. This is now used for all the stability tests
3. Added a new test suite, this one will run the normal install_script without the flag to ensure we run the same tests as install_update
https://www.drupal.org/project/social/issues/3111353
We now also test all optional modules that have a …
> Issue #3111353 - Ensure we run test against all optional modules

- modules/social_features/social_core/social_core.module
The contextual edit icon was appearing to the users even if it didn't have access to edit the node.
Added a cache context depending upon permission/access of the user to the node.
https://www.drupal.org/project/social/issues/3109076
N.A
N.A
N.A
> Issues #3109076: Added cache context to node edit url link.

- tests/behat/features/capabilities/gdpr/inform-block.feature
On our 8.x and 9.x branches the behat test for /gdpr/inform-block.feature fails, due to the fact we have enabled optional modules the order of blocks has changed.
Ensure we directly place the block from the machine name link which doesnt change, the order can change due to more or less blocks being available.
https://www.drupal.org/project/social/issues/3112434
We have ensured our travis test are running for 8 and 9.
> Issue #3112434 Behat test for GDPR inform block fails

- modules/social_features/social_comment/social_comment.install
- modules/social_features/social_core/social_core.install
- modules/social_features/social_node/social_node.install
- modules/social_features/social_post/social_post.install
Update hook to set the correct view mode for post, comments and nodes in the stream.
https://www.drupal.org/project/social/issues/3111961
n/a
> #3111961: Make sure the post, comment and node entities have the correct view mode in the stream after the update to 8.x

- modules/social_features/social_event/modules/social_event_enrolments_export/src/Plugin/Action/ExportEnrolments.php
- modules/social_features/social_group/modules/social_group_members_export/src/Plugin/Action/ExportMember.php
- modules/social_features/social_user_export/social_user_export.module
- modules/social_features/social_user_export/src/Plugin/Action/ExportUser.php
LU with Group Manager role can't download CSV export of group members when performing the export users bulk action via the manage members tab of a group.
**How to reproduce**
_Make sure the social_user_export module is enabled._
- As a regular logged in user (non admin, or site manager etc.) who is a manager of a group.
- Go to a group I manage.
- Go to manage members.
- Select users you want to export, click Action > Export members.
- When completed, see the notification the export has been completed and click on the download link.
- See that the user lands on an access denied page.
The logged in user with the role manage members should be able to download the exported CSV file.
https://www.drupal.org/project/social/issues/3111591
_Make sure the social_user_export module is enabled._
> Issue #3111591 - Fixed an issue with LU users with group manager roles not being able to download an exported CSV from group members

- modules/social_features/social_event/config/features_removal/social_event.settings.yml
- modules/social_features/social_event/config/install/social_event.settings.yml
- modules/social_features/social_event/social_event.install
The default for the <code>enroll</code> item in <code>social_event.settings</code> is an empty value. However this value is used in <code>EnrollActionForm</code> as an array directly. This causes warnings.
This has been made more apparent by the feature revert in Open Social 8.0.
Make sure the default value is an empty array instead of an empty value. Include an update hook for existing sites.
https://www.drupal.org/project/social/issues/3114280
Fixed the default value for the <code>social_event.settings</code> <code>event</code> key that was incorrect and could lead to errors.
> Issue #3114278: Default social_event.settings.enroll is not an array

- .travis.yml
We recommend 7.x and higher, lets test update paths from there also to ensure all security things are taken in to account.
:) Updated branch to 7.x
Not needed.
> Support 7.x now in travis for ensuring security checks work

- modules/social_features/social_event/social_event.tokens.inc
Event enrolment notification all says "Anonymous has enrolled..."
See: 
The `social_event:enrolled_user` token had a negate on checking the instance of a variable. In this case that meant the user was cast as a AN at the start. 
Even if a EventEnrollment was found, it skipped the part where it was getting the displayname.
https://www.drupal.org/node/3105138
https://getopensocial.atlassian.net/browse/DS-7103
Event enrolment notifications all said "Anonymous has enrolled..." even if there was an existing user who enrolled. We made sure the users display name is shown again.
> Issue #3105138: Event enrolment notification all says "Anonymous has enrolled..."

- modules/social_features/social_private_message/social_private_message.install
Follow up for https://github.com/goalgorilla/open_social/pull/1727. We need to revert all the configurations in the features_removal folder. One of the issues which came up is that /user/inbox theme is broken after the upgrade to OS 8.x
Revert remaining features.
https://www.drupal.org/project/social/issues/3113150
N.A
N.A
N.A
N.A
> Issue #3113150 by navneet0693: Reverted remaining configuration by hook_update_N which was left in 8801.

- modules/social_features/social_post/src/Entity/Post.php
The `setType` method doesn't work correctly for the Post entity. Try to set a new Post type to some entity and you will get the previous type
In the method setType set type from parameter instead of current bundle
https://www.drupal.org/project/social/issues/3110778
Try to set a new Post type to some entity and you should get the new type
> Issue #3110778 by rolki: Fixed an issue that not set the type for the Post entity

- modules/social_features/social_book/social_book.install
After features removal the configuration for books didn't go that well. 
Run another update hook, after features removal has taken place to re-import config one last time.
http://drupal.org/node/3117047
None needed.
> Issue #3117047 run update hook to ensure config of books is re-imported

- tests/behat/features/bootstrap/FeatureContext.php
- tests/behat/features/bootstrap/SocialDrupalContext.php
Mink 1.8.0 no longer automatically starts a session when `getSession` is
called. This breaks some `beforeScenario` steps that rely on the
sessions (for example, testing JS support or resizing the window).
This commit simply checks whether the session is started before calling
any methods on the session, starting it if needed. This is only done in
`beforeScenario` calls that actually use the session.
For `FeatureContext` the beforeScenario calls are merged because I'm
unsure whether we can rely on call order.
Change in Mink: https://github.com/minkphp/Mink/pull/705
*Should be backported to all supported branches*
No issue, issue in testing.
N/A
N/A
> Fix compatibility with Mink 1.8.0

- modules/custom/social_auth_extra/social_auth_extra.module
- modules/custom/social_tour/config/install/tour.tour.social_user.yml
- modules/social_features/social_private_message/social_private_message.install
- modules/social_features/social_profile/social_profile.module
- modules/social_features/social_user/social_user.module
- themes/socialbase/src/Plugin/Preprocess/PageTitle.php
- themes/socialblue/src/Plugin/Preprocess/Page.php
See: https://www.drupal.org/node/3090422
The entity.profile.type.user_profile_form and entity.profile.type.user_profile_form.add routes have been replaced by profile.user_page.single, profile.user_page.multiple and profile.user_page.add_form.
Urls generated for the previous routes will need to be updated; the functionality is similar but the old route names will no longer resolve.
Change all the in code related routes and match them with the new ones.
https://www.drupal.org/node/3118746
The update of Profile has caused some issues with changed routes in the contrib module not being reflected in Open Social.
> Issue #3118746 - Profile update changed routes

- themes/socialbase/assets/css/form-controls.css
- themes/socialbase/components/02-atoms/form-controls/_input.scss
When we use a browser-native datepicker for an input of type `date`, we do not want to show a background image. This because it overlaps with the arrow that's placed inside the field by the browser itself (See screenshot).
Remove the background from the input with type `date`. At the moment, this is only the case when we want to use our native datepicker referenced in https://github.com/goalgorilla/open_social/pull/1741
Before:
After without hover:
After with hover:
We improved the way we display a native datepicker on specified fields. The dropdown indicator should only show the native dropdown icon from the browser, not our own background icon.
> TB-2922 - Remove the background for input type date fields

- modules/social_features/social_follow_content/config/update/social_follow_content_update_8001.yml
- modules/social_features/social_follow_content/social_follow_content.install
- modules/social_features/social_follow_content/social_follow_content.module
The follow content button is added after modules have been installed. 
It's also the result of an optional module so it's possible that the 
button doesn't exist. These factors don't allow the view display 
configuration for the field to be set in configuration that is shipped 
with our modules. 
To work around this an modules_installed hook is implemented that makes 
the change for us. An update hook is provided to fix platforms that 
installed a version that had the new templates to render before this fix 
was present.
https://www.drupal.org/project/social/issues/3120644
A new style for topic teasers caused the "follow content" button to show up in the teaser erroneously. This has been resolved.
> Add update and install hook to remove follow content button from topic small teassers

- composer.json
- drupal-org-core.make
Updates - https://www.drupal.org/project/drupal/releases/8.8.4
We have updated Drupal Core to 8.8.4 to ensure we stay up to date with latest CKEditor security patch.
> Issue SA-CORE-2020-001 - Core 8.8.4

- themes/socialbase/assets/css/base.css
- themes/socialbase/components/01-base/tables/_tables.scss
The table has the wrong styles on the mobile
Add reset `margin-top` for the table on mobile if this table has `card__block--table` class
https://getopensocial.atlassian.net/browse/ECI-1008
https://www.drupal.org/project/social/issues/3116652
before:
after:
Fixed wrong styles for the table if the table has `card__block--table` class
> YANG-1008: Update styles for the table on the mobile

- modules/social_features/social_content_block/config/install/field.storage.block_content.field_sorting.yml
- modules/social_features/social_content_block/social_content_block.install
- modules/social_features/social_content_block/src/ContentBuilder.php
As a CM I want to sort content for the custom content block according to my specific use case
- Add sorting by most commented
- Add sorting by most liked
- https://www.drupal.org/project/social/issues/3118044
- https://getopensocial.atlassian.net/browse/YANG-2000
- When you open Add Custom content list block custom block page (/block/add/custom_content_list) then you should see that these page doesn't use an administrative theme
- You should see two extra sorting options (most commented and most liked)
- Use a new specific sorting
- Paste this block to the Complementary top region
> Issue #3118044 by rolki: As a CM I want to sort content for the custom content block according to my specific use case

- themes/socialblue/assets/css/cards--sky.css
- themes/socialblue/components/02-atoms/cards/cards--sky.scss
The 'Create idea' button has the wrong styles on the Sky theme
Should update styles for the 'Create idea' button on the Sky theme
https://www.drupal.org/project/social/issues/3117064
Before:
After:
The 'Create idea' button has correct styles on the Sky theme
> Issue #3117064 by agami4: Add styles for the "Create idea" button

- themes/socialbase/assets/css/alert.css
- themes/socialbase/components/02-atoms/alert/alert.scss
The layout two columns(layout-builder module) has the wrong styles if you have a message block
Update position for the close button on the message block
https://getopensocial.atlassian.net/browse/ECI-1020
https://www.drupal.org/project/social/issues/3123458
Before:
After:
> Issue #3123458 by Agami4: Fix position for the close button on the message block when using layout builder

- modules/social_features/social_core/config/optional/block.block.socialbase_local_tasks.yml
- modules/social_features/social_core/config/optional/block.block.socialblue_local_tasks.yml
- modules/social_features/social_core/config/update/social_core_update_8808.yml
- modules/social_features/social_core/social_core.install
On /user/x/profile the tabs are shown (in SKY style).
Update block configs ad hide tabs on this page.
- https://www.drupal.org/project/social/issues/3123549
> Issue #3123549 by ribel: Hide tabs from /user/x/profile page

- modules/custom/group_core_comments/src/GroupCommentAccessControlHandler.php
During comment migration by Migrate API faced an error:
`TypeError: Argument 1 Passed to Drupal\group\Entity\GroupContent::loadByEntity0 must implement interface ContentEntityInterface`
Add an extra condition for commented entity
https://www.drupal.org/project/social/issues/3124378
Try to run any migration for comments
Add an extra check for the commented entity in `group_core_comments/src/GroupCommentAccessControlHandler.php` to prevent errors with migrate API.
> Issue #3124378 by rolki: Add an extra condition for commented entity

- modules/social_features/social_core/config/optional/block.block.socialblue_local_actions.yml
- modules/social_features/social_core/config/update/social_core_update_8809.yml
- modules/social_features/social_core/social_core.install
- themes/socialblue/templates/layout/page--sky.html.twig
The socialblue_local_actions is rendered lazily, this can cause the simple `if` check to be false. This is not a problem in the normal layout because the content is limited to 67% width and this region just fills the remaining 1/3rd of the page.
However, in Sky, this is problematic because the region is moved to the left which causes the other content to be shifted to the right even if there appears to be no actual content.
Hide socialblue_local_actions on those pages where we don't have any blocks in the sidebar.
- https://www.drupal.org/project/social/issues/3125249
Fix complementary region moving page content to the side
> Issue #3125249 by ribel: Fix complementary region moving page content to the side

- themes/socialbase/assets/css/admin-toolbar.css
- themes/socialbase/components/00-config/_variables.scss
- themes/socialbase/components/04-organisms/admin-toolbar/admin-toolbar.scss
- themes/socialbase/templates/block/block--system-branding-block.html.twig
- themes/socialbase/templates/block/block--system-menu-block--main.html.twig
When the admin toolbar is visible the z-index of the main menu is changed. This is done to ensure the admin toolbar is shown on top of the main menu. However, this also causes the main menu to appear under certain page elements.
This happens in all browsers
Don't try to change the z-index of the main menu when the admin bar is present, but instead properly update the admin toolbar's z-index.
https://www.drupal.org/project/social/issues/3096602
https://getopensocial.atlassian.net/browse/YANG-1776
Also affected https://www.drupal.org/node/3106782 where a slightly different fix was previously applied.
The main menu no longer appear under page content on mobile devices when a user has access to the administrative menus.
> Issue #3096602 by agami4: Update position of css style for menu on the mobile

- modules/social_features/social_event/modules/social_event_an_enroll/src/Controller/EventAnEnrollController.php
- modules/social_features/social_event/modules/social_event_an_enroll/templates/event-an-enroll-dialog.html.twig
CTA for account creation on Event AN Guest sign-up shows when account creation for anonymous users is disabled.
Hide the CTA when account creation is disabled.
https://www.drupal.org/project/social/issues/3114852
When a platform admin disabled accounts registration and people try to enrol in an event anonymously, the 'create an account' button is no longer displayed.
> 3114852: CTA for account creation on Event AN Guest sign-up should not always show

- tests/behat/features/capabilities/group/group-access-roles.feature
The test fails on step:
`And I click "My groups"`
_Element is not currently visible and so may not be interacted with_
Rewrite step by using `And I am on "/my-groups"`
- https://www.drupal.org/project/social/issues/3126265
Fix behat test for group access roles when Contextual Links are enabled
> Issue #3126265 by ribel: Fix behat test for group access roles when Contextual Links are enabled

- themes/socialblue/assets/css/cards--sky.css
- themes/socialblue/components/02-atoms/cards/cards--sky.scss
The cards have a large vertical distance between them.
Revert changes for the vertical distance between cards
https://www.drupal.org/project/social/issues/3125325
https://getopensocial.atlassian.net/browse/YANG-2688
before
after:
> Issue #3125325 by Agami4: Fix vertical distance between cards in Sky style

- themes/socialblue/templates/group/group--default--sky.html.twig
- themes/socialblue/templates/profile/profile--profile--default--sky.html.twig
The introduction part full width of the content card, but keep the rest of the fields in the 2 columns layout.
https://www.drupal.org/project/social/issues/3125226
https://getopensocial.atlassian.net/browse/YANG-2648
> Issue #3125226 by agami4: Update info tab layout on the profile and group page

- themes/socialbase/assets/css/offcanvas.css
- themes/socialbase/components/04-organisms/offcanvas/offcanvas.scss
When there are a lot of filters available on mobile, the canvas can't be scrolled to the filter button. Because of this, filters are not applicable (see screenshot).
Add some bottom padding to the filter section on mobile, to make sure the filter button is usable.
https://www.drupal.org/project/social/issues/3127758
> Issue #3127758 by sjoerdvandervis: Make search filters applicable on mobile

- composer.json
- drupal-org-core.make
- modules/social_features/social_search/social_search.module
The problem #1729 tried solve is that when you have a site with more than 1 language, and URL detection available as Language detection and selection option, the redirect doesn't take the current active language in to account and it switches back to back to the main/default language when filtering in Search.
This was due to the fact the path was hardcoded as the current_path which didnt take in to account this language code. 
But this resulted in a 'Page not found' for those multilingual sites that did not have Language detection and selection set to detect form URL because it enforces the form submit to go to the current page with a langcode, but it doesn't mean anything for sites without URL detection on langauges. 
It could also result in issues with installations in a subfolder.
When …
> Issue #3128174 - Ensure filter works for multilingual sites regardless of language detection

- modules/social_features/social_profile/config/install/field.field.profile.profile.field_profile_image.yml
- modules/social_features/social_profile/config/update/social_profile_update_8008.yml
- modules/social_features/social_profile/social_profile.install
Currently, when a user doesn't have a profile picture and if you hover over the user's picture, you will see "Default profile image" text. 
This is because browsers are picking up the 'title' property of a user's profile which set <code><img></code> tag in https://github.com/goalgorilla/open_social/blob/8.x-9.x/themes/socialbase/templates/profile/profile--compact.html.twig#L26
Remove title's value in https://github.com/goalgorilla/open_social/blob/8.x-9.x/modules/social_features/social_profile/config/install/field.field.profile.profile.field_profile_image.yml#L34
https://www.drupal.org/project/social/issues/3125680
**Before**: 
**After**:
Profile Image field will not have a default title by the installation.
The default image title property in the profile image field …
> Issue #3125680 by navneet0693: Removed title property of field_profile_image.

- modules/social_features/social_mentions/js/jquery.mentions.ckeditor.js
When a user goes to edit mode of a comment (with WYSIWYG editor) he is not able just to change status without updating content
Adjust & fix the bug in related extension (jquery.mentions.ckeditor.js)
- https://www.drupal.org/project/social/issues/3128589
- https://getopensocial.atlassian.net/browse/YANG-2735
Comments created with a WYSIWYG editor now can be edited without text lost.
> Issue #3128589 by SV: Comments created with a WYSIWYG editor can not be edited

- modules/social_features/social_group/src/Plugin/views/field/SocialGroupViewsBulkOperationsBulkForm.php
When a group has no members, the Manage Members page errors with the following error message:
```
Error: Call to a member function getArguments() on null in Drupal\social_group\Plugin\views\field\SocialGroupViewsBulkOperationsBulkForm->viewsForm() (line 120 of profiles/contrib/social/modules/social_features/social_group/src/Plugin/views/field/SocialGroupViewsBulkOperationsBulkForm.php).
```
Skip processing the SocialGroupViewsBulkOperationsBulkForm when there are no results in the group_manage_members view.
- https://www.drupal.org/project/social/issues/3089990
- Rebased from: #1577
> Issue #3089990 - When a group has no members, the Manage Members page errors

- modules/social_features/social_group/social_group.module
Using the "Social Flexible Group" and I've created a new content type for which I have activated the group content plugin in the group types.
When I edit a node of my new content type, I get the fatal error:
```
TypeError: Argument 4 passed to Drupal\social_group\SetGroupsForNodeService::setGroupsForNode() must be of the type array, null given, called in /app/html/profiles/contrib/social/modules/social_features/social_group/social_group.module on line 1542 in Drupal\social_group\SetGroupsForNodeService->setGroupsForNode() (line 52 of profiles/contrib/social/modules/social_features/social_group/src/SetGroupsForNodeService.php).
```
I have added a line of code to evaluate whether the value exists before it's used. …
> Issue #3035308 Fix fatal error when editing content with a custom content type

- composer.json
- drupal-org.make
Logs filling up with the following warning so many times that it can create logs up to 400mb per day.
Warning: time() expects exactly 0 parameters, 2 given in /var/www/drupal/web/core/lib/Drupal/Core/Field/BaseFieldDefinition.php on line 469
Apply the patch from the votingagpi module
https://www.drupal.org/project/votingapi/issues/3048085
https://www.drupal.org/project/social/issues/3099608
If this Pull Request makes visual changes then please include some screenshots that show what has changed here. 
We applied a patch for the votingapi module that will prevent the logs being filled up with warnings.
> Issue #3099608 by robertragas: Add patch to fix time() callback filling up logs for the votingapi module

- modules/social_features/social_content_block/src/ContentBuilder.php
The page loads endlessly or breaks the site
Remove OR conditions to includes related nodes for comments and likes
https://www.drupal.org/project/social/issues/3130548 
Create a new custom content block and choose the group type and last interacted sorting then go to the page with this block
> Issue #3130548 by rolki: Remove OR conditions for node comments and likes to fix performance issues with "Last interacted sorting"

- modules/social_features/social_group/social_group.module
After creating a new group type and adding visibility field to this group then I use _social_flexible_group_edit_submit callback to change visibility options for all content related to this group, but I faced with the error:
`TypeError: Argument 1 passed to _social_group_cache_tags() must implement interface Drupal\group\Entity\GroupInterface, null given, called in /var/www/html/profiles/contrib/social/modules/social_features/social_group/social_group.module on line 769 in _social_group_cache_tags() (line 1197 of /var/www/html/profiles/contrib/social/modules/social_features/social_group/social_group.module`
Add an extra condition before invalidating cache tags.
https://www.drupal.org/project/social/issues/3133763
> Issue #3133763 by rolki: Add an extra condition before invalidating cache tags

- modules/social_features/social_group/social_group.module
- modules/social_features/social_group/src/Plugin/Block/GroupAddBlock.php
- modules/social_features/social_group/src/SocialGroupHelperService.php
"Add Group" block on /user/{uid}/groups on the current user project doesn't take the context of permissions which enables the user to add groups in the system. If the user has permission to create only one group, the + icon in the header takes directly to that group but Add block doesn't, it will take you to /group/add.
Use the same logic to create the link as used here: https://github.com/goalgorilla/open_social/blob/8.x-9.x/modules/social_features/social_group/social_group.module#L1745
https://www.drupal.org/project/social/issues/3134100
N.A
The Add Group block on the user profile page will now have a computed URL as per permission to create a group of the current user. It will have either of the two URLs
1. If user have permission to create only 1 group, URL will be …
> Issue #3134100 by navneet0693: Add Group block on user profile's group doesn't takes "create group" permissions in context

- modules/social_features/social_group/social_group.module
1 Thing was overlooked in https://github.com/goalgorilla/open_social/pull/1828 so correcting that in a follow-up.
> Issue #3134100 by robertragas: remove incorrect cache invalidate

- modules/social_features/social_core/social_core.install
- modules/social_features/social_group/modules/social_group_flexible_group/src/SocialGroupFlexibleGroupConfigOverride.php
- modules/social_features/social_group/modules/social_group_secret/src/SocialGroupSecretConfigOverride.php
Group Manager doesn't receive a notification when someone joins the group of type "Flexible groups".
Add configuration override to add the flexible group in this configuration https://github.com/goalgorilla/open_social/blob/8.x-9.x/modules/social_features/social_activity/config/install/message.template.join_to_group.yml#L8 for adding flexible groups as well.
Do the same for secret groups too.
https://www.drupal.org/project/social/issues/3136540
Flexible and Secret Group Manager will receive a notification when someone joins the group.
N.A
N.A
> Issue #3136540 by navneet0693: Added configuration override for sending notification to group manager in flexible & secret groups.

- .github/PULL_REQUEST_TEMPLATE.md
It's not always clear for developers what the intention is of the headings in the pull request template. This causes information that can be useful to reviewers to be missed.
Be more elaborate in the pull request template. Prompting the developer for the information that's expected and providing some examples.
A full How to test is included because it's sometimes difficult to determine the level of details required.
The issue link section is clarified to show that a Drupal.org issue is always needed for release management and links to other issue trackers are additions, not substitutions.
The screenshots section shows what a screenshot could be made of.
The release notes described better what they actually are.
The translations section now explains why it's there to guide developers in …
> Elaborate in pull request template

- themes/socialbase/assets/css/teaser.css
- themes/socialbase/components/03-molecules/teaser/teaser.scss
Titles for discussions and groups get cut on the third line
Decrease min-height of the title
https://getopensocial.atlassian.net/browse/YANG-2937
https://www.drupal.org/project/social/issues/3136973
before:
after:
Decrease min-height of the title
> Issue #3136973 by agami4: Decrease min-height of teaser title

- modules/social_features/social_event/modules/social_event_invite/config/optional/block.block.socialeventinviteblock.yml
- modules/social_features/social_event/modules/social_event_invite/config/update/social_event_invite_update_8001.yml
- modules/social_features/social_event/modules/social_event_invite/social_event_invite.install
- modules/social_features/social_event/modules/social_event_invite/social_event_invite.module
- modules/social_features/social_event/modules/social_event_invite/src/Plugin/Block/SocialEventInviteLocalActionsBlock.php
Blalla event invite this that
Add cache context of current node to block.
https://github.com/goalgorilla/open_social/pull/1782
> TB-4383: Added cache context of current node to social invite action block

- modules/social_features/social_group/social_group.module
The above text does not refer to the user accepting an invite.
By altering the text when someone accepts an invite it is clearer for the user what is about to happen.
https://www.drupal.org/project/social/issues/3119327
N/a
N/a, should be part of the Group Invite feature.
N/a
> #3119327: Make the confirmation join text more meaningful for users accepting an invite to a group

- modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
- modules/social_features/social_group/modules/social_group_flexible_group/src/Access/FlexibleGroupJoinPermissionAccessCheck.php
A user with sufficient access has no access to add people to a group directly; he / she will be refused access because of access checks.
When a user has sufficient rights to a group and wants to add people directly to the group, we will now grant this person access.
*For example*
*A group manager is now able to add people to his/her flexible group directly.*
> TB-4416 - Add directly page access

- modules/social_features/social_event/modules/social_event_invite/src/Controller/CancelEnrollInviteController.php
When cancelling an invite as the event organizer I get the confirmation that the invite is declined. However the status message shows it is "Invalid or expired".
Change the status message to "Declined".
https://www.drupal.org/project/social/issues/3120797
N/a
N/a, part of #1782.
N/a
N.a
> #3120797: Change the 'cancel enrollment by event manager' to Declined instead of Invalidd/Expired

- modules/social_features/social_event/modules/social_event_managers/src/SocialEventManagersAccessHelper.php
The event owner was not able to add user directly to his event.
The access checks were written only for event managers. Not all event managers are also the owner.
Allow event owner access to the "add directly" page.
https://www.drupal.org/project/social/issues/3120797
N/a
N/a, part of #1782 
N/a
N/a
> Issue #3120797 by bramtenhove: Allow event owners to add users directly

- modules/social_features/social_event/modules/social_event_invite/src/Form/EnrollInviteConfirmForm.php
There are 2 typo's in the confirmation dialog screen when inviting users to an event.
Fixed the typo's.
https://www.drupal.org/project/social/issues/3120797
N/a, part of #1782.
N/a
N/a
> Issue #3120797 by bramtenhove: Fix typo in the invite confirmation dialog

- modules/custom/activity_basics/src/Plugin/ActivityAction/CreateActivityAction.php
- modules/custom/activity_basics/src/Plugin/ActivityContext/EventRequestActivityContext.php
- modules/custom/activity_basics/src/Plugin/ActivityContext/OwnerActivityContext.php
- modules/custom/activity_creator/src/ActivityFactory.php
- modules/social_features/social_event/modules/social_event_managers/src/Element/SocialEnrollmentAutocomplete.php
- modules/social_features/social_event/modules/social_event_managers/src/Form/SocialEventManagersAddEnrolleeForm.php
When a user is invited they also receive a notification that they're added to an event.
This is not entirely correct as they, so far, only have been invited.
And when a user is added directly to an event by, for example, an event manager, there was also a notification send to the user being added that his request to join was approved. But he never requested anything, so that notification was confusing and useless.
Made sure that when a user is invited he gets only one, relevant, notification.
And the same for when a user is added directly, they won't receive another notification about their request being approved.
https://www.drupal.org/project/social/issues/3120797
N/a
N/a, part of #1782.
N/a
N/a
> #3120797: Prevent double notifications

- themes/socialblue/assets/css/layout--sky.css
- themes/socialblue/assets/css/offcanvas--sky.css
- themes/socialblue/components/04-organisms/offcanvas/offcanvas--sky.scss
- themes/socialblue/components/05-templates/layout/layout--sky.scss
The filter button has a wrong position on the mobile mode.
Update the position filter button on the mobile mode.
https://www.drupal.org/project/social/issues/3143546
*For example*
before:
after:
The position of the filter button was fixed on mobile mode
> Issue #3143546 by agami4: Fix filter button on mobile in sky style 

- modules/social_features/social_user/src/Plugin/Block/AccountHeaderBlock.php
After login under custom role, I receive an error:
`TypeError: Argument 1 passed to Drupal\social_user\Plugin\Block\AccountHeaderBlock::hasAccessibleChild() must be of the type array, null given, called in /var/www/html/profiles/contrib/social/modules/social_features/social_user/src/Plugin/Block/AccountHeaderBlock.php on line 172 in Drupal\social_user\Plugin\Block\AccountHeaderBlock->hasAccessibleChild() (line 307 of /var/www/html/profiles/contrib/social/modules/social_features/social_user/src/Plugin/Block/AccountHeaderBlock.php)`
Add extra conditions to the `AccountHeaderBlock` plugin
https://www.drupal.org/project/social/issues/3144445
> Issue #3144445 by rolki: Add extra conditions to the AccountHeaderBlock plugin

- modules/social_features/social_event/modules/social_event_invite/social_event_invite.module
- modules/social_features/social_event/modules/social_event_max_enroll/social_event_max_enroll.module
- modules/social_features/social_event/modules/social_event_max_enroll/src/Service/EventMaxEnrollService.php
The Max Enroll feature no longer works due to changes in the Request to Event and Invite to Event features.
Added the new enroll action form to the list of forms the Max Enroll feature is checking. Also fixed an issue with the active enrollment check for the current user.
And fixed two minor coding improvements, preventing a possible notice.
*Paste a link to the drupal.org issue queue item. If any other issue trackers were used, include links to those too.*
**Play around with all the options**, try to invite people, add people, etc.
N/a
N/a, part of #1782.
N/a
N/a
> #3120797: Make sure Max Enroll plays nicely with the Request to Event feature

- modules/social_features/social_group/social_group.module
- themes/socialblue/templates/group/group--statistic.html.twig
The current representation of numbers related to a group goes in the following order from left to right:
1. Events
2. Topic
3. Members
Typically, members are a bit number while topics and events are smaller.
Re-arrange the order to:
1. Members
2. Events
3. Topics
- https://www.drupal.org/project/social/issues/3144424
- https://getopensocial.atlassian.net/browse/YANG-3080
- https://getopensocial.atlassian.net/browse/YANG-2843
> Issue #3144424 by ribel: Re-arrange the order of the group statistics block

- modules/social_features/social_user/src/Plugin/QueueWorker/UserMailQueueProcessor.php
User accounts can anonymous or cannot email ID sometimes, or contain UID 0, which leads to failure of queues on cron run and then cron is stuck forever.
Add defensive checks to check for either user authentication or no empty emails.
https://www.drupal.org/project/social/issues/3145643
https://getopensocial.atlassian.net/browse/TB-4528
N.A
N.A
User Emails queue processor now have defensive checks to not crash the queue when user doesn't have an email or anonymous.
N.A
N.A
> Issue #3136540 by navneet0693: Added a defensive of user authentication in user mail queue processor.

- modules/social_features/social_user/social_user.module
- translations.php
When a user tries to create an account using an e-mail address and username.
The process returns the wrong error message when the username already exists.
Currently, the message states that there is an error with the e-mail address, while it's actually the username that gives the problem.
A better distinction has been made in the field that didn't pass validation. The message is kept generic by (still) removing the original Drupal message, trying not to disclose information about the existence of the user.
The generic message is left in place to inform about the information disclosure but hasn't been assigned to a field but to the form.
https://www.drupal.org/project/social/issues/3089112
Registration form now have more distinct messages.
Updated strings are now added to translation file.
> Issue #3089112 by royharink: Registration field specific validation error messages

- modules/social_features/social_event/config/install/views.view.upcoming_events.yml
- modules/social_features/social_event/config/update/social_event_update_8810.yml
- modules/social_features/social_event/social_event.install
- modules/social_features/social_event/social_event.module
As a User it would be helpfull to filter events on the events overview based on their enrollment method.
Adds a filter by default to the community or explore events overview.
https://www.drupal.org/node/3145315
https://www.loom.com/share/8d8698956e0d4475a0484830228b2f1a
Adds a new filter for the enrollment method on the explore events overview. So users can quickly identify which events they can easily enroll for.
> Issue #3145315 Add filter to the explore events page for enrollment method

- modules/social_features/social_event/modules/social_event_invite/src/Form/EventInviteEnrollActionForm.php
- modules/social_features/social_event/modules/social_event_max_enroll/social_event_max_enroll.module
- modules/social_features/social_event/social_event.module
- modules/social_features/social_event/src/Form/EnrollActionForm.php
- modules/social_features/social_event/src/Service/SocialEventEnrollService.php
- tests/behat/features/capabilities/group/group-create-open.feature
- tests/behat/features/capabilities/group/group-create-public.feature
We encountered multiple problems with the event invite feature
1. When you are the event owner or organizer you should always be able to enroll via the hero, even when it's invite only
2. When you create an event with "request to join" and have multiple people joined, you can convert it to "invite only" but then all enrollments will be lost that got accepted.
3. When you are invited for an event and accepted, you are not able to un-enroll anymore as the button is gone.
4. When I want to un-enroll to an invite only invite, I need to press the button twice before it actually un-enrolls me.
5. When changing an event from "request to join" to "invite only" the enrollments block on the detail pages is gone.
1. Create exceptions for enrolling when you are the event owner or organizer
2. Add …
> fix multiple issues with event invite

- composer.json
- drupal-org.make
- modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install
- modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
- modules/social_features/social_group/modules/social_group_flexible_group/src/SocialGroupFlexibleGroupConfigOverride.php
Whenever a user selects flexible groups from the Group type filter, we want the user to be able to filter on join methods. Especially now with the request to join it makes a lot of sense. In the future all platforms will migrate to flexible groups only. So we can remove some of the additional alter logic that we need to take in to account now.
Add a filter for the allowed join method for flexible groups. On the group overview and search page.
https://www.drupal.org/node/3143273
https://www.loom.com/share/8242b0f475da47ffb2a589fd32000b6f
We now have the group join method available as filter on the explore group and search group pages whenever you filter on flexible groups.
> Issue #3143273 - Add filter with group join methods for flexible groups

- modules/social_features/social_group/social_group.module
On the all groups page if a user has access to two different types of groups then the user can filter on all group types. Even if he/she does not have access to a certain group type.
We need to ensure we check the current user roles, and see if any of those roles have acces to the 'view group' permission of a certain group type if that its the case we can show the filter option.
The way it's done is the following.
1. If AN can see the groups of a group type - We show the filter
2. If group type has a outsider role and that role can see the groups of a group type  - We show the filter
3. If group type has a member role and that role can see the groups of a group type  - We show the filter (This is necessary so we don't need to invalidate caches or calculate which group a user belongs to …
> Issue #2995501: Group filters show values that a user does not need access to

- modules/social_features/social_mentions/social_mentions.tokens.inc
When we send out notifications, it can be that in cases a mention is made to a person. These tokens reside in social_features/social_mentions/social_mentions.tokens.inc
The problem is that when these are run through the cron it can be that the mentioned user is already deleted. In this case the cron will crash and stop. 
Add defensive checks when converting mention tokens.
https://www.drupal.org/project/social/issues/3150253
We have added defensive checks to the cron when sending out notifications with mentions in it.
> by robertragas: add defensive check for mentions in social tokens

- modules/social_features/social_group/modules/social_group_flexible_group/src/Access/FlexibleGroupContentAccessCheck.php
- tests/behat/features/capabilities/group/group-create-flexible.feature
When creating a flexible group with only public content visibility, the group page does not show certain links such as the stream to the LU any longer. They are also not accessible by logged in users.
Inside the `FlexibleGroupContentAccessCheck.php` class, there is the following if statement :
```
// It's a non member but Community isn't enabled.
// No access for you only for the about page.
if ($account->isAuthenticated() && !social_group_flexible_group_community_enabled($group)
&& $route_match->getRouteName() !== 'view.group_information.page_group_about'
&& $route_match->getRouteName() !== 'entity.group.canonical'
&& $route_match->getRouteName() !== 'view.group_members.page_group_members') {
return AccessResult::forbidden()->addCacheableDependency($group);
}
```
This if statement should …
> Issue 3151179 by frankgraave - Fix flexible group with only public content visibility

- modules/custom/social_node_statistics/social_node_statistics.module
- modules/social_features/social_group/modules/social_group_invite/social_group_invite.module
- modules/social_features/social_group/social_group.module
There's a caching issue with the join CTA buttons for groups when the Sky theme is enabled.
When a user joins the group, the next user will see that he already joined the group because it's already cached.
Fixed the typo in the `cache contexts`. It's now cached correctly and as intended.
_Bonus fix, same typo occurred with the Node Statistics module._
https://www.drupal.org/project/social/issues/3155032
N/a
N/a, kind of part of the Group Request to Join and Invite to join feature.
N/a
N/a
> #3155032: Group join method CTA buttons caching issue

- modules/social_features/social_landing_page/social_landing_page.install
Enable helper modules when flexible group and / or social_book are enabled.
When social_group_flexible_group is enabled, we would like to enable the helper module social_flexible_group_featured, which is responsible for providing a featured view mode which is used when a flexible group is added as featured content on landingpages. The same goes for social_book, for which we enable the submodule social_book_featured.
When placing flexible groups and / or book pages on a landingpage as featured content, there is no view mode for this so we fall back to a blank placeholder, which doesn't have the image that should be used for this type of content.
Enable the two submodules for these modules if they are installed. The submodules provide the configuration for the featured view modes of these …
> Featured view mode for flexible group and social_book

- modules/social_features/social_group/social_group.module
There's a caching issue with the join CTA buttons for groups when the Sky theme is enabled.
When a user joins the group, the next user will see that he already joined the group because it's already cached.
Apply the same fix as #1890 to `8.x-8.x`. This is a custom backport of that of that issue.
https://www.drupal.org/project/social/issues/3155032
N/a
The caching for the group join button, in combination with the Sky theme, was incorrect. The caching contexts are now applied correctly.
N/a
N/a
> #3155032: Fix a caching issue with the group join button

- themes/socialbase/assets/css/comment.css
- themes/socialbase/components/04-organisms/comment/comment.scss
The text is not moved to a new line.
Add to the text `word-break: break-word;` style.
- https://www.drupal.org/project/social/issues/3159764
- https://getopensocial.atlassian.net/browse/YANG-3354
*For example*
Before:
After:
If the word is very long, it will be moved to a new line on the comment block.
> Issue #3159764 by agami4: Add "break-word" style to the text of comment block

- modules/social_features/social_event/modules/social_event_invite/config/update/social_event_invite_update_8004.yml
- modules/social_features/social_event/modules/social_event_invite/social_event_invite.install
- modules/social_features/social_event/modules/social_event_invite/social_event_invite.tokens.inc
- modules/social_features/social_group/modules/social_group_invite/social_group_invite.install
There are some inconsistencies in the emails that get send out for the invite feature. We have invite for groups and for events, but text is different, and also the flow is different, where as groups lands on the group invites overview page, and the event lands on the event detail page.
Make the language context the same, and also let the event follow the flow of the group.
https://www.drupal.org/project/social/issues/3160248
We made the invite flow for events and groups similar for consistency.
> Feature invite emails language and flow

- composer.json
- drupal-org.make
"Load More" button duplicates header on "Manage members" page if using "Infinite Scroll"
Add patch to distro to fix this issue. See:
* https://www.drupal.org/project/views_infinite_scroll/issues/2899705
* https://www.drupal.org/project/views_infinite_scroll/issues/2945524
https://getopensocial.atlassian.net/browse/YANG-3296
*For example*
> Issue #2899705 by rolki: Remove header duplicates after click on "Load more" in table views with Views Infinite Scroll

- modules/social_features/social_group/src/Controller/SocialGroupController.php
- modules/social_features/social_user/social_user.install
- modules/social_features/social_user/social_user.permissions.yml
- modules/social_features/social_user/social_user.routing.yml
- modules/social_features/social_user/src/Controller/SocialUserController.php
- modules/social_features/social_user/src/Routing/RouteSubscriber.php
Disable access to blocked users' pages through the direct link
Add custom permission to allow view blocked users' pages and add it to routes
- https://www.drupal.org/project/social/issues/3158812
- https://getopensocial.atlassian.net/browse/YANG-3225
> Issue #3158812 by tBKoT: Disable access to the blocked users pages

- modules/social_features/social_event/modules/social_event_managers/src/Form/SocialEventManagersAddEnrolleeForm.php
- themes/socialbase/assets/css/email-preview.css
- themes/socialbase/components/04-organisms/email/email-preview.scss
For the group invite feature we have created a email preview what the recipients will see. We also need this for the event invite for consistency.
Add the email preview to the event invite feature.
https://www.drupal.org/project/social/issues/3160262
For the group invite feature you could see the preview of the email you are about to send out to invitees. This has also been added to the invite event feature.
> #3152934 - Follow up for preview add directly functionality

- modules/social_features/social_content_block/src/ContentBuilder.php
When I try to add a specific link with GET parameters to a custom content list block, those parameters are trimmed.
For example: `/search/resources?f%5B0%5D=topic_type%3A36547` becomes just `/search/resources`
Fix overwriting URL options in getLink() method of ContentBuilder.
- https://www.drupal.org/project/social/issues/3157762
- https://getopensocial.atlassian.net/browse/YANG-3358
Allow GET parameters in read more links of the custom content list blocks.
> Issue #3157762 by ribel: Fix GET parameters in read more links of the custom content list blocks

- modules/social_features/social_book/social_book.install
- modules/social_features/social_book/src/SocialBookConfigOverride.php
When enabling social book, when you search for a book you will see the result in the Content tab but not in the All tab although that also shows all other pieces of content.
The search autocomplete through the magnifying glass also doesn't show this in that case.
Ensure we also index and show book as search results for the All index. This will make sure it works for both.
Also ensure we trigger a re-index and save so the new config is added.
https://www.drupal.org/project/social/issues/3159259
https://getopensocial.atlassian.net/browse/OS-303
Book pages can now also be found using the search autocomplete using the magnifying glass, or on the search all tab of the search itself.
> Issue #3159259: Book pages need to be available in the search all and search autocomplete

- modules/custom/social_path_manager/social_path_manager.module
*Hero image is missing on the discussion page with ailas /digitalhealthrights/discussion/digital-health-technologies-respecting-rights-**add**ressing because Hero block display based on path*
*Replace paths with routes to avoid incorrect matches in conditions*
*https://www.drupal.org/project/social/issues/3144794*
*https://getopensocial.atlassian.net/browse/YANG-3422*
- fill all fields
- add alias like: /digitalhealthrights/discussion/digital-health-technologies-respecting-rights-**add**ressing 
*Resolve an issue when "Hero block" is not displays on the node page.*
> Issue 3144794: Hero block display based on path is too fragile

- themes/socialbase/templates/node/field--node--body.html.twig
*Using static classes for the body field of node prevents adding dynamic attributes by other modules (like quickedit) which could cause issues.*
*Use the "attributes" variable.*
- https://www.drupal.org/project/social/issues/3159810
- https://getopensocial.atlassian.net/browse/YANG-3361
> Issue #3159810 by SV: Replace static classes with attributes variable for the body field of node

- themes/socialbase/src/Plugin/Preprocess/Node.php
We can make the comment box title sound more engaging.
Change the text for the comment box title.
https://www.drupal.org/project/social/issues/3160305
**Before**
**After**
The comment box title at nodes now says "Be the first one to comment" instead of a disappointing "Comments (0)".
N/a
N/a
> #3160305: Change the comment box title when there are no comments

- modules/social_features/social_core/social_core.module
User can change Text Format for body field when enabled quickedit module.
In source code we have the following:
> // Only fields listed here will have text format settings disabled.
$full_html_field_ids = [
'edit-body-0',
'edit-field-profile-self-introduction-0',
'edit-field-group-description-0',
];
...
elseif (
$element['#type'] == 'text_format' &&
$account->hasPermission($permission_name) &&
in_array($element['#id'], $full_html_field_ids)
) {
$element['#format'] = 'full_html';
$element['format']['format']['#access'] = FALSE;
but when we have enabled quickedit module element id includes additional unique sub-id, like edit-body-0--CN3RzsrtGkE which causes that user can change "disabled" option.
Cleanup element id and remove part after "--"
- …
> Issue #3161709 by SV: User can change Text Format for body field

- modules/social_features/social_core/src/Plugin/Field/FieldFormatter/LinkClassFormatter.php
- modules/social_features/social_featured_items/config/install/core.entity_view_display.paragraph.featured_item.default.yml
- modules/social_features/social_featured_items/config/update/social_featured_items_update_8001.yml
- modules/social_features/social_featured_items/social_featured_items.install
- modules/social_features/social_featured_items/templates/paragraph--featured-item--default.html.twig
When you create a featured item on a landing page, you can define an url with a "read more". Only the text within this button is clickable while the whole button should work.
Move the classes around so the button itself is styled on the link and not the surrounding div.
https://www.drupal.org/project/social/issues/3089852
When creating a featured item for a landing page, only the link text was clickable. This has been fixed and now the complete button can be clicked.
> Issue #3089852 by robertragas: featured item link markup to make the whole button clickable

- modules/custom/social_gdpr/social_gdpr.installer_options.yml
- modules/custom/social_path_manager/social_path_manager.installer_options.yml
- modules/social_features/social_comment_upload/social_comment_upload.installer_options.yml
- modules/social_features/social_content_block/social_content_block.installer_options.yml
- modules/social_features/social_content_report/social_content_report.installer_options.yml
- modules/social_features/social_embed/social_embed.installer_options.yml
- modules/social_features/social_event/modules/social_event_an_enroll/social_event_an_enroll.installer_options.yml
- modules/social_features/social_event/modules/social_event_enrolments_export/social_event_enrolments_export.installer_options.yml
- modules/social_features/social_event/modules/social_event_managers/social_event_managers.installer_options.yml
- modules/social_features/social_event/modules/social_event_max_enroll/social_event_max_enroll.installer_options.yml
- modules/social_features/social_group/modules/social_group_default_route/social_group_default_route.installer_options.yml
- modules/social_features/social_landing_page/social_landing_page.installer_options.yml
- modules/social_features/social_private_message/social_private_message.installer_options.yml
- modules/social_features/social_profile/modules/social_profile_fields/social_profile_fields.installer_options.yml
- modules/social_features/social_profile/modules/social_profile_organization_tag/social_profile_organization_tag.installer_options.yml
- modules/social_features/social_profile/modules/social_profile_privacy/social_profile_privacy.installer_options.yml
- modules/social_features/social_tagging/social_tagging.installer_options.yml
- modules/social_features/social_user_export/social_user_export.installer_options.yml
Open Social includes a lot of optional modules but they may not be easily discovered. Additionally automation applications want to be able to enable these modules during site install.
This commit adds `installer_options.yml` to a lot of modules that we
currently install on platforms using _core modules.
Adding these files to these modules will make them available both to
`drush site-install` as well as through the installer UI. This increases
discoverability of these modules for distribution users and eases the
live of our own SaaS hosting :)
https://www.drupal.org/project/social/issues/3163317
*For example*
n.a.
The following modules can now also be chosen during initial site installation: social_gdpr, social_path_manager, social_comment_upload, social_content_block, …
> DS-7199 Make module installable from installer

- modules/social_features/social_core/config/optional/block.block.socialblue_local_actions.yml
- modules/social_features/social_core/config/update/social_core_update_8813.yml
- modules/social_features/social_core/social_core.install
There is layout misalignment in group invite form in Sky style.
Add `group/*/invite-members` to the `socialblue_local_actions` block.
- https://www.drupal.org/project/social/issues/3164021
Before:
After:
> Issue #3164021 by ribel: Fix layout misalignment in group invite form

- modules/social_features/social_event/modules/social_event_an_enroll_enrolments_export/social_event_an_enroll_enrolments_export.services.yml
When both social_event_enrollment_export and social_event_an_enroll_enrolments_export are enabled we see two Export buttons. Although the Export action in AN Enrollment is the only one we need, because it's extend the regular one.
`html/profiles/contrib/social/modules/social_features/social_event/modules/social_event_an_enroll_enrolments_export/src/SocialEventAnEnrollEnrolmentsExportOverrides.php`
Contained:
`$overrides[$config_name]['display']['default']['display_options']['fields']['social_views_bulk_operations_bulk_form_enrollments_1']['selected_actions']['social_event_enrolments_export_enrollments_action'] = 0;` Which was already in place, however this was not running due to the priority not being set correctly for it to run later than the Override consistently. …
> DS-7315: When AN and Event Enrollments is enabled there are 2 export buttons shown

- modules/social_features/social_event/modules/social_event_managers/social_event_managers.links.action.yml
- modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
- tests/behat/features/capabilities/group/group-edit-join-method-flexible.feature
Buttons to Add a Member to a Group and to Add an Enrollee to an Event sometime are not visible on the page, this happens for different roles.
Add proper cache context to button for event and add group manager's check in social_group_flexible_group_menu_local_actions_alter.
https://www.drupal.org/project/social/issues/3157175
https://getopensocial.atlassian.net/browse/TB-4365
N.A
There was an inconsistent caching bug due to which sometimes the group manager or event organizer was not able to see the "Add member" button if they have an LU role. It should be solved now.
N.A
N.A
> Issue #3157175 - Add member button

- modules/social_features/social_profile/modules/social_profile_fields/config/install/social_profile_fields.settings.yml
- modules/social_features/social_profile/modules/social_profile_fields/social_profile_fields.module
- modules/social_features/social_profile/modules/social_profile_fields/src/Form/SocialProfileFieldsFlushForm.php
- modules/social_features/social_profile/modules/social_profile_fields/src/Form/SocialProfileFieldsSettingsForm.php
- modules/social_features/social_profile/modules/social_profile_fields/src/SocialProfileFieldsBatch.php
- modules/social_features/social_profile/modules/social_profile_fields/src/SocialProfileFieldsHelper.php
Make sure postalcode can also be hidden
Implement possibility to enable/disable postalcode address's profile field 
https://www.drupal.org/project/social/issues/3137445
https://getopensocial.atlassian.net/browse/YANG-3511
Implement possibility to enable/disable Postal code address's profile field.
> Issue #3137445 by mdeny: Make sure postalcode can also be hidden

- modules/social_features/social_group/src/Plugin/Block/GroupStatisticBlock.php
I get an error when going to the group members page
Add an extra condition to the getcacheTags for GroupStatisticBlock
* https://www.drupal.org/project/social/issues/3164984
* https://getopensocial.atlassian.net/browse/YANG-3526
- Login as member
- Go to some basic course
- Go to the members tab manually
> Issue #3164984 by rolki: Add an extra condition to cacheTags method for GroupStatisticBlock

- modules/custom/social_path_manager/social_path_manager.module
After merging PR #1915 there are hero duplicates on content pages with aliases including words `add`, `edit`
Revert commit d90926e2 and implement a fix for missing her in external modules, see book config override for example.
- https://getopensocial.atlassian.net/browse/YANG-3491
> Revert "Issue 3144794: Replace paths with routs to avoid incorrect matches in conditions. (#1915)"

- modules/social_features/social_group/modules/social_group_request/social_group_request.module
When a CM or SM or admin visits a group, with the request to join a group setting enabled it gets redirected to a page with a debug message.
This is due to the fact we don't pass along the correct setting to twig which renders the ajax pop-up to request to join a group.
Make sure we pass along the correct variables in the preprocess_group so that twig knows what to render.
*Paste a link to the drupal.org issue queue item. If any other issue trackers were used, include links to those too.*
As a CM+ you can now also request to join a group when that setting is enabled.
> Issue #3167974: Ensure as CM+ we can also request to join a group

- themes/socialbase/templates/node/event/node--event--full.html.twig
- themes/socialblue/templates/node/node--full--sky.html.twig
The 'Ongoing' label is shown in the main content of the event.
Update the node event template.
https://www.drupal.org/project/social/issues/3169519
https://getopensocial.atlassian.net/browse/YANG-3667
> Issue #3169519 by tBKoT: Remove the 'Ongoing' label on main event page

- themes/socialblue/assets/css/teaser--sky.css
- themes/socialblue/assets/css/teaser.css
- themes/socialblue/components/03-molecules/teaser/teaser--sky.scss
- themes/socialblue/components/03-molecules/teaser/teaser.scss
At landing pages or group pages, I can no longer see the number of members of the group.
Update color number of members of the group teasers
https://www.drupal.org/project/social/issues/3169448
https://getopensocial.atlassian.net/browse/YANG-2974
before:
after:
The badge label has a correct color on the teasers
Update color for the badge label on the teasers for blue and sky themes
> Issue #3169448 by agami4: Fix color for the badge label on the group teasers

- themes/socialbase/templates/card/bootstrap-panel.html.twig
When I hide some fields on the node edit form I still can see empty blocks
Add an extra condition to bootstrap-panel.html.twig template
https://www.drupal.org/project/social/issues/3166552
> Issue #3166552 by rolki: Issue with empty blocks in entity form display

- modules/custom/activity_creator/activity_creator.install
- modules/custom/activity_creator/src/ActivityNotifications.php
There is an error in \Drupal\activity_creator\ActivityNotifications::deleteNotificationsByIds. On line 260 of ActivityNotifications.php the line ->condition('aid', $activity_ids) is used, where $activity_ids is an array. However, the default comparison operator for condition is = which causes issues in the query, resulting in unremoved activities.
- Ensure the correct operator is used in the condition, in this case, add "IN" as the third argument. Similar to what's done on line 196 of the same file
- Create an update hook that cleans up any notifications for whom the user or associated entity no longer exists.
https://www.drupal.org/project/social/issues/3162557
> Issue #3162557 by tBKoT, Kingdutch: Update delete notification condition

- modules/social_features/social_activity/social_activity.tokens.inc
- modules/social_features/social_comment/social_comment.tokens.inc
The e-mail notification for a reply to a comment on a discussion is not working properly. It doesn't contain a snippet of the text/comment.
Remove hardcoded limitation only for topics and events. We don't need it here.
- https://getopensocial.atlassian.net/browse/YANG-3478
- https://github.com/goalgorilla/open_social/pull/1304
> YANG-3478: Allow to use social activity token in other content types, like Discussion

- themes/socialblue/src/Plugin/Preprocess/Html.php
- themes/socialblue/src/Plugin/Preprocess/Page.php
- themes/socialblue/templates/layout/page--user--edit--sky.html.twig
- themes/socialblue/templates/layout/page--user--profile--sky.html.twig
When SKY is enabled and a user visits the edit profile or edit user page, any blocks (like the data policy from social_gdpr) are rendered incorrect. Either on the left side of the main content, or on the right side without margin for the page title.
Make sure we render the blocks on the above pages correctly on the right side, with necessary margin.
https://www.drupal.org/project/social/issues/3166522
Before:
After
When choosing the SKY style in our theme, on the user edit and edit profile page we now render any blocks correctly in the sidebar on the right.
> Issue #3166522: Sky theme - Render blocks on user edit and profile edit on the right side.

- themes/socialbase/templates/group/group--default.html.twig
In https://www.drupal.org/project/social/issues/3071081: Make field label visible by respecting field UI settings the group--default.html.twig template was updated to be able to show the field label.
Some issues with field labels were fixed in https://www.drupal.org/project/social/issues/3108296: Field labels are now shown for multiple display modes of multiple entities but the display configuration for groups is still set to show the label eventhough we only render the group description.
We have reverted the changes, so we only render the description field, if necessary this field can have it's label rendered using the manage display settings. So we are not causing the former to not work anymore. It feels like this was added without knowing we are not showing the field label, we are …
> Issue #3144847: Groups about page shows entity label/title

- themes/socialbase/src/Plugin/Preprocess/Node.php
When enabling social_sharing, with SKY theme enabled the social sharing buttons arent rendered for AN on public content.
`{% if content.shariff_field and visibility_icon == 'public' %}
<div class="hero-footer__share">
<span>{% trans %} Share this page {% endtrans %}</span>
{{ content.shariff_field }}
</div>
{% endif %}`
On NON Sky we use the shariff block which is not affected by this.
Make sure the twig statement in node--hero--sky gets the correct data. 
The visibility icon was only set for LU+ not for AN, therefor it never came in this statement.
So we need to ensure for AN this is also OK.
https://www.drupal.org/project/social/issues/3166533
When you have enabled SKY and social_sharing you are now able to share a public page again as anonymous user.
> Issue #3166533: SKY theme on public content with social sharing enabled the share buttons dont get rendered for AN

- themes/socialbase/src/Plugin/Preprocess/Container.php
When logged in as a site manager, if you are on a search page when caches haven't been build yet, you'll end up with a broken Gin admin toolbar as shown in the screenshot:
In `themes/socialbase/src/Plugin/Preprocess/Container.php`, we check whether we are on a search path and set the variable `bare` to TRUE. This should stay in place because it will otherwise break search pages in a different manner. We will add a specific case to the Preprocess class which will set `bare` to be `FALSE` when we are dealing with the element `administration_menu`
https://www.drupal.org/project/social/issues/3170776
The before situation is shown above.
After:
- We squashed a bug where the administration toolbar would not load correctly when cache was not build up yet on certain search pages.
> Issue #3170776 by sjoerdvandervis: Do not set template variable to TRUE when Gin admin menu is handled

- modules/social_features/social_core/social_core.module
In the block "All my upcoming events" we use the translatable `All @label` where `@label` is the translation for `My upcoming events". This does work correctly in English but not in other languages, as the word `All` can have different translations based on the text that follows. For instance, in Dutch this would translate to "Al mijn aankomende evenementen" while `All upcoming events in the community` would translate to `Alle aankomende evenementen in de community`. You see that All has a different translation based on what follows it.
Use the full translation that is being used in views for the More label.
https://getopensocial.atlassian.net/browse/TB-4603
*We changed the way the translatable is loaded for the All My upcoming events block, so that we use the full translation instead of …
> TB-4603 - "All my upcoming events" is not translatable correctly

- composer.json
URL Embed module has done a new release version.
This version contains one of the major improvements in embed library as mention here: https://www.drupal.org/project/url_embed/releases/8.x-1.0-beta1
This will also solve the problem of support of Instagram mentioned here: https://www.drupal.org/project/url_embed/issues/3150213
1. Update module version
2. Remove dependencies lock in favor of https://git.drupalcode.org/project/url_embed/-/blob/8.x-1.0-beta1/composer.json
https://www.drupal.org/project/social/issues/3165299
https://www.drupal.org/project/social/issues/2930457
in composer.json - patches:
```
"drupal/url_embed" : {
"Improve performance for embeds": "https://www.drupal.org/files/issues/2020-04-08/url_embed-n2867668-23.patch",
"Improve how the module deals with non-embeddable …
```
> Issue #3165299 by navneet0693: Upgrade the url_embed module version.

- modules/custom/activity_creator/activity_creator.install
In PR #1956 we introduced batch update of all activity entities in `activity_creator_update_8802()`.
During update to latest 8.x-8.x on one of project with around 30000 activities, I received memory outage during this batch, both locally and on Platform.sh.
I propose to increase the number of items from 10 to at least 100 to have this batch finished.
When I tried this locally all was good, but on Platform.sh it was not enough even when I increased to 200, but I am also not sure to what value it's good to increase.
- https://github.com/goalgorilla/open_social/pull/1965
N.A
N.A
N.A
N.A
> Issue #3162557: Increase number of activities per one batch operation

- modules/social_features/social_event/assets/css/social-event--admin.css
- modules/social_features/social_event/assets/css/social-event--admin.scss
- modules/social_features/social_event/social_event.module
There are some inconsistencies in the event create/edit page that will make the page harder to understand.
Incorrect copy text under timezone.
1. Update text
2. Change/add classes for correct styles
- https://getopensocial.atlassian.net/browse/YANG-3671
- https://github.com/goalgorilla/open_social/pull/1921
**Before:**
**After**
N/A
N/A
N/A
> YANG-3671: Fix text copy and styles for event date & time fields

- .travis.yml
The script already provides an interpreter in the script
file itself using the SHEBANG. This allows the script to
execute using `bash` providing all the features it needs.
The `sh` shell does not provide the features needed.
We should consider doing this for the other scripts too.
However, we will need to make sure the scripts are executable
in the script repository.
Remove the shell invocation. The `run-tests.sh` and `unit-tests.sh` scripts have been given executable status (`chmod +x`) in the scripts repository.
No issue, internal CI hotfix.
Travis should pass again.
Not applicable
Not applicable
Not applicable
Not applicable
> Don't invoke a separate shell to run unit-tests

- modules/social_features/social_event/social_event.module
Needs to change the timezone label for the event from the city name to the timezone's abbreviation
Use date format `T` instead of timezone from core
https://getopensocial.atlassian.net/browse/YANG-2960
https://getopensocial.atlassian.net/browse/YANG-3728
**Before:**
**After:**
Now user see timezone abbreviation instead of the city name
N/A
N/A
> Issue #3162222 by tBKoT: Change timezone label from the city name to the timezone's abbreviation

- themes/socialbase/assets/js/navbar-main-menu.min.js
- themes/socialbase/components/03-molecules/navigation/navbar/navbar-main-menu.js
- themes/socialbase/socialbase.libraries.yml
When you click on the second level(if this level has children elements) menu I can not move to the page.
Remove bootstrap attributes from the second-level menu(if this level has children elements).
https://www.drupal.org/project/social/issues/3172705
N.A
When you click on the second level(if this level has children elements) menu I can move to the page.
> Issue #3172705 by agami4: Remove bootstrap attributes from second level menu if this level has children elements

- themes/socialbase/assets/css/cards.css
- themes/socialbase/components/02-atoms/cards/cards.scss
- themes/socialblue/assets/css/stream--sky.css
- themes/socialblue/components/04-organisms/stream/stream--sky.scss
The spacing in the right column is 12 px, and in the left column is 24 px. They should both be 20 px.
Update margin-bottom to 20px for the 'card' class
https://www.drupal.org/project/social/issues/3170824
*For example*
before:
after:
The margin-bottom was changed from 12px to 20px for both themes
> Issue #3170824 by agami4: Update margin-bottom for the "card" class for both themes

- modules/custom/activity_creator/activity_creator.install
- modules/custom/activity_creator/activity_creator.post_update.php
I started working on the issue https://www.drupal.org/project/social/issues/3171563 and I created a solution here: https://github.com/goalgorilla/open_social/pull/1986. But even this solution was leading to memory outage no matter if the batch size is 10 or 10000. So, I decided to take a different approach to solve the issue.
1. Use database queries instead of Entity APIs to solve the problem reported here: https://www.drupal.org/project/social/issues/3162557
2. Split the updates into two updates.
3. First update hook should delete non-existent Activity IDs from **activitiy_notification_status** table.
4. Second update hook should delete the Activity entities which doesn't have any value in "field_activity_entity".
https://www.drupal.org/project/social/issues/3171563
N.A
In a past release …
> Issue #3171563 by navneet0693: Moved logic from activity_creator_update_8802 to hook_post_update_name and refactored.

- themes/socialbase/assets/css/base.css
- themes/socialbase/assets/css/like.css
- themes/socialbase/components/01-base/links/_links.scss
- themes/socialbase/components/03-molecules/like/like.scss
The focus of elements don't work in Firefox and possibly also in other browsers
Update styles for the focus of the elements
https://www.drupal.org/project/social/issues/2947668
*For example*
Added style updates for the focus of the elements.
> Issue #2947668 by agami4: Check and add updates to focus links [Accessibility]

- themes/socialbase/assets/css/teaser.css
- themes/socialbase/components/03-molecules/teaser/teaser.scss
At a screen width of 320px, the content of a featured content item teaser will overflow. The author text is properly truncated for teasers on a desktop (1200px) but this doesn't seem to work on mobile devices.
Update with styles for the `teaser__body` on the mobile.
https://www.drupal.org/project/social/issues/3171630
*For example*
On small devices (320px) the features content items on a landing page no longer overflow
> Issue 3171630 by agami4: Update styles for the teaser__body

- themes/socialbase/assets/css/navbar.css
- themes/socialbase/components/03-molecules/navigation/navbar/navbar.scss
The form with ID search-content-form is used to show the search overlay. However, even when this overlay is not visible the form still captures focus.
Adjust the `search-take-over` class to use `display:none` and add `display: initial` to the `.mode-search .search-take-over ` selector. The search icon itself should be keyboard and screenreader accessible to make the search overlay visible.
https://www.drupal.org/project/social/issues/3171792
*For example*
The search form is no longer in the tab order when it's not visible. No visual changes.
> Issue #3171792 by agami4: Update styles for the show/hide search popup

- modules/social_features/social_core/social_core.install
- themes/socialblue/theme-settings.php
When GIN is the admin theme, and socialblue the default theme we can try and update the brand colors in GIN to match the socialblue ones. This will give a better admin experience.
Create an update hook to override the gin settings if we have the socialblue as default and gin as admin.
Also write a custom form submit function which listens to the system_theme form being submitted. 
Both SocialBlue as the color module actually use this form to update the necessary style settings.
https://www.drupal.org/project/social/issues/3174646
Update the GIN admin theme colors so they actually adhere to your custom branded primary and secondary colors.
> Issue #3174646 - impoved colors gin theme based on social blue

- themes/socialbase/templates/post/post--activity.html.twig
- themes/socialbase/templates/post/post.html.twig
- themes/socialblue/color/preview.html
When adding a link to a topic, you see that the color of the link within the body adheres to the color settings configured for the Link color in the theme settings. See the bold text in the previewed html.
For Post this isnt the case. Let's make sure it does. 
https://www.drupal.org/project/social/issues/3174638
Links in a post will now understand that it needs to follow the theme color configuration.
> Issue #3174638 - Make sure links in a post get the correct configured theme color applied

- modules/social_features/social_event/modules/social_event_addtocal/social_event_addtocal.links.menu.yml
- modules/social_features/social_event/modules/social_event_addtocal/social_event_addtocal.module
- modules/social_features/social_event/modules/social_event_addtocal/src/Form/SocialAddToCalendarSettingsForm.php
For the `Add to calendar` feature we have a configuration page. But if we select only one calendar for it the button 'Add to Calendar' on the event page doesn't work.
Check the number of links before the render button. If the count of links is 1 don't use the 'no-split' attribute.
https://www.drupal.org/project/social/issues/3174889
*For example*
N/A
N/A
N/A
N/A
> Issue #3174889 by tBKoT: Bug with only one selected calendar in settings

- modules/social_features/social_activity/social_activity.module
The link that pops open the notification center in the header doesn't contain a path to link to. This reduces accessibility for users of screen readers and also makes the notification center inaccessible when not using JavaScript.
Make sure the link links to the notification center. The current JavaScript implementation already prevents the default behavior and opens the pop-up as desired.
https://www.drupal.org/project/social/issues/3171778
*For example*
The 'notification center' button now links to the notification page. This was previously an anchor tag without a valid href which is invalid.
-
-
> Issue #3171778 by agami4: Add url to the notification center button(icon ring bell)

- themes/socialbase/templates/group/group--hero.html.twig
- themes/socialbase/templates/node/node--hero.html.twig
- themes/socialbase/templates/profile/profile--profile--hero.html.twig
- themes/socialblue/templates/group/group--hero--sky.html.twig
- themes/socialblue/templates/node/node--hero--sky.html.twig
- themes/socialblue/templates/profile/profile--profile--hero--sky.html.twig
The pencil edit button that's displayed in the hero contains an SVG element that does not contain an alternative text or title element, this means the edit button is not accessible for screen readers.
Add the required alternative or title text to the SVG.
https://www.drupal.org/project/social/issues/3171498
-
The pencil icon to edit the current page now has a title attribute, improving accessibility.
-
-
> Issue #3171498 by agami4: Add title to edit content svg icon on the all pages

- themes/socialbase/templates/private_message/private-message-thread.html.twig
When viewing a private message conversation, there's an icon shaped like a "left arrow" in the top left corner. This icon allows you to go back to your inbox. The link does not contain any text indicating where the link goes so screen reader users only hear "link".
Add `aria-hidden="true"` to the SVG icon and add title to the `back to infobox` button.
https://www.drupal.org/project/social/issues/3171566
*For example*
The `back to infobox` has the `title` attribute and SVG icon has `aria-hidden="true"` attribute.
-
-
> Issue #3171566 by agami4: Make back infobox icon not visible for the accessibility tree and add title to button

- modules/social_features/social_post/modules/social_post_photo/js/post-widget.js
- themes/socialbase/assets/css/image-widget.css
- themes/socialbase/components/03-molecules/form-elements/image-widget/image-widget.scss
- themes/socialbase/templates/file/image-widget.html.twig
When adding an image to a post, the image will show up and be overlaid with a button containing a cross that allows the removal of the image. This button correctly has a text for screenreaders but it does not mark the SVG cross image as being decorative.
Remove focus styles and add `aria-hidden="true"` for the `post remove image` button.
- https://www.drupal.org/project/social/issues/3171502
- https://www.drupal.org/project/social/issues/3134488
*For example*
The `post remove image` button has not focus styles and has `aria-hidden="true"`
-
-
> Issue #3171502 by agami4: Make post remove image button not visible for the accessibility tree

- themes/socialbase/assets/css/form-elements.css
- themes/socialbase/components/03-molecules/form-elements/form-elements.scss
- themes/socialbase/templates/card/bootstrap-panel.html.twig
- themes/socialbase/templates/form/fieldset.html.twig
- themes/socialbase/templates/form/form--group.html.twig
In Open Social we have two templates in socialbase that produce fieldset output in many places. However, these fieldsets don't properly use the legend tag, causing difficulties for users of screenreaders while filling in the form.
Add `legend` HTML tag to the `fieldset`.
https://www.drupal.org/project/social/issues/3171606
*For example*
-
The fieldset elements have a legend HTML tag.
-
-
> Issue #3171606 by agami4: Add "legend" HTML tag to the fieldset

- themes/socialbase/templates/block/block--system-menu-block--main.html.twig
The search icon in the menu bar contains a help text. However, this help text isn't actually visible for screen readers.
Replace <span class="invisible">Search</span> with <span class="sr-only"Search</span> and add `aria-hidden="true"`
https://www.drupal.org/project/social/issues/3171785
*For example*
The help text search button not visible for the accessibility tree.
-
-
> Issue #3171785 by agami4: Make help text search button not visible for the accessibility tree

- modules/social_features/social_post/js/visibility-settings.js
- themes/socialbase/templates/file/image-widget.html.twig
- themes/socialbase/templates/form/dropdown.html.twig
The ID `btnicon` is used in image-widget.html.twig as well as dropdown.html.twig. This usage causes it to show up multiple times on the same page. Having an ID duplicated on a page is invalid.
This ID seems to be used in the visibility-settings.js file.
Replace id with class and update js behavior
https://www.drupal.org/project/social/issues/3171814
*For example*
-
Replaced `btnicon` id with class and updated js behavior
-
-
> Issue #3171814 by agami4: Replace id with class and update js behavior

- themes/socialbase/assets/css/teaser.css
- themes/socialbase/components/03-molecules/teaser/teaser.scss
The 3rd line of the teaser title is cut off on Safari.
Update max-height for the teaser title.
- https://www.drupal.org/project/social/issues/3175438
- https://getopensocial.atlassian.net/browse/YANG-3871
*For example*
before:
after:
The title has a maximum of two lines on the teaser
-
-
> Issue #3175438 by agami4: Update max-height for the teaser title

- modules/social_features/social_search/config/install/search_api.index.social_all.yml
- modules/social_features/social_search/config/install/search_api.index.social_content.yml
- modules/social_features/social_search/config/install/search_api.index.social_groups.yml
- modules/social_features/social_search/config/install/search_api.index.social_users.yml
- modules/social_features/social_search/social_search.install
When indexing the nodes' `Rendered HTML` with a very big body (more than 4 000 000 symbols) the Search API index leaked out of memory.
Change the weight of Search API index HTML filter processors on indexing.
https://www.drupal.org/project/social/issues/3176585
https://getopensocial.atlassian.net/browse/YANG-3892
N/A
Changed weight of HTML filter processor for better indexing.
N/A
N/A
> Issue #3176585 by tBKoT: Out of memory on search indexing

- modules/social_features/social_featured_content/templates/group--featured.html.twig
- modules/social_features/social_featured_content/templates/node--event--featured.html.twig
- modules/social_features/social_featured_content/templates/node--featured.html.twig
- themes/socialbase/assets/js/navbar-collapse.min.js
- themes/socialbase/components/03-molecules/navigation/navbar/navbar-collapse.js
- themes/socialbase/templates/group/group--teaser.html.twig
- themes/socialbase/templates/node/event/node--event--teaser.html.twig
- themes/socialbase/templates/node/node--teaser.html.twig
- themes/socialbase/templates/node/node--teaser__field.html.twig
- themes/socialbase/templates/profile/profile--profile--teaser.html.twig
- themes/socialblue/templates/node/event/node--event--featured--sky.html.twig
- themes/socialblue/templates/node/event/node--event--teaser--sky.html.twig
- themes/socialblue/templates/node/node--featured--sky.html.twig
- themes/socialblue/templates/node/node--teaser--sky.html.twig
Teasers use icons to convey the meaning of values that are shown. These icons do not have alternative labels so it's unclear for users using assistive technology (e.g. screen readers) what information they're being read.
Add the title to SVG elements for all type of the teasers
https://www.drupal.org/project/social/issues/3171512
-
Featured content on landing pages should now be easier to navigate using a screenreader. The information conveyed in teasers has a clear title.
-
-
> Issue #3171512 by agami4: Add title to SVG elements for all type of the teasers

- composer.json
- modules/custom/social_ajax_comments/social_ajax_comments.info.yml
- modules/custom/social_ajax_comments/social_ajax_comments.module
- modules/custom/social_ajax_comments/social_ajax_comments.routing.yml
- modules/custom/social_ajax_comments/social_ajax_comments.services.yml
- modules/custom/social_ajax_comments/src/Controller/AjaxCommentsController.php
- modules/custom/social_ajax_comments/src/Routing/RouteSubscriber.php
- modules/social_features/social_comment/src/SocialCommentLazyRenderer.php
- modules/social_features/social_mentions/js/social_mentions.js
- themes/socialbase/includes/form.inc
- themes/socialbase/socialbase.theme
- themes/socialbase/src/Plugin/Preprocess/Field.php
- themes/socialbase/src/Plugin/Preprocess/Node.php
- themes/socialbase/templates/comment/field--comment.html.twig
- themes/socialbase/templates/comment/form--comment.html.twig
We have tried to solve several issues which were encountered when using Ajax comments.
1. Ajax comments breaks landing pages and dashboards, when using the Views block, content in de activity stream is rendered using a wrong display mode.
2. Ajax comments and the lazy builder do not work well together, see: 2018
3. Replying on a reply, or replying on a comment do not render correctly. Messages are in the wrong place.
4. Error with "top" undefined when clicking on the reply button
Make sure we stabilize social_ajax_comments. Update the ajax_comments patch and help it being committed.
All the below should be fixed:
https://www.drupal.org/project/social/issues/3108608
https://www.drupal.org/project/social/issues/3167492
Ajax comments are now stable.
> Issue #3108608 - Stability of Ajax comments

- .travis.yml
Travis runs
```
composer self-update
Upgrading to version 2.0.6 (stable channel).
Use composer self-update --rollback to return to version 2.0.4
```
While we don't support it yet, breaking our tests.
**Solution 1. Rollback to v1 untill we support it.** 
Solution 2. In a separate PR is to remove hirak/prestissimo and see if v2 actually does work in tests. hirak/prestissimo isn't necessary anymore for composer v2 since performance is much improved (also they announced it themselves) 
Solution 2 is tested in #2059 
So lets see which one is green!
None
See if tests succeed.
> Travis self-updates to v2 of composer while we don't support it (yet).

- .travis.yml
- composer.json
- tests/behat/features/capabilities/topic/topic-overview-filter.feature
Drupal core ^8.8 won't receive support anymore soon. Lets update our 9.x / 8.x versions of OS with this version. 
Drupal core 9.x will be supported in 10.0.x
Update core in the composer.json to ~8.9.9 
https://www.drupal.org/project/social/issues/3183500
Here you find a screenshot of the update path
We now support Drupal Core 8.9.x versions.
> Issue #3183500: Update drupal core to 8.9^

- modules/social_features/social_content_report/social_content_report.module
- modules/social_features/social_content_report/social_content_report.services.yml
- modules/social_features/social_content_report/src/ContentReportService.php
Critical bug in AJAX Comments + Report. When:
a) posting a comment
b) directly report that comment for abuse
c) system crashes
The solution is to create a different destination url on the report form, when the comment was inserted in the DOM through an ajax request.
https://getopensocial.atlassian.net/browse/TB-5356
https://www.drupal.org/project/social/issues/3186203
An issue was fixed, where one would report one's own comment (made with ajax), a redirect would be made to a white screen with nothing more than a textarea.
> Reporting (ajax) comments leads to white screen 

- themes/socialbase/src/Plugin/Alter/ThemeSuggestions.php
- themes/socialbase/templates/system/details--collapsible.html.twig
Right now our details element is not working properly, we have created it custom within code but that is not extendable enough, also see screenshots for the current issue. 
We want it to look more appealing, whilst also being able to re-use it using Drupals Field UI and adding fields to it / remove it / ordering weights etc.
We have added a new theme suggestion, for those who want to use this element please use the below settings in the manage form display:
- http://drupal.org/node/3186003 - Doesn't need to be closed, this is just an enabler for the work later.
Before:
After:
Will be added later, this is just an enabler for the epic.
> Issue #3186003 - Part 1: Enabler - Create re-usable details element, which is collapsible.

- .github/workflows/drupalCodingStandards.yml
- .travis.yml
- composer.json
- modules/custom/activity_creator/activity_creator.post_update.php
- modules/custom/dropdown/src/Plugin/Field/FieldType/Dropdown.php
- modules/social_features/social_event/src/Plugin/views/sort/EventPassedDesc.php
- modules/social_features/social_like/social_like.module
- modules/social_features/social_profile/social_profile.module
- modules/social_features/social_search/social_search.module
- phpcs.xml
- themes/socialbase/src/Plugin/Preprocess/SocialBaseImageWidget.php
Travis gave us quite some issues with coding standards, we decided travis is not the way forward as it's also not fully free for open source software anymore.
We took the liberty to move towards github actions instead. While doing so we also added the following:
- (Potentially Composer v2 support, not verified yet but it seems it runs on v2)
- phpcs.xml where we configure the coding standards 
- Update drupal/coder so we benefit from the latest coding standards
- Unfortunately this gave a ton of errors which we cant fix that easily, so we decided to exclude some in our phpcs.xml
None - Only internal usage as coding standards applied before.
See the new github actions are green!
None - Internal only.
> Developer task - Use github actions for coding standards check on a PR.

- modules/social_features/social_core/social_core.api.php
- themes/socialbase/src/Plugin/Preprocess/Page.php
Title block duplicates on the discussion pages.
Add alter hook to modify the list of content types where need to hide the default title block
https://www.drupal.org/project/social/issues/3175203
https://getopensocial.atlassian.net/browse/YANG-3709
Create a new hook (`hook_social_content_type_alter`) that allow modifying the list of content types where need to hide the default title block
N/A
N/A
> Issue #3175203 by tBKoT: Create an alter hook to modify the list of content type where need to hide the default title block

- modules/social_features/social_event/modules/social_event_addtocal/social_event_addtocal.routing.yml
- modules/social_features/social_event/modules/social_event_addtocal/src/Controller/AddToCalendarIcsController.php
- modules/social_features/social_event/modules/social_event_addtocal/src/Plugin/SocialAddToCalendar/AddToICal.php
- modules/social_features/social_event/modules/social_event_addtocal/src/Plugin/SocialAddToCalendarBase.php
Need to add the `iCal` option to the `Add to Calendar` feature.
Create a plugin with the `iCal` option.
Create a controller to download the ICS file.
https://www.drupal.org/project/social/issues/3176854
https://getopensocial.atlassian.net/browse/YANG-3712
Now SM could choose the `iCal` as one of the options for adding the event to the calendar
N/A
N/A
> Issue #3176854 by tBKoT: Add iCal option to the 'Add to calendar' feature

- themes/socialbase/assets/css/form-controls.css
- themes/socialbase/components/02-atoms/form-controls/form-controls.scss
- themes/socialbase/templates/block/block--views-exposed-filter-block.html.twig
- themes/socialblue/assets/css/offcanvas--sky.css
- themes/socialblue/components/04-organisms/offcanvas/offcanvas--sky.scss
1. The select has the wrong styles
2. Filter button isn't visible on the mobile screen
Add style update for the select and filter button(on the mobile screen)
- https://www.drupal.org/project/social/issues/3186442
widget before:
widget after:
filter before:
filter after:
Social tagging select widget has the correct styles and the filter button is visible on the mobile screen.
-
-
> Issue #3186442 by agami4: Fix styles for the tag select on the filter form and fix position for the filter button on the mobile screen

- modules/social_features/social_group/modules/social_group_welcome_message/social_group_welcome_message.module
- modules/social_features/social_private_message/src/Plugin/ActivityContext/PrivateMessageActivityContext.php
- modules/social_features/social_private_message/src/Plugin/EntityReferenceSelection/UserSelection.php
- modules/social_features/social_private_message/src/Plugin/Field/FieldWidget/SocialPrivateMessageThreadMemberWidget.php
- modules/social_features/social_private_message/src/Service/PrivateMessageMailer.php
- modules/social_features/social_profile/social_profile.module
As LU I only want to be able to write messages to users that have permission to see them
Check if the user has the `use private messaging system` permission before sending him an email related to private messages.
https://www.drupal.org/project/social/issues/3182368
https://getopensocial.atlassian.net/browse/YANG-3889
N/A
Now users that don't have permission to view private messages do not receive emails. 
N/A
N/A
> Issue #3182368 by tBKoT: Don't send any message if user don't have permission to view it

- .github/workflows/drupalCodingStandards.yml
PHPCS is failing, lets fix it.
https://github.com/actions/virtual-environments/issues/1816
By using ubuntu-latest by default github actions use the latest supported PHP version, which is 8.0
Either use 18.04 of ubuntu, or specify the php version.
None.
Lets see test turn green.
> PHPCS - Fix github actions / ubuntu-latest which uses PHP 8.0 we don't support yet.

- modules/social_features/social_core/social_core.module
- modules/social_features/social_page/config/install/core.entity_form_display.node.page.default.yml
- modules/social_features/social_page/config/install/field.field.node.page.field_files.yml
- modules/social_features/social_page/config/update/social_page_update_8905.yml
- modules/social_features/social_page/social_page.install
- modules/social_features/social_tagging/social_tagging.module
Rename the fieldset labels and move the field to new fieldsets for Page content type.
1. Rename Content → Basic details
2. Rename Group & Visibility → Access permissions
3. Rename Attachments → Additional details
4. Add Settings
5. Move description field to Basic details
6. Remove Description fieldset
7. Add the following fields to the new “Settings” fieldset: Comment setting, URL Alias, Author information, Published status
https://www.drupal.org/node/3186003
**Page - Before**
**Page - After**
Will be dealt with in the parent issue.
> Issue #3186003 by navneet0693: DS-7442 - Updated fieldsets and re-arranged fields in new order for "Basic Page" CT

- modules/social_features/social_group/modules/social_group_default_route/social_group_default_route.module
- modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_form_display.group.flexible_group.default.yml
- modules/social_features/social_group/modules/social_group_flexible_group/config/install/field.field.group.flexible_group.field_group_image.yml
- modules/social_features/social_group/modules/social_group_flexible_group/config/update/social_group_flexible_group_update_8904.yml
- modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install
- modules/social_features/social_group/modules/social_group_welcome_message/src/SocialGroupWelcomeMessageConfigOverride.php
- modules/social_features/social_tagging/social_tagging.module
Follow-up of https://github.com/goalgorilla/open_social/pull/2121. Update sub-modules and social tagging module to add their respective custom fieldsets in correct fieldsets.
1. Manually add "-label" key in update helper files.
2. Update social_group_default_route, social_tagging and social_group_welcome_message modules.
3. Change label of Group image field.
https://www.drupal.org/node/3186003
> Issue #3186003 by navneet0693: DS-7438 - Updated fieldsets with new labels and re-arranged fields in Flexible group.

- tests/behat/features/bootstrap/FeatureContext.php
Whenever you embed a link in an iFrame sometimes it strips out the query fragments/attributes resulting in the src not completely matching what you put in.
That could result in adding a link like:
`https://www.youtube.com/embed/lh3xOx8eutQ"
But the link inside the iFrame contains
`src="https://www.youtube.com/embed/lh3xOx8eutQ?feature=oembed"`
Try to not exactly match the source, but see if the source contains.
> Developer task - Update the custom step.

- .travis.yml
We run in to this:
> You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
https://travis-ci.community/t/docker-hub-you-have-reached-your-pull-rate-limit/10517/9
Use a mirror which can cache our public available images so it gets the cached image and doesn't hurt the rate limits.
> Internal - Lets see if we can use a cached mirror for our public images

- modules/social_features/social_post/templates/post--featured.html.twig
The more" link has the wrong position and style
Add extra wrappers for the body for the post featured
https://getopensocial.atlassian.net/browse/YANG-4377
https://www.drupal.org/project/social/issues/3189783
*For example*
-
Add extra wrappers for the body for the post featured(for the dashboard page)
-
-
> Issue #3189783 by agami4: Add extra wrappers for the body on the post featured

- modules/social_features/social_group/modules/social_group_invite/config/optional/views.view.social_group_invitations.yml
- modules/social_features/social_group/modules/social_group_invite/config/optional/views.view.social_group_user_invitations.yml
- modules/social_features/social_group/modules/social_group_invite/social_group_invite.install
Invite pagination links are buggy at the bottom of the invite overview page
Update views configuration
https://getopensocial.atlassian.net/browse/YANG-4414
https://www.drupal.org/project/social/issues/3189693
N/A
N/A
N/A
> Issue #3189693 by tBKoT: Fix pagination text on invitation views

- modules/social_features/social_event/social_event.install
- themes/socialbase/templates/node/field--node--field-files.html.twig
In https://github.com/goalgorilla/open_social/pull/2095 , we made it possible to attach files of image types to a node. However, if only images are uploaded, the correct stylesheet is not included in the page. Therefor, the page looks formatted incorrectly.
We will now add the stylesheet whenever the field_files is shown for the node.
https://www.drupal.org/project/social/issues/3187257
*For example*
We've included the option to add images to events, topics and pages as attachments. When uploading images as attachments to events / topics / pages, they will now be shown as thumbnails instead of a regular file icon.
> Issue #3187257 by sjoerdvandervis: add stylesheet of files when files are attached

- modules/custom/social_devel/social_devel.module
- modules/custom/social_path_manager/social_path_manager.module
- modules/social_features/social_group/social_group.module
In the Open Social profile, we have the `social_path_manager` module that generates aliases for group tabs. However, it skips a lot of tabs and generates aliases without correct language from the group entity.
1. Modify the alter hook that unset some tabs.
2. Set the language for alias from a group entity.
https://www.drupal.org/project/social/issues/3189847
https://getopensocial.atlassian.net/browse/YANG-4014
*For example*
N/A
N/A
N/A
N/A
> Issue #3189847 by tBKoT: Generate consistent aliases for all group tabs

- themes/socialbase/assets/css/comment.css
- themes/socialbase/components/04-organisms/comment/comment.scss
- themes/socialbase/templates/comment/field--comment.html.twig
The comment block has not loading-throbber icon when comments are loading.
Add loading-throbber for the comment section on all content types.
- https://www.drupal.org/project/social/issues/3189814
- https://getopensocial.atlassian.net/browse/YANG-4041
*For example*
When comments are loading you will see the loading-throbber icon.
-
-
> Issue #3189814 by agami4: Add indication for comments section that comments are loading

- themes/socialblue/assets/css/brand.css
- themes/socialblue/components/brand.scss
The download link on the no-background certificate has the wrong color.
Update download link color on the no-background certificate.
https://www.drupal.org/project/social/issues/3190090
*For example*
The download link has a primary color on the no-background certificate.
-
-
> Issue #3190090 by agami4: Update download link color for the social_certificate module

- modules/social_features/social_profile/modules/social_profile_organization_tag/src/SocialProfileOrgTagConfigOverride.php
- modules/social_features/social_tagging/social_tagging.install
- modules/social_features/social_tagging/social_tagging.module
- modules/social_features/social_tagging/src/Form/SocialTaggingSettingsForm.php
- modules/social_features/social_tagging/src/SocialTaggingOverrides.php
- modules/social_features/social_tagging/src/SocialTaggingService.php
- themes/socialbase/templates/profile/profile--profile--default.html.twig
- themes/socialblue/templates/profile/profile--profile--default--sky.html.twig
As a LU I want to be able to filter on all the attributes added to the profile
Expand Social Tagging feature on user profiles
- https://www.drupal.org/project/social/issues/3189003
- https://getopensocial.atlassian.net/browse/YANG-4352
https://www.figma.com/proto/eFn9UYCaSnerZgx9vxsmbR/Open-Social-Design-System?node-id=5097%3A4&viewport=639%2C775%2C0.5&scaling=min-zoom
> Issue #3189003 by mdeny: Expand Social Tagging feature on user profiles

- modules/custom/social_lets_connect/modules/social_lets_connect_contact/social_lets_connect_contact.links.menu.yml
People using Open Social sometimes do not know of the Extensions offered by Open Social. We want to show this possibility by adding a menu item to the Social Lets Connect module, which is rendered in the admin menu.
Add a link to the extensions page to the Open Social menu, visible for CM+ roles.
We added a link to the Open Social menu that points to the page which describes all our optional extensions.
> Add an extra menu item to have Extensions added to the Open Social admin menu

- modules/social_features/social_group/modules/social_group_flexible_group/src/SocialGroupFlexibleGroupConfigOverride.php
To ensure that dependencies for configurations added in configuration overrides are merged properly, we're not allowed to use numerical indices. Drupal uses <code>NestedArray::mergeDeep</code> to merge these arrays and this function will override any numerical indices. To get around this we use string keys which are properly preserved and allow to add to these arrays in multiple different places. This works without issues for simple keys and values, such as module names.
A problem arises when the dependency that's added contains dots and this value is used as key without modification. For example when the dependency is for another configuration object. The <code>Drupal\Core\Config\Schema\ArrayElement</code> class contains logic …
> Issue #3189030: Dependencies added in config override may not contain dots

- .travis.yml
- composer.json
- modules/social_features/social_swiftmail/src/Plugin/Mail/SocialSwiftMailer.php
drupal/sendgrid_integration could not be installed with the old version of swiftmailer.
1. Removed the patch for the drupal/swiftmailer 1.0-beta2.
2. Updated to drupal/swiftmailer 2.0-beta1 and swiftmailer/swiftmailer:6.2.4
3. We also needed to ensure our SocialSwiftMailer is up to date with SwiftMailers massageMessageBody
4. And since PHP is not supported as a swiftmailer send option we need to use mailcatchers smtp
See https://www.drupal.org/project/swiftmailer/issues/3143292
```
$config['swiftmailer.transport']['transport'] = 'smtp';
$config['swiftmailer.transport']['smtp_host'] = 'mailcatcher';
$config['swiftmailer.transport']['smtp_port'] = '1025';
```
Should do the trick.
Or use the re-install script with the new `--localsettings` flag. This should ensure your settings are added on …
> Issue #3188183 by aangel: Update Swiftmailer

- modules/social_features/social_group/modules/social_group_secret/modules/social_secret_group_featured/config/install/core.entity_view_display.group.secret_group.featured.yml
- modules/social_features/social_group/modules/social_group_secret/modules/social_secret_group_featured/social_secret_group_featured.info.yml
- modules/social_features/social_landing_page/social_landing_page.install
When featuring a secret group on a landing page, the group image is not shown. This is due to the absence of a 'featured' view mode.
This solution provides the 'featured' view mode for secret groups.
- https://www.drupal.org/project/social/issues/3190319
- https://getopensocial.atlassian.net/browse/SUP-457
Fixed an issue when featuring secret groups on a landing page, the image would not show.
> #3190319 by jochemvn: add 'featured' view mode for secret groups

- modules/custom/social_font/social_font.routing.yml
*Describe the problem you're trying to solve, this should motivate why the changes you're proposing are needed.*
The route to the admin pages of Social Font (/admin/config/fonts) uses the general permission 'access administration pages' instead of the more granular 'administer font entities' permission.
*Describe the solution you've created, elaborate on any technical choices you've made. Why is this the right solution and is a different solution not the right one?*
Replace 'access administration pages' by 'administer font entities'
*Paste a link to the drupal.org issue queue item. If any other issue trackers were used, include links to those too.*
https://www.drupal.org/project/social/issues/3191095
*For example*
*If this Pull Request makes visual changes then please include some …
> correct permission

- modules/social_features/social_user/social_user.tokens.inc
- modules/social_features/social_user/src/Plugin/Action/SocialSendEmail.php
- modules/social_features/social_user/src/Plugin/QueueWorker/UserMailQueueProcessor.php
When using "Send email to group members" you are not abel to personalize the salutation.
You can't say:
"Hello [username],
please enjoy the new discussion here"
you can only have a common salutation:
"Hello all,
please enjoy the new discussion here"
Idea, spend social_user module a recepient token which enable group managers / admins to send emails with a personalized salutation.
https://www.drupal.org/project/social/issues/3119823
A group manager will now be able to send now emails to group members with a personalized salutation using the tokens in message body.
There is a new token declared in social_user module called [social_user:recipient] which will enabled user to add the display name of user in message body.
> add [social_user:recepient] token

- modules/social_features/social_profile/config/install/core.entity_form_display.profile.profile.default.yml
- modules/social_features/social_profile/config/update/social_profile_update_8803.yml
- modules/social_features/social_profile/social_profile.install
Right now the profile picture input field is rendered above the banner input field.
This usually means the banner field is pushed below the fold after users upload a banner and we noticed a lot of users actually don't upload one, while it has a huge visual impact.
Move the banner field above profile image field.
https://www.drupal.org/project/social/issues/3191206
We have adjusted the banner image to appear before profile image field when you edit your profile.
N.A
N.A
> Issue #3191206 by navneet0693: Updated weight of banner image field on profile.

- modules/social_features/social_core/social_core.module
- modules/social_features/social_landing_page/config/install/core.entity_form_display.node.landing_page.default.yml
- modules/social_features/social_landing_page/config/update/social_landing_page_update_8811.yml
- modules/social_features/social_landing_page/social_landing_page.install
- modules/social_features/social_landing_page/social_landing_page.module
Landing page was outside of the scope for the new content form style. We decided to use it as a great example of documentation on how you can change your content types to match the new content form style.
Since we will have more content types who still render the vertical tabs as settings.
```
if (theme_get_setting('content_entity_form_style') === 'open_social')
```
1. Add a new fieldset called 'group_settings', it needs to have this machine name, and make sure it has the class `social-collapsible-fieldset` this will ensure it themes and renders it nicely and pretty.
2. It should be collapsible and of type details.
3. Move Authored by, Authored on, URL alias and Publish Status to new fieldset
4. Let update helper create the necessary configuration updates
5. Invoke …
> Issue #3186003 by navneet0693: DS-7506 Added new 'group_settings' fieldset to landing page content type.

- modules/social_features/social_core/social_core.module
- tests/behat/features/capabilities/landing-page/landing-page-as-404.feature
- tests/behat/features/capabilities/landing-page/landing-page-create.feature
- tests/behat/features/capabilities/page/page-create.feature
The submit button on our nodes used the machine name from the Node type. For most this was OK, but for landing pages it resulted in Create landing_page. 
Use the node type label instead, lowercase this so we dont have unnecessary capitals in there. 
Bugfix - Part of https://drupal.org/node/3186003
> Issue #3186003 - Update form submit label to use Create -> node type label
