goalgorilla/open_social

- .travis.yml
This will enable travis in the install profile.
> Enable travis in the install profile

- modules/social_features/social_core/config/install/user.role.anonymous.yml
- modules/social_features/social_core/config/install/user.role.authenticated.yml
- modules/social_features/social_search/config/install/views.view.search_groups.yml
- modules/social_features/social_search/config/install/views.view.search_users.yml
- modules/social_features/social_search/social_search.permissions.yml
> DS-1703 AN should have permission to see content search results

- modules/social_features/social_book/config/install/block.block.booknavigation.yml
- modules/social_features/social_book/config/install/core.entity_form_display.node.book.default.yml
- modules/social_features/social_book/config/install/core.entity_view_display.node.book.default.yml
- modules/social_features/social_book/config/install/core.entity_view_display.node.book.teaser.yml
- modules/social_features/social_book/config/install/field.field.node.book.field_book_image.yml
- modules/social_features/social_book/config/install/field.storage.node.field_book_image.yml
- modules/social_features/social_core/social_core.module
- modules/social_features/social_core/src/Plugin/Block/SocialPageTitleBlock.php
- themes/socialbase/templates/book/node--book--teaser.html.twig
**Reinstall the module (drush dre social_book --yes) and check the following:**
> DS-1900 Add image to book

- themes/socialbase/components/asset-builds/css/ajax.css
- themes/socialbase/components/asset-builds/css/alerts.css
- themes/socialbase/components/asset-builds/css/buttons.css
- themes/socialbase/components/asset-builds/css/cards.css
- themes/socialbase/components/asset-builds/css/ckeditor.css
- themes/socialbase/components/asset-builds/css/datepicker.css
- themes/socialbase/components/asset-builds/css/jumbotron.css
- themes/socialbase/components/asset-builds/css/materialize.css
- themes/socialbase/components/asset-builds/css/modals.css
- themes/socialbase/components/asset-builds/css/styleguide.css
- themes/socialbase/components/asset-builds/css/toc.css
- themes/socialbase/components/asset-builds/css/type.css
- themes/socialbase/components/asset-builds/css/waves.css
- themes/socialbase/components/components/cards/cards.scss
- themes/socialbase/components/components/type/type.scss
- themes/socialbase/components/init/_variables.scss
- themes/socialbase/components/materialize/_hero.scss
- themes/socialbase/components/materialize/_list-group.scss
- themes/socialbase/components/materialize/_navbar.scss
- themes/socialbase/components/theme/_styles.scss
- themes/socialbase/templates/block/block--system-menu-block--main.html.twig
- themes/socialbase/templates/navigation/menu--main.html.twig
Replace fixed values with variables and provide theming options for extra menu
> DS-1879 - subtheme fixes

- composer.json
Issue drupal.org/node/2466197 has been resolved and it's tagged with stable release 8.1.8
> Remove patch for 2466197

- modules/social_features/social_core/social_core.install
- modules/social_features/social_event/social_event.install
- modules/social_features/social_group/config/install/group.role.open_group-83776d798.yml
- modules/social_features/social_group/config/install/group.role.open_group-ba5854c29.yml
- modules/social_features/social_group/social_group.info.yml
- modules/social_features/social_page/social_page.install
- modules/social_features/social_post/social_post.install
- modules/social_features/social_profile/social_profile.install
- modules/social_features/social_topic/social_topic.install
- modules/social_features/social_user/social_user.install
> DS-1202 - CM Role and feature cleanup (user roles)

- modules/social_features/social_core/social_core.install
> DS-1356 by jochemvn: Add permission to administer blocks for SM

- modules/custom/social_devel/config/install/devel.settings.yml
- themes/socialbase/templates/book/node--book--teaser.html.twig
> DS-1766 - teaser changes

- modules/social_features/social_book/config/install/core.base_field_override.node.book.promote.yml
- modules/social_features/social_book/config/install/core.entity_view_display.node.book.search_index.yml
- modules/social_features/social_book/config/install/node.type.book.yml
- modules/social_features/social_book/social_book.features.yml
- modules/social_features/social_book/social_book.info.yml
- modules/social_features/social_book/social_book.services.yml
- modules/social_features/social_book/src/SocialBookConfigOverride.php
- modules/social_features/social_core/social_core.module
- modules/social_features/social_core/src/Plugin/Block/SocialPageTitleBlock.php
- modules/social_features/social_core/templates/page-hero-data.html.twig
- modules/social_features/social_search/config/install/search_api.index.social_content.yml
- themes/socialbase/components/asset-builds/css/navbar.css
- themes/socialbase/components/components/navbar/navbar.scss
- themes/socialbase/components/init/_variables.scss
- themes/socialbase/socialbase.theme
- themes/socialbase/templates/book/node--book--teaser.html.twig
- themes/socialbase/templates/event/node--event--teaser.html.twig
- themes/socialbase/templates/field/field.html.twig
- themes/socialbase/templates/node/node--teaser.html.twig
- themes/socialbase/templates/node/node--teaser__body.html.twig
- themes/socialbase/templates/node/node--teaser__field.html.twig
- themes/socialbase/templates/node/node--teaser__type.html.twig
- themes/socialbase/templates/page/node--page--teaser.html.twig
- themes/socialbase/templates/topic/node--topic--teaser.html.twig
> DS-1939 by maikelkoopman: display date field in teaser, make teaser files more dry, display date field in node book hero

- themes/socialbase/socialbase.theme
to only make it match the modal window, not all strings
> change in_array function 

- modules/social_features/social_book/social_book.install
> DS-2021 - CM / SM need to be able to add book pages

- themes/socialbase/components/asset-builds/css/datepicker.css
- themes/socialbase/components/asset-builds/css/forms.css
- themes/socialbase/components/asset-builds/css/hero.css
- themes/socialbase/components/asset-builds/css/navbar.css
- themes/socialbase/components/components/datepicker/datepicker.scss
- themes/socialbase/components/components/forms/forms.scss
- themes/socialbase/components/components/hero/hero.scss
- themes/socialbase/components/components/navbar/navbar.scss
- themes/socialbase/components/init/_variables.scss
> DS-2030 by maikelkoopman: set correct line height for date fields in iOS

- modules/social_features/social_event/config/install/views.view.events.yml
HTT:
- Login as user A
- Create an event, signup for this event
- Login as another user
- Signup for this event
- Visit the profile of user A and check the block on the right and the Events tab on the profile. The event should not be there multiple times.
> DS-2069 by jaapjan: events are being duplicated on user/x/events

- modules/custom/activity_basics/src/Plugin/ActivityContext/ProfileActivityContext.php
- modules/custom/activity_logger/activity_logger.tokens.inc
- modules/social_features/social_activity/config/install/field.field.message.create_comment_post_profile.field_message_context.yml
- modules/social_features/social_activity/config/install/field.field.message.create_comment_post_profile.field_message_destination.yml
- modules/social_features/social_activity/config/install/field.field.message.create_comment_post_profile.field_message_related_object.yml
- modules/social_features/social_activity/config/install/message.template.create_comment_post_profile.yml
- Added message template 'Create comment on post on my profile'
> DS-1038 by ribel: When a LU comments on a post posted on my stream, I want to be notified via e-mail

- modules/custom/activity_basics/src/Plugin/ActivityContext/OwnerActivityContext.php
- modules/custom/activity_creator/activity_creator.module
- modules/custom/activity_creator/src/ActivityFactory.php
- modules/social_features/social_activity/config/install/field.field.message.create_comment_reply.field_message_context.yml
- modules/social_features/social_activity/config/install/field.field.message.create_comment_reply.field_message_destination.yml
- modules/social_features/social_activity/config/install/field.field.message.create_comment_reply.field_message_related_object.yml
- modules/social_features/social_activity/config/install/message.template.create_comment_reply.yml
- Added message template 'Create reply on my comment'
> DS-1042 by ribel: When a LU replies on my comments, I want to be notified via e-mail

- composer.json
- drupal-org-core.make
Let's see what our tests think of this :)
> DS-1677 - core security update

- composer.json
- drupal-org-core.make
- drupal-org.make
HTT.
Make sure it works, mostly activity stream / notifications are affected
> DS-1677 by ronaldtebrake: updated token from beta1 to beta2

- modules/social_features/social_topic/social_topic.api.php
- modules/social_features/social_topic/src/Controller/SocialTopicController.php
This code is useful for enterprise projects.
HTT:
1. Implement the hook e.g. in social_core of the Social Topics API.
2. Check that the titles are altered on the newest topics view.
3. Check code
> DS-2089 by nielsvandermolen: Create a hook to alter the topic type view title

- modules/social_features/social_post/social_post.links.menu.yml
See https://www.drupal.org/node/2764587#comment-11660471
> DS-2135 by ronaldtebrake: missed removing a link for the entity post

- themes/socialbase/components/asset-builds/css/forms.css
- themes/socialbase/components/asset-builds/css/grid.css
- themes/socialbase/components/asset-builds/css/media.css
- themes/socialbase/components/asset-builds/css/scaffolding.css
- themes/socialbase/components/components/forms/_autocomplete.scss
- themes/socialbase/components/components/forms/forms.scss
Test via expertise, interests of member search
- add some terms in your profile
- enter them in the search
- check the autocomplete works like expected
> Theme jquery.ui autocomplete

- modules/social_features/social_profile/config/install/social_profile.settings.yml
- modules/social_features/social_profile/social_profile.features.yml
- modules/social_features/social_profile/social_profile.install
> DS-2082 by ribel: Remove social profile config from features. Add setting default config to installation hook

- modules/social_features/social_activity/config/install/block.block.views_block__activity_stream_block_stream_homepage.yml
- modules/social_features/social_activity/config/install/views.view.activity_stream.yml
- modules/social_features/social_core/social_core.routing.yml
- modules/social_features/social_core/src/Controller/SocialCoreController.php
- themes/socialbase/socialbase.theme
- themes/socialbase/templates/block/block--views-block--activity-stream-block-stream-homepage.html.twig
HTT:
> admin/structure/views/view/activity_stream/edit/block_stream_homepage
> admin/structure/block
> DS-2207 change homestream view page to a view block to get more flexibility

- themes/socialbase/socialbase.theme
- Fixed syntax of altering imageWidgetCrop.js
- Changed the weight of vertical-tabs.js
> DS-2151 by alex.ksis: Fix altering of imageWidgetCrop.js

- themes/socialbase/components/components/navbar/navbar.scss
- themes/socialbase/components/components/tabs/tabs.scss
- themes/socialbase/socialbase.theme
- themes/socialbase/templates/group/group--hero.html.twig
- themes/socialbase/templates/system/html.html.twig
set path-classes on body,
remove shadow in dropdown of navbar on mobile,
make group join button display conditional,
give avatar a border
> Basetheme updates for custom theme

- themes/socialbase/socialbase.theme
- Added check that imageWidgetCrop.js is attached.
> DS-2168 by alex.ksis: Fix notices

- modules/custom/social_demo/content/entity/comment.yml
- modules/custom/social_demo/content/entity/event.yml
- modules/custom/social_demo/content/entity/group.yml
- modules/custom/social_demo/content/entity/topic.yml
- modules/custom/social_demo/content/entity/user.yml
> Integrity fix for demo content (eg: no more public content in groups)

- modules/social_features/social_user/src/Plugin/Block/AccountHeaderBlock.php
- themes/socialbase/socialbase.theme
> DS-2176 by alex.ksis: Fix wrong links

- themes/socialbase/components/asset-builds/css/dropdowns.css
- themes/socialbase/components/asset-builds/css/list-group.css
- themes/socialbase/components/asset-builds/css/navbar.css
- themes/socialbase/components/asset-builds/css/off-canvas.css
- themes/socialbase/components/components/list-group/list-group.scss
- themes/socialbase/components/components/navbar/navbar.scss
- themes/socialbase/components/components/off-canvas/off-canvas.scss
- themes/socialbase/components/init/_variables.scss
- themes/socialbase/templates/block/block--account-header-block.html.twig
- themes/socialbase/templates/block/block--local-tasks-block.html.twig
- themes/socialbase/templates/block/block--social-search.html.twig
- themes/socialbase/templates/block/block--views-block--activity-stream-block-stream-homepage.html.twig
- themes/socialbase/templates/block/block--views-block--event-enrollments-event-enrollments.html.twig
- themes/socialbase/templates/block/block--views-block--sidebar.html.twig
- themes/socialbase/templates/block/block--views-exposed-filter-block.html.twig
- themes/socialbase/templates/block/block.html.twig
- themes/socialbase/templates/views/views-view--bare.html.twig
- themes/socialbase/templates/views/views-view--event-enrollments--page.html.twig
- themes/socialbase/templates/views/views-view--list-group.html.twig
- themes/socialbase/templates/views/views-view--stream.html.twig
- themes/socialbase/templates/views/views-view.html.twig
> DS-2272: As a CM I want to be able to create a large menu in the navbar.

- modules/social_features/social_search/social_search.module
- modules/social_features/social_search/src/Plugin/Block/SearchContentBlock.php
> DS-2268 by ribel: Fix caching of search exposed filter blocks

- modules/custom/activity_logger/src/Service/ActivityLoggerFactory.php
Added some logic to automatically create new field instances if they do not exists for the message. Solves an old bug we used to have that makes it difficult to create new message types.
Htt:
> by nielsvandermolen: Activity logger improvements

- composer.json
- drupal-org-core.make
INFO:
See https://www.drupal.org/node/2744069
HTT.
> DS-2157 by ronaldtebrake: update core with patch so IN queries work

- tests/behat/features/capabilities/group/group-create-open.feature
- tests/behat/features/capabilities/page/page-create.feature
- tests/behat/features/capabilities/profile/hide-profile-email.feature
Pushes are working, so let's test the PR build on Travis.
> Add false negatives as @stability again

- modules/social_features/social_event/src/Plugin/Block/EventAddBlock.php
- modules/social_features/social_group/src/Plugin/Block/GroupAddBlock.php
- modules/social_features/social_group/src/Plugin/Block/GroupAddEventBlock.php
- modules/social_features/social_group/src/Plugin/Block/GroupAddTopicBlock.php
- modules/social_features/social_topic/src/Plugin/Block/TopicAddBlock.php
- tests/behat/config/behat.yml
- themes/socialbase/components/asset-builds/css/dropdowns.css
- themes/socialbase/components/asset-builds/css/file.css
- themes/socialbase/components/asset-builds/css/grid.css
- themes/socialbase/components/asset-builds/css/hero.css
- themes/socialbase/components/asset-builds/css/layout.css
- themes/socialbase/components/asset-builds/css/modals.css
- themes/socialbase/components/asset-builds/css/navbar.css
- themes/socialbase/components/asset-builds/css/off-canvas.css
- themes/socialbase/components/asset-builds/css/utilities.css
- themes/socialbase/components/components/file/file.scss
- themes/socialbase/components/components/off-canvas/off-canvas.scss
- themes/socialbase/components/init/_variables.scss
- themes/socialbase/components/layout/layout.scss
- themes/socialbase/js/custom/responsive-dom/responsive-dom-init.js
- themes/socialbase/templates/block/block--views-exposed-filter-block.html.twig
- themes/socialbase/templates/layout/page.html.twig
- themes/socialbase/templates/node/node--teaser.html.twig
- themes/socialbase/templates/profile/profile--profile--teaser.html.twig
- change layout breakpoint from 768 to 960 wide (sidebar)
- insert coment no. in teaser (all CT)
- updates affected modules and components
> 2406: update layout breakpoint and comments no. in teaser

- modules/custom/activity_creator/src/ActivityFactory.php
- modules/social_features/social_activity/config/install/message.template.create_comment_community_node.yml
- modules/social_features/social_activity/config/install/message.template.create_comment_community_post.yml
- modules/social_features/social_activity/config/install/message.template.create_comment_group_node.yml
- modules/social_features/social_activity/config/install/message.template.create_comment_group_post.yml
- modules/social_features/social_activity/config/install/message.template.create_event_group.yml
- modules/social_features/social_activity/config/install/message.template.create_post_group.yml
- modules/social_features/social_activity/config/install/message.template.create_topic_group.yml
- tests/behat/features/capabilities/activity-stream/activity-stream-comments.feature
- New Topic and Event in Group
- New Post in Community
- New Post in Group
- Comment on Group Post or Content
- Comment on Community Post or Content
> DS-1895 by ribel: Extend Explore Stream

- modules/social_features/social_core/social_core.install
HTT:
- run updates/reinstall
- new image quality should be at 90% instead of 75%
> DS-2397 by vlad-nosykov: Increase image quality

- themes/socialbase/templates/node/book/node--book--teaser.html.twig
- themes/socialbase/templates/node/field--node--body.html.twig
> DS-2455: remove body field from book teaser

- modules/social_features/social_search/config/install/search_api.index.social_users.yml
> DS-2377 by ribel: Add username to users search index

- themes/socialbase/templates/node/event/node--event--full.html.twig
**HTT**
1. Clear caches
2. Add event address value to field when editing node
3. View node full display
4. See if address is above the line and not repeated under the line
> BS-2591 - Moved location address to above the line.

- modules/custom/social_demo/social_demo.drush.inc
- modules/custom/social_demo/social_demo.module
See: https://www.drupal.org/node/2834600
> Issue #2834600 - Touch-ups demo module

- modules/custom/template_suggestions_extra/template_suggestions_extra.module
https://www.drupal.org/node/2834602
> Issue #2834602: Code symplification for template suggestions

- modules/social_features/social_event/modules/social_event_type/social_event_type.module
- themes/socialbase/templates/node/event/node--event--full.html.twig
- themes/socialbase/templates/node/event/node--event--teaser.html.twig
- themes/socialbase/templates/node/node--full.html.twig
When reviewing take a look at the @todo in the preprocess. This still needs some attention.
> DS-2426 - Theming or event type teaser and full node.

- drupal-org-core.make
> DS-2758 - Add new drupal version to forgotten make file

- tests/behat/features/capabilities/account/login.feature
> Improve the login with email account Behat test

- modules/custom/entity_access_by_field/entity_access_by_field.install
- modules/custom/group_core_comments/group_core_comments.install
- modules/custom/social_font/social_font.install
- modules/social_features/social_book/social_book.install
- modules/social_features/social_comment/social_comment.install
- modules/social_features/social_core/social_core.install
- modules/social_features/social_event/social_event.install
- modules/social_features/social_follow_content/social_follow_content.install
- modules/social_features/social_group/social_group.install
- modules/social_features/social_mentions/social_mentions.install
- modules/social_features/social_page/social_page.install
- modules/social_features/social_post/social_post.install
- modules/social_features/social_profile/social_profile.install
- modules/social_features/social_search/social_search.install
- modules/social_features/social_topic/social_topic.install
- modules/social_features/social_tour/social_tour.install
- modules/social_features/social_user/social_user.install
https://www.drupal.org/node/2847087
> by nielsvandermolen: Fix update hook for custom roles

- drupal-org.make
Somebody forgot about this booobooo
> Beta-10 image-widget-crop patch update

- modules/social_features/social_like/social_like.install
- tests/behat/features/capabilities/like/like-create-event.feature
- tests/behat/features/capabilities/like/like-create-topic.feature
Both are marked as stability, so if the branch builds, you can merge. 
Also added some permissions that enable LUs to like events. The test will prove that it works.
> DS-2853 - 2 behat tests for like

- modules/social_features/social_like/config/install/message.template.create_like_node_or_post.yml
- modules/social_features/social_like/social_like.tokens.inc
- tests/behat/features/capabilities/like/like-create-event.feature
- tests/behat/features/capabilities/like/like-create-topic.feature
- tests/behat/features/capabilities/like/like-post-stream.feature
> DS-3116 - More descriptive notification when someone liked my content

- modules/social_features/social_post/config/install/core.entity_view_display.post.post.activity.yml
- modules/social_features/social_post/config/install/core.entity_view_display.post.post.default.yml
- modules/social_features/social_post/src/Plugin/Field/FieldFormatter/CommentPostFormatter.php
See: https://www.drupal.org/node/2767295
> #2767295 Order of comments in posts

- modules/social_features/social_like/social_like.install
- themes/socialbase/includes/node.inc
- themes/socialbase/templates/node/node--full.html.twig
Remove the old like widget in favor of the top content detail page
> DS-3212 - Duplicate like widget for AN

- modules/custom/activity_creator/src/ActivityFactory.php
Related Issue: https://www.drupal.org/node/2858427
> Issue #2858427 by ribel: Fix duplicated activities in activity stream

- modules/custom/download_count/download_count.module
- modules/custom/download_count/src/Plugin/Field/FieldFormatter/FieldDownloadCount.php
- themes/socialbase/assets/css/file.css
- themes/socialbase/components/03-molecules/file/file.scss
- themes/socialbase/templates/file/download-count-file-field-formatter.html.twig
Related Issue: https://www.drupal.org/node/2863389
> Issue #2863389 by ribel: Fix styles for attachments with enabled download counter

- modules/social_features/social_event/modules/social_event_type/config/install/social_event_type.settings.yml
- modules/social_features/social_event/modules/social_event_type/social_event_type.features.yml
- modules/social_features/social_event/modules/social_event_type/social_event_type.install
See: https://www.drupal.org/node/2862101
> Issue #2862101 by ribel: Fix event type settings

- modules/social_features/social_sharing/social_sharing.module
Related Issue: https://www.drupal.org/node/2842653
> Issue #2842653 by ribel, alex.ksis: Exclude Social Sharing block from Add and Edit node pages

- modules/custom/activity_basics/src/Plugin/ActivityDestination/NotificationsActivityDestination.php
- modules/custom/activity_basics/src/Plugin/ActivityDestination/StreamExploreActivityDestination.php
- modules/custom/activity_basics/src/Plugin/ActivityDestination/StreamGroupActivityDestination.php
- modules/custom/activity_basics/src/Plugin/ActivityDestination/StreamHomeActivityDestination.php
- modules/custom/activity_basics/src/Plugin/ActivityDestination/StreamProfileActivityDestination.php
- modules/custom/activity_creator/activity_creator.services.yml
- modules/custom/activity_creator/src/ActivityFactory.php
- modules/custom/activity_creator/src/Annotation/ActivityDestination.php
- modules/custom/activity_creator/src/Plugin/ActivityDestinationManager.php
- modules/custom/activity_send/modules/activity_send_email/src/Plugin/ActivityDestination/EmailActivityDestination.php
Related Issue: https://www.drupal.org/node/2864345
> Issue #2864345 by ribel: Improve activity aggregation by moving logic to the activity destination plugins

- themes/socialblue/assets/css/waves.css
- themes/socialblue/components/02-atoms/waves/waves.scss
1. Open safari browser
2. Go to /user/login
3. Click the default action and see that the waves effect is triggered within the button.
> #2861184 by peterpolman: Added relative position to waves effect.

- themes/socialbase/includes/form.inc
How to test:
- create a new account
- go to mailcatcher and click on the link
- the description is now in a card and the button has a primary color and is aligned right.
> #2866935 by maikelkoopman: theme user reset form

- themes/socialbase/assets/css/like.css
- themes/socialbase/components/03-molecules/like/like.scss
As per: https://www.drupal.org/node/2866531
> Issue #2866531 by peterpolman: Solid Like icon looks better

- modules/social_features/social_topic/config/install/views.view.topics.yml
Related Issue: https://www.drupal.org/node/2866397
> Issue #2866397 by ribel: Fix topics duplicates on my topics overview

- modules/social_features/social_event/src/Form/EnrollActionForm.php
- tests/behat/features/capabilities/group/group-create-open.feature
Related issue: https://www.drupal.org/node/2868288
> #2868288 Behat tests are failing

- modules/social_features/social_post/src/PostHtmlRouteProvider.php
1. Login as a LU / Admin
2. See that when you go to /post/add you don't get an error anymore.
> 2866028 by ronaldtebrake: render title after getting translated markup

- composer.json
- drupal-org-core.make
- modules/social_features/social_user/config/install/core.entity_view_display.user.user.default.yml
- modules/social_features/social_user/config/install/core.entity_view_display.user.user.full.yml
- modules/social_features/social_user/social_user.install
- social.info.yml
Tested the following two scenario's:
1. Fresh install (also done by the tests below)
2. Install on master and then:
- switch to this branch (in composer)
- composer update
- ds cc drush
- ds updb --yes
- ds cc drush
- ds fra --yes
This last method seems to be the most interesting case and I can recommend trying that over a fresh install. Both is better obviously
> DS-3427 - Update core

- composer.json
> DS-3427 by jochemvn: Update core to 8.3.2

- modules/social_features/social_core/social_core.module
- modules/social_features/social_profile/config/install/views.view.newest_users.yml
> #2866041 - Fix error call on empty object

- themes/socialbase/assets/css/stream.css
- themes/socialbase/components/04-organisms/stream/stream.scss
- [] Go the the homepage as LU in IE11+
- [] Click the visibility button and see if it appears above all cards
- [] When clicking another visibility setting the button should be updated
> Issue #2875187 by peterpolman: Fixed z-index of first stream-item.

- modules/social_features/social_tour/social_tour.install
- modules/social_features/social_tour/social_tour.links.menu.yml
- modules/social_features/social_tour/social_tour.module
- modules/social_features/social_tour/social_tour.permissions.yml
- modules/social_features/social_tour/social_tour.routing.yml
- modules/social_features/social_tour/src/Form/SocialTourSettings.php
> DS-2726 by jochemvn: Add social_tour settings form; Create function to check for access

- social.profile
See: https://www.drupal.org/node/2882966
HTT:
> #2882966: remove (soon to be) obsolete Address requirements checks

- themes/socialbase/assets/css/ajax.css
- themes/socialbase/assets/css/base.css
- themes/socialbase/assets/css/button.css
- themes/socialbase/assets/css/cards.css
- themes/socialbase/assets/css/ckeditor.css
- themes/socialbase/assets/css/form-controls.css
- themes/socialbase/assets/css/hero.css
- themes/socialbase/assets/css/input-groups.css
- themes/socialbase/assets/css/like.css
- themes/socialbase/assets/css/modal.css
- themes/socialbase/assets/css/nav-tabs.css
- themes/socialbase/assets/css/navbar.css
- themes/socialbase/assets/css/offcanvas.css
- themes/socialbase/assets/css/password.css
- themes/socialbase/assets/css/teaser.css
- themes/socialbase/assets/css/tour.css
- themes/socialbase/components/04-organisms/hero/hero.scss
Original issue: https://www.drupal.org/node/2877727
Used Flexbox layout for cover-wrap container, aligned hero-footer using flexbox properties instead of relative/absolute positioning.
> Issue #2877727 by Andrew147: Fix hero breaking with long title

- modules/social_features/social_post/src/PostHtmlRouteProvider.php
Original PR: #402
Original issue: https://www.drupal.org/node/2884397
> Issue #22884397 by t0r: Change route collection requirement

- modules/social_features/social_post/src/PostHtmlRouteProvider.php
Change route collection requirement
Related issue: https://www.drupal.org/node/2884397
> Change route collection requirement

- modules/social_features/social_post/src/PostViewBuilder.php
Original PR: #403
Original Issue: https://www.drupal.org/node/2884305
> Issue #2884305 by t0r, ribel: Add destination to post edit link

- modules/social_features/social_post/src/PostViewBuilder.php
Added link query destination to link 'edit-form'.
Related issue: https://www.drupal.org/node/2884305
> Add destination to post edit link

- composer.json
> DS-3748 by jochemvn: Update drupal core to 8.3.3

- .travis.yml
- composer.json
- drupal-org-core.make
- modules/social_features/social_core/social_core.install
- social.info.yml
Lets push for a rc8 release with the latest Drupal Core a.s.a.p.
Lets also include pull [437](https://github.com/goalgorilla/open_social/pull/437) ?
> Update Drupal Core from 8.3.3 to 8.3.4

- social.profile
- tests/behat/features/capabilities/tour/tour.feature
> Don't turn on the tour module by default

- themes/socialbase/templates/file/download-count-file-field-formatter.html.twig
How to test:
- enable social_download_count module
- Add file to a node
- Check theme of display of this attachment is correct and download counter is shown
> #2890630: change classes for files when download count is enabled

- modules/social_features/social_post/modules/social_post_photo/config/install/core.entity_view_display.post.photo.activity.yml
- modules/social_features/social_post/modules/social_post_photo/config/install/core.entity_view_display.post.photo.activity_comment.yml
- modules/social_features/social_post/modules/social_post_photo/config/install/core.entity_view_display.post.photo.default.yml
- modules/social_features/social_post/modules/social_post_photo/social_post_photo.features.yml
- modules/social_features/social_post/modules/social_post_photo/social_post_photo.info.yml
> DS-3920 by jochemvn: Make social_post_photo a feature

- modules/social_features/social_sso/social_sso.install
**Related issue**: https://www.drupal.org/node/2893819
**HTT**
> Issue #2893819 by ribel: Fix setting permissions in social_sso module

- composer.json
- drupal-org-core.make
> DS-3921 by jochemvn: Update core to 8.3.5

- modules/custom/activity_creator/src/Plugin/ActivityContextBase.php
- modules/custom/activity_creator/src/Plugin/QueueWorker/ActivityWorkerLogger.php
- modules/custom/mentions/src/MentionsViewsData.php
- modules/custom/mentions/src/Plugin/Mentions/Entity.php
- modules/custom/social_auth_extra/social_auth_extra.api.php
- modules/custom/social_auth_facebook/src/Controller/FacebookAuthController.php
- modules/custom/social_auth_google/src/Controller/GoogleAuthController.php
- modules/custom/social_auth_linkedin/src/Controller/LinkedInAuthController.php
- modules/custom/social_auth_twitter/src/Controller/TwitterAuthController.php
- modules/social_features/social_comment_upload/social_comment_upload.module
- modules/social_features/social_core/social_core.install
- modules/social_features/social_core/src/Controller/EntityAutocompleteController.php
- modules/social_features/social_core/src/Entity/Element/EntityAutocomplete.php
- modules/social_features/social_core/src/Entity/EntityAutocompleteMatcher.php
- modules/social_features/social_core/src/Plugin/Block/SocialPageTitleBlock.php
- modules/social_features/social_core/src/Routing/RouteSubscriber.php
- modules/social_features/social_core/src/SocialCoreServiceProvider.php
- modules/social_features/social_mentions/src/Plugin/ActivityContext/MentionActivityContext.php
- modules/social_features/social_post/src/Form/PostForm.php
- modules/social_features/social_user/src/ContextProvider/UserRouteContext.php
- modules/social_features/social_user_export/src/Plugin/Action/ExportUser.php
These coding standards will be a process as we are progressing towards a stable release on drupal.org and these coding standards still need to set up a check upon our PR's. So, since this is a little hard to test, I'd suggest you click around the platform and test out the stuff that has been affected with these code changes.
> DS-4013 - fix coding standard issues

- modules/social_features/social_post/social_post.module
https://www.drupal.org/node/2901337
> Issue #2901337 Add context for post button translation

- composer.json
Try an update and reinstall
Check the [release notes](https://www.drupal.org/project/views_infinite_scroll/releases/8.x-1.5)
See that everything still works
> DS-4101-maintenance by frankgraave: update views_infinite_scroll to 1.5

- tests/behat/features/capabilities/group/group-create-open.feature
**Changes:**
Replaced **a** with **an** in behat test, to be consistent with code.
**HTT:**
> ECI-2 by ribel: Fix article in Open group behat test

- themes/socialbase/includes/form.inc
So save button aligns to the right
> Add "add" profile form to default forms

- themes/socialbase/assets/css/autocomplete.css
- themes/socialbase/components/03-molecules/form-elements/autocomplete/autocomplete.scss
- Missing background color on jquery ui autocomplete. Typo in scss
> Restore background color of autocomplete list

- modules/social_features/social_post/social_post.module
- themes/socialbase/templates/block/block--social-post.html.twig
- themes/socialbase/templates/post/form--post-create.html.twig
To make the post form a bit nice we want to show a small avatar of the current user next to the message input area.
> DS-4882 - Show profile picture in all post forms

- modules/custom/social_demo/src/DemoUser.php
Issue: https://www.drupal.org/node/2909958
How to test:
```
drush pm-enable social_demo -y
drush sda create_test_user
```
> Issue #2909958 by chmez: add checking if a user account has profile.

- themes/socialbase/assets/css/base.css
- themes/socialbase/assets/css/ckeditor.css
- themes/socialbase/assets/css/stream.css
- themes/socialbase/components/01-base/utilities/_utilities.scss
- themes/socialbase/components/04-organisms/stream/stream.scss
- themes/socialbase/templates/post/post--activity.html.twig
- themes/socialbase/templates/post/post.html.twig
https://www.drupal.org/node/2908197
> Issue #2908197 by maikelkoopman: apply elevated img style on post detail

- composer.json
- src/Composer/AssetPackagist.php
In order to help users to update their root composer.json to the same as https://github.com/goalgorilla/drupal_social/pull/320, we added a script.
> DS-4122 - composer script for updating root composer.json

- modules/social_features/social_post/src/PostListBuilder.php
Issue: https://www.drupal.org/node/2889889
HTT:
> Issue #2889889 - More information in the admin post list

- modules/social_features/social_group/social_group.module
Pull request for the supplied patch in https://www.drupal.org/node/2904866.
> Issue #2904866: Broken group members page because of missed check

- modules/custom/improved_theme_settings/improved_theme_settings.module
- modules/custom/social_demo/src/DemoContent.php
- modules/custom/social_demo/src/DemoContentInterface.php
- modules/custom/social_demo/src/DemoContentParserInterface.php
- modules/custom/social_demo/src/DemoNode.php
- modules/custom/social_demo/src/DemoSystem.php
- modules/custom/social_demo/src/DemoUser.php
- modules/custom/social_demo/src/Plugin/DemoContent/Book.php
- modules/custom/social_demo/src/Plugin/DemoContent/Event.php
- modules/custom/social_demo/src/Plugin/DemoContent/Post.php
- modules/custom/social_demo/src/Plugin/DemoContent/Topic.php
There are still 36 warnings open, but with this PR all coding standard **errors** should now be fixed! Now shooting in this PR to keep the coding standard changes smaller per PR.
> DS-4228 - Fix more coding standards

- tests/behat/features/capabilities/event/event-overview.feature
- tests/behat/features/capabilities/topic/topic-overview.feature
Two tests were failing in SaaS. This was because some permissions are a bit different in SaaS. I changed the tests, but from a functional point of view nothing should have been changed.
> DS-3912 by jochemvn: Make sure behats don't use user 1

- themes/socialbase/assets/css/base.css
- themes/socialbase/assets/css/ckeditor.css
- themes/socialbase/components/01-base/embedded/_embedded.scss
Add support for responsive embed. These classes won't do anything by itself, but can be used by SM and CM to create a responsive embed in content
> Support for responsive embed

- modules/social_features/social_core/config/install/field.field.block_content.hero_call_to_action_block.field_hero_image.yml
- modules/social_features/social_event/config/install/field.field.node.event.field_event_image.yml
- modules/social_features/social_group/config/install/field.field.group.closed_group.field_group_image.yml
- modules/social_features/social_group/config/install/field.field.group.open_group.field_group_image.yml
- modules/social_features/social_page/config/install/field.field.node.page.field_page_image.yml
- modules/social_features/social_topic/config/install/field.field.node.topic.field_topic_image.yml
How to test:
- upload png images to event, topic, hero block, group or page
> #2900381 by pgrond: added png to all the file fields

- modules/custom/social_demo/eaa/content/entity/system.yml
- modules/custom/social_demo/eaa/content/entity/topic.yml
- modules/custom/social_demo/src/DemoSystem.php
Site https://demo.getopensocial.com/ didn't show correct demo content anymore
As of drupal 8.4 the Yml parser crashes when a colon is in the title field.
https://jira.goalgorilla.com/browse/DS-4479
> DS-4479 by jochemvn: Fix EAA demo content

- tests/behat/features/capabilities/private-message/create-private-message.feature
We did not have any behat test for the private message feature.
Created a new behat that tests a single message and a thread with multiple users. Also checking on multiple threads in the inbox and the .unread-thread class.
- DS-4372
> DS-4372 - Add behat test for private message

- modules/social_features/social_tagging/config/install/taxonomy.vocabulary.social_tagging.yml
- modules/social_features/social_tagging/social_tagging.install
- modules/social_features/social_tagging/social_tagging.links.menu.yml
- modules/social_features/social_tagging/social_tagging.module
- modules/social_features/social_tagging/social_tagging.routing.yml
- modules/social_features/social_tagging/social_tagging.services.yml
- modules/social_features/social_tagging/src/Form/SocialTaggingSettingsForm.php
- modules/social_features/social_tagging/src/SocialTaggingService.php
Feature request, not solving a bug here. See issue tracker for more information.
- https://jira.goalgorilla.com/browse/DS-4352
> DS-4352 - As LU/SM I want to be able to tag content

- tests/behat/features/capabilities/administration/view-block-users.feature
One of behat tests is incorrect, so it is failing.
Fix it
- https://www.drupal.org/project/social/issues/2932657
> Issue #2932657 by alex.ksis: Fix behat test

- modules/social_features/social_core/social_core.install
"Argument 2 passed to t() must be of the type array, string given"
fix typo
> fix typo in drupal_set_message

- .github/PULL_REQUEST_TEMPLATE.md
We sometimes forget to add items to release notes and so on
Add a couple of extra DOD steps
- `<none>`
> Update GH pull request template

- modules/social_features/social_group/social_group.module
- modules/social_features/social_group/src/Plugin/Block/GroupHeroBlock.php
> Notice: Undefined index: content in template_preprocess_block() (line 216 of core/modules/block/block.module).
Improve hero block visibility.
https://www.drupal.org/project/social/issues/2935919
> 2935919 Notice: Undefined index: content in template_preprocess_block()

- composer.json
- drupal-org-core.make
```
Error: Call to a member function getSetting() on null in Drupal\comment\CommentViewBuilder->getBuildDefaults() (line 65 of core/modules/comment/src/CommentViewBuilder.php).
Drupal\comment\CommentViewBuilder->getBuildDefaults(Object, 'activity') (Line: 138)
Drupal\Core\Entity\EntityViewBuilder->viewMultiple(Array, 'activity', 'und') (Line: 111)
Drupal\Core\Entity\EntityViewBuilder->view(Object, 'activity', 'und') (Line: 131)
Drupal\dynamic_entity_reference\Plugin\Field\FieldFormatter\DynamicEntityReferenceEntityFormatter->viewElements(Object, 'en') (Line: 80)
Drupal\Core\Field\FormatterBase->view(Object, 'en') (Line: 76)
Drupal\Core\Field\Plugin\Field\FieldFormatter\EntityReferenceFormatterBase->view(Object, NULL) (Line: 259)
Drupal\Core\Entity\Entity\EntityViewDisplay->buildMultiple(Ar …
```
> DS-4871: Fatal error occurs when clearing caches via CLI on multilingual installs

- .travis.yml
Do not check accessibility when building environment via Travis.
Create shell script for checking the accessibility of pages.
- https://jira.goalgorilla.com/browse/DS-4945
> DS-4945 Add tracker to Travis

- composer.json
- drupal-org-core.make
- modules/custom/social_demo/src/DemoContent.php
- modules/custom/social_demo/src/DemoContentParser.php
- modules/custom/social_demo/src/DemoContentParserInterface.php
- modules/social_features/social_follow_content/config/install/views.view.following.yml
- modules/social_features/social_like/config/install/views.view.who_liked_this_entity.yml
- tests/behat/features/bootstrap/FeatureContext.php
- tests/behat/features/capabilities/language/change-language.feature
Open Social is still on 8.4.
Update to 8.5.1
- https://www.drupal.org/project/social/issues/2957223
> #2957223 - Update to Drupal Core 8.5

- modules/custom/social_demo/content/entity/system.yml
- modules/social_features/social_core/social_core.install
- modules/social_features/social_group/src/Controller/SocialGroupContentListBuilder.php
- modules/social_features/social_profile/config/install/core.entity_form_display.profile.profile.default.yml
- tests/behat/features/capabilities/group/group-edit-open.feature
- themes/socialbase/components/01-base/tables/table.twig
- themes/socialbase/components/02-atoms/list/list-label.json
- themes/socialblue/components/styleguide/homepage.md
Both organisation and organization are found.
Let's switch to American English organization.
- https://www.drupal.org/project/social/issues/2948281
> Issue #2948281: Organisation should be organization

- social.profile
Reverts goalgorilla/open_social#781.
We're moving to the new `8.x-2.x` branch!
> Revert "DS-4503: enable inline form errors for new installs"

- modules/social_features/social_user_export/social_user_export.module
- modules/social_features/social_user_export/src/ExportUser.php
Reverts goalgorilla/open_social#736.
We're moving this to new `8.x-2.x` branch!
> Revert "Number of likes to be added to the CSV export"

- modules/social_features/social_profile/modules/social_profile_fields/src/Form/SocialProfileFieldsSettingsForm.php
Reverts goalgorilla/open_social#787.
We're moving this to the new `8.x-2.x` branch!
> Revert "DS-5042 by bramtenhove: Fix incompatibility issue with Social Profile Privacy and Social Profile Fields"

- modules/social_features/social_group/src/Plugin/Field/FieldWidget/SocialGroupSelectorWidget.php
When a LU is creating a new content item (topic/event) it is now required to select a group.
Made the code less complex and added appropriate checks for if the `$option_category` is an array or not. Also ensures that the `_none` option is never removed from the `$options` array.
- https://www.drupal.org/project/social/issues/2962743
> Issue #2962743 : Make group selection optional when creating content

- drupal-org.make
See: https://github.com/goalgorilla/open_social/pull/852
Can be merged when the make build is functioning as expected (Travis build successful).
> Issue #2962301 by jaapjan: add the patch for applying default cropping to make file

- themes/socialblue/assets/css/brand.css
- themes/socialblue/assets/css/button.css
- themes/socialblue/assets/css/ckeditor.css
- themes/socialblue/assets/css/like.css
- themes/socialblue/assets/css/page-node.css
- themes/socialblue/assets/css/preview.css
- themes/socialblue/components/05-templates/page-node/page-node.scss
- themes/socialblue/components/brand.scss
When creating a link via the editor in the introduction section, the link style as defined in the theme isn't applied.
Add styles for link in the introduction section in brand.css
- ECI-792
> ECI-792 Landingpage introduction link

- modules/custom/sitewide_js/sitewide_js.module
(cherry picked from commit 322f1bc90e9abfc2f69b0070985f6be1d849792f)
See PR:
https://github.com/goalgorilla/open_social/pull/905
> 2920717 by jochemvn, bramtenhove: Fix SitewideJS module for 8.x-2.x

- modules/social_features/social_post/src/Form/PostForm.php
Modified from #913 for `1.x` branch.
> #2941556: Editing posts in closed groups impossible

- modules/custom/activity_send/modules/activity_send_email/activity_send_email.module
This item is cherry-picked from https://github.com/goalgorilla/open_social/pull/923 for the `1.x` branch.
> #2932250 by bramtenhove: Remove the interval check for items in the daily digest

- modules/social_features/social_comment/config/install/core.entity_form_display.comment.comment.default.yml
- themes/socialbase/templates/comment/form--comment-edit.html.twig
Comment edit screen (as SM) looks not good
Fix styles/template for edit comment page
- https://jira.goalgorilla.com/browse/DS-5829
> DS-5829 by serhiy-chornobay: Fixed styles/template for edit comment page

- modules/social_features/social_core/social_core.install
See #971. Cherry-picked for 1.x.
> DS-5827 by jaapjan: update r4032login settings to make sure destination parameter works.

- drupal-org.make
Somebody forgot to update the makefile with patches
Make sure composer.json & drupal make files are the same
> 8.2.4 - Somebody forgot to update the makefile with patches

- modules/custom/activity_basics/activity_basics.module
- modules/social_features/social_group/social_group.module
- modules/social_features/social_group/social_group.services.yml
- modules/social_features/social_group/src/SetGroupsForNodeService.php
- tests/behat/features/bootstrap/FeatureContext.php
- tests/behat/features/bootstrap/SocialDrupalContext.php
- tests/behat/features/capabilities/group/group-edit-content-in-group.feature
This reverts #985, so now #952 is back for the 3.x branch.
We have fixed the issue in #984 
See #952 for test instructions.
> Put back #952 for 2.x 

- themes/socialblue/assets/css/brand.css
- themes/socialblue/assets/css/preview.css
- themes/socialblue/components/brand.scss
Reverts goalgorilla/open_social#1007
> Revert "FOR-101 by serhiy-chornobay: Fix brand color for Social Vote widget"

- .github/PULL_REQUEST_TEMPLATE.md
- themes/socialblue/assets/css/brand.css
- themes/socialblue/assets/css/preview.css
- themes/socialblue/components/brand.scss
Changed base branch to 8.3
See original: https://github.com/goalgorilla/open_social/pull/1007
> FOR-101 by serhiy-chornobay: Fix brand color for Social Vote widget

- themes/socialblue/assets/css/brand.css
- themes/socialblue/assets/css/preview.css
- themes/socialblue/components/brand.scss
- https://jira.goalgorilla.com/browse/NWO-26
> NWO-26 by serhiy-chornobay: Fix brand color for Social Birthday widget

- composer.json
> Update Core Patch on 4.x branch as well

- modules/custom/social_node_statistics/config/schema/social_node_statistics.schema.yml
- modules/custom/social_node_statistics/content/block/social_kpi_lite_node_views.yml
- modules/custom/social_node_statistics/social_node_statistics.install
- modules/custom/social_node_statistics/social_node_statistics.module
- themes/socialbase/socialbase.theme
- themes/socialbase/src/Plugin/Preprocess/Node.php
Some code improvements were possible for the recently merged node statistics module.
- Removed uninstall hook, added enforced dependency in block config
- Moved preprocess logic to module instead of theme
- Added config schema file
- https://www.drupal.org/project/social/issues/3013127
n/a (see #1102)
> #3013127 - Improved node statistics module

- themes/socialblue/assets/css/brand.css
- themes/socialblue/components/brand.scss
Cookie wall should work with changing colors in the Open Social blue theme
Add styles for Cookie wall in brand.scss
- https://jira.goalgorilla.com/browse/GPDE-12
> Cookie wall should work with changing colors in Open Social blue theme

- composer.json
Update to the latest version
https://www.drupal.org/project/social/issues/3021952
Updated bower-asset/tablesaw
> Issue #3021952 by truls1502: Update bower-asset/tablesaw from v3.0.9 to v3.1.0

- composer.json
The purpose of this feature request is that the package [zaporylie/composer-drupal-optimizations](https://packagist.org/packages/zaporylie/composer-drupal-optimizations) to save time and use less RAM regarding composer. 
Thanks to @zaporylie where I got help. 
Before: 
```
Memory usage: 331.03MB (peak: 756.01MB), time: 11.87s
```
After:
```
Memory usage: 285.35MB (peak: 471.11MB), time: 5.59s
```
- // To make sure the cache is populated and get solid results:
`composer update nothing `
- // Then run composer update without running an actual update:
`composer update nothing --profile`
- // Then add the package:
`composer require zaporylie/composer-drupal-optimizations`
- // Then run the update again and compare the results
`composer update nothing --profile` …
> Issue #3023428 by truls1502, zaporylie: Adding zaporylie/composer-drupal-optimizations

- composer.json
Update to the latest version
https://www.drupal.org/project/social/issues/3031858
Update bower-asset/highlight from 9.13.1 to 9.14.2
> Issue #3031858 by truls1502: Update bower-asset/highlight from 9.13.1 to 9.14.2

- modules/custom/activity_logger/activity_logger.install
- modules/custom/activity_logger/activity_logger.module
- modules/custom/activity_logger/activity_logger.post_update.php
- modules/custom/activity_logger/config/schema/activity_logger.schema.yml
PR for https://www.drupal.org/project/social/issues/3020571
> #3020571: Implement config schema for message.template.*.third_party.activity_logger

- composer.json
Update to the latest version
https://www.drupal.org/project/social/issues/3038771
Update bower-asset/highlight from 9.14.2 to 9.15.6
> Issue #3038771 by truls1502: Update bower-asset/highlight from 9.14.2 to 9.15.6

- composer.json
Update bower-asset/raphael from v2.2.7 to v2.2.8
https://www.drupal.org/project/social/issues/3044304
Update bower-asset/raphael from v2.2.7 to v2.2.8
> Issue #3044304: Update bower-asset/raphael from v2.2.7 to v2.2.8

- modules/social_features/social_landing_page/config/install/views.view.community_activities.yml
Some PRs were never cherry-picked (or incorrectly it seems) to 4.x
- #1143 
- #1112 
Do it again
I think we can re-use the issue tracker
- Let the test do the work.
We can re-use the issue tracker
> Missing PRs For 4.x (and 5.x)

- composer.json
- drupal-org-core.make
Tests are failing because a change in the latest Symfony, more info here:
https://www.drupal.org/project/drupal/issues/3045349#comment-13054347
Let's apply the patch.
https://www.drupal.org/project/social/issues/3045866
Symfony 3.4.24 caused some issues related to session management, we solved this by applying the relevant Drupal core patch.
> Issue #3045349: Add patch to fix session handling in Symfony

- .travis.yml
- composer.json
I believe it will take the test quicker and easier to restart specific `install_stability` rather than 3 to 5.
> Splitted the install_stability_3-4-5

- README.md
https://www.drupal.org/project/social/issues/3046626
> Issue #3046626 by truls1502: Add Travis badge to README.md (4.x)

- README.md
Same as #1307 - but for 5.x
https://www.drupal.org/project/social/issues/3046626
> Issue #3046626 by truls1502: Add Travis badge to README.md (5.x)

- README.md
Added Packagist version and Follow their Twitter account
> Update README.md for 5.x with two more badges

- composer.json
- drupal-org-core.make
- social.info.yml
[SA-CORE-2019-006](https://www.drupal.org/sa-core-2019-006)
- https://www.drupal.org/project/social/issues/3048992
> Issue #3048992 by truls1502: Update Drupal Core to 8.6.15 for 4.10

- composer.json
- drupal-org-core.make
- social.info.yml
[SA-CORE-2019-006](https://www.drupal.org/sa-core-2019-006)
- https://www.drupal.org/project/social/issues/3048992
> Issue #3048992 by truls1502: Update Drupal Core to 8.6.15 for 5.1

- themes/socialbase/yarn.lock
- themes/socialblue/yarn.lock
We need to update our dependencies in yarn.lock 
Did that. 
-
- 
Updated dependencies for our subtheme.
> Update TAR dependency in yarn

- composer.json
- drupal-org-core.make
https://www.drupal.org/SA-CORE-2019-007
<describe the solution you're created>
<paste a link to the drupal.org issue queue item, or any other issue tracker if applicable>
If this Pull Request changes the way that developers should do things or introduces a new API for developers then a change record to document this is needed. Please provide a draft for a change record or a link to an unpublished change record below. [Existing change records](https://www.drupal.org/list-changes/social) can be consulted as example.
> SA-CORE-2019-007 - Update core, see what tests do

- composer.json
- drupal-org.make
[Full Changelog](https://git.drupalcode.org/project/bootstrap/compare/8.x-3.17...8.x-3.19)
- https://www.drupal.org/project/bootstrap/releases/8.x-3.19
https://www.drupal.org/project/social/issues/3054119
Update drupal/bootstrap from 3.17 to 3.19
> Issue #3054119 by truls1502: Update drupal/bootstrap from 3.17 to 3.19

- themes/socialbase/assets/css/navbar.css
- themes/socialbase/components/03-molecules/navigation/navbar/navbar.scss
- themes/socialbase/includes/form.inc
- themes/socialblue/assets/css/brand.css
- themes/socialblue/assets/css/preview.css
- themes/socialblue/components/brand.scss
After configuring header menu to white, then click the search icon in the menu. In the light box appears afterwards, the search icon is not visible anymore, maybe because it is also white.
Add svg icon for search button.
https://www.drupal.org/project/social/issues/3029706
After configuring header menu to the white search icon was invisible. Now it will take color of the text - according to the color scheme.
> Issue #3029706 by agami4: Add svg icon for search button

- modules/social_features/social_follow_content/config/install/views.view.following.yml
Buttons on the Content I follow page are duplicated
Remove the duplicate buttons
https://www.drupal.org/project/social/issues/3029738
Removed the wrapper div for the unfollow link.
> Issue #3029738 by agami4: Remove the duplicate buttons

- composer.json
- drupal-org.make
[Full Changelog](https://git.drupalcode.org/project/bootstrap/compare/8.x-3.19...8.x-3.20)
- https://www.drupal.org/project/bootstrap/releases/8.x-3.20
https://www.drupal.org/project/social/issues/3021413
Update drupal/bootstrap from 3.19 to 3.20
> Issue #3063282 by truls1502: Update drupal/bootstrap from 3.19 to 3.20

- modules/social_features/social_swiftmail/social_swiftmail.links.menu.yml
Related to PR: #1432 a small textual change.
I don't think release note changes or How to test is needed here. If automated tests pass let's merge.
> Issue #2983330: rename description for e-mail settings (Remove Swiftmail reference)

- modules/social_features/social_content_block/social_content_block.module
Social content block not descriptive enough
Add more descriptions to the fields in the form
> by robertragas: add description fields to explain what they do

- themes/socialbase/src/Plugin/Preprocess/PageTitle.php
Getting error on edit profile page: /user/*/profile
Error: Call to a member function getArguments() on string in /public_html/profiles/contrib/social/themes/socialbase/src/Plugin/Preprocess/PageTitle.php on line 29
Make sure that $variables['title'] is a TranslatableMarkup before getting arguments.
https://www.drupal.org/project/social/issues/3069288
> issue #3069288 edit profile - unexpected error

- themes/socialbase/assets/css/hero.css
- themes/socialbase/components/04-organisms/hero/hero.scss
- themes/socialbase/templates/profile/profile--profile--hero.html.twig
Reverts goalgorilla/open_social#1450
> Revert "#3066658: Add bottom space for private message button"

- themes/socialblue/assets/css/brand.css
- themes/socialblue/components/brand.scss
If change color scheme for theme, color title of course is black
Add ability to change color according to color scheme
https://www.drupal.org/project/social/issues/3084689
Color title of course change according to color scheme
> Issue #3084689 by agami4: Update color for title of course according to scheme color

- .gitignore
- modules/custom/social_path_manager/social_path_manager.module
- modules/social_features/social_comment_upload/social_comment_upload.module
- modules/social_features/social_group/src/SetGroupsForNodeService.php
Avoid calls to ::load() in loops.
1. Use ::loadMultiple
2. Refactor the code to put most logical if conditions to be checked first.
https://www.drupal.org/project/social/issues/3085248
- N.A
N.A
N.A
> Issue #3085248: Replaced individual ::load calls in loop with ::loadMultiple along with some code adjustments.

- themes/socialbase/templates/node/node--teaser.html.twig
Revert latest fixes in 8.x to see if that fixes travis PR's.
Reverts.
<paste a link to the drupal.org issue queue item, or any other issue tracker if applicable>
If this Pull Request changes the way that developers should do things or introduces a new API for developers then a change record to document this is needed. Please provide a draft for a change record or a link to an unpublished change record below. [Existing change records](https://www.drupal.org/list-changes/social) can be consulted as example.
> #1362 - follow up

- composer.json
- translations.php
The Drupal core patch was failing to apply on Drupal 8.7.9 update
Apply the patch from https://www.drupal.org/project/drupal/issues/3007424#comment-13349811
https://www.drupal.org/project/social/issues/3093583
> Updated the lastest patch from Drupal core.

- modules/custom/activity_send/modules/activity_send_email/src/Plugin/QueueWorker/ActivitySendEmailWorker.php
…nto batches of 50 for large groups
We moved to one to many notification to reduce the amount of queue workers. For example you have a group of 1000 members and post a message. This will create 1000 queue workers.
In this new feature it will only create 1 queue worker. 
The problem is that this is too much for large groups, because it will loop through it 1000 times and get a timeout on the cronjob on certain hosts, such as Pantheon. In the next cronjob it will go through the same loop again, sending the same notifications.
If there are more than 50 recipients, split it up in batches to make sure it does not time out.
In our one to many feature change we optimized the amount of queue workers that get created for 1 activity. This queue worker had too much information resulting in timeouts …
> Split up the one to many queue workers into batches of 50 for large groups

- modules/social_features/social_follow_content/config/features_removal/block.block.exposedformfollowingfollowing.yml
- modules/social_features/social_follow_content/config/features_removal/field.field.message.create_comment_following_node.field_message_context.yml
- modules/social_features/social_follow_content/config/features_removal/field.field.message.create_comment_following_node.field_message_destination.yml
- modules/social_features/social_follow_content/config/features_removal/field.field.message.create_comment_following_node.field_message_related_object.yml
- modules/social_features/social_follow_content/config/features_removal/flag.flag.follow_content.yml
- modules/social_features/social_follow_content/config/features_removal/message.template.create_comment_following_node.yml
- modules/social_features/social_follow_content/config/features_removal/views.view.following.yml
- modules/social_features/social_follow_content/social_follow_content.features.yml
See problem definition in [#3092272: [Meta] [PP-1] Moving away from features.](https://www.drupal.org/project/social/issues/3092272)
Remove the `module.features.yml` file
- Move the default editable config from `hook_install()` into a module's `config/install/*.yml` file.
- If `hook_install` alters configuration from other modules, consider whether we should include the config file in the profile's `config/install` folder to overwrite it instead
- Remove any `_module_set_defaults` function
https://www.drupal.org/project/social/issues/3102808
> Issue #3102808 by Kingdutch: Remove features from Social Follow Content

- modules/social_features/social_search/config/features_removal/search_api.index.social_all.yml
- modules/social_features/social_search/config/features_removal/search_api.index.social_content.yml
- modules/social_features/social_search/config/features_removal/search_api.index.social_groups.yml
- modules/social_features/social_search/config/features_removal/search_api.index.social_users.yml
- modules/social_features/social_search/config/features_removal/search_api.server.social_database.yml
- modules/social_features/social_search/config/features_removal/views.view.search_all.yml
- modules/social_features/social_search/config/features_removal/views.view.search_content.yml
- modules/social_features/social_search/config/features_removal/views.view.search_groups.yml
- modules/social_features/social_search/config/features_removal/views.view.search_users.yml
- modules/social_features/social_search/config/install/search_api.settings.yml
- modules/social_features/social_search/config/install/search_api_db.settings.yml
- modules/social_features/social_search/social_search.features.yml
See problem definition in [#3092272: [Meta] [PP-1] Moving away from features.](https://www.drupal.org/project/social/issues/3092272)
Remove the `module.features.yml` file
- Move the default editable config from `hook_install()` into a module's `config/install/*.yml` file.
- If `hook_install` alters configuration from other modules, consider whether we should include the config file in the profile's `config/install` folder to overwrite it instead
- Remove any `_module_set_defaults` function
https://www.drupal.org/project/social/issues/3102803
> Issue #3102803 by Kingdutch: Remove features from Social Search

- modules/social_features/social_comment_upload/config/features_removal/field.field.comment.comment.field_comment_files.yml
- modules/social_features/social_comment_upload/config/features_removal/field.storage.comment.field_comment_files.yml
- modules/social_features/social_comment_upload/social_comment_upload.features.yml
See problem definition in <a href="https://www.drupal.org/project/social/issues/3092272">#3092272: [Meta] [PP-1] Moving away from features</a>.
<ul>
<li>Remove the <code>module.features.yml</code> file</li>
<li>Move the default editable config from <code>hook_install()</code> into a module's <code>config/install/*.yml</code> file.</li>
<li>If <code>hook_install</code> alters configuration from other modules, consider whether we should include the config file in the profile's <code>config/install</code> folder to overwrite it instead</li>
<li>Remove any <code>_module_set_defaults</code> function</li>
</ul>
https://www.drupal.org/project/social/issues/3100560
> Issue #3100560 by Kingdutch: Remove features from Social Comment Upload

- modules/social_features/social_page/config/features_removal/core.base_field_override.node.page.promote.yml
- modules/social_features/social_page/config/features_removal/core.entity_form_display.node.page.default.yml
- modules/social_features/social_page/config/features_removal/core.entity_view_display.node.page.activity.yml
- modules/social_features/social_page/config/features_removal/core.entity_view_display.node.page.activity_comment.yml
- modules/social_features/social_page/config/features_removal/core.entity_view_display.node.page.default.yml
- modules/social_features/social_page/config/features_removal/core.entity_view_display.node.page.search_index.yml
- modules/social_features/social_page/config/features_removal/core.entity_view_display.node.page.teaser.yml
- modules/social_features/social_page/config/features_removal/field.field.node.page.body.yml
- modules/social_features/social_page/config/features_removal/field.field.node.page.field_content_visibility.yml
- modules/social_features/social_page/config/features_removal/field.field.node.page.field_files.yml
- modules/social_features/social_page/config/features_removal/field.field.node.page.field_page_comments.yml
- modules/social_features/social_page/config/features_removal/field.field.node.page.field_page_image.yml
- modules/social_features/social_page/config/features_removal/field.storage.node.field_page_comments.yml
- modules/social_features/social_page/config/features_removal/field.storage.node.field_page_image.yml
- modules/social_features/social_page/config/features_removal/node.type.page.yml
- modules/social_features/social_page/social_page.features.yml
See problem definition in [#3092272: [Meta] [PP-1] Moving away from features.](https://www.drupal.org/project/social/issues/3092272)
Remove the `module.features.yml` file
- Move the default editable config from `hook_install()` into a module's `config/install/*.yml` file.
- If `hook_install` alters configuration from other modules, consider whether we should include the config file in the profile's `config/install` folder to overwrite it instead
- Remove any `_module_set_defaults` function
[https://www.drupal.org/project/social/issues/3099849](https://www.drupal.org/project/social/issues/3099849)
- Enable all changed modules
- See that none of them install configuration provided by other modules
- Change configuration for each module
- Revert features
> Issue #3099849 by sjoerdvandervis: Removed features.yml file from social_page

- modules/social_features/social_sharing/social_sharing.features.yml
See problem definition in [#3092272]. 
The features file exists but excludes all config files so it does absolutely nothing
Throw it away :D 
https://www.drupal.org/project/social/issues/3097274
> Issue #3097274 by Kingdutch: Remove features from Social Sharing module

- modules/social_features/social_group/modules/social_group_welcome_message/social_group_welcome_message.info.yml
- modules/social_features/social_group/modules/social_group_welcome_message/social_group_welcome_message.module
- modules/social_features/social_group/modules/social_group_welcome_message/social_group_welcome_message.services.yml
- modules/social_features/social_group/modules/social_group_welcome_message/src/SocialGroupWelcomeMessageConfigOverride.php
Private message when successfully joining the group
Implement Social Group Welcome Message module
https://www.drupal.org/project/social/issues/3087026
https://getopensocial.atlassian.net/browse/YANG-1463
Enable social_group_welcome_message
Implements possibility to send private message when successfully joining the group
> Issue #3087026 by mdeny: Social Group Welcome Message

- modules/social_features/social_core/social_core.install
- modules/social_features/social_core/social_core.post_update.php
- modules/social_features/social_user/config/features_removal/social_user.settings.yml
Internal interdiff for features-removal story.
<describe the solution you're created>
<paste a link to the drupal.org issue queue item, or any other issue tracker if applicable>
If this Pull Request makes visual changes then please include some screenshots that show what has changed here. 
If this Pull Request changes the way that developers should do things or introduces a new API for developers then a change record to document this is needed. Please provide a draft for a change record or a link to an unpublished change record below. [Existing change records](https://www.drupal.org/list-changes/social) can be consulted as example.
> Control timing of features removal update

- modules/social_features/social_landing_page/social_landing_page.module
When I click "Manage enrollments" on the event view page:
> The website encountered an unexpected error. Please try again later.
> Error: Call to a member function bundle() on string in social_landing_page_preprocess_page() (line 131 of profiles/contrib/social/modules/social_features/social_landing_page/social_landing_page.module).
Add a check if variable is instanceof NodeInterface
- https://www.drupal.org/project/social/issues/3116193
- https://getopensocial.atlassian.net/browse/ECI-1000
> Issue #3116193 by SV: Prevent error on the event enrollments page

- modules/social_features/social_search/social_search.module
https://travis-ci.org/goalgorilla/open_social/jobs/657696197#L1588
Do the changes in files reporting coding standard errors.
N.A
N.A
N.A
N.A
N.A
> Fixed coding standard errors reported on running PHPCS.

- themes/socialblue/assets/css/brand--sky.css
- themes/socialblue/assets/css/site-footer--sky.css
- themes/socialblue/components/04-organisms/site-footer/site-footer--sky.scss
- themes/socialblue/components/brand--sky.scss
Should revert color changes for the footer
Revert color changes for the footer
https://getopensocial.atlassian.net/browse/YANG-2961
https://www.drupal.org/project/social/issues/3138858
> Issue #3138858 by Agami4: Revert color changes for the footer in sky style

- themes/socialbase/src/Plugin/Preprocess/Block.php
Fatal error when I tried to edit the node
Add an extra condition to socialbase theme in preprocess block (`themes/socialbase/src/Plugin/Preprocess/Block.php`)
https://www.drupal.org/project/social/issues/3137793
If this Pull Request makes visual changes then please include some screenshots that show what has changed here. 
If this Pull Request changes the way that developers should do things or introduces a new API for developers then a change record to document this is needed. Please provide a draft for a change record or a link to an unpublished change record below. [Existing change records](https://www.drupal.org/list-changes/social) can be consulted as example.
> Issue #3137793 by rolki: Add extra conditions to theme block preprocess

- themes/socialbase/assets/css/dropdown.css
- themes/socialbase/assets/css/navbar.css
- themes/socialbase/components/00-config/_mixins.scss
- themes/socialbase/components/00-config/mixins/_dropdown-menu.scss
- themes/socialbase/components/03-molecules/dropdown/dropdown.scss
- themes/socialbase/components/03-molecules/navigation/navbar/navbar.scss
- themes/socialbase/templates/navigation/menu.html.twig
- themes/socialblue/assets/css/brand.css
- themes/socialblue/components/brand.scss
Add a second level menu level in the navigation bar
https://getopensocial.atlassian.net/browse/YANG-2706
https://www.drupal.org/project/social/issues/3137523
Added a second level menu level in the navigation bar
> Issue #3137523 by agami4: Add styles for the second level main menu

- composer.json
- drupal-org-core.make
https://www.drupal.org/project/drupal/releases/8.8.8
Was released
Drupal core - Critical - Cross-Site Request Forgery - SA-CORE-2020-004
Drupal core - Critical - Arbitrary PHP code execution - SA-CORE-2020-005
Drupal core - Less critical - Access bypass - SA-CORE-2020-006
Lets up our minimum requirements, should not stop anybody from updating in the meantime. 
Lets see if tests pass :)
> Updated Drupal Core to 8.8.8

- modules/social_features/social_book/social_book.install
- modules/social_features/social_book/src/SocialBookConfigOverride.php
Reverts goalgorilla/open_social#1904
This wasn't necessary there is a better way to solve it.
> Revert "Issue #3159259: Book pages need to be available in the search all and search autocomplete"

- composer.json
On most of the entity add / edit pages we get a
`Undefined property: stdClass::$region in field_group_form_process()`
Update field group to the latest
And patch it with https://www.drupal.org/project/field_group/issues/3059614
Or ensure older patch for 3.0 is added
https://www.drupal.org/project/field_group/issues/3059614#comment-13478246
https://www.drupal.org/project/social/issues/3162843
*For example*
We have updated field_group to 3.1 and ensured we patch the notice on any of the entity add and edit pages.
> Issue #3162843 - Undefined property: stdClass::$region in field_group_form_process()

- themes/socialbase/assets/css/button.css
- themes/socialbase/components/02-atoms/button/button.scss
Drupal shows a contextual menu for edit and delete that in Open Social consists of a small pencil in a circle. This occurs when the user has the "use contextual actions" permission.
The pencil in this contextual icon doesn't match contrast guidelines.
Change the pencil icon and add focus behavior.
https://www.drupal.org/project/social/issues/3171763
*For example*
Change the icon for the edit button and add focus behavior
-
-
> Issue #3171763 by agami4: Change icon and focus behavior for edit button

- themes/socialblue/assets/css/site-footer.css
- themes/socialblue/components/04-organisms/site-footer/site-footer.scss
With the new `social_footer` module, the footer needs some UI updates.
Add support for the new block and add style updates for the footer menu.
- https://www.drupal.org/project/social/issues/3185615
- https://getopensocial.atlassian.net/browse/YANG-4347
Before
After
Add updates to the footer block and Powered by block
- N/A
- N/A
> Issue #3185615 by agami4: Fix alignment of footer menu if site logo block is added

- modules/social_features/social_content_report/src/ContentReportService.php
#2091 - Added some coding standards
Fix em.
Not needed.
Make sure CS is fixed.
Not needed.
> Issue #3186203 by ronaldtebrake: Fix CS for TB-5356

- composer.json
- themes/socialbase/socialbase.libraries.yml
6 years was passed since the last release of the morris library so I suggest using another version on this library. Also, it needs to provide a new horizontal bar chart for KPI (screenshot).
Use the new library https://www.npmjs.com/package/morris.js06
https://www.drupal.org/project/social/issues/3184207
https://getopensocial.atlassian.net/browse/YANG-3983
N/A
A new version of Morris library.
The process of using morris is not changed. The new library support all features from old, just add something new.
N/A
> Issue #3184207 by tBKoT: Update morris.js library from version 0.5 to 0.6

- themes/socialblue/templates/node/event/node--event--hero--sky.html.twig
Saw the comment on https://github.com/goalgorilla/open_social/pull/2074 1 second too late, and he was right so following that up here.
> by robertragas: follow-up bugfix for removing metadata from events

- modules/social_features/social_footer/assets/css/social_footer.css
- modules/social_features/social_footer/assets/css/social_footer.css.map
- modules/social_features/social_footer/assets/css/social_footer.scss
- modules/social_features/social_footer/config/optional/block.block.footer_powered.yml
- modules/social_features/social_footer/config/optional/block.block.socialblue_footer_powered.yml
- modules/social_features/social_footer/config/schema/social_footer.schema.yml
- modules/social_features/social_footer/social_footer.info.yml
- modules/social_features/social_footer/social_footer.installer_options.yml
- modules/social_features/social_footer/social_footer.libraries.yml
- modules/social_features/social_footer/social_footer.module
- modules/social_features/social_footer/src/Plugin/Block/SocialFooterPoweredByBlock.php
- social.info.yml
As a user, I want to see a logo in the footer.
Should be possible to replace: logo, text, link.
- https://www.drupal.org/project/social/issues/3189520
- https://getopensocial.atlassian.net/browse/ECI-1113
There is now an easy option to add your organizations logo to the footer next to the footer menu.
> Issue #3189520 by chmez: As a user I want to see logo in the footer

- modules/social_features/social_album/config/install/core.entity_form_display.node.album.default.yml
- modules/social_features/social_album/social_album.module
Update the album content form as per new design changes.
Update the entity form display of album.
https://www.drupal.org/project/social/issues/3172477
Will be picked up from main PR.
N.A
N.A
> Issue#3177902 - Album content form design changes.

- themes/socialbase/assets/css/teaser.css
- themes/socialbase/components/03-molecules/teaser/teaser.scss
- themes/socialblue/assets/css/teaser--sky.css
- themes/socialblue/components/03-molecules/teaser/teaser--sky.scss
Teaser tag text on the teasers do not break properly and displays line break mid-word.
Disable word wrapping to a new line.
https://www.drupal.org/project/social/issues/3194809
https://getopensocial.atlassian.net/browse/YANG-4590
*For example*
before:
after:
-[ ] resource library:
The teaser will be on one line if it has a long text.
-
-
> Issue #3194809 by agami4: Improve teaser tag for the teasers in SKY style

- composer.json
Follow up of #1953.
Update patches which we use from 
1. https://www.drupal.org/project/url_embed/issues/2867668
2. https://www.drupal.org/project/url_embed/issues/2761187
3. https://www.drupal.org/project/social/issues/2930457
Combine the patches and create a custom one to be used with open social
https://www.drupal.org/project/social/issues/2930457#comment-13973067
N.A
N.A
N.A
N.A
> Issue/3165299 by navneet0693: Add latest patches in url_embed module.

- composer.json
Fatal error in ajax comment module:
```
TypeError: Argument 1 passed to Drupal\ajax_comments\FieldSettingsHelper::isEnabled() must implement interface Drupal\Core\Field\FormatterInterface, bool given, called in /var/www/html/modules/contrib/ajax_comments/ajax_comments.module on line 91 in Drupal\ajax_comments\FieldSettingsHelper->isEnabled() (line 160 of modules/contrib/ajax_comments/src/FieldSettingsHelper.php).
```
```
Drupal\ajax_comments\FieldSettingsHelper->isEnabled() (Line: 91)
ajax_comments_comment_links_alter(Array, Object, Array) (Line: 539)
Drupal\Core\Extension\ModuleHandler->alter('comment_links', Array, Object, Array) (Line: 157)
Drupal\comment\CommentLazyBuilders->renderLinks('246', 'activity_comment', …
```
> Issue #3198706 by Ressinel: Fix fatal error in ajax comment module.

- modules/custom/activity_viewer/src/Plugin/views/filter/ActivityFilterPersonalisedHomepage.php
Regression after merging the #2229 PR.
Check comment from @ronaldtebrake https://github.com/goalgorilla/open_social/pull/2229#issuecomment-801199399
Change conditions for comments activity.
https://getopensocial.atlassian.net/browse/YANG-5208
N/A
N/A
N/A
N/A
N/A
> Issue #3197794 by tBKoT: Fix regression on activity stream

- tests/behat/features/capabilities/group/group-edit-content-in-group.feature
Tests were failing in /social/tests/behat/features/capabilities/group/group-edit-content-in-group.feature.
Add a cron run statement for the creation of activities in-stream page.
N.A
N.A
N.A
N.A
N.A
> [Internal] - Add extra cron run statement for fixing test

- modules/social_features/social_group/modules/social_group_invite/src/Controller/SocialGroupInvitationOperations.php
There is an issue with redirecting after user clicks email link the second time - sending to an unusable page
Redirect user to the group if he is already a member of this group to prevent displaying "Access denied" page
- https://getopensocial.atlassian.net/browse/YANG-5341
- https://www.drupal.org/project/social/issues/3214990
- https://github.com/goalgorilla/open_social/pull/2233
Unusable page: 
Email:
Redirect user to the invited group instead of sending to unusable page after confirming join(in a second time)
> Issue #3214990 by SV: Redirect user to the group if he is already a member of invited group

- modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
We get this error message in a lot of admin pages:
`Notice: Undefined index: #type in social_group_flexible_group_preprocess_form_element()`
- https://www.drupal.org/project/social/issues/3208208
> Issue #3208208 by vnech: Fix annoying error message 

- modules/social_features/social_group/social_group.module
- tests/behat/features/capabilities/group/group-create-flexible.feature
The `group_create_flexible` feature is giving us results.
Fix it.
https://www.drupal.org/project/social/issues/3215641
Behat should pass again.
> [WIP] - Internal - Fix behat test

- composer.json
Update ctools to latest version.
Update ctools to latest version.
TBD.
Updated ctools from 3.6 -> 3.7
> Update ctools to 3.7

- modules/custom/activity_creator/src/ActivityNotifications.php
- modules/social_features/social_event/modules/social_event_managers/src/Plugin/views/field/SocialEventManagersViewsBulkOperationsBulkForm.php
- modules/social_features/social_event/src/Form/EnrollActionForm.php
- modules/social_features/social_follow_taxonomy/src/Plugin/ActivityContext/FollowTaxonomyActivityContext.php
- modules/social_features/social_group/src/Plugin/views/field/SocialGroupViewsBulkOperationsBulkForm.php
There are the same PHPStant errors for each new PR which do not mention PR changes.
Fix those PHPStan errors directly.
N/A
N/A
N/A
N/A
> [Internal] - Fix PHPStan errors.

- composer.json
Update the CSV Serialization module to have compatibility with Drupal 9
Update to the latest version.
- https://www.drupal.org/project/social/issues/3224507
N/A
The CSV Serialization module has been updated to 2.0. Please view the release notes from [2.0-beta3](https://www.drupal.org/project/csv_serialization/releases/8.x-2.0-beta3) and [2.0](https://www.drupal.org/project/csv_serialization/releases/8.x-2.0) of that module for the changes.
N/A
N/A
> Issue #3224507 by Ressinel: Update the CSV Serialization module from 2.0-beta1 to 2.0

- composer.json
- modules/social_features/social_album/social_album.module
- modules/social_features/social_event/config/update/social_event_update_10303.yml
- modules/social_features/social_event/social_event.install
- modules/social_features/social_group/config/update/social_group_update_10302.yml
- modules/social_features/social_group/social_group.install
- modules/social_features/social_search/config/install/views.view.search_all.yml
- modules/social_features/social_search/config/update/social_search_update_10301.yml
- modules/social_features/social_search/social_search.install
- tests/behat/features/capabilities/group/group-edit-open.feature
- tests/behat/features/capabilities/language/change-language.feature
- tests/behat/features/capabilities/private-message/create-private-message.feature
- tests/behat/features/capabilities/profile/profile-tags.feature
- tests/behat/features/capabilities/topic/topic-follow-content.feature
It seems it's been solved in `instaclick/php-webdriver` master, but not yet tagged in a release, so we will fix it locally.
This error causes an `curl_error` on our side.
Create a patch.
https://www.drupal.org/project/social/issues/3226058#comment-14177898
See test pass.
> #3226058 - Curl_exec error - the PHP Webdriver we use for our behat tests causes issues.

- modules/social_features/social_album/src/Plugin/Field/FieldWidget/SocialAlbumOptionsSelectWidget.php
Reverts goalgorilla/open_social#2495
> Revert "Issue #3232350 by rolki: Not possible to add new images to the existing album from the stream page"

- composer.json
- modules/custom/activity_send/modules/activity_send_email/src/Plugin/ActivitySend/EmailActivitySend.php
- modules/custom/activity_send/src/Plugin/ActivitySendInterface.php
- modules/custom/social_advanced_queue/src/Plugin/ActivitySend/EmailActivitySendAdvancedQueue.php
- modules/social_features/social_footer/src/Form/FooterSettingsForm.php
- phpstan-baseline.neon
- phpstan.neon
We were running into some PHPStan annoyances and were using an incorrect phpstan-drupal version.
- Relax phpstan-drupal version 
- Ignore missing iterable value type in PHPStan 
-  Fix open PHPStan errors
- Regenerate PHPStan baseline
N/a
N/a 
N/a internal change
> Fine-tune PHPStan config

- modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/social_follow_landing_page.module
- phpstan-baseline.neon
It is not possible to see selected tags in the 'Follow tag' block when we edit it because default values are empty. For the best example of it issue, we need to use dashboards.
Need to change behavior how we can get default values of selected tags.
https://www.drupal.org/project/social/issues/3247723
https://getopensocial.atlassian.net/browse/YANG-6576
N/A
N/A
N/A
> Issue #3247723 by tBKoT: Fix missing tags in edit form of Follow tag block

- modules/social_features/social_like/social_like.module
This is a follow up from: https://github.com/goalgorilla/open_social/pull/2596
> Issue #3248515 by SV: Add attributes only for existing elements to fix voting

- modules/custom/social_demo/content/entity/comment.yml
- modules/custom/social_demo/content/entity/event-enrollment.yml
- modules/custom/social_demo/content/entity/event.yml
- modules/custom/social_demo/content/entity/group.yml
- modules/custom/social_demo/content/entity/page.yml
- modules/custom/social_demo/content/entity/post.yml
- modules/custom/social_demo/content/entity/topic.yml
- modules/custom/social_demo/developer/content/entity/event.yml
- modules/custom/social_demo/developer/content/entity/topic.yml
- modules/custom/social_demo/eaa/content/entity/book.yml
- modules/custom/social_demo/eaa/content/entity/comment.yml
- modules/custom/social_demo/eaa/content/entity/event-enrollment.yml
- modules/custom/social_demo/eaa/content/entity/event.yml
- modules/custom/social_demo/eaa/content/entity/group.yml
- modules/custom/social_demo/eaa/content/entity/page.yml
- modules/custom/social_demo/eaa/content/entity/post.yml
- modules/custom/social_demo/eaa/content/entity/topic.yml
Currently demo content has und as default language, this causes it to be left out in a couple of views due to the language filter.
Current demo content has "und" as a default language.
Update demo module and add "en" as default language code.
https://www.drupal.org/project/social/issues/3249155
N/A
N/A
N/A
N/A
> 3249155 | Adding default en as content demo language

- composer.json
Related to https://github.com/goalgorilla/open_social/pull/2317
There is a new patch in the tracker issue.
Update patch.
- https://www.drupal.org/project/views_bulk_operations/issues/3217543
N/A
N/A
N/A
N/A
> Update patch for VBO module.

- src/Installer/Form/ModuleConfigureForm.php
Fix issue while installing Open Social
Check the default value of the "array_merge" function
N/A
N/A
N/A
N/A
N/A
> Fixing the install_configure_form step

- modules/custom/activity_send/modules/activity_send_email/src/Plugin/QueueWorker/ActivityDigestWorker.php
Have more defensive checks in ActivityDigestWorker.
Improve defensive checks.
N.A
N.A
N.A
N.A
N.A
> [Internal] Improved defensive checks in ActivityDigestWorker queueworker.

- modules/social_features/social_core/social_core.module
- modules/social_features/social_tagging/social_tagging.module
1. Remove accidentally added function from code social_tagging_entity_form_display_alter().
2. Remove $form_display->save() call in hook_entity_form_display_alter().
See: https://github.com/goalgorilla/open_social/pull/2450
See: https://github.com/goalgorilla/open_social/pull/2335#discussion_r772869928
See: https://github.com/goalgorilla/open_social/pull/2360#discussion_r772869513
Remove the code.
N.A
N.A
N.A
N.A
> [Internal] Remove un-required code.

- composer.json
Update the socialblue theme to latest version.
Update to https://www.drupal.org/project/socialblue/releases/1.3.4
N.A
N.A
N.A
N.A
N.A
> Update socialblue theme to latest version.

- modules/social_features/social_event/modules/social_event_an_enroll/src/Form/EventAnEnrollForm.php
When you enable the data_policy and social_event_an_enroll and add multiple data policies, the data policies are incorrectly displayed when an anonymous user tries to enroll in the event. It will always display just the first policy. 
The issue is that data_policy module was updated to enable multiple data policies, this change was never updated in the social_event_an_enroll module, where the code still expects only 1 data policy.
https://www.drupal.org/project/social/issues/3255592
1. Enable data_policy and social_event_an_enroll
2. Enable data_policy
3. Add multiple data policies and update the consent text to include all of them
4. Create a public event with anonymous enrollments enabled
5. Try to enroll in an event as an anonymous user and check the data policy
Before:
After:
Fixed …
> Issue #3255592 by nkoporec: Social Event Anonymous Enrolments - the data policy is incorrect

- modules/social_features/social_swiftmail/social_swiftmail.install
> Backport #2724 - Fix out of the box swiftmailer config

- modules/custom/activity_send/modules/activity_send_email/activity_send_email.module
- modules/custom/download_count/download_count.module
- modules/custom/dropdown/dropdown.module
- modules/custom/dropdown/src/Element/Dropdown.php
- modules/custom/social_demo/src/DemoContent.php
- modules/custom/social_demo/src/DemoContentManager.php
- modules/custom/social_demo/src/Plugin/DemoContent/MenuLink.php
- modules/custom/social_lets_connect/modules/social_lets_connect_usage/src/Plugin/ShareUsageDataPlugin/EntityTypeCount.php
- modules/social_features/social_activity/modules/social_activity_filter/src/Plugin/views/filter/ActivityFilterTags.php
- modules/social_features/social_core/social_core.install
- modules/social_features/social_core/social_core.module
- modules/social_features/social_group/modules/social_group_welcome_message/social_group_welcome_message.module
- modules/social_features/social_landing_page/social_landing_page.module
- modules/social_features/social_swiftmail/src/Form/SocialSwiftmailSettingsForm.php
- modules/social_features/social_tagging/social_tagging.module
- modules/social_features/social_user/social_user.module
Drupal coding standard check is failing due to release of new Coder module.
https://www.drupal.org/project/coder/releases/8.3.14
Fix coding standard errors.
N.A
N.A
N.A
N.A
N.A
> Added fixes for PHPCS.

- modules/custom/social_lets_connect/modules/social_lets_connect_usage/src/Plugin/ShareUsageDataPlugin/ModulesInstalled.php
- modules/social_features/social_group/modules/social_group_default_route/social_group_default_route.module
- modules/social_features/social_group/modules/social_group_invite/social_group_invite.module
- phpstan-baseline.neon
I tried installing the Open Social distribution using Composer (v2) exactly as explained in the documentation, but get a lot of notices of type "Undefined Index" during the install process using the classic browser install (see attached file for notices).
These notices seem to be related to one or multiple non-default features I checked, but I haven't figured out which one yet. 
Refactor code to remove such errors.
https://www.drupal.org/project/social/issues/3259107
N.A
We have made installation of Open Social without any reported errors.
N.A
N.A
> Issue #3259107 by Axael, tbsiqueira, navneet0693: Unable to install properly, undefined index warnings.

- modules/custom/alternative_frontpage/src/EventSubscriber/RedirectHomepageSubscriber.php
If multilingual configuration set up not to use langcode prefix, alternative front pages follows to the 404 page.
Use the \Drupal\Core\Url class for generation URLs instead of adding a prefix.
https://www.drupal.org/project/social/issues/3267764
> Issue #3267764 by alex.ksis: Generate a URL instead of adding a prefix.

- composer.json
Reverts goalgorilla/open_social#2815
- https://www.drupal.org/project/social/issues/3269482
> Revert "[Internal] - Remove Social Base theme patch since those changes were released in last theme version."

- .travis.yml
We want to use new drupal_social setup which includes changes from https://github.com/goalgorilla/drupal_social/pull/369 and https://github.com/goalgorilla/open_social_scripts/pull/42
Update to new tag 4.0.0
Not required.
N.A
N.A
N.A
N.A
N.A
> Updated drupal_social version to 4.0.0 and corrected indentation of travis.yml file.

- modules/social_features/social_event/social_event.install
> [Internal] Backport of PR #2849.

- modules/social_features/social_group/modules/social_group_invite/social_group_invite.install
Follow up https://github.com/goalgorilla/open_social/pull/2842
> I just update my Open Social from 11.0.7 to 11.1.0 and when trying to run the update `social_group_invite_update_11001` and I got the following error:
> Missing bundle entity, entity type group_type, entity id flexible_group.
Check if the **Social Flexible Group** module is enabled before adding a new field to the flexible group.
- https://www.drupal.org/project/social/issues/3272437
N/A
N/A
N/A
N/A
N/A
> Issue #3272437 by CurriedN, Ressinel: Check if the Social Flexible Group module is enabled before adding a new field to the flexible group.

- modules/custom/alternative_frontpage/src/EventSubscriber/RedirectHomepageSubscriber.php
- modules/social_features/social_activity/src/EmailTokenServices.php
1. `Argument 5 passed to Drupal\alternative_frontpage\EventSubscriber\RedirectHomepageSubscriber::__construct() must be an instance of Drupal\Core\State\StateIntarface instead of Drupal\Core\State\State.`
2. `TypeError: Argument 1 passed to Drupal\social_activity\EmailTokenServices::__construct() must be an instance of Drupal\Core\Entity\EntityTypeManagerInterface instead of Drupal\webprofiler\Entity\EntityManager.`
1. `State` -> `StateIntarface`
2. `EntityTypeManager` -> `EntityTypeManagerInterface`
1. https://www.drupal.org/project/social/issues/3266571
3. https://www.drupal.org/project/social/issues/3266605
N/A
N/A
N/A
N/A
N/A
> Issue #3266571 by szato, Ressinel: Fix fatal errors

- modules/social_features/social_event/modules/social_event_invite/social_event_invite.links.menu.yml
A CM+ have access to the social event invite settings(/admin/config/opensocial/event-invite), but currently the new dashboard does not include this menu link.
Add the missing menu link.
https://www.drupal.org/project/social/issues/3273311
1. Enable the social_event_invite module
2. As CM+ go to /admin/dashboard
3. Check if there is a link to the social event invite settings page.
*[Required if new feature, and if applicable] If this Pull Request makes visual changes then please include some screenshots that show what …
> Issue #3273311 by nkoporec: AS CM+ I want to have a link to the social_event_invite settings

- modules/social_features/social_group/social_group.module
Removing `'group_type_[group_type]'` fields from the user entities don't work since we are checking for only node entity type in the parent `if()`.
```
/**
* Implements hook_entity_base_field_info_alter().
*/
function social_group_entity_base_field_info_alter(&$fields, EntityTypeInterface $entity_type) {
if ($entity_type->id() === 'node' && isset($fields['groups'])) {
/** @var \Drupal\Core\Field\FieldDefinitionInterface[] $fields */
$fields['groups']
->setLabel(t('Group'))
->setDescription('')
->setSetting('handler', 'social')
->setCardinality(FieldStorageDefinitionInterface::CARDINALITY_UNLIMITED)
->setDisplayOptions('form', [
'type' => 'social_group_selector_widget',
'settings' => [],
'weight' => 16,
])
->setDisplayConfigurable('form', TRUE);
// Remove 'group_type_<group_type>' fields …
```
> Issue #3274572 by Ressinel: Refactor social_group_entity_base_field_info_alter

- composer.json
Socialbase and socialblue have new releases, we need to update the release on our composer.json
Update socialblue to 2.1.5 version
https://www.drupal.org/project/social/issues/3277621
N/A
N/A
N/A
N/A
N/A
> Issue #3277621: Update socialblue dependency to 2.1.5

- modules/custom/activity_basics/activity_basics.module
- modules/custom/activity_creator/activity_creator.module
- modules/custom/activity_creator/src/Plugin/QueueWorker/ActivityWorkerLogger.php
- modules/custom/activity_logger/src/Plugin/QueueWorker/MessageQueueCreator.php
- modules/custom/activity_logger/src/Service/ActivityLoggerFactory.php
- modules/custom/activity_send/modules/activity_send_email/activity_send_email.module
- modules/custom/activity_send/modules/activity_send_email/src/Plugin/AdvancedQueue/JobType/ActivitySendEmailJobType.php
- modules/custom/activity_send/modules/activity_send_email/src/Plugin/QueueWorker/ActivityDigestWorker.php
- modules/custom/activity_send/modules/activity_send_email/src/Plugin/QueueWorker/ActivitySendEmailWorker.php
- modules/custom/activity_viewer/src/Plugin/views/row/ActivityRow.php
- modules/custom/mentions/src/Plugin/Filter/MentionsFilter.php
- modules/custom/social_queue_storage/social_queue_storage.module
- modules/social_features/social_content_block/social_content_block.install
- modules/social_features/social_content_block/social_content_block.module
- modules/social_features/social_content_block/src/ContentBuilder.php
- modules/social_features/social_event/modules/social_event_addtocal/social_event_addtocal.module
- modules/social_features/social_event/modules/social_event_managers/src/Plugin/views/field/SocialEventManagersViewsBulkOperationsBulkForm.php
- modules/social_features/social_event/social_event.install
- modules/social_features/social_follow_taxonomy/modules/social_follow_tag/social_follow_tag.module
Backport of PR #2917 to Open Social 11.1.x
This PR contains the same changes as in the original PR, but it doesn't contains `phpstan-baseline.neon` changes which was causing the backporting conflict.
> Issue #3278347 by navneet0693: Junk plugin data can crash activity entity related view.

- modules/social_features/social_core/assets/js/invite-form.js
- modules/social_features/social_core/social_core.libraries.yml
- modules/social_features/social_core/src/Form/InviteEmailBaseForm.php
In the invite forms we were able to fill a non existing username. If we try to send an invite, we will get a fatal error.
The solution is to create validation on the front-end side to allow users fill only existing usernames or emails.
Dupal.org issue: https://www.drupal.org/project/social/issues/3278471
Jira ticket: https://getopensocial.atlassian.net/browse/YANG-7526
Added front-end validation for the invite forms to avoid mistakes.
> Issue #3278471 by alex.ksis: Do now allow to fill non existing username.

- modules/social_features/social_event/modules/social_event_managers/src/Plugin/views/field/SocialEventManagersViewsBulkOperationsBulkForm.php
- modules/social_features/social_group/modules/social_group_invite/src/Plugin/views/field/SocialGroupInviteViewsBulkOperationsBulkForm.php
- modules/social_features/social_group/src/Plugin/views/field/SocialGroupViewsBulkOperationsBulkForm.php
When using bulk operation for event/group membership page shows errors (only when trying to execute an action for the first time):
`Notice: Undefined index: bulk_form_keys in Drupal\views_bulk_operations\Plugin\views\field\ViewsBulkOperationsBulkForm->viewsFormSubmit() (line 926 of modules/contrib/views_bulk_operations/src/Plugin/views/field/ViewsBulkOperationsBulkForm.php).`
`Warning: Invalid argument supplied for foreach() in Drupal\views_bulk_operations\Plugin\views\field\ViewsBulkOperationsBulkForm->viewsFormSubmit() (line 926 of modules/contrib/views_bulk_operations/src/Plugin/views/field/ViewsBulkOperationsBulkForm.php).`
Add fixes for Open Social Views Bulk Operations field plugins.
- https://www.drupal.org/project/social/issues/3279904
N/A
N/A
N/A
N/A
N/A
> Issue #3279904 by Ressinel: Notice: Undefined index: bulk_form_keys

- modules/social_features/social_group/social_group.module
On the `Manage members` page, we have actions like `Edit`, `Delete`, `View`, etc. As we can click on the member's avatar or name, so the `View` action actually not needed. Also, when we click on `View` it does not work and redirects back to the `Manage members` page.
Remove the `View` action from the `Manage members` page.
- https://www.drupal.org/project/social/issues/3272028
- https://getopensocial.atlassian.net/browse/YANG-1680
N/A
N/A
N/A
N/A
> Issue #3272028 by tBKoT: Removes the 'View' action on the 'Manage members' page

- modules/social_features/social_core/src/Form/InviteEmailBaseForm.php
- modules/social_features/social_event/modules/social_event_invite/src/Form/EnrollInviteEmailForm.php
- phpstan-baseline.neon
In Open Social 11 was released a new feature that allows users to invite other users to the event or share it. However, if an anonymous user will enroll in the event all other anonymous users will automatically be able to invite. 
Disable access for the AN users to the event invite route
- https://www.drupal.org/project/social/issues/3276049
- https://getopensocial.atlassian.net/browse/YANG-7623
N/A
N/A
Anonymous users should not have the possibility to invite other users to the event.
N/A
N/A
> Issue #3276049 by tBKoT: Disallow AN users inviting to the event

- composer.json
Socialbase and socialblue have new releases, we need to update the release on our composer.json
Update socialblue to 2.2.2 version
- https://www.drupal.org/project/social/issues/3279897
N/A
N/A
The socialblue theme was updated to 2.0.1
N/A
N/A
> Issue #3279897: Update socialblue dependency to 2.2.2

- modules/custom/social_gdpr/social_gdpr.links.menu.yml
The menu link for route entity.informblock.collection is missing from the new site manager dashboard.
Add the missing link.
https://www.drupal.org/project/social/issues/3278356
1. Enable the social_gdpr
2. Go to the new dashboard located at /admin/dashboard
3. There should be a link to Data usage explanation page
*[Required if new feature, and if applicable] If this Pull Request makes visual changes then please include some screenshots that show what has changed here. A before and after screenshot helps the reviewer …
> Issue #3278356 by nkoporec: Missing data policy explanation link in the new dashboard

- tests/behat/features/capabilities/embed/embed-consent.feature
- tests/behat/features/capabilities/embed/embed.feature
Temporary comment step in behat test since it will fail because of the Embed module new release https://www.drupal.org/project/embed/releases/8.x-1.5
Changes: https://git.drupalcode.org/project/embed/-/commit/89b249e4da8f5b39fdfa3e97960107c850427469
N/A
N/A
N/A
N/A
N/A
N/A
> [Internal] Fix behat test after new release for the Embed module

- composer.json
Update socialblue version to 2.2.3
Update socialblue version to 2.2.3
https://www.drupal.org/project/social/issues/3283306
N/A
N/A
N/A
N/A
N/A
> Issue #3283306: Update socialblue version to 2.2.3

- composer.json
The patch is not applied.
We need to update that patch because of these change in Drupal 9.3.x https://git.drupalcode.org/project/drupal/-/commit/5a9f90aab04af4f089e80d71b3793448ff50bc0e
- https://www.drupal.org/project/drupal/issues/3123561
N/A
N/A
N/A
N/A
N/A
> [Internal] Update necessary patch

- .github/mergeable.yml
Open Social follows certain conventions in order to maintain the quality of code and maintain PRs. Overlooking of these conventions like proper commit messages has impacted us a lot in past. We want to automate this to help developers adopt them while raising PR.
Read more at: https://github.com/mergeability/mergeable
We wanted our contributors to follow proper conventions while creating a pull request. These conventions are like meaningful commit messages, proper labels, etc. This helps in maintaining code quality as well as provides more information for reviews and maintainers at first glance. These conventions are now adopted with help of mergeable tools which will provide helpful suggestions to authors of PR. The tool also prevents merging if the conventions/recommendations by it are …
> Internal: Added mergeables tool.

- .github/dependabot.yml
- composer.json
- modules/social_features/social_group/modules/social_group_invite/social_group_invite.module
- modules/social_features/social_group/modules/social_group_invite/src/Form/SocialBulkGroupInvitation.php
- tests/composer.json
Currently, we are maintaining dev/test dependencies at different places.
https://github.com/goalgorilla/open_social/blob/main/composer.json#L224
https://github.com/goalgorilla/open_social/blob/main/tests/composer.json#L9
https://github.com/goalgorilla/open_social_docker/blob/master/composer.json#L30
https://github.com/goalgorilla/drupal_social/blob/master/composer.json#L30
This made it difficult to update the dependencies and also to maintain them in different places. The dependencies version is the same across our repositories. This lead to a lot of time consumption of doing the same thing in different places, also because these repositories are coupled tightly, outdated repository lead to the failure of others.
Our inspiration comes from https://packagist.org/packages/drupal/core-dev . …
> Internal: Replaced dev-dependencies with goalgoriall/open_social_dev.

- tests/composer.json
Current quality checks are breaking due to missing config option on `tests/composer.json` file
Add missing `config` options
N/A
N/A
N/A
N/A
N/A
N/A
> Internal: Add necessary test config option on composer.json for quality checks

- modules/social_features/social_follow_user/config/install/social_follow_user.settings.yml
- modules/social_features/social_follow_user/social_follow_user.info.yml
- modules/social_features/social_profile/modules/social_profile_preview/assets/js/social_profile_preview.js
- tests/behat/features/capabilities/follow-users/follow-users.feature
Add test coverage of the "Follow user" feature to make sure that it works as expected and won't cause any issues
- Add behat test to cover basic Follow user functionality that was already completed.
- Make the module not hidden, so it can be enabled from UI (can be still Experimental)
- Also, includes a small improvement for the preview modal window
- https://www.drupal.org/project/social/issues/3285718
- https://getopensocial.atlassian.net/browse/YANG-7603
- https://getopensocial.atlassian.net/browse/YANG-7922
N/A
Added test coverage of the "Follow user" feature
> Issue #3285718 by SV: Add behat tests for the "Follow user" feature

- modules/social_features/social_event/modules/social_event_managers/config/optional/message.template.member_added_by_event_organiser.yml
- modules/social_features/social_event/modules/social_event_managers/config/update/social_event_managers_update_11101.yml
- modules/social_features/social_event/modules/social_event_managers/social_event_managers.install
On the user settings page under E-mail notifications the "Message to me" section contains the `A organizer added me to a Event` setting. This is grammatically incorrect, it should be "An organizer". Additionally, this is the only sentence on the page where we capitalise a content type.
Change the string to `An organizer added me to an event`.
- https://www.drupal.org/project/social/issues/3092963
N/A
N/A
N/A
N/A
N/A
> Issue #3092963 by mikeegoulding: Added to event notification setting text is inconsistent and incorrect

- .github/PULL_REQUEST_TEMPLATE.md
The definition of done didn't contain a dedicated item to tests.
Add the missing definition of done test item.
N/A
N/A
N/A
N/A
N/A
N/A
> Internal: Added the addition of tests as an item of the definition of done

- .github/workflows/behat-stability-1-basic-installation.yml
- .github/workflows/behat-stability-1-upgrade-path.yml
- .github/workflows/behat-stability-1.yml
- .github/workflows/behat-stability-2.yml
- .github/workflows/behat-stability-3.yml
- .github/workflows/behat-stability-4.yml
We added some granuality to behat github actions check in https://github.com/goalgorilla/open_social/commit/01d26de469d7d43da1bc3cb7f8834884cda84f5e to get trigerred on limited events. This was done in order to keep our "Github actions" queue under control.
But this produced some inconsistent results.
For example,
If there are two pull requests open.
1. PR 1 is directly put in "Ready for Review" status while opening itself.
2. PR 2 is in draft status.
**_Behat checks:_**
1. Behat checks will not trigger on PR 1.
2. Behat checks will trigger on PR 2 once PR is marked as "Ready for Review"
**_Optimistic scenario_**
1. Behat checks will trigger on both if more commits are added after being in "Ready for review" status.
Now, we want to make sure that Behat checks trigger on all the pull …
> Internal: Allow behat github actions check to trigger on all PR events.

- .github/workflows/behat-stability-1.yml
- tests/behat/features/bootstrap/SocialDrupalContext.php
- tests/behat/features/capabilities/install/install.feature
Follow up https://github.com/goalgorilla/open_social/pull/2242
Even though we tend to stick to Drush there is always also the opportunity to install Open Social to the browser, however, we are lacking a browser test here.
Add a new install step to re-install through the Browser, to see if that helps.
It's already a closed issue we're re-using to assign it to a discussion there:
- https://www.drupal.org/project/social/issues/3196407
N/A
[Internal] We are now running a behat test to check if we can (re)install Open Social through the browser including optional modules.
N/A
N/A
> Issue #3196407: Update install through web test

- modules/custom/activity_viewer/src/Plugin/views/filter/ActivityPostVisibilityAccess.php
- modules/social_features/social_group/social_group.module
Group Content, eg topic and event nodes, is created in public groups, but anonymous users do not have access to view such activities. See more info https://www.drupal.org/project/social/issues/3267522
Make sure that we also add all public groups to groups unique to provide the possibility for anonymous users to see public group's activity
- https://www.drupal.org/project/social/issues/3267522
N/A
N/A
TBD
N/A
N/A
> Issue #3267522 by Ressinel, epapaniko: Anonymous users cannot view activities related to topics or events on public group streams

- modules/social_features/social_comment/social_comment.install
The following errors occur when running the update script of social_comment on a site where the 'views.view.comment' View was removed.
```
>  [notice] Update started: social_comment_update_11202
>  [warning] array_keys() expects parameter 1 to be array, null given social_comment.install:173
>  [warning] array_search() expects parameter 2 to be array, null given social_comment.install:173
>  [warning] array_slice() expects parameter 1 to be array, null given social_comment.install:177
>  [error]  Unsupported operand types 
```
Add defensive check.
- https://www.drupal.org/project/social/issues/3292235
N/A
N/A
N/A
N/A
N/A
> Issue #3292235 by sutharsan, Ressinel: Update fails when views.view.comment does not exist

- modules/social_features/social_group/social_group.links.action.yml
The group membership page shows an assertion error if the Group Invitation plugin is not installed:
`AssertionError: assert(\Drupal::service('cache_contexts_manager')->assertValidTokens($cache_contexts)) in assert() (line 31 of core/lib/Drupal/Core/Cache/Cache.php).`
The old caching tags were used in the action links. Update group and group.role to the route.group cache tag, which should be valid for any routes using the group parameter. Add also the group permission related context, as the link may also depend on that. BTW the group change record of the cache contexts: https://www.drupal.org/node/3011700
- https://www.drupal.org/project/social/issues/3260291
N/A
N/A
TBD
N/A
N/A
> Issue #3260291 by sayco: Assertion error on group membership page

- modules/custom/activity_viewer/src/Plugin/views/filter/ActivityFilterPersonalisedHomepage.php
When showing the personalized stream block on a page it should show all the content relevant to a person. There are some checks to see if the user has access to nodes but does not work for the usecase when content is not in a group and posted to the community or public.
It will try to make some joins with the group_content_field_data but doesn't take into account that entity_ids are not unique. For example a membership can be entity_id 5 but a topic content can also be entity_id 5. Therefore it can think the content is within a group and remove it from the list and thus missing from the activity stream.
Change the query to only contain the content nodes as we don't show invitations or membership in our stream activity.
https://www.drupal.org/project/social/issues/3253268
It can be hard to …
> Issue #3253268 by robertragas: change the personalised activity stream query to make sure we filter with the correct group content data

- modules/social_features/social_user/social_user.tokens.inc
When e-mailing the event enrollees, the token [social_user:recipient] is never transformed into the actual recipient name.
Inside social_user_token(), there is a condition that the message data needs to be an instance of Message entity, but if you look and the actual job, we pass in a message string and not the entire entitity.
https://www.drupal.org/project/social/issues/3273700
1. Create an event and add a user
2. Use 'Email selected enrollees' action
3. In the message use the [social_user:recipient] token
4. Check …
> Issue #3273700 by nkoporec: The [social_user:recipient] token is not transforming correctly

- modules/custom/entity_access_by_field/entity_access_by_field.post_update.php
In this PR #2872, we added the post update to clear search indexes and reindex items again, but it fails when we have a lot of content that should be reindexed.
Do not reindex items and let cron do this job.
https://www.drupal.org/project/social/issues/3300210
N/A
N/A
Re-indexing is necessary due to updates in search index.
N/A
N/A
> Issue #3300210 by tBKoT: Fix broken post update with search re-index

- modules/social_features/social_event/src/Form/EnrollActionForm.php
If the user was invited to an event, and he enrolls for this event not from the `/event-invites` page, but from the event itself, then this event disappears from the `/event-invites` list, but the indicator that there are new invitations to the event still remains and it is almost impossible to get rid of it.
If the user was invited to an event, and he enrolls for this event not from the /event-invites page, but from the event itself, then we also need to mark this enrollment as accepted, otherwise, the list of invites will be empty, but the notification center will say that there are new invites.
- https://www.drupal.org/project/social/issues/3301083
- https://getopensocial.atlassian.net/browse/PROD-20238
NONE.
*[Required if new feature, and if applicable] A short summary of the changes …
> Issue #3301083 by rolki: Event invites do not disappear from the notification center

- .github/workflows/behat-stability-1.yml
- composer.json
Update address module due to new release.
https://github.com/commerceguys/addressing/releases/tag/v1.4.0 was released yesterday and it breaks compatibility with the address module.
Also, https://www.drupal.org/project/address/releases/8.x-1.11 was released fixing https://www.drupal.org/project/address/issues/3302484 which is now required.
Update composer.json
N.A
N.A
N.A
N.A
N.A
N.A
> Internal: Update the address module to new version.

- .github/workflows/behat-stability-1-basic-installation.yml
- .github/workflows/behat-stability-1-upgrade-path.yml
- .github/workflows/behat-stability-1.yml
- .github/workflows/behat-stability-2.yml
- .github/workflows/behat-stability-3.yml
- .github/workflows/behat-stability-4.yml
A new version of drupal_social has been released, we need to update the github workflows to the new version.
Set 6.1.0 as version for drupal_social in the github workflows.
N/A
N/A
N/A
N/A
N/A
N/A
N/A
> Internal: Updated drupal_social to 6.1.0 in the github workflows

- modules/custom/ginvite/ginvite.module
When trying to delete accounts, Open Social would throw an error that the `invitee_mail` cannot be null. This was caused by the social_chat module, that recreated a deleted user, for referencing purposes.
By checking if the user has an email address, we can mitigate this error. This is the same way the contrib module handles it.
* https://getopensocial.atlassian.net/browse/PROD-21700
* https://www.drupal.org/project/social/issues/3305437
*[Required]
*[Required if new feature, and if applicable] A short summary of the changes that were made that can be …
> Don't check for invitations when users has no email (anonymous)

- modules/social_features/social_event/modules/social_event_managers/social_event_managers.module
- phpstan-baseline.neon
When a person is directly added to a event, they do not receive a notification via email.
There is a message template ` member_added_by_event_organiser` that should be sent to the user, but this never happens. The issue is that in `ActivitySendEmailJobType.php `we always check if the recipient has access to the entity, before sending out an email. This is not the case, when adding users directly to the event, since the owner of the event enrollment is not the recipient but the event manager, so the condition evaluates to false
We need to allow view access to event enrollment entity if the user is a recipient, since it make sense that the user has access to its own event enrollment.
https://www.drupal.org/project/social/issues/3305919
*[Required if applicable] Paste a link to the …
> Issue #3305919 by nkoporec: User does not receive email notification when added directly to a event

- modules/social_features/social_event/modules/social_event_managers/social_event_managers.module
- phpstan-baseline.neon
Reverts goalgorilla/open_social#3078
Due to lack of documentation in code and other remarks, we would like to fix those things before merging this to main.
> Revert "Issue #3305919 by nkoporec: User does not receive email notification when added directly to a event"

- composer.json
Update socialblue to 2.2.5
Update socialblue to 2.2.5
N/A
N/A
N/A
N/A
N/A
N/A
N/A
> Update socialblue dependency to 2.2.5

- modules/social_features/social_footer/social_footer.info.yml
project key on social_footer info.yml file creates an issue with our translation tool.
Remove the extra key
https://www.drupal.org/project/social/issues/3310016
N/A
N/A
Remove unused **_project_** key from social_footer.info.yml file
N/A
N/A
> Issue #3310016: Remove "project" key from social_footer info.yml file

- tests/behat/behat.yml
- tests/behat/features/bootstrap/CKEditorContext.php
- tests/behat/features/bootstrap/FeatureContext.php
- tests/behat/features/bootstrap/GroupContext.php
- tests/behat/features/bootstrap/GroupTrait.php
- tests/behat/features/bootstrap/PostContext.php
- tests/behat/features/bootstrap/ThemeContext.php
We have a lot of functionality in FeatureContext or other non-descript contexts, this makes it difficult to see at a glance what functionality is available or find specific steps.
Move functionality around a specific topic (e.g. group or users) into a specific context.
Internal change no ticket
> Internal: Refactor behat contexts

- tests/behat/behat.yml
- tests/behat/features/bootstrap/BookContext.php
- tests/behat/features/bootstrap/ModuleContext.php
- tests/behat/features/bootstrap/SocialDrupalContext.php
- tests/behat/features/capabilities/book/book-create.feature
Our Behat tests are written more like a PHPUnit test than a scenario that is discussible with non-technical stakeholders. In addition we have some brittleness (partly because of this) that causes tests to randomly fail.
Rewrite flaky tests with inspiration from https://medium.com/@djphenaproxima/ive-been-using-behat-wrong-this-whole-time-ced6efd04e72 Make the scenario steps more descriptive and hide the nitty gritty in specialised contexts.
Internal change, no issue
> Internal: refactor book create test

- tests/behat/behat.yml
- tests/behat/features/bootstrap/TopicContext.php
- tests/behat/features/capabilities/contentmanagement/unpublished.feature
Our test is written like a PHPUnit test and the Behat .feature is not useful to stakeholders at all. Because we use individual steps, the test is also more brittle than it needs to be.
We use the new learnings to make the scenario more succinct so it's easier to understand for everyone and introduce a TopicContext to actually do the heavy lifting.
This removes some testing of the verified role since this is more approprate in `topic.feature` and was also duplicated there.
> Internal: Rewrite unpublished.feature

- composer.json
We are currently requiring an outdates Drupal core version. https://www.drupal.org/sa-core-2022-016
Updated the required version to drupal/core-recommeneded 9.3.22
This change needs to be backported to 11.3.x Open Social version 
https://git.drupalcode.org/project/drupal/-/commits/9.3.x
https://www.drupal.org/project/social/issues/3312530
N/A
Drupal core is now updated to 9.3.22
N/A
N/A
> Internal: Update drupal/core-recommended package to the latest released version

- modules/social_features/social_group/modules/social_group_request/social_group_request.module
**Error:**
Call to a member function getName() on null in social_group_request_preprocess_group() (line 234 of /app/html/profiles/contrib/social/modules/social_features/social_group/modules/social_group_request/social_group_request.module)
**Error is triggered:**
- If you want to reindex “social all”
- if you want to reindex “social groups”
- When group landing page needs to be rendered
**What are consequences of this issue:**
- pop up search autocomplete suggestions are not working
- Empty “all” search results
- WSOD on “groups” search results
- WSOD in group landing page
**Reasons for issue:**
- If taxonomy term is deleted, but it is still referenced in field_group_type (Group > Basic information > Type) getName() method is called on null causing the consequences listed above
Add …
> Issue #3254715 by zanvidmar: Group preprocess error breaks search index and group rendering if referenced group type does not exist

- modules/social_features/social_editor/config/install/editor.editor.mail_html.yml
- modules/social_features/social_editor/config/install/filter.format.mail_html.yml
- modules/social_features/social_editor/config/update/social_editor_update_9000.yml
- modules/social_features/social_editor/social_editor.install
The mail_html text format is very strict on buttons that it provides. For example if we have an arabic text which is read from right to left so naturally the sentence starts aligned to the right, not the left like in English, currently there is no way to align it to the right in this text format, which causes issues.
Add the alignment buttons to mail_html format.
https://www.drupal.org/project/social/issues/3311126
1. Install Open Social
2. Create a flexible group
3. In the 'Manage members', select members and click …
> Issue #3311126 by nkoporec: Add alignment buttons to mail_html text format

- modules/custom/activity_basics/src/Plugin/ActivityContext/GroupContentInMyGroupActivityContext.php
When a user requests a group membership, the group managers/admins don't receive any notifications about it, even if the email settings are set to immediately.
The issue is that, when a user creates a group, it receives a Group Admin role, but the code determining who should receive membership request notifications only sends notifications to users with group manager roles. We need to add group admins to the list of recipients.
https://www.drupal.org/project/social/issues/3314436
1. Create a new flexible group with …
> Issue #3314436 by nkoporec: Group managers doesn't receive notifications about group membership requests

- modules/social_features/social_core/social_core.module
In the user stream page (user/*/stream) I have an error saying
Warning: Illegal string offset '#markup' in social_core_preprocess_block() (line 408 of profiles/contrib/social/modules/social_features/social_core/social_core.module).
Make sure that '$variables['label']['#markup']' exists as a valid array_key/array
https://www.drupal.org/project/social/issues/3314911
N/A
N/A
N/A
N/A
N/A
> Issue #3314911 by immaculatexavier, pflora, apaderno, dco, tbsiqueira: Warning: Illegal string offset '#markup'

- .github/workflows/behat.yml
- composer.json
- modules/social_features/social_comment/src/Entity/Access/CommentQueryAccessHandler.php
- modules/social_features/social_core/src/SocialCoreServiceProvider.php
- modules/social_features/social_embed/src/Plugin/Filter/SocialEmbedConvertUrlToEmbedFilter.php
- modules/social_features/social_event/modules/social_event_managers/social_event_managers.module
- modules/social_features/social_event/modules/social_event_managers/src/Form/SocialEventManagersAddEnrolleeForm.php
- modules/social_features/social_group/social_group.module
- modules/social_features/social_group/src/SetGroupsForNodeService.php
- modules/social_features/social_post/social_post.module
- phpstan-baseline.neon
Update latest Drupal 9.4.x.
1. Added changes according to https://www.drupal.org/node/3000490.
2. Added changes according to https://www.drupal.org/node/2948698.
3. Removed patch from  https://www.drupal.org/project/bootstrap/issues/3021413 as it is moved to socialbase 2.4.0 now.
4. Remove obsolete patches from socialbase and socialblue.
5. PHPStan baseline is updated to remove errors.
6. Added new SocialBlue theme 2.4.0
7. Removed https://git.drupalcode.org/project/drupal/-/merge_requests/1215.patch
8. Re-rolled patch from Drupal core issue #2998390
9. Updated drupal/core* to ~9.4.8
https://www.drupal.org/project/social/issues/3314649
1. https://www.drupal.org/project/bootstrap/issues/3209773
2. https://www.drupal.org/project/bootstrap/issues/3021413
3. …
> Issue #3314649 by navneet0693,tbsiqueira: Make Open Social compatible to Drupal 9.4

- modules/custom/social_font/social_font.info.yml
- modules/social_features/social_activity/social_activity.info.yml
See the Problem/Motivation section at https://www.drupal.org/project/social/issues/2962184
Remove the dependency on `social_font` from `social_activity`.
- https://www.drupal.org/project/social/issues/2962184
N/A
N/A
N/A
N/A
N/A
> Issue #2962184 by jaapjan, mparker17, Kolin, SocialNicheGuru, Ressinel: social_activity does not need to depend on social_font

- modules/social_features/social_event/social_event.install
The update script `social_event_update_10306()` does not finish if the field `field_event_enable_enrollment` is not present or empty. This situation was encountered while updating from **Open Social** `10.2.2` to `11.3.3`.
Also update the `current` counter when not processing the entity.
- https://www.drupal.org/project/social/issues/3291657
N/A
```
...
> [info] Configuration core.entity_view_display.profile.profile.teaser has been successfully updated.
>  [notice] Update completed: social_profile_update_11301
>  [notice] Update started: social_event_update_10306
...
```
N/A
Fixed issue where social_event_update_10306 does not finish.
N/A
N/A
> Issue #3291657 by Sutharsan, Ressinel: social_event_update_10306 does not finish

- social.info.yml
Update outdated version on social.info.yml
Update outdated version on social.info.yml
N/A
N/A
N/A
N/A
N/A
N/A
N/A
> Update info file to 11.5.x-dev

- modules/social_features/social_profile/social_profile.module
Username is not showing on admin/people page, this is affecting only Open Social 11.5.x and above.
In PR #3103, we removed the hook_theme() which caused the username to disappear.
See: https://github.com/goalgorilla/open_social/pull/3103#issuecomment-1284277075
Add the hook_theme back.
https://www.drupal.org/project/social/issues/3316226
N.A
**Before**
**After**
N.A
N.A
N.A
> Issue #3316226 by navneet0693, tbsiqueira: Username not showing on admin/people page

- composer.json
Socialblue has new release versions, we need to update them on all active Open Social versions.
Socialblue has new release versions, we need to update them on all active Open Social versions.
https://www.drupal.org/project/social/issues/3316887
11.5.x PR: https://github.com/goalgorilla/open_social/pull/3166
11.3.x PR: https://github.com/goalgorilla/open_social/pull/3168
N/A
N/A
N/A
N/A
N/A
> Issue #3316887: Update socialblue version on 11.4.x

- composer.json
Socialblue has new release versions, we need to update them on all active Open Social versions.
Socialblue has new release versions, we need to update them on all active Open Social versions.
https://www.drupal.org/project/social/issues/3316887
11.4.x PR: https://github.com/goalgorilla/open_social/pull/3167
11.5.x PR: https://github.com/goalgorilla/open_social/pull/3166
N/A
N/A
N/A
N/A
N/A
> Issue #3316887: Update socialblue version on 11.3.x

- composer.json
Socialblue has new release versions, we need to update them on all active Open Social versions.
Socialblue has new release versions, we need to update them on all active Open Social versions.
https://www.drupal.org/project/social/issues/3316887
11.4.x PR: https://github.com/goalgorilla/open_social/pull/3167
11.3.x PR: https://github.com/goalgorilla/open_social/pull/3168
N/A
N/A
N/A
N/A
N/A
> Issue #3316887: Update socialblue version on main ( 11.5.x )

- modules/social_features/social_group/modules/social_group_invite/src/Form/SocialBulkGroupInvitation.php
- phpstan-baseline.neon
Currently it is possible to send membership invites to users who is already group members. If the member try to accept the invite he got "access denie" (which is correct as he is a member).
- Fix typo in `modules/social_features/social_group/modules/social_group_invite/src/Form/SocialBulkGroupInvitation.php`
- https://www.drupal.org/project/social/issues/3313745
- https://getopensocial.atlassian.net/browse/PROD-22090
n/a
n/a
*Prevent sending membership invites to users who are already group members.*
n/a
n/a
> Issue #3313745 by vnech: Prevent unexpected sending group membership invites

- modules/custom/activity_creator/activity.page.inc
- phpstan-baseline.neon
PHPStan checks were failing since https://github.com/goalgorilla/open_social/pull/3129
Update phpstan-baseline.
N.A
N.A
N.A
N.A
N.A
N.A
> Internal: Update phpstan baseline.

- composer.json
GraphQL has a newer 4.3 version but there is currently an issue with tests on 4.3 due to an addition to graphql module here: 
https://github.com/drupal-graphql/graphql/blob/8.x-4.x/tests/src/Traits/QueryResultAssertionTrait.php#L107
We added a patch to remove a new assertion introduced on 4.3 version, this was necessary so our tests could still pass.
The patched solution will be implemented later on, following up our work already started on https://github.com/goalgorilla/open_social/pull/2770
We decided to not move forward with https://github.com/goalgorilla/open_social/pull/2770 because we don't think that the additions there are production ready.
https://www.drupal.org/project/social/issues/3191622
This issue is just a placeholder, please don't close it after this PR is merged and …
> Issue #3191622 by tbsiqueira, Kingdutch: Update graphql version to 4.3 from 4.1

- composer.json
Search API has a new version 1.27.0
Update search api to 1.27.0
N/A
N/A
N/A
N/A
N/A
N/A
> Internal: Update search_api to version 1.27.0

- tests/composer.json
If applying a patch fails for any reason composer is skipping the failure, this is not good since we need to know if we have any issues while applying patches.
Since we are using [cweagans/composer-patches](https://github.com/cweagans/composer-patches) to manage patches, we could force exiting on failed patch apply using `"composer-exit-on-patch-failure": true` on composer.json `"extra"` section like [suggested here](https://github.com/cweagans/composer-patches#error-handling) 
This is going to be added, for now, only on our tests/composer.json so it fails during our pipelines
N/A
N/A
N/A
N/A
N/A
N/A
> Internal: Force composer exit on patch failure for our tests/composer.json

- composer.json
Socialblue theme is deprecated since there are two now releases for version 2.3.x and 2.4.x
Update socialblue from 2.3.3 to [2.3.4](https://www.drupal.org/project/socialblue/releases/2.3.4) on Open Social 11.4.x
https://www.drupal.org/project/social/issues/3321141
https://www.drupal.org/project/socialblue/issues/3321125
N/A
https://www.drupal.org/project/socialblue/releases/2.3.4
N/A
N/A
> Issue #3321141: Update socialblue to 2.3.4 on Open Social 11.4.x

- composer.json
Socialblue theme is deprecated since there are two now releases for version 2.3.x and 2.4.x
Update socialblue from 2.4.1 to [2.4.2](https://www.drupal.org/project/socialblue/releases/2.4.2) on Open Social 11.5.x/main
https://www.drupal.org/project/social/issues/3321141
https://www.drupal.org/project/socialblue/issues/3321125
N/A
https://www.drupal.org/project/socialblue/releases/2.4.2
N/A
N/A
> Issue #3321141: Update socialblue to 2.4.2 version on Open social 11.5.x/main

- modules/social_features/social_event/social_event.module
- tests/behat/features/capabilities/event/show-hide-eventenrollments.feature
Needs to cover "show/hide enrolees" feature with `Behat` tests (PR - https://github.com/goalgorilla/open_social/pull/3084)
Add `behat` test coverage for "show/hide enrolees" feature
- https://www.drupal.org/project/social/issues/3320715
- https://getopensocial.atlassian.net/browse/PROD-22857
n/a
n/a
n/a
*Add `behat` test coverage for "show/hide enrolees" feature.*
n/a
n/a
> Issue #3320715 by vnech: Add behat test for "show/hide enrolees" feature

- composer.json
We are currently locking socialblue requirements, meaning that if there is a new socialblue release we need a new Open Social release. This happened because in the past releases were not well coordinated and bugs happened due to unmatching dependencies between socialbase and socialblue.
Change Open Social composer.json to require socialblue like this: `~MAJOR.MINOR.PATCH` Example: `~2.4.2` or `~2.3.3`. Requiring it with `~` will guarantee that only patches versions are updated.
This PR affects 11.4.x only
https://www.drupal.org/project/social/issues/3324332
https://www.drupal.org/project/socialblue/issues/3324329
N/A
Socialblue now will be automatically required to the latest patch version for each min version.
N/A
N/A
> Issue #3324332: Change socialblue requirement on composer.json for 11.4.x

- composer.json
We are currently locking socialblue requirements, meaning that if there is a new socialblue release we need a new Open Social release. This happened because in the past releases were not well coordinated and bugs happened due to unmatching dependencies between socialbase and socialblue.
Change Open Social composer.json to require socialblue like this: `~MAJOR.MINOR.PATCH` Example: `~2.4.2` or `~2.3.3`. Requiring it with `~` will guarantee that only patches versions are updated.
This PR affects main/11.5.x only
https://www.drupal.org/project/social/issues/3324332
https://www.drupal.org/project/socialblue/issues/3324329
N/A
Socialblue now will be automatically required to the latest patch version for each min version.
N/A
N/A
> Issue #3324332: Change socialblue requirement on composer.json for main/11.5.x

- modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
- modules/social_features/social_private_message/social_private_message.module
In a previous commit we've started using the `$entity` for an entity view hook but PHPStan doesn't know this is a specific entity class rather than just any entity class.
We add an assert because we only expect that entity class to be provided for a properly named hook, as per Drupal's hook system.
We also slightly rewrite flexible_group code to get the proper type for our account id which is needed until
https://www.drupal.org/project/drupal/issues/3324733 is fixed.
No issue
> Internal: Fix PHPStan issues in main

- modules/social_features/social_profile/src/SocialProfileTagService.php
Unpublished tags are shown on profile edit page.
- The tag field in the profile uses profile_tags vocabulary.
- The terms on profile entity are fetched by https://github.com/goalgorilla/open_social/blob/main/modules/social_features/social_profile/src/SocialProfileTagService.php in functions https://github.com/goalgorilla/open_social/blob/main/modules/social_features/social_profile/src/SocialProfileTagService.php#L87 and https://github.com/goalgorilla/open_social/blob/main/modules/social_features/social_profile/src/SocialProfileTagService.php#L118
- These functions internally call the function https://github.com/goalgorilla/open_social/blob/main/modules/social_features/social_profile/src/SocialProfileTagService.php#L222 which was not checking if the term is published or not.
- This check …
> Issue #3324951 by navneet0693: Unpublished Profile Tags are available for selection in Profile form.

- tests/behat/features/bootstrap/EventContext.php
- tests/behat/features/bootstrap/FeatureContext.php
- tests/behat/features/capabilities/event/eventenrollment-manage.feature
The test was randomly failing in our CI and it was unclear why.
We use the opportunity to clean up the test and divide it into a few different scenarios. This should give us better insights into why things are failing and hopefully makes the test more robust too.
Internal test change no issue
> Internal: Rewrite event enrollment manage test

- .tugboat/config.yml
Tugboat prefers updating over recreating (since it's faster). However, our composer command did not allow updates of dependencies which meant that the Tugboat preview update fails if we update our dependencies.
This can cause Tugboat to fail for dependabot but also when we finally merge our dependency update to main, which then causes Tugboat to fail on all PRs (which use the main preview as a base to save disk space).
We change our composer require to allow updating dependencies so that this scenario no longer occurs.
> Internal: Fix tugboat failing for updated dependencies

- modules/social_features/social_embed/src/Plugin/Filter/SocialEmbedConvertUrlToEmbedFilter.php
- modules/social_features/social_event/social_event.post_update.php
- modules/social_features/social_group/social_group.module
- modules/social_features/social_group/src/Form/SocialGroupSettings.php
- modules/social_features/social_group/src/SetGroupsForNodeService.php
- modules/social_features/social_group/src/SocialGroupHelperService.php
- modules/social_features/social_profile/modules/social_profile_organization_tag/social_profile_organization_tag.module
- modules/social_features/social_user/src/Plugin/Block/AccountHeaderBlock.php
- phpstan-baseline.neon
- tests/composer.json
We try to fix as many new issues as we can but try to avoid things that
may change code that isn't quite clear.
Additionally we don't touch anything that would just change the location
in the baseline but wouldn't necessarily add to the baseline.
Please remove the Debug: commit and make sure `open_social_dev:main` is updated.
> Internal: Update to PHPStan 1.9.2

- modules/social_features/social_group/social_group.module
PHPStan checks are failing on `main` branch.
```
0/1061 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
440/1061 [▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░]  41%
760/1061 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░]  71%
1061/1061 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
Error: Negated boolean expression is always false.
Error: Process completed with exit code 1.
```
Refactor the code as per PHPStan feedbacks.
N.A
N.A
N.A
N.A
N.A
N.A
> Internal: Removed unrequired if condition as per PHPStan analysis results.

- modules/social_features/social_tagging/src/Form/SocialTaggingSettingsForm.php
Currently site manager can't reorder categories (parent terms) in "Content tags" vocabulary.
Reordering categories can be useful for some business needs -  underline some prioritised tags etc.
Add a new "Categories reordering" setting item to "Tag settings".
- https://www.drupal.org/project/social/issues/3304774
- https://getopensocial.atlassian.net/browse/PROD-21848
N/A
A new setting in "Tag settings":
Add an ability to reorder categories in "Content tag" vocabulary.
N/A
N/A
> Issue #3304774 by vnech: Reordering categories in "Content Tags"

- .github/workflows/qualityChecks.yml
We use assertions in our code to make sure things that should be a given actually work as we expect. However, we weren't running the assertions in our test suite.
We only need to enable this for PHPUnit since PHPCS/PHPStan use static analysis and don't need assertion code generated. Meanwhile our Behat tests use a Docker image that should have assertions enabled.
CI should still be green, otherwise apparently we had undiscovered bugs and need to figure out whether we want to change our coverage strategy or fix the bug before enabling the stricter tests using assertions.
> Internal: Enable assertions in PHPUnit tests

- social.info.yml
Open Social `social.info.yml` file is not reflecting our current released version
Update `social.info.yml` and change it's version to `11.7.x-dev`
N/A
N/A
N/A
N/A
N/A
N/A
> Update social.info.yml to reflect current Open Social version

- .github/workflows/behat.yml
This should ensure we get stack traces for the exceptions in our code so that we can more easily find their cause without having to re-run the test locally.
> Internal: Make behat output verbose in the CI

- modules/custom/entity_access_by_field/entity_access_by_field.module
- modules/custom/entity_access_by_field/src/EntityAccessByFieldPermissions.php
- modules/custom/entity_access_by_field/tests/src/Kernel/EntityAccessAccessGrantsTest.php
A lot of things are happening at the Node Grants and Node Grants Alter hooks in this module.
These can be also some very expensive calls that are being done. E.g. to load content.
To fix this on a short-term, apply static caching to some of the functions. This will in some cases reduce page load times by over 400ms.
Follow-ups are to be done later, including a full rewrite of the access system. But this needs a full testing suite first.
https://www.drupal.org/project/social/issues/3333352
https://getopensocial.atlassian.net/browse/PROD-23954
N/a
N/a
Improve the overall performance by adding static caching to the access layer with node grants.
N/a
N/a
> Issue #3333352 - Add static caching to parts of the Entity Access By Field module

- .github/workflows/behat.yml
- modules/social_features/social_group/modules/social_group_secret/social_group_secret.install
- modules/social_features/social_group/social_group.install
- tests/behat/features/bootstrap/PostContext.php
- tests/behat/features/capabilities/administration/check-export-users-to-CSV.feature
- tests/behat/features/capabilities/administration/check-mail-users.feature
- tests/behat/features/capabilities/comment/comment-create.feature
- tests/behat/features/capabilities/groups/groups-create-closed.feature
- tests/behat/features/capabilities/profile/profile-manager-notes.feature
- tests/behat/features/capabilities/topic/topic-overview-filter.feature
- tests/default.settings.php
This PR depends on https://github.com/goalgorilla/open_social/pull/3285 merge that first
The install script tries to install demo content which doesn't work consistently between versions of Open Social. However as of a recent update the CI actually exits when it fails (previously it failed silently).
In our tests we're supposed to create everything we need so we shouldn't be installing demo content anyway. That's why we replace the usage of the script with a more transparent site-install command.
Internal change no release notes
> Internal: Remove usage of install_script.sh in Behat CI

- .github/workflows/behat.yml
- tests/behat/README.md
- tests/behat/behat.yml
- tests/behat/features/bootstrap/DatabaseContext.php
- tests/behat/features/bootstrap/LogContext.php
- tests/behat/features/bootstrap/ModuleContext.php
- tests/behat/features/bootstrap/SocialDrupalContext.php
- tests/behat/features/bootstrap/ThemeContext.php
- tests/behat/features/capabilities/account/verified-user.feature
- tests/behat/features/capabilities/administration/check-export-users-to-CSV.feature
- tests/behat/features/capabilities/administration/check-mail-users.feature
- tests/behat/features/capabilities/administration/check-people-page-elements.feature
- tests/behat/features/capabilities/administration/check-revoke-or-grant-administrador-roles.feature
- tests/behat/features/capabilities/event/all-day-timezone.feature
- tests/behat/features/capabilities/event/event-create.feature
- tests/behat/features/capabilities/event/event-invite-members.feature
- tests/behat/features/capabilities/event/lu-homepage-my-events.feature
- tests/behat/features/capabilities/gdpr/create-data-policy.feature
- tests/behat/features/capabilities/gdpr/user-consent.feature
- tests/behat/features/capabilities/groups/groups-create-closed.feature
- tests/behat/features/capabilities/groups/groups-create-secret.feature
- tests/behat/features/capabilities/groups/groups-edit-open.feature
- tests/behat/features/capabilities/groups/groups-invite-members.feature
- tests/behat/features/capabilities/groups/groups-mute-notify.feature
- tests/behat/features/capabilities/mention/mention-comment.feature
- tests/behat/features/capabilities/post/post-create-disabled.feature
- tests/behat/fixture/.gitignore
- tests/composer.json
This PR depends on #3285 and #3282, merge those first
While moving over the behat tests from our `@stability-*` set-up to running all test folders on separate GitHub Workflow Jobs we lost the test that would upgrade Open Social from one major version to another.
In this commit we add a new parameter to our matrix which will perform an installation of the previous major version, update all the code and then run the database updates. This will ensure all our tests run against an updated site with and without all optional modules so that we know our update hooks don't break anything.
Internal no ticket
Some tests showed possible issues in our upgrade path. However, this PR is more valuable merged than waiting to fix the issues it discovered so a follow-up meta ticket with children has been …
> Internal: Ensure upgrade path is tested

- .github/workflows/behat.yml
During our test workflows we are always executing the following to require an Open Social branch:
`composer require goalgorilla/open_social:dev-$BRANCH_NAME`
Since we are also running tests when we merge to branches like `11.7.x` the statement above will fail to check out the branch and the tests are not going to run.
Verify what branch we are "checking out" and only add `dev-` if we have a development branch.
More information here https://getcomposer.org/doc/articles/versions.md#branches
N/A
N/A
N/A
N/A
N/A
N/A
> Internal: Update github workflows to make our tests work with development branches

- modules/custom/activity_viewer/src/Plugin/views/filter/ActivityNotificationVisibilityAccess.php
- phpstan-baseline.neon
I added a new custom message template message.template.example with this data:
[Video screenshot](https://user-images.githubusercontent.com/19921926/212740991-0717b0fa-77a7-4519-9e05-a4752c3a5b00.mov)
Then if I create a topic I will see multiple (duplicated) messages in "Notification Center":
The problem coming from views filter plugin - `\Drupal\activity_viewer\Plugin\views\filter\ActivityNotificationVisibilityAccess`, namely query in `query()` method has broken join with `node_access` table which cause duplicated rows in view.
- https://www.drupal.org/project/social/issues/3333919
- https://getopensocial.atlassian.net/browse/PROD-23776
n/a
n/a
Fix issue with duplicated messages on "Notification Center"
n/a
n/a
> Issue #3333919 by vnech: Duplicated messages in "Notification Center"

- modules/social_features/social_group/modules/social_group_invite/social_group_invite.install
- modules/social_features/social_group/modules/social_group_invite/social_group_invite.module
- modules/social_features/social_group/modules/social_group_invite/src/Form/SocialBulkGroupInvitation.php
<a href="https://www.drupal.org/project/ginvite">Group invite</a> module provide an ability to have invite message per group type. Distro enforce to have only one global message rather than use the message we can specify directly in group invite content:
Add possibility to have invite message per group type.
- https://www.drupal.org/project/social/issues/3326663
- https://getopensocial.atlassian.net/browse/PROD-19307
n/a
Email message preview:
Email message:
New settings on _/admin/config/opensocial/social-group_:
Site Manager has ability to change invite message per group type.
n/a
n/a
> Issue #3326663 by vnech: Replace default group invite email message

- modules/social_features/social_follow_user/social_follow_user.install
<code>social_follow_user_update_11403</code> moves the follow-user field from the profile to the user entity, but the ID in the code is incorrect. While Drupal itself overrides the ID in <code>FieldConfigBase</code> ensuring this isn't actually a problem, it reads a bit weird so it's good to fix.
No data has been malformed so it's purely a maintenance fix.
<h4 id="summary-steps-reproduce">Steps to reproduce</h4>
Ensure the ID in <code>social_follow_user_update_11403</code> is correct.
https://www.drupal.org/project/social/issues/3338215
N/a code change only
> Issue #3338215 by Kingdutch: Follow user field ID is incorrect after move

- modules/social_features/social_profile/modules/social_profile_preview/social_profile_preview.module
The profile preview activity alter incorrectly assumes an activity always has an Owner, but this could result in an error:
`TypeError: Drupal\profile\ProfileStorage::loadByUser(): Argument #1 ($account) must be of type Drupal\Core\Session\AccountInterface, null given, called in /app/html/profiles/contrib/social/modules/social_features/social_profile/modules/social_profile_preview/social_profile_preview.module on line 37 in /app/html/modules/contrib/profile/src/ProfileStorage.php on line 33 #0 /app/html/profiles/contrib/social/modules/social_features/social_profile/modules/social_profile_preview/social_profile_preview.module(37): Drupal\profile\ProfileStorage->loadByUser(NULL, 'profile')
`
Make sure we only alter if there is an actual Owner available for the activity. …
> Issue #3337612 by ronaldtebrake: Profile preview for Activities could cause errors

- modules/custom/activity_logger/activity_logger.install
- modules/social_features/social_activity/config/install/field.field.message.event_request_approved.field_message_context.yml
- modules/social_features/social_activity/config/install/field.field.message.event_request_approved.field_message_destination.yml
- modules/social_features/social_activity/config/install/field.field.message.event_request_approved.field_message_related_object.yml
- modules/social_features/social_content_report/config/install/field.field.message.content_reported.field_message_context.yml
- modules/social_features/social_content_report/config/install/field.field.message.content_reported.field_message_destination.yml
- modules/social_features/social_content_report/config/install/field.field.message.content_reported.field_message_related_object.yml
- modules/social_features/social_group/modules/social_group_flexible_group/modules/social_flexible_group_book/config/optional/field.field.message.create_book_group.field_message_context.yml
- modules/social_features/social_group/modules/social_group_flexible_group/modules/social_flexible_group_book/config/optional/field.field.message.create_book_group.field_message_destination.yml
- modules/social_features/social_group/modules/social_group_flexible_group/modules/social_flexible_group_book/config/optional/field.field.message.create_book_group.field_message_related_object.yml
- modules/social_features/social_group/modules/social_group_invite/config/optional/field.field.message.invited_to_join_group.field_message_context.yml
- modules/social_features/social_group/modules/social_group_invite/config/optional/field.field.message.invited_to_join_group.field_message_destination.yml
- modules/social_features/social_group/modules/social_group_invite/config/optional/field.field.message.invited_to_join_group.field_message_related_object.yml
- modules/social_features/social_mentions/config/install/field.field.message.create_mention_comment_stream.field_message_context.yml
- modules/social_features/social_mentions/config/install/field.field.message.create_mention_comment_stream.field_message_destination.yml
- modules/social_features/social_mentions/config/install/field.field.message.create_mention_comment_stream.field_message_related_object.yml
- modules/social_features/social_mentions/config/install/field.field.message.create_mention_post_stream.field_message_context.yml
- modules/social_features/social_mentions/config/install/field.field.message.create_mention_post_stream.field_message_destination.yml
- modules/social_features/social_mentions/config/install/field.field.message.create_mention_post_stream.field_message_related_object.yml
- modules/social_features/social_private_message/config/install/field.field.message.create_private_message.field_message_context.yml
- modules/social_features/social_private_message/config/install/field.field.message.create_private_message.field_message_destination.yml
- modules/social_features/social_private_message/config/install/field.field.message.create_private_message.field_message_related_object.yml
Some config was forgotten in  in #3285 but this is now needed as per https://www.drupal.org/node/3333024. Additionally some existing install config actually didn't match what the activity factory required but is now being errored on.
Add the missing field configs. 
Re-run the update hook added in 3285 to fix any missing config that was not yet added in 11.7.1.
https://getopensocial.atlassian.net/browse/PROD-24054
We have the following notifications:
```bash
$ find . -name 'message.template.*' | grep -vE '[0-9]'
./modules/custom/social_queue_storage/config/install/message.template.background_process_finished.yml
./modules/social_features/social_private_message/config/install/message.template.create_private_message.yml
./modules/social_features/social_content_report/config/install/message.te …
```
> Hotfix: PROD-24054 Add missing notification field configs

- modules/custom/activity_creator/src/Entity/Activity.php
- modules/custom/activity_creator/src/Plugin/ActivityActionBase.php
- modules/custom/activity_creator/src/Plugin/ActivityActionInterface.php
- modules/custom/activity_logger/activity_logger.module
- modules/custom/activity_logger/src/Entity/NotificationConfigEntityBase.php
- modules/custom/activity_logger/src/Entity/NotificationConfigEntityInterface.php
- modules/custom/activity_logger/src/Service/ActivityLoggerFactory.php
- phpstan-baseline.neon
To complete https://getopensocial.atlassian.net/browse/PROD-445 we need to add support for the config entity for the notifications system.
Updated activity_creator and activity_logger modules to add support for config entities.
To Make it works config entity must extend NotificationConfigEntityBase class that has needed methods.
https://www.drupal.org/project/social/issues/3344237#comment-14939516
https://getopensocial.atlassian.net/browse/PROD-445
None.
None.
Added notifications support for config entity.
Added abstract class NotificationConfigEntityBase for config entity to extend to have the possibility to use notifications.
None.
> Issue #3344237 by kashandarash: Add notification support for config entity

- .github/workflows/behat.yml
We tried to move test results even if there were none which caused the
"Move test artifacts into upload folder" test step to fail and hide real
test failures that caused it. This is confusing to developers and can
make it harder to figure out what's wrong.
The added line checks that there are actually any files to move (and
ignores the .gitignore file that's already in the folder) before trying
to move things.
> Internal: Only try to move test results if they exist

- modules/social_features/social_event/modules/social_event_invite/src/SocialEventInviteConfigOverride.php
We're doing expensive config gets in overrides and this is also for Social Event Invite.
Move the expensive calls within the `if` statement to avoid it being executed more often than necessary.
https://www.drupal.org/project/social/issues/3348279
N/a
N/a
We improved performance by reducing the number of config get calls in Social Event Invite.
N/a
N/a
> Issue #3348279 - Fix config override for Event Invite

- modules/social_features/social_user/social_user.module
We're seeing quite a few calls happening for `social_user_user_format_name_alter()`. In the example below on a user's stream page it happens ~100 times while there are only 3 unique users being displayed.
Add static caching per user so we don't have to go through all of the different suggestions numerous times.
https://www.drupal.org/project/social/issues/3348274
N/a
N/a
Improved performance by statically caching the outcome of the user_format_name_alter hook implementation per account ID.
N/a
N/a
> Issue #3348274 - Add static caching for the user_format_name_alter hook

- modules/social_features/social_group/modules/social_group_flexible_group/modules/social_flexible_group_book/social_flexible_group_book.module
- modules/social_features/social_group/modules/social_group_flexible_group/modules/social_flexible_group_book/src/Controller/SFGBController.php
- modules/social_features/social_group/modules/social_group_flexible_group/src/Subscriber/Route.php
These pages are visible for users who don't have view access to the group:
<ul>
<li><em>/group/{gid}/albums</em></li>
<li><em>/group/{gid}/books</em></li>
</ul>
Add fixes to access checkers.
- https://www.drupal.org/project/social/issues/3347940
- https://getopensocial.atlassian.net/browse/PROD-24503
n/a
n/a
Group pages "/group/{gid}/books" and "/group/{gid}/albums" pages aren't visible for non-allowed users.
n/a
n/a
> Issue #3347940 by vnech: Group "/books" and "/albums" pages are visible for non-allowed users

- modules/social_features/social_group/modules/social_group_invite/src/SocialGroupInviteConfigOverride.php
We're doing expensive config gets in overrides and this is also for Social Group Invite.
Move the expensive calls within the `if` statement to avoid it being executed more often than necessary.
https://www.drupal.org/project/social/issues/3348269
N/a
N/a
We improved performance by reducing the number of config get calls in Social Group Invite.
N/a
N/a
> Issue #3348269 - Fix config override for Group Invite

- composer.json
- modules/custom/activity_creator/activity_creator.module
- modules/custom/download_count/download_count.module
- modules/custom/entity_access_by_field/tests/src/Kernel/EntityAccessNodeAccessTestBase.php
- modules/social_features/social_embed/tests/src/Kernel/SocialUserEmbedTest.php
- modules/social_features/social_group/social_group.module
- modules/social_features/social_landing_page/social_landing_page.install
- modules/social_features/social_like/social_like.install
- phpstan-baseline.neon
- tests/behat/features/bootstrap/FeatureContext.php
Reverts goalgorilla/open_social#3312
Due to the branch being behind we need to rebase it and re-create the PR
> Revert "Issue #3341238: Upgrade Drupal version to Drupal 9.5"

- composer.json
- modules/custom/activity_creator/activity_creator.module
- modules/custom/download_count/download_count.module
- modules/custom/entity_access_by_field/tests/src/Kernel/EntityAccessNodeAccessTestBase.php
- modules/social_features/social_embed/tests/src/Kernel/SocialUserEmbedTest.php
- modules/social_features/social_group/social_group.module
- modules/social_features/social_landing_page/social_landing_page.install
- modules/social_features/social_like/social_like.install
- phpstan-baseline.neon
- tests/behat/features/bootstrap/FeatureContext.php
- translations/gpch/fr_CH.po
This is the updated version of PR https://github.com/goalgorilla/open_social/pull/3312 that was merged and reverted here https://github.com/goalgorilla/open_social/pull/3368.
We are going to use the latest version from main to make sure that all tests are still valid.
Currently, Open Social is using Drupal 9.4 ( https://github.com/goalgorilla/open_social/blob/11.7.1/composer.json#L127 )
Drupal 9.4's security support is going to end on June 21, 2023 as per documentation in https://www.drupal.org/about/core/policies/core-release-cycles/schedule#current
The current minor version upgrade of Drupal is https://www.drupal.org/project/drupal/releases/9.5.3.
So, we are upgrading Open Social to Drupal 9.5.3
Release notes of Drupal 9.5: https://www.drupal.org/project/drupal/releases/9.5.0
1. Upgrade …
> Issue #3341238: Upgrade Drupal version to Drupal 9.5

- modules/social_features/social_group/src/SocialGroupHelperService.php
If try to execute the function `_social_group_get_current_group($node)` in out-of-page context we get an error:
```bash
WARNING  Undefined array key "node" in profiles/contrib/social/modules/social_features/social_group/src/SocialGroupHelperService.php on line 128
```
This issue can be reproduced in a lot of places related to activity creation (and may block "Activity Creator" cron job).
Fix syntax error.
- https://getopensocial.atlassian.net/browse/PROD-24769
- https://www.drupal.org/project/social/issues/3350838
n/a
n/a
Fix the error blocked the "Activity Creator" cron job.
n/a
n/a
> Issue #3350838 by vnech: Error blocked the "Activity Creator" cron job

- modules/social_features/social_event/config/optional/message.template.user_was_enrolled_to_event.yml
- modules/social_features/social_event/config/update/social_event_update_11901.yml
- modules/social_features/social_event/social_event.install
```
Import of string \"<p>Dit is om te bevestigen dat je je hebt ingeschreven voor het evenement <u>[social_event:event_iam_organizing]</u>.</p>  <p>[message:preview]</p>  <p>[message:cta_button]</p> \" was skipped because of disallowed or malformed HTML. []
```
Change `<u>` to `<em>`.
- https://www.drupal.org/project/social/issues/3355561
N/a
```text:
2:
value: "<p>This is to confirm that you've enrolled for the event <u>[social_event:event_iam_organizing]</u>.</p>\r\n\r\n<p>[message:preview]</p>\r\n\r\n<p>[message:cta_button]</p>\r\n"
format: full_html
```
N/a
Fixed an error where the translation for a string containing a `<u>` tag would not import.
N/a
N/a
> Issue #3355561 - Change underline html tag to em to ensure translations can be imported correctly

- modules/social_features/social_footer/src/Plugin/Block/SocialFooterPoweredByBlock.php
- phpstan-baseline.neon
Looks like when a logo is not uploaded in the socialblue_footer_powered block it could generate duplicates:
Add a check if the default logo exists then it should prevent the creation a new files.
- https://www.drupal.org/project/social/issues/3355356
- https://getopensocial.atlassian.net/browse/PROD-25135
N/A
N/A
Fixed an issue with "open_social_logo.png" duplicated records on the files page
N/A
N/A
> Issue #3355356 by SV: Prevent duplicated logo images on the Files page

- composer.json
Having a really long HTML tag (e.g. < img > with src:data/image...) makes preg_split fail and return false. On PHP 7.4 this throws a warning ("Warning: count(): Parameter must be an array or an object that implements Countable in _filter_url() (line 535 of core/modules/filter/filter.module).") and makes the field render empty, on PHP 8.0 this throws a fatal error.
If $chunks is empty, keep $text.
https://www.drupal.org/project/social/issues/3360661
*[Required if new feature, and if applicable] A short summary of the changes that were made that can be …
> Issue #3360661 - Url Embed - preg_split in _filter_url breaks for long html tags

- modules/custom/activity_creator/activity_creator.module
- modules/custom/activity_creator/activity_creator.services.yml
- modules/custom/activity_creator/src/Service/ActivityCreatorBatchActivityDeletion.php
- tests/behat/behat.yml
- tests/behat/features/bootstrap/LogContext.php
- tests/behat/features/bootstrap/UserContext.php
- tests/behat/features/capabilities/account/delete_user.feature
- tests/behat/features/capabilities/post/post-comments.feature
When deleting a user it will trigger the activity_creator delete hook, this will in turn delete all the activities for the user.
These activities are currently being deleted with a multiple_load inside the activity_creator, when doing this for 4k items or more the memory will time out.
Altering this to a batch we make sure we don't make the request too heavy and divide it per batch. Also it will improve the interface when deleting a user, because now it will seem stuck on status 'initializing'. With this change you will see the process of deleting the activities which is the most heavy process of deleting users.
https://www.drupal.org/project/social/issues/3356508
We fixed an issue where old users with a lot of activities couldn't be deleted because the action would time out with an error …
> Issue #3356508 - Deleting users with a lot of activities crashing with memory limit

- composer.json
- modules/social_features/social_activity/modules/social_activity_filter/config/modify/social_activity_filter.views.yml
- modules/social_features/social_activity/modules/social_activity_filter/social_activity_filter.install
- modules/social_features/social_follow_user/config/modify/social_follow_user.profile_views.yml
- modules/social_features/social_follow_user/social_follow_user.install
- phpstan-baseline.neon
- phpstan.neon
- phpunit.xml.dist
- src/PHPStan/Rules/CorrectUpdateHelperUsage.php
- tests/phpstan/data/install_example/install_example.install
- tests/phpstan/src/TestCorrectUpdateHelperUsage.php
We sometimes use PHPStan outside of update hooks but this is prone to hard to debug errors which is why we shouldn't do it.
This adds a PHPStan hook (with test coverage) to allow `executeUpdate` calls from a `hook_update_N` but not in other functions.
*[Required if new feature, and if applicable] A short summary of the changes that were made that can be included in release notes.*
*[Required if applicable] If this Pull Request changes the way that developers should do things or introduces a new API for developers then a change record …
> Internal: Create updateHelper PHPStan rule

- modules/custom/activity_send/modules/activity_send_email/src/Plugin/EmailFrequency/Immediately.php
When sending out email notifications based on the message templates while having multilanguage on. It will only send the base language, not the translation for the subject lines.
This is caused by the function $message->getTemplate which load the override free template, in our case we need the translated version as we later include this in the sendemail as a variable %subject which Drupal does not translate.
Replace the function getTemplate by getting it from the entitytypemanager with the override, so it's correctly translated.
https://www.drupal.org/project/social/issues/3361854
*[Required if applicable] Paste a link to the drupal.org theme issue queue item, either from [socialbase](https://www.drupal.org/project/socialbase) or [socialblue](https://www.drupal.org/project/socialblue). If …
> Issue #3361854 - Message template subject translation for multilanguage

- tests/behat/features/capabilities/account/delete_user.feature
We forgot to add a comment to a test in https://github.com/goalgorilla/open_social/pull/3387
Add comment
https://www.drupal.org/project/social/issues/3356508
N/A
N/A
N/A
N/A
N/A
N/A
> Issue #3356508 - Add missing comment for PR 3387

- modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install
Add access check for entity queries used in social_group_flexible_group_update_11701 hook.
social_group_flexible_group_update_11701 fails on database update.
> [error] 'status' not found
> [error] Update failed: social_group_flexible_group_update_11701
> [error] Update aborted by: social_group_flexible_group_update_11701
> [error] Finished performing updates.
Related to: https://www.drupal.org/project/social/issues/3348199
[Access checking must be explicitly specified on content entity queries](https://www.drupal.org/node/3201242)
[3364059](https://www.drupal.org/project/social/issues/3364059)
N/A
N/A
Resolved an issue where the database update (social_group_flexible_group_update_11701) would encounter an error.
N/A
N/A
> Issue #3364059 by zanvidmar: Add access check for entity queries

- modules/social_features/social_event/modules/social_event_managers/social_event_managers.module
Fix status message on "Manage enrollments" actions that reports wrong number of operations.
Status message on Manage enrollments actions reports wrong number of operations.
Fix the issue introduced in [https://github.com/goalgorilla/open_social/commit/cad316d3c661b099945851...](https://github.com/goalgorilla/open_social/commit/cad316d3c661b099945851eefa528b148aa5cf79#diff-276d80a5f825c11ab82d3f38f32d1631e7f4b1dec0a571480012602a5666fa30L451)
[3363797](https://www.drupal.org/project/social/issues/3363797)
N/A
Status message on "Manage enrollments" actions now reports correct number of operations.
N/A
N/A
> Issue #3354659 by zanvidmar: Fix status message on "Manage enrollments" actions

- modules/social_features/social_event/modules/social_event_addtocal/social_event_addtocal.routing.yml
As guest event enroller I can't add event to iCal calendar because when I click on link "iCal calendar" I am prompted to log in.
Allow for Guest event enrollers add event to iCal calendar
- https://www.drupal.org/project/social/issues/3365299
- https://getopensocial.atlassian.net/browse/PROD-25586
n/a
n/a
Allow for guest event enrollers to add event to iCal calendar
n/a
n/a
> Issue #3365299 by vnech: Allow for guest event enrollers add event to iCal calendar

- tests/behat/features/capabilities/groups/flexible/groups-flexible-views-order.feature
Broken behat tests for flexible groups views order.
Add correct date format in broken behat test.
n/a
n/a
n/a
n/a
n/a
n/a
n/a
> Hotfix: Broken behat tests

- composer.json
Currently in Distro we use dev version of module `drupal/like_and_dislike`
It was done as part of Drupal 9.5 update on April 7 in PR #3369
On April 11 there was new release of a module: [8.x-1.0-beta3](https://www.drupal.org/project/like_and_dislike/releases/8.x-1.0-beta3)
On some CI it's not allowed to use modules in dev-version, and it's better to use fixed version if possible.
Update  module to latest fixed version.
N/A
N/A
N/A
Like & Dislike module has been updated to the version 1.0-beta3.
N/A
> Updates: Like & Dislike module from dev to fixed version 1.0-beta3

- modules/social_features/social_follow_taxonomy/assets/css/activity-followed.css
- modules/social_features/social_follow_taxonomy/assets/css/activity-followed.scss
The `Unfollow` button is displayed on the stream teaser.
Change styles to the `Unfollow` button on the stream teasers.
- https://www.drupal.org/project/social/issues/3365270
- https://getopensocial.atlassian.net/browse/PROD-25576
N/A
before:
The `Unfollow` button is hidden on the stream teasers.
> Issue #3365270 by agami4: Add improvements to the `Unfollow` button on the stream teasers

- modules/social_features/social_profile/modules/social_profile_organization_tag/social_profile_organization_tag.module
- phpstan-baseline.neon
- tests/behat/features/capabilities/profile/profile-organization-tag.feature
Profile organization tag with special characters not displayed correctly in profile stream.
Remove double-escaping.
[3366231](https://www.drupal.org/project/social/issues/3366231)
N/A
N/A
> Issue #3366231 by zanvidmar: Profile organization tag with special characters not displayed correctly

- tests/behat/features/bootstrap/EventContext.php
- tests/behat/features/bootstrap/FileContext.php
- tests/behat/features/capabilities/event/add-to-calendar.feature
As a developer I want to have Behat tests for "Add to calendar" feature.
- Add Behat tests for **iCal** calendar
- https://getopensocial.atlassian.net/browse/PROD-25673
n/a
n/a
n/a
- Add Behat tests for **iCal** calendar
n/a
n/a
> Internal: Add Behat tests for "Add to calendar" feature

- .github/workflows/qualityChecks.yml
- phpstan.neon
PHP 8.0 will reach EOL soon, so we need to upgrade our platform to use PHP 8.1
Upgrade our requirements to PHP 8.1
https://www.drupal.org/project/social/issues/3368689
N/A
N/A
N/A
N/A
N/A
> Issue #3368689 by tbsiqueira: Add PHP 8.1 compatibility to Open Social

- tests/behat/features/bootstrap/SocialMinkContext.php
We're missing a Behat step to assert a number of items a text is present on the page in a given selector.
A Behat test step is added that does just that :)
An example of where this would be useful is to test whether a specific entity is shown multiple times in an overview, to detect duplicate results after filtering.
N/a, internal only.
N/a
N/a
N/a
N/a
N/a
> Internal: Add a new Behat step that tests for an exact number of times a text is present in a given selector

- cspell.json
```
Dictionary Error with (project-baseline)
name: project-baseline
msg: failed to load
stack:
project-baseline: failed to load
at /home/runner/work/_actions/streetsidesoftware/cspell-action/v2/action/node_modules/cspell-lib/dist/cjs/SpellingDictionary/DictionaryController/DictionaryLoader.js:110:147
at async Promise.all (index 0)
```
Seems we didn't fully remove the baseline before.
Make sure we remove the project baseline details from the cspell.json
None, internal. 
See the error doesn't occur, as you can f.e. see here: https://github.com/goalgorilla/open_social/actions/runs/5422956794
None, internal fix for the spell check action.
> Internal: Fix non blocking error on the Spell Check action

- modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserAnalyticsCommentsCreated.php
- modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserAnalyticsEventEnrollments.php
- modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserAnalyticsEventsCreated.php
- modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserAnalyticsGroupMemberships.php
- modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserAnalyticsGroupsCreated.php
- modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserAnalyticsLikes.php
- modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserAnalyticsPostsCreated.php
- modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserAnalyticsTopicsCreated.php
- modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserGroupMemberships.php
- tests/behat/features/bootstrap/PostContext.php
- tests/behat/features/bootstrap/SocialDrupalContext.php
- tests/behat/features/capabilities/administration/check-export-users-to-CSV.feature
Currently, when I do a CSV export of users on the platform, the resulting file is missing data in some of the columns.
For the following columns values for all users are 0
- created posts
- comments
- topics
- events
- groups
- group memberships 
- likes
- private messages
- group memberships
Fix incorrect type check for `$user_id` var.
- https://www.drupal.org/project/social/issues/3365912
- https://getopensocial.atlassian.net/browse/PROD-25468
N/A
**Users page**
**Exported CVS (with empty columns)**
Fixed issue with empty engagement data in users export.
N/A
N/A
> Issue #3365912 by SV: User Export no longer contains  engagement data

- modules/social_features/social_event/src/SocialEventTrait.php
Currently, when all day checkbox is activated and the start date and end date are the same for example today, then the event is passed.
Add condition in SocialEventTrait.php - if the all-day checkbox is activated and the end date is equal to the current date then the event is ongoing.
https://www.drupal.org/project/social/issues/3276434
N/A
N/A
N/A
N/A
N/A
> Issue #3276434 by v.koval: Add condition if all day is activated and current date is equal to the end date

- modules/social_features/social_activity/src/EmailTokenServices.php
**IMPORTANT:**
Should only be merged in `11.10.x` and `11.9.x`
During cherry-pick of the PR https://github.com/goalgorilla/open_social/pull/3459 to `11.10.x` and `11.9.x` there was conflict. After resolving duplicate key `#profile_class` was added to the `getUserPreview` method of `EmailTokenServices`
Remove duplicate `#profile_class` as it was done in the original PR #3459 
Internal.
N/A
- Check if PHPStan pass
Internal. See the problem part.
N/A
N/A
> Internal: Remove duplicate array key profile_class in EmailTokenServices

- modules/social_features/social_search/config/install/search_api.index.social_all.yml
- modules/social_features/social_search/config/install/search_api.index.social_content.yml
- modules/social_features/social_search/config/install/search_api.index.social_groups.yml
- modules/social_features/social_search/config/install/views.view.search_all.yml
- modules/social_features/social_search/config/install/views.view.search_content.yml
- modules/social_features/social_search/config/install/views.view.search_groups.yml
- modules/social_features/social_search/config/update/social_search_update_11402.yml
- modules/social_features/social_search/social_search.install
- tests/behat/features/capabilities/search/search-multilingual.feature
The search results in Search All, Search Content and Search Group doesn't appear if a user whose language is different than default site language.
In Search All, only users will appear as results.
There is a filter called “Interface Language” on Search All, Search Content, Search Group which limits the search results. Search User doesn’t have this filter which is why only “Members” (Users) appear in search results when a user of “non-site-default” language uses the search function.
Update the filters to consider fallback language.
- https://www.drupal.org/project/social/issues/3310800
- https://getopensocial.atlassian.net/browse/PROD-21427
N/A
German version:
French version:
Fixes issue with incomplete results in the search for multilingual sites. 
N/A
N/A
> Issue #3310800 by SV: Search results don't appear for non-default site language users

- tests/behat/features/capabilities/comment/comment-reply-to-thread.feature
We merged https://github.com/goalgorilla/open_social/pull/3472 without writing tests for it, so we need to add them.
Add behat tests for https://github.com/goalgorilla/open_social/pull/3472.
https://www.drupal.org/project/social/issues/3378480
Add tests for https://github.com/goalgorilla/open_social/pull/3472
> Issue #3378480 by nkoporec: Add tests for #3378480

- modules/social_features/social_event/config/update/social_event_update_11902.yml
We're expecting a specific key to exist, but testing showed that it's possible the keys in the list are -1, 0 and 1, and not 0, 1, and 2. In that case the expected config fails. To resolve this we remove the expectation of a specific commit and make sure we fix the config regardless of what's currently stored in it.
https://www.drupal.org/project/social/issues/3383985
> Issue #3383985: Fix expected config in `social_event_update_11902`

- modules/social_features/social_event/social_event.module
- modules/social_features/social_event/src/Plugin/views/filter/EventDate.php
- phpstan-baseline.neon
- tests/behat/features/capabilities/event/filter-community-events.feature
Currently, when all day checkbox is activated and the start date and end date are the same for example today, then the event is passed and doesn't show on the map.
Change the code for a custom filter that allows us to filter events correctly
- https://getopensocial.atlassian.net/browse/PROD-22452
-  https://www.drupal.org/project/social_geolocation/issues/3378384
- https://www.drupal.org/project/social/issues/3384253
N/A
**Activate the all day field and set today's date in start date field and end date field:**
**After saving it on /community-events page you will see the marker in geo map with this event**
**Click on the marker, you will see the title and datetime of the event.**
Fix the display of ongoing events on the map and event overview when the checkbox all day is activated.
N/A …
> Issue #3384253 by Koval: Fix ongoing events when checkbox all day is activated

- modules/social_features/social_comment_upload/js/comment-upload.js
- modules/social_features/social_comment_upload/social_comment_upload.libraries.yml
- modules/social_features/social_core/assets/js/invite-form.js
- modules/social_features/social_core/social_core.libraries.yml
- modules/social_features/social_landing_page/js/social_landing_page--accordion.js
- modules/social_features/social_landing_page/social_landing_page.libraries.yml
- modules/social_features/social_post/modules/social_post_album/assets/js/social-post-album--popup-slider.js
- modules/social_features/social_post/modules/social_post_album/social_post_album.libraries.yml
- modules/social_features/social_profile/modules/social_profile_preview/assets/js/social_profile_preview.js
- modules/social_features/social_profile/modules/social_profile_preview/social_profile_preview.libraries.yml
Deprecated message to once-jquery function
Update once-jquery function to keep forward to Drupal 10 upgrade.
See:
- https://www.drupal.org/node/3158256
- https://www.drupal.org/project/drupal/issues/3183149
https://www.drupal.org/project/social/issues/3385143
N/A
N/A
N/A
N/A
N/A
> Issue #3385143 - Update javascript code to the new standard d10

- composer.json
Changes:
https://git.drupalcode.org/project/config_update/-/compare/8.x-1.7...2.0.0-alpha3?from_project_id=55524&straight=false 
Update to latest version.
https://www.drupal.org/project/social/issues/3386141#comment-15223076
> Issue #3386141 by nkoporec: Update drupal/config_update from 1.7 to 2.0.0-alpha3

- composer.json
- modules/custom/gvbo/src/Plugin/views/field/GroupViewsBulkOperationsBulkForm.php
- modules/social_features/social_core/src/Controller/SocialCoreController.php
- modules/social_features/social_event/modules/social_event_managers/social_event_managers.module
- modules/social_features/social_event/modules/social_event_managers/src/Plugin/Action/SocialEventManagersSendEmail.php
- modules/social_features/social_event/modules/social_event_managers/src/Plugin/views/field/SocialEventManagersViewsBulkOperationsBulkForm.php
- modules/social_features/social_group/modules/social_group_gvbo/src/Access/SocialGroupViewsBulkOperationsAccess.php
- modules/social_features/social_group/modules/social_group_invite/src/Plugin/views/field/SocialGroupInviteViewsBulkOperationsBulkForm.php
- modules/social_features/social_group/src/Plugin/views/field/SocialGroupViewsBulkOperationsBulkForm.php
- modules/social_features/social_user/src/Plugin/Action/SocialSendEmail.php
- phpstan-baseline.neon
Reverts goalgorilla/open_social#3281
This PR introduced a patch that points to the diff of a PR rather than a static file and it's breaking our CI
This PR was also merged and not rebased.
> Revert "Updates: (deps): Update drupal/views_bulk_operations requirement from 4.1.4 to 4.2.3"

- composer.json
VBO was removed when reverted: [Revert "Updates: (deps): Update drupal/views_bulk_operations requirement from 4.1.4 to 4.2.3" by tbsiqueira · Pull Request #3526 · goalgorilla/open_social](https://github.com/goalgorilla/open_social/pull/3526) 
[Revert "Updates: (deps): Update drupal/views_bulk_operations requirement from 4.1.4 to 4.2.3" by tbsiqueira · Pull Request #3526 · goalgorilla/open_social](https://github.com/goalgorilla/open_social/pull/3526) 
The confusion is coming from merge (should be rebased instead): [Updates: (deps): Update drupal/views_bulk_operations requirement from 4.1.4 to 4.2.3 by dependabot · Pull Request #3281 · goalgorilla/open_social](https://github.com/goalgorilla/open_social/pull/3281/commits/ffc03b76d9e6d9e7bcdf91e0a20a7e4b9b2f67ca)
Revert views_bulk_operations …
> Hotfix: Revert wrongly removed views_bulk_operations with commit d1abf916f

- composer.json
We are currently running 8.x-1.16 which is not compatible with Drupal 10
Update dynamic_entity_reference to 3.0.0 to be compatible with Drupal 10 and PHP 8.1.
Use [open_social_upgrade_patches](https://github.com/goalgorilla/open_social_upgrade_patches) to properly apply patches for dynamic_entity_reference.
`dynamic_entity_reference` `3.0.0`
- compatible with Drupal 10
- patch: https://www.drupal.org/files/issues/2023-09-08/3099176-3.x-16.diff
`dynamic_entity_reference` `1.1.6`
- compatible with Drupal 9
- patch: https://www.drupal.org/files/issues/2022-02-14/3099176-1.x-14.patch
[3386004](https://www.drupal.org/project/social/issues/3386004)
N/A
N/A
Update dynamic_entity_reference to 3.0.0 to be compatible with Drupal 10 and PHP 8.1.
N/A
N/A
> Issue #3386004 Update dynamic_entity_reference to 3.0.0

- composer.json
The current version isn't compatible with D10
Update the Data policy module to the latest version
https://www.drupal.org/project/social/issues/3386735
Data Policy:
- https://www.drupal.org/project/data_policy/issues/3286895
- https://www.drupal.org/project/data_policy/issues/3387128
N/A
N/A
N/A
N/A
N/A
> Issue #3386735 - Update the Data Policy module to be compatible with D10

- composer.json
- modules/custom/gvbo/src/Plugin/views/field/GroupViewsBulkOperationsBulkForm.php
- modules/social_features/social_core/src/Controller/SocialCoreController.php
- modules/social_features/social_event/modules/social_event_managers/social_event_managers.module
- modules/social_features/social_event/modules/social_event_managers/src/Plugin/Action/SocialEventManagersSendEmail.php
- modules/social_features/social_event/modules/social_event_managers/src/Plugin/views/field/SocialEventManagersViewsBulkOperationsBulkForm.php
- modules/social_features/social_group/modules/social_group_gvbo/src/Access/SocialGroupViewsBulkOperationsAccess.php
- modules/social_features/social_group/modules/social_group_invite/src/Plugin/views/field/SocialGroupInviteViewsBulkOperationsBulkForm.php
- modules/social_features/social_group/src/Plugin/views/field/SocialGroupViewsBulkOperationsBulkForm.php
- modules/social_features/social_user/src/Plugin/Action/SocialSendEmail.php
- modules/social_features/social_user/src/Plugin/QueueWorker/UserMailQueueProcessor.php
- phpstan-baseline.neon
We need to update VBO module to latest version so that we are compatible with Drupal 10.
This is a breaking change because VBO added type-hint to their functions, making them BC breaking changes, so it should land in major version of OS. We also need to check cablecar extensions compatibility, since any custom VBO action will break.
Upgrade VBO module and fix all the custom code compatibility.
Follow up from https://github.com/goalgorilla/open_social/pull/3281
Upgrade views_bulk_operation module to the latest …
> Updates: (deps): Update drupal/views_bulk_operations requirement from 4.1.4 to 4.2.4 - follow up

- modules/social_features/social_activity/social_activity.install
- modules/social_features/social_event/social_event.install
- modules/social_features/social_group/social_group.install
- modules/social_features/social_profile/social_profile.install
- modules/social_features/social_topic/social_topic.install
- phpstan-baseline.neon
A pattern that was seen to add the "All x" links was that we'd load all the menu links (which can be 100s) and then looped through them all.
This commit instead uses filters in the database query to more efficiently find the correct link and then more efficently creates the new child menu link. While making this change we move things back into hook_install, which is generally small enough not to need splitting up (especially since we usually don't re-use any of the other install code, since installing is a pretty specific action).
https://www.drupal.org/project/social/issues/3385398
[Not sure if release notes is needed for performance optimization on install]
> Issue #3385398 by Kingdutch: Optimize menu link loading for module installs

- composer.json
- modules/custom/social_gdpr/social_gdpr.module
- modules/custom/social_magic_login/src/Controller/MagicLoginController.php
- tests/behat/features/capabilities/gdpr/create-data-policy.feature
- tests/behat/features/capabilities/gdpr/inform-block.feature
- tests/behat/features/capabilities/gdpr/user-consent.feature
A new version of the Data Policy module was released.
Update to the latest Data Policy module 2.0.0-beta8.
- https://www.drupal.org/project/social/issues/3390638
- https://getopensocial.atlassian.net/browse/PROD-26831
- - https://www.drupal.org/project/data_policy/releases/2.0.0-beta7
- https://getopensocial.atlassian.net/browse/PROD-26275
- - https://www.drupal.org/project/data_policy/releases/2.0.0-beta8
N/a
Instead of "**data policy**" the copy changed to "**data protection statement**". Additionally the default text "**I agree with the <data policy here>**" changed to "**I read and consent to the <data protection statement here>**".
Fixed error with the Data Policy Agreement detail page if there are no data policies created.
N/a
N/a
> Issue #3390638: Update the copy of the Data Policy module

- modules/social_features/social_user/config/install/views.view.user_admin_people.yml
- modules/social_features/social_user/social_user.install
- modules/social_features/social_user/social_user.module
- modules/social_features/social_user_export/src/Plugin/UserExportPlugin/UserLastAccess.php
- tests/behat/features/capabilities/administration/check-export-users-to-CSV.feature
- tests/behat/features/capabilities/administration/check-people-page-elements.feature
On the `admin/people` page we have a last login filter, but the last login field is not displayed, instead, the last access field is displayed, which can lead to a misunderstanding. So, we need to replace the `Last login` with the `Last activity (last access)` filter. After that admin can filter users by last access
Replace  `Last login` with the `Last activity (last access)` filter using hook_update
- https://www.drupal.org/project/social/issues/3388336
- https://getopensocial.atlassian.net/browse/PROD-24149
- https://getopensocial.atlassian.net/browse/PROD-26878
N/A
Replace the 'Last login' with the 'Last activity' (last access) filter on the `admin/people` page.
https://www.drupal.org/node/3390675
N/A
> Issue #3388336 by v.koval: Replace the 'Last login' with the 'Last activity' (last access) filter on the admin/people page.

- composer.json
The current private message version isn't be compatible with Drupal 10
Apply the patch from [#3297888: Automated Drupal 10 compatibility fixes](https://www.drupal.org/project/private_message/issues/3297888) to private message 3.0.0-beta2 version.
- https://www.drupal.org/project/social/issues/3388559
- https://www.drupal.org/project/private_message/issues/3297888
N/A
N/A
N/A
N/A
N/A
> Issue #3388559: Apply patch at Private Message module to be compatible with D10

- cspell.words.txt
- modules/social_features/social_event/modules/social_event_addtocal/src/Controller/AddToCalendarIcsController.php
Currently the spellchecker is failing due to changes in the iCall feature.
Make sure we add the words to the spellchecker definition as we cannot use any other wording for it, as they are ical attributes.
Internal - quality check fix to get all the tests green
> Internal: Fix the Add to iCall feature spellchecker quality control

- composer.json
Even though it's declared to be D10 compatible in the latest releases there are some fixes so we want to upgrade already.
but it is also required for the profile refactor in #3480
We decided to cherry-pick the commit already for our 11.11.x branches coming from the profile refactor.
https://github.com/goalgorilla/open_social/pull/3480/commits/57842329d8a3727df6bab0b059dec272f4dd32a2
Additionally patches were needed for regression:
https://github.com/goalgorilla/open_social/pull/3480/commits/0865f7a71482b548c52424d12232254bf5601738
Update includes:
https://www.drupal.org/project/profile/releases/8.x-1.5
https://www.drupal.org/project/profile/releases/8.x-1.6
https://www.drupal.org/project/profile/releases/8.x-1.7
https://www.drupal.org/project/social/issues/3393846 …
> Issue #3393846: Update `drupal/profile` requirement from 1.4.0 to 1.7.0

- composer.json
In a previous commit config update has been upgraded to version 2.0, but this version requires php 8.1.
The distro states that it should be able to work with 8.0 and higher, but because 2.0 was already released in 11.11.1 we give our users the option to either use 1.7 or 2.0 with php 8.1.
Let the community use either 1.7 with php 8 or 2.0 with php 8.1
https://www.drupal.org/project/social/issues/3386141
In a previous release the dependency drupal/config_update has been upgraded to version 2.0, but this version …
> Issue #3386141 - Hidden dependency for config_update forced php 8.1

- composer.json
Socialblue is added as a minimal requirement version for 2.5.0, but since now we have a newer socialblue version we can force it to the latest version.
This PR will also force the removal of PHP 8.0 dependency as Bootstrap is no longer supporting it, thus we might consider it a breaking change.
Update our composer.json file to require Socialblue ~[2.5.4](https://www.drupal.org/project/socialblue/releases/2.5.4), this will also require Socialbase ~[2.5.9](https://www.drupal.org/project/socialbase/releases/2.5.9) since Socialbase is a [requirement](https://git.drupalcode.org/project/socialblue/-/blob/2.5.x/composer.json?ref_type=heads#L8) of Socialblue. Those are important versions since they are now featuring Drupal 10 forward compatibility.
N/A …
> Internal: Update minimal required version of Socialblue to 2.5.4

- modules/social_features/social_tagging/social_tagging.module
- modules/social_features/social_tagging/src/SocialTaggingService.php
- modules/social_features/social_tagging/src/SocialTaggingServiceInterface.php
When I open `/node/add/event` there is an error:
Currently, in `termIsVisibleForEntities()`, there can be loaded terms that don't have a `field_category_usage` it causes an error and needs to add checks to prevent it.
- https://getopensocial.atlassian.net/browse/PROD-27205
- https://www.drupal.org/project/social/issues/3396674
- https://www.drupal.org/project/social/issues/3396372
N/A
N/A
Fixes an issue on event/topics create/edit pages
N/A
N/A
> Issue #3396674 by SV: Error on edit or create events and topics pages

- composer.json
- modules/social_features/social_private_message/src/Plugin/Field/FieldFormatter/SocialPrivateMessageOwnerFormatter.php
- modules/social_features/social_private_message/src/Plugin/Field/FieldFormatter/SocialPrivateMessageThreadMemberFormatter.php
- modules/social_features/social_private_message/src/Plugin/Field/FieldWidget/SocialPrivateMessageThreadMemberWidget.php
- phpstan-baseline.neon
In #3535 we used a patch for D10 compatibility for private message. However we didn't use the [lenient plugin](https://www.drupal.org/docs/develop/using-composer/using-drupals-lenient-composer-endpoint) or other solutions required to have composer be able to run it on D10. 
Fortunately there is a new stable release with D10 compatibility, use that instead, saves us installing a plugin and a patch.
https://www.drupal.org/project/private_message/releases/3.0.0
Also fix some PHPStan related issues coming from fixes here:
https://git.drupalcode.org/project/private_message/-/blob/8cd60c5124411527475604c044786c93fa45c432/src/Plugin/Field/FieldFormatter/PrivateMessageThreadMemberFormatter.php
https://www.drupal.org/project/social/issues/3388559
Update `drupal/private_message` to 3.0.0
> Issue #3388559 - Update `drupal/private_message` to stable 3.0.0

- composer.json
- modules/social_features/social_editor/social_editor.info.yml
In our ckeditor5 story on https://github.com/goalgorilla/open_social/pull/3574 we forgot to replace the core ckeditor4 module with the contrib one to extend the support until the end of the year.
Move to contrib Ckeditor4
https://www.drupal.org/project/social/issues/3391286
None -> release notes from https://github.com/goalgorilla/open_social/pull/3574 should be used as this is a follow-up
> Issue #3391286 - Move to ckeditor4 contrib module

- composer.json
In the PR https://github.com/goalgorilla/open_social/pull/3513 we added new dependency from  [open_social_upgrade_patches](https://github.com/goalgorilla/open_social_upgrade_patches) as `1.x-dev || 2.x-dev`
But some of CI/CD of our projects don't allow to use `dev-versions` in the dependencies.
Change open_social_upgrade_patches to stable versions `^1 || ^2` in composer.json.
Internal.
N/A
> Internal: Set stable versions for open_social_upgrade_patches

- modules/social_features/social_tagging/social_tagging.module
After Drupal 10 upgraded, the search start to throw an memory exhausted error to search by tag.
Symfony 5/6 deprecated/removed the ability to return non-scalar values, we need to use all() for that.
Change the get to all to fix the problem.
[#3398808](https://www.drupal.org/project/social/issues/3398808)
N/A
N/A
N/A
N/A
N/A
[PROD-27325]: https://getopensocial.atlassian.net/browse/PROD-27325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Issue #3398808: Memory exhausted to search content by tag

- modules/social_features/social_group/config/install/views.view.group_manage_members.yml
- modules/social_features/social_group/config/update/social_group_update_12001.yml
- modules/social_features/social_group/social_group.install
- modules/social_features/social_group/social_group.module
- modules/social_features/social_group/src/Plugin/Action/ChangeGroupMembershipRole.php
"Change roles of the selected members" in a Group does not change the role from Group Admin to a Group Manager of a group and vice versa.
- Change the code in `ChangeGroupMembershipRole.php`, function `execute()`.
- Output all roles for each user on Group page
- https://getopensocial.atlassian.net/browse/PROD-26912
- https://www.drupal.org/project/social/issues/3396860
n/a
and change the role to Admin 
It should work and you should see both roles
> Issue #3396860: Change roles of the selected members in a Group does not change the role from Group Admin to a Group Manager and vice versa

- composer.json
- modules/custom/activity_creator/src/Service/ActivityCreatorBatchActivityDeletion.php
- modules/custom/social_ajax_comments/social_ajax_comments.module
- modules/custom/social_ajax_comments/src/Controller/AjaxCommentsController.php
- modules/custom/social_ajax_comments/src/Routing/RouteSubscriber.php
When a comment is deleted and it has a notification created the pop-up confirmation never close, an error happen at browser-console and the comment is deleted.
This problem happen because a batch is started by activity module to keep the notification updated with the main entity and when the Ajax Comments is be using the batch can't redirect to batch page, it should be keep to be return at th request, but it is be ignoring by batch validation.
Applied a patch from Drupal Community to avoid the batch validation to redirect ajax **request.**
[#3395384](https://www.drupal.org/project/social/issues/3395384)
[#3395358](https://www.drupal.org/project/drupal/issues/3395358)
N/A
N/A
N/A
N/A
N/A
[PROD-26816]: https://getopensocial.atlassian.net/browse/PROD-26816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmND …
> Issue #3395384 - Fix error to delete a comment with notification

- .github/workflows/behat.yml
Our CI was still running on D9.5 images, which doesn't do harm as they are all PHP 8.1 compatible, but we want to make sure they run on the new versions based of drupal's docker images correctly.
https://hub.docker.com/r/goalgorilla/open_social_docker/tags
Two new tags we're created:
`drupal10-php8.1`
`ci-drupal10-php8.1`
None, internal.
See all tests pass. 
None, internal.
> Internal: Update our `goalgorilla/open_social_docker` images to Drupal 10

- modules/custom/social_media_system/README.md
- modules/custom/social_media_system/config/install/field.storage.media.field_media_file.yml
- modules/custom/social_media_system/social_media_system.info.yml
We need a module for all the default media configuration that can be reused by other modules.
Add Social Media System module (social_media_system) to Open Social.
[3402176](https://www.drupal.org/project/social/issues/3402176)
N/A
N/A
Add Social Media System module to Open Social. This release does not bring any functional changes for Open Social, to the current set of features. The existing functionalities remain unaffected.
Any media related configuration, that can be reused by other modules, should live in social_media_system module from now on.
N/A
> Issue #3402176: Add Social Media System module (social_media_system)

- modules/custom/social_graphql/src/GraphQL/Violation.php
To keeping forward with PHP 8.1 compatibility, the Social GraphQL is throwing a deprecated message:
`
Return type of Drupal\social_graphql\GraphQL\Violation::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed
`
Add a return type for the function: Drupal\social_graphql\GraphQL\Violation::jsonSerialize()
[#3402882](https://www.drupal.org/project/social/issues/3402882)
N/A
Run PHPUnit and check ht deprecated message is resolved.
N/A
N/A
N/A
N/A
> Issue #3402882: Deprecated message for Social GraphQL module for PHP8.1

- modules/social_features/social_event/modules/social_event_an_enroll_enrolments_export/src/Plugin/UserExportPlugin/EnrolmentUserDisplayName.php
- modules/social_features/social_event/modules/social_event_an_enroll_enrolments_export/src/Plugin/UserExportPlugin/EnrolmentUserEmail.php
- modules/social_features/social_event/modules/social_event_an_enroll_enrolments_export/src/Plugin/UserExportPlugin/EnrolmentUserFirstName.php
- modules/social_features/social_event/modules/social_event_an_enroll_enrolments_export/src/Plugin/UserExportPlugin/EnrolmentUserLastName.php
- modules/social_features/social_event/modules/social_event_an_enroll_enrolments_export/src/Plugin/UserExportPlugin/EnrolmentUserRegistration.php
There are some  warnings during the export of enrolment user data:
Add checks to prevent warnings during the export of anonymous enrolments.
- https://getopensocial.atlassian.net/browse/PROD-26734
- https://www.drupal.org/project/social/issues/3402841
N/A
Need to use drush command to export user data
Add checks to prevent wanrnings during the export of enrolment user data.
> Issue #3402841 by SV: Undefined array key "entity" during export of enrolment user data

- composer.json
The "Enter" key does not work after first message was sent in Private Message
This error already be fixed before and it should be used the solution before.
[#3397809](https://www.drupal.org/project/social/issues/3397809)
Private Message:
[#3397794](https://www.drupal.org/project/private_message/issues/3397794)
N/A
N/A
N/A
N/A
N/A
> Issue #3397809: Enter key does not work to send a private message

- phpstan.neon
The reason it was ignored was fixed in #3615 but the PHPStan exclusion was forgotten.
> Internal: Analyse GraphQL\Violation with PHPStan

- modules/custom/social_media_system/config/install/core.entity_view_mode.media.teaser.yml
Add default media teaser view mode to Social Media System module
At the moment, uninstall hook is missing, and this will be fixed by FUP: [3404301](https://www.drupal.org/project/social/issues/3404301) 
We need a default media teaser view mode in Social Media System so it can be reused.
Add default media teaser view mode to Social Media System module
[3403980](https://www.drupal.org/project/social/issues/3403980)
N/A
Add default media teaser view mode
N/A
N/A
> Issue #3403980: Add default media teaser view mode

- modules/social_features/social_core/src/Controller/SocialCoreController.php
- modules/social_features/social_event/social_event.module
The title should be fully translated on the create event page - so, the article should be wrapped with t() and then it will be properly displayed in:
>     return $this->t('Create @article @name', [
>      '@article' => $titles[$entity_type_id]['bundles'][$entity_type->id()] ?? 'a',
>      '@name' => mb_strtolower($label),
>    ])->render(); 
- https://www.drupal.org/project/social/issues/3404422
- https://getopensocial.atlassian.net/browse/PROD-27093
N/A
N/A
Fixes the issue with translation of title on the create event page
N/A
N/A
> Issue #3404422 by SV: Is not possible to translate a title on the "Add event" page

- modules/custom/entity_access_by_field/src/EntityAccessHelper.php
When I tried to create an event and got an error:
Add a check to prevent an issue on event create page
- https://www.drupal.org/project/social/issues/3403765
- https://getopensocial.atlassian.net/browse/PROD-27295
N/A
N/A
Add a check to prevent possible errors when creating content assigned to a specific group.
N/A
> Issue #3403765 by SV: Prevent unexpected error when creating content assigned to a group

- modules/social_features/social_swiftmail/social_swiftmail.install
- modules/social_features/social_swiftmail/src/Plugin/EmailAdjuster/InlineCssEmailAdjuster.php
- modules/social_features/social_swiftmail/src/Plugin/EmailAdjuster/MailHtmlTextFormat.php
- modules/social_features/social_swiftmail/src/Plugin/EmailBuilder/SocialSwiftmailEmailBuilder.php
- phpstan-baseline.neon
We are having an issue where our e-mails lose styling / formatting. 
1. the inline-css plugin does not see any css and will not go through the css-inline plugin and will not add inline css. This causes gmail to not have any styling. 
2. there are emails without text formats, meaning they are escaped, mail_html feels like a safe workaround.
As a workaround we are adding our own plugin who basically does the same apart from that it will do this always, not only if there is additional css and additionally adds a fallback if there is no text format.
https://www.drupal.org/project/social/issues/3406164
We introduced a workaround to fix the inline-css styling not being applying to emails causing the emails to not be styled for some clients like gmail.
> Issue #3406164 - Make sure our email template styling gets converted correctly.

- tests/behat/features/bootstrap/CKEditorContext.php
In some cases the context for @When /^I fill in the "([^"]*)" WYSIWYG editor with "([^"]*)"$/ is not working correctly, especially when the form is loaded via AJAX or nested (like in IEF module). In that case the div gets appended a unique identifier so when the JS script gets evaluated in cannot find the CKEditor instance.
Fix the context so that it works in all cases.
https://www.drupal.org/project/social/issues/3408235
1. Write a test that uses the above context and wants to write to CKEditor 5 instance that is …
> Issue #3408235 by nkoporec: Fix behat CKEditor context for writing inside the editor

- modules/social_features/social_core/social_core.install
After updating from 11.9 to version 12, updating the database returns the error
`
[error] The installed version of the /User/ module is too old to be updated day. Update to a version earlier than 10.0.0 first time (missing updates: user_post_update_update_roles).
if we still update the database, the site crashes with the following error:
Plugin (group_invitation) instance class "Drupal\ginvite\Plugin\GroupContentEnabler\GroupInvitation" does not exist.
and
The service "group.relation_handler.operation_provider.group_invitation" has a dependency on a non-existent service "group.relation_handler.operation_provider".
`
Trick Drupal in to thinking our post update hook has ran, by adding a update hook that adds this to the db and lets drupal know. …
> Issue #3400861: User module is too old after update 11 > 12

- modules/social_features/social_event/social_event.module
- tests/behat/features/capabilities/event/all-day-timezone.feature
- tests/behat/features/capabilities/event/event-create.feature
The event information isn't showing date-end and it should be shown at the event page and at the block from home or explore page.
The format function is choosing wrong format for event dates, fix the validation to choose the right format for each event date.
[PROD-27204](https://getopensocial.atlassian.net/browse/PROD-27204)
[#3398385](https://www.drupal.org/project/social/issues/3398385)
N/A
N/A
N/A
N/A
N/A
[PROD-27204]: https://getopensocial.atlassian.net/browse/PROD-27204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Issue #3398385: Event information is not showing date-end

- tests/behat/features/bootstrap/UserContext.php
This is split-off from #3480 out of 0139fbb89943854c0fb422c09c77c6d28fc3f0ff
This is a step we will need in future tests to be able to write tests around user registration. This decouples the path from the step.
https://getopensocial.atlassian.net/browse/PROD-27793
> Internal: PROD-27793 - Add user registration page step to `UserContext`

- tests/behat/features/bootstrap/FeatureContext.php
- tests/behat/features/capabilities/account/default-profile-picture.feature
We have previously had a lot of challenges with the default profile image disappearing on us and this is somewhat dependent on our file settings.
Cherry-pick the test introduced in #3480 from fd263a8be3a6259923182f6425d04c70c89c4fd8
We know now how to add a Behat test to verify that it’s present.
https://getopensocial.atlassian.net/browse/PROD-27795
> Internal: PROD-27795 - Add test coverage for default profile image

- modules/social_features/social_emoji/assets/js/social_emoji_picker.js
The Social Emoji ins't be shown at text-area field after the D10 is upgraded
The D10 removed the Popper from core-library and it was removed from our library, but, the injection continue at javascript file.
Remove the injection from javascript file.
[PROD-27850](https://getopensocial.atlassian.net/browse/PROD-27850)
[#33411083](https://www.drupal.org/project/social/issues/3411083)
N/A
I advise to get database from Enterprise environment and restore locally to test it.
N/A
N/A
N/A
N/A
[PROD-27850]: https://getopensocial.atlassian.net/browse/PROD-27850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Issue #33411083: Social Emoji isn't be shown after D10 upgraded

- modules/custom/social_path_manager/social_path_manager.module
- modules/social_features/social_comment/tests/src/Kernel/CommentViewAccessTest.php
- modules/social_features/social_core/social_core.module
- modules/social_features/social_core/tests/src/Kernel/ConfigLanguageManagerTest.php
- modules/social_features/social_group/modules/social_group_flexible_group/modules/social_flexible_group_book/social_flexible_group_book.module
- modules/social_features/social_user/tests/src/Kernel/GraphQL/GraphQLUsersEndpointTest.php
- phpstan-baseline.neon
- tests/composer.json
The 2.0 version of the package should've been needed for Drupal 10 compatibility but apparently in the distribution that works fine with 1.4.0.
Nevertheless we should upgrade to 2.0.0 to make sure we update Drush and all of our tooling.
We immediately jump to 2.1.0 because it adds `kingdutch/cucumber-linter` which we want to use for linting our Behat tests.
https://getopensocial.atlassian.net/browse/PROD-27811
> Internal: Update open_social_dev to 2.1

- tests/behat/features/capabilities/post/post-emoji.feature
The Social Emoji ins't be shown at text-area field after the D10 is upgraded
Create a behat-test to avoid the system to broken again in the future.
[PROD-27850](https://getopensocial.atlassian.net/browse/PROD-27850)
[#33411083](https://www.drupal.org/project/social/issues/3411083)
N/A
N/A
N/A
N/A
N/A
N/A
[PROD-27850]: https://getopensocial.atlassian.net/browse/PROD-27850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Issue #3411083: Behat test for Social Emoji

- modules/social_features/social_event/modules/social_event_addtocal/src/Plugin/SocialAddToCalendarBase.php
WSOD when previewing an event when `social_event_addtocal` is enabled.
You'll see the following:
```
Drupal\Core\Entity\EntityMalformedException: The "node" entity cannot have a URI as it does not have an ID in Drupal\Core\Entity\EntityBase->toUrl() (line 161 of core/lib/Drupal/Core/Entity/EntityBase.php).
Drupal\social_node\Entity\Node->toUrl('canonical', Array) (Line: 155)
Drupal\social_event_addtocal\Plugin\SocialAddToCalendarBase->getEventDescription(Object) (Line: 91)
Drupal\social_event_addtocal\Plugin\SocialAddToCalendarBase->generateSettings(Object) (Line: 27)
Drupal\social_event_addtocal\Plugin\SocialAddToCalendar\AddToOutlook->generateUrl(Object) (Line: 255)
_social_event_addtocal_get_links(Object) (Line: 107)
social_event_addtocal_node_view(Array, Object, Object, 'full') …
```
> Issue #3368031 by SocialNicheGuru: WSOD on preview of event with `social_event_addtocal` enabled

- composer.json
The Paragraph module has a new minor version with small bugfixes.
Upgrade the Paragraph to minor version
[PROD-27857](https://getopensocial.atlassian.net/browse/PROD-27857)
[#3411253](https://www.drupal.org/project/social/issues/3411253)
N/A
N/A
Paragraph releases notes: https://www.drupal.org/project/paragraphs/releases/8.x-1.16
N/A
N/A
[PROD-27857]: https://getopensocial.atlassian.net/browse/PROD-27857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Issue #3411253: Upgrade the Paragraph module to the major version

- .github/workflows/qualityChecks.yml
In case `$TEST_FILES` is not is not empty but contains only correctly named files then `$MISNAMED_FILES` will be an empty variable but `read -r line` will still trigger once adding an error without file to the PR which is confusing.
Update the while loop to stop if `$line` is empty which should only happen in the above described case.
Internal CI hotfix: No ticket
> Internal: Ensure empty MISNAMED_FILES doesn't report file name error in qualityChecks.yml

- .github/workflows/qualityChecks.yml
When opening a PR with a changed file test (administration/check-filter-by-group.feature in this case) the Behat name linting will fail with the following error:
```
home/runner/work/_temp/f16c8ebb-ffe4-4cf8-93e0-2e7887e535b3.sh: line 4: [: tests/behat/features/capabilities/administration/check-filter-by-group.feature: binary operator expected
[13](https://github.com/goalgorilla/open_social/actions/runs/7458380737/job/20292249484?pr=3664#step:5:14)
Error: Process completed with exit code 1.
```
`[` is bash specific syntax for the testing of conditions.
The default shell in the GitHub Workflow Ubuntu images isn't bash, but we do use `bash` syntax in our if-statement to evaluate filenames. To ensure we have predictable behaviour we set the default shell to `bash` for the job that contains …
> Internal: Ensure Behat filename linting runs on Bash

- .github/workflows/behat.yml
In #3578 we locked the major version because alpha versions of a new release were causing the wrong update path to be tested. We're now back with a stable 12.0 release and working on 13.0 so we can test the upgrade path from the latest 12 release  to `main`
We may in the future want to test the previous marjor release to our backported current major version's upgrade path still works but that requires additional workflow code and GitHub workflow resources.
Internal no change
> Internal: Unlock behat major version for CI testing

- modules/custom/social_lets_connect/social_lets_connect.install
The previous update hook added in #3636 was accidentally named incorrectly which means it hasn't run. 
We create a new update hook instead.
> Issue #3406822: Add new update hook to remove social_lets_connect_usage

- modules/social_features/social_core/social_core.install
- social.info.yml
The Social Emoji module isn't be enable by default, it would be great be enabled for all.
Add Social Emoji module as dependency to be enabled for all and add an hook-update to be enabled for already installed system.
[PROD-27847](https://getopensocial.atlassian.net/browse/PROD-27847)
[#3413813](https://www.drupal.org/project/social/issues/3413813)
N/A
Check if the Social Emoji module is enabled by default.
N/A
The Social Emoji will be enabled by all and it will be installed by default in new installation.
N/A
N/A
[PROD-27847]: https://getopensocial.atlassian.net/browse/PROD-27847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Issue #3413813: Enable Social Emoji to be enabled by default

- modules/custom/social_media_system/config/install/core.entity_view_mode.media.featured.yml
- modules/custom/social_media_system/social_media_system.install
We need a featured view mode in Social Media System so it can be reused.
Add featured view mode to Social Media System module in `config install folder` and write `hook_update`
https://www.drupal.org/project/social/issues/3413974
N/A
Clean Install:
Update:
N/A
Add new view mode for Media - featured
N/A
N/A
> Issue #3413974: Add featured view mode to social media system

- composer.json
In our previous version we locked the Gin Toolbar module at 1.0-beta17 version [#3222350: Lock gin_toolbar to 1.0-beta17](https://www.drupal.org/project/social/issues/3222350) and it isn't be necessary anymore, so we should unlocked this version and it should be controlled by Gin module and their dependencies.
Unlocked the Gin Toolbar module to be controlled by Gin module dependencies, which updates it to:
`drupal/gin_toolbar` requirement from 1.0.0-rc3 to 1.0.0-rc5
[PROD-27895](https://getopensocial.atlassian.net/browse/PROD-27895)
[#3413211](https://www.drupal.org/project/social/issues/3413211)
N/A
Unlocked the Gin Toolbar module will upgrade two version and these versions will fix some small compatibility issue with Drupal 10, so to test it, open admin page and navigate into some pages …
> Issue #3413211: Unlock gin_toolbar version from composer and update from `1.0.0-rc3` to `1.0.0-rc5`

- modules/social_features/social_event/modules/social_event_enrolments_export/social_event_enrolments_export.module
- modules/social_features/social_event/modules/social_event_enrolments_export/src/Plugin/Action/ExportEnrolments.php
- modules/social_features/social_group/modules/social_group_members_export/social_group_members_export.module
- modules/social_features/social_group/modules/social_group_members_export/src/Plugin/Action/ExportMember.php
- modules/social_features/social_user_export/social_user_export.module
- modules/social_features/social_user_export/src/Plugin/Action/ExportUser.php
Automated security scanning tools report on md5 usage. In these cases it's a false positive, but there's some small room for improvement.
Replace the md5 hashes with an alternative, PHP's built-in `random_bytes()` which we use in combination with bin2hex to generate a unique 16 character string.
https://www.drupal.org/project/social/issues/3413392
N/a
N/a
Minor code improvement replacing MD5 usage to reduce false positives for automated security scanning tools.
N/a
N/a
> Issue #3413392: Replace md5 hash with random_bytes

- modules/social_features/social_user_export/src/Plugin/Action/ExportUser.php
It's recommended to escape formulas in CSV exports.
Follow Symfony's implementation escaping CSV values when they start with a formula character.
https://www.drupal.org/project/social/issues/3414239
N/a
N/a
CSV exports now escape formulas so Spreadsheet software interprets them as text.
N/a
N/a
> Issue #3414239: Escape formulas in CSV exports

- modules/social_features/social_profile/modules/social_profile_organization_tag/social_profile_organization_tag.module
When running the cron the message outputs
LogicException: Render context is empty, because render() was called outside of a renderRoot() or renderPlain() call. Use renderPlain()/renderRoot() or #lazy_builder/#pre_render instead. in Drupal\\Core\\Render\\Renderer->doRender() (line 251 of /app/html/core/lib/Drupal/Core/Render/Renderer.php). {\"severity_level\":3,\"exception\":\"[object] (LogicException(code: 0): Render context is empty, because render() was called outside of a renderRoot() or renderPlain() call. Use renderPlain()/renderRoot() or #lazy_builder/#pre_render instead. at /app/html/core/lib/Drupal/Core/Render/Renderer.php:251)\"}
Replace the render for renderPlain in the social_profile_organization_tag.module
https://www.drupal.org/project/social/issues/3413772
Fixed an issue …
> Issue #3413772 - Render context empty when mentioning users

- .github/workflows/behat.yml
Reverts goalgorilla/open_social#3648
Ran into: https://github.com/actions/upload-artifact/issues/478 
So we need to fix this first.
> Revert "Bump actions/upload-artifact from 3 to 4"

- modules/custom/social_lazy_loading/social_lazy_loading.install
In https://www.drupal.org/node/3173719 we already switched to native lazy loading for images.
It's now time to also move to that for iframes, which we use in our `social_embed` using the same native functionality as images use https://web.dev/articles/iframe-lazy-loading
This has added benefit we can remove javascript in the future, as well as have it work better in a webview on a native app.
Currently we use the https://www.drupal.org/project/lazy module for iframes, this uses a text filter and adds either javascript and classes to lazy load images or lets us use the native browser behavior.
Currently we prefer the native solution, so this is something we want to install by default. 
In the future we will deprecate our `social_lazy_loading` and use this by default. …
> Issue #3415514 by ronaldtebrake: Prefer native lazy loading

- modules/custom/social_demo/content/entity/group.yml
- modules/custom/social_demo/eaa/content/entity/group.yml
As part of the group migration we're removing all the old group types. For local development and quick set-up we have a bunch of demo content, but this still uses the old group types. Ideally we really should be using our new flexible group types.
Replace the old group types with the corresponding flexible group types in the demo content.
https://www.drupal.org/project/social/issues/3380714
Subtask https://getopensocial.atlassian.net/browse/PROD-27946
> Issue #3380714: Replace legacy group types with flexible groups in demo content

- tests/behat/features/bootstrap/FileContext.php
As a developer I want to test if certain download url can be accessed by checking response code (200, 404, 403,..) and response headers.
Provide 3 new Behat test steps:
@When I try to download :url
@then I should see response status code :statusCode
@Then I should see in the response header :header with :value
Example:
Given I am logged in as "user"
When I try to download "/download-url"
Then I should see response status code 200
And I should see in the response header "Content-Type" with "application/pdf"
[3415923](https://www.drupal.org/project/social/issues/3415923)
N/A
N/A
We added 3 new Behat test steps:
- @When I try to download :url
- @Then I should see response status code :statusCode
- @Then I should see in the response header :header with :value
N/A
N/A
> Issue #3415923: Add new Behat test steps for validating download urls

- tests/behat/features/bootstrap/GroupContext.php
Improve Behat test step in a way that group with multiple "Group content visibility options" can be created
At the moment it is only possible to set singe value for "Group content visibility options" with "@Given groups:"
```
Given groups:
| author | title    | description     | author   | type        | language | field_group_allowed_visibility
| user-1 | My title | My description  | username | open_group  | en       | public
| ...    | ...      | ...             | ...      | ...         | ...      | ...
```
[Screenshot](https://www.drupal.org/files/issues/2024-01-19/Screenshot%202024-01-19%20at%2018.45.01.png)
Improve Behat test step in a way that group with multiple "Group content visibility options" can be created
Example:
```
Given groups:
| author | title    | description     | …
```
> Issue #3415933: Improve Behat test step for groups

- modules/custom/social_media_system/config/install/field.storage.media.field_media_file.yml
- modules/custom/social_media_system/config/update/social_media_system_update_12102.yml
- modules/custom/social_media_system/social_media_system.install
In version 12.0.0 `social_media_system` module was added as a helper module for all the default media configurations.
This module provides `field_media_file` which by default uses public uri_scheme.
Change uri_scheme of `field_media_file` from to private by default for better flexibility.
- https://www.drupal.org/project/social/issues/3417652
> Issue #3417652: Change uri_scheme of field_media_file from public to private

- modules/social_features/social_embed/src/Plugin/Filter/SocialEmbedConvertUrlToEmbedFilter.php
- modules/social_features/social_embed/src/Plugin/Filter/SocialEmbedUrlEmbedFilter.php
- phpstan-baseline.neon
In Drupal 10.1 the watchdog_exception function was deprecated to be removed on Drupal 11.
[watchdog_exception() deprecated](https://www.drupal.org/node/2932520)
Replace the deprecated function.
[watchdog_exception() deprecated](https://www.drupal.org/node/2932520)
[PROD-28009](https://getopensocial.atlassian.net/browse/PROD-28009)
[#3417867](https://www.drupal.org/project/social/issues/3417867)
N/A
That is a treatment to unexpected error and can't be tested.
N/A
N/A
N/A
[PROD-28009]: https://getopensocial.atlassian.net/browse/PROD-28009?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Issue #3417867: Replace watchdog_exception deprecated function

- modules/social_features/social_event/social_event.module
- phpstan-baseline.neon
In Drupal 10.1 the system_time_zones() function was deprecated to be removed on Drupal 11.
https://www.drupal.org/node/3023528
Replace the deprecated function, get example at: https://www.drupal.org/node/3023528
[PROD-28012](https://getopensocial.atlassian.net/browse/PROD-28012)
[#3418911](https://www.drupal.org/project/social/issues/3418911)
N/A
N/A
N/A
N/A
N/A
N/A
[PROD-28012]: https://getopensocial.atlassian.net/browse/PROD-28012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Issue #3418911: Replace system_time_zones() deprecated function

- composer.json
- modules/social_features/social_post/src/Plugin/views/area/SocialPostPostForm.php
Ctools is no longer a required dependency, as it was remove from https://www.drupal.org/project/pathauto/releases/8.x-1.11
Remove the dependency.
https://www.drupal.org/project/social/issues/3418675
Removed ctools from our dependency, as it is no longer needed.
> Issue #3418675 by nkoporec : Remove drupal/ctools as dependency from our composer.json

- composer.json
We're currently getting quite some issues which are in the form of:
```
Error getting exif ('Orientation') metadata for [IMAGENAME]. Message: Size of Canon Camera Settings does not match the number of entries. []
```
Although this needs to have a fix upstream (see related drupal.org issue) it seems that's far from available. The attached patch is the one from the merge request from the linked issue made by the maintainer, which isn't ideal just removing it, but considering it's the maintainers choice for now perhaps our best bet especially as it's linked to the issue in the contrib module, which makes it easier for us to track it's progress.
Manual testing (and the fact it returns NULL on error) seems like there isn't much of a downside to suppress the error for now, alternatively if this …
> Issue #3408735 - Error suppression for file_mdm exif metadata issues.

- modules/social_features/social_group/modules/social_group_migration_test/README.md
- modules/social_features/social_group/modules/social_group_migration_test/social_group_migration_test.info.yml
- modules/social_features/social_group/modules/social_group_migration_test/social_group_migration_test.install
- modules/social_features/social_group/social_group.install
⚠️ This should be merged after https://github.com/goalgorilla/open_social/pull/3692
⚠️ This PR is part of a set of stacked commits please do not rebase this PR but instead ping @Kingdutch
We have platforms with a lot of old groups for the old types (public, open, closed, secret) which we want to migrate to the flexible group type. Because there are a lot of these groups with associated content and relationships we need to be efficient in our update hooks and can not load entities into memory while migrating them.
We provide a set of update hooks with custom crafted queries. This allows the migration to happen in-database which drastically speeds the migration up and allows the migration to happen with minimal memory consumption.
We migrate all the available plugins and roles.
We provide a …
> Issue #3380714: Create update hook to migrate old group types to flexible groups

- modules/social_features/social_event/social_event.module
- phpstan-baseline.neon
Even when 'event enrollment' has been disabled, the platform shows '0 attendees,' visible from a site manager and verified user account.
Hide the enrollments counter if "Enable event enrollment" for the event is disabled.
- https://www.drupal.org/project/social/issues/3419202
- https://getopensocial.atlassian.net/browse/PROD-26090
n/a
**Before**
**After**
Hide the enrollments counter if "Enable event enrollment" for the event is disabled.
> Issue #3419202: Hide event enrollments count if enrollment is disabled

- modules/social_features/social_event/social_event.module
Event with view mode "Featured" still "ongoing" after the event ends.
Invalidate cache for ongoing Events.
- https://getopensocial.atlassian.net/browse/PROD-27131
- https://www.drupal.org/project/social/issues/3402828
N/A
> Issue #3402828: Invalidate cache for ongoing Event

- modules/social_features/social_group/modules/social_group_invite/config/optional/views.view.social_group_invitations.yml
- modules/social_features/social_group/modules/social_group_invite/config/update/social_group_invite_update_12001.yml
- modules/social_features/social_group/modules/social_group_invite/social_group_invite.install
- modules/social_features/social_group/modules/social_group_invite/src/Plugin/Action/SocialGroupInviteRemove.php
- modules/social_features/social_group/modules/social_group_invite/src/Plugin/Action/SocialGroupInviteResend.php
- translations.php
Currently, it's not possible to add translations for "Send reminders/Remove" invites actions buttons on the group invitation-overview page
Tthe idea is to fix it directly in the plugin action social_group_invite_resend_action instead of overriding the label in the views.
- https://www.drupal.org/project/social/issues/3420469
- https://getopensocial.atlassian.net/browse/PROD-27569
N/A
Before:
After:
Fixes a translation issue for "Send reminders/Remove invites" actions buttons on the group invitation-overview page
N/A
> Issue #3420469 by SV: Translate "Send reminders/Remove invites" actions buttons on the group invitation-overview page

- .tugboat/composer.json
We are currently using drush 12 but our tugboat QA environment is still running drush 11. To make sure everything behaves in the same way we should also update our tugboat.
Update drush to version 12
Internal issue - no tracker
Internal: We have updated the tugboat environment to use drush 12 to keep it the same as our clients use.
> Internal: Update our tugboat to use drush 12

- modules/social_features/social_follow_user/src/Form/SocialFollowUserSettingsForm.php
- phpstan-baseline.neon
In Drupal 10.2 the system_time_zones() function was deprecated to be removed on Drupal 11.
https://www.drupal.org/node/3349759
Replace the deprecated function, get example at: https://www.drupal.org/node/3349759
[PROD-28013](https://getopensocial.atlassian.net/browse/PROD-28013)
[#3418930](https://www.drupal.org/project/social/issues/3418930)
N/A
N/A
N/A
N/A
N/A
N/A
[PROD-28013]: https://getopensocial.atlassian.net/browse/PROD-28013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Issue #3418930: Replace user_role_names() deprecated function

- .github/workflows/behat.yml
- .github/workflows/qualityChecks.yml
v3 uses a deprecated Node.js version (16);
the only change for v4 is updating to Node.js version 20. We don't use Node.js ourselves and the change is only in the scope of the action, so it doesn't affect us.
Internal no ticket
> Internal: update actions/cache to v4

- modules/social_features/social_topic/config/install/core.entity_view_display.node.topic.activity.yml
- modules/social_features/social_topic/config/install/core.entity_view_display.node.topic.activity_comment.yml
- modules/social_features/social_topic/config/install/core.entity_view_display.node.topic.default.yml
- modules/social_features/social_topic/config/install/core.entity_view_display.node.topic.hero.yml
- modules/social_features/social_topic/config/install/core.entity_view_display.node.topic.search_index.yml
- modules/social_features/social_topic/config/install/core.entity_view_display.node.topic.teaser.yml
- modules/social_features/social_topic/config/update/social_topic_update_130000.yml
- modules/social_features/social_topic/social_topic.install
https://www.drupal.org/project/social/issues/3420092
The references to specific group types have been removed from the user view modes in `social_topic`.
> Issue #3420092: Remove references to public_group, open_group, closed_group, and secret_group for social_topic module

- composer.json
- modules/social_features/social_core/social_core.services.yml
- modules/social_features/social_core/src/Service/LayoutService.php
- modules/social_features/social_core/src/SocialCoreServiceProvider.php
- phpstan-baseline.neon
⚠️ Depends on socialblue 2.5.6
After update to Drupal 10, the service 'social_core.layout' can't be declared via SocialCoreServiceProvider.
Declare service 'social_core.layout' in .yml file and use it via \Drupal::service()
- https://getopensocial.atlassian.net/browse/PROD-27877
- https://www.drupal.org/project/social/issues/3405938
- https://www.drupal.org/project/socialbase/issues/3405919
Test with updated Socialbase theme
> Issue #3405938: Declare social_core.layout in social_core.services.yml

- composer.json
When adding a video via the media embed button of a topic, after having clicked on the ok, the video is well embedded, but the whole topic is frozen and it is impossible to save and publish the topic anymore.
Add a patch #2 from https://www.drupal.org/project/drupal/issues/3409505
- https://www.drupal.org/project/social/issues/3422423
- https://getopensocial.atlassian.net/browse/PROD-28307
- https://www.drupal.org/project/drupal/issues/3409505
n/a
Fix embedding a video during content creation which might freeze the page and prevent saving/publishing.
> Issue #3422423: Embedding a video in a Topic content type freezes the page and prevents saving/publishing

- modules/social_features/social_page/config/install/core.entity_view_display.node.page.activity.yml
- modules/social_features/social_page/config/install/core.entity_view_display.node.page.activity_comment.yml
- modules/social_features/social_page/config/install/core.entity_view_display.node.page.default.yml
- modules/social_features/social_page/config/install/core.entity_view_display.node.page.hero.yml
- modules/social_features/social_page/config/install/core.entity_view_display.node.page.search_index.yml
- modules/social_features/social_page/config/install/core.entity_view_display.node.page.small_teaser.yml
- modules/social_features/social_page/config/install/core.entity_view_display.node.page.teaser.yml
- modules/social_features/social_page/config/update/social_page_update_130000.yml
- modules/social_features/social_page/social_page.install
https://www.drupal.org/project/social/issues/3420094
The references to specific group types have been removed from the user view modes in `social_page`.
> Issue #3420094: Remove references to public_group, open_group, closed_group, and secret_group for social_page module

- modules/social_features/social_event/config/install/core.entity_view_display.node.event.activity.yml
- modules/social_features/social_event/config/install/core.entity_view_display.node.event.activity_comment.yml
- modules/social_features/social_event/config/install/core.entity_view_display.node.event.default.yml
- modules/social_features/social_event/config/install/core.entity_view_display.node.event.hero.yml
- modules/social_features/social_event/config/install/core.entity_view_display.node.event.search_index.yml
- modules/social_features/social_event/config/install/core.entity_view_display.node.event.small_teaser.yml
- modules/social_features/social_event/config/install/core.entity_view_display.node.event.teaser.yml
- modules/social_features/social_event/config/update/social_event_update_130000.yml
- modules/social_features/social_event/modules/social_event_invite/config/update/social_event_invite_update_13000.yml
- modules/social_features/social_event/modules/social_event_invite/social_event_invite.install
- modules/social_features/social_event/social_event.install
https://www.drupal.org/project/social/issues/3420096
The references to specific group types have been removed from the user view modes in `social_event`.
> Issue #3420096: Remove references to public_group, open_group, closed_group, and secret_group for social_event module

- .github/workflows/behat.yml
- .tugboat/config.yml
We are currently having issues with SOLR 9 behat tests where it cannot send requests to solr as its unreachable.
For now this is blocking behat test on the main branch so we should switch back to 8.11 until we figure out the issue
https://getopensocial.atlassian.net/browse/PROD-28309
> Internal: Revert solr in github actions/tugboat back to 8.11

- modules/social_features/social_album/social_album.install
There was a copy paste error which was not caught until we merged things to main and PHPStan started to complain about the wrong function name.
Unreleased hotfix for https://github.com/goalgorilla/open_social/pull/3774 no issue
> Internal: Fix hook_dependencies name in social_album

- .github/workflows/behat.yml
- tests/default.settings.php
We saw errors in the CI installer for e-mails because the settings are not correct until the site is installed. By moving the settings into the test's default.settings.php instead we ensure these settings are also correct during installation.
> Internal: Move mail config into settings.php

- .github/workflows/behat.yml
- tests/default.settings.php
The `$drupal_settings` variable is something from the olden days and no longer used. We just want to load a local settings file whenever it exists regardless of where we are (the file itself is ignored by git so it'll only every contain local settings).
Internal: no issue
> Internal: remove drupal_settings from tests/default.settings.php

- .github/workflows/behat.yml
- modules/social_features/social_group/modules/social_group_flexible_group/config/modify/social_group_flexible_group.search.yml
- modules/social_features/social_search/config/install/search_api.index.social_groups.yml
- modules/social_features/social_search/config/install/views.view.search_groups.yml
- tests/default.settings.php
In the migration from old group types to flexible groups we added a field to the group search. However that field doesn't exist if flexible groups isn't enabled and the search will be installed before flexible groups. So to make sure the search config is valid we need to make sure that the flexible group module adds the field rather than it being in the social_search module.
We don't yet move the entire index and view for two reasons:
1) There's plans to merge the group index into `all` at which point we'll also have to move the field indexing, but that's out of current scope and already in motion elsewhere (profile refactor).
2) We want to have the `group` view in `flexible_group` because the view should only show flexible groups. However, currently it's also still used to show …
> Internal: Move flexible group specific field from search to flexible group module

- .github/workflows/behat.yml
- modules/social_features/social_group/modules/social_group_flexible_group/config/modify/social_group_flexible_group.search.yml
- modules/social_features/social_search/config/install/search_api.index.social_groups.yml
- modules/social_features/social_search/config/install/views.view.search_groups.yml
- tests/default.settings.php
Drush doesn't actually exit if there's an error during installation which is really annoying. We found out because our CI was passing even though the installer threw errors.
To fix this we apply a similar fix which we previously applied in the update steps which captures and checks the output text to check if there's any errors.
Internal CI fix no change
> Internal: Ensure there are no install errors

- modules/social_features/social_core/social_core.install
The Admin Toolbar Tools module would be uninstalled from [#3385341](https://www.drupal.org/project/social/issues/3385341), but it ins't uninstalled from all because the required-by skip couple installation.
Create a hook-update to uninstall Admin Toolbar Tools if it isn't be required by an enabled module.
[PROD-28317](https://getopensocial.atlassian.net/browse/PROD-28317)
[#3423203](https://www.drupal.org/project/social/issues/3423203)
N/A
N/A
N/A
N/A
N/A
N/A
[PROD-28317]: https://getopensocial.atlassian.net/browse/PROD-28317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Issue #3423203: Uninstall admin_toolbar_tools module

- composer.json
We're requiring address 2.0, but a lot of dependencies don't have the requirement yet. This happened in: https://github.com/goalgorilla/open_social/pull/3667
Which means we could run in a scenario where people are blocked with our 13.0.0 release, just by the fact we're requiring only the 2.0 version, where address is still maintaining it's 1.x version.
For now we're accepting both versions, and later we could require it solely. This should mean if nothing is blocking 2.0.0 from being installed we use that. Otherwise giving people the time to make that move.
https://www.drupal.org/project/social/issues/3415353
Shouldn't be necessary, already part of #3667 
Internal.
> Internal: Make sure we also still accept the old `drupal/address` version of 13.0.0

- modules/social_features/social_embed/src/Plugin/Filter/SocialEmbedConvertUrlToEmbedFilter.php
- modules/social_features/social_embed/src/Plugin/Filter/SocialEmbedUrlEmbedFilter.php
- modules/social_features/social_embed/src/Service/SocialEmbedHelper.php
- phpstan-baseline.neon
There are inconsistencies with whitelisted embedding and auto-linking URLs in posts
- For supported sources we need to make sure that the regular expression is working correctly and that also allows to embed these URL when they start with https, http etc( https://, http:// or [www.facebook.com](http://www.facebook.com/) or facebook.com)
- For NOT supported sources (sources that are not in our list here [https://github.com/goalgorilla/open_social/blob/main/modules/social_feat...](https://github.com/goalgorilla/open_social/blob/main/modules/social_features/social_embed/src/Service/SocialEmbedHelper.php#L123)) we should never embed anything and always display the URL as a link
- When I add several links after each other they should all behave as in the criteria above
**Supported sources …
> Issue #3421184: Fix incorrect URL embedding

- composer.json
- modules/social_features/social_group/social_group.info.yml
- modules/social_features/social_group/social_group.install
For the group upgrade, there is a new [dependency](https://www.drupal.org/node/3281065), and in the [release notes](https://www.drupal.org/project/group/releases/2.0.0) we have the following note:
> flexible_permissions module should be enabled before group upgrade
Add and enable **flexible_permissions** module as a dependency of **social_group**.
- https://www.drupal.org/project/social/issues/3427372
- https://getopensocial.atlassian.net/browse/PROD-26913
- https://www.drupal.org/node/3281065
N/A
This module provides only helper services, so passing automated tests and checks should be enough. 
Add a new flexible_permissions module that will be required for the upcoming group upgrade to version 2.
N/A
> Issue #3427372 by SV: Add flexible_permissions module

- modules/custom/social_demo/src/DemoGroup.php
Follow up for https://github.com/goalgorilla/open_social/pull/3691#discussion_r1465960151
Demo groups can be created with visibility fields.
n/a
n/a
n/a
n/a
n/a
n/a
n/a
> Issue #3380714: Demo groups can be created with visibility fields

- .github/workflows/bestPractices.yml
- .github/workflows/bestPracticesFeedback.js
We see a lot of "helper" OOP objects being introduced but have found that these are often very difficult to maintain. Their usage can spread out to many different files and it's often unclear what the goal of the helper class is beside deduplicating some code. This makes refactoring it without breaking consuming code very difficult.
This commit extends our best practices workflow to flag helper classes being added (we ignore existing ones being modified) and also extends our workflow with a GitHub script that will post a message explaining both the config overrides and the helper method errors. The script creates a comment that it keeps updated based on the status and will clean up the comment when the issues are resolved.
The script is introduced as a standalone JavaScript file which …
> PROD-29280: Ban helper OOP pattern

- cspell.baseline.txt
- modules/social_features/social_comment/config/install/views.view.comment.yml
- modules/social_features/social_comment/config/update/social_comment_update_12201.yml
- modules/social_features/social_comment/social_comment.info.yml
- modules/social_features/social_comment/social_comment.install
- modules/social_features/social_user/config/install/views.view.user_admin_people.yml
- modules/social_features/social_user/config/update/social_user_update_12201.yml
- modules/social_features/social_user/social_user.install
When I type user's First Name and Last Name (for existing user) in search input on admin/content/comments and /admin/people pages, I see "No people available."
**For _/admin/content/comments_ view page:**
- Add hidden fields First Name, Last Name
- In the combined filter include new added fields
- In the combined filter change search operator to "allwords"
**For _/admin/people_ view page:**
- In the combined filter change search operator to "allwords"
- https://www.drupal.org/project/social/issues/3436775
- https://getopensocial.atlassian.net/browse/PROD-28076
n/a
Fix filtering by First Name and Last Name in search input on `admin/content/comments` and `admin/people` pages.
> Issue #3436775: No results when filtering by User on `admin/content/comments` and `admin/people`

- modules/social_features/social_event/modules/social_event_managers/src/Form/SocialEventManagersViewsBulkOperationsConfirmAction.php
- modules/social_features/social_group/modules/social_group_gvbo/src/Form/SocialGroupViewsBulkOperationsConfirmAction.php
- tests/behat/features/capabilities/event-an-enroll/event-bulk.feature
- translations.php
This bug is actual for events and groups. There are typos on the following confirmation pages:
- _/group/{group}/membership/configure-action_ - "Are you sure you want to send your email to to the following %count members?"
- _/node/{node}/all-enrollments/confirm-action_ - "Are you sure you want to send your email to to the following %count enrollees?"
Remove extra "to" in:
- SocialEventManagersViewsBulkOperationsConfirmAction.php
- SocialGroupViewsBulkOperationsConfirmAction.php
- event-bulk.feature
- https://www.drupal.org/project/social/issues/3439386
- https://getopensocial.atlassian.net/browse/PROD-28632
Fix a typo and remove the extra "to" in enrolees/members form confirmation messages.
> Issue #3439386: Remove extra "to" in enrolees/members form confirmation messages

- modules/custom/activity_creator/src/ActivityFactory.php
Open Social uses so called "activities" when creating content. For example when creating a topic it will also create an activity to show this on the activity stream.
These activities have referenced objects, but in some cases it can be that a user create a topic, but later on deleted it again. Depending on the run-time of the cron it can happen that there is still a queue item, but not reference item anymore. The cron will then fail as it cannot retrieve this piece of content.
Add some defensive checks to make sure the related object exist before creating the activity
https://www.drupal.org/project/social/issues/3439974
Internal: We have added extra validation in the activity creator to make sure referenced entities exist before processing them, avoiding crashes with the cron, or empty …
> Issue #3439974: Activity creator breaking down when the referenced entity does not exist

- modules/social_features/social_page/config/install/node.type.page.yml
- modules/social_features/social_page/config/update/social_page_update_130001.yml
- modules/social_features/social_page/social_page.install
- tests/behat/features/capabilities/landing-page/custom-content-list.feature
- tests/behat/features/capabilities/page/page-create.feature
Customers have indicated that the basic page label gets in the way. An underlying assumption is that they use these pages for generic website content and thus the type of content is less important. 
Rename "Basic Page" content type label into "Page". 
We must make sure the existing tests will pass.
- https://getopensocial.atlassian.net/browse/PROD-24397
- https://www.drupal.org/project/social/issues/3442690
N/A
Rename "Basic Page" content type label into "Page".
> Issue #3442690: Rename "Basic Page" content type label into "Page"

- modules/social_features/social_album/social_album.module
There is no ability to edit an Album on the Album page.
You can do it only from the `/{group}/albums` page as a content manager or Album owner.
Add the "Edit" link to the right top menu on the Album page for users with edit access.
- https://www.drupal.org/project/social/issues/3438906
- https://getopensocial.atlassian.net/browse/PROD-27132
Add the "Edit" link to the right top menu on the Album page for users with edit access.
> Issue #3438906: Add "Edit" link on Album page

- modules/social_features/social_event/config/install/field.field.node.event.field_event_date_end.yml
- modules/social_features/social_event/config/update/social_event_update_130002.yml
- modules/social_features/social_event/social_event.install
- tests/behat/features/capabilities/administration/check-export-users-to-csv.feature
- tests/behat/features/capabilities/event/eventenrollment-manage.feature
- tests/behat/features/capabilities/event/eventenrollment.feature
- tests/behat/features/capabilities/groups/flexible/content/edit/group-manager/groups-flexible-content-edit-group-manager.feature
- tests/behat/features/capabilities/groups/flexible/content/edit/member/groups-flexible-content-edit-member.feature
- tests/behat/features/capabilities/groups/flexible/content/edit/outsider-platform-manager/groups-flexible-content-edit-outsider-platform-manager.feature
- tests/behat/features/capabilities/groups/flexible/content/edit/outsider/groups-flexible-content-edit-outsider.feature
- tests/behat/features/capabilities/groups/flexible/content/view/member/groups-flexible-content-view-member.feature
- tests/behat/features/capabilities/groups/flexible/content/view/outsider-anonymous/groups-flexible-content-view-outsider-anonymous.feature
- tests/behat/features/capabilities/groups/flexible/content/view/outsider-authenticated/groups-flexible-content-view-outsider-authenticated.feature
- tests/behat/features/capabilities/groups/flexible/content/view/outsider-contentmanager/groups-flexible-content-view-outsider-contentmanager.feature
- tests/behat/features/capabilities/groups/flexible/content/view/outsider-sitemanager/groups-flexible-content-view-outsider-sitemanager.feature
- tests/behat/features/capabilities/groups/flexible/content/view/outsider-verified/groups-flexible-content-view-outsider-verified.feature
Currently, end date of an event is an option field. This causes some issues in Calendar block, custom content lists, overviews and more.
We want to make this field required so that when an event is created or edited, these value will have to be provided.
- Make the end date of the event required
- As a Vu+ I need to specify an end date and time when I create or edit an event
- There is a visual indicator that shows that the field is required *
- Make sure that existing events are still working correctly after the update
- When an existing event is edited and saved a validation message should be displayed to require the end date value if not available.
- https://www.drupal.org/project/social/issues/3443501
- https://getopensocial.atlassian.net/browse/PROD-25979
1. Use the open …
> Issue #3443501: Make the end date of the event required

- modules/social_features/social_core/assets/css/preview-el.css
- modules/social_features/social_core/assets/css/preview-el.scss
The preview element has a wrong hover behavior on the teaser.
Reset general and hover styles for the preview element when we use text.
- https://www.drupal.org/project/social/issues/3450286
- https://getopensocial.atlassian.net/browse/PROD-29684
N/A
before:
after:
The text preview element has the correct styles on the general and hover states.
> Issue #3450286: Fix pewview element on the general and hover states

- modules/custom/secret_file_system/src/Controller/SecretFileController.php
Path processors don't run on cached route matches and attributes aren't part of the cached value. This means that our `filepath` attribute isn't available for second requests to our secret file path controller. 
We fixed this issue by reprocessing the URL. However, contrary to the URL in our path processor, the value for our controller on a cached route match has no preprocessing done on it since `PathProcessorDecode` hasn't run in that case.
This means that for image with a space in their name we were unable to find the file on disk and unable to locate the source file since we were looking for files with `%20` in their name. 
See https://www.drupal.org/project/drupal/issues/3085360#comment-15614838 for the full story.
We decode the `$target` which should ensure that we start looking for …
> Hotfix: Decode filepath for cached secret file requests

- composer.json
This PR bumps the version of `data_policy` module to 2.0.1, which contains important bugfixes.
https://www.drupal.org/project/data_policy/releases/2.0.1
- [#3449668: The "data_policy" entity type did not specify a "delete" form class](https://www.drupal.org/project/data_policy/issues/3449668)
- [#3449654: RedirectSubscriber is not redirecting users when there's a new required data policy entity](https://www.drupal.org/project/data_policy/issues/3449654)
- https://getopensocial.atlassian.net/browse/PROD-29567
- https://getopensocial.atlassian.net/browse/PROD-29687
- https://getopensocial.atlassian.net/browse/PROD-29695
- https://getopensocial.atlassian.net/browse/PROD-29920
When we create a new Data Policy entity and set it as required, users were not being redirected to accept the terms. …
> PROD-29920: Bump version of `data_policy` to 2.0.1

- modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install
Migration group_admin to group_manager role should be applied for users that have assigned SM/CM roles and they are already creators of the group
Add additional checks on sitemanager, contentmanager roles and group owner in migration
- https://www.drupal.org/project/social/issues/3455400
- https://getopensocial.atlassian.net/browse/PROD-29829
N/A
This update can be checked only for existing sites during group upgrade when Group Admin is replaced with Group Manager   role only for SM/CM group creators
N/A
Fixes an issue with replacing group_admin with group_manager roles for members.
N/A
N/A
> Issue #3455400: Move group_admin to group_manager group role only for SM/CM creators

- .github/workflows/behat.yml
Now that we have new Docker images with `rdkafka` extension (https://github.com/goalgorilla/open_social_docker/pull/39), we want all of our workflows to use it.
- https://getopensocial.atlassian.net/browse/PROD-29890
> PROD-29890: Update Github workflows to use the new Docker image with `rdkafka`

- modules/social_features/social_event/social_event.module
- modules/social_features/social_event/social_event.services.yml
- modules/social_features/social_event/src/EdaHandler.php
- modules/social_features/social_event/src/Event/EventCreateEventData.php
- phpstan-baseline.neon
This pull request creates the first EDA event "event create" (node/add/event), and dispatches it to the topic `com.getopensocial.cms.event.create`. The event is triggered on `social_event_node_insert`.
It uses the services `Drupal\social_eda_dispatcher\Dispatcher` (to dispatch the event to Kafka) and `social_eda.data_formatter` which makes it easier to format reusable data outputs.
It requires the Cable Car modules `social_eda` and `social_eda_dispatcher`.
This PR requires https://github.com/goalgorilla/cablecar/pull/1755
https://getopensocial.atlassian.net/browse/PROD-29755
The message should be dispatched to Kafka. If you are running locally using the Docker containers, you should be able to see the message on the Kafka UI at http://localhost:8080.
> PROD-29755: Implement "event create" EDA publishing

- .github/workflows/behat.yml
- README.md
- composer.json
- modules/social_features/social_branding/tests/src/Kernel/GraphQL/BrandingGraphQLTest.php
- modules/social_features/social_core/social_core.info.yml
- modules/social_features/social_core/social_core.install
Patches don't apply anymore for #3409370 and #3458790 as they are now merged.
Also in bootstrap 3.32 dependencies got updated but need to be enabled in the profile as they cannot create update hooks in the theme. See https://www.drupal.org/project/bootstrap/releases/8.x-3.32
Remove the patches, and add dependencies to the new modules in our social_core.
https://www.drupal.org/project/socialbase/issues/3467700
Internal: old patches removed and new dependencies added for install.
> PROD-30375: Remove patch from issue #3409370 and #3458790 as they are now merged

- modules/social_features/social_embed/src/Plugin/Filter/SocialEmbedUrlEmbedFilter.php
When the user enables the "_Enforce consent for all embedded content settings_", they will see a consent button on the embedded media preview. However, when the Site Manager creates or edits content with embedded media, they also see this consent button, even on the create or edit page, which they shouldn't.
Add route checking in the process method of SocialEmbedUrlEmbedFilter to avoid adding the placeholder on the `embed.preview` route (this route is used to apply the filter when adding or editing a new embed URL).
- https://www.drupal.org/project/social/issues/3473556
- https://getopensocial.atlassian.net/browse/PROD-30643
Disabled placeholder of Embed URL during creation or editing content.
> Issue #3473556: Disable the placeholder for Embed URL when adding or editing content

- cspell.words.txt
- modules/social_features/social_event/src/EdaHandler.php
- modules/social_features/social_event/tests/src/Unit/EdaHandlerTest.php
- phpstan-baseline.neon
- tests/composer.json
This PR provides the test coverage that was omitted from the acceptance criteria in https://getopensocial.atlassian.net/browse/PROD-29755.
https://getopensocial.atlassian.net/browse/PROD-30133
N/A
Check if all tests passed in the PR.
N/A
N/A
N/A
N/A
> PROD-30133: Implement test coverage for "event create" EDA event

- modules/custom/social_path_manager/social_path_manager.module
- modules/social_features/social_content_report/social_content_report.module
- modules/social_features/social_event/modules/social_event_type/social_event_type.info.yml
- modules/social_features/social_event/modules/social_event_type/social_event_type.module
- modules/social_features/social_event/social_event.install
- modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
- modules/social_features/social_profile/modules/social_profile_fields/social_profile_fields.module
- modules/social_features/social_profile/modules/social_profile_organization_tag/social_profile_organization_tag.info.yml
- modules/social_features/social_profile/modules/social_profile_organization_tag/social_profile_organization_tag.install
- modules/social_features/social_profile/modules/social_profile_organization_tag/social_profile_organization_tag.module
- modules/social_features/social_profile/social_profile.info.yml
- modules/social_features/social_profile/social_profile.install
- modules/social_features/social_profile/social_profile.module
- modules/social_features/social_topic/social_topic.module
- tests/behat/features/bootstrap/EventContext.php
- tests/behat/features/bootstrap/SocialMinkContext.php
- tests/behat/features/bootstrap/TopicContext.php
- tests/behat/features/capabilities/groups/flexible/content/groups-flexible-content-visibility.feature
Reverts goalgorilla/open_social#4087
> Issue #3476285: Revert #4087 - Improve usability of Taxonomy term creations

- composer.json
- modules/custom/activity_creator/activity_creator.module
- modules/custom/activity_creator/drush.services.yml
- modules/custom/activity_creator/src/Commands/CleanUpActivitiesDrushCommands.php
Some activities have no related entity after a deletion of the entity. It displays empty blocks of content.
Create a drush command that will clean up all existing activities entity that their related entity has been deleted.
https://getopensocial.atlassian.net/browse/PROD-30862
https://getopensocial.atlassian.net/browse/PROD-30481
- Get the database of Medtech partners on your local
- Get this branch (feature/PROD-30862-delete-orphaned-activity)
- turn on dblog: `drush en dblog`
- Run `drush cleanup-activities`
- check the logs `drush ws`
- you should see 
- `X orphaned activities with target_type "votingapi_vote" have been removed`
- `X orphaned activities with target_type "post" have been removed`
- ... 
Provide a command to clean up orphaned activities.
> PROD-30862: delete orphaned activity

- modules/social_features/social_event/modules/social_event_an_enroll/src/Form/EventAnEnrollActionForm.php
- modules/social_features/social_event/src/Form/EnrollActionForm.php
https://www.drupal.org/project/socialblue/issues/3472973
We have added a throbber in the socialblue theme that is causing issue when a button is just disabled without needing to progress it to another state.
- Remove the throbber and replace it in the Distro with a progress throbber.
https://www.drupal.org/project/social/issues/3473010
https://www.drupal.org/project/socialblue/issues/3472973
As it's theoretically you need to also alter some code in inspector.
We replaced the event enrollment throbber with a default one from Drupal. This should result in no visual change.
> Issue #3473010: Add throbber back to event enrollment.

- modules/custom/social_magic_login/src/Controller/MagicLoginController.php
- modules/social_features/social_content_block/src/ContentTranslationDefaultsConfigOverride.php
- modules/social_features/social_core/src/ContentTranslationDefaultsConfigOverride.php
- modules/social_features/social_event/modules/social_event_managers/src/EventSubscriber/RouteSubscriber.php
- modules/social_features/social_featured_content/src/ContentTranslationDefaultsConfigOverride.php
- modules/social_features/social_featured_items/src/ContentTranslationDefaultsConfigOverride.php
- modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/src/ContentTranslationDefaultsConfigOverride.php
- modules/social_features/social_group/src/Plugin/Field/FieldWidget/SocialGroupSelectorWidget.php
- modules/social_features/social_profile/modules/social_profile_fields/src/Form/SocialProfileFieldsSettingsForm.php
- modules/social_features/social_user/src/Plugin/AdvancedQueue/JobType/UserMailQueueJob.php
- modules/social_features/social_user/src/Plugin/QueueWorker/UserMailQueueProcessor.php
The PR to implement hux is too complex
Replace Modulehandler with ModuleHandlerInterface.
> PROD-30967: Replace ModuleHandler usage with ModuleHandlerInterface

- composer.json
Get the latest changes for the socialblue theme.
Update to 2.6.5
Updated to socialblue 2.6.5
All bugs in the theme release were individually tested already
> Updates: Update to socialblue 2.6.5

- modules/custom/social_lazy_loading/compass.yaml
This file was created but not filled in the original PR that configured Compass. This might be the reason Compass isn't importing any components from the repository.
> Internal: Fill in compass file for Social Lazy Loading

- modules/social_features/social_user/asyncapi.yml
- modules/social_features/social_user/social_user.module
- modules/social_features/social_user/src/EdaHandler.php
- modules/social_features/social_user/tests/src/Unit/EdaHandlerTest.php
> [!CAUTION]
> This PR depends on #4111
This pull request introduces the new EDA event "profile updated" which is dispatches to the Kafka topic `com.getopensocial.cms.profile.update`.
The event is triggered when a user profile is updated (only if any data changes).
```
{
"id": "ccb6623d-4516-41b3-b2fa-5f1af46e1621",
"source": "/user/4/profile",
"type": "com.getopensocial.cms.profile.update",
"time": "2024-10-24T12:17:27Z",
"data": {
"user": {
"id": "44fc2f3a-da2f-11e5-b5d2-0a1d41d68578",
"created": "2024-10-24T12:17:27",
"updated": "2024-10-24T12:17:27",
"displayName": "Michelle Clark",
"firstName": "Michelle",
"lastName": "Clark",
"email": …
```
> PROD-30978: Implement EDA event for when a user profile is updated

- modules/social_features/social_user/asyncapi.yml
- modules/social_features/social_user/social_user.module
- modules/social_features/social_user/src/EdaHandler.php
- modules/social_features/social_user/tests/src/Unit/EdaHandlerTest.php
> [!CAUTION]
> This PR depends on #4151
This pull request introduces the new EDA event "user logs out" which is dispatches to the Kafka topic `com.getopensocial.cms.user.logout`.
```
{
"id": "0cf6cf17-ca0e-4bdd-b791-b3c77a34d300",
"source": "/user/logout",
"type": "com.getopensocial.cms.user.logout",
"time": "2024-10-24T12:15:59Z",
"data": {
"user": {
"id": "3cd53a66-b86a-41b4-8225-66eed5bb5fe3",
"created": "2024-10-24T12:15:59",
"updated": "2024-10-24T12:15:59",
"firstName": "",
"lastName": "",
"email": "devel@getopensocial.com",
"roles": [
"administrator"
],
"address": {
"label": "", …
```
> PROD-30975: Implement "user logs out" event for the EDA

- .github/workflows/behat.yml
Step [Install previous Open Social major version](https://github.com/goalgorilla/open_social/actions/runs/11779521056/job/32808141901?pr=4171#logs) was failing
Remove hardcoded version for `drupal/dynamic_entity_reference` and `drupal/core`. etc  from `behat.yml`
Internal.
> Internal: Remove dependency from specific poackages in behat.yml

- composer.json
- modules/social_features/social_core/social_core.info.yml
- modules/social_features/social_core/social_core.install
As outlined in our decision record, we have identified the need to integrate Hux instead of relying on traditional hooks for managing interactions and events wit
We will migrate from the current hook-based implementation to Hux. The Hux library offers a more modern and modular approach for handling events, making the system easier to maintain and extend in the long term.
Blog post on how to: https://www.previousnext.com.au/blog/hux-alternative-to-hooks
Drupal seems to go the same way: https://www.drupal.org/node/3442349
Hook usage is becoming not recommended.
Hux annotation and services usage becomes the recommended way to implement a hook.
> PROD-30967: Add hux module as core dependency

- modules/social_features/social_group/modules/social_group_flexible_group/asyncapi.yml
- modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
- modules/social_features/social_group/modules/social_group_flexible_group/src/EdaHandler.php
- modules/social_features/social_group/modules/social_group_flexible_group/tests/src/Unit/EdaHandlerTest.php
Currently we don't have an EDA event that fires when a group is unpublished.
Implement the new event:
Payload:
```
{
"id": "6602e815-61c9-480c-a5f4-30857bbe1dc7",
"source": "/group/21/edit",
"type": "com.getopensocial.unpublish",
"time": "2024-11-20T07:19:41Z",
"data": {
"group": {
"id": "5cff14e9-0d1d-46a4-9ce1-e3db612b98fc",
"created": "2024-11-20T07:19:41",
"updated": "2024-11-20T07:26:59",
"status": "unpublished",
"label": "New group",
"roles": []
},
"contentVisibility": {
},
"membership": {
"method": "request"
},
"type": null,
"author": {
"href": {
"canonical": …
```
> PROD-31341: Implement group unpublish EDA event

- modules/social_features/social_group/modules/social_group_flexible_group/asyncapi.yml
- modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
- modules/social_features/social_group/modules/social_group_flexible_group/src/EdaHandler.php
- modules/social_features/social_group/modules/social_group_flexible_group/src/Event/GroupEntityData.php
- modules/social_features/social_group/modules/social_group_flexible_group/tests/src/Unit/EdaHandlerTest.php
Currently we don't have an EDA event that fires when a group is published.
Implement the new event:
Payload:
```
{
"id": "83909395-dc40-4ff8-9b57-6fa3392c4128",
"source": "/group/25/edit",
"type": "com.getopensocial.cms.group.publish",
"time": "2024-11-22T13:57:34Z",
"data": {
"group": {
"id": "7c2163c1-28bc-4d6d-b90e-bd1ecc77af7f",
"created": "2024-11-22T13:57:34",
"updated": "2024-11-22T14:06:38",
"label": "Test",
"type": "public",
"roles": []
},
"contentVisibility": "community",
"membership": {
"method": "request"
},
"type": "27aaa381-4322-4096-9cfa-63d4df67d538",
"author": {
"href": {
"canonical": …
```
> PROD-31340: Implement "group publish" event for the EDA

- modules/social_features/social_group/modules/social_group_default_route/src/SocialGroupDefaultRouteRedirectService.php
The error in variable naming
Fix the variable name.
Fixed the code.
> Issue #3481367: Fix SocialGroupDefaultRouteRedirectService

- composer.json
Get the latest changes for the socialblue theme.
[SocialBase 2.6.8](https://www.drupal.org/project/socialbase/releases/2.6.8) and [SocialBlue 2.6.6](https://www.drupal.org/project/socialblue/releases/2.6.6)
**SocialBase:**
- [#3484629: Add bootstrap patch for Drupal 11 compatibility](https://www.drupal.org/project/socialbase/issues/3484629)
- [#3487493: [UI] The Ajax throbber behavior issue](https://www.drupal.org/project/socialbase/issues/3487493)
- [#3486329: [UI] The image resize behavior does not work - CKEditor5](https://www.drupal.org/project/socialbase/issues/3486329)
- [#3490131: I want to see that a Book page is part of a Group](https://www.drupal.org/project/socialbase/issues/3490131)
**SocialBlue:**
- [#3487686: [UI][RTL] Access permissions popover …
> Updates: Update to socialblue 2.6.6

- modules/social_features/social_event/modules/social_event_managers/social_event_managers.module
- modules/social_features/social_event/modules/social_event_managers/social_event_managers.services.yml
- modules/social_features/social_event/modules/social_event_managers/src/EventSubscriber/NodeQueryAccessAlterSubscriber.php
> [!CAUTION]
> [!NOTE]  
Replace `node grants` with query alters for nodes with event managers.
> Issue #3458767: Replace node grants for "social_event_managers" module
