goalgorilla/open_social

modules/social_features/social_book/social_book.module
modules/social_features/social_core/social_core.api.php
modules/social_features/social_core/social_core.module
modules/social_features/social_landing_page/social_landing_page.module
themes/socialblue/theme-settings.php

Make sure that existing content types not served by Open Social can be presented in new content form style as reported during bugfixing day.
Add an alter hook to enable extensions to declare list of node types forms to be included.
https://www.drupal.org/node/3186003
https://getopensocial.atlassian.net/browse/DS-7506
N>A
The extensions/modules which adds a new content type to Open Social default distro will be able to add a hook_social_core_compatible_content_forms_alter to add/modify the list of nodes which can be presented in new content form style.
N.A

Issue #3186003 by navneet0693: Enable extension to declare list of nodes to be presented in new content form style.

---

modules/social_features/social_content_block/modules/social_content_block_landing_page/src/Service/SocialContentBlockLandingPageContentBuilder.php
modules/social_features/social_content_block/src/ContentBuilder.php

Fatal errors after added custom content list block to a landing page or when block Custom content list block placed (exist) on the landing page.
As an Admin, create Custom block on /admin/structure/block/block-content page
go /node/add/landing_page page and add new section with Custom content list block
Add your custom block to that section
Press save button
ER: User can create a landing page with custom block
AR: Server error appears after user clicks Save button
Update ContentBuilder class and method getEntities in child to ContentBuilder classes.
https://www.drupal.org/project/social/issues/3192078
As an Admin, create Custom block on /admin/structure/block/block-content page
go /node/add/landing_page page and add new section with Custom content list block
Add your custom block to that …

Issue #3192078 by laykin: Fatal errors after added custom content list block to a landing page

---

modules/social_features/social_group/src/SocialGroupHelperService.php

There's a notice on almost every page load: `Notice: Trying to access array offset on value of type null in Drupal\social_group\SocialGroupHelperService->getGroupFromEntity() (line 69 of profiles/contrib/social/modules/social_features/social_group/src/SocialGroupHelperService.php).`
Check if the protected cache is an array itself, before trying to access its value.

by jochemvn: fix notice on almost every page load

---

modules/custom/social_graphql/src/GraphQL/EntityConnection.php
modules/custom/social_graphql/tests/src/Kernel/SocialGraphQLTestBase.php
modules/social_features/social_profile/tests/src/Kernel/GraphQLUsersEndpointTest.php
modules/social_features/social_user/tests/src/Kernel/GraphQLUsersEndpointTest.php

The <code>startCursor</code> and <code>endCursor</code> in <code>pageInfo</code> for a paginated result should always correspond to the cursor of the first and last node in the result respectively. This is not currently the case for queries using <code>last</code> in their arguments. Instead the cursors are swapped which breaks automated pagination.
<ul>
<li>Ensure that this scenario is properly detected by tests.</li>
<li>Use the correct cursors</li>
</ul>
https://www.drupal.org/project/social/issues/3192835
You expect to see the five results before the first 5 result but instead get one result before the first 5 results and the first 4 results of the 5 other results. …

[GraphQL] pageInfo cursors are incorrect for `last` based queries

---

themes/socialbase/assets/css/modal.css
themes/socialbase/assets/css/popover.css
themes/socialbase/components/03-molecules/popover/popover.scss
themes/socialbase/components/04-organisms/modal/modal.scss

The popover information is overlapped with the toolbar menu on the flexible group create page.
The different styles for the modal close button.
Add style updates for the popover if the gin theme is active,
Make the same behavior for all modal close buttons.
https://getopensocial.atlassian.net/browse/YANG-4560
https://getopensocial.atlassian.net/browse/YANG-4561
https://www.drupal.org/project/social/issues/3191823
*For example*
before:
after:
The popover has a correct position if the Gin theme is active.
The general modal close buttons have the same behavior and styles.
-
-

Issue #3191823 by agami4: UI issues with popover and modal close button

---

themes/socialbase/assets/css/form-controls.css
themes/socialbase/components/02-atoms/form-controls/_radio-checkbox.scss

Adjust the topic/event type radio buttons - show them inline
Make the topic/event type radio buttons on one line
https://getopensocial.atlassian.net/browse/DS-7430
https://getopensocial.atlassian.net/browse/DS-7439
*For example*
The topic/event type radio buttons on one line
-
-

DS-7430-7439: Add updates for the radio buttons

---

modules/social_features/social_post/modules/social_post_album/templates/image-widget--album.html.twig

Add image button text should become add images.
Changed button text.
https://www.drupal.org/project/social/issues/3172477
https://www.drupal.org/project/social/issues/3177902
Not needed.

Issue #3172477 by nachosalvador: DS-7488 Modify add image button text.

---

modules/social_features/social_follow_taxonomy/assets/js/follow_popup.js
modules/social_features/social_follow_taxonomy/modules/social_follow_tag/social_follow_tag.module

Follow taxonomy issues for 10.x release
- When the user follows a tag there should be a star icon after the tag.
- User cannot follow the parent content tag
Fix existing issues
https://www.drupal.org/project/social/issues/3193963
https://getopensocial.atlassian.net/browse/YANG-4717
https://getopensocial.atlassian.net/browse/YANG-4716
N/A
Now users can follow the parent term.
N/A
N/a

YANG-4717 by tBKoT: Add ability to follow a parent tag and improve star icon appearing

---

composer.json

This commit removes the patch for interfaces implementing interfaces support
since the functionality has been merged into the module. The new minor version
is within the version constraints of `drupal/graphql` which causes it to be installed,
this then causes the patch to fail to apply.
We can safely remove the patch but must add our own requirement on a minimum
version to ensure that we have the new feature that we require. Using `>=` is fine here
because it allows `drupal/graphql` to supply the actual constraint and it allows us to 
update with that module to newer major versions, since the Drupal module contains most
of the surface that affects us in terms of compatibility.
https://www.drupal.org/project/social/issues/3194508
webonyx/graphql-php release notes: …

Require minimum 14.5.0 of webonyx/graphql-php

---

modules/custom/social_graphql/tests/src/Kernel/SocialGraphQLTestBase.php

This PR should be merged after #2183 but contains both for easier conflict resolution :D 
Open Social currently provides a test base to test the pagination on endpoints according to the Relay connection specification. However, it only supports this for top level paginated fields, not for fields that are under a different type than <code>Query</code>. Additionally the testing currently only tests the default sort and doesn't allow testing any other sort order.
<h4 id="summary-steps-reproduce">Steps to reproduce</h4>
Implement the ability to specify parent fields and a sort key for the pagination test methods.
https://www.drupal.org/project/social/issues/3194731
N/a …

[GraphQL] Improve nested pagination and sorting tests

---

modules/social_features/social_follow_content/social_follow_content.module

The social_follow_content module comes with a hook to alter the content types that get auto-followed when commented on. However, the types themseleves are never actually checked so all content types are automatically followed.
Check if the commented on node's type is in the types array before auto-following.
https://www.drupal.org/project/social/issues/3100728
There's a pretty good chance that there are people out there unwittingly taking advantage of this bug to auto-follow their own custom content types in their OS installations. Fixing this bug will break that functionality for them. Not sure what the best way to handle this is? Release notes maybe... or maybe we reverse the hook and make it an exclude? Open to suggestions but for now this PR just adds what I believe to be the …

Follow content types are never actually checked

---

modules/social_features/social_user/src/Plugin/Block/AccountHeaderBlock.php

After a user has logged in and it clicks on its user profile icon it is presented with "Signed in as" and followed by current user's display name on next line. it would really great if it becomes clickable and links to user profile page.
Link account display after 'Signed in as' in AccountHeaderBlock to user profile page.
https://www.drupal.org/project/social/issues/3195069
We have updated the account header block which contains the user menu. Now, when a user will click it's own display name it will be link to it's own profile page.
N.A
N.A

Issue #3195069 by navneet0693: Link account display name in account header block to user profile page.

---

modules/social_features/social_core/social_core.module

After a user selects the crop for image on events page after saving they are presented with status messages. These messages are not useful for the user.
Unset the Drupal status messages coming from image_widget_crop module.
https://www.drupal.org/project/social/issues/3195131
**Before**
**After**
We have removed the unwanted messages about the cropping of images which user might have seen while after adding/editing a content on the platform.
N.A
N.A

Issue #3195131 by navneet0693: Remove status messages from image_widget_crop module.

---

modules/social_features/social_user/src/Plugin/GraphQL/DataProducer/Viewer.php
modules/social_features/social_user/src/Plugin/GraphQL/SchemaExtension/UserSchemaExtension.php

Want to re-use the loaded current user on different fields.
This is slightly simplified from the previously composed dataproducers.
It also ensures that the viewer can be easily injected in viewer
specific fields on other types.
N/a internal unreleased refactoring.
*For example*
N/a code only
N/a internal unreleased refactoring.

[GraphQL] Implement dedicated viewer producer

---

composer.json
modules/social_features/social_album/social_album.module
modules/social_features/social_album/src/Plugin/Field/FieldWidget/SocialAlbumOptionsSelectWidget.php
modules/social_features/social_album/src/SocialAlbumConfigOverride.php
modules/social_features/social_post/src/Form/PostForm.php

1) When adding post albums to existing albums from the post form, the context of existing albums is causing potential security issues where the post visibility isnt updated according to the album context. Also bugfixed the creation of albums from the Post form, to ensure it gets the visibility defaulted from the post on creation.
2) When adding an album through node/add/album if you select an existing group the visbility isn't updated accordingly
3) Ensure we can't update the "group" section on edit anymore, as we dont have a bulk update for the post and its comments inside an album
1) Removed existing options for now, so we can only add it directly to a newly created Album
Make sure the newly created Album either personal or within a group is using the post visibility field as the …

DS-7491 - Issues with Albums added to existing albums from the post form

---

modules/social_features/social_user/graphql/social_user_schema_extension.extension.graphqls
modules/social_features/social_user/src/Plugin/GraphQL/DataProducer/QueryUser.php
modules/social_features/social_user/src/Plugin/GraphQL/SchemaExtension/UserSchemaExtension.php
modules/social_features/social_user/tests/src/Kernel/GraphQL/GraphQLUsersEndpointTest.php
modules/social_features/social_user/tests/src/Kernel/GraphQL/GraphQLViewerEndpointTest.php

This is a shorter name and better matches other places of fields that
relate to information about the current actor. Other GraphQL APIs also
already commonly use this name for the field, most notably the GitHub
API.
Tests are adapted to use the built-in assertResults trait instead of
manually executing and matching the query. This requires adding some
cache metadata to match with. This cache metadata is not necessarily
what we want it to be yet but it provides us a place to change our
expectations and implement a fix.
N/a unreleased internal change
N/a API only
N/a unreleased internal change
N/a unreleased internal change

Rename `currentUser` field to `viewer`

---

modules/custom/activity_creator/activity_creator.tokens.inc
modules/social_features/social_private_message/src/Plugin/UserExportPlugin/UserAnalyticsPrivateMessage.php
modules/social_features/social_profile/social_profile.module
modules/social_features/social_user_export/src/Plugin/UserExportPluginBase.php
tests/behat/features/capabilities/security/private-file-uploads.feature

PHPstan encountered some new issues, these are fixed.
We see the private file upload test fail regularly as a false negative on travis, lets see if this makes it more robust.
Updated the `Variable ... in PHPDoc tag @var does not exist` issues
Updated the private file test to not use a label but the id of the input itself
None - Internal robustness.
None needed.
None needed.

[Internal] - Fix phpstan latest issues + stability on the private file upload test

---

modules/social_features/social_profile/social_profile.module
tests/behat/features/capabilities/landing-page/featured-profile-create.feature

Profile teasers added as "featured content" items on landing pages do not display for non-logged-in users. Page permissions are set to public and it is a bit confusing that added block displays as empty
Provides access for AN (users who don't have `view any profile profile` permission) to preview teasers profiles but only for landing & dashboard pages.
- https://www.drupal.org/project/social/issues/3197235
- https://getopensocial.atlassian.net/browse/SUP-560
*For example*
Create a section with profiels:
Landing page for LU
Landing page for AN
Allow view profile teasers which added as "featured content" items on landing or dashboard pages for anonymous users.

Issue #3197235 by SV: Display featured profile section for anonymous users

---

modules/custom/social_graphql/graphql/open_social.graphqls
modules/custom/social_graphql/src/GraphQL/ResolverRegistry.php
modules/custom/social_graphql/src/GraphQL/Violation.php
modules/custom/social_graphql/src/Plugin/GraphQL/DataProducer/Payload/PayloadViolations.php
modules/social_features/social_user/src/Plugin/GraphQL/DataProducer/UserFromWrapper.php
modules/social_features/social_user/src/Wrappers/UserAwareInterface.php

Violations can't currently be output. Before we fix [#3191621] this is a quick fix to make sure that violations can actually be accessed.
Fix the string representation.
https://www.drupal.org/project/social/issues/3199146
N/A Unsupported internal change

Issue #3199146: [GraphQL] Improve Violation representation

---

modules/social_features/social_footer/config/optional/block.block.socialblue_footer_powered.yml
modules/social_features/social_swiftmail/social_swiftmail.module

Hashtags are more accessible when the individual words are capitalised: https://www.boia.org/blog/make-your-hashtags-accessible
Capitalise the individual words of the hashtag. This improves readability for sighted users and ensures proper
pronounciation for screenreaders. An all-around accessibility win.
Tagged as bugfix as per our accessibility considerations.
https://www.drupal.org/project/social/issues/3199257
A slight improvement in the #MadeToShare campaign to improve legibility.

Capitalise MadeToShare hashtag

---

modules/social_features/social_group/modules/social_group_request/social_group_request.api.php
modules/social_features/social_group/modules/social_group_request/social_group_request.module
modules/social_features/social_group/social_group.module

There is no way to add join methods for group types except flexible group.
Use the custom hook to add other group types
- https://www.drupal.org/node/3197706
- https://getopensocial.atlassian.net/browse/YANG-4740
- https://www.drupal.org/project/social/issues/3199293
Provide a method to alter array of group types used in social group request

Issue #3197706 by rolki: Provide a method to alter array of group types used in social group request

---

modules/custom/activity_viewer/activity_viewer.api.php
modules/custom/activity_viewer/src/Plugin/views/filter/ActivityFilterPersonalisedHomepage.php
phpstan-baseline.neon

On the UN project is not possible to save activity streams on the dashboard. The 'activity_filter_personalised_homepage' filter is overridden and the SQL query takes too much time.
Also, anonymous user see empty activities because they don't have access to related entities
Improve the 'activity_filter_personalised_homepage' filter and allow to alter the query.
https://www.drupal.org/project/social/issues/3197794
https://getopensocial.atlassian.net/browse/YANG-3793
https://getopensocial.atlassian.net/browse/YANG-4509
https://getopensocial.atlassian.net/browse/YANG-4887
https://getopensocial.atlassian.net/browse/YANG-4888
N/A
Added new hooks alter to modify activity filter query.
- `hook_activity_viewer_available_nodes_query_alter` to add own conditions which nodes available to view.
- …

Issue #3197794 by tBKoT: Improve the personalised homepage activity filter and allow to alter the query

---

modules/social_features/social_group/modules/social_group_invite/src/Form/SocialBulkGroupInvitation.php

Group invite doesn't work in the latest OS version for new users
It seems the problem in the `groupInvitationLoader` service, it returns wrong results, so as around way we can use group content storage to check if the user was already invited or not.
- https://getopensocial.atlassian.net/browse/YANG-4986
- https://www.drupal.org/project/social/issues/3199157

Issue #3199157 by rolki: Use group_content storage instead of groupInvitationLoader service for checking invitation

---

modules/social_features/social_event/modules/social_event_managers/src/Element/SocialEnrollmentAutocomplete.php

After adding member through "Add directly" receive:
`Warning: preg_match_all() expects parameter 2 to be string, array given in Drupal\Component\Utility\Tags::explode() (line 25 of core/lib/Drupal/Component/Utility/Tags.php).`
`Notice: Undefined index: #validate_reference in Drupal\Core\Entity\Element\EntityAutocomplete::validateEntityAutocomplete() (line 242 of core/lib/Drupal/Core/Entity/Element/EntityAutocomplete.php).`
Make fixes in `/modules/social_features/social_event/modules/social_event_managers/src/Form/SocialEventManagersAddEnrolleeForm.php`
- https://www.drupal.org/project/social/issues/3198521
- https://getopensocial.atlassian.net/browse/YANG-4480
*Fixed warnings after adding member through "Add directly" to event enrollments.*
N/A
N/A

Issue #3198521 by Ressinel: Fix PHP warning when add event enrollees

---

modules/social_features/social_follow_taxonomy/modules/social_follow_tag/social_follow_tag.module
modules/social_features/social_follow_taxonomy/modules/social_follow_tag/src/SocialFollowTagLazyBuilder.php
modules/social_features/social_follow_taxonomy/modules/social_follow_tag/templates/social-tagging-nosplit.html.twig
modules/social_features/social_follow_taxonomy/modules/social_follow_tag/templates/social-tagging-popup.html.twig
modules/social_features/social_follow_taxonomy/modules/social_follow_tag/templates/social-tagging-split.html.twig

Improve Follow taxonomy block performance and extendability
Implement Lazy Load or AJAX for a popup with counters for performance improvements. Count followed users and related content inside the popup rendering instead of block preprocess.
https://www.drupal.org/project/social/issues/3198528
https://getopensocial.atlassian.net/browse/YANG-4810
N/A
N/A
Popup for the following taxonomy badges now loads through the lazy builder.
All counts are calculated in popup rendering.
N/A
N/A

Issue #3198528 by tBKoT: Improve Follow taxonomy block performance

---

modules/social_features/social_group/modules/social_group_request/social_group_request.module
modules/social_features/social_group/modules/social_group_request/src/Plugin/Block/SocialGroupRequestMembershipNotification.php

See https://getopensocial.atlassian.net/browse/YANG-5001
When we install the "Group membership" plugin for some group type, then we have an issue with notifications since it hardcoded only for the flexible group.
Use hook alter to get the list of request group types instead of the only flexible group.
- https://getopensocial.atlassian.net/browse/YANG-5001
- https://www.drupal.org/project/social/issues/3199893

Issue #3199893 by rolki: Notifications don't work for the group types that install the "Group request membership" plugin except for flexible group

---

modules/social_features/social_editor/config/install/editor.editor.basic_html.yml
modules/social_features/social_editor/config/install/filter.format.basic_html.yml
modules/social_features/social_editor/config/update/social_editor_update_8904.yml
modules/social_features/social_editor/social_editor.install

Currently, authorized users can create/edit new nodes but they are not able to use a table widget because they have access only to the `basic_html` format which does not provide that possibility.
Adjust `basic_html` format and add table widget
- https://www.drupal.org/project/social/issues/3199367
- https://getopensocial.atlassian.net/browse/YANG-4987
Extends basic_html format and add table widget. So, authorized users will be able to use it when create/edit nodes

Issue #3199367 by SV: Allow member to add a table in the description of node

---

modules/social_features/social_comment/social_comment.tokens.inc

When people receive a notification the URLs / links that you can see in the e-mail notification is always broken. (once you click on the 'post' it does work) even though we do provide the right URL-link.
- Cleanup `Carriage return` in the mail text
- https://www.drupal.org/project/social/issues/3199704
- https://getopensocial.atlassian.net/browse/YANG-4941
*For example*
- Actual result:
- Expected result:
Fixes broken links in the notification mail.

Issue #3199704 by SV: URL-link is broken in the e-mail notification

---

modules/custom/social_graphql/graphql/open_social.graphqls
modules/custom/social_graphql/src/GraphQL/DecoratableTypeResolver.php
modules/social_features/social_user/graphql/social_user_schema_extension.base.graphqls
modules/social_features/social_user/graphql/social_user_schema_extension.extension.graphqls
modules/social_features/social_user/src/GraphQL/UserActorTypeResolver.php
modules/social_features/social_user/src/Plugin/GraphQL/SchemaExtension/UserSchemaExtension.php

Currently we always expect things to be done by users. However, with the introduction of third-party applications and server-to-server OAuth authentication we may also see other systems perform actions (like creating content or triggering actions that perform notifications). Additionally for some data Open Social itself may be the cause.
An example where we already have something like this in our current UI is commenting as anonymous users. It would be useful to distinguish in the API between anonymous users (i.e. we have no data about them) and anonymized users (i.e. registered platform users acting anonymously). This can also help link actions by the same user, for example in anonymized discussions.
This commit introduces the …

Issue #3201182 by Kingdutch: [GraphQL] Introduce an Actor interface

---

modules/social_features/social_tagging/social_tagging.module

We have a few modifications for "Tagging" field in the function social_tagging_form_alter(). The issue is that if we render entities with "Inline Entity Form" module widgets this hook doesn't trigger....
Add addition hook allows compatibility with the "Inline Entity Form" module widgets
- https://www.drupal.org/project/social/issues/3202292
- https://getopensocial.atlassian.net/browse/YANG-5012

Issue #3202292 by vnech: Fix hiding of "Tagging" field in the Inline Entity Form

---

composer.json
modules/social_features/social_event/modules/social_event_managers/social_event_managers.module
modules/social_features/social_event/social_event.module
tests/behat/features/capabilities/security/private-file-uploads.feature

There is no restriction in the version of ajax_comments, this resulted in it automatically updating to beta 3 which ensured our patch wasn't applying anymore
Update patch to ensure it applies to beta3
https://www.drupal.org/project/social/issues/3204775#comment-14037093
Ajax comments is now updated to it's newest version

Issue #3204775 - Update patch for ajax comments based on beta 3

---

modules/social_features/social_profile/config/install/views.view.newest_users.yml
modules/social_features/social_profile/config/optional/block.block.exposedformnewest_userspage_newest_users.yml
modules/social_features/social_profile/config/optional/block.block.socialblue_exposedformnewest_userspage_newest_users.yml
modules/social_features/social_profile/config/static/block.block.exposedformnewest_userspage_newest_users_8901.yml
modules/social_features/social_profile/config/static/block.block.socialblue_exposedformnewest_userspage_newest_users_8901.yml
modules/social_features/social_profile/config/update/social_profile_update_8902.yml
modules/social_features/social_profile/social_profile.install
modules/social_features/social_profile/social_profile.module
modules/social_features/social_tagging/social_tagging.module
modules/social_features/social_tagging/src/SocialTaggingOverrides.php

The profile tags are not showing up in the all members tab.
There is no filter, where you can filter out the tags created.
Display social tagging filters on all members page.
Valid only if they are enabled for the profile.
Reuse functionality from all topics overview page.
- https://www.drupal.org/project/social/issues/3198953
- https://getopensocial.atlassian.net/browse/YANG-4909
- https://github.com/goalgorilla/open_social/pull/2137
*For example*
Add filters block when social tags on profile are enabled to the all members overview page.
- N/A
- N/A

Issue #3198953 by ribel: As a LU I want to be able to filter on the all members overview page

---

modules/social_features/social_event/modules/social_event_invite/social_event_invite.routing.yml
modules/social_features/social_event/social_event.routing.yml

Our routing.yml declaration isn't correct and compatible with modules like Plugin.
Fix our routing.yml route requirements section instead of misusing the parameters section.
https://www.drupal.org/project/social/issues/3196173
https://www.drupal.org/project/social/issues/3169375
None needed. 
An internal fix which resulted in issues when certain modules were used.

Issue #3196173 - Fix Expected argument of type "array or Traversable and ArrayAccess" 

---

.travis.yml
composer.json

This PR is in favor of #2278
Resolves an issue introduced in #2259 where standardizing our package name caused issues with drupal's infrastructure, as well as the fact we have widened `goalgorilla/open_social` replace range caused composer to think that 10.1.x-dev can
replace 10.0.3, which the replace key says is true but it's not what we want. 
Revert the package name to `goalgorilla/open_social` whilst maintaining some of our travis improvements. Also we make sure we add `drupal/social` to our composer.json replace attribute using the `self.version` to make sure external dependencies can still depend on drupal/social versions
https://www.drupal.org/project/social/issues/3203225
We can postpone https://www.drupal.org/node/3203229 untill we can finally standardize our package name.

Issue #3203225: revert the package name to goalgorilla/open_social and use an updated travis config

---

modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module

There are some new issues with saving visibilities for other group types when we use `hook_social_group_settings_alter`, so it means states from flexible group can't be reused for other group types yet.
Revert changes for group visibility states
https://getopensocial.atlassian.net/browse/YANG-5116
https://www.drupal.org/project/social/issues/3200113

Issue #3200113 by rolki: Enable visibility states only for the flexible group

---

modules/custom/activity_send/modules/activity_send_email/activity_send_email.module

We are getting a ton of immediate notification to our site manager account when people respond to an event invite or request enrollment to an event.
I don't see an option to set this notification type to other timeframes under the "What i manage" section of notification options.
Add request_event_enrollment message template to the "What i manage" section of notification options, so they don't receive all of these immediately, but instead daily or weekly based on preference.
- https://www.drupal.org/project/social/issues/3205805
- https://getopensocial.atlassian.net/browse/YANG-5121
*For example*
Users now see "A user request an enrollment for event" in "What i manage" section of Email notification settings, so they don't receive all of these immediately, but instead daily or weekly based …

Issue #3205805 by ribel: Add request event enrollment message template to email notification settings

---

modules/custom/social_graphql/graphql/open_social.graphqls
modules/custom/social_graphql/src/Wrappers/InputBase.php

We want to have specific input and output formats for clientMutationId and related types.
Introduce a UUIDv4 scalar that makes it clear what the format should be.
This scalar is separate from GraphQLs built-in ID which is an opaque identifier type that has meaning to the server. The UUIDv4 can be used for the specific string format that may not need to correspond to data within Open Social.
Any use of <code>clientMutationId</code> is changed to follow the UUIDv4 format so that it becomes safe for us to store in the database.
https://www.drupal.org/project/social/issues/3208055
Not under test, tested by an Open Social extension.
N/a
N/a unreleased internal change
N/a …

Issue #3208055 by Kingdutch: [GraphQL] Provide UUIDv4 scalar type

---

modules/social_features/social_group/config/install/core.entity_form_display.group.closed_group.default.yml
modules/social_features/social_group/config/install/core.entity_form_display.group.open_group.default.yml
modules/social_features/social_group/config/install/core.entity_form_display.group.public_group.default.yml
modules/social_features/social_group/config/update/social_group_update_8905.yml
modules/social_features/social_group/modules/social_group_secret/config/install/core.entity_form_display.group.secret_group.default.yml
modules/social_features/social_group/modules/social_group_secret/config/update/social_group_secret_update_8901.yml
modules/social_features/social_group/modules/social_group_secret/social_group_secret.install
modules/social_features/social_group/social_group.install

These group types have incorrect fields order on add/edit pages:
- Public group
- Open group
- Closed group
- Secret group
Update form display configuration for group types
- https://www.drupal.org/project/social/issues/3208734
- https://getopensocial.atlassian.net/browse/ECI-1160
Update form display configuration for group types: Public group, Open group, Closed group, Secret group"

Issue #3208734 by vnech: Update form display configuration for Public, Open, Closed and Secret group types

---

modules/custom/social_ajax_comments/src/Controller/AjaxCommentsController.php

If I try to submit a comment (for example, on "Topic" page) with an empty body the error messages don't displays.
Refactor code and add a correct selector for AjaxCommand.
- https://www.drupal.org/project/social/issues/3207801
- https://getopensocial.atlassian.net/browse/YANG-5392
Fix error message displaying on comments.

Issue #3207801 by vnech: Display error messages (if exist) on Ajax Comments

---

composer.json

[#3010020] updated the image_effects module and introduced a specific version requirement for <code>drupal/file_mdm</code>. The drupal/file_mdm module is now a few versions up and the version we require uses the <code>lsolesen/pel</code> library which causes a lot of warnings on PHP 7.4
<code>
Deprecated function: Array and string offset access syntax with curly braces is deprecated in include() (line 478 of /var/www/vendor/composer/ClassLoader.php)
#0 /var/www/html/core/includes/bootstrap.inc(600): _drupal_error_handler_real(8192, 'Array and strin...', '/var/www/vendor...', 410, Array)
#1 /var/www/vendor/composer/ClassLoader.php(478): _drupal_error_handler(8192, 'Array and strin...', '/var/www/vendor...', 410, Array)
#2 …

Issue #3212793 by Kingdutch: Remove drupal/file_mdm dependency

---

modules/custom/social_lets_connect/modules/social_lets_connect_contact/social_lets_connect_contact.links.menu.yml

The link in the social_lets_connect_contact module to `Services` leads to a 404 on getopensocial.com . We would like to change this to Review Open Social on Capterra.
Change the link in said module to link (Distro) users to reviewing Open Social on Capterra.
https://getopensocial.atlassian.net/browse/SAL-21

[Internal] Change link from getopensocial.com/services to Review Open Social on Capterra

---

.tugboat/composer.json
.tugboat/config.yml
.tugboat/settings.local.php

This sets up a simple Open Social installation using a custom PHP image
based on open_social_docker but using the TugboatQA/php image as base
(the default php image is not supported).
The site is installed without optional modules so that it's easy to test
that modules only require the things they actually need or to build up
an environment as needed. Additionally we don't provide admin access
(although we can store a Tugboat configured admin password in LastPass
as back-up) to encourage testing with properly permissioned user.
As a compromise to allow modules to be enabled we provide this
permission to site managers. Addtionally we start out with demo content
so that there is a base to start manual testing from.
We use a custom composer.json file rather than trying to pull in …

Add TugboatQA configuration

---

modules/social_features/social_comment/config/schema/social_comment.schema.yml
modules/social_features/social_comment/social_comment.module
modules/social_features/social_comment/src/Entity/Access/CommentQueryAccessHandler.php
modules/social_features/social_comment/tests/src/Kernel/CommentViewAccessTest.php
modules/social_features/social_core/social_core.info.yml

Access checks based on published status or ownership for comments aren't performed during an entity query. This means that these checks need to be done after an entity is loaded. This causes issues for pagination, most notably in GraphQL, as outlined in #2979294: Improve pagination DX (a core issue for the JSON:API).
This problem is illustrated by `QueryCommentsTest::testUserRequiresAccessCommentsPermission` and `QueryCommentsTest::testUserCanviewOnlyOwnOrOtherPublishedComments` introduced in https://github.com/goalgorilla/open_social/pull/2285.
As Open Social already depends on the entity module that contains the new entity access API we can use this in our solution.
We should duplicate the access checking logic for comments into the entity access API so that these access checks can be …

Issue #3210685 by rolki: Add a query_access handler to the comment entity type

---

modules/custom/activity_viewer/src/Plugin/views/filter/ActivityNotificationVisibilityAccess.php
tests/behat/features/bootstrap/SocialDrupalContext.php
tests/behat/features/capabilities/administration/export-users.feature
tests/behat/features/capabilities/administration/mail-users.feature
tests/behat/features/capabilities/mention/mention-post.feature

See #2272
The activity notification filter for follow taxonomy filters out content related to mentions and backgroundtasks as well.
This was a regression created in #2201 where the goal was to filter out notifications for content created based on tags you are following. This could be that you saw content which was placed in a group you are not a member of, but because it had a tag you're following it showed up in the notification list.
Ensure we allow the mentions / background tasks again as part of the notification centre and filter with test coverage so we dont have this regression anymore.
https://www.drupal.org/project/social/issues/3205376
We have fixed the mentions & background task notifications in the notification center, they will pop up again as expected.

Issue #3205376: Make sure mentions and background tasks are working in the notification center

---

modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
modules/social_features/social_group/social_group.module

A user should still see this button and then be prompted to log in so they can join.
otherwise, we are missing out on a large number of users getting a call to action that they can in fact interact with the page.
Display "Join" button for an anonymous user on the public flexible groups with "open to join" visibility option
- https://www.drupal.org/project/social/issues/3215151
- https://getopensocial.atlassian.net/browse/YANG-5688
After fix applied:
Display "Join" button for anonymous users on the public flexible groups so they can join.

Issue #3215151 by SV: Display "Join" button for anonymous user on the public flexible groups

---

modules/social_features/social_group/modules/social_group_flexible_group/src/Access/FlexibleGroupContentAccessCheck.php
tests/behat/features/capabilities/group/group-create-flexible.feature

In #2270 a regression was introduced where SM / Admin can't visit flexible groups which have the "secret" selected.
Make sure we check users with manage all groups permissions before we do the field value checks, this is more performant for them and also makes sure we can escape this access check when users have these powerfull global permissions.
https://www.drupal.org/project/social/issues/3204850
As a SM you get an access denied whilst visiting a flexible group with the "Secret" configuration. That is now fixed as a SM should be able to see this always.

Issue #3204850: Make sure SM / Admin can still visit flexible groups marked as secret

---

modules/social_features/social_core/social_core.install

The `gin--vertical-toolbar` class is absent when we have a gin vertical toolbar.
Add vertical toolbar setting to the gin.settings.yml file.
https://www.drupal.org/project/social/issues/3215132
before:
after:
The header has a correct position relative to the gin toolbar.

Issue #3215132 by agami4: Fix gin toolbar settings

---

modules/social_features/social_group/src/Element/SocialGroupEntityAutocomplete.php

After adding member to group through "Add directly" receive:
Notice: Undefined index: #validate_reference in Drupal\Core\Entity\Element\EntityAutocomplete::validateEntityAutocomplete() (line 242 of core/lib/Drupal/Core/Entity/Element/EntityAutocomplete.php).
Drupal\Core\Entity\Element\EntityAutocomplete::validateEntityAutocomplete(Array, Object, Array) (Line: 77)
Drupal\social_group\Element\SocialGroupEntityAutocomplete::validateEntityAutocomplete(Array, Object, Array, 1) (Line: 1024)
_social_group_unique_members(Array, Object, Array)
call_user_func_array('_social_group_unique_members', Array) (Line: 280)
Make fixes in /modules/social_features/social_group/src/Element/SocialGroupEntityAutocomplete.php
https://www.drupal.org/project/social/issues/3216268
Fixed warnings after adding member …

Fix PHP warning when add user to group directly

---

modules/social_features/social_group/config/install/group.type.closed_group.yml
modules/social_features/social_group/config/install/group.type.open_group.yml
modules/social_features/social_group/config/install/group.type.public_group.yml
modules/social_features/social_group/modules/social_group_flexible_group/config/install/group.type.flexible_group.yml
modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install
modules/social_features/social_group/modules/social_group_secret/social_group_secret.install
modules/social_features/social_group/social_group.install
modules/social_features/social_group/social_group.module

There is no possibility to remove the "Group Admin" group role for users who are group members and have CM+ role at the same time.
Delete functions (hooks) handled force assign "Group Admin" role for members with CM+ role.
NOTE: This PR saves the ability to make CM+ users as group admins if the one creates a group.
- https://www.drupal.org/project/social/issues/3215464
- https://getopensocial.atlassian.net/browse/YANG-5715
- https://getopensocial.atlassian.net/browse/YANG-4990
Add an ability to remove the "Group Admin" role for members with CM+ global roles.

Issue #3215464 by vnech: Add ability for CM+ to remove "Group Admin" role for members

---

modules/social_features/social_tagging/social_tagging.module

Tags are currently grouped together with other settings on the add/edit node pages. Also, these settings are collapsed by default, and as result users can miss them when creating or edit content.
Move “Tags” from “Additional information” to a separate section on create/edit screen
- https://www.drupal.org/project/social/issues/3216240
- https://getopensocial.atlassian.net/browse/YANG-5649
**Before** 
is collapsed:
is mixed with other fields:
**After:** 
displays in separate fieldset
Now, "Tags" is much more visible and displays in the new separate fieldset

Issue #3216240 by SV: Improve visibility of tags in content creation

---

modules/social_features/social_group/modules/social_group_welcome_message/social_group_welcome_message.module

Don't send a message to group admins when a new member is added as this produces a lot of similar messages.
- https://www.drupal.org/project/social/issues/3217678
- https://getopensocial.atlassian.net/browse/YANG-4990

Issue #3217678 by vnech: Remove group admins as recipient for sending message when a new member is added

---

composer.json
modules/custom/social_graphql/src/GraphQL/ResolverRegistry.php

This version of the module includes support for resolving fields on
interfaces so that code is no longer needed in Open Social's
ResolverRegistry.
We keep the registry class so we don't have to change exsiting modules
and can easily override `graphql` behaviour in the future (if needed).
Replaces https://github.com/goalgorilla/open_social/pull/2194 once https://github.com/drupal-graphql/graphql/pull/1155 is merged.
https://www.drupal.org/project/social/issues/3194938
See related PRs
N/a internal change

Update GraphQL module to 4.1

---

modules/custom/social_graphql/src/GraphQL/ResolverRegistry.php
modules/custom/social_graphql/src/GraphQL/StandardisedMutationSchemaTrait.php
modules/custom/social_graphql/src/Plugin/GraphQL/SchemaExtension/SchemaExtensionPluginBase.php
modules/social_features/social_comment/src/Plugin/GraphQL/SchemaExtension/CommentSchemaExtension.php
modules/social_features/social_profile/src/Plugin/GraphQL/SchemaExtension/ProfileSchemaExtension.php
modules/social_features/social_user/src/Plugin/GraphQL/SchemaExtension/UserSchemaExtension.php

Open Social creates its own ResolverRegistry so that it can make changes to the way the schema is built in case this is desirable. However, the actual schema extension plugins always expect a standardised ResolverRegistry as they must adhere to the schema extension interfaces. This means there's no easy way to call public methods from a schema extension on our custom resolver registry because it may lead to calling a non-existent function.
Instead of trying to provide the functionality for our schema extensions in the registry we should just make the function easily available to the extensions directly. This can easily be done by providing a trait that can be reused by …

[GraphQL] Move addMutationResolver into trait for schema extension

---

modules/custom/social_gdpr/social_gdpr.install

SM can't add/edit translations for Data Policy
Add permission for "sitemanager" role
- https://www.drupal.org/project/social/issues/3219037
- https://getopensocial.atlassian.net/browse/YANG-5768
*SM can add/edit Data Policy translations*

Issue #3219037 by vnech: Add permission for SM to edit Data Policy translations

---

modules/custom/social_language/modules/social_content_translation/social_content_translation.module
modules/custom/social_language/social_language.module

There is an issue with the "langcode" field when creating entities in multilanguage OS.
For example, I have two languages installed - "English" (default) and "Ukrainian".
If I create a Topic in "Ukrainian" first the wrong "langcode" sets in the node (the field has "en" value instead of "uk")
Set correct "langcode" on form alter for new entities.
- https://www.drupal.org/project/social/issues/3217219
- https://getopensocial.atlassian.net/browse/YANG-5782
*For example*
Set correct langcode when creating content in different than default language

Issue #3217219 by vnech: Set correct langcode when create a content in other then default language first

---

README.md

We are currently improving our PR flow.
TravisCI is blocking our PR tests currently with it's limited concurrency and increased pricing so we want to move away from Travis whilst maintaining our tests in a separate manner and improving our Developer Experience alltogether.
Update ReadMe with all the individual changes.
- Include Automated tests #2315 using dependabot
- Include Tugboat [WIP]
-- Include live preview
-- Include Behat & Cypress
- Include mirroring our repo [WIP]
- Remove TavisCI [WIP]
- Move PHPUnit from Travis to Github actions [WIP]
It's internal.
Not needed.
See preview.
Not needed.

[Documentation] Update readme with new PR flow

---

modules/custom/social_graphql/src/GraphQL/ConnectionQueryHelperBase.php
modules/custom/social_graphql/src/GraphQL/ConnectionQueryHelperInterface.php
modules/custom/social_graphql/src/GraphQL/EntityConnection.php
modules/social_features/social_comment/src/Plugin/GraphQL/DataProducer/QueryComments.php
modules/social_features/social_comment/src/Plugin/GraphQL/DataProducer/SocialCommentAttachments.php
modules/social_features/social_comment/src/Plugin/GraphQL/QueryHelper/CommentAttachmentsQueryHelper.php
modules/social_features/social_comment/src/Plugin/GraphQL/QueryHelper/CommentQueryHelper.php
modules/social_features/social_user/src/GraphQL/QueryHelper/UserQueryHelper.php
modules/social_features/social_user/src/Plugin/GraphQL/DataProducer/QueryUser.php

In some cases the default sorting direction should not be ascending but instead descending. A possible scenario is for example sorting content by the number of likes.
Forward is currently always assumed to be "Ascending" and reversed is considered to be "Descending" with no way to change this.
Update <code>ConnectionQueryHelperInterface</code> to add <code>getForwardSortDirection</code> and <code>getReverseSortDirection</code> which can be called instead of the current hardcoded 'ASC' and 'DESC' values.
Introduce <code>ConnectionQueryHelperBase</code> that contains these functions with their current default values to make upgrading easier. …

Issue #3219123 by Kingdutch: [GraphQL] Allow EntityConnectionQueryHelper to change sorting direction

---

modules/social_features/social_profile/social_profile.post_update.php
modules/social_features/social_profile/src/Plugin/views/field/ProfileEntitySortable.php

1. Update all profiles by post_update take a lot of time
2. Sorting for users which have permission to view hidden fields doesn't works properly.
1. Add the Profile name field value directly by database insert to reduce the update time of a large number of profiles.
2. Try to improve sorting code.
- https://www.drupal.org/project/social/issues/3211565
- https://getopensocial.atlassian.net/browse/DS-7546
N/A
Some improvements and fixes:
1. Reduce the update time of a large number of profiles.
2. Sort members in group view for users which have permission to view hidden fields works fixed and works properly now.
N/A
N/A

Issue #3211565 by Ressinel: Sort users in Group view (improvements).

---

modules/social_features/social_footer/social_footer.install
modules/social_features/social_footer/social_footer.permissions.yml

The social_footer has a route requirement for a permission called 'administer social_footer_block settings' , but this permission does not exists in the module (there is no .permission.yml file for it). So only users that have the permission added programetically can access this route.
We need to create a permission.yml file where this permission will be defined.
https://www.drupal.org/project/social/issues/3215978
1. Go to /admin/people/permissions
2. Try to find the 'administer social_footer_block settings'

Issue #3215978 by nkoporec: Administer social_footer settings permission is missing

---

modules/social_features/social_event/modules/social_event_managers/src/Plugin/Action/SocialEventManagersSendEmail.php

When trying to send out an email to event enrollees, an AJAX error occurs.
I fixed the issue by removing a foreach block that was not necessary.
https://www.drupal.org/project/social/issues/3220277
1. Create an event and add enrollees
2. Select a few enrollees and execute the 'Send email to enrollees' action.
3. Enter the email details and hit send.
4. An AJAX error occurrs.
1. Fixed an issue where sending out emails to event enrolles would crash during the AJAX execution, which resulted in no emails being sent.

Issue #3220277 by nkoporec: Fix the error message, when sending out emails to event enrollees.

---

composer.json

Gin toolbar 1.0-beta18 makes toolbar disappear even for the superuser (UID 1)
Lock gin_toolbar to 1.0-beta17.
https://www.drupal.org/project/social/issues/3222350
N.A
Gin toolbar version is locked to 1.0-beta17
N.A
N.A

Issue #3222350 by navneet0693: Locked gin_toolbar version to 1.0-beta17.

---

modules/social_features/social_follow_content/src/Plugin/ActivityContext/FollowContentActivityContext.php
tests/behat/features/capabilities/topic/topic-follow-content.feature

Not all followers receive (email) notifications of content they are following.
Make some fixes to the in FollowContentActivityContext
- https://getopensocial.atlassian.net/browse/DS-7612
- https://www.drupal.org/project/social/issues/3220085
N/A
Fixes when not all followers receive (email) notifications of content they are following.
N/A
N/A

Issue #3220085 by Ressinel: Fixes when not all followers receive (email) notifications of content they are following.

---

modules/custom/social_graphql/src/GraphQL/EmptyEntityConnection.php
modules/custom/social_graphql/src/Plugin/GraphQL/DataProducer/Connection/ConnectionEdges.php
modules/custom/social_graphql/src/Plugin/GraphQL/DataProducer/Connection/ConnectionPageInfo.php
modules/social_features/social_user/src/Plugin/GraphQL/DataProducer/QueryUser.php
modules/social_features/social_user/tests/src/Kernel/GraphQL/GraphQLUsersEndpointTest.php

We already know users are not allowed to list all users on a platform so we don't need to go querying at all.
Short-cut the query for anonymous users.
Change on unsupported code, internal issue only: https://getopensocial.atlassian.net/browse/DS-7613
N/a
N/a
N/a
N/a

DS-7613 - 1: Short-cut UserQuery for anonymous users

---

modules/social_features/social_event/modules/social_event_addtocal/src/Plugin/SocialAddToCalendar/AddToICal.php
modules/social_features/social_event/modules/social_event_addtocal/src/Plugin/SocialAddToCalendar/AddToOffice365.php
modules/social_features/social_event/modules/social_event_addtocal/src/Plugin/SocialAddToCalendar/AddToOutlook.php
modules/social_features/social_event/modules/social_event_addtocal/src/Plugin/SocialAddToCalendar/AddToYahoo.php

`Add to calendar` functionality for outlook does not work properly. It redirects members to general Outlook login, and after login does not provide an option to add the event to the calendar. It happens when trying to add an event to the calendar of accounts that are connected to Office 365.
Create a new option for the `Add to calendar` to provide the possibility to add events in Office 365 accounts. It's needed because Outlook and Office 365 used different links to add events in the calendar.
https://www.drupal.org/project/social/issues/3223299
https://getopensocial.atlassian.net/browse/YANG-5106
N/A
Now we have one more option for the `Add to calendar` feature which allows us to add events in Office 365 account's calendar
N/A
N/A

Issue #3223299 by tBKoT: Add Office 365 support for Add to calendar

---

modules/social_features/social_tagging/src/SocialTaggingService.php

When "Allow use a parent of category." option is enabled users can select a parent of tag and on saving translated node there is the following error:
Need to add a check if there is a translation for a current term before call getTranslation()
- https://www.drupal.org/project/social/issues/3223639
- https://getopensocial.atlassian.net/browse/YANG-5883
Following options are enabled on the tags settings page:
Also, will need to enable all required translation modules:
Screen of translated node:
Fixes issue with adding parent tags for translated nodes

Issue #3223639 by SV: Error after adding a parent of tag for translated nodes

---

modules/custom/social_language/social_language.install
modules/custom/social_language/social_language.module
modules/custom/social_language/src/Routing/RouteSubscriber.php
modules/social_features/social_book/social_book.install
modules/social_features/social_event/social_event.install
modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install
modules/social_features/social_landing_page/social_landing_page.install
modules/social_features/social_page/social_page.install
modules/social_features/social_topic/social_topic.install

In OS "Content manager" role doesn't have permissions to add/edit/delete translations but has permissions to manage most of the content.
Grand "Content manager" role with permissions to translate content he has permissions to edit.
- https://www.drupal.org/project/social/issues/3222538
- https://getopensocial.atlassian.net/browse/YANG-5978
- https://getopensocial.atlassian.net/browse/YANG-5985
*Allow "Content Manager" role to translate content.*

Issue #3222538 by vnech: Allow "Content Manager" role to translate content

---

modules/custom/social_graphql/src/Plugin/GraphQL/DataProducer/Entity/EntityUrl.php
modules/social_features/social_comment/graphql/social_comment_schema_extension.base.graphqls
modules/social_features/social_topic/graphql/social_topic_schema_extension.base.graphqls
modules/social_features/social_topic/graphql/social_topic_schema_extension.extension.graphqls
modules/social_features/social_topic/src/Plugin/GraphQL/DataProducer/QueryTopic.php
modules/social_features/social_topic/src/Plugin/GraphQL/DataProducer/QueryTopicByType.php
modules/social_features/social_topic/src/Plugin/GraphQL/QueryHelper/TopicQueryByTypeHelper.php
modules/social_features/social_topic/src/Plugin/GraphQL/QueryHelper/TopicQueryHelper.php
modules/social_features/social_topic/src/Plugin/GraphQL/SchemaExtension/TopicSchemaExtension.php
modules/social_features/social_topic/tests/src/Kernel/GraphQL/QueryTopicTest.php
modules/social_features/social_topic/tests/src/Kernel/GraphQL/QueryTopicTypesTest.php
modules/social_features/social_topic/tests/src/Kernel/GraphQL/QueryTopicsTest.php

With the intention to allow external websites to display teasers for topics. Those teasers should have access to the author, title, created data, topic type, image, contents and comment data. Additionally it should be able to provide a link to the topic so that it can be viewed on the Open Social website.
The updated date is currently omitted because this information is not generally displayed on an Open Social platform itself.
It should be possible to
- Select a topic by its UUID
- Select an overview of all topics and paginate through results according to the Relay connection specification
Querying and searching for data should respect existing privacy measures (such as visibility settings) according to platform configuration.
Implement the required GraphQL Schema and DataProducer …

Issue #3185523 by rolki: Implement basic topic querying in the Graph

---

modules/social_features/social_event/graphql/social_event_schema_extension.base.graphqls
modules/social_features/social_event/graphql/social_event_schema_extension.extension.graphqls
modules/social_features/social_event/src/Plugin/GraphQL/DataProducer/EventManagers.php
modules/social_features/social_event/src/Plugin/GraphQL/DataProducer/Field/DateToTimestamp.php
modules/social_features/social_event/src/Plugin/GraphQL/DataProducer/QueryEvent.php
modules/social_features/social_event/src/Plugin/GraphQL/QueryHelper/EventManagersQueryHelper.php
modules/social_features/social_event/src/Plugin/GraphQL/QueryHelper/EventQueryHelper.php
modules/social_features/social_event/src/Plugin/GraphQL/SchemaExtension/EventSchemaExtension.php
modules/social_features/social_event/tests/src/Kernel/GraphQL/QueryEventTest.php
modules/social_features/social_event/tests/src/Kernel/GraphQL/QueryEventsTest.php

Events play a big part in a community. To open this data up towards external consumers can aid in engagement and enrollees.
It should be possible to
- Select an event by its UUID
- Find an event by a specific property of its node data, or specific event-related data (No need for additions like geolocation just yet)
- Search for an event in a similar manner as on /search/content
- Paginate through results according to the Relay connection specification
Querying and searching for data should respect existing privacy measures (such as public content is available for AN, community to LU, etc) according to platform configuration.
Implement the required GraphQL Schema and DataProducer plugins in `social_event` that extend the schema defined on `social_graphql`
- …

Issue #3185497 by rolki: Implement basic event querying in the Graph

---

modules/social_features/social_group/modules/social_group_flexible_group/config/optional/language.content_settings.group.flexible_group.yml

If we have already a multi-language OS and then enable the module "Social Flexible Group" flexible groups can't be translated because of missed configuration `language.content_settings.group.flexible_group`
Add missed content translation configuration for "Flexible Group" group type
- https://www.drupal.org/project/social/issues/3223946
- https://getopensocial.atlassian.net/browse/YANG-5702
- https://github.com/goalgorilla/open_social/pull/2369
N/A
N/A
*Add missed content translation configuration for "Flexible Group" group type.*
N/A
N/A

Issue #3223946 by vnech: Add missed content translation config for Flexible Group

---

modules/social_features/social_profile/src/Plugin/Field/FieldWidget/SocialProfileTagSplitWidget.php

The user receives an error when trying to save the profile with empty profile tags
```
TypeError: Argument 1 passed to Drupal\Core\Field\WidgetBase::massageFormValues() must be of the type array, string given, called in /var/www/html/core/lib/Drupal/Core/Field/WidgetBase.php on line 390 in Drupal\Core\Field\WidgetBase->massageFormValues() (line 537 of core/lib/Drupal/Core/Field/WidgetBase.php).
Drupal\Core\Field\WidgetBase->massageFormValues('', Array, Object) (Line: 390)
Drupal\Core\Field\WidgetBase->extractFormValues(Object, Array, Object) (Line: 232)
Drupal\Core\Entity\Entity\EntityFormDisplay->extractFormValues(Object, Array, Object) (Line: 338)
Drupal\Core\Entity\ContentEntityForm->copyFormValuesToEntity(Object, …
```

Issue #3224828 by tBKoT: Fix profile save process when profile tagging is enabled

---

modules/custom/social_language/social_language.module

After enabling content translations we got confusing suffix on field groups labels "all languages" even if all fields in the field group are translatable.
Remove suffix "all languages" on multilingual sites.
- https://www.drupal.org/project/social/issues/3225297
- https://getopensocial.atlassian.net/browse/YANG-5843
*Remove suffix "all languages" on multilingual sites.*
N/A
N/A

Issue #3225297 by vnech: Remove "all languages" suffix from field group labels

---

modules/custom/social_language/social_language.install
modules/custom/social_language/social_language.module

When translations are enabled on node (groups or other entities) forms appear fieldset "Translations" and this broke a common form design (see screenshot below).
Move "Translations" fieldset to the "Settings" field group.
- https://www.drupal.org/project/social/issues/3225336
- https://getopensocial.atlassian.net/browse/YANG-5842
*Move "Translations" fieldset to the "Settings" field group.*
N/A
N/A

Issue #3225336 by vnech: Move "Translations" fieldset to "Settings" fields group

---

modules/social_features/social_sharing/social_sharing.module

When I'm deleting a public page, I should't be able to share it via the Share this page block.
I added the 'entity.node.delete_form' route to the excluded routes in the Social Sharing module.
https://www.drupal.org/project/social/issues/3208696
Before:
After:
Add 'entity.node.delete_form' to the excluded routes in Social Sharing module

Issue #3208696 by nkoporec: I shouldn’t be able to share the 'Delete node' page

---

modules/social_features/social_profile/modules/social_profile_fields/social_profile_fields.module

As a regular user, with no special roles or permissions, I can see a revision log at the bottom of the edit profile form.
The revision log field should only display for users that have the permission to edit all profiles and the field should also not show up if you are editing your own profile, since it does not make sense to set a revision message for it.
https://www.drupal.org/project/social/issues/3214731
1. Enable social_profile and social_profile_fields
2. Login in as an authenticated user
3. Go to 'Edit my profile' page.
Before:
After:

Issue #3214731 by nkoporec: As an authenticated user I should not see the revision log field when editing my profile

---

translations.php

Currently the access permission tab is not fully translated.
Add the missing translation strings to translations.php so it gets pickup by POTX tool.
https://www.drupal.org/project/social/issues/3216202
1. Enable translations
2. Go to edit group form
3. See the 'Access permission' tab
- Added new source strings to the `translations.php` file.

Issue #3216202 by nkoporec: Missing translations for access permissions on flexible groups form

---

modules/social_features/social_activity/config/optional/views.view.activity_stream.yml
modules/social_features/social_activity/social_activity.install

Follow up: https://github.com/goalgorilla/open_social/pull/1818
The Activity Stream view page for /stream displays an error on the views UI in the Filter Criteria. This is basically a filter that does not have (and never has had) an accompanying plugin. It was introduced here: https://github.com/goalgorilla/open_social/pull/539/files
- Remove the filter from the view config files
- Add an update hook to remove from the current config.
- https://www.drupal.org/project/social/issues/3123493
N/A
Resolved missing/broken view filter on the activity stream.
N/A
N/A

Issue #3123493 by AlanHDev: Resolve missing/broken view filter on activity stream

---

modules/custom/activity_send/modules/activity_send_email/src/Plugin/EmailFrequency/None.php
modules/social_features/social_swiftmail/src/Form/SocialSwiftmailSettingsForm.php
tests/behat/features/bootstrap/EmailContext.php
tests/behat/features/capabilities/notifications/notification-emails.feature

Currently, as part of `/admin/config/opensocial/swiftmail`, we can already configure for each email notification if they are by default send as Immediately, Daily or Weekly.
We need to add the option for emails not to be sent.
Add a `none`(Never) option for email notification frequency 
https://www.drupal.org/project/social/issues/3225518
https://getopensocial.atlassian.net/browse/YANG-6040
Site settings
User settings
Site settings
User settings
Now SM+ can select "Never" as a default email frequency option for email notifications.
N/A
N/A

Issue #3225518 by tBKoT: Allow SM to disable specific email notifications

---

modules/custom/social_path_manager/social_path_manager.module
modules/social_features/social_group/modules/social_group_default_route/social_group_default_route.services.yml
modules/social_features/social_group/modules/social_group_default_route/src/EventSubscriber/RedirectSubscriber.php
modules/social_features/social_group/social_group.services.yml

The `group/{group}/home` page is not used anywhere and it returns just a white page only with a title. That provides some issues with already existing aliases and users do not see any information on this page.
- Add `group/{group}/home` route as needed to be redirected.
- Add priority for route subscribers to make them the same as the module weight to provide the correct order of execution.
- https://getopensocial.atlassian.net/browse/YANG-5837
- https://www.drupal.org/project/social/issues/3224886
Now all users that go to the group/{group_id}/home page will be redirected to the selected tab in group settings.
N/A
N/A

Issue #3224886 by tBKoT: Fix redirect for the group home route

---

modules/social_features/social_landing_page/config/install/field.field.paragraph.accordion.field_accord_description.yml
modules/social_features/social_landing_page/config/install/field.field.paragraph.accordion.field_accord_title.yml
modules/social_features/social_landing_page/config/install/field.field.paragraph.accordion_item.field_accord_item_description.yml
modules/social_features/social_landing_page/config/install/field.field.paragraph.accordion_item.field_accord_item_title.yml
modules/social_features/social_landing_page/config/install/field.field.paragraph.block.field_block_link.yml
modules/social_features/social_landing_page/config/install/field.field.paragraph.block.field_block_title.yml
modules/social_features/social_landing_page/config/install/field.field.paragraph.button.field_button_link_an.yml
modules/social_features/social_landing_page/config/install/field.field.paragraph.button.field_button_link_lu.yml
modules/social_features/social_landing_page/config/install/field.field.paragraph.hero.field_hero_image.yml
modules/social_features/social_landing_page/config/install/field.field.paragraph.hero.field_hero_subtitle.yml
modules/social_features/social_landing_page/config/install/field.field.paragraph.hero.field_hero_title.yml
modules/social_features/social_landing_page/config/install/field.field.paragraph.hero_small.field_hero_small_image.yml
modules/social_features/social_landing_page/config/install/field.field.paragraph.hero_small.field_hero_small_subtitle.yml
modules/social_features/social_landing_page/config/install/field.field.paragraph.hero_small.field_hero_small_title.yml
modules/social_features/social_landing_page/config/install/field.field.paragraph.introduction.field_introduction_link_an.yml
modules/social_features/social_landing_page/config/install/field.field.paragraph.introduction.field_introduction_link_lu.yml
modules/social_features/social_landing_page/config/install/field.field.paragraph.introduction.field_introduction_text.yml
modules/social_features/social_landing_page/config/install/field.field.paragraph.introduction.field_introduction_title.yml
modules/social_features/social_landing_page/config/optional/language.content_settings.paragraph.accordion.yml
modules/social_features/social_landing_page/config/optional/language.content_settings.paragraph.accordion_item.yml
modules/social_features/social_landing_page/config/optional/language.content_settings.paragraph.hero_small.yml
modules/social_features/social_landing_page/config/optional/language.content_settings.paragraph.section.yml
modules/social_features/social_landing_page/config/update/social_landing_page_update_10302.yml
modules/social_features/social_landing_page/social_landing_page.install
modules/social_features/social_landing_page/src/ContentTranslationDefaultsConfigOverride.php

There are a few paragraph type in "Landing Page" node that don't support translations:
- Accordion
- Accordion Item
- Hero small
- Make paragraphs translatable
- Make all fields used in "Landing Page" translatable by default
- https://www.drupal.org/project/social/issues/3227326
- https://getopensocial.atlassian.net/browse/YANG-6107
*For example*
N/A
*Make paragraphs in "Landing Page" translatable; Make fields in "Landing Page" translatable by default*
N/A
N/A

Issue #3227326 by vnech: Add missed translation support for "Landing Page" content type

---

modules/social_features/social_landing_page/social_landing_page.module

When creating a new landing page and adding a new block in a section, the override title block field is not working correctly. The checkbox is enabled, but the actual field is not displayed, so currently you are not able to override the block title.
The problem is with #states attribute. When rendering a form inside paragraphs, the '#name' attribute of fields are alternated since they are deeply nested within the paragraph fields. This means that the #states value of the original form(block settings form) is no longer correct, so we need to alter the form and set the correct #states attribute.
https://www.drupal.org/project/social/issues/3226672
1. Enable social_landing_page module
2. Create a new landing page content type
3. Add a new section
4. Add a block reference
5. For 'Primary' …

Issue #3226672 by nkoporec: Overwrite title field for blocks does not work in Landing Page form

---

modules/social_features/social_event/social_event.module
modules/social_features/social_event/src/Form/EnrollActionForm.php

When viewing the event enrollments on /group/*/events the number of enrollments is cached. This means that if after your first page load an additional members joins the event then the enrollment number will not be correct until the render cache is cleared.
Don't cache the number.
https://www.drupal.org/project/social/issues/3221056
*For example*
1. Find a group with an event
2. Go to /group/*/events and check the number of enrollments
3. Go to incognito as a different user and enroll into that event
4. As a previous user reload the /group/*/events page and check the enrollment count ( it will still be the same, even though a new user enrolled)

Issue #3221056 by nkoporec: Don't cache the number of event enrollments

---

modules/social_features/social_page/config/install/core.entity_view_display.node.page.small_teaser.yml
modules/social_features/social_page/social_page.install

Follow up of #2407 
After commit f11bf26e47c93af7bee59592e753f8380b9876a7 (whose commit message references [#3193302](https://www.drupal.org/project/social/issues/3193302)); `modules/social_features/social_page/config/install/core.entity_view_display.node.page.small_teaser.yml` contains layout_builder config in the third_party_settings section, which causes the following issue when you try to do a fresh site install without layout_builder enabled:
```
Drupal\Core\Config\ConfigImporterException: There were errors validating the config synchronization.
Configuration <em class="placeholder">core.entity_view_display.node.page.small_teaser</em> depends on the <em class="placeholder">Layout Builder</em> module that will not be installed after import. in …
```

Issue #3222835 by mparker17,navneet0693: Removed layout_builder settings from small_teaser view mode for page.

---

modules/social_features/social_search/config/install/views.view.search_groups.yml
modules/social_features/social_search/config/update/social_search_update_10302.yml
modules/social_features/social_search/social_search.install
modules/social_features/social_search/social_search.module

On groups search page (`/search/groups`) we have a filter "type" that allows filtering groups by type.
The issue is that the filter doesn't work properly (choosing group type doesn't give any effect). And even if we go to the view configuration page (`/admin/structure/views/view/search_groups`) and try to configure the filter we will see the error (see in screenshot section)
- Change "type" filter plugin type from `search_api_string` to `search_api_options`
- https://www.drupal.org/project/social/issues/3228885
- https://getopensocial.atlassian.net/browse/YANG-6200
*Fix "type" filter on the Search Groups views page.*
N/A
N/A

Issue #3228885 by vnech: Type filter doesn't work correctly on search groups page

---

modules/social_features/social_core/src/InviteService.php

We have PHPStan error:
`Method Drupal\social_core\InviteService::getInviteData() should return array|string but returns int<0, max>.`
Ensure that `Drupal\social_core\InviteService::getInviteData()` returns `array|string`.
N/A
N/A
N/A
N/A
N/A

Internal - Fix PHPStan error

---

modules/custom/social_language/social_language.module

When we enable translations support for any entity in OS "Content Translation" module add to the entity a few new fields (like `content_translation_source`, `content_translation_status` etc). After this Drupal require this fields definition updates on status report page:
Add a hook function that listens to any module installation and runs updates for translations field definitions if exist.
- https://www.drupal.org/project/social/issues/3230885
- https://getopensocial.atlassian.net/browse/YANG-6064
N/A
*Automate translation fields definitions updates.*
N/A
N/A

Issue #3230885 by vnech: Automate translation fields definitions updates

---

social.installer_options_list.yml

Most hosting providers these days provide their own static page caching.
This means that Drupal's page_cache provides only overhead but no 
actual benefit. We've found such a set-up in some cases to cause issues.
To fix this we no longer enable the page_cache by default but require site
builders to manually enable this module when it makes sense for their 
hosting set-up.
https://www.drupal.org/project/social/issues/3231551
*For example*
N/a
The `page_cache` module is no longer enabled for new site installs by default. When your hosting provider does not over a static page cache you should enable this yourselves.
https://www.drupal.org/node/3231552
N/a

Issue #3231551 by Kingdutch, ronaldtebrake: Do not install `page_cache` by default

---

.travis.yml

We are in a process to use Drupal 9 and ship with Drush 10 and a lot more goodies in our `goalgorilla/drupal_social` development repository.
For that we have had to use versioning so we can use Drupal 8.9.x and Drush 8 next to Drupal 9 and Drush 10.
Make sure we use the correct version in our travis.yml file.
You can see the differences here:
https://github.com/goalgorilla/drupal_social/pull/361/files
https://github.com/goalgorilla/open_social_scripts/compare/1.0.0...2.0.0
Internal
Let test pass.

[Internal] - Travis update after drupal_social versioning.

---

modules/social_features/social_activity/src/Plugin/ActivityEntityCondition/GroupContentSingleActivityEntityCondition.php

Group post notifications don't work after https://github.com/goalgorilla/open_social/pull/2300 is merged.
Fix it in `GroupContentSingleActivityEntityCondition.php`
- https://www.drupal.org/project/social/issues/3007303
N/A
N/A
N/A
N/A

Issue #3007303 by Ressinel: Fix issue with group post notifications.

---

modules/social_features/social_landing_page/social_landing_page.module

Content expanded to full page width.
Add route translation page to the condition.
https://www.drupal.org/project/social/issues/3233546
https://getopensocial.atlassian.net/browse/WAGGGGS-24
*For example*
before:
after:
Landing page content on the page is in the wrapper and doesn’t expand to full page width
N/A
N/A

Issue #3233546 by agami4: Content on add new landing page translation has no wrapper

---

.tugboat/config.yml

The social_demo module silences status messages in 
`Drupal\social_demo\Messenger` to ensure that the environment isn't
spammed while creating the demo content. However, this also removes 
useful status messages when working on the platform.
Disable the social_demo module after demo content setup.
Untracked CI change.
N/a
N/a
N/a
N/a

Uninstall `social_demo` in Tugboat after setup

---

modules/social_features/social_footer/src/Form/FooterSettingsForm.php

When adding inline images (using ckeditor upload widget) to the social footer block at /admin/config/opensocial/footer-block the images gets deleted after certain time. The problem is that this images are set as temporary, this means that on cron run Drupal will delete all temporary images. 
We need to set the images to have the permanent status and add them to the file usage table.
https://www.drupal.org/project/social/issues/3232648
1. Go to /admin/config/opensocial/footer-block
2. Upload and embed the image via Ckeditor
3. Save the form.
4. Go to admin/content/files and see the image status.
We have fixed an issue where images embedded with ckeditor on social footer settings page would get deleted after a certain time.

 Issue #3232648 by nkoporec: Social footer inline images are deleted after a certain time

---

.travis.yml
composer.json

As of Open Social 11.0.0 we want to use modern PHP features (like typed class properties). Additionally PHP 7.3 will no longer receive security updates after December 6th 2021.
Indicate in <code>composer.json</code> that we have compatibility with PHP 7.4 or PHP 8. Do not yet include PHP 9 because we don't know what breaking changes it might have.
https://www.drupal.org/project/social/issues/3238766
N/a
Open Social now requires at least PHP 7.4
https://www.drupal.org/node/3238767
N/a

Issue #3238766 by Kingdutch: Require at least PHP 7.4

---

modules/custom/social_graphql/tests/src/Kernel/GraphQLTestBase.php
modules/custom/social_graphql/tests/src/Kernel/SocialGraphQLTestBase.php
modules/social_features/social_profile/tests/src/Kernel/GraphQLUsersEndpointTest.php
modules/social_features/social_user/tests/src/Kernel/GraphQL/GraphQLUsersEndpointTest.php
modules/social_features/social_user/tests/src/Kernel/GraphQL/GraphQLViewerEndpointTest.php
phpstan-baseline.neon

The `GraphQLTestBase` of the graphql module creates a user during set-up
and installs languages. This may be problematic in case we have a module
that acts on this (e.g. through hook_user_insert) and then relies on
their own configuration that may not yet be installed. This happens
because all modules are installed before `setUp` is called (enabling
their hooks) but the GraphQL module's `setUp` is called before some of
our own config is installed (to ensure dependent config is installed in
the proper order).
The easiest way to solve this is to duplicate everything we need but
remove the offending lines. We already expected tests to be explicit
about setting up their test user in the class. We choose to keep a
separate class so that it's clear what is part of the `graphql` module's …

Use own copy of `GraphQLTestBase` in tests

---

modules/social_features/social_activity/social_activity.tokens.inc
modules/social_features/social_activity/src/EmailTokenServices.php
modules/social_features/social_comment/social_comment.tokens.inc
modules/social_features/social_content_report/social_content_report.tokens.inc
modules/social_features/social_event/social_event.tokens.inc
modules/social_features/social_follow_taxonomy/social_follow_taxonomy.tokens.inc
modules/social_features/social_group/modules/social_group_request/social_group_request.tokens.inc
modules/social_features/social_group/social_group.tokens.inc
modules/social_features/social_like/social_like.tokens.inc
modules/social_features/social_mentions/social_mentions.tokens.inc
modules/social_features/social_private_message/social_private_message.tokens.inc

In #2277 we created a new service that accepted strings in a `getCtaButton` method. Meanwhile Drupal has great types for the things that we are processing. Using string types caused two problems:
- Call to action texts are not translatable (since the string literals were not wrapped in a translatable class or function, static analysis can not find them)
- URLs may be empty or invalid. Since we were relying on path literals rather than Drupal routes, a change in paths could break emails being sent (e.g. because someone changes the path structure or because a language on the site requires a localised path).
Switch over to using `Url` and `TranslatableMarkup` classes.
Looking at the goal of the function being called we should be able to go a step further and use `Link` classes, maybe even …

New email call to actions are not translatable

---

.github/workflows/drupalCodingStandards.yml
modules/social_features/social_group/social_group.install
modules/social_features/social_user/tests/src/Kernel/GraphQL/GraphQLUsersEndpointTest.php
phpcs.xml

Our PHPCS configuration and CI set-up has a few bugs.
Specifically running PHPCS on the entire `social` folder no longer works because the themes are no longer included. This is not noticed in PRs because PHPCS only runs against changed files (that aren't removed).
Additionally our PHPCS workflow doesn't catch warnings which means that we aren't alerted of using variables in Drupal translation functions, e.g.: https://github.com/goalgorilla/open_social/commit/d29174775d9a52f5afc7b7372b5d28df7de9e835#diff-8830e9f8d111250aa50db10f31d5d9e4c66990800cc26adb86686dbb3c6fa911R251
- Remove themes
- Enable warnings in the GitHub workflow.
CI change, no issue
CI change, n/a

Fix PHPCS configuration

---

scripts/README.md
scripts/pre-commit.sh

We have a lot of "Fix coding standards" commits that are really annoying in a git history because they tell you nothing about the change.
The script makes it easy to execute all the things that we also run in
our GitHub workflows. This makes it easier to check those things
locally.
It can also easily be used in `git bisect` or `git rebase --exec` to
find a broken commit or verify that each commit is working.
For example `git rebase --exec scripts/pre-commit.sh --reschedule-failed-exec main` will go through each commit in your current branch as it's placing it onto `main` and run PHPCS, PHPStan and PHPUnit. If any of those errors the rebase will halt and you can clean up the errors. When you use `git rebase --continue` the checks will automatically be applied again (thanks to …

Add script that can be run as pre-commit hook

---

modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/social_follow_landing_page.module

In this [PR](https://github.com/goalgorilla/open_social/pull/2566) I've missed one critical thing. If we add parent term to the following block on the Landing page then we get an error:
`Error: Call to a member function getName() on bool in social_follow_landing_page_preprocess_paragraph() (line 61 of profiles/contrib/social/modules/social_features/social_follow_taxonomy/modules/ social_follow_landing_page/social_follow_landing_page.module)`
As even first level tags have a parent with a "0" id we need to check if the term does not have any "real" parent terms.
https://www.drupal.org/project/social/issues/3246407
https://getopensocial.atlassian.net/browse/YANG-6521
N/A
N/A
N/A
N/A

Issue #3246407 by tBKoT: Check if parent term exist on the Follow Tag on the Landing Page

---

modules/social_features/social_tagging/config/install/social_tagging.settings.yml
modules/social_features/social_tagging/config/schema/social_tagging.schema.yml
modules/social_features/social_tagging/social_tagging.install

Initially the content types didn't have a default settings, this caused an issue where on a clean installation, users would need to re-save the social tagging in order to work. Also added a hook update to enable it by default on all already installed content types, since this is the expected behaviour
On a clean installation, user should be able to create and add tags to the following content types as a default behaviour:
- Book page
- Event
- Basic page
- Topic
- Enable tags by default for the following content types: Book page, event, basic page, topic
- Add a hook update to social_tag to enable tags on all installed content types as default true
https://www.drupal.org/project/social/issues/3246398
N/A
N/A
N/A
N/A

Issue #3246398 by tbsiqueira: Social Tag Settings not working on a new installation

---

modules/social_features/social_content_block/src/ContentBuilder.php

When uses MySQL ^5.7 with ONLY_FULL_GROUP_BY sql_mode, then custom content list block does not fetch any element.
**Error message:**
`Drupal\Core\Database\DatabaseExceptionWrapper: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'opensocial.base_table.changed' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by: SELECT base_table.nid AS nid FROM {node_field_data} base_table WHERE base_table.type = :db_condition_placeholder_0 GROUP BY base_table.nid ORDER BY base_table.changed DESC LIMIT 5 OFFSET 0; Array ( [:db_condition_placeholder_0] => topic ) in Drupal\social_content_block\ContentBuilder->getEntities() (line 201 of …

Issue #3247237 by rolki: Custom content list block not working with Mysql 5.7 and ONLY_FULL_GROUP_BY

---

modules/custom/activity_logger/activity_logger.tokens.inc
modules/social_features/social_activity/social_activity.tokens.inc

After the Open Social update to 10.3, we noticed fatal errors on activity streams. They were related to missing `field_message_related_object` during token generations.
Add additional check if $messaage actually has related object field:
```
$message->hasField('field_message_related_object') && !empty($message->get('field_message_related_object')
```
https://www.drupal.org/project/social/issues/3247222
*For example*
Add additional check if $messaage actually has related object field t prevent fatal errors during activity tokens genrations.
No 
No

Issue #3247222 by ribel: Fix fatal error in activity tokens when related object doesn't exist

---

modules/social_features/social_post/modules/social_post_album/social_post_album.module
modules/social_features/social_post/modules/social_post_album/social_post_album.services.yml
modules/social_features/social_post/modules/social_post_album/src/SocialPostPhotoAlbumConfigOverride.php

In the config overrides exists code that never applied:
- `modules/social_features/social_post/modules/social_post_album/src/SocialPostPhotoAlbumConfigOverride.php`
Also,  during updating OS to 10.3 a run time error is rising (see screenshot).
- Move unapplied code from config overrides to appropriate hooks etc.
- https://www.drupal.org/project/social/issues/3246384
*Move unapplied code from config overrides to appropriate hooks etc.*
N/A
N/A

Issue #3246384 by vnech: Move unapplied code from Album config override

---

modules/social_features/social_activity/src/EmailTokenServices.php

Updating the Open Social version to `10.3.1` with `PHP 7.3` cause error:
`ParseError: syntax error, unexpected 'EntityTypeManager' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in Composer\Autoload\includeFile() (line 34 of /profiles/contrib/social/modules/social_features/social_activity/src/EmailTokenServices.php)`
Remove type from properties.
- https://www.drupal.org/project/social/issues/3248383
N/A
Fixed error related to typed properties on `PHP 7.3` in `modules/social_features/social_activity/src/EmailTokenServices.php`.
N/A
N/A

Issue #3248383 by Ressinel: Open Social version 10.3.1 is not supported by PHP 7.3 - It works good with PHP 7.4

---

modules/social_features/social_tagging/social_tagging.module
modules/social_features/social_tagging/src/Plugin/Block/SocialGroupTagsBlock.php
modules/social_features/social_tagging/src/Plugin/Block/SocialTagsBlock.php
modules/social_features/social_tagging/src/SocialTaggingService.php
phpstan-baseline.neon

It's possible to add unpublished content tags to the content which is not logical.
Change the process how we can taxonomy terms for the select options
https://www.drupal.org/project/social/issues/3247742
https://getopensocial.atlassian.net/browse/YANG-6546
Now content creators can not use unpublished Content tags for content tagging.
N/A
N/A

Issue #3247742 by tBKoT: Disallow to use unpublished content tags

---

modules/custom/activity_creator/activity_creator.tokens.inc
modules/custom/activity_logger/activity_logger.tokens.inc
modules/social_features/social_activity/social_activity.tokens.inc
modules/social_features/social_comment/social_comment.tokens.inc
modules/social_features/social_follow_taxonomy/social_follow_taxonomy.tokens.inc
modules/social_features/social_group/social_group.tokens.inc
modules/social_features/social_like/social_like.tokens.inc
modules/social_features/social_mentions/social_mentions.tokens.inc

`Error: Call to a member function getVotedEntityType() on null in social_like_tokens_alter() (line 152 of profiles/contrib/social/modules/social_features/social_like/social_like.tokens.inc). `
Also, I've noticed that we do have a not correct condition to check if the field is empty here #2277 which could provide critical issues on the token replacement process.
`empty($entity->geet('<field_name>'))` will always return FALSE, so better to ALWAYS use already existing method `isEmpty()` for field values.
Check if the like exists and we do not use the `NULL` value.
https://www.drupal.org/project/social/issues/3247896
https://getopensocial.atlassian.net/browse/YANG-6552
N/A
N/A
N/A
N/A

Issue #3247896 by tBKoT: Fix errors with activity tokens when the related object does not exist

---

modules/social_features/social_like/social_like.module

I'm logged in as admin. If I try to see the comments under the discussions, they don't load.
Looks like after upgrading like_and_dislike module hasn't changed inherited functionality:
In the **8.x-1.0-alpha2** version there is the following:
>    $build['icons'] = [
'#theme' => 'like_and_dislike_icons',
'#attached' => ['library' => ['like_and_dislike/icons']],
'#entity_id' => $entity_id,
'#entity_type' => $entity_type_id,
'#likes' => $likes,
'#dislikes' => $dislikes,
'#like_attributes' => $like_attributes,
'#dislike_attributes' => $dislike_attributes,
];
and it was changed in **8.x-1.0-beta2** to:
>    $like_attributes = new Attribute([
'title' => $this->t('Like'),
'data-entity-id' => $entity_id,
'data-entity-type' => $entity_type_id,
]);
...................................
> …

Issue #3248515 by SV: Comments do not load when there is unpublished item in the thread

---

composer.json

Since the last update of the like module, only Administrators can like the content.
Looks like there is an issue in the like_and_dislike module and we should include a patch to fix the current issue for all projects
- https://www.drupal.org/project/social/issues/3248421
- https://www.drupal.org/project/like_and_dislike/issues/3247929
- https://getopensocial.atlassian.net/browse/YANG-6530
- Fixes the issue with "liking/disliking" a content

Issue #3248421 by SV: As LU+ I can not like any content

---

modules/social_features/social_search/social_search.module

When on /search/group page, the type filter will always display even if you go to the view settings and remove the filter. The reason for this is because we are programetically overriding it. This is a problem if you want to remove this filter, currently it is not possible and you can only do it via code.
We need to check if the the form for this filter includes the 'type' element, if not then we should not override it.
https://www.drupal.org/project/social/issues/3247843
1. Go to admin/structure/views/view/search_groups
2. Remove the 'Group datasource: Type (exposed)' filter and save it
3. Go to search/groups and see that the filter is still showing
The type filter was removed from the view:
*If this …

Issue #3247843 by nkoporec: Don't override the group types on search view if the filter is not active

---

modules/social_features/social_featured_items/templates/paragraph--featured-item--default.html.twig

The tooltip does not display when you hover on the featured info icon on the featured item teaser
Add `data-title` attribute to the icon
https://www.drupal.org/project/social/issues/3247700
https://getopensocial.atlassian.net/browse/YANG-6566
*For example*
N/A
The tooltip displays when you hover on the info icon on the featured item teaser.
N/A
N/A

Issue #3247700 by agami4: Add data-title attribute to the icon of the featured item

---

composer.json

The status report page shows an error of missing `jquery-ui-touch-punch/jquery.ui.touch-punch.min.js`  library.
**drupal/jquery_ui_touch_punch needs library** is dependency of **"drupal/better_exposed_filters" which requires "furf/jquery-ui-touch-punch"** which is available in npm here: https://www.npmjs.com/package/jquery-ui-touch-punch
Add "npm-asset/jquery-ui-touch-punch": "^0.2.3 in composer.json
https://www.drupal.org/project/social/issues/3248947
N.A
N.A
N.A
N.A

Issue #3248947: Added missing library for drupal/jquery_ui_touch_punch.

---

modules/social_features/social_event/modules/social_event_type/social_event_type.module
tests/behat/features/capabilities/event/event-create.feature

When we use the event types then it should be shown instead of the `Event` label above the title.
Fix incorrect condition in the `social_event_type.module`.
Add test or scenario to check changes.
https://www.drupal.org/project/social/issues/3228303
https://getopensocial.atlassian.net/browse/YANG-6161
*For example*
N/A
N/A
N/A

Issue #3228303 by tBKoT: Use event type label instead of 'Event'

---

composer.json

On a multilingual website, when a user creates content in one language and then moves it to a group, a redirect is registered for that path in the language of the user. But when a user from a different language tries to access the old link the content is not found as the redirect is not registered for that language.
Add patch from https://www.drupal.org/project/redirect/issues/2991423#comment-13657465
https://www.drupal.org/project/social/issues/3249894
https://getopensocial.atlassian.net/browse/TB-5925
N.A
We fixed a redirection issue where when the content of one language is moved within a group, it cannot be accessed by its old URL by a user of another language.
N.A
N.A

Issue #3249894 by navneet0693: Added patch on redirect module for allowing redirection when the interface language is different from content language.

---

modules/social_features/social_search/src/EventSubscriber/RedirectSubscriber.php
modules/social_features/social_search/src/Form/SearchContentForm.php
modules/social_features/social_search/src/Form/SearchHeroForm.php

When Social is installed under a domain's directory, ex. http://www.example.com/social/, search forms and their exposed filters redirect to the wrong path once submitted.
Specifically, SearchContentForm and SearchHeroForm use Url::fromUserInput() which includes the base path resulting in a url like the following http://www.example.com/social/social/search/content/term.
The exposed filters of the form present the opposite problem; when submitting, they strip the base path from the url, so we end up with something like http://www.example.com/search/content/term?type=event
N/A
- https://www.drupal.org/project/social/issues/3102720
N/A
Fix issue where search form submit redirects to the wrong path when the installation is under a subdirectory.
N/A
N/A

Issue #3102720 by epapaniko, Ressinel: Search form submit redirects to the wrong path when the installation is under a subdirectory.

---

modules/social_features/social_group/social_group.module

We already do not need this code since the issue where the exposed flag filter can't show unflagged groups was fixed.
Remove code.
- https://www.drupal.org/project/group/issues/3219902
N/A
N/A
N/A
N/A

[Internal] - Remove unneeded code.

---

composer.json
tests/behat/features/bootstrap/FeatureContext.php

Whenever we update our theme to “sky” by default for new installs (not for existing customers), it also means our Behat tests will be running on Sky because behat is running on both new install / updates in our Distribution
So that will break all our tests if we don’t fix it.
Making sure we run our tests on the old theme.
- https://www.drupal.org/project/socialblue/issues/3251299
N/A
N/A
N/A
N/A

[Internal] - Make sure we run our tests on the old theme.

---

modules/social_features/social_follow_taxonomy/templates/activity--followed.html.twig
modules/social_features/social_follow_taxonomy/templates/activity--node--followed.html.twig

Text **"related to tag(s) you follow"** intro text of the "followed" items is not translatable on the stream.
Replace:  `<span>{{ content_type }} related to tag(s) you follow:</span> ` in the  related twig template
With following:   `<span>{{ content_type }} {% trans %} related to tag(s) you follow: {% endtrans %}</span>` 
- https://www.drupal.org/project/social/issues/3251664
- https://getopensocial.atlassian.net/browse/YANG-6597
Make intro text of the followed items translatable on the stream page

Issue #3251664 by SV: Intro text of the "followed" items is not translatable on the stream

---

modules/social_features/social_follow_taxonomy/social_follow_taxonomy.tokens.inc

Notification messages about tagging content use the [social_taxonomy:content_type] token which is not translatable
Use label instead of machine name of the content type in the token replacement
- https://www.drupal.org/project/social/issues/3251371
- https://getopensocial.atlassian.net/browse/YANG-6597
*For example*
*If this Pull Request makes visual changes then please include some screenshots that show what has changed here. A before and after screenshot helps the reviewer determine what changes were made.*
Fixes a translation issue for [social_taxonomy:content_type] token in the notification messages

Issue #3251371 by SV: Token [social_taxonomy:content_type] is not translatable

---

modules/social_features/social_tagging/social_tagging.module

We can not use taxonomy terms with special characters as a filter field for a content search
Change the function which converted term names to the field names to replace any of the special characters
https://www.drupal.org/project/social/issues/3250345
https://getopensocial.atlassian.net/browse/YANG-6663
The process of replacing the term with machine-readable has changed. Now all non-alphanumeric characters are replaced with underscores
N/A
N/A

Issue #3250345 by tBKoT: Changes the process of converting a term name to a machine-readable name

---

modules/social_features/social_book/src/SocialBookConfigOverride.php

For example on Share Square - if I search the term MDR. the All page shows 4 results, only the ones with MDR in the title, while the Content page show 19 results where MDR is also mentioned in the description of the nodes. So seems the All page does not index the content of the nodes, while Content does. is that something that can possibly be fixed?
I just searched "extensions" on Community Talks. and it seems that the All page also does not index the content of the Book page, but it does index the content of Topics & Events. So it might only be so for book pages? Or different settings per content type.
Update `modules/social_features/social_book/src/SocialBookConfigOverride.php`
- https://www.drupal.org/project/social/issues/3252054
Fixed issue for the search all when book content cannot …

Issue #3252054 by Ressinel: Search all results should show correct information.

---

modules/social_features/social_group/modules/social_group_invite/src/Form/SocialBulkGroupInvitation.php

When group managers are inviting users to the group they currently can select existing members too. The invite batch will go through but no invites will actually be sent, but this is still a bad UX.
If the user is already a member of the group an error should show up.
https://www.drupal.org/project/social/issues/3248205
1. Create a group
2. Invite a user to the group and accept the invitation as that user
3. After the user is already a member of the group invite him again.
4. See that no error will show up
*If this Pull Request changes the way that developers should do things or introduces a new API for developers then a change record to document this is needed. Please provide a draft for a change …

Issue #3248205 by nkoporec: Group managers should not be allowed to send invitations to users that are already part of the group

---

modules/social_features/social_event/modules/social_event_addtocal/src/Controller/AddToCalendarIcsController.php

The default Calendar app on Mac OS or on an iPhone is not importing the events exported using the iCal add to calendar feature. On the desktop the Calendar app imports the event but it is not shown after, on an iPhone a parsing error is shown during the import.
After investigating, the emojis are supported in Calendar app on OSX, so I checked the file that Open Social export and the file that the Calendar app exports and I found out that it is adding the 'TRANSP' property to the VEVENT which is missing in the Open Social export file.
https://www.drupal.org/project/social/issues/3254503
1. Enable the social_event_addtocal module
2. Under module settings enable the iCal export
3. Create an event with emojis in title and body
4. Click the Add to calendar button and select the iCal
5. Try to …

Issue #3254503 by nkoporec: iCal is not importing to Calendar (Mac OSX) if the event contains emojis

---

modules/social_features/social_embed/src/Plugin/Filter/SocialEmbedUrlEmbedFilter.php
modules/social_features/social_embed/src/Service/SocialEmbedHelper.php

Wrong instance passed to the constructor of **_SocialEmbedHelper_**.
`TypeError: Argument 1 passed to Drupal\social_embed\Service\SocialEmbedHelper::__construct() must be an instance of Drupal\Component\Uuid\Php, instance of Drupal\Component\Uuid\Pecl given in Drupal\social_embed\Service\SocialEmbedHelper->__construct()`
_**SocialEmbedHelper**_ expects `Drupal\Component\Uuid\Php` class because that is what core service _**uuid**_ offers.
Because of compatibility there is a service alter on CoreServiceProvider::alter that checks for existing functions and this can lead to a different class injection at SocialEmbedHelper
```
$uuid_service = $container->getDefinition('uuid');
// Debian/Ubuntu uses the (broken) OSSP extension as their UUID
// implementation. The OSSP implementation is not …
```

Issue #3254114 by tbsiqueira: Wrong UuidInterface instance on SocialEmbedHelper

---

composer.json

Update data policy module to use the new beta version
N/A
N/A
N/A
N/A

INTERNAL | Update data_policy to 2.0.0 for Drupal 9.2 compatibility

---

modules/custom/mentions/src/Plugin/Filter/MentionsFilter.php
modules/custom/mentions/templates/mention-link.html.twig

There is an issue for sites installed in the subfolder and the domain looks like: https://example.com/community.
When mention you're redirected to a non-existent page (e.g. https://example.com/user/9/information) because the /community URL section is missing (the right URL would be, for instance, https://example.com/community/user/9/information).
Replace hardcoded `/` in template with `base_path()` function in the preprocess.
- https://www.drupal.org/project/social/issues/3254196
- https://getopensocial.atlassian.net/browse/YANG-6760
Fix mention link output to work with the sites installed under a subdirectory.
N/A
N/A

Issue #3254196 by ribel: Fix mention link output to work with the installation under a subdirectory

---

phpstan-baseline.neon
phpstan.neon

Update PHPStan.neon file.
1. Remove rule: '#Plugin manager has cache backend specified but does not declare cache tags.#' as https://github.com/mglaman/phpstan-drupal/issues/112 was resolved.
2. Remove obselete ignore errors: '#Class PHPUnit\Framework\TestCase not found#' and '#Reflection error: PHPUnit\Framework\TestCase not found#'. These errors are resolved by a properly configured phpstan/phpunit and an (in)direct phpunit/phpunit (dev-)dependency in the project
3. Remove `reportUnmatchedIgnoredErrors: false` because we want our PHPStan to tell us when our baseline includes things that are fixed.
4. Regenerate baseline.
[Internal]
N.A
N.A
N.A
N.A

[Internal] Update PHPStan.neon

---

modules/custom/grequest/src/Form/GroupRequestMembershipForm.php
phpstan-baseline.neon

Follow up of #2669
`GroupRequestMembershipForm` class was using `self::TYPE_ERROR` which does not exist on Form classes. It should have been `MessengerInterface::TYPE_ERROR`.
Use the messenger corresponding methods to display a Status or an Error.
- https://www.drupal.org/project/social/issues/3256120
N/A
N/A
N/A
N/A
N/A

Issue #3222835 by curriedn, Ressinel: GroupRequestMembershipForm was using non-existing constant

---

modules/social_features/social_core/src/Entity/EntityAutocompleteMatcher.php

Now, the `entity autocomplete` fields that use the view as a handler returns nothing because views cannot be found.
I've noticed that problem in `EntityAutocompleteMatcher`, it has incorrect the `$options` array for instances. For example, I can not find any field in the distro, only in extensions.
Make the `$options` array be like in extended class.
- https://www.drupal.org/project/social/issues/3255928
Entity autocomplete works as expected.
N/A
N/A

Issue #3255928 by tBKoT: Fix enity autocomplete when views is using

---

modules/social_features/social_profile/social_profile.module

Private messages are still visible on the page “All Members” and this allows everyone to send messages to everybody. The link “Private message” should not be visible for a normal user if they doesn't have "create private messages thread" permission.
Use addition check if the current user has `create private messages thread` permission.
- https://www.drupal.org/project/social/issues/3255823
- https://getopensocial.atlassian.net/browse/YANG-6625
Hide a "Private message" button if user doesn't have "create private messages thread" permission.

Issue #3255823 by SV: Hide "Private message" button if user doesn't have "create private messages thread" permission.

---

.github/dependabot.yml
phpstan-baseline.neon
tests/composer.json

We noticed not locking our phpstan ruleset (phpstan-drupal) would mean whenever a patch or minor version was released all our PR's on top of main were breaking. Eventhough the information might be correct, we can't have such a breaking workflow.
We have now locked the package and start utilizing Dependabot to update the actual package(s) in our `/tests/composer.json`, this should give us a nice PR showing the breaking changes that were introduced so we can immediately fix it in our pull requests.
Internal fix for workflow.
See that PHPSTan now passes

[Internal] Lock our phpstan rules and utilize dependabot to update the dependencies

---

.github/dependabot.yml

Your .github/dependabot.yml contained invalid details
https://github.com/goalgorilla/open_social/pull/2676/checks?check_run_id=4703238785
Shorten the prefix of commit message.
N.A
N.A
N.A
N.A
N.A

[Internal] Updated commit message prefix for dependabot as limit is 15 characters.

---

modules/social_features/social_core/config/update/social_core_update_11005.yml
modules/social_features/social_core/social_core.install

The social medium image style doesn't show correctly the cropped image.
Change the image style for the “Social medium” to use the small crop type.
https://www.drupal.org/project/social/issues/3251038
*For example*
1. Create an event adding an image and crop it:
2. Check the small cropped image on homepage on the Upcoming events block:
**Before**
**After**
None
None
None

Update social medium image style configuration to use crop small type

---

composer.json

Remove support to datepicker on our date fields due to Drupal 9 removing JQueryUI datepicker because jQueryUI is no longer being supported.
The implication is that the datepicker will now be handled by browsers native support.
For more information, please take a look at the following links:
Deprecate and remove jQuery UI datepicker
jQuery UI datepicker deprecated and core usages removed
Most jQuery UI asset libraries are deprecated and moved to contrib modules
Remove the library and let browsers handle date fields natively.
https://www.drupal.org/project/social/issues/3256449
https://www.drupal.org/project/socialblue/issues/3256450
https://www.drupal.org/project/socialbase/issues/3256388
**Before:**
**After:**
We are removing deprecated date picker and time picker libraries due to removal …

Issue #3256449 by navneet0693, tbsiqueira, skatheeth, andregp: Remove deprecated jQuery UI datepicker.

---

modules/social_features/social_event/modules/social_event_invite/social_event_invite.module

If you delete an event, the co-responding event invites are not deleted. This means that if a user has a pending invite and the event gets deleted, the user will keep seeing the pending invite notification even though the event no longer exists.
When deleting an event, we should also delete all invites for that event.
https://www.drupal.org/project/social/issues/3256341
1. Create an event
2. Invite an authenticated user to the event
3. Log in as that user and see your pending invites
4. As admin delete this event
5. Login back as authenticated user and see you pending invites.
When deleting an event make sure that all invites gets deleted as well.
*If this Pull Request changes the way that developers should do things or introduces a new API for developers then a change record to document …

Issue #3256341 by nkoporec: When deleting an event, delete the event invites too

---

composer.json
modules/social_features/social_profile/src/Plugin/views/filter/SocialSearchApiSplitProfileTerms.php
modules/social_features/social_search/social_search.module
modules/social_features/social_search/social_search.services.yml
modules/social_features/social_search/src/EventSubscriber/SearchApiSubscriber.php
modules/social_features/social_search/src/Plugin/views/filter/SocialDate.php
phpstan-baseline.neon

There is a broken date filter on Content/User search pages.
1. Removed patch from https://www.drupal.org/project/search_api/issues/3248183#comment-14284072 as it was breaking event dispatching.
2. Added event subscriber to map our custom date views filter to search api date filter. This was done in favor of https://www.drupal.org/node/3059866.
3. Refactored code to make the form work again.
https://www.drupal.org/project/social/issues/3257221
**Before:**
**After:**
We have fixed a bug in exposed form on the Search content and user form which contain "Date of Event" and "Registration Date" filter respectively.
N.A
N.A

Issue #3257221 by navneet0693,ronaldtebrake,Ressinel: Broken search exposed form on search content and users.

---

modules/social_features/social_content_block/src/SocialContentBlockOverride.php

Fields Event types, Group types and Topic type in the custom content list block is not friendly for users which work with content. Now fields have type of autocomplete and users should keep in mind ​what values they want to type.
Change widget for fields from autocomplete to select list (select2_entity_reference).
https://www.drupal.org/project/social/issues/3251356
https://getopensocial.atlassian.net/browse/MAIN-311
1. Turn on the modules: Social Content Block, Social Event Content Block, Social Group Content Block
2. Make terms in vocabularies (Topic type,  Event types)
3. Add block custom content list (/block/add/custom_content_list?destination=/admin/structure/block/block-content)
4. Select type of content (Event, Group, Topic)
5. Start type in field (Event types, Group types, Topic …

Issuue #3251356 by yaroslav-shandra: Change type field widget from autocomplete to select list

---

composer.json
tests/composer.json

Lock PHPStan library version to avoid sudden PHPStan check failures. Recently, it was caused due to release of new phpstan library version https://github.com/phpstan/phpstan/releases/tag/1.4.1.
This was automatically updated as we require https://github.com/mglaman/phpstan-drupal and it has https://github.com/mglaman/phpstan-drupal/blob/main/composer.json#L15 which causes automatic updates.
See failures: https://github.com/goalgorilla/open_social/runs/4841468744?check_suite_focus=true#step:5:9
Fix https://github.com/phpstan/phpstan to 1.3.3
[Internal]
N.A
N.A
N.A
N.A

Locked phpstan/phpstan library as it is not locked to a specific version in mglaman/phpstan-drupal.

---

modules/social_features/social_group/social_group.module

When on the group page canonical URL, the 'Stream' tab does not have an 'active' class.
Add the missing class.
https://www.drupal.org/project/social/issues/3258954
1. Install Open Social
2. Disable the new 'Sky' styling
3. Go to the group stream page
4. See if the 'Stream' local task menu has an active class.
Before:
After:
*If this Pull Request changes the way that developers should do things or introduces a new API for developers then a change record to document this is needed. Please provide a draft for a change record or a link to an unpublished change record below. [Existing change records](https://www.drupal.org/list-changes/social) can be consulted as example.*
*Translatable strings are always …

Issue #3258954 by nkoporec: When on the group stream the local menu task is missing the active class

---

modules/social_features/social_user/src/Form/SocialUserLoginForm.php

With PHP 8.0 version when the user tries to submit with Invalid username/password it throws below website encounter error.
This error is due to PHP 8.0 version causing TypeError exception with error message passed to form element.
https://www.drupal.org/project/social/issues/3258139
N/A
N/A
N/A
N/A

Issue #3258139 by CurriedN, hitesh-jain, tbsiqueira: Invalid user name/password on login screen throws website error

---

composer.json

Backport SA-CORE-2022-001 to still supported 10.x Open Social versions
Backport SA-CORE-2022-001
https://www.drupal.org/project/social/issues/3259572
N/A
N/A
N/A
N/A

Issue #3259572 by tbsiqueira, navneet0693, ronaldtebrake: Backport Drupal 9.x SA-CORE-2022-001 to Open Social 10.x versions

---

modules/custom/activity_viewer/src/Plugin/views/filter/ActivityNotificationVisibilityAccess.php

I created my own custom entity. Then I decided to create a new message template to send "notification" message to some users.
Sending works as should. Receivers get the correct numbers of new messages (at the "bell" sign).
But the "notifications" doesn't displaying on the _/notifications_ page...
The issue is that the page is built with views and the view display using the filter plugin with hardcoded access rules - [modules/custom/activity_viewer/src/Plugin/views/filter/ActivityNotificationVisibilityAccess.php](https://github.com/goalgorilla/open_social/blob/main/modules/custom/activity_viewer/src/Plugin/views/filter/ActivityNotificationVisibilityAccess.php)
Add a general rule to the view filter plugin for accessing to activities by `field_activity_recipient_user` field
- …

Issue #3255221 by vnech: Make possible to display notifications created in custom entities context

---

composer.json

Our composer.json allows PHP 8, since Open Social is not fully tested, therefore supported, we need to remove it from Open Social 11
Remove PHP 8 from composer.json
https://www.drupal.org/project/social/issues/3260860
N.A
N.A
N.A
N.A

Issue #3260860 by navneet0693,tbsiqueira: Remove PHP 8 support from Open Social 11.

---

modules/social_features/social_swiftmail/social_swiftmail.install

The default swiftmailer config is to use sendmail with the <code>bs</code> option.
<blockquote>Stand-alone SMTP server mode. Read SMTP commands from standard input, and write responses to standard output.  In stand-alone SMTP server mode, mail relaying and other access
controls are disabled by default. To enable them, run the process as the mail_owner user.
This mode of operation is implemented by running the smtpd(8) daemon.
</blockquote>
The issue is that this mode isn't allowed on some more secure hosting providers (such as Platform.sh). Instead they will have their PHP settings configured to use the <code>t</code> option.
<blockquote>
Extract recipients from message headers. These are added to any recipients specified on the …

Issue #3261093 by Kingdutch: Fix out of the box swiftmailer config

---

modules/social_features/social_content_block/src/ContentBlockBase.php
modules/social_features/social_content_block/src/ContentBuilder.php

In the Custom content list block there are several sort options. None of them includes the last comments.
Add new sorting option for custom content list block that will apply for all content types - last commented
- https://www.drupal.org/project/social/issues/3260835
- https://getopensocial.atlassian.net/browse/YANG-6628
Adds a new option of sorting - last commented in custom content block

Issue #3260835 by SV: User should be able to see a list with the content with the latest comments

---

tests/behat/features/capabilities/private-message/create-private-message.feature

We have an error on a lot of PRs for test:
```
@api @private-message @DS-4372 @DS-5206 @stability-3 @create-private-message
Feature: Create Private Message
```
- Try to change the step right before the error.
N/A
N/A
N/A
N/A
N/A

[Internal] - Fix bahat test error. 

---

tests/behat/features/capabilities/private-message/create-private-message.feature

Follow up https://github.com/goalgorilla/open_social/pull/2736
We have an error on a lot of PRs for test:
```
@api @private-message @DS-4372 @DS-5206 @stability-3 @create-private-message
Feature: Create Private Message
```
- Try to change the step right before the error.
N/A
N/A
N/A
N/A
N/A

[Internal] - Fix bahat test error. (recreated)

---

modules/custom/social_magic_login/src/Controller/MagicLoginController.php
phpstan-baseline.neon

When trying to login with social_magic_link, certain users receive this error:
`Error: Call to undefined method Drupal\data_policy\DataPolicyConsentManager::hasGivenConsent()`
The hasGivenConsent() method no longer exists in data_policy, so we need to update it.
https://www.drupal.org/project/social/issues/3261513
1. Create a new user, but don't login yet
2. Make sure data_policy module is enabled
2. Create a magic login link using social_magic_link module
3. Visit the magic link
*If this Pull Request makes visual changes then please include some screenshots that show what has changed here. A before and after screenshot helps the reviewer determine what changes were made.*
*If this Pull Request changes …

Issue #3261513 by nkoporec: Error: Call to undefined method Drupal\data_policy\DataPolicyConsentManager::hasGivenConsent()

---

modules/social_features/social_profile/modules/social_profile_privacy/social_profile_privacy.module

In the backend, the **Site manager** can select which fields are available on the user profile. When a field is NOT selected, it does not show up on the user profile. But the unselected field still shows up in the Privacy settings of the users and this is confusing to see.
Profile fields that are not available on the platform should also not be visible in the user settings.
- https://www.drupal.org/project/social/issues/3265075
- https://getopensocial.atlassian.net/browse/TB-6028
N/A
Profile fields that are not available on the platform also not be visible in the user settings.
N/A
N/A

Issue #3265075 by Ressinel: Profile fields that are not available on the platform should also not be visible in the user settings.

---

modules/custom/activity_send/modules/activity_send_email/src/Plugin/EmailFrequency/Immediately.php
modules/custom/activity_send/modules/activity_send_email/src/Plugin/QueueWorker/ActivityDigestWorker.php

When we send digest emails sometimes tokens are not replaced. The main reason that related content was deleted before we generate the email
Check if a related entity still exists before creating the message for email.
- https://www.drupal.org/project/social/issues/3264208
- https://getopensocial.atlassian.net/browse/YANG-7105
Users will not receive emails for activities where related content does not exist
N/A
N/A

Issue #3264208 by tBKoT: Do not send emails if related content does not exist

---

modules/custom/entity_access_by_field/entity_access_by_field.module
modules/custom/entity_access_by_field/src/EntityAccessByFieldPermissions.php
modules/custom/entity_access_by_field/src/EntityAccessHelper.php
modules/custom/entity_access_by_field/tests/src/Unit/EntityAccessTest.php
modules/social_features/social_group/social_group.module
phpstan-baseline.neon

For now, if we wanna use the 'entity_access_field' type for the base fields in entity types it is not possible because of some methods that do not exist in that kind of field definition. Also, widgets with multiple values do not support default values and we cannot use the "allowed_values_function".
- Use the `getName` method to generate permission labels.
- Check allowed values by using `allowed_values_function` if it exists, use same process as in the `options.module`
- Update default value in the `social_group_field_widget_form_alter` to make it possible use multiple values.
- https://www.drupal.org/project/social/issues/3262896
- https://getopensocial.atlassian.net/browse/YANG-6191
N/A
N/A
Now the `entity_access_field` field type could be used for the base field definitions and for …

Issue #3262896 by tBKoT: Make entity_access_by_field type more usefull

---

modules/social_features/social_private_message/social_private_message.install

```
>  [error]  Configuration objects (core.entity_form_display.message.private_message_notification.default, core.entity_view_display.message.private_message_notification.default, core.entity_view_display.message.private_message_notification.mail_body, core.entity_view_display.message.private_message_notification.mail_subject, field.field.message.private_message_notification.field_message_pm_thread, field.field.message.private_message_notification.field_message_private_message, field.storage.message.field_message_pm_thread, field.storage.message.field_message_private_message) provided by private_message_notify already exist in active configuration 
>  [error]  Update failed: private_message_update_8007 
```
- Before enabling the `private_message_notify` module, configurations, that …

Issue #3266049 by Ressinel: Error during the update.php after updating to 11.0.3 with Composer

---

modules/custom/social_lazy_loading/src/SocialLazyLoadingTextFormatOverride.php

"Lazy-loading is not enabled...." message always is shown.
Update SocialLazyLoadingTextFormatOverride so that it would be compatible with lazy:3.10
https://www.drupal.org/project/social/issues/3266990

Issue #3266990 by alex.ksis: Update config override to be compatible with lazy 3.11

---

.travis.yml

We have https://github.com/goalgorilla/drupal_social/blob/2.0.0/composer.json#L9 which now has latest additions in https://github.com/Roave/SecurityAdvisories/commit/5bd8c4f672d819d073ca8de1922fdb6898d0df3a which prohibits to install `drupal/core:~8.9.9`
See: https://app.travis-ci.com/github/goalgorilla/open_social/jobs/561687499#L303
Add a composer command to remove that dependency from the composer.json to facilitate success upgrade of composer.json
N.A
N.A
N.A
N.A
N.A

Added composer command to remove roave/security-advisories dependency from composer.json as it was conflict with our ugprade branch.

---

modules/social_features/social_group/src/Plugin/views/field/SocialGroupViewsBulkOperationsBulkForm.php

VBO action on Group membership page throws error when you select any custom actions defined for Group membership view
Error was caused due to incorrect key being used to fetch Selected action label and as it was invalid key to fetch Label it was empty and hence calling `render` function on empty label caused above error.
https://www.drupal.org/project/social/issues/3258123
N/A
N/A
N/A
N/A
N/A

Issue #3258123 by hitesh-jain, tbsiqueira: VBO actions on Group membership not working

---

modules/social_features/social_event/modules/social_event_invite/src/Controller/UserEnrollInviteController.php
modules/social_features/social_event/modules/social_event_invite/src/Form/EnrollInviteEmailForm.php
modules/social_features/social_event/modules/social_event_managers/src/Form/SocialEventManagersAddEnrolleeForm.php
modules/social_features/social_event/modules/social_event_managers/src/Plugin/views/field/SocialEventManagersViewsBulkOperationsBulkForm.php
modules/social_features/social_event/modules/social_event_max_enroll/config/install/field.field.node.event.field_event_max_enroll_num.yml
modules/social_features/social_event/modules/social_event_max_enroll/config/update/social_event_max_enroll_update_11001.yml
modules/social_features/social_event/modules/social_event_max_enroll/social_event_max_enroll.install
modules/social_features/social_event/modules/social_event_max_enroll/social_event_max_enroll.module
modules/social_features/social_event/modules/social_event_max_enroll/social_event_max_enroll.services.yml
modules/social_features/social_event/modules/social_event_max_enroll/src/Controller/UserEnrollInviteControllerAlter.php
modules/social_features/social_event/modules/social_event_max_enroll/src/EventMaxEnrollOverride.php
modules/social_features/social_event/modules/social_event_max_enroll/src/Routing/RouteSubscriber.php
phpstan-baseline.neon

**Should**: when users set a maximum of enrollees for their events, this maximum should not be exceeded.
**Is**: in a particular event, the organizers have set a maximum of 28 enrollees, however, it is able to enroll as the 30th user.
- Make sure that we always have the node object when we want to disable the **Enroll** button.
- Make sure that users can't accept invites if there are no spots left in an event.
- https://www.drupal.org/project/social/issues/3263114
- https://getopensocial.atlassian.net/browse/TB-5626
Limit of enrollees is **3**.
Details page:
Enrollments page:
The event invites page:
Details page:
Enrollments page:
The event invites page:
Fixed event issue where a user was able to exceed the limit of enrollees.
N/A
N/A

Issue #3263114 by Ressinel: Events maximum for enrollee's has been exceeded.

---

modules/social_features/social_profile/modules/social_profile_privacy/social_profile_privacy.module

After update to 11.1.x & D9 displays a notice on the "/all-members" page:
`Notice: Undefined index: children in social_profile_privacy_private_fields_list() (line 356 of profiles/contrib/social/modules/social_features/social_profile/modules/social_profile_privacy/social_profile_privacy.module).
`
Add a check to prevent the notice
- https://www.drupal.org/project/social/issues/3266003
- https://getopensocial.atlassian.net/browse/YANG-7178
Fixes  'Notice: Undefined index: children in social_profile_privacy_private_fields_list()'

Issue #3266003 by SV: Fix 'Notice: Undefined index: children in social_profile_privacy_private_fields_list()

---

composer.json

A fatal error occurred when creating content inside a group: **Call to undefined method Drupal\social_group\Entity\Group::urlInfo() in group_tokens**
The OS uses a patch for the group module which uses urlInfo method. The error happened because of the urlInfo was deprecated and now does not exists.
There is an updated patch for the group module which solves the original issue but also compatible with D9.
https://www.drupal.org/project/social/issues/3267357

Issue #3267357 by alex.ksis: Replace a patch for group for compatibility with D9.

---

composer.json

Update Social Blue theme to the latest 2.1.3 version
Update Social Blue theme to the latest 2.1.3 version
https://www.drupal.org/project/social/issues/3268097
N/A
N/A
N/A
N/A

Issue #3268097: Update social blue theme to the latest version

---

modules/social_features/social_comment/config/install/views.view.comment.yml
modules/social_features/social_comment/config/schema/social_comment.schema.yml
modules/social_features/social_comment/config/update/social_comment_update_11201.yml
modules/social_features/social_comment/social_comment.info.yml
modules/social_features/social_comment/social_comment.install
modules/social_features/social_comment/social_comment.module
modules/social_features/social_comment/tests/src/Kernel/CommentViewAccessTest.php
modules/social_features/social_comment/tests/src/Kernel/GraphQL/QueryCommentTest.php
modules/social_features/social_comment/tests/src/Kernel/GraphQL/QueryCommentsTest.php
modules/social_features/social_group/social_group.views.inc
modules/social_features/social_group/src/Plugin/views/filter/FilterByGroup.php
phpstan-baseline.neon

As a CM+ I want to filter comments in the comments overview
Add configuration for comment view in the `social_comment` module same as it was done for the `People` page. Add update for existing projects.
To fix syles for the `Select2` widget use a patch from this issue for the Gin theme -> https://www.drupal.org/project/gin/issues/3246977
- https://www.drupal.org/project/social/issues/3265644
- https://getopensocial.atlassian.net/browse/YANG-6821
Now content/site managers are able to filter comments by commented content title/type or by a group where commented content is.
N/A
N/A

Issue #3265644 by tBKoT: Adds filtration on the comment overview pages

---

modules/social_features/social_event/src/Form/EnrollRequestDeclineForm.php
modules/social_features/social_profile/src/SocialProfileNameService.php
phpstan-baseline.neon

If the user id is out of sync with the profile id the wrong name is displayed in the in the decline request confirmation and the success message. The reason is that the profile entity is loaded directly with the user id of the user.
Instead of loading the profile directly by id use EntityTypeManagerInterface loadByProperties to get the profile for the specific user.
- https://www.drupal.org/project/social/issues/3263649
TBD
N/A
TBD
N/A
N/A

Issue #3263649 by Corn696, Ressinel: Fix wrong profile name for event enrollment decline request messages.

---

composer.json

The **Social Base** theme patch is not applying.
Remove **Social Base** theme patch since those changes were released in the last theme version:
- Release https://www.drupal.org/project/socialbase/releases/2.1.5
- MR https://git.drupalcode.org/project/socialbase/-/merge_requests/81
N/A
N/A
N/A
N/A
N/A

[Internal] - Remove Social Base theme patch since those changes were released in last theme version.

---

modules/custom/social_magic_login/src/Controller/MagicLoginController.php

If you have a data policy and use the social magic link, then the 'destination' param is removed when going to the data policy agreement form.
We need to pass the 'destination' query param when displaying the data policy message in social magic login controller.
https://www.drupal.org/project/social/issues/3268520
1. Set up the data policy
2. Use social magic login link
3. Click the data policy message link
4. After the form submits, see if you get redirected to the correct page.
*If this Pull Request makes visual changes then please include some screenshots that show what has changed here. A before and after screenshot helps the reviewer determine what changes were made.*
*If this Pull Request changes …

Issue #3268520 by nkoporec: The destination param is missing when logging in via the social_magic_link and accepting the data policy.

---

modules/custom/alternative_frontpage/alternative_frontpage.install

The alternative_frontpage_update_11101 hook is trying to create alternative frontpages even if they already exist.
Check if entities with the given ids already exists.
https://www.drupal.org/project/social/issues/3270932

Issue #3270932 by alex.ksis: Do not recreate alternative frontpages if they exist.

---

modules/social_features/social_core/src/Plugin/Field/FieldFormatter/FileAndImageTableFormatter.php

When creating a node that has attachments, the file is shown with the title, even when the description is filled in.
By altering the file_image_default field formatter we can add the description before it gets preprocess. Drupal will then pickup the description if it's filled in, instead of the title.
https://www.drupal.org/project/social/issues/3270782
https://getopensocial.atlassian.net/browse/TB-6704
- [] Create a Topic with an attachment
- [] Fill a description for the file
- [] Save
- [] See that the file description is shown
We fixed a bug where the description of a file was not shown. If you provide a description for a file, it will be shown instead of the title.

Add description before preprocessing for files

---

modules/social_features/social_footer/assets/css/social_footer.css
modules/social_features/social_footer/assets/css/social_footer.css.map
modules/social_features/social_footer/assets/css/social_footer.scss

If the image in the footer block is wide, then the text will expand beyond its parent.
The wrapper that wraps the image should not have the flex display when the screen width is really small. We should make it a block, so that elements will stack on top of each other.
https://www.drupal.org/project/social/issues/3268100
1. Add a wide image in the footer block
2. Add a couple paragraph of text
3. Check how it looks on mobile
Before:
After:
*If this Pull Request changes the way that developers should do things or introduces a new API for developers then a change record to document this is needed. Please provide a draft for a change record or a link to an unpublished change record below. [Existing change …

Issue #3268100 by nkoporec: Footer block image is not responsive

---

composer.json

We are using a patch that is no longer able to be applied:
- https://www.drupal.org/files/issues/2021-10-17/social-instaclick-webdriver-3226058-8.patch
The file changed on version 1.4.11 we need to re-roll the patch.
- https://github.com/instaclick/php-webdriver/blob/1.4.11/lib/WebDriver/AbstractWebDriver.php
- https://www.drupal.org/project/social/issues/3272386
N/A
N/A
N/A
N/A
N/A

Issue #3272386 by Ressinel: Patch for instaclick/php-webdriver is not longer being applied

---

modules/social_features/social_tagging/social_tagging.install

In 11.0.8 we introduced https://github.com/goalgorilla/open_social/pull/2527 which added social_tagging to the search indexes because sometimes they were not added correctly as it was using an override.
It seems that in some cases the field social_tagging already exists within the search indexes. In this case it will crash the update hook.
Make sure we double check if the field already exists in the search indexes before we add it.
https://www.drupal.org/project/social/issues/3272432
In our last release 11.0.8 we introduced a fix for being able to use content tags in the search pages, but didn't correctly check if the field was already present. This caused the update process to get stuck. This now has been solved.

Issue #3272432 by robertragas: Only add the social tagging field to the search index if it's not there yet

---

modules/custom/social_language/social_language.module

For some platforms the Translations report at /admin/reports/translations may crash when the provided timestamp is NULL and the template tries to create a time from it for the report.
By preprocessing the template file we can set all empty timestamp to 0, that way the report will keep working.
https://www.drupal.org/project/social/issues/3264434
The translation report has been fixed and should work for all platforms.

Issue #3264434 by nickmans: Set timestamp to 0 when timestamp is empty

---

modules/social_features/social_event/modules/social_event_an_enroll_enrolments_export/src/SocialEventAnEnrollEnrolmentsExportOverrides.php

Open Social showing PHP notice when I see the event enrollment list with no-enrollment
Trying to use values of type `null, bool, int, float or resource `as an array (such as `$null["key"]`) will now generate a notice.
`https://www.php.net/manual/en/migration74.incompatible.php#migration74.incompatible.core.non-array-access`
`open_social\modules\social_features\social_event\modules\social_event_an_enroll_enrolments_export\src\SocialEventAnEnrollEnrolmentsExportOverrides.php:44`
`$overrides[$config_name]['display']['default']['display_options']['fields']['social_views_bulk_operations_bulk_form_enrollments_1']['selected_actions']['social_event_enrolments_export_enrollments_action'] = 0;`
Assigning a zero value and is not checking if the actions are actually there in the configuration or not, …

Issue #3272941 by nijuley, tbsiqueria, Ressinel: PHP warning for event enrollment listing (with no-enrollment)

---

modules/social_features/social_group/social_group.module

When we add the translation of the content inside the group we lose their connection. It's happening because of using useless fields in this [patch](https://www.drupal.org/files/issues/2021-07-30/group-2718195-58-groups-computed-field.patch). It contains additional fields for every group type which we do not use. These fields check the values before the node saves and deletes the `group_content` entities.
Remove all useless `group_type` fields.
https://www.drupal.org/project/social/issues/3270158
Fixed bug with closed connection between content and group
N/A
N/A

Issue #3270158 by tBKoT: Remove useless fields

---

modules/social_features/social_group/config/install/views.view.group_topics.yml
modules/social_features/social_group/config/update/social_group_update_11004.yml
modules/social_features/social_group/social_group.install

Update the **Group Topics (Group content)** view by adding appropriate translation settings.
- https://www.drupal.org/project/social/issues/3273357
N/A
N/A
Fix the issue where a translated topic is displayed twice on the group topics page.
N/A
N/A

Issue #3273357 by Ressinel: Fix issue where translated topic is displayed twice on the group topics page

---

modules/social_features/social_group/modules/social_group_flexible_group/config/install/core.entity_form_display.group.flexible_group.default.yml
modules/social_features/social_group/modules/social_group_flexible_group/config/install/field.field.group.flexible_group.field_group_posts_enabled.yml
modules/social_features/social_group/modules/social_group_flexible_group/config/install/field.storage.group.field_group_posts_enabled.yml
modules/social_features/social_group/modules/social_group_flexible_group/config/static/field.field.group.field_group_posts_enabled_11201.yml
modules/social_features/social_group/modules/social_group_flexible_group/config/static/field.storage.group.field_group_posts_enabled_11201.yml
modules/social_features/social_group/modules/social_group_flexible_group/config/update/social_group_flexible_group_update_11202.yml
modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install
modules/social_features/social_group/social_group.module
modules/social_features/social_post/src/Plugin/Block/PostGroupBlock.php
phpstan-baseline.neon
tests/behat/features/capabilities/post/post-create-disabled.feature

In many communities, we have groups where all users are automatically added or groups that are used for coordination purposes only.
In these groups, we should be able to prevent regular users from posting so that communication is only going from the top-down and the purpose of the group can be fulfilled.
Right now every user can post so we end up with a lot of meaningless messages that push the user to mute the group altogether
Create a new field in the group, for now only in the flexible group, that will allow GMs to disable posting in groups for members.
- https://www.drupal.org/project/social/issues/3272707
- https://getopensocial.atlassian.net/browse/YANG-7371
N/A
Group manager now able to disable posting in groups for group members
N/A
N/A

Issue #3272707 by tBKoT: Allows GMs to decide if group members can leave a post

---

modules/social_features/social_group/modules/social_group_invite/src/Plugin/Block/SocialInviteLocalActionsBlock.php

Wrong group-ID when adding a member directly to a group
`/group/{group}/membership` resolves to a view, so the route parameter {group} isn't converted to a Group object for use by the route.group cache context. Changed it to use url.path as an alternative cache context.
- https://www.drupal.org/project/social/issues/3202509
N/A
That is correct.
Which is not correct. It should be: group/209/content/add/group_membership
N/A
Fixed wrong group ID when adding a member to a group directly.
N/A
N/A

Issue #3202509 by drasgardian, Ressinel: Wrong group-ID when adding a member to a group

---

modules/social_features/social_event/social_event.install

In https://github.com/goalgorilla/open_social/pull/2849 we missed defining a default size for the batch in `social_event_update_10306`. There can be a condition where project has not copied https://git.drupalcode.org/project/drupal/-/blob/9.2.16/sites/default/default.settings.php#L764 in their settings.php.
Add a default.
https://www.drupal.org/project/social/issues/3272898
N.A
N.A
Copy from https://github.com/goalgorilla/open_social/pull/2849
N.A
N.A

Issue #3272898 by navneet0693: Add a default of 50 if the entity_update_batch_size is not defined.

---

modules/custom/activity_send/modules/activity_send_push_notification/activity_send_push_notification.module

Error if Push plugin has no description in annotation:
`Notice: Undefined index: description in activity_send_push_notification_form_user_form_alter() (line 35 of profiles/contrib/social/modules/custom/activity_send/modules/activity_send_push_notification/activity_send_push_notification.module).`
```
activity_send_push_notification_form_user_form_alter(Array, Object, 'user_form') (Line: 539)
Drupal\Core\Extension\ModuleHandler->alter('form', Array, Object, 'user_form') (Line: 836)
Drupal\Core\Form\FormBuilder->prepareForm('user_form', Array, Object) (Line: 279)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 73)
Drupal\Core\Controller\FormController->getContentResult(Object, Object) (Line: 39)
Drupal\layout_builder\Controller\LayoutBuilderHtmlEntityFormController->getContent …
```

Issue #3274890 by Ressinel: Notice: Undefined index: description in activity_send_push_notification_form_user_form_alter()

---

yaml_translation_patterns.yml

A <code>yaml_translation_patterns.yml</code> file exists to instruct the POTX tool on how to translate our custom installer_options.yml files. However the top level key in that file should be <code>translation_patterns</code> but we have <code>translation_patters</code>
This issue has existed since the file was originally created in January 2020. However apparently Open Social is not regularly installed in a non-English language before the language is switched to something else, not making this problem very visible.
The required key can be seen [in the POTX tool](https://git.drupalcode.org/project/potx/-/blob/8.x-1.x/potx.inc#L2315).
Fix the typo
*Milestone set to 12.0.0 because translations are extracted from our `main` branch*. Therefore I believe no backport is required, unless this …

Issue #3273470 by Kingdutch: Installer options data is not translatable

---

composer.json
modules/social_features/social_profile/config/install/core.entity_view_display.profile.profile.teaser.yml
modules/social_features/social_profile/config/schema/social_profile.schema.yml
modules/social_features/social_profile/config/update/social_profile_update_11301.yml
modules/social_features/social_profile/social_profile.install
modules/social_features/social_profile/src/Plugin/Field/FieldFormatter/SocialProfileTextFormatter.php

As a User I want to see the short description on full size teasers.
- Use the short description field instead of the full description
- if it not filled in fall back to the long description and cap it at 140 char
- if this is not filled in leave empty
- https://getopensocial.atlassian.net/browse/YANG-7266
- https://www.drupal.org/project/social/issues/3272694
- https://www.drupal.org/project/socialbase/issues/3272691
Display short description or trimmed full description in profile full teaser.

Issue #3272694 by chmez, agami4: As a User I want to see the short description on full size teasers

---

modules/social_features/social_core/social_core.module
phpstan-baseline.neon

Currently, users have the ability to set author information, inside of that fieldset, they also have the ability to change the created timestamp. We don't validate the date, so users can set the created date in the future, which is a problem, because this date is used in other parts of Open Social, for example, the activity entity is using it, and if the date is in the future then activity date will also be in the future, which means that on /stream page, it will always be on top.
We need to add validation for that field, so users can't set the date in the future.
https://www.drupal.org/project/social/issues/3270714
1. Create a topic
2. Under Author information set the authored on date in the future
3. Save the topic and run cron
4. Wait a couple of minutes and go to the /stream page …

Issue #3270714 by nkoporec: Don't allow setting the created date in the future

---

modules/social_features/social_landing_page/social_landing_page.module

```
Warning: array_flip(): Can only flip STRING and INTEGER values! in Drupal\Core\Entity\EntityStorageBase->loadMultiple() (line 261 of core/lib/Drupal/Core/Entity/EntityStorageBase.php).
Drupal\Core\Entity\EntityStorageBase->loadMultiple(Array) (Line: 245)
Drupal\Core\Entity\EntityStorageBase->load(NULL) (Line: 488)
Drupal\Core\Entity\EntityBase::load(NULL) (Line: 308)
_social_landing_page_get_hero_image(Object) (Line: 252)
social_landing_page_preprocess_node(Array, 'node', Array) (Line: 287)
Drupal\Core\Theme\ThemeManager->render('node', Array) (Line: 436)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 201)
Drupal\Core\Render\Renderer->render(Array, ) (Line: 241)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 578) …
```

Issue #3063436 by Ressinel: Social landing page gives: Warning: array_flip(): Can only flip STRING and INTEGER values

---

modules/social_features/social_embed/social_embed.post_update.php

The if condition was meant for executing the update in database but it was in-correctly written. So, if the conditions were true, it said Batch API that it has finished instead of doing the update. 
Switch the if-else condition logic.
https://www.drupal.org/project/social/issues/3232309
N.A
N.A
We corrected an update that was meant to enable embed-consent for all users on existing platforms by default. This means that on an existing platform with social_embed module enabled, once the site manager enables the feature at `/admin/config/opensocial/embed-consent`, it will enable opt-in embed-consent option for all users automatically.
N.A
N.A

Issue #3232309 by navneet0693: Switched if-else condition in social_embed_post_update_11001_populate_field_embed_content_settings.

---

modules/custom/activity_basics/activity_basics.module
modules/custom/activity_creator/activity_creator.module
modules/custom/activity_creator/src/Plugin/QueueWorker/ActivityWorkerLogger.php
modules/custom/activity_logger/src/Plugin/QueueWorker/MessageQueueCreator.php
modules/custom/activity_logger/src/Service/ActivityLoggerFactory.php
modules/custom/activity_send/modules/activity_send_email/activity_send_email.module
modules/custom/activity_send/modules/activity_send_email/src/Plugin/AdvancedQueue/JobType/ActivitySendEmailJobType.php
modules/custom/activity_send/modules/activity_send_email/src/Plugin/QueueWorker/ActivityDigestWorker.php
modules/custom/activity_send/modules/activity_send_email/src/Plugin/QueueWorker/ActivitySendEmailWorker.php
modules/custom/activity_viewer/src/Plugin/views/row/ActivityRow.php
modules/custom/mentions/src/Plugin/Filter/MentionsFilter.php
modules/custom/social_queue_storage/social_queue_storage.module
modules/social_features/social_content_block/social_content_block.install
modules/social_features/social_content_block/social_content_block.module
modules/social_features/social_content_block/src/ContentBuilder.php
modules/social_features/social_event/modules/social_event_addtocal/social_event_addtocal.module
modules/social_features/social_event/modules/social_event_managers/src/Plugin/views/field/SocialEventManagersViewsBulkOperationsBulkForm.php
modules/social_features/social_follow_taxonomy/modules/social_follow_tag/social_follow_tag.module
phpstan-baseline.neon

Certain scenarios like:
1. configuration overrides
2. undefensive code
3. uninstalled modules not cleaning it's related data at the time of uninstalling
can lead to orphaned and/or junk data in entities in database. 
Sometimes the modules which are uninstalled may contain plugins and configuration overrides which can lead to the storage of unrequired data in the database. Also, on removal, these modules may not be related data from the database which leads to junk data.
These orphaned data crash pages and other views or blocks that render the "Activity" entity, for example.
A module declaring a plugin instance and attaching that instance with entities, for example, activities, was uninstalled; but during uninstall it didn't cleaned it's related data from activities. This will lead to …

Issue #3278347 by navneet0693: Junk plugin data can crash activity entity related view

---

modules/social_features/social_core/social_core.module

1. On Open Social 11.1.2 based multilingual platform with social_language and content_translation module enabled.
2. Open the website as an anonymous user.
3. Try to switch language from one language to another where one of the menu links doesn't have translated version of that particular language.
The PR #2831 introduced a problem where it throws an error whenever an anonymous user tried to switch website language via a language switcher blocker on an existing multilingual platform.
Switching of language triggers an action in Drupal core which checks for fallback language. See https://git.drupalcode.org/project/drupal/-/blob/9.2.17/core/modules/language/src/ConfigurableLanguageManager.php#L387 which also invokes https://git.drupalcode.org/project/drupal/-/blob/9.2.17/core/modules/content_ …

Issue #3275980 by navneet0693: Switching language on multilingual platform leads to unexpected error

---

modules/social_features/social_follow_user/config/install/views.view.followers_user.yml
modules/social_features/social_follow_user/config/update/social_follow_user_update_11203.yml
modules/social_features/social_follow_user/social_follow_user.install

The "Followers" title is displayed above the user's avatar on the mobile site version:
The title should be removed in the related views
- https://www.drupal.org/project/social/issues/3277470
- https://getopensocial.atlassian.net/browse/YANG-7634
Fixes a bug with displaying title on the followers page.

Issue #3277470 by SV: The "Followers" title is displayed on the followers page on Mobile

---

modules/social_features/social_profile/modules/social_profile_preview/social_profile_preview.module

1. If LU hover on the user's name on the "/user/inbox" page then the modal window doesn't appear:
2. The modal profile preview displays in notification popup:
1. Attach profile preview classes to the profile name of private message to display profile preview on hover (for example, like on the stream page).
2. Disable profile preview in notification popup
- https://www.drupal.org/project/social/issues/3278697
- https://getopensocial.atlassian.net/browse/YANG-7470
- Fixes a bug with profile preview on the Inbox page
- Disable profile preview in notification popup

Issue #3278697 by SV: Fix a bug with profile preview on the Inbox page and disable it in notification popup

---

modules/social_features/social_activity/src/EmailTokenServices.php

`Drupal\Component\Plugin\Exception\PluginNotFoundException: The "" entity type does not exist. in Drupal\Core\Entity\EntityTypeManager->getDefinition() (line 150 of core/lib/Drupal/Core/Entity/EntityTypeManager.php).`
Let's add check if the `field_message_related_object` is not empty to prevent errors.
- https://www.drupal.org/project/social/issues/3045872
N/A
_It is not entirely clear how to reproduce this problem._
N/A
N/A
N/A
N/A

Issue #3045872 by colan, Resssinel: Message related object entity type is randomly empty

---

modules/social_features/social_profile/modules/social_profile_preview/assets/js/social_profile_preview.js

Currently, there is a redirect when LU clicks on follow users button from profile preview.
It would be good to AJAXify Follow button on Profile preview the same as on normal teasers.
- https://www.drupal.org/project/social/issues/3276000
- https://getopensocial.atlassian.net/browse/YANG-7532

Issue #3276000 by SV: AJAXify Follow button on Profile preview

---

modules/social_features/social_profile/social_profile.module

The page contains input fields where personal information must be entered. The input fields such as first name and last name do not have a mechanism to automatically complete the input. This makes filling out forms easier for many users, especially those for whom text entry takes a long time, as this is done through special tools such as pointing out letters. The use of autocomplete with the correct value is mandatory, on page https://www.w3.org/TR/2018/REC-WCAG21-20180605/#input-purposes is a list of the values ​​to be used if applicable. There are more fields where the autocomplete attribute should be used, for example the field for the telephone number. In the list you can see which values ​​can be used for which fields.
Properly use the following autocomplete values on the profile …

Issue #3179171 by agami4: Add autocomplete attr to the profile edit fields

---

modules/social_features/social_core/social_core.links.menu.yml
modules/social_features/social_core/src/Plugin/Menu/HomepageConfigurationHeroBlockLink.php

If an installation doesn't have the default hero CTA block for the homepage it breaks the dashboard with an empty route exception.
Because there will always be the need for a default URL, instead of hiding the menu item, invite users to create a new CTA block and place it to the hero region at the homepage.
https://www.drupal.org/project/social/issues/3274219
N/A
A new option is available in case there is not default hero call to action block set up to the homepage. When clicking at the link, users will have the option to create a new "Hero call to action block".
This block will be available to be used at the _Block layout_ (_admin/structure/block_)part of the website, under "Hero" 
It should be configured to Anonymous user role only:
N/A
N/A

Issue #3274219 by tbsiqueira: New Dashboard throws fatal errors

---

modules/social_features/social_content_block/src/ContentBuilder.php

In custom content list I can choose between different type of content. When I choose “Events” some extra filter options become available like Event types and Date period.
However, in the sorting options I still see the standard elements.
After I create the block and I place it on the dashboard, if I edit it again I suddenly have a new sorting option available “Event date”.
The “Event date” sorting option should be available during the creation of the block once “Events” is selected as Type of content on Dashboard.
Probably some code refactoring need to implement this.
P.S. Fix can be checked on ECI: https://enterprise.getopensocial.net/
- https://www.drupal.org/project/social/issues/3281332
- https://getopensocial.atlassian.net/browse/YANG-7074
None.
None.
None.
None.

Issue #3281332 by rolki: Fix sorting options for custom content list block on dashboard when choose events

---

modules/custom/activity_logger/config/schema/activity_logger.schema.yml

Email subjects were introduced in [#3236256] and https://github.com/goalgorilla/open_social/pull/2544. The email subjects are textfield but are not available for translation. This is due to schema being <code>type: string</code> for a textfield.
Read more at: https://www.drupal.org/docs/drupal-apis/configuration-api/configuration-schemametadata#types
Change the schema of email_subject to "label".
https://www.drupal.org/project/social/issues/3282031
N.A
**Before:**
**After:**
Email subjects were introduced in Open Social 10.3 but they were not available for translations. We have now made them available for translations. Now, an admin should be able to add translations of message templates including email subjects.
N.A
N.A

Issue #3282031 by navneet0693: Email subjects in message templates are not translatable.

---

modules/custom/social_ajax_comments/social_ajax_comments.module

Contrib module ajax_comments does not support ajax comments on standalone comment reply page
or comment edit page. Because submit button ajax property is set by ajax_comments module anyway,
it has to be removed, otherwise comment in comment form is never submitted.
TL;DR: Reply button / commenting is not working on standalone comment reply page when ajax_comments module is enabled.
Someone has commented my topic. I receive a notification in the notification center or via E-Mail, click on the notification and I am directed to this page, that only shows the comment and a reply button: 
https://{domain-name}.com/comment/reply/node/{node_id}/field_topic_comments/{comment_id} 
I type in my reply but after I have pressed "reply" nothing happens and my reply is not submitted (screenshot)
When I …

Do not use ajax comments on standalone comment reply/edit page

---

modules/social_features/social_group/social_group.module

See https://github.com/goalgorilla/open_social/pull/2932
Revert changes for `social_group_views_query_alter()`
- https://www.drupal.org/project/social/issues/3279787
N/A
N/A
N/A
N/A
N/A

Issue #3279787 by colan, tbsiqueira, Ressinel: Authenticated non-member users can no longer find closed groups

---

modules/social_features/social_event/src/Form/EnrollActionForm.php

During a final rebase the logic for optionally converting a route
parameter was messed up. This caused the enroll button to never render.
This commit fixes that logic to accept having a pre-converted node
rather than a string/int ID as well.
Regression caused by https://github.com/goalgorilla/open_social/pull/2948/files#diff-76a00b0f3e321114351f9f6f10225febb389f8f0a7a5e4dbd9780bc0bfe7e499
N/a unreleased bug

Fix enroll button parameter conversion logic

---

modules/social_features/social_event/modules/social_event_an_enroll/src/Form/EventAnEnrollActionForm.php
modules/social_features/social_event/src/Form/EnrollActionForm.php
modules/social_features/social_event/src/SocialEventTrait.php
phpstan-baseline.neon

AS per https://github.com/goalgorilla/open_social/pull/792#discussion_r213029760 `EventAnEnrollActionForm` extends `EnrollActionForm` although this is probably not needed as there are more differences than overlap.
We can move the common functionality that needs to be shared into a trait that they can both use. This also makes it possible for other forms to easily reuse this logic in the future.
- https://www.drupal.org/project/social/issues/2995574
N/A
N/A
EnrollActionForm::eventHasBeenFinished() was moved into a trait SocialEventTrait.
We moved the `eventHasBeenFinished()` into the trait `SocialEventTrait`. That makes it possible for other forms to easily reuse this method by adding a trait.
`modules/social_features/social_event/src/Form/EnrollActionForm::eventHasBeenFinished()` …

Issue #2995574 by Ressinel: Move eventHasBeenFinished into a trait

---

modules/social_features/social_comment/src/SocialCommentBreadcrumbBuilder.php
phpstan-baseline.neon

```
Warning: array_flip(): Can only flip STRING and INTEGER values! in Drupal\Core\Entity\EntityStorageBase->loadMultiple() (line 261 of core/lib/Drupal/Core/Entity/EntityStorageBase.php).
Drupal\Core\Entity\EntityStorageBase->loadMultiple(Array) (Line: 245)
Drupal\Core\Entity\EntityStorageBase->load(NULL) (Line: 65)
Drupal\social_comment\SocialCommentBreadcrumbBuilder->build(Object) (Line: 83)
Drupal\Core\Breadcrumb\BreadcrumbManager->build(Object) (Line: 72)
Drupal\system\Plugin\Block\SystemBreadcrumbBlock->build() (Line: 171)
Drupal\block\BlockViewBuilder::preRender(Array)
call_user_func_array(Array, Array) (Line: 101)
Drupal\Core\Render\Renderer->doTrustedCallback(Array, Array, 'Render #pre_render callbacks must be methods of a class that implements …
```

Issue #3276411 by tarikflz, Ressinel: SocialCommentBreadcrumbBuilder causes an error loading entities

---

modules/social_features/social_group/social_group.module

Since we do not have a separate membership page, aliases are not necessary.
An unnecessary field is displayed in the Approve membership form.
Hide the field.
https://www.drupal.org/project/social/issues/3281476
https://getopensocial.atlassian.net/browse/YANG-7784
Hide the path alias field from the approve membership form.

Issue #3281476 by alex.ksis: Hide path alias field from the approve membership form.

---

modules/social_features/social_event/modules/social_event_managers/src/Form/SocialEventManagersAddEnrolleeForm.php
phpstan-baseline.neon

Social Event Organisers `social_event_managers` module requires a service from Social Event Max Enroll `social_event_max_enroll` but doesn't add it to it's dependencies.
~~Add `social_event_max_enroll` as a dependency of `social_event_managers`, and add the required hook update on `social_event_managers`.~~
Make `social_event_max_enroll` service DI optional.
https://www.drupal.org/project/social/issues/3282766
N/A
N/A
N/A
N/A
N/A

Issue #3282766 by tbsiqueira: Adding enrollees to event crashes site

---

modules/social_features/social_core/social_core.module

User still can see field labels even he doesn't have access to these fields:
Hide un-useful form fields labels if user don't have an access to these labels (for nodes)
- https://www.drupal.org/project/social/issues/3291105
- https://getopensocial.atlassian.net/browse/YANG-7716
N/A
Before:
After:
*Hide un-useful form fields labels if user don't have an access to these labels (for nodes)*
N/A
N/A

Issue #3291105 by vnech: Hide redundant form fields labels if user doesn't have an access to them

---

modules/social_features/social_tagging/social_tagging.install
modules/social_features/social_tagging/social_tagging.module
modules/social_features/social_tagging/src/Form/SocialTaggingSettingsForm.php

As a LU I want to add metadata to files
Extend social tagging module so that we could add Social Tagging terms to media.
https://www.drupal.org/project/social/issues/3283541
https://getopensocial.atlassian.net/browse/YANG-7653
Added an ability to add tags for the media entity type.

Issue #3283541 by alex.ksis: Allow to add tags to media entities.

---

modules/custom/activity_creator/js/notifications.js
modules/social_features/social_activity/social_activity.module
modules/social_features/social_swiftmail/src/Form/SocialSwiftmailSettingsForm.php
tests/behat/features/capabilities/like/like-create-event.feature
tests/behat/features/capabilities/like/like-create-topic.feature

The spelling of "Centre" should be "Center".
Replace "Centre" with "Center" throughout all the Distro.
- https://www.drupal.org/project/social/issues/3201416
N/A
N/A
The word "Centre" was replaced with "Center" throughout all the Open Social.
N/A
N/A

Issue #3201416 by hotwebmatter, DamienMcKenna, Ressinel: Spelling for "Notification Centre" should be American English

---

modules/social_features/social_profile/templates/profile--profile--name.html.twig

Before, when the module `social_profile_organization_tag` was enabled and the user had an organization tag, yellow icon showed next to the user name on the People overview page. In the latest **Open Social** version it doesn't show.
Add `profile_name_extra` variable to `/modules/social_features/social_profile/templates/profile--profile--name.html.twig`
- https://www.drupal.org/project/social/issues/3292017
N/A
Reverted back organization tag icon to the People overview page.
N/A
N/A

Issue #3292017 by Ressinel: Profile organization tag yellow icon is disappeared on People overview page

---

composer.json

Update socialblue dependency to 2.2.4 on 11.3.x
Update socialblue dependency to 2.2.4 on 11.3.x
*[Required] Paste a link to the drupal.org issue queue item. If any other issue trackers were used, include links to those too.*
https://www.drupal.org/project/social/issues/3291633
N/A
N/A
N/A
N/A

Issue #3291633: Update socialblue dependency to 2.2.4 on 11.3.x

---

modules/social_features/social_event/src/Form/EnrollActionForm.php

Show enroll button on multi-group event if user is member of at least one group
Previous / deprecated PR: [2941](https://github.com/goalgorilla/open_social/pull/2941)
Users are not able to join the multi-group event if they are not members of both groups, which is unexpected behaviour.
Changing the conceptual permission logic from "and" (user must be member of all groups) to "or" (user must be member of at least one group) fixes that issue.
Situation:
- **Event 1**:
- Group: “Group A” and “Group B”
- Visibility: Members,
- Registration method: Open registration
- Unchecked: Allow Logins or Enrollments from Non-Group Members)
- **Group A**:
- Members: 
- User A
- User C
- **Group B**:
- Members:
- User B
- User C
- **User D**:
- Not member of Group A and Group B
Facts:  
- User A can not …

Issue #3281618 by zanvidmar: Show enroll button on multi-group event if user is member of at least one group

---

modules/social_features/social_embed/src/Plugin/Filter/SocialEmbedUrlEmbedFilter.php

Referring to https://www.drupal.org/project/url_embed/issues/3199301.
There is a possibility to experience this exception from YouTube APIs on high-traffic websites. This exception is being thrown from https://github.com/oscarotero/Embed/blob/v3.4.16/src/Embed.php#L142
The above library is the requirement of https://www.drupal.org/project/embed which is required by https://www.drupal.org/project/url_embed.
See: https://www.rfc-editor.org/rfc/rfc6585#page-3
See: https://developers.google.com/youtube/v3/docs/core_errors?hl=en#TOO_MANY_REQUESTS
Gracefully handle the exception.
https://www.drupal.org/project/social/issues/3293388
N.A
This is quite difficult to reproduce on local as this happens on high traffic websites.
N.A
There was a possibility of an exception/error on content pages with …

Issue #3293388 by navneet0693: Status Code 429 on YouTube urls on a content page

---

modules/social_features/social_profile/social_profile.module

We got a fatal error when displaying profile with empty field_profile_image field.
```php
Error: Call to a member function set() on null in social_profile_profile_view_alter() (line 677 of profiles/contrib/social/modules/social_features/social_profile/social_profile.module).
social_profile_profile_view_alter(Array, Object, Object) (Line: 539)
Drupal\Core\Extension\ModuleHandler->alter('profile_view', Array, Object, Object) (Line: 316)
Drupal\Core\Entity\EntityViewBuilder->buildMultiple(Array) (Line: 250)
Drupal\Core\Entity\EntityViewBuilder->build(Array)
call_user_func_array(Array, Array) (Line: 100)
Drupal\Core\Render\Renderer->doTrustedCallback(Array, Array, 'Render #pre_render callbacks must be methods of a class that …
```

Issue #3271758 by vnech: Fix fatal error on "social_profile_profile_view_alter()" function

---

modules/social_features/social_group/social_group.module

"Url alias" and "Revisions" form fields are placed out of the field groups:
- Hide "Advanced" vertical tab fieldset
- Hide "Revisions" form field
- https://www.drupal.org/project/social/issues/3291092
- https://getopensocial.atlassian.net/browse/YANG-7715
N/A
Before:
After:
*Hide revisions form fields on group create/edit pages.*
N/A
N/A

Issue #3291092 by vnech: Hide revisions form field on group create & edit pages

---

modules/custom/group_core_comments/src/Plugin/Field/FieldFormatter/CommentGroupContentFormatter.php
modules/social_features/social_post/src/Plugin/Field/FieldFormatter/CommentPostFormatter.php

If a user is not logged in and is on a topic/event/discussion page and wants to leave a comment or enroll, they are required to log in first. And as they log in they are redirected to a homepage and not the content page where they wanted to perform an action.
After logging in a user is redirected to the same page from which log in was performed.
- https://www.drupal.org/project/social/issues/3282392
- https://getopensocial.atlassian.net/browse/YANG-7769
None.
None.
Now, after logging user is redirected to the same page from which log in was performed to comment. This change also works properly with "Alternative front page".
None.

As an AN commenting on a content I should be redirected to the same content after I login

---

modules/social_features/social_activity/social_activity.module
modules/social_features/social_core/social_core.module
modules/social_features/social_event/social_event.module
modules/social_features/social_group/social_group.module
modules/social_features/social_profile/social_profile.module
modules/social_features/social_topic/social_topic.module

PR for 11.1.x https://github.com/goalgorilla/open_social/pull/3022
When we use code like $link = end($link); the function end() can return FALSE for empty array. And when we try to retrieve link title we have FALSE instead of link instance.
`Error: Call to a member function getTitle() on bool in social_core_entity_access() (line 1239 of profiles/contrib/social/modules/social_features/social_core/social_core.module).`
Add defensive checks.
- https://www.drupal.org/project/social/issues/3275980
N/A
N/A
N/A
N/A
N/A

Issue #3275980 by Ressinel: Add defensive checks to fix error when we try to retrieve a link title

---

modules/social_features/social_album/social_album.install
modules/social_features/social_core/social_core.module
phpstan-baseline.neon

The Social Album has helper functions which install blocks on specified pages. The functions are: `_social_album_blocks()` and `_social_album_install_blocks()`. They both are in the `social_album.install`
These functions might be useful for other modules as well.
Move helper functions from Social Album to the Social Core module.
https://www.drupal.org/project/social/issues/3284938
https://getopensocial.atlassian.net/browse/YANG-7827
Move helper functions from album module to core.
(in draft) https://www.drupal.org/node/3291491

Issue #3284938 by alex.ksis: Move helper functions from album module to core

---

modules/social_features/social_group/src/Plugin/views/argument/UserUid.php

In the `Drupal\social_group\Plugin\views\argument\UserUid` views argument plugin, `groups_field_data.id` is used. If `groups_field_data` is replaced by `$this->tableAlias`, the argument can also be used in views that do not start from groups. And the existing views that use the argument keep working.
Use `$this->tableAlias` instead of hardcoded table name.
- https://www.drupal.org/project/social/issues/3106344
N/A
N/A
N/A
N/A
N/A

Issue #3106344 by alduya: Use $this->tableAlias instead of hardcoded table name

---

modules/social_features/social_user/src/ContextProvider/UserRouteContext.php

Profile hero block disappears when saved.
Revert context id as it was before to fix an issue where the profile hero block disappears after saving.
- https://www.drupal.org/project/social/issues/3211735
N/A
N/A
N/A
N/A

Issue #3211735 by SocialNicheGuru, Ressinel: Profile Image Header disappears when saved

---

modules/social_features/social_core/config/optional/block.block.socialblue_pagetitleblock_content.yml
modules/social_features/social_core/config/update/social_core_update_11402.yml
modules/social_features/social_core/social_core.install
modules/social_features/social_core/social_core.module

Related PR https://github.com/goalgorilla/open_social/pull/1960
There is an issue of duplicate Hero Blocks when the URL has one of the words `add`, `edit`, or `delete`.
Correct visibility settings for socialblue_pagetitleblock_content block.
- https://www.drupal.org/project/social/issues/3144794
N/A
It is reproducible only in some environments but not on vanilla Open Social.
N/A
N/A
N/A

Issue #3144794: Hero block display based on path is too fragile

---

modules/social_features/social_comment/src/SocialCommentViewBuilder.php

If we are on any page of comments pager except the first one, instead of the word "first" we see "comments".
Add tag in `SocialCommentViewBuilder::buildMultiple()` only if the module `social_ajax_comments` is enabled.
- https://www.drupal.org/project/social/issues/3296055
N/A
Correct the comments pager button text.
N/A
N/A

Issue #3296055: In a comments' pager shows the word "comments" instead of "first"

---

modules/custom/activity_basics/src/Plugin/ActivityContext/ContentInMyGroupActivityContext.php
modules/social_features/social_content_report/social_content_report.tokens.inc

**Problem 1**
This was a special case scenario where a queue was created by activity_creator_logger . It was trying to send notifications/emails to all the members.
`Error: Call to a member function id() on null in Drupal\activity_basics\Plugin\ActivityContext\ContentInMyGroupActivityContext->getRecipients() (line 160 of html/profiles/contrib/social/modules/custom/activity_basics/src/Plugin/ActivityContext/ContentInMyGroupActivityContext.php) #0 html/profiles/contrib/social/modules/custom/activity_creator/src/Plugin/QueueWorker/ActivityWorkerLogger.php(48): Drupal\activity_basics\Plugin\ActivityContext\ContentInMyGroupActivityContext->getRecipients(Array, 0, 0)`
While processing all the memberships at https://github.com/goalgorilla/open_social/blob/11.1.13/modules/custom/activity_basics/sr …

Issue #3295894 by navneet0693: Junk data crashes queues.

---

modules/social_features/social_event/modules/social_event_addtocal/src/Plugin/SocialAddToCalendarBase.php

Whenever a user adds an event to his / her / their calendar, there is no trace of the event anymore in the personal calendar.
Add a link to the event in the calendar description.
https://www.drupal.org/project/social/issues/3293556
* We've added a link to the event in Open Social to the description when adding an event to a personal calendar.

Issue #3293556 by sjoerdvandervis: Add link to calendar description

---

modules/social_features/social_search/src/EventSubscriber/RedirectSubscriber.php

When the exposed filter Profile datasource: Owner » User » Created (exposed) is removed from the search/users view, the exposed filters are not submittable.
This is a bug introduced by this fix [#3085806: Pagination does not work anymore on Search Users page: "An illegal choice has been detected."](https://www.drupal.org/project/social/issues/3085806) which aims to solve another bug.
The fix assumes that the exposed filter "created" will always be present which is not always the case if the search view is customized.
It can be fixed by merging the `$query` param with the `['created_op' => '<']`;
- https://www.drupal.org/project/social/issues/3278207
N/A
N/A
Was fixed user search page filters in case the view was customized and the exposed filter "created" is not present.
N/A
N/A

Issue #3278207 by msti: Search users page exposed filters not working

---

composer.json

Core released:
https://www.drupal.org/sa-core-2022-012
https://www.drupal.org/sa-core-2022-013
https://www.drupal.org/sa-core-2022-014
https://www.drupal.org/sa-core-2022-015
But since we still support versions 9.2.x in Open Social we need to backport this.
Backport issues as patch, I'm trying directly to see if this applies to our 11.3.x branch.
https://drupal.org/node/3298688
See that all our tests pass.

Patch Drupal 9.2.x with backported fixes for drupal core SA-CORE-2022

---

composer.json

The patch for:
```
"Empty language (langcode) field wrapper inserted into contact form": "https://www.drupal.org/files/issues/2022-01-29/empty-langcode-field-wrapper-2842405-23.patch"
```
Created regression as we are revoking access, while all we want is to remove it from the render process in certain occassions.
This is a 2 step solution.
1. Remove the patch.
2. Find a way to fix the use case we were trying to fix.
This PR is to fix number 1, so we don't cause regression and have this waiting for too long.
Also good to note is that the patch was already removed as part of #3045 in the 11.3.x, 11.2.x, 11.1.x branches.
https://www.drupal.org/project/social/issues/3298713
This doesn't need a HTT, step 2 does when we fix it. 
See: https://www.drupal.org/project/drupal/issues/2842405#comment-1 …

Issue #3298713: Remove patch for empty langcode so we dont create regression

---

modules/social_features/social_core/social_core.module

Sometimes "Comments Settings" field is placed out of the "Settings" group field on entity create page.
Hardcode comments field in "settings" field group.
- https://www.drupal.org/project/social/issues/3284885
- https://getopensocial.atlassian.net/browse/YANG-7700
N/A
N/A
*Fix comments field place in entity form creation page.*
N/A
N/A

Issue #3284885 by vnech: Fix comments field place in entity form creation page

---

modules/social_features/social_tagging/social_tagging.install
modules/social_features/social_tagging/src/SocialTaggingOverrides.php

When updating OS from 11.3 to 11.4, there is a new update hook appeared in the views module. This hook collects all the changes from the override services like SocialTaggingOverrides and adds them directly to the config. After that override services might not work correctly and as a result unnecessary filters are displayed in the newest members block.
The SocialTaggingOverrides service adds filters by tags to all displays of the Newest members view. In this PR we are forcing all displays to have own filters instead of inheriting the default display. It will allow to override filters of a certain display in the SocialTaggingOverrides.
https://getopensocial.atlassian.net/browse/PROD-20227
https://www.drupal.org/project/social/issues/3294502
Force all displays of the Newest members view to …

Issue #3294502 by alex.ksis: Override a certain display instead of the whole view.

---

modules/social_features/social_group/src/EventSubscriber/RedirectSubscriber.php

There are two pages with membership requests. One is provided by the `grequest` module, another one is provided by the `social_group` module.
There are two pages with membership requests. One of them is not correct and has broken "Approve" and "Reject" links.
Create a redirect to the correct page.
https://getopensocial.atlassian.net/browse/YANG-8012
https://www.drupal.org/project/social/issues/3291402
Added redirect from the "Membership requests" page provided by the grequest module to the page provided by the social group module.

Issue #3291402 by alex.ksis: Add redirect to the correct membership requests page.

---

modules/social_features/social_core/social_core.services.yml
modules/social_features/social_core/src/Service/MachineName.php
modules/social_features/social_tagging/social_tagging.module
phpstan-baseline.neon

On a multilingual website of Open Social installed with English as the base language, if a content manager or site manager adds/edits content where tags (Social Tagging feature) are enabled then the translated tag categories don't appear on the page.
The code https://github.com/goalgorilla/open_social/blob/11.4.0/modules/social_features/social_tagging/social_tagging.module#L237  tries to convert the names of “Taxonomy” in a machine name.
So, the function https://github.com/goalgorilla/open_social/blob/11.4.x/modules/social_features/social_tagging/social_tagging.module#L587 doesn’t considers the “non-english” language to be present in the given text which then fails.
Our goal was to make the improvements in the logic of converting the terms/given strings to machine_name irrespective of …

Issue #3306207 by navneet0693, robertragas, ronaldtebrake: Tag categories do not appear on add/edit page on multilingual websites

---

.github/workflows/translations.yml

We currently run nightly translation extraction. This means there's a large feedback loop for new code added and translations being available in our translation tool.
This implements translation extraction as a GitHub action, similar to what we've done internally. We re-use an internal tool using our private packagist subrepository created to provide access to tools only.
The GitHub action creates a pull request against the `main` branch for any new translations added whenever new code is pushed to that branch.
The labels `translated` and `automated` have been created and are added to any PR opened by the workflow so they can easily be identified or targetted by other processes (e.g. Mergeable could ignore PRs with the `automated` tag)

Internal: Implement GitHub Action translation extraction

---

modules/social_features/social_core/social_core.services.yml
modules/social_features/social_core/src/Service/MachineName.php
modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/social_follow_landing_page.module
modules/social_features/social_follow_taxonomy/modules/social_follow_tag/src/SocialFollowTagLazyBuilder.php
modules/social_features/social_tagging/social_tagging.module
modules/social_features/social_tagging/src/SocialTaggingOverrides.php
modules/social_features/social_tagging/src/SocialTaggingService.php
phpstan-baseline.neon

On a multilingual website of Open Social installed with English as the base language, if a content manager or site manager adds/edits content where tags (Social Tagging feature) are enabled then the translated tag categories don't appear on the page.
The code https://github.com/goalgorilla/open_social/blob/11.4.0/modules/social_features/social_tagging/social_tagging.module#L237  tries to convert the names of “Taxonomy” in a machine name.
So, the function https://github.com/goalgorilla/open_social/blob/11.4.x/modules/social_features/social_tagging/social_tagging.module#L587 doesn’t considers the “non-english” language to be present in the given text which then fails.
On a multilingual website of Open Social installed with English as the base language, if a content manager or site manager …

Issue #3306207 by navneet0693, robertragas, ronaldtebrake: Tag categries do not appear on add/edit page on multilingual websites.

---

modules/social_features/social_group/modules/social_group_invite/social_group_invite.module

Because of the app's architecture the group invitation urls are not working. By removing the destination logic and using the url directly and let Drupal handle the login logic, this will work for both app and desktop.
When sending group invitation mails, we include the accept url for the invite. We are sending the user to /user/login page with the accept url as a destination. However, this interferes with the app.
When you are invited to a private group, you get a mail, which contains a link to the new group. If you click on the link, you accept the invite. The link is going to /user/login with the accept url as a destination (https://example.com/user/login?destination=/social-group-invite/{group_id}/accept).
This doesn't work on the app, because all user/login url's are forced to open in …

Issue #3305677: Remove destination in group invites url

---

composer.json

Socialblue has a new version 2.3.2 and we should update it on Open Social
Update socialblue to 2.3.2
https://www.drupal.org/project/social/issues/3311064
N/A
N/A
N/A
N/A
N/A

Issue #3311064: Update socialblue to 2.3.2

---

modules/social_features/social_album/social_album.install

When viewing a public group, anonymous users don't see the album link, although the module is enabled.
By adding the right permissions to the anonymous users for flexible groups, anonymous users are able to see both the Albums link and Albums page.
https://www.drupal.org/project/social/issues/3309222#comment-14689753
Please be aware that this change has permission changes. This is going to change the way users are able to view albums.
AN users will be able to view any public album you create
LU users will be able to view any public and community album you create.

Issue #3309222: Assign the right permissions for social_album

---

tests/behat/behat.yml
tests/behat/features/capabilities/administration/flood-edit.feature

Since we've added a `Configuration` item in the site manager menu, if the test starts before the admin menu has collapsed then Behat may press the wrong "Configuration" item. Since we don't want to test the menu structure of Drupal, it's safe to go to the path directly to ensure this functionality works.
Internal no ticket

Internal: Make flood-edit test deterministic

---

modules/social_features/social_core/social_core.permissions.yml

This change was split out from https://github.com/goalgorilla/open_social/pull/2478
In some cases we want to expose a bit more information to developers so that they can quickly diagnose issues. Information that may not be understandable to site managers (such as raw field names).
To provide a unified solution for this that does not rely on the developer user having uid 1 we introduce a new permission. This is placed in social_core so that we can use it in all modules building on top of this.
https://www.drupal.org/project/social/issues/3308580
`social_core` introduces the `view debug` permission which allows modules building on top of `social_core` to hide developer only information.

Issue #3308580: Add `view debug` permission to social_core

---

modules/custom/social_graphql/src/Plugin/GraphQL/DataProducer/Field/Field.php
modules/social_features/social_profile/src/Plugin/GraphQL/DataProducer/DefaultProfileLoad.php

This was split out from https://github.com/goalgorilla/open_social/pull/2478
The producer returned a field item for empty fields which could cause
non-nullable sub-fields to return NULL instead (e.g. for a formatted
text field). Returning NULL for an empty field ensures that we don't try
to access sub-fields.
Our profile field isn't allowed to return NULL because all users should
have a profile (and profiles aren't accessible as standalone data) so if
a user is not allowed to view profile data then we just fake this by
returning an empty profile instead. The profile fields are already
nullable because users can choose visibility on a per-field basis.
Change the relevant dataproducers.
https://www.drupal.org/project/social/issues/3308535
The GraphQL response for profiles violated the …

Issue #3308535: GraphQL API returns types for profile that violate schema

---

tests/behat/features/bootstrap/TopicContext.php
tests/behat/features/capabilities/contentmanagement/unpublished.feature
tests/behat/features/capabilities/sharing/share.feature

The share test had to be disabled because it wasn't working in all cases, this was caused by the share module not being enabled in the test (which only made it work when all optional modules were enabled).
We enable the module at the start of the test. Additionally while working on the test we break the different assertions into multiple scenarios. Each scenario only tests a specific business rule to ensure that if a scenario fails we know what's broken without further debugging.
Internal change, no issue.

Internal: Re-enable and optimise share topic test

---

modules/social_features/social_core/config/install/user.role.verified.yml
modules/social_features/social_core/social_core.install

This change was split out from https://github.com/goalgorilla/open_social/pull/2478
This ensures that the verified user role shows up before the content manager and site manager roles in settings forms. This is sensible because usually the verified user role will be less permissioned. This follows other patterns in Drupal of presenting lower permissions roles first.
https://www.drupal.org/project/social/issues/3308584
Ensured the verified user role is now shown before higher permissioned roles such as content manager and site manager.

Issue #330884: Verified user role weight should be lower than content manager

---

composer.json

Open Social is applying the following patch to ajax_comments: [https://www.drupal.org/files/issues/2021-03-19/ajax_comments-ajax_not_wo...](https://www.drupal.org/files/issues/2021-03-19/ajax_comments-ajax_not_working_when_using_non_default_view_mode-2896916-beta3.patch) unfortunately this patch is breaking caching for anonymous users.
https://www.drupal.org/project/ajax_comments/issues/2896916#comment-14508870
Re-roll the patch and add a new condition to the altered function to check if current user has post message permissions
```
if (!\Drupal::currentUser()->hasPermission('post comments')) {
return;
}
```
https://www.drupal.org/project/social/issues/3311816
N/A
N/A
Previous patch was not considering if user had permission to post comments on a page, this was breaking cache for …

Issue #3311816 by tbsiqueira: Caching issues with ajax_comments module

---

modules/social_features/social_album/config/optional/block.block.socialblue_album_count_and_add.yml
modules/social_features/social_album/social_album.post_update.php
modules/social_features/social_book/config/optional/block.block.booknavigation.yml
modules/social_features/social_book/config/optional/block.block.booknavigation_2.yml
modules/social_features/social_book/social_book.post_update.php
modules/social_features/social_core/config/optional/block.block.socialbase_pagetitleblock.yml
modules/social_features/social_core/config/optional/block.block.socialblue_pagetitleblock.yml
modules/social_features/social_core/social_core.post_update.php
modules/social_features/social_event/config/optional/block.block.socialblue_views_block__event_enrollments_event_enrollments_socialbase.yml
modules/social_features/social_event/config/optional/block.block.views_block__event_enrollments_event_enrollments_socialbase.yml
modules/social_features/social_event/modules/social_event_managers/config/optional/block.block.views_block__managers_event_managers.yml
modules/social_features/social_event/modules/social_event_managers/config/optional/block.block.views_block__managers_event_managers_2.yml
modules/social_features/social_event/modules/social_event_managers/social_event_managers.post_update.php
modules/social_features/social_event/social_event.post_update.php
modules/social_features/social_sharing/config/optional/block.block.shariffsharebuttons.yml
modules/social_features/social_sharing/config/optional/block.block.shariffsharebuttons_2.yml
modules/social_features/social_sharing/social_sharing.post_update.php

As per change record https://www.drupal.org/node/2983299 node_type plugin condition is now deprecated and replaced by a generic entity_bundle condition.
Open Social has a couple of default blocks still using the deprecated condition and needs update.
Follow the same code on block_post_update_replace_node_type_condition and update Open Social block configuration on optional and default blocks.
https://www.drupal.org/project/social/issues/3313663
N/A
N/A
N/A
N/A
N/A

Issue #3313663: Deprecated plugin filter node_type for Open Social default blocks

---

modules/social_features/social_content_block/src/ContentBuilder.php

After processing of all plugins in `social_content_block/ContentBuilder`, we have an array of entities, after which we sort them and limit the number of results using `$query->range(0, $block_content->field_item_amount->value);` 
The problem is that after limiting, we load the objects entities and check whether the user has access to them, this is not correct as the selection is already limited to, for example, 5 items, but the user has access to only 2, in this case, even though 5 is selected in the block settings, only 2 will be displayed.
Another problem is that some sites, to solve the problem above, simply remove this range and add `array_slice` after the objects are loaded and checked for access - and this is even worse since `5000+` (depends on platform) entities can be loaded and …

Issue #3308363 by rolki: Improve access checking and fix possible performance issue for custom content list block

---

modules/social_features/social_group/modules/social_group_flexible_group/config/update/social_group_flexible_group_update_11402.yml
modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install

In https://www.drupal.org/project/social/issues/3254715 we have tried to make our allowed join group method field re-usable, instead of providing storage options, we opted for a callback. Super helpful if people wanted to extend it.
However the actual update hook implied, expected configuration to be there. Which in our case wasn't always the case due to the field storage already being updated and altered with more configuration.
The exact scenario why we want to have a callback for the allowed values.
I've recreated the update hook, made sure there is no expected config so it runs always.
We can point to the actual release notes of the issue there is no additional value created.
I have tried to put it in a test case, but because of the way we have set our dependencies I have to enable …

Issue #3316310 - Recreate update hook for updating field group allowed join methods as it failed on expected config

---

modules/social_features/social_content_report/social_content_report.tokens.inc

When content is flagged and the content item is deleted before the activity is created, the cron fails, because the entity cannot be loaded anymore.
By adding a check to see if the flagging still exists, we prevent the cron from failing.
https://www.drupal.org/project/social/issues/3315916

Hotfix: Check if flagging exists before loading the entity

---

modules/social_features/social_event/social_event.module

When you click on the "See who else is going" link after enrolling in an event, you are forced to view the result in a new tab.
The pop-up with the link (nice improvement!) was introduced in #2830.
This is not a great interaction and it will leave a "zombie" tab behind.
Remove `target=blank`.
- https://www.drupal.org/project/social/issues/3317257
- https://getopensocial.atlassian.net/browse/PROD-22910
N/a
N/a
After enrolling to an event a pop-up is opened. The link to view who else is also attending the event now opens in the same window instead of opening a new one.
N/a
N/a

Issue #3317257: Change the 'Who else is going' target from blank to same window

---

.github/dependabot.yml

There are a lot of pending module updates and currently dependabot only query five PRs at a time, besides that there is also an outdated configuration with dependabot labels.
- Increate the amount of max open PRs from 5 to 10;
- Update outdated labels, change `team: nucleus` to `team: guardians`;
- Add a new `status: needs review` label;
N/A
N/A
N/A
N/A
N/A
N/A

Internal: Update dependabot labels and max amount of open PRs configuration

---

modules/custom/entity_access_by_field/tests/src/Unit/EntityAccessTest.php

PHPUnit deprecated prophecy integration on https://github.com/sebastianbergmann/phpunit/issues/4141 
There a couple of approaches, all suggested on the above PR:
- Use [prophecy](https://github.com/phpspec/prophecy) directly, suggested here https://github.com/sebastianbergmann/phpunit/issues/4141#issuecomment-601240143
- Use a rector suggested here https://github.com/sebastianbergmann/phpunit/issues/4141#issuecomment-628531052
Whatever the method, unit tests should still work.
N/A
N/A
N/A
N/A
N/A
N/A

Internal: Fix PHPUnit deprecated prophecy integration

---

composer.json

After
https://github.com/goalgorilla/open_social/pull/3177
https://github.com/goalgorilla/open_social/pull/3176
A couple of patches aren't applying anymore, this is happening because they are already included on those modules newer versions:
Entity: https://www.drupal.org/project/entity/issues/3217876#comment-14457281
Crop: https://www.drupal.org/project/crop/issues/3248169#comment-14768170
Remove deprecated patches
https://www.drupal.org/project/social/issues/3318338
N/A
N/A
N/A
N/A
N/A

Issue #3318338: Patches for crop / entity are not applying after update

---

composer.json

At the new version drupal/advancedqueue is already including a fix that was previously added as a patch to Open Social.
The original patch was applied to the new module version, and can be removed, for more information please check the original issue on drupal.org
https://www.drupal.org/project/advancedqueue/issues/3248140
N/A
N/A
N/A
N/A
N/A
N/A

Internal: Remove deprecated patch for drupal/advancedqueue

---

composer.json

Ctools patch doesn't apply after https://github.com/goalgorilla/open_social/pull/3194
Remove patch.
N.A
N.A
N.A
N.A
N.A
N.A

Internal: Updated patch on ctools from https://www.drupal.org/project/ctools/issues/3191286.

---

modules/social_features/social_mentions/social_mentions.module
modules/social_features/social_mentions/social_mentions.services.yml
modules/social_features/social_mentions/src/SocialMentionsHelper.php
modules/social_features/social_mentions/src/SocialMentionsHelperInterface.php

It is good to have a helper service to be possible to use mentions functions where needed.
There is not possible to reuse some mentions functionality. E.g. get prefix and suffix.
Add a helper service with appropriate methods.
- https://www.drupal.org/project/social/issues/3307272
N/A
N/A
Social mentions now offers a new service `social_mentions.helper` this helper service allows developers to:
- Get the mentions prefix and suffix using function `getMentionsPrefixSuffix()`;
- Gets the mentions pattern using function `getMentionsPattern()`;
- Get the mentions from text using function `getMentions(string $text)`;
N/A
N/A

Issue #3307272: Create helper service for Social Mentions module

---

composer.json

Open Social introduced a new image effect, "convert to webp". This effect is not working as intended when images are uploaded to a private file system.
The new effect was introduced here: https://github.com/goalgorilla/open_social/pull/3085
Follow proposed solution on https://www.drupal.org/project/drupal/issues/2786735 and apply patch #39
https://www.drupal.org/project/social/issues/3322194
N/A
Before:
After:
HTML:
N/A
N/A
N/A

Issue #3322194: Image style that uses convert and private file system is not working

---

modules/social_features/social_search/social_search.module

The Date of Event filter on the Search > Content page is not working correctly.
Social search depends on better_exposed_filters. In the 6.0.x version of better_exposed_filters an extra container has been added ([code](https://git.drupalcode.org/project/better_exposed_filters/-/blob/6.0.x/src/Plugin/better_exposed_filters/filter/FilterWidgetBase.php#L253)) and this breaks the process logic how to make changes for the filter block on the content search page.
Update social_search_alter_content_exposed_filter_block() code take into account an extra container added by better_exposed_filters.
[3322858](https://www.drupal.org/project/social/issues/3322858)
N/A
Steps to reproduce
fix ![](https://www.drupal.org/files/issues/2022-11-21/fix.png)
N/A
Update …

Issue #3322858 by zanvidmar: Broken date filter on search

---

.github/workflows/translations.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

Internal: GitHub Workflows security hardening

---

social.install

As a CM+ I see not needed div element class="gin-secondary-toolbar gin-secondary-toolbar--frontend" behind the navbar on every page.
Disable secondary toolbar on frontend in Gin theme.
[3323562](https://www.drupal.org/project/social/issues/3323562)
N/A
*Install scenario*
*Update scenario*
Disable secondary toolbar on frontend in Gin theme by default.
N/A
N/A

Issue #3323562 by zanvidmar: Disable secondary toolbar on frontend in Gin theme by default

---

tests/behat/features/bootstrap/FeatureContext.php
tests/behat/features/bootstrap/GroupContext.php
tests/behat/features/bootstrap/SocialMinkContext.php
tests/behat/features/capabilities/groups/groups-edit-type.feature

This test was failing randomly in some of our automated testing with an unclear reason.
The rewrite aims to have the same coverage but uses some of our new testing primitives introduced in the flexible groups rewrite to make the test more compact and readable. We also add a new assertion to properly expand the settings tab that contains the group type settings field which should ensure the test no longer fails randomly.
Some future optimizations remain and I'm not entirely happy with the fact we have multiple assertions in a single test, but I couldn't figure out how to achieve the same coverage in separate tests.
Internal test change no issue

Internal: Rewrite the group edit group type test

---

.github/dependabot.yml

We've made improvements to the stability of our tests which should make it a lot easier to review whether a dependabot PR can be merged quickly or requires a larger amount of work.
We increase the number of dependabot PRs that are allowed to be open so it's easier to see which module updates we can easily perform.
Internal issue no change

Internal: Increase dependabot open PR limit

---

tests/behat/behat.yml
tests/behat/features/bootstrap/Chrome/ChromeDriver.php
tests/behat/features/bootstrap/Chrome/ChromeExtension.php
tests/behat/features/bootstrap/Chrome/ChromeFactory.php

We've had flaky tests in our test suite for a long time but never quite knew why.
A current working theory is that it might be caused by a race condition between our usage of CKEditor and the way the Behat ChromeDriver (and potentially other Behat drivers) click on elements.
To make sure page rendering is not blocked the CKEditor will wait with loading itself until the page is ready. Similarly when visiting a page the Behat ChromeDriver will wait with further test steps until a page is loaded. This means that CKEditor starts its initialization at the same time that test steps after visiting a page are resumed.
The ChromeDriver click implementation is performed by sending instructions to the browser to move the mouse to a specific location and then sending a mouse down event. This method …

Internal: Modify ChromeDriver to fix CKEditor race condition

---

modules/social_features/social_album/config/install/views.view.albums.yml
modules/social_features/social_album/config/update/social_album_update_11470.yml
modules/social_features/social_album/social_album.install
modules/social_features/social_album/social_album.module
modules/social_features/social_album/src/Controller/SocialAlbumController.php
modules/social_features/social_album/src/Plugin/Field/FieldWidget/SocialAlbumOptionsSelectWidget.php
phpstan-baseline.neon

Images disappear in an album after editing. On the Edit form, there is no default value in "Add image(s) to an album" so after saving the value is lost so the entity lost its album.
On the edit form except for "none" and "Create new album" keep the default value for "Add image(s) to an album" field.
Update permissions so managers roles can edit and add posts to any albums.
- https://www.drupal.org/project/social/issues/3321091
- https://getopensocial.atlassian.net/browse/PROD-22975
NONE.
The field "Add image(s) to an album" on a "Post" page is updated to keep the default values on the edit form.
Tags invalidation for the Albums is updated.
NONE.
NONE.

Issue #3321091  by kashandarash: Update Post form to keep album relation on edit

---

.github/workflows/behat.yml
tests/composer.json

We want to do upgrade path testing in #3138 but that has some other problems that are related to Open Social 10. This draft PR exists to show that https://github.com/goalgorilla/open_social_dev/pull/44 is otherwise fine and the removal of `drupal/core-dev` has no adverse effects on the Open Social test suite.
When this is green then the open_social_dev PR can be merged and tagged as stable version which allows this repository to use tagged versions rather than `dev-main`.

Internal: Make Open Social Dev compatible with 10.x

---

modules/social_features/social_event/modules/social_event_managers/social_event_managers.module
modules/social_features/social_event/social_event.api.php
modules/social_features/social_event/social_event.module

I want to create a subpage on /node/{id)/page , that renders a form. As part of the requirements, this page should include all menu local tasks that are currently present on /node/{id} page.
Currently, there is no way to show links like 'Enrollments', 'Manage enrollments', 'Organisers'. The reason for this is because we programmatically remove this menu links via hook_menu_local_tasks_alter() for all pages except certain ones, which are hard coded inside an array.
We need to provide a way to alter this hard coded list of routes where this special event menu local tasks are shown. The most straightforward way is to create a new hook, where user will be able to alter this array. 
https://www.drupal.org/project/social/issues/3281598
*[Required if applicable] Paste a link to the drupal.org …

Issue #3281598 by nkoporec: Unable to show event default menu local tasks on a custom subpage

---

modules/social_features/social_content_block/modules/social_event_content_block/config/install/field.storage.block_content.field_event_date.yml
modules/social_features/social_content_block/modules/social_event_content_block/social_event_content_block.install
modules/social_features/social_content_block/modules/social_event_content_block/src/Plugin/ContentBlock/EventContentBlock.php

When an event is “ongoing” meaning that we are within the date range it should not disappear from a custom content list showing upcoming events until that event has ended.
The suggestion here is to create a new Date period option called "`Future and ongoing`" when “`Events`” are selected as the content type.
We already have “`Future`” and we already have “`Ongoing`” so it will be a combination of the two.
- https://www.drupal.org/project/social/issues/3318902
- https://getopensocial.atlassian.net/browse/PROD-22336
NONE.
*Future and ongoing*
Now we have an additional filter for events in the "Custom content list block" which is "Future and ongoing" and can be selected in the "Date period field".
NONE.
NONE.

Issue #3318902 by rolki: Add a new filtering option by "Future and ongoing" to Custom content list block

---

modules/social_features/social_profile/modules/social_profile_organization_tag/social_profile_organization_tag.module

On multilingual website the organization tags on the profile stream page are displayed in the default language instead of current language. The yellow marker contains the tag name in language which doesn't matches the current language or user's preferred language.
**Steps to reproduce**
1. Install Open Social
2. Enable social content language module and configure more than one languages.
3. Enable social profile organization tags module
4. Add profile tags and also add translations for them
5. Edit a profile and add the organization tag to it
6. Visit the profile.
7. Regardless of the current language selected, the yellow marker tooltip will show the organization tag in default language only.
Add conditions to check if the website is multilingual and then fetch the correct translation of …

Issue #3329802 by navneet0693: Organization tags display doesn't respect current language

---

composer.json

The library `npm-asset/highlight.js` is not used by Open Social but it is mentioned as requirement in composer.json
Remove the redundant library.
N.A
N.A
N.A
N.A
N.A
N.A

Internal: Remove redundant highlight dependency

---

modules/custom/social_graphql/social_graphql.info.yml
modules/custom/social_graphql/src/Plugin/GraphQL/Schema/OpenSocialBaseSchema.php
modules/custom/social_graphql/tests/src/Kernel/SocialGraphQLTestBase.php

We add a new dependency graphql_oauth:graphql_oauth but with a few flaws
- No update hook, so /graphql will now break because the plugin is missing
- Enabling the plugin will break as it enables simple_oauth without configuration, so no private keys etc. and this gives an error message with native app as that one relies on oauth2_server
Revert the change to we can properly implement it on a later stage.
https://www.drupal.org/project/social/issues/3174548#comment-14772998
Reverted a change where graphql_oauth dependency was added incorrectly, and adds new settings that are not being configured correctly without manual steps.
We reverted the graphql_oauth dependency from our code until it gets fixed properly. However this means that whoever had simple_oauth enables because of this needs to …

Issue #3174548 - revert - Disable the reliance on graphql_oauth as it breaks current implementations

---

modules/social_features/social_follow_taxonomy/modules/social_follow_tag/social_follow_tag.module

When the social_follow_tag and social_follow_taxonomy modules are enabled, it should show a popup when you click on a tag that is used in a topic/node. I enabled both of the modules but when I click on the tag, nothing happens, the page simply reloads.
The problem is that social_follow_tag overrides the default template of social_tagging via the hook_theme, and there is no dependency on social_tagging, so it could happen that the module weight is set before the social_tagging one, this causes the hook_theme is executed before social_tagging, so effectively the template is not overridden. We need to make sure that we always execute the hook_theme after social_tagging.
https://www.drupal.org/project/social/issues/3330544
*[Required if applicable] Paste a link to the drupal.org theme issue …

Issue #3330544 by nkoporec: Social follow taxonomy popup doesn't appear

---

composer.json

Reverting merge due to the new feature that might be BC breaking change:
[#2892104](https://www.drupal.org/i/2892104) by idimopoulos, claudiu.cristea, alexpott, webflo, benelori, mikhailkrainiuk, geek-merlin, blade_ukraine: Add support for CC and BCC headers

Revert "Updates: (deps): Update drupal/swiftmailer requirement from 2.3.0 to 2.4.0"

---

modules/social_features/social_swiftmail/config/schema/social_swiftmail.schema.yml
modules/social_features/social_swiftmail/social_swiftmail.install
modules/social_features/social_swiftmail/social_swiftmail.module
modules/social_features/social_swiftmail/src/Form/SocialSwiftmailSettingsForm.php

Currently we hardcode the user greeting when we sent any email, eq: (https://monosnap.com/file/B5sMPud3I3kTSHdFO7il7AcnVW7ca7)
This is not ideal and it would be good to have some kind of setting where you could configure this.
It doesn't make sense to hard-code the user greeting since it might not be relevant for certain email templates.
There are a couple of templates that doesn't need the user greeting, since by default it already includes one, so we could either hard-code the template names or create a settings form to be configurable. I prefer the second option even thought this is not something that will change a lot, it still has value to be able to alter it via the UI. So I suggest to create a new setting for social_swiftmailer where you add the template name that should not …

Issue #3324960 by nkoporec: Make user greeting optional for certain emails

---

composer.json

Drupal core issue #1236098 => Notice: Undefined index: 'base' in _color_rewrite_stylesheet().
Warning appears when saving /admin/appearance/settings/socialblue settings.
The source issues: https://www.drupal.org/project/color/issues/1236098
Apply the patch to remove the warnings.
[3334848](https://www.drupal.org/project/social/issues/3334848)
N/A
Apply the patch for Drupal core issue #1236098 (Notice: Undefined index: 'base' in _color_rewrite_stylesheet())
N/A
N/A

Issue #3334848 by zanvidmar: Add patch to fix the Drupal core issue #1236098 

---

modules/social_features/social_profile/social_profile.module

The user images were not being displayed on the when profile entity is somehow added to landing_page content type, for example, having a featured section in a landing page having profile entity display.
1. https://github.com/goalgorilla/open_social/blob/main/modules/social_features/social_profile/social_profile.module#L727 called for access check on File entity.
2. This called https://git.drupalcode.org/project/drupal/-/blob/9.5.x/core/modules/file/src/FileAccessControlHandler.php#L21
3. In the function mentioned above, the `$entity_and_field_access = $referencing_entity->access('view', $account, TRUE)->andIf($referencing_entity->$field_name->access('view', $account, TRUE));` resulted in `AccessResultAllowed`
4. This line checked for access on both **File** …

Issue #3325955 by navneet0693: Profile pictures missing on landing page content type.

---

modules/social_features/social_tagging/src/Form/SocialTaggingSettingsForm.php

In the Submit of the form the code checks:
```
public function submitForm(array &$form, FormStateInterface $form_state): void {
...
if ($form_state->hasValue('tag_type_profile')) {
$result = $this->database->select('cachetags', 'ct')
->fields('ct', ['tag'])
->condition('ct.tag', 'profile:%', 'LIKE')
->execute();
if ($result !== NULL) {
// Clear cache tags of profiles.
$this->cacheTagsInvalidator->invalidateTags($result->fetchCol());
}
}
....
```
There are a number of issues with this:
1. `hasValue('tag_type_profile')` is always true, as the form state has this value even if it's not checked.
2.
```
$result = $this->database->select('cachetags', 'ct')
->fields('ct', ['tag'])
->condition('ct.tag', 'profile:%', 'LIKE')
->execute(); 
```
Might return
```Uncaught PHP Exception …
```

Issue #3336391: Allowing content tagging on Profile using the Settings Form incorrectly clears cache tags and could result in Unexpected Error

---

.github/workflows/behat.yml

Nested test failures currently don't produce assets due to incorrect pathnames. Additionally if an update test fails it may be difficult to reproduce the failure locally because you'd need to install an older version of Open Social.
- Add a script to create a folder hierarchy of test outputs and use GitHub's asset action behaviour of appending to the same asset to merge all the test output into a single downloadable archive
- Include the `installation.sql` database which is loaded at the start of the test in the output so that it can be downloaded and loaded locally.
Internal, no issue
N/a

Internal: Improve test asset naming and contents

---

tests/behat/features/bootstrap/SocialDrupalContext.php

This step is sometimes called after a cache clear which rebuilds the container and unloads all modules. Normally an HTTP request will ensure all modules are loaded again, but if the cache clear is directly preceding queue processing then that's not the case. Normally this wouldn't even be a problem, but in some tests we have those two steps AND we have something in the queue that calls `renderPlain` (e.g. a message token) which will cause the theme system to balk at unloaded modules. Thus, to fix this we must now make sure all modules are loaded.

Internal: Fix queue after cache in tests

---

modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module

Distro has those three functions that checking `group visibility` in a group:
- `social_group_flexible_group_public_enabled()`
- `social_group_flexible_group_community_enabled()`
- `social_group_flexible_group_members_enabled()`
The problem is that those functions check `field_group_allowed_visibility` field rather than `field_flexible_group_visibility` field. Checked field should be vise versa (`field_flexible_group_visibility` and not `field_group_allowed_visibility`) which is more logical and follows from the context (and functions names 🙂)
This also cause a problem that a flexible group can be created with public visibility and group visibility for content, as a result the group is not available to anonymous users.
Check access to the group by `field_flexible_group_visibility`, not by …

Issue #3314447 by rolki: Inconsistent in checking access to a group

---

modules/custom/activity_logger/src/Service/ActivityLoggerFactory.php

Our tests only run in English so we don't encounter this in our CI. However some users with sites that have non-English languages might have assertions enabled in production.
In that case the language code will not be `en` and an exception will be thrown even if the rest of the config is correct. From a functionality point of view the langcode itself doesn't really matter.
Removing the language check removes the risk of distro users with misconfigured servers getting an exception thrown even when everything is fine.
https://www.drupal.org/project/social/issues/3342382
Although we recommend disabling assertions for production environment, the activity system will no longer throw an exception about incorrectly installed fields for environments with assertions enabled that are processing …

Issue #3342382: Don't validate language in `debugMessageTemplateIsCompatible`

---

modules/custom/alternative_frontpage/alternative_frontpage.services.yml
modules/custom/alternative_frontpage/src/EventSubscriber/RedirectHomepageSubscriber.php

When using the alternative_frontpage module, users can create endless redirect loops if they use path aliases for path instead of actual url.
In RedirectHomepageSubscriber.php we are not checking if the frontpage path setting is an alias or an actual url. We need to always compare urls and not aliases and then decide if we need to do the redirect.
*https://www.drupal.org/project/social/issues/3344207
1. Install alternative_frontpage module
2. Create a basic page, that will be the frontpage for authenticated users …

Issue #3344207 by nkoporec: Alternative frontpage settings causes an endless redirect loop

---

.github/workflows/behat.yml

It can be difficult to get an older version of Open Social installed locally (e.g. due to unsupported PHP versions). This commit dumps the database after installing the older version so that it can easily be loaded for local debugging in case the upgrade path is broken.
The GitHub artefact is only created in case the test fails so we don't waste any storage space on success.
Internal change no ticket

Internal: Dump pre-update database to GitHub artifact

---

modules/social_features/social_content_block/social_content_block.services.yml
modules/social_features/social_content_block/src/ContentBuilder.php
modules/social_features/social_content_block/src/ContentBuilderInterface.php

Anonymous users can see <code>community</code> <code>secret</code> flexible group teasers in "Custom content list block" block:
Should be:
Add access check before entities view build.
- https://www.drupal.org/project/social/issues/3339566
- https://getopensocial.atlassian.net/browse/PROD-24010
n/a
_Before changes_:
_After changes_:
Now "Custom content list block" block displays only content (and groups) that user has access to.
n/a
n/a

Issue #3339566 by vnech: Entity access is ignoring in "Custom content list block" block type

---

modules/social_features/social_group/modules/social_group_invite/social_group_invite.module
modules/social_features/social_group/modules/social_group_invite/src/Plugin/Join/SocialGroupInviteJoin.php
modules/social_features/social_group/modules/social_group_request/src/Plugin/Join/SocialGroupRequestJoin.php
modules/social_features/social_group/social_group.module

Invited user is missing option to accept/reject invitation when they are invited to "request to join" group.
Which "join plugin" is initiated with given group can be determined by field or by method. Flexible groups are defining this by field_group_allowed_join_method "Join methods". In the code, there was already predicted that If user has a pending invite, we should skip the request button and go to "fallback" `added` join method, but that never worked since https://github.com/goalgorilla/open_social/pull/2658. To fix this we added `added` join method as something that is always available for flexible groups despite and in addition to what is selected by "Join methods"
[social_group_invite.module](https://github.com/goalgorilla/open_social/pull/3326/files#diff-676d9bcf9065b481e26a458b6df …

Issue #3345231 by zanivdmar: Missing option to accept invite 

---

modules/social_features/social_core/src/EventSubscriber/SocialInviteSubscriber.php

We execute `$this->inviteService->getInviteData();` on every page load (also file loads from the private file system).
Move execution inside of the existing `if` statement controlling the actual notification.
- https://www.drupal.org/project/social/issues/3347315
N/a
N/a
Slightly improve performance by removing unnecessary load of pending invite data.
N/a
N/a

Issue #3347315 by bramtenhove: Move execution of expensive invitation data to when it is needed for sending notifications 

---

modules/social_features/social_core/src/ContentTranslationConfigOverrideBase.php
phpstan-baseline.neon

As we're adding this to social_core, so we can easily and always extend this (without creating dependencies) we need to make sure we worry about performance as well. The config override is added on runtime for every request now; but it should only kick in when:
- Social content translation is enabled.
- The module, extending, is configured to be true in the content translation settings
- The config name matches the overridden translations from the extending plugin
If its not enabled, lets return early, saves a hell of a lot of checks. 
If it is enabled, lets make sure we statically cache the settings from config, 
otherwise we need to load that over and over.
Otherwise continue as normal, as we are already only overriding things when the config name is in the array of the plugin …

Issue #3346966 by ronaldtebrake: Social Content Translation Config Override runs in unnecessary circumstances.

---

modules/social_features/social_follow_taxonomy/modules/social_follow_tag/src/SocialFollowTagOverrides.php

We're doing expensive config gets in overrides and this is also the case for Social Follow Tag.
Move the `if` statement that checks for the config name first before executing the config get call.
https://www.drupal.org/project/social/issues/3348281
N/a
N/a
We improved performance by reducing the number of config get calls in Social Follow Tag.
N/a
N/a

Issue #3348281 - Fix expensive calls in config override of Social Follow Tag

---

.github/workflows/bestPractices.yml

We've found that config overrides cause a lot of performance issues because they'll be called in a lot of scenarios. We used to need them when we were still using Features, but these days 99.9% of the config overrides can be replaced with a config update in an install hook and uninstall hook instead.
We add a one-liner check to ensure that no new config overrides are being added to our code. In case someone does add one the CI check will fail which can prompt a discussion on the PR for alternative solutions. In case the PR is merged with the override still in then we won't keep complaining on the merged branch.
Internal change no issue

Internal: Add CI check to prevent Config Overrides being added

---

tests/behat/features/bootstrap/EventContext.php
tests/behat/features/bootstrap/TopicContext.php
tests/behat/features/capabilities/contentmanagement/unpublished.feature
tests/behat/features/capabilities/event/eventenrollment-manage.feature
tests/behat/features/capabilities/groups/flexible/content/edit/group-admin/groups-flexible-content-edit-group-admin.feature
tests/behat/features/capabilities/groups/flexible/content/edit/group-manager/groups-flexible-content-edit-group-manager.feature
tests/behat/features/capabilities/groups/flexible/content/edit/member/groups-flexible-content-edit-member.feature
tests/behat/features/capabilities/groups/flexible/content/edit/outsider-platform-manager/groups-flexible-content-edit-outsider-platform-manager.feature
tests/behat/features/capabilities/groups/flexible/content/edit/outsider/groups-flexible-content-edit-outsider.feature
tests/behat/features/capabilities/groups/flexible/content/view/member/groups-flexible-content-view-member.feature
tests/behat/features/capabilities/groups/flexible/content/view/outsider-anonymous/groups-flexible-content-view-outsider-anonymous.feature
tests/behat/features/capabilities/groups/flexible/content/view/outsider-authenticated/groups-flexible-content-view-outsider-authenticated.feature
tests/behat/features/capabilities/groups/flexible/content/view/outsider-contentmanager/groups-flexible-content-view-outsider-contentmanager.feature
tests/behat/features/capabilities/groups/flexible/content/view/outsider-sitemanager/groups-flexible-content-view-outsider-sitemanager.feature
tests/behat/features/capabilities/groups/flexible/content/view/outsider-verified/groups-flexible-content-view-outsider-verified.feature
tests/behat/features/capabilities/groups/groups-edit-type.feature
tests/behat/features/capabilities/groups/groups-management-for-platform-managers.feature
tests/behat/features/capabilities/sharing/share.feature

This replicates what we previously did for groups to events and topics so that we have better control of content ownership to improve test predictability and reliability.

Internal: Add control around authors of content in tests

---

modules/social_features/social_group/modules/social_group_invite/social_group_invite.module
modules/social_features/social_group/modules/social_group_invite/src/Plugin/Join/SocialGroupInviteJoin.php
modules/social_features/social_group/modules/social_group_request/src/Plugin/Join/SocialGroupRequestJoin.php
modules/social_features/social_group/social_group.module

After extensive tests for 11.8.1, we noticed that this fix introduced a new issue where users are not able to ask to join a group that is "invitation only".
We decided to roll back the change.
Reverts goalgorilla/open_social#3326

Issue #3345231 by zanivdmar: Missing option to accept invite | REVERT

---

modules/social_features/social_landing_page/social_landing_page.module
modules/social_features/social_landing_page/templates/paragraph--custom-content-list.html.twig
modules/social_features/social_landing_page/templates/paragraph--custom-multiple-content-list.html.twig

The Custom list block and Custom multiple list block do not have the container wrapper.
Add `container` wrapper to a Custom list block and a Custom multiple list block.
- https://www.drupal.org/project/social/issues/3347592
- https://getopensocial.atlassian.net/browse/PROD-23578
N/A
**Before:**
**After:**
A Custom list and a Custom multiple list blocks now have a correct layout.
N/A
N/A

Issue #3347592 by agami4: Improve layout of the blocks on the landing page

---

modules/social_features/social_comment_upload/src/SocialCommentUploadConfigOverride.php

We're doing expensive config gets in overrides and this is also for Social Comment Upload.
Move the expensive calls within the `if` statement to avoid it being executed more often than necessary.
https://www.drupal.org/project/social/issues/3348272
N/a
N/a
We improved performance by reducing the number of config get calls in Social Comment Upload.
N/a
N/a

Issue #3348272 - Fix config override cache gets for Social Comment Upload

---

modules/social_features/social_album/config/install/views.view.albums.yml
modules/social_features/social_album/config/update/social_album_update_11471.yml
modules/social_features/social_album/social_album.install

Nothing happens when clicking on a pager on Album content type.
The reason in that the pager id is not correct, we need to set it to 0 (as it is by default)
https://www.drupal.org/project/social/issues/3350671
1. Enable social_album
2. Create a new album and add at least 13 images (so that the pager is displayed)
3. View the album and try to use the pager.
*[Required if new feature, and if applicable] If this Pull Request makes visual changes then please include some screenshots that show what has changed here. A …

Issue #3350671 by nkoporec: Pager not working in Albums

---

composer.json

Currently, after adding an embed_url in the content we get an error that blocks user to add a media link.
There is already a patch to fix the issue for the `url_embed` module and we could use it as well.
- https://www.drupal.org/project/social/issues/3348717
- https://www.drupal.org/project/url_embed/issues/3285139
- https://getopensocial.atlassian.net/browse/PROD-24012
Currently:
After applying a patch:
URL Embed now adds a X-Drupal-EmbedPreview-CSRF-Token header to the preview request in order to fix 403 forbidden issue.

Issue #3348717 by SV: Embed Preview throws 403 forbidden - Embed now requires a csrf token

---

modules/social_features/social_content_block/social_content_block.services.yml
modules/social_features/social_content_block/src/ContentBuilder.php
modules/social_features/social_content_block/src/ContentBuilderInterface.php

Custom content list block does not display the correct number of items when content is translated.
Adding language filtering to remove translation duplicates in a query that returns an entity list for the "Custom content list block".
[3351588](https://www.drupal.org/project/social/issues/3351588)
N/A
Type of content: Topic
Topic type: News 
Number of items: 5
Sort: Most recent
and save the changes
N/A
The "Custom content list block" now displays the correct number of items when content on the list is translated.
N/A
N/A

Issue #3351588 by zanvidmar: Wrong number of items on Custom content list block

---

modules/social_features/social_profile/social_profile.module

Profile pictures missing on landing page content type for LU that is not VU.
This is the FUP of [3237](https://github.com/goalgorilla/open_social/pull/3237)
For authenticated user, which is not verified user, the user profile image is not loaded and appears broken instead of the default placeholder.
Use permission system instead of role based logic which is not covering all the cases.
[3346912](https://www.drupal.org/project/social/issues/3346912)
N/A
N/A
When the website was using private file, then the profile images appear to be broken on landing pages for Authenticated users without verified user role, if a featured content or a stream view was added. We resolved the access problem for given users and now the default profile picture is displayed.
N/A
N/A

Issue #3346912 by zanvidmar: Profile pictures missing on landing page

---

composer.json

For some reason d.org updated the patch file name, adding a "_0" at the end of the file this made our patch broke therefore breaking main
see: https://www.drupal.org/project/drupal/issues/2910000#comment-15001837
Update patch URL.
N/A
N/A
N/A
N/A
N/A
N/A

Issue #3341238: Fix wrong patch url on main

---

modules/social_features/social_landing_page/templates/page--node--landing-page.html.twig

Header top region is missing from overridden Landing Page template: `page--node--landing-page.html.twig`.
Add rendering of Header top region the same as in base template of socialblue theme: page--sky.html.twig:
```
{% if page.header_top and multi_line %}
{{ page.header_top }}
{% endif %}
```
- https://www.drupal.org/project/social/issues/3353190
- [PROD-24944](https://getopensocial.atlassian.net/browse/PROD-24944)
N/A
Before:
After:
Header top region is now displayed on Landing Pages.
N/A
N/A
[PROD-24944]: https://getopensocial.atlassian.net/browse/PROD-24944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Issue #3353190 by ribel: Add Header top region to the Landing page template

---

composer.json
modules/custom/activity_basics/activity_basics.module
modules/social_features/social_follow_taxonomy/modules/social_follow_tag/social_follow_tag.module
phpstan-baseline.neon

When migrate a content activities are created as well. As a result when there are a huge of amount content this can cause a bad users experience because of streams flooding.
Create an activity only if entity is not syncing.
- https://getopensocial.atlassian.net/browse/PROD-24731
- https://www.drupal.org/project/social/issues/3351326
- https://www.drupal.org/project/drupal/issues/3052115
n/a
This can be faced on content migration.
n/a
Skip activities creation during content migration.
n/a
n/a

Issue #3351326 by vnech: Skip activities creation during content migration

---

modules/social_features/social_group/social_group.services.yml
modules/social_features/social_group/src/GroupMuteNotify.php
modules/social_features/social_group/tests/src/Unit/GroupNotifyTest.php
phpstan-baseline.neon
phpstan.neon

We got a `LogicException: An anonymous user must be identified by session ID` because we forgot to provide a session id if the user is anonymous. Something the `FlagService` expects as you can see below: 
```
if (!isset($account)) {
// If there isn't an account, set it to the current user.
$account = $this->currentUser;
// If the user is anonymous, get the session ID. Note that this does not
// always mean that the session is started. Session is started explicitly
// from FlagService->ensureSession() method.
if (!isset($session_id) && $account->isAnonymous()) {
$session_id = $this->getAnonymousSessionId();
}
}
elseif ($account->isAnonymous() && $session_id === NULL) {
throw new \LogicException('Anonymous users must be identified by session_id');
}
```    
It could occur the user is …

Issue #3355315 by ronaldtebrake: Ensure we check for the mute notification flag and provide a session id for AN users.

---

modules/social_features/social_activity/config/optional/views.view.activity_stream.yml
modules/social_features/social_activity/config/update/social_activity_update_11701.yml
modules/social_features/social_activity/social_activity.install

Currently, we have two different blocks (block_stream_homepage, block_stream_homepage_without_post) with the same name in the activity_stream views that can confuse users when there is a possibility to select a block and there are two duplicated items.
Rename duplicate block label in views:
- `block_stream_homepage` => **Homepage stream block (with post form)**
- https://www.drupal.org/project/social/issues/3356324
- https://getopensocial.atlassian.net/browse/PROD-24014
N/A
Before:
After:
Fix duplicated names for "Activity Stream: Homepage stream block"
N/A
N/A

Issue #3356324 by SV: Fix duplicated names of "Activity Stream: Homepage stream block"

---

composer.json
tests/behat/features/capabilities/alternative-frontpage/alternative-frontpage.feature

We updated Open Social to Drupal 9.5.3 ([PR](https://github.com/goalgorilla/open_social/pull/3369))
We need to upgrade Gin to at least 8.x-3.0-rc1 as stated in PR.
Check the Gin issue for more info: https://www.drupal.org/project/gin/issues/3309113
Update Gin version to 8.x-3.0-rc2
[3354659](https://www.drupal.org/project/social/issues/3354659)
[3309113](https://www.drupal.org/project/gin/issues/3309113)
N/A
Gin has been updated to 3.0-rc2
Gin has been updated to 3.0-rc2. RC1 deprecated the CamelCase CSS3 classes in favor of kebab case classnames. They will be removed in the stable release. See [#3309113: Change CSS3 variables from camelCase to kebab-case](https://www.drupal.org/project/gin/issues/3309113)
N/A

Issue #3354659 by zanvidmar: Update Gin version to 8.x-3.0-rc2

---

modules/social_features/social_search/src/Form/SearchContentForm.php
modules/social_features/social_search/src/Form/SearchHeroForm.php
tests/behat/features/capabilities/search/search-content.feature

When you have a search going on at `/search/content/queryterm?page=2` and you start a new one, you will stay at page 2 and not start anew, e.g. `/search/content/newqueryterm?page=2`.
1. Search for something
2. Go to page 2
3. Search for something new
4. You are still at page 2
Always remove the `page` query parameter when starting a new search query.
- https://www.drupal.org/project/social/issues/3355419
- https://getopensocial.atlassian.net/browse/PROD-22096
N/a
_Consider running the updated Behat test on a different branch. You will notice the final step failing._
N/a
Fixed an issue where a user would perform a search query further down the search result pages (e.g. on page 3), and they would stay at page 3 when performing a new search query. Now, when you start a new search you will …

Issue #3355419 - Make sure new search queries always start at the first page

---

tests/behat/features/bootstrap/EntityTrait.php
tests/behat/features/bootstrap/TopicContext.php

This commit allows taxonomy reference data to be provided as a comma separated list of IDs or term names (mixing is allowed). This can now be used in tables for e.g. groups, topics and events. By putting this in the validate method we can use this everywhere.
This ensures we deduplicate the taxonomy title lookup so that we don't break on a pre-fetched value. Since we now do it by field type we no longer need to do it by field name.
Additionally we allow date fields to be filled using a human readable date (e.g. `-1 seconds` or `+ 1 hours`).
```cucumber
Scenario: Reference a tag by name
Given social_tagging terms:
| name      | parent   |
| Clothing  |          |
| Pants     | Clothing |
And groups with non-anonymous owner:
| label            | type           | …
```

Internal: Improve test fixture creation for taxonomy references and dates

---

.github/workflows/behat.yml
tests/behat/behat.yml
tests/behat/features/bootstrap/AvoidCleanupTrait.php
tests/behat/features/bootstrap/ConfigContext.php
tests/behat/features/bootstrap/DatabaseContext.php
tests/behat/features/bootstrap/EmailContext.php
tests/behat/features/bootstrap/EventContext.php
tests/behat/features/bootstrap/FeatureContext.php
tests/behat/features/bootstrap/GroupContext.php
tests/behat/features/bootstrap/PostContext.php
tests/behat/features/bootstrap/SocialDrupalContext.php
tests/behat/features/bootstrap/SocialMessageContext.php
tests/behat/features/bootstrap/TopicContext.php
tests/behat/features/capabilities/dev-helpers/fail.feature
tests/behat/features/capabilities/dev-helpers/pass.feature

We previously utilised a lot of clean-up steps to make sure our tests didn't affect eachother. However we've since moved to a scenario where both in the CI and locally a new database is loaded between scenarios, this makes the clean-up no longer needed.
Additionally if the clean-up does run then this makes debugging a failed test a lot more difficult because you can't inspect the state of the platform at the time the test failed.
This commit ensures that all the clean-up that is provided by the DrupalExtension by default is disabled. For this we have to disable autoloading of sub-contexts (which we weren't using anyway) because the search_api contained a `behat.inc` file that would load the `RawDrupalContext` class which contained more cleaning.
There are DrupalExtension stories open to …

Internal: Disable clean-up in Behat tests

---

modules/custom/social_admin_menu/social_admin_menu.info.yml
modules/custom/social_admin_menu/social_admin_menu.module
modules/custom/social_admin_menu/src/Menu/SocialAdminMenuAdministratorMenuLinkTreeManipulators.php
phpstan-baseline.neon

This is part of a bigger performance improvement;
#3355 is the bigger chunk where we will work on reducing links as well as creating our own admin menu where we have all control but it's under construction as that is a massive overhaul that might need a major version.
Part of the problem is that we have different modules enabled that all want to take part in rendering (and caching) our admin menu.
For example;
1. Gin_toolbar wants to cache it per route; 
https://git.drupalcode.org/project/gin_toolbar/-/blob/8.x-1.x/gin_toolbar.module#L191 so the active menu trail works.
2. Bootstrap wants to add a cache based on if it's the frontpage or not and does this globally, so it runs for multiple preprocesses which are bubbled up 
https://git.drupalcode.org/project/bootstrap/-/blob/8.x-3.x/src/Boot …

Issue #3349597 by ronaldtebrake: Part 1: Improve admin menu performance by using correct cache contexts

---

modules/social_features/social_follow_taxonomy/assets/css/social_follow_taxonomy.css
modules/social_features/social_follow_taxonomy/assets/css/social_follow_taxonomy.scss
modules/social_features/social_follow_taxonomy/templates/flag--follow-term.html.twig

The `Unfollow` button doesn't have a frame on the follow tag popup.
Replace the `flag` wrapper class with different one.
- https://www.drupal.org/project/social/issues/3360728
- https://getopensocial.atlassian.net/browse/PROD-25421
N/A
Before:
After:
The `Unfollow` button on follow tag popup has a correct style.
N/A
N/A

Issue #3360728 by agami4: Improve to the Unfollow button in the follow tag popup

---

.github/PULL_REQUEST_TEMPLATE.md

The PR template requires a lot of removal when trying to fill it in.
Move template explanations into HTML comments
This allows them to be more easily ignored and allows someone to just start writing in the template rather than having to replace or remove text.

Internal: Move template explanations into HTML comments

---

tests/behat/features/bootstrap/EventContext.php

Provide Behat step definition where enrollees can be added to event.
As a developer I want to have Behat step definition where I can programatically enroll users to an event.
Add new functionalities to EventContext.php in Behat test folder.
[3363814](https://www.drupal.org/project/social/issues/3363814)
N/A
N/A
N/A
Improve Behat test step definitions for event.
N/A
N/A

Internal: #3363814 by zanvidmar: Behat step definition to enroll users to event

---

modules/social_features/social_landing_page/js/social_landing_page--accordion.js
modules/social_features/social_landing_page/social_landing_page.libraries.yml

As a LU+ I see that accordions open and close a few times when I click on the expand/collapse button on the landing pages
Add `once` to the js accordion behavior.
- https://www.drupal.org/project/social/issues/3365307
- https://getopensocial.atlassian.net/browse/PROD-25613
N/A
Before:
https://github.com/goalgorilla/open_social/assets/16086340/04077ddd-01e4-4b4d-9c8a-616cd7a97564
After:
https://github.com/goalgorilla/open_social/assets/16086340/7253b7ef-a0d6-4a2a-80f9-f8dc4f44b1b8
The accordion collapse has a correct behavior.
N/A
N/A

Issue #3365307 by agami4: Add improvements to the accordion collapse behavior

---

modules/social_features/social_profile/modules/social_profile_preview/assets/js/social_profile_preview.js
modules/social_features/social_profile/modules/social_profile_preview/social_profile_preview.libraries.yml

As a LU+ I see multiple profile previews at once when I hover on a user’s profile image or name
Add `once` to the mouseover event.
- https://www.drupal.org/project/social/issues/3366143
- https://getopensocial.atlassian.net/browse/PROD-25712
N/A
Before:
After:
Display only one preview profile window when hovering over the profile avatar.
N/A
N/A

Issue #3366143 by agami4: Add improvements to the profile preview window

---

.github/workflows/behat.yml

We're working on Open Social versions which have different minimum and maximum PHP requirements. To make sure we can test the upgrade path we must move the installation of the previous version to a separate job. This allows us to use a different PHP image and thus a different version.
This commit moves the previous installs into separate jobs and then reuses the output of that in the current upgrade path job so we can upgrade from one PHP version to another.
Internal CI change no issue

Internal: Separate previous version install in GitHub CI

---

.github/workflows/behat.yml

GitHub is messing up the installation database dumps since #3427.  This deduplicates the installations across jobs and also makes it clearer which is which. An added benefit is that we no longer have the same installation dump in the behat-test-output multiple times :) 

Internal: Set Behat CI install dump names depending on job configuration

---

tests/behat/features/capabilities/administration/check-revoke-or-grant-administrador-roles.feature
tests/behat/features/capabilities/groups/groups-create-closed.feature

We have a known race condition in the way the Chrome driver clicks on buttons. It will first query the page for the position of a button using JavaScript and then send a click event to Chrome for the retrieved coordinates on the page.
It can happen that something is being loaded (e.g. CKEditor or a VBO feedback element) which can caue the page to shift between the determination of the button's component and the actual click. This can cause the test to "misclick" which results in an intermittend test failure.
We add a second delay before we try to click the buttons which we believe are affected by this issue so that the page has time to settle.

Internal: Fix false positives in CIs

---

.github/workflows/behat.yml
tests/behat/features/bootstrap/EmailContext.php
tests/behat/mail-spool/.gitignore

We previously created this in the GitHub workflow, but this makes new developer project set-up more difficult (because then when running an email test the folder doesn't exist).
By adding it to the repository we ensure it's present for developers and we can remove some steps from the CI.
We rename it from `swiftmailer-spool` to `mail-spool` because we know in the future we want to move away from swiftmailer.
We ignore all messages in the directory to make sure we don't accidentally commit debug output.

Internal: Ensure the mail-spool directory exists for Behat tests

---

modules/custom/activity_logger/src/Service/ActivityLoggerFactory.php

Entity conditions are executed in ActivityLoggerFactory::createMessages before some of the other checks are evaluated. This can cause an entity condition that may only be usable on specific bundles to be called on other data.
We re-order the checks so that we check for matching properties first and only at the end execute the more expensive entity condition plugins. This also makes it easier to move the conditions into a database query when we move into a different configuration structure in the future.
Note: a nicer solution would be to make the conditions a more cohesive whole, but that's too big a change for now, so we just change the evaluation of conditions from generic (e.g. bundle) to specific (condition on data of the entity) to make our developer lives easier. …

Issue #3369035: Notification entity conditions can not rely on other template configuration

---

modules/social_features/social_album/src/Plugin/Field/FieldWidget/SocialAlbumOptionsSelectWidget.php
tests/behat/behat.yml
tests/behat/features/bootstrap/AlbumContext.php
tests/behat/features/capabilities/post/post-album-existing.feature

When using social_album and I want to add an image to stream using the default /stream page, I see that a field widget is displayed to also add this image to an album, but the options there are always "None" or "Create a new album", even if I already have multiple albums created. So it should be possible to select an existing album.
I have multiple public albums created:
I don't see them in the field widget:
We need to update the custom field widget to allow selecting an existing albums.
https://www.drupal.org/project/social/issues/3370849
*[Required if applicable] Paste a link to the drupal.org theme issue queue item, either from [socialbase](https://www.drupal.org/project/socialbase) or [socialblue](https://www.drupal.org/project/socialblue). If any other issue trackers were used, …

Issue #3370849 by nkoporec: Can't add an image to the existing album on stream page

---

modules/social_features/social_group/modules/social_group_flexible_group/config/modify/social_group_flexible_group.field_group_type_overview_filter.yml
modules/social_features/social_group/modules/social_group_flexible_group/config/update/social_group_flexible_group_update_11901.yml
modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install
modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
modules/social_features/social_group/social_group.module
modules/social_features/social_group/src/Form/SocialGroupSettings.php
tests/behat/features/bootstrap/GroupContext.php
tests/behat/features/bootstrap/SocialMinkContext.php
tests/behat/features/capabilities/groups/groups-view-overview-filter.feature

In Open Social version 10 we have introduced a new taxonomy vocabulary called Group types where a user is able to categorise a flexible group using this taxonomy term reference field. At the moment we do not expose this as a filter anyway so its use is limited.
Scope of this story will be to expose the filter in the /all-groups overview.
Add the filter to the overview and follow the following business rules:
1. If there are no values in the vocabulary referenced by the new type filter, we hide the filter.
2. If the setting in the Group settings to require the new type field on flexible groups is disabled, we hide the filter.
3. Whenever flexible group is the only Group type option we hide the old Group type filter.
4. Whenever flexible group is the only Group type option and the Group …

Issue #3370936 by ronaldtebrake: Allow users to filter on the Flexible Group types on the `/all-groups` overview

---

modules/custom/activity_creator/activity_creator.module

When enabling social_language it should support multiple language, but the actvity stream items keep in the default language.
Make sure the activities get loaded in the correct language before outputting them
https://www.drupal.org/project/social/issues/3358171
We fixed an issue where activity stream items would show in the wrong language if you would have multiple languages.
*[Required if applicable] If this Pull Request changes the way that developers should do things or introduces a new API for developers then a change record to document this is needed. Please provide a draft for a change record or a link to an unpublished change record below. Existing change records can be consulted as example. Please provide a draft for a change record or a link to an unpublished change record below. …

Issue #3358171 : Multilanguage: Activity stream items are not showing in the correct language

---

.tugboat/config.yml

This is a PR from a series of 4 PRs that should be merged in the following order: 
1. https://github.com/goalgorilla/open_social_dev/pull/70 
2. https://github.com/goalgorilla/open_social/pull/3460 ( this PR )
3. https://github.com/goalgorilla/open_social/pull/3457
4. https://github.com/goalgorilla/drupal_social/pull/392 ( this is just a private repository that we use for development, this will not be available for public users )
They are ALL BC and should not cause any breaking change for our local development 
Since we are moving to PHP 8.1, we should update our tugboat docker image
Use the new available image from here https://github.com/goalgorilla/ci_images/pkgs/container/ci-tugboat-php
https://www.drupal.org/project/social/issues/3373172
N/A
N/A
N/A
N/A
N/A

Issue #3373172 by tbsiqueira: Update our tugboat docker image with one supporting PHP 8.1

---

.github/workflows/behat.yml
modules/custom/activity_basics/activity_basics.install
modules/custom/download_count/download_count.module
modules/custom/improved_theme_settings/improved_theme_settings.module
modules/custom/social_path_manager/social_path_manager.module
modules/social_features/social_core/social_core.install
modules/social_features/social_event/social_event.install
modules/social_features/social_follow_user/social_follow_user.install
modules/social_features/social_group/modules/social_group_invite/src/Form/SocialBulkGroupInvitation.php
modules/social_features/social_landing_page/social_landing_page.module
modules/social_features/social_post/modules/social_post_album/src/Element/SocialPostAlbumManagedFile.php
modules/social_features/social_profile/social_profile.install
modules/social_features/social_profile/src/SocialProfileTrait.php
modules/social_features/social_swiftmail/social_swiftmail.module
modules/social_features/social_user/social_user.install

This is a PR from a series of 5 PRs that should be merged in the following order: 
1. https://github.com/goalgorilla/open_social_dev/pull/70 
2. https://github.com/goalgorilla/open_social/pull/3460
3. https://github.com/goalgorilla/open_social/pull/3457
4. https://github.com/goalgorilla/drupal_social/pull/392 ( this is just a private repository that we use for development, this will not be available for public users )
5. https://github.com/goalgorilla/open_social/pull/3439
We are now officially adding php 8.1 support, but our behat tests are still running on PHP 8.0, this is not an issue because PHPStan guarantees the compatibility, but we want to run our behat tests using PHP 8.1,
After we fixed the behat tests, a couple of issues raised:
`$extensions = explode(' ', …

Issue #3368689 by tbsiqueira: Update behat tests to use the new compatible php 8.1 images

---

modules/social_features/social_mentions/social_mentions.module

The reply button is missing when you want to reply to a comment reply.
Fix the if check in social_mentions module.
https://www.drupal.org/project/social/issues/3378480
1. Create a topic and enable comments
2. Create a comment as user 1
3. As a different user reply to this comment
4. As user 1 try to reply to the reply created above
Before:
After:
Fixed a bug where users could not reply to a comment reply.

Issue #3378480 by nkoporec: Cannot reply to a comment reply

---

modules/social_features/social_event/config/install/views.view.event_enrollments.yml
modules/social_features/social_event/config/install/views.view.event_manage_enrollment_requests.yml
modules/social_features/social_event/modules/social_event_an_enroll/config/install/views.view.manage_enrollments.yml
modules/social_features/social_event/modules/social_event_invite/config/install/views.view.event_manage_enrollment_invites.yml
modules/social_features/social_event/modules/social_event_managers/config/install/views.view.event_manage_enrollments.yml
modules/social_features/social_event/modules/social_event_managers/config/install/views.view.managers.yml
modules/social_features/social_event/social_event.install
tests/behat/features/bootstrap/SocialMinkContext.php
tests/behat/features/capabilities/event-management/event-management.feature

If you add a translation to an event, it leads to duplicate enrollees and event organisers. This also applies to invitations and requests.
Update the configurations of the views that are responsible for this, namely, enable the distinct option to prevent duplication.
- https://getopensocial.atlassian.net/browse/PROD-22011
- https://www.drupal.org/project/social/issues/3377397
N/A
Fixes issue with duplication event enrollees and organisers, when event has several translations.
N/A
N/A

Issue #3377397 by Kovalskiy266: Fix duplication of event enrollees and organizers

---

modules/social_features/social_swiftmail/social_swiftmail.module

The variable 'border_radius' is not used in a template and can be not set.
After a discussion, there was decided to use two border configurations from theme.
The issue about that already exists on Drupla org, but uses a different approach https://www.drupal.org/project/social/issues/3342642
Add variables and use them in a template.
- https://www.drupal.org/project/social/issues/3342642
- https://getopensocial.atlassian.net/browse/PROD-26293
- https://git.drupalcode.org/project/socialbase/-/merge_requests/178
Pass theme `border-radius` configuration to the email template.
None.
None.

Issue #3342642: Update variables for email template to pass border-radius config

---

modules/custom/mentions/src/Plugin/Filter/MentionsFilter.php
modules/social_features/social_activity/social_activity.services.yml
modules/social_features/social_activity/src/EmailTokenServices.php
modules/social_features/social_mentions/src/Plugin/ActivityContext/MentionActivityContext.php

When we mention other users in comments or in posts, an email is sent to them to notify them. But we have a problem -  instead of the names of the users mentioned, we see their IDs in the email. This is not correct. This problem has been here for quite some time, previously it was discussed here - https://github.com/goalgorilla/open_social/pull/1873
Change the code for comment and post previews by applying a mention filter with settings. This way, the `[message:preview]` token will display the correct result
- https://www.drupal.org/project/social/issues/3069371
- https://getopensocial.atlassian.net/browse/PROD-26095
N/A
**Before:**
**After:**
We have solved a problem where email notifications containing mentions would not get converted to the correct display name but instead showed an …

Issue #3069371: Change preview token for comment and post to fix mentions in emails

---

modules/social_features/social_search/config/install/search_api.index.social_all.yml
modules/social_features/social_search/config/install/views.view.search_all.yml
modules/social_features/social_search/config/install/views.view.search_content.yml
modules/social_features/social_search/config/install/views.view.search_groups.yml
modules/social_features/social_search/social_search.install

In #3470 we changed the search_api_language filter to a language_with_fallback filter to ensure that users could find matching content in different languages if no version in their own language was available. However, this also changed the IDs of the filter which can break existing sites that might rely on that filter.
In this commit we revert the ID/name change and only change the field used. We also revert any formatting changes made to the views.* files to make fixing merge conflicts in our search rework easier.
https://www.drupal.org/project/social/issues/3382816
In Open Social 11.9.10 the name and ID of the language filter were changed along with its type. If you relied on this name this may cause you issues. We've reverted the change to the name and ID so existing code can keep …

Issue #3382816: Revert search_api_language filter ID change in search views

---

.github/workflows/behat.yml

It can be difficult to debug failed tests for e-mails because we are not able to look at the files that are in the mail-spool. This commit changes the Behat failure scenario to also copy any e-mail messages from the mail-spool on a test failure.
Internal change no ticket

Internal: Allow debugging mail spool for failed tests

---

composer.json

As this patch only lands in 10.1.x (which is when we can remove this patch) we backport it as it could have significant performance impact, especially on pages layout builder or paragraphs driven (or even views with many fields).
This way we can get the benefits already from the work done there, and remove it once we do our update towards 10.1.x, which is not yet planned at the time or writing.
Backport the issue from Drupal Core issue [3231503](https://www.drupal.org/project/drupal/issues/3231503)
[3383704](https://www.drupal.org/project/social/issues/3383704)
Performance improvement for `hook_entity_extra_field_info()` and `EntityFieldManager::getExtraFields()`

Issue #3383704: cache improvements for `hook_entity_extra_field_info()` and `EntityFieldManager::getExtraFields()`

---

modules/social_features/social_search/social_search.install

A typo in `social_search_update_11403` leaves sites in an indeterminate state which causes a fatal error for admins. Additionally it means that the view configuration is not properly updated.
We can't just fix the change in `social_search_update_11403` because we would leave sites that had already executed the update in an indeterminate state.
There's two scenarios:
1) The update has already run. In this case the change for the groups view hasn't happened due to the type, the new update hook will be executed and now all views are correct.
2) The update hook hasn't run already. In this case we do the correct 2 views (that sites from scenario 1 don't need help changing) in 11403 and we fix groups in 11404.
https://www.drupal.org/project/social/issues/3383079
A typo in an upgrade hook caused …

Issue #3383079: Hotfix: Fix view name for groups search

---

modules/social_features/social_content_block/src/SocialContentBlockOverride.php

The class reads existing config, but in the upgrade path from Open
Social 10 to 11 the config schema is changed, so the array element we're
trying to read might not exist. This causes warnings in the upgrade
path.
We ignore the setting if it doesn't exist because it means we're working with the old config. The config override will be reloaded after the post-update cache-clear which ensures the proper override is applied.
https://www.drupal.org/project/social/issues/3383956

Issue #3383956: Fix upgrade path warning in SocialContentBlockOverride

---

.github/workflows/behat.yml
modules/social_features/social_content_block/src/SocialContentBlockOverride.php
modules/social_features/social_event/config/update/social_event_update_11902.yml

Although people's configuration changes might cause warnings in an upgrade path (for example of upgrade_helper skips a config change to avoid undoing site-builder choices), we do not expect any warnings in the default upgrade path that we build for Open Social.
A warning (like an undefined array key) usually points to a typo and can lead to fatal errors down the line. We want to make sure that there are no warnings in our upgrade path if nothing was changed.
Our behat test runs an upgrade from the previous major version. Drush has no good "fail on warning" options, so we'll have to parse the text output of the command and check if any log messages of the warning type were output.
This PR required some other fixes to prove it works and those need to be reviewed before merging this
- CI …

Internal: Ensure Behat test run exits in case of warnings in upgrade path

---

composer.json
modules/custom/social_gdpr/social_gdpr.install
modules/social_features/social_book/social_book.install
modules/social_features/social_core/config/modify/social_core.access_contextual_links_permissions.yml
modules/social_features/social_core/social_core.install
modules/social_features/social_event/social_event.install
modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install
modules/social_features/social_landing_page/social_landing_page.install
modules/social_features/social_page/social_page.install
modules/social_features/social_profile/social_profile.install
modules/social_features/social_topic/social_topic.install
tests/behat/features/bootstrap/LogContext.php

Starting with Drupal 9.3.0, all permissions in a user role must be defined in a module.permissions.yml file or a permissions callback. Other permissions are now considered invalid. This includes permissions from uninstalled modules, permissions that depend on configuration that has been removed (such as a content type), and permissions of obscure origin.
In Drupal 9.3.0 or later, saving a role with an invalid permission will trigger a E_USER_DEPRECATED error. In Drupal 10, it will throw a runtime exception.
Since Drupal 8.0, modules are supposed to remove their data from the database when they are uninstalled. See [Modules cannot be in a disabled state anymore, only installed and uninstalled](https://www.drupal.org/node/2193013). One exception has been that uninstalled modules did not …

Issue #3384622 by zanvidmar: Permission must exist (D10)

---

composer.json

If try to add to user profile "Expertise" taxonomy term which label contained parentheses and then try to save profile then we get error:
Add related patch for drupal core.
- https://getopensocial.atlassian.net/browse/PROD-26084
- https://www.drupal.org/project/drupal/issues/2924783
n/a
n/a
Fix error on entity autocomplete widget if entity label contains parentheses
n/a
n/a

Issue #2924783: Fix error on entity autocomplete widget if entity label contains parentheses

---

composer.json

It is not possible to support both Drupal 9.x and 10.x in a single release of this module due to a breaking change in EncoderInterface::encode() between Symfony 4.4 (D9) and Symfony 6.2 (D10). When preparing for an upgrade to Drupal 10 we need to widen Composer version constraints to allow either 2.x or 3.x: composer require drupal/csv_serialization:^2.0 || ^3.0. This will allow the module to be automatically upgraded when you upgrade Drupal core.
Changelists:
[https://git.drupalcode.org/project/csv_serialization/-/commits/3.x?ref_t...](https://git.drupalcode.org/project/csv_serialization/-/commits/3.x?ref_type=heads)
Allow 3.x version in composer.json
https://www.drupal.org/project/social/issues/3386542
*[Required if applicable] Paste a link to the drupal.org theme issue queue item, …

Issue #3386542 by nkoporec: Update drupal/csv_serialization from 2.x to 3.x

---

composer.json

Update url_embed to provide Drupal 10 compatibility including related patches. Issues related with update: #2930457, #3386579.
We are currently running 8.x-1.0-beta1 which is not compatible with Drupal 10
Update url_embed to 2.0.0-alpha1 which is compatible with Drupal 10 and update all related patches.
**Remove patch:** 
"Embed Preview throws 403 forbidden": "https://www.drupal.org/files/issues/2023-03-17/url_embed-preview-403-3285139-10.patch" 
Fixed <a href="https://git.drupalcode.org/project/url_embed/-/commit/64596b7">here</a>.
**Remove patch:** 
"Support for Facebook/Instagram API changes - add access token settings": "https://www.drupal.org/files/issues/2021-07-14/url_embed-add-facebook-access-token-config-3177860-opensocial-2.patch"
Fixed <a …

Issue #3386579: Update url_embed to 2.0.0-alpha1

---

modules/custom/activity_creator/src/ActivityFactory.php
modules/social_features/social_activity/social_activity.tokens.inc
modules/social_features/social_comment/social_comment.tokens.inc
modules/social_features/social_content_report/social_content_report.tokens.inc
modules/social_features/social_event/social_event.tokens.inc
modules/social_features/social_follow_taxonomy/social_follow_taxonomy.tokens.inc
modules/social_features/social_group/modules/social_group_request/social_group_request.tokens.inc
modules/social_features/social_group/social_group.tokens.inc
modules/social_features/social_like/social_like.tokens.inc
modules/social_features/social_mentions/social_mentions.tokens.inc
modules/social_features/social_private_message/social_private_message.tokens.inc

Currently, on a multilingual site, when the user received a notification (for example "join_to_group") , the "Call to Action" token will be not translated.
Check a "Prefered Language" of recipients during processing `cta_button` token:
`new TranslatableMarkup('See all members', [], [langcode])`
- https://www.drupal.org/project/social/issues/3380523
- https://getopensocial.atlassian.net/browse/PROD-26247
- https://github.com/goalgorilla/cablecar/pull/563
N/A
before applying a patch:
and after:
Fixes an issue with an untranslated "Call to Action" token in email notifications for multilingual sites
N/A
N/A

Issue #3380523 by SV: Fix untranslated CTA token in email notifications for multilingual sites

---

tests/behat/features/bootstrap/EmailContext.php
tests/behat/mail-spool/.gitignore

The EmailContext mail handling was created quite some years ago. In case an email in a test didn't match, the developer only got information that there was no match, there was no useful information about what didn't match (for example that a subject wasn't found, or that a specific line didn't match).
The test steps are rewritten so that the developer gets as much actionable information as possible. This can be that a specific subject wasn't found, or that one or more lines of the body did not match. This makes it easier for the developer based on just the test output and the changes they may have made to determine where the error comes from.
Providing this information in the test output requires some new functions to be rewritten. This opportunity is used to also restructure the other …

Internal: Restructure EmailContext to provide better debug information

---

composer.json

Move Social Tour module out of the distribution and make it a contrib module. We have found this module is rarelly unused, so we decided not to provide it by default. Rather allow you to make a conscious decision to have this in your community.
1. Remove Social Tour from composer.json
2. Allow users to declare this new module in their composer.json
[3388607](https://www.drupal.org/project/social/issues/3388607)
N/A
N/A
We have moved the social_tour module as contrib module on drupal.org and have added it as a dependency in Open Social.
New module page: https://www.drupal.org/project/social_tour
The module social_tour shall now be added as dependency in project's composer.json which means after a composer install it will be moved to module/contrib folder.
The directory changes might affect …

Issue #3388607: Remove social_tour from distribution.

---

modules/social_features/social_core/social_core.info.yml
modules/social_features/social_core/social_core.install
modules/social_features/social_core/tests/modules/social_core_test/social_core_test.info.yml

<h2 id="summary-problem-motivation">Problem/Motivation</h2>
Open Social requires a lot of modules to function. However, while profiling our installation it was found that <code>admin_toolbar_tools</code> was responsible for over half of the database queries needed during an installation (~85k out of ~125k total).
Looking at the hooks for <code>admin_toolbar_tools</code> the module will also perform this expensive rebuild operation during run-time any time a content entity is created that has bundles.
<h2 id="summary-proposed-resolution">Proposed resolution</h2>
Since the menu rebuild is an expensive operation and almost all of the actions users can take on the platform that are not view will cause an entity to be inserted/updated/deleted, there's a high likely-hood that …

Issue #3385341 by Kingdutch: Uninstall admin_toolbar_tools and remove from default installation

---

modules/social_features/social_profile/src/SocialProfileTrait.php
phpstan-baseline.neon

The SocialProfileTrait is doing too many things that should probably be a specific service to fulfill a goal rather than something that performs a lot of query alters.
In the profile refactor we'll be removing most of its use, but we're not quite ready to remove it yet. We want to deprecate it in 11.x so we can work on it in [#3381156: Remove usage of SocialProfileTrait ](https://www.drupal.org/project/social/issues/3381156)and remove it in any version after 12.0.0 when we're ready for it.
https://www.drupal.org/project/social/issues/3381157
Documentation change, no tests.
Usage of `SocialProfileTrait` has been deprecated. The trait was for code-sharing in internal code and will be marked as `@internal` in 12.0.0 so that it can be refactored. There is no replacement.

Issue #3381157: Deprecate SocialProfileTrait ahead of removal

---

modules/custom/entity_access_by_field/entity_access_by_field.module
modules/social_features/social_core/social_core.module
modules/social_features/social_event/modules/social_event_max_enroll/social_event_max_enroll.module
modules/social_features/social_event/social_event.module
modules/social_features/social_follow_taxonomy/modules/social_follow_landing_page/social_follow_landing_page.module
modules/social_features/social_follow_taxonomy/modules/social_follow_tag/social_follow_tag.module
modules/social_features/social_group/modules/social_group_welcome_message/social_group_welcome_message.module
modules/social_features/social_group/social_group.module
modules/social_features/social_landing_page/social_landing_page.module
modules/social_features/social_profile/social_profile.module
phpstan-baseline.neon

Replace deprecated hook_field_widget_form_alter() with hook_field_widget_single_element_form_alter and
hook_field_widget_WIDGET_TYPE_form_alter() with
hook_field_widget_single_element_WIDGET_TYPE_form_alter
Change records: https://www.drupal.org/node/3180429
Replace deprecated hooks
[3387564](https://www.drupal.org/project/social/issues/3387564)
N/A
**old**: entity_access_by_field_field_widget_form_alter
**new**: entity_access_by_field_field_widget_single_element_form_alter
Expected result:
Unexpected result:
**old**: social_core_field_widget_form_alter
**new**: social_core_field_widget_single_element_form_alter
Expected result:
Unexpected result:
**old**: social_event_max_enroll_field_widget_form_alter
**new**: social_event_max_enroll_field_widget_single_element_form_alter
Expected …

Issue #3382821: Remove deprecated hooks

---

modules/social_features/social_event/src/Plugin/views/filter/EventDate.php

There is a fatal error on the community events page in some scenarios when Social Geolocation and Event Map is enabled. 
It's related to changes from this PR: https://github.com/goalgorilla/open_social/pull/3450
It seems that the database could not determine from which table to take the 'nid' field in the query
It happened after we added the`EventDate` filter for the view map. The same filter has `all events` view. 
- https://getopensocial.atlassian.net/browse/PROD-22452
- https://www.drupal.org/project/social/issues/3390191
- https://github.com/goalgorilla/open_social/pull/3450
N/A
Fix Event Date filter for cases when Social Geolocation and Event Map is enabled on All events page.
N/A
N/A

Issue #3390191 by v.koval: Fix error on Event Date filter when Social Geolocation and Event Map is enabled

---

modules/social_features/social_event/modules/social_event_an_enroll/src/Controller/EventAnEnrollController.php
modules/social_features/social_event/modules/social_event_managers/src/SocialEventManagersAccessHelper.php
phpstan-baseline.neon

The `Social Event Organisers` module has hardcoded `access denied` access result to event edit page if event don't have any organisers.
This breaks access results counting chain for other modules and non-organisers don't have ability to edit event.
Replace `AccessResult::forbidden()` with `AccessResult::neutral()`
- https://getopensocial.atlassian.net/browse/PROD-26652
- https://www.drupal.org/project/social/issues/3387060
n/a
n/a
Removed hardcoded `access denied` access result for events.
n/a
n/a

Issue #3387060 by vnech: Remove hardcoded "access denied" result for events

---

composer.json

Changes that were released as 12.0.0-alpha1 were built as if they were going in a minor version which causes issues in our update hook numbering. All changes in 12.0.0-alpha1 are backwards compatible, so to fix this we can also release those as 11.11.0.
This was also merged as part of 12.0.0-alpha2, however is also BC breaking, so we need to remove it from main.
This reverts commit bb95d45730c8f0d9bb3e5d267d59b2a3d571b915.

Revert "Issue #3388607: Remove social_tour from distribution."

---

composer.json
modules/social_features/social_tagging/config/install/core.entity_form_display.taxonomy_term.social_tagging.default.yml
modules/social_features/social_tagging/config/install/core.entity_view_display.taxonomy_term.social_tagging.default.yml
modules/social_features/social_tagging/config/install/field.field.taxonomy_term.social_tagging.field_category_usage.yml
modules/social_features/social_tagging/config/install/field.storage.taxonomy_term.field_category_usage.yml
modules/social_features/social_tagging/config/static/field.field.taxonomy_term.social_tagging.field_category_usage_11802.yml
modules/social_features/social_tagging/config/static/field.storage.taxonomy_term.field_category_usage_11802.yml
modules/social_features/social_tagging/config/update/social_tagging_update_11803.yml
modules/social_features/social_tagging/social_tagging.install
modules/social_features/social_tagging/social_tagging.module
modules/social_features/social_tagging/src/Form/SocialTaggingSettingsForm.php
modules/social_features/social_tagging/src/Plugin/Field/FieldFormatter/TaggingUsageFormatter.php
modules/social_features/social_tagging/src/Plugin/Field/FieldWidget/TaggingUsageWidget.php
modules/social_features/social_tagging/src/SocialTaggingService.php
modules/social_features/social_tagging/src/SocialTaggingServiceInterface.php
tests/behat/behat.yml
tests/behat/features/bootstrap/TaggingContext.php
tests/behat/features/capabilities/follow-taxonomy/follow-tags.feature

Currently we give flexibility to SM to add content tags categories.
Each category is displayed and separate field in the entity creation page and used as filter  in overviews and search.
Currently every entity that supports content tags uses the same set of categories.
When a new category is added, it becomnes available for every entity.
This has a big limitation. It is very common that a tag is relevant for events but makes no sense for Groups and the other way around.
Because of this limitation, in the past we had to create ad hoc vocabularies for some projects in order to support their migration.
We want to introduce the possibility of choosing in which entity a certain category should be displayed. 
The available options are all the entities that are available and that are enabled in …

Issue #26669: As a SM I want to decide where a content tag category should be displayed

---

.github/workflows/qualityChecks.yml

Currently we still have parts of our automation testing PHP 8.0 and running on PHP 8.0. While we have D10 requirements that need PHP 8.1.
With Drupal 10 and updates like [#3384177: Update drupal/bootstrap from 3.26 to 3.29](https://www.drupal.org/project/socialbase/issues/3384177) requiring PHP 8.1 we are going to drop support for PHP 8.0, we will do so softly as our code is still fine on PHP 8.0 however our dependencies will require it.
We are going to stop checking for PHP 8.0 support in our test suite, so we can safely require the updates that have an actual PHP 8.1 requirement.
https://www.drupal.org/project/social/issues/3396251
Check if everything is running on PHP 8.1 
Open Social will be running on PHP 8.1 as other dependencies require it, we've been PHP 8.1 ready for a long time …

Issue #3396251 by ronaldtebrake: PHP 8.1 will be required, so remove PHP 8.0 checks

---

modules/social_features/social_follow_taxonomy/social_follow_taxonomy.install

Authenticated user should be able to "Flag Follow term" and "Unflag Follow term".
Grant "Flag Follow term" and "Unflag Follow term" permissions for authenticated user for newly installed platforms. Deliberately don't update existing platforms with update hooks.
[3395680](https://www.drupal.org/project/social/issues/3395680)
N/A
N/A
Grant "Flag Follow term" and "Unflag Follow term" permissions for authenticated user for newly installed platforms. 
N/A
N/A

Issue #3395680: Improve permissions for social_follow_taxonomy

---

tests/behat/features/bootstrap/EntityTrait.php

It seems there are some false negative scenarios when behat is running and dates are being created for entities. So for now we set it to UTC, see if that makes it more stable.
You can see [below tests](https://github.com/goalgorilla/open_social/actions/runs/6650048214/job/18070757980) we're failing for:
```
Scenario: Successfully use filters for ongoing and upcoming events with today's end date # features/capabilities/event/filter-community-events.feature:29
Given users:                                                                           # Drupal\social\Behat\SocialDrupalContext::createUsers()
| name         | mail             | status | timezone | roles    |
| regular_user | some@example.com | 1      | UTC      | verified |
And events with non-anonymous author: …
```

Internal: Test hardening: Set a UTC timezone when creating dates in our behat suite

---

composer.json
modules/social_features/social_editor/social_editor.info.yml

Ckeditor4 will be deprecated from core in favor of Ckeditor5. Open Social will be moving to Ckeditor5 in the version 12, but to give the community some time in moving from 11 to 12, we can move to the contrib ckeditor which will be supported until the end of the year.
Move to contrib Ckeditor4
https://www.drupal.org/project/social/issues/3397613
We moved the ckeditor4 module from Drupal core to the contrib one. This will be supported until the end of the year and will give people some extra time in moving to Open …

Issue #3397613 - Replace the ckeditor4 core modules with the contrib one

---

composer.json
social.info.yml

The drupal/color was moved out of drupal-core and it will be removed at Drupal 10.
To keep forward to be compatible with Drupal 10, install the drupal/color and change the dependency from drupal-core to the new module.
[PROD-27283](https://getopensocial.atlassian.net/browse/PROD-27283)
[#3397252](https://www.drupal.org/project/social/issues/3397252)
N/A
N/A
When choosing colors for the Open Social theme you are able to use a color picker. This module has been removed from Drupal 10 core as they use their own interface for this. As we still use the color picker, we moved to the contrib module.
For the end-user nothing will change.
N/A
N/A
[PROD-27283]: https://getopensocial.atlassian.net/browse/PROD-27283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1K …

Issue #3397252: Moved the color module to out of Drupal-Core

---

modules/custom/social_language/modules/social_content_translation/config/modify/social_content_translation.book_translation_permissions.yml
modules/custom/social_language/modules/social_content_translation/config/modify/social_content_translation.data_policy_translation_permissions.yml
modules/custom/social_language/modules/social_content_translation/config/modify/social_content_translation.event_translation_permissions.yml
modules/custom/social_language/modules/social_content_translation/config/modify/social_content_translation.flexible_group_translation_permissions.yml
modules/custom/social_language/modules/social_content_translation/config/modify/social_content_translation.landing_page_translation_permissions.yml
modules/custom/social_language/modules/social_content_translation/config/modify/social_content_translation.page_translation_permissions.yml
modules/custom/social_language/modules/social_content_translation/config/modify/social_content_translation.topic_translation_permissions.yml
modules/custom/social_language/modules/social_content_translation/social_content_translation.info.yml

In Issue #3384622 with PR #3499 we remove the assignment of the translate permissions because these permissions don’t exist when the content translation module is not enabled and having non-existent permissions assigned is disallowed in Drupal 10.
However, from a product perspective this is problematic because when enabling features we don’t want manual work of adding permissions. The PR itself does not add any code to automatically re-assign these permissions when they exist.
Permissions:
translate book node
translate event node
translate flexible_group group
translate landing_page node
translate page node
translate topic node
translate data_policy
Automatically grant permissions listed above in the same way as before [3384622](https://www.drupal.org/project/social/issues/3384622) with …

Issue #3398931: Grant content translate permissions

---

modules/custom/entity_access_by_field/src/EntityAccessByFieldPermissions.php

The PR [#3109](https://github.com/goalgorilla/open_social/pull/3109) extended functionality of EntityAccessHelper to cover all entity types and rename method to entityAccessCheck(). However, permission definitions in the PR were not updated to apply to this logic.
Starting with Drupal 9.3.0, all permissions in a user role must be defined in a module.permissions.yml file or a permissions callback. Source: https://www.drupal.org/node/3193348
Resolve the issue by defining permissions for entity_access_field for all entity types (at the moment, permissions are defined only for node entity type).
[3397762](https://www.drupal.org/project/social/issues/3397762)
N/A
```
public|public
community|community
group|group
test|test
```
and save it.
Related to this method: …

Issue #3397762: Define entity_access_by_field permissions for all entity types

---

composer.json

In #3518 - we updated to 3.x, however just a couple of days ago: https://www.drupal.org/project/csv_serialization/issues/3396149  it shows that was reverted and we need to move to the 4.x major.
Move to the 4.x major as well.
https://www.drupal.org/project/social/issues/3386542
Make sure comment export still works.
Shouldn't change a thing as all changes we're tested in the 3.x branch already in #3518 however now with better support.
Allow the 4.x branch as well for csv_serialization for D10 compatibility.

Issue #3386542 by nkoporec part 2: Update drupal/csv_serialization to 4.x 

---

composer.json

Drush 12 support was added in the 4.0 major branch of `drupal/update_helper`, both version 3 and 4 are Drupal 10 compatible so this way we can help users with Drush, which is not an Open Social Distro requirement but a common Drupal requirement.
Make sure both version 3 and 4 are accepted, so composer can figure it out.
https://www.drupal.org/project/social/issues/3399456
See updates still pass in our behat tests.  
Allow `update_helper` version 3 and 4 for Drush 12 support.

Issue #3399456: by ronaldtebrake: Update `drupal/update_helper` In order to support Drush 12

---

modules/social_features/social_user/assets/css/views-exposed-form--admin-people.css
modules/social_features/social_user/assets/css/views-exposed-form--admin-people.css.map
modules/social_features/social_user/assets/css/views-exposed-form--admin-people.scss

The group filter field collapses incorrectly.
When the user adds tags into the group field and removes all of them, the field does not have a correct with.
Add width style to the group field.
- https://www.drupal.org/project/social/issues/3399843
- https://getopensocial.atlassian.net/browse/PROD-27023
- https://getopensocial.atlassian.net/browse/PROD-27296
N/A
Before:
After:
Improved the width of the group filter on the admin/people page.

Issue #3399843 by agami4: Improve width of the group filter on the admin/people page

---

modules/social_features/social_content_block/modules/social_event_content_block/config/install/field.field.block_content.custom_content_list.field_event_group.yml
modules/social_features/social_content_block/modules/social_event_content_block/social_event_content_block.install

I'm creating a new content list block using the layout builder. I want to select an "event content type" and also limit these event to a specific group. When trying to search for my group it never shows up in the autocomplete options.
The issue is that the flexible group type is not set as an option to be referenced for this field, so we need to add it.
https://www.drupal.org/project/social/issues/3398750
1. Enable social_event_content_block module.
2. Create a new flexible group
3. Create a new event that is part of …

Issue #3398750 by nkoporec: Can't select a group when creating a content list block and using the event content type

---

modules/social_features/social_post/src/Controller/PostCommentController.php
phpstan-baseline.neon

As part of our Drupal 10 work #3578 we've added an assertion to check if the `$element_parents` was a string or not. This because PHPStan started complaining.
Actually looking at the file shows the variable is never used so we can safely remove it as it's giving issues with creating a reply on a Post in the stream.
Should be there, the assertion just didn't fire (see post-comments.feature)
https://www.drupal.org/project/social/issues/3402403
Replying on a Post should work again, was only broken in Open Social 12.

Issue #3402403 - Replying on a Post gives an unexpected error.

---

composer.json

The Social Base is customize the CKEditor 5 layout and currently it will impacting the width limit from entity create page.
Apply a patch to fix the width layout bug.
Social issue: [#3398146](https://www.drupal.org/project/social/issues/3398146)
Social Base issue: [#3398140](https://www.drupal.org/project/socialbase/issues/3398140)
N/A
N/A
N/A
N/A

Issue #3398146: CKEditor 5 isn't respecting width limit

---

modules/custom/social_ajax_comments/social_ajax_comments.module

When a comment is created and the unpublish button isn't be setted, an error message is throwing at page.
Before to add the unpublish button, add a validation to avoid an error message
[PROD-27528](https://getopensocial.atlassian.net/browse/PROD-27528)
[#3404072](https://www.drupal.org/project/social/issues/3404072)
N/A
Create a comment in a post without unpublish button configuration
N/A
N/A
N/A
N/A
[PROD-27528]: https://getopensocial.atlassian.net/browse/PROD-27528?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Issue #3404072: PHP error when has comment on page

---

modules/social_features/social_profile/modules/social_profile_fields/src/Plugin/Validation/Constraint/UniqueNickname.php
modules/social_features/social_profile/modules/social_profile_fields/src/Plugin/Validation/Constraint/UniqueNicknameValidator.php
tests/behat/features/capabilities/profile/unique-nickname.feature

When a new user tries to register using a "Nickname" that already exists in the system, the registration fails and the user gets shown:
- Add check to prevent issue on user register page. 
- Update text of the waring message: “This name is already taken, please try another one”
- https://www.drupal.org/project/social/issues/3403776
- https://getopensocial.atlassian.net/browse/PROD-26459
N/A
N/A
Fixes the issue with "Unique nicknames" on the user register page
N/A
N/A

Issue #3403776 by SV: "Unique nicknames" setting should result in error message instead of "unexpected error" during registration

---

modules/social_features/social_comment/social_comment.tokens.inc

When the user comments on content, "topic"  (or also event, discussion, idea)  displays untranslated on the stream/email notification.
Use entity type label in related token to get translated data on the stream/email.
- https://www.drupal.org/project/social/issues/3406255
- https://getopensocial.atlassian.net/browse/PROD-27576
Before:
After:
Fixes translations of entity type name on the stream/email notification.
N/A
N/A

Issue #3406255 by SV: Display translated "commented content type" on the stream/email notification

---

.github/workflows/behat.yml
composer.json
tests/composer.json

There is a new version of `instaclick/php-webdriver` and the patch doesn't apply
Lets see if we still get CURL issues, if so we need to lock the version for now as it's blocking main and we can create a follow up to properly fix this, also with an issue in the actual instaclick/php-webdriver repo.
Internal.
Behat shouldn't get any curl issues.

Internal: There is a new version of `instaclick/php-webdriver` and the patch doesn't apply

---

modules/custom/social_ajax_comments/social_ajax_comments.module

The Social Ajax Comments module has an hook_batch_alter and thier isn't have a treatment to batch without form-state and it is throwing a php error.
Add a nullable default value to form-state variable and the form-state validation will return early.
[PROD-27607](https://getopensocial.atlassian.net/browse/PROD-27607)
[#3406311](https://www.drupal.org/project/social/issues/3406311)
N/A
**This error is happen at Enterprise environment**
N/A
N/A
N/A
N/A
[PROD-27607]: https://getopensocial.atlassian.net/browse/PROD-27607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Issue #3406311: Form State is empty at Ajax Comment hook_batch_alter

---

modules/custom/social_lets_connect/modules/social_lets_connect_usage/social_lets_connect_usage.info.yml
modules/custom/social_lets_connect/modules/social_lets_connect_usage/social_lets_connect_usage.installer_options.yml
modules/custom/social_lets_connect/social_lets_connect.install

The module social_lets_connect_usage needs to be marked as deprecated and will be removed in a next major version.
This module functionality is no longer in use, so we can deprecate it.
Write an update hook to uninstall the module and remove the configs, deprecate the module in .info.yml file.
https://www.drupal.org/project/social/issues/3406822
The module social_lets_connect_usage has been marked as deprecated and will be removed in the next major release.
The module social_lets_connect_usage has been marked as …

Issue #3406822 by nkoporec: Deprecate and remove social_lets_connect_usage

---

modules/social_features/social_content_report/src/ContentReportService.php
modules/social_features/social_follow_user/src/Service/SocialFollowUserHelper.php

This is a follow-up as we did not fix this on all places yet.
Original issue: https://www.drupal.org/node/3355315
Our socialFollowUser checks all flags for the current user, however, for AN the flag service requires a session id as per:
[https://git.drupalcode.org/project/flag/-/commit/497e170c267780dc314e0f0...](https://git.drupalcode.org/project/flag/-/commit/497e170c267780dc314e0f0ed5962ad5d89dfee7#b6b1c3c70255325ebedd7af4aceb1639bd19829b_129_180)
If not provided, it will trigger the Exception.
In our case we can use the same $this->flagService->getAnonymousSessionId to make sure it returns NULL if the user is logged in or provide a/the session ID for AN.
https://www.drupal.org/project/social/issues/3408496
*[Required if applicable] Paste a link to the drupal.org theme issue queue …

Issue #3408496 - Make sure our flagging has the correct arguments otherwise it will break profile teasers for AN.

---

modules/social_features/social_activity/src/EmailTokenServices.php

When expecting logs we found the following error, popping up multiple times:
Error: Call to a member function get() on null Drupal\\social_activity\\EmailTokenServices->getUserPreview() (line 251 of /app/html/profiles/contrib/social/modules/social_features/social_activity/src/EmailTokenServices.php)
Make sure that the field exists before calling get()
https://www.drupal.org/project/social/issues/3407056
Fixed an undefined error that occurred when sending out emails with tokens.

Issue #3407056 by nkoporec: Error: Call to a member function get() on null Drupal\\social_activity\\EmailTokenServices->getUserPreview()

---

composer.json

We added some patches, which are now released as part of https://www.drupal.org/project/socialbase/releases/2.5.11
As we didn't lock our theme(s) they are automatically added and patches are failing builds.
Remove them.
None - internal. 
None - internal. 
None - internal.

Internal: Remove socialbase patches after release of 2.5.11

---

modules/custom/activity_send/modules/activity_send_email/src/Plugin/EmailFrequency/Immediately.php

The renderRoot() should be used as a response to a controller. If we use the renderRoot or render() methods incorrectly it can produce warnings such as:
`LogicException: Render context is empty, because render() was called outside of a renderRoot() 
`
We are catching a lot of this kind of logs warnings and its related to when cron processes a queue job.
Replace renderRoot with renderPlain
https://www.drupal.org/project/social/issues/3408511
It's hard to reproduce this one, but you can try by creating a lot of …

Issue #3408511 by nkoporec: Replace renderRoot() with renderPlain() when trying to render a notifiication in an email

---

composer.json
modules/social_features/social_embed/social_embed.post_update.php
phpstan-baseline.neon

When going to the Drupal status page you will see an error message like in the screenshot below.
The url embed module did not migrate the old plugin to the new ckeditor5 but added a new plugin. This causes the old button still being available on admin/config/content/embed which is not compatible with ckeditor5. This will not create any issues but does pollute the status page.
To solve this we can remove this old button as we don't use it anymore and replaced it with the new one.
Only remove it when no text-formats are using ckeditor4 with this plugin
https://www.drupal.org/project/social/issues/3409033
*[Required if applicable] Paste a link to the drupal.org theme issue queue item, either from [socialbase](https://www.drupal.org/project/socialbase) or …

Issue #3409033 - Add an update hook to remove leftsovers of the embed_button for the ckeditor 4 to 5 migration

---

tests/behat/features/bootstrap/FeatureContext.php

Split off from #3480 out of 2b640208df7b05c79fc22c1b573e5d2aba7821b8
We usually check in a test for a certain text to be present but that doesn’t always verify that a field exists (it might be in a help text for example), so we need steps to check for form fields specifically.
https://getopensocial.atlassian.net/browse/PROD-27794

Internal: PROD-27794 - Add Behat steps to verify a field with a specific label exists

---

tests/behat/behat.yml
tests/behat/features/bootstrap/ProfileContext.php

As part of the profile refactor we added [quite comprehensive test steps around profiles](https://github.com/goalgorilla/open_social/blob/2b640208df7b05c79fc22c1b573e5d2aba7821b8/tests/behat/features/bootstrap/ProfileContext.php). We want to bring those into the distribution ahead of the profile refactor because they can be useful already.
All the steps that are not directly related to the new field management system are included:
-  When I am viewing my profile
-  When I try to view the profile of :user
-  Given user :username has a profile filled with:
-  Given I have a profile filled with:
-  Given have a profile filled with:
-  When I am editing my profile
-  When I try to edit the profile of :user
-  Given unique nickname for users is :state
-  Then unique nicknames for users should …

Internal: PROD-27796 - Add Behat test steps around profile management

---

phpstan-baseline.neon
phpstan.neon
src/PHPStan/Rules/DisallowPrivateModuleFunctions.php
tests/phpstan/data/private_function_example/private_function_example.info.yml
tests/phpstan/data/private_function_example/private_function_example.module
tests/phpstan/src/TestDisallowPrivateModuleFunctions.php

We use an underscore (`_`) to denote private methods inside a .module file since we can't give visibility modifiers for functions outside of a class. However, we tend to call those functions anyway inside of other modules.
This creates unneccessary coupling and sometimes also means APIs aren't properly used (for example usage of `_social_group_get_current_group` rather than using Drupal's context system or calling `_activity_basics_entity_action` rather than using entity conditions on the existing create/update actions). That incorrect usage makes our product more difficult to maintain and can cause performance issues.
https://getopensocial.atlassian.net/browse/PROD-27813

Internal: Add PHPStan rule for correct usage of private methods

---

composer.json
cspell.words.txt
tests/behat/features/bootstrap/SocialDrupalContext.php
tests/behat/features/capabilities/event/add-to-calendar.feature

The behat tests related to anonymous-user enrolling to an event and downloading the calendar file is falling at git-checks and locally works perfectly.
The logs show the script trying to run before the modal/form be rendered.
Create a new function to wait a field be rendered and throw an error when this fields isn't be rendered.
[PROD-27550](https://getopensocial.atlassian.net/browse/PROD-27550)
[#3410068](https://www.drupal.org/project/social/issues/3410068)
N/A
This error is hardest to reproduce locally, usually it happen at git-checks probably because is a lazy environment.
N/A
N/A
N/A
N/A
[PROD-27550]: https://getopensocial.atlassian.net/browse/PROD-27550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Issue #3410068: Behat tests falling during git-checks

---

tests/behat/features/bootstrap/SearchContext.php

When running tests backed by SOLR locally you may run into content still being in the SOLR database when the database gets reset. This is because our Behat test doesn’t clear out the SOLR database when a new MariaDB database is loaded, but we can easily do this with onDatabaseLoaded.
It can also be challenging when writing search Behat tests to make sure that text you’re searching for is part of the result set and doesn’t trigger on the search input or on a filter. For this we want to add two steps that actually look inside of the content region to exclude those other sections.
Finally we currently have a “are the search indexes up to date” step which has a custom implementation. However we can get the code for free by invoking Drush instead. That reduces the amount of code we need to …

Internal: PROD-27797 - Improve Behat support for SOLR

---

.github/workflows/behat.yml
.github/workflows/bestPractices.yml
.github/workflows/qualityChecks.yml

If someone is rapidly iterating on a PR (e.g. because they're trying to fix a workflow) then the action queue can be filled with workflows for the same PR where we no longer care about any results except the last one.
This commit uses the default GitHub concurrency of 1 workflow per ref (branch/pr/tag). The concurrency group must be specified even though it's the default, otherwise cancel-in-progress would cancel all workflow runs rather than only the ones in the current group. In case the change is for a PR (head_ref is not empty) we cancel previous in progress workflows in the group.
See https://docs.github.com/en/actions/using-jobs/using-concurrency See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
Internal CI change no issue …

Internal: Automatically cancel PR workflows on new code pushes

---

modules/social_features/social_group/config/install/views.view.group_manage_members.yml
modules/social_features/social_group/config/update/social_group_update_12101.yml
modules/social_features/social_group/social_group.install
modules/social_features/social_group/social_group.module
tests/behat/features/capabilities/groups/flexible/content/groups-flexible-manage-members-page-limit.feature

A filter should be added to the Group members overview where GM can choose how many users are displayed
As part of this story, we also want to increase the default number from 10 to 25 users.
Add a pager limit option on the manage member group page.
- https://www.drupal.org/project/social/issues/3402109
- https://getopensocial.atlassian.net/browse/PROD-26201
- https://www.drupal.org/project/socialbase/issues/3402180
Group Managers can choose how many users are shown on the Manage members overview page.

Issue #3402109 by SV: As a GM I want to choose how many users I can see in the Manage members overview page

---

modules/custom/activity_creator/src/ActivityAccessControlHandler.php

We have encountered a WSOD page when visiting a regular members profile as a SM. The error was
```
Uncaught PHP Exception Error: "Call to a member function access() on null" at /app/html/profiles/contrib/social/modules/custom/activity_creator/src/ActivityAccessControlHandler.php line 116
```
Currently activity_creator/src/ActivityAccessControlHandler.php we not gracefully handling if the related entity does not exist. We always assume that it is there, so we should add a check that verifies that the related entity indeed exists before calling a method.
https://www.drupal.org/project/social/issues/3412327
*[Required if applicable] Paste a link to the drupal.org theme issue queue item, either from [socialbase](https://www.drupal.org/project/socialbase) or …

Issue #3412327 by nkoporec: Uncaught PHP Exception Error: "Call to a member function access() on null"

---

phpstan-baseline.neon

Our PHPStan is failing in main.
Seems to be because of a recent phpstan update, which we don't lock.
Removed the ignored errors.
None: internal.
See PHPStan pass.
Fix PHPStan, removing from baseline is always nice!

Internal: Remove fixed errors from baseline

---

.github/workflows/behat.yml
tests/behat/features/bootstrap/DatabaseContext.php

Drush requires the -y flag to run in automated environments because it prompts with the list of available updates. However it also does an update requirements check which gets skipped by the same -y option.
This means that our update path in the CI doesn't fail if there are requirements errors (even though it should, because it causes errors later in tests that are hard to debug) and our tests against fixture dumps for specific update scenarios also don't fail.
Until Drush provides a better solution in
https://github.com/drush-ops/drush/issues/5806. We manually go through the update output and errors if the key sentence for requirements errors is spotted.
*[Required if applicable] Paste a link to the drupal.org theme issue queue item, either from …

Internal: Ensure Behat tests abort if updates fail with requirements errors

---

modules/social_features/social_event/modules/social_event_invite/config/install/message.template.invite_event_enrollment.yml
modules/social_features/social_event/modules/social_event_invite/config/update/social_event_invite_update_12001.yml
modules/social_features/social_event/modules/social_event_invite/social_event_invite.install

When you invite a user to an event, the user gets 2 e-mails. This looks like a bug, as the user is supposed to only receive one e-mail.
First, the user receives the correct e-mail. Then the user receives a default system e-mail (after running cron).
Disable email notification for the event invite message template and keep only one configurable by Site Manager in the Event invite settings.
- https://getopensocial.atlassian.net/browse/PROD-26510
- https://www.drupal.org/project/social/issues/3410565
N/A
N/A
Disable duplicated email notifications for the event invite message template and keep only one configurable by the Site Manager in the Event invite settings.
N/A
N/A

Issue #3410565: Disable email notification in the Invited to join a group message template

---

composer.json

https://www.drupal.org/sa-core-2024-001 has been released, we need to backport it to Drupal Core 10.0.x which we still support.
https://www.drupal.org/project/social/issues/3415447
Release https://www.drupal.org/sa-core-2024-001

Issue #3415447: Backport SA-CORE-2024-001

---

.tugboat/config.yml
.tugboat/settings.local.php

After moving to symfony mailer we need to make sure the correct settings are also provided for tugboat.
Update the config for tugboat and add a similar config object like this:
Internal
See tugboat catches mail again.

Internal: Update tugboat with symfony mailer config in settings.local.php

---

composer.json
tests/behat/features/bootstrap/GroupContext.php

```
Type error: str_contains(): Argument #1 ($haystack) must be of type string, array given in features/bootstrap/GroupContext.php:672
```
In #3712 we added
```
// @todo We might want to do add more generic approach for multi-value
// fields like "field_group_allowed_visibility".
if (isset($groupHash['field_group_allowed_visibility'])) {
$groupHash['field_group_allowed_visibility'] =
explode(',', $groupHash['field_group_allowed_visibility']);
}
```
added as part of `@Given groups:` 
However, we also have it now as part of the `private function groupCreate(array $group) {` which should work for all scenario's using this. This was added as part of the security release, as we couldn't open a public PR tests we're not running and we only noticed this later.
Additional testing uncovered an …

Internal: Fix `Behat\Testwork\Call\Exception\FatalThrowableError`

---

modules/social_features/social_group/modules/social_group_flexible_group/config/modify/social_group_flexible_group.authenticated_taxonomy_permissions.yml
modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.info.yml
modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install
modules/social_features/social_topic/config/modify/social_topic.authenticated_taxonomy_permissions.yml
modules/social_features/social_topic/social_topic.info.yml
modules/social_features/social_topic/social_topic.install

When the Taxonomy Access Fix module was enabled, the Topic and Group type don't be displayed as expected and this fields is mandatory to create new entities.
Created a new configuration modify to add this permission when the Taxonomy Access Fix module are enable.
[PROD-27790](https://getopensocial.atlassian.net/browse/PROD-27790)
[#3411006](https://www.drupal.org/project/social/issues/3411006)
N/A
N/A
N/A
N/A
N/A
[PROD-27790]: https://getopensocial.atlassian.net/browse/PROD-27790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Issue #3411006: Topic and Group type taxonomy permission missing

---

modules/custom/social_graphql/graphql/open_social.graphqls

For system-to-system APIs an external system will usually want to push some kind of update for data it knows has changed (e.g. perhaps it manages address information for users) without changing anything else. 
These changes should happen as a single efficient transaction to ensure data doesn’t end up in an unknown state, this excludes splitting mutations on a per-field level, since they’re executed independently. Additionally it’s not feasible for external systems to first request existing data because this might cause race conditions (whether those race conditions are a problem for user-facing applications is feature/application specific but because it’s a user initiated action this is much less likely a problem because the user sees the info they intend to submit).
To meet these design …

Issue #3416247: Add optional string and phone number GraphQL input types

---

.github/workflows/behat.yml
composer.json

https://www.drupal.org/project/dynamic_entity_reference/releases/3.2.0 was just released and now our patch is failing.
Lock it, so we can update the module separately and see what we need to do with the patch (and make sure we do our due dilligence on testing the update and it's full impact) this has the least amount of regression impact.
https://www.drupal.org/project/social/issues/3418006
Internal.

Issue #3418006: Lock `drupal/dynamic_entity_reference` to make sure patch still applies.

---

modules/social_features/social_activity/src/EmailTokenServices.php

In our logs we are spotting  `Error: Call to a member function hasField() on null `errors, its related to a missing profile.
Full error:
```
Error: Call to a member function hasField() on null in Drupal\\social_activity\\EmailTokenServices->getUserPreview() 
(line 252 of /app/html/profiles/contrib/social/modules/social_features/social_activity/src/EmailTokenServices.php) 
#0 /app/html/profiles/contrib/social/modules/social_features/social_group/social_group.tokens.inc(207): 
Drupal\\social_activity\\EmailTokenServices->getUserPreview(Object(Drupal\\social_user\\Entity\\User)) 
#1 /app/html/core/lib/Drupal/Core/Extension/ModuleHandler.php(545): social_group_tokens_alter(Array, Array, 
Object(Drupal\\Core\\Render\\BubbleableMetadata)) #2 …
```

Issue #3417011 by nkoporec: Error: Call to a member function hasField() on null

---

yaml_translation_patterns.yml

We have an issue with translation extraction in our Github Actions.
In [#3411529](https://www.drupal.org/i/3411529) (after/on D10.2) `field_type_categories.yml` 
translatable strings we're marked as missing from potx.
Because we're using a tagged version and this isn't released yet, we also need to make sure our yaml_translation_patterns are aware. This can be removed once we can update potx with a new released version.
TBD.
TBD. 
Internal.

Internal: Fix translation extraction after updating to Drupal 10.2

---

tests/behat/features/bootstrap/GroupContext.php
tests/behat/features/capabilities/event-management/event-management.feature
tests/behat/features/capabilities/groups/groups-mute-notify.feature
tests/behat/features/capabilities/search/search-all.feature
tests/behat/features/capabilities/search/search-groups.feature

⚠️ This should be merged after https://github.com/goalgorilla/open_social/pull/3678
⚠️ This PR is part of a set of stacked commits please do not rebase this PR but instead ping @Kingdutch
We’re in the process of removing the old group types which means their tests will start failing. Since we no longer care about the old group types we adjust the test coverage for them.
- https://www.drupal.org/project/social/issues/3380714
- https://getopensocial.atlassian.net/browse/PROD-27948
n/a
n/a
n/a
n/a
n/a
n/a
n/a

Issue #3380714: Adjust tests for old group types

---

modules/social_features/social_event/modules/social_event_invite/src/Plugin/views/field/SocialEventInviteRecipientField.php
phpstan-baseline.neon

n Drupal 10.1 the format_size function was deprecated to be removed on Drupal 11.
https://www.drupal.org/node/3311862
Replace the deprecated function, get example at: https://www.drupal.org/node/3311862
[PROD-28011](https://getopensocial.atlassian.net/browse/PROD-28011)
N/A
N/A
N/A
N/A
N/A
N/A
[PROD-28011]: https://getopensocial.atlassian.net/browse/PROD-28011?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Issue #3418896: Replace EntityTranslationRenderTrait::getEntityTranslation deprecated function

---

modules/custom/download_count/src/Plugin/Field/FieldFormatter/FieldDownloadCount.php
phpstan-baseline.neon

In Drupal 10.2 the format_size function was deprecated to be removed on Drupal 11.
https://www.drupal.org/node/2999981
Replace the deprecated function, get example at: https://www.drupal.org/node/2999981
[PROD-28010](https://getopensocial.atlassian.net/browse/PROD-28010)
[#3418731](https://www.drupal.org/project/social/issues/3418731)
N/A
N/A
N/A
N/A
N/A
N/A
[PROD-28010]: https://getopensocial.atlassian.net/browse/PROD-28010?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Issue #3418731: Replace format_size deprecated function

---

modules/social_features/social_core/src/Controller/SocialCoreController.php
modules/social_features/social_core/src/Routing/RouteSubscriber.php

After updating to views_bulk_operations 4.2.6, we noticed the actual selection wasn't updating anymore correctly this blocked the bulk operations action button. On top of that we have a selection message which talks about members but this callback is used for every bulk operations, including content and more. We need beter ways of fixing it. 
Deprecate this callback, and move to ViewsBulkOperationsController's variant. This fixes the blocking updateSelection issue (see screenshot of how the button and selection isn't matching)
https://www.drupal.org/project/social/issues/3419770
All bulk operations should work again.
https://www.drupal.org/node/3419810

Issue #3419770 - Remove our custom views bulk operations update selection callback

---

modules/social_features/social_group/config/install/core.entity_view_mode.group.medium_teaser.yml
modules/social_features/social_group/config/update/social_group_update_13003.yml
modules/social_features/social_group/social_group.install

We need to have the medium teaser for one of the group types. But, it's better to place this teaser in the `social_group` module, since in the future we can reuse this teaser for any group type
Place config of medium teaser view mode in `config/install `and add` hook_update_N`
https://www.drupal.org/project/social/issues/3419584
N/A
Clean install:
Update:
Add medium teaser view mode for groups
N/A
N/A

Issue #3419584: Add medium teaser view mode for groups

---

modules/social_features/social_group/social_group.api.php
modules/social_features/social_group/src/SocialGroupHelperServiceInterface.php
phpstan.neon

⚠️ This PR is part of [a set of stacked-PRs](https://newsletter.pragmaticengineer.com/p/stacked-diffs). *Do not* use the rebase button, but instead rebase the branch of the last PR in the series [using `git rebase --update-refs`](https://andrewlock.net/working-with-stacked-branches-in-git-is-easier-with-update-refs/) ⚠️ 
We'll be removing the function as part of [#3420020: [13.0.0] Remove Drupal\social_group\SocialGroupHelperService::getDefaultGroupVisibility](https://www.drupal.org/project/social/issues/3420020) but want to make sure people are aware that it will disappear.
Deprecate the function in the next minor version to inform people of its pending removal.
https://www.drupal.org/project/social/issues/3420022
`Drupal\social_group\SocialGroupHelperService::getDefaultGroupVisibility` …

Issue #3420022: Deprecate Drupal\social_group\SocialGroupHelperService::getDefaultGroupVisibility

---

modules/social_features/social_core/social_core.install
modules/social_features/social_post/config/install/views.view.posts.yml
modules/social_features/social_post/social_post.install
modules/social_features/social_post/social_post.links.action.yml
modules/social_features/social_post/social_post.links.menu.yml
modules/social_features/social_post/src/Entity/Post.php

The post overview `/admin/content/post` is ordered by oldest first.
This is inconsistent with our other overviews and it is not very handy for site managers.
- As a SM I want to see the latest post first
- Column name “Operations”is renamed “Actions”
- Status options are capital “published” → “Published” , “unpublished” → “Unpublished”
The `/admin/content/post` page is an entity collection. So, we need to create a view and use it instead to add any customization.
- https://getopensocial.atlassian.net/browse/PROD-27190
- https://www.drupal.org/project/social/issues/3418595
- https://github.com/goalgorilla/cablecar/pull/1065
n/a
Change default order in the post overview to show the newest first.
Also added ability to sort by other columns.

Issue #3418595: Replace post entity collection with views and show newest posts first

---

modules/social_features/social_group/src/GroupContentVisibilityUpdate.php
phpstan.neon

⚠️ This PR is part of [a set of stacked-PRs](https://newsletter.pragmaticengineer.com/p/stacked-diffs). *Do not* use the rebase button, but instead rebase the branch of the last PR in the series [using `git rebase --update-refs`](https://andrewlock.net/working-with-stacked-branches-in-git-is-easier-with-update-refs/) ⚠️ 
Should be merged after #3751
This class will be removed in [#3420069: [13.0.0] Remove the ability to change a group bundle type](https://www.drupal.org/project/social/issues/3420069)
Deprecate the class in a minor version before its removal.
https://www.drupal.org/project/social/issues/3420071
`Drupal\social_group\GroupContentVisibilityUpdate` is deprecated and will be removed in Open Social 13.0.0
https://www.drupal.org/node/3420118

Issue #3420071: Deprecate Drupal\social_group\GroupContentVisibilityUpdate

---

modules/social_features/social_group/src/Form/SocialGroupAddForm.php
phpstan.neon

⚠️ This PR is part of [a set of stacked-PRs](https://newsletter.pragmaticengineer.com/p/stacked-diffs). *Do not* use the rebase button, but instead rebase the branch of the last PR in the series [using `git rebase --update-refs`](https://andrewlock.net/working-with-stacked-branches-in-git-is-easier-with-update-refs/) ⚠️ 
Should be merged after #3752
The class will be removed in [#3420070: [13.0.0] Remove Drupal\social_group\Form\SocialGroupAddForm](https://www.drupal.org/project/social/issues/3420070)
Deprecate the class in a minor version before its removal.
https://www.drupal.org/project/social/issues/3420072
`Drupal\social_group\Form\SocialGroupAddForm` is deprecated and will be removed in Open Social 13.0.0
https://www.drupal.org/node/3420122

Issue #3420072: Deprecate Drupal\social_group\Form\SocialGroupAddForm

---

modules/social_features/social_group/social_group.module
modules/social_features/social_group/src/SocialGroupHelperService.php
modules/social_features/social_group/src/SocialGroupHelperServiceInterface.php
phpstan-baseline.neon
phpstan.neon

⚠️ This PR is part of [a set of stacked-PRs](https://newsletter.pragmaticengineer.com/p/stacked-diffs). Do not use the rebase button, but instead rebase the branch of the last PR in the series [using git rebase --update-refs](https://andrewlock.net/working-with-stacked-branches-in-git-is-easier-with-update-refs/) ⚠️
Should be merged after https://github.com/goalgorilla/open_social/pull/3754
getDefaultGroupVisibility was used to find the default visibility for the different group types that we have. However, as part of [#3380714: Remove support for public_group, open_group, closed_group, and secret_group and migrate to flexible_group](https://www.drupal.org/project/social/issues/3380714) we're removing all the old group types. This means the function no longer serves a purpose.
Remove the …

Issue #3420020: [13.0.0] Remove  Drupal\social_group\SocialGroupHelperService::getDefaultGroupVisibility

---

modules/social_features/social_profile/src/Plugin/Field/FieldWidget/SocialProfileTagSplitWidget.php

We want to programetically render a form that contains that uses the SocialProfileTagSplitWidget widget, the #options array is populated later (after rendering the initial form). The problem is that the field is not being rendered correctly as within the widget we are returning an empty array if there are no #options. I think this should not be the case and the widget should return the basic structure of the element.
Don't return an empty array if the #options are empty but rather return the already build element array.
https://www.drupal.org/project/social/issues/3415090
1. Create a form that uses SocialProfileTagSplitWidget
2. Try to render the form programetically but don't populate the #options of the widget.
3. Render the form and check if the widget is rendered.
Fixed an issue with …

Issue #3415090 by nkoporec: SocialProfileTagSplitWidget is not being rendered if the #options is empty

---

modules/social_features/social_profile/config/modify/social_profile.anonymous_taxonomy_permissions.yml
modules/social_features/social_profile/config/modify/social_profile.authenticated_taxonomy_permissions.yml
modules/social_features/social_profile/modules/social_profile_fields/config/modify/social_profile_fields.anonymous_taxonomy_permissions.yml
modules/social_features/social_profile/modules/social_profile_fields/config/modify/social_profile_fields.authenticated_taxonomy_permissions.yml
modules/social_features/social_profile/modules/social_profile_fields/social_profile_fields.install
modules/social_features/social_profile/modules/social_profile_organization_tag/config/modify/social_profile_organization_tag.anonymous_taxonomy_permissions.yml
modules/social_features/social_profile/modules/social_profile_organization_tag/config/modify/social_profile_organization_tag.authenticated_taxonomy_permissions.yml
modules/social_features/social_profile/modules/social_profile_organization_tag/social_profile_organization_tag.install
modules/social_features/social_profile/social_profile.info.yml
modules/social_features/social_profile/social_profile.install

The taxonomy fields from Registration page isn't working as expected.
Created a configuration-modify to add the permission when some modules is enabled.
[PROD-27744](https://getopensocial.atlassian.net/browse/PROD-27744)
[#3409546](https://www.drupal.org/project/social/issues/3409546)
N/A
N/A
Internal: For the SaaS version of Open Social we are having some issues with permissions for a registration module in combination with taxonomy. Because there is at the moment no better place where the code can live we have added it to the Distro. 
This should not affect your installation unless you also have added the drupal/taxonomy_access_fix as a dependency.
N/A
N/A
[PROD-27744]: https://getopensocial.atlassian.net/browse/PROD-27744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJ …

Issue #3409546: Missing permission to taxonomies for all users

---

modules/social_features/social_user/config/install/core.entity_view_display.user.user.default.yml
modules/social_features/social_user/config/install/core.entity_view_display.user.user.full.yml
modules/social_features/social_user/config/update/social_user_update_13000.yml
modules/social_features/social_user/social_user.install

https://www.drupal.org/project/social/issues/3420091
The references to specific group types have been removed from the user view modes in `social_user`.

Issue #3420091: Remove references to public_group, open_group, closed_group, and secret_group for social_user module

---

modules/social_features/social_search/config/install/search_api.index.social_all.yml
modules/social_features/social_search/config/install/search_api.index.social_groups.yml
modules/social_features/social_search/config/install/views.view.search_all.yml
modules/social_features/social_search/config/install/views.view.search_groups.yml
modules/social_features/social_search/config/update/social_search_update_13002.yml
modules/social_features/social_search/social_search.install

https://www.drupal.org/project/social/issues/3420093
The references to specific group types have been removed from the user view modes in social_search.

Issue #3420093: Remove references to public_group, open_group, closed_group, and secret_group for social_search module

---

modules/social_features/social_group/social_group.module

We must differentiate between group members and non-members at the newly created medium teaser view mode on social_group, added on PR #3748.
Unfortunately `hook_preprocess_group()` implemented at `social_group_preprocess_group()` has a partial implementation of this feature, [where here it defined "joined" as FALSE](https://github.com/goalgorilla/open_social/blob/main/modules/social_features/social_group/social_group.module#L252) but never changes its value. 
This causes our templates to have a "NULL" value thus we cannot verify it in our new teaser template. 
https://git.drupalcode.org/project/socialbase/-/merge_requests/201/diffs#505b7cf7a07a2932a54dbb7c314f900a81672244_0_93
This is also an old bug because [group--teaser.html.twig](https://git.drupalcode.org/project/socialbase/-/blob/2.4 …

Issue #3420647: Fix $variables['joined'] on preprocess template

---

modules/social_features/social_landing_page/config/install/core.entity_view_display.node.landing_page.default.yml
modules/social_features/social_landing_page/config/install/core.entity_view_display.node.landing_page.featured.yml
modules/social_features/social_landing_page/config/install/core.entity_view_display.node.landing_page.teaser.yml
modules/social_features/social_landing_page/config/update/social_landing_page_update_130000.yml
modules/social_features/social_landing_page/social_landing_page.install

https://www.drupal.org/project/social/issues/3420095
The references to specific group types have been removed from the user view modes in `social_landing_page`.

Issue #3420095: Remove references to public_group, open_group, closed_group, and secret_group for social_landing_page module

---

modules/social_features/social_book/config/optional/core.entity_view_display.node.book.activity.yml
modules/social_features/social_book/config/optional/core.entity_view_display.node.book.activity_comment.yml
modules/social_features/social_book/config/optional/core.entity_view_display.node.book.hero.yml
modules/social_features/social_book/config/optional/core.entity_view_display.node.book.search_index.yml
modules/social_features/social_book/config/optional/core.entity_view_display.node.book.small_teaser.yml
modules/social_features/social_book/config/update/social_book_update_130000.yml
modules/social_features/social_book/modules/social_book_featured/config/optional/core.entity_view_display.node.book.featured.yml
modules/social_features/social_book/social_book.install
modules/social_features/social_book/src/Plugin/Block/GroupAddBookBlock.php

https://www.drupal.org/project/social/issues/3420098
The references to specific group types have been removed from the user view modes in `social_book`.

Issue #3420098: Remove references to public_group, open_group, closed_group, and secret_group for social_book module

---

modules/social_features/social_post/src/PostAccessControlHandler.php
phpstan-baseline.neon

https://www.drupal.org/project/social/issues/3420103
The references to specific group types have been removed from the user view modes in `social_post`.

Issue #3420103: Remove references to public_group, open_group, closed_group, and secret_group for social_post module

---

composer.json
modules/social_features/social_event/config/install/views.view.event_enrollments.yml
modules/social_features/social_event/config/update/social_event_update_121001.yml
modules/social_features/social_event/social_event.install

The All Enrollments link from an Event page is broken and Verified User isn't be possible to access clicking on it.
That error was found during regression test for Drupal upgrade #3414795.
We was used the footer section to save more links and after Drupal upgrade it start to broken, we need to use the custom more link section to save it.
[PROD-28086](https://getopensocial.atlassian.net/browse/PROD-28086)
[#3416326](https://www.drupal.org/project/social/issues/3416326)
N/A
N/A
Internal:
The Drupal 10.2 removed an variable/feature from View module breaking the read more link in our enrollment view.
This was already fixed in Open Social with a patch, but now fixed in a proper way.
N/A
N/A
[PROD-28086]: https://getopensocial.atlassian.net/browse/PROD-28086?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …

Issue #3416326: All Enrollments link has broken to Verified User

---

modules/social_features/social_featured_content/config/install/core.entity_view_display.node.event.featured.yml
modules/social_features/social_featured_content/config/install/core.entity_view_display.node.topic.featured.yml
modules/social_features/social_featured_content/config/optional/core.entity_view_display.node.page.featured.yml
modules/social_features/social_featured_content/config/update/social_featured_content_update_13000.yml
modules/social_features/social_featured_content/social_featured_content.install

https://www.drupal.org/project/social/issues/3420101
The references to specific group types have been removed from the user view modes in `social_featured_content`.

Issue #3420101: Remove references to public_group, open_group, closed_group, and secret_group for social_featured_content module

---

modules/custom/activity_basics/activity_basics.module

If I create a topic, event, etc. in a group and save it first as a draft (disabling the "published" checkbox), it will not generate a notification for members of the group when it is later updated to be published.
This is also reproducible when using the scheduler extension, no notification is sent when the content inside the group is published later on.
- If `entity`, which has relation to `group_content` created unpublished we should not create any activities for message templates that have group_content as trigger entity;
- And vise versa - if `entity` become published (or create as published) we should create activities for message templates that have `group_content` as trigger entity;
- https://getopensocial.atlassian.net/browse/PROD-26551
- …

Issue #3422694: Send notification for group content that become published

---

modules/social_features/social_core/social_core.install

The 'administer site configuration' permission should granted to site-manager role to manage DNS information.
For new installation already have a function to be granted, but, we need to guaranteed to all old installation.
Create a hook-update to grant 'administer site configuration' permission to site-manager role.
[PROD-28386](https://getopensocial.atlassian.net/browse/PROD-28386)
[#3424719](https://www.drupal.org/project/social/issues/3424719)
N/A
N/A
We fixed an issue to make sure the site-managers have the permissions "administer site configuration". This was already working for new installations but not existing ones.
N/A
N/A
[PROD-28386]: https://getopensocial.atlassian.net/browse/PROD-28386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Issue #3424719: Add 'administer site configuration' permission to site-manager role

---

modules/custom/social_language/config/update/social_language_update_12201.yml
modules/custom/social_language/social_language.install

Currently we have a cron to get new translation and it's ran each 15 minutes, looking to improve our performance we can change it to run 1 time per day.
Created a hook-update to change the frequency in installed system and added a logic to change it when the Social Language i will enable in new installation.
[PROD-28138](https://getopensocial.atlassian.net/browse/PROD-28138)
[#3424659](https://www.drupal.org/project/social/issues/3424659)
N/A
N/A
We have changed the fetching of new translations from 15 minutes to 1 day when you have the multilingual module enabled. 15 min creates unnecessary stress on the cron-jobs and in practice 1 day is more then enough to keep a site up to date with the latest translations.
N/A
N/A
[PROD-28138]: …

Issue #3424659: Change cron to get translation to run one time per day

---

modules/social_features/social_event/src/Plugin/views/filter/EventDate.php
tests/behat/features/capabilities/event/filter-community-events.feature

Events that started and ended in the same day are not displayed in community events page
The custom-filter view isn't built correctly, fix it to return past events.
[PROD-28258](https://getopensocial.atlassian.net/browse/PROD-28258)
[#3423273](https://www.drupal.org/project/social/issues/3423273)
N/A
**I advice to create a couple of past events with different dates and using all day as well and check Community Events page.**
N/A
We fixed an issue where the past events would not show up in the event overview if the end and start date would be the previous day in combination with different timezones.
N/A
N/A
[PROD-28258]: https://getopensocial.atlassian.net/browse/PROD-28258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Issue #3423273: Past events isn't be showing at Community Events page

---

modules/custom/social_graphql/src/GraphQL/EntityConnection.php
src/Installer/OptionalModuleManager.php
tests/behat/features/bootstrap/AlbumContext.php
tests/behat/features/bootstrap/BookContext.php
tests/behat/features/bootstrap/TaggingContext.php

There's various cases in the codebase where a string is created and a variable is interpolated (e.g. <code>"Something like {$foo}"</code> where this happens incorrectly (i.e. <code>"Something like ${$foo}"</code>) which causes the contents of the variable to be used as name of a different variable that's then interpolated.
After internal investigation we find that none of the 5 occurrences found provide the ability to leak sensitive data and thus we do not consider this a security issue.
Three times in test code.
<ul>
<li>tests/behat/features/bootstrap/TaggingContext.php</li>
<li>tests/behat/features/bootstrap/BookContext.php</li>
<li>tests/behat/features/bootstrap/AlbumContext.php</li>
</ul> …

Issue #3427607 by slowflyer, Kingdutch: Variables are incorrectly output in strings causing them to be interpolated as different variables

---

modules/social_features/social_core/config/modify/social_core.system_performance_maximum_age.yml
modules/social_features/social_core/social_core.install
tests/behat/features/bootstrap/Chrome/ChromeDriver.php
tests/behat/features/bootstrap/FeatureContext.php
tests/behat/features/bootstrap/TopicContext.php
tests/behat/features/capabilities/contentmanagement/default-visibility.feature
tests/behat/features/capabilities/contentmanagement/node-visibility.feature
tests/behat/features/capabilities/embed/embed-consent.feature
tests/behat/features/capabilities/topic/newest-topics.feature

The default `cache.page.max_age` isn't configured and the default value is 0, change it to 1 hour to increase our performance.
1. Create a hook-update to set 1 hour for cache maximum age when it's empty and create a configuration modify to new installation being with 1 hour as default cache maximum age.
2. Fix behat tests
Expanding on that a bit more, as you can see it's quite the change.
The biggest issue is that we currently have a lot of places where we now encounter browser cache.
This is because `FinishResponseSubscriber`
```
if ($is_cacheable && $this->config->get('cache.page.max_age') > 0) {
if (!$this->isCacheControlCustomized($response)) {
// Only add the default Cache-Control header if the controller did not
// specify one on the response.
$this->setResponseCacheable($response, …
```

Issue #3423900: Set default cache maximum age with 1 hour

---

modules/social_features/social_core/assets/css/preview-el.css
modules/social_features/social_core/assets/css/preview-el.scss
modules/social_features/social_core/assets/css/preview-popup.css
modules/social_features/social_core/assets/css/preview-popup.scss
modules/social_features/social_core/assets/js/preview-popup.js
modules/social_features/social_core/social_core.libraries.yml
modules/social_features/social_core/templates/preview-popup.html.twig

The preview popup implementation will be used in other modules
**Back-end:**
1) First of all, we need to create a new view mode, for `preview`. It should be called `preview`, with id `preview.` - For example -  `core.entity_view_mode.group.preview.yml`
2) For this view mode, we need to create a `view_display` config, this is where we will add the fields that will be displayed on the popup - For example - `core.entity_view_display.group.flexible_group.preview.yml`
3) Then, we should create a `route`. It should be a dynamic route that accepts the id of the entity, the fields of which should be displayed in the popup. For example, the route might look like this:
```
my_module_preview.canonical:
path: '/group/{group}/preview'
defaults:
_entity_view: 'group.preview'
_title: 'Group preview' …
```

Issue #3423452: Preview popup library

---

modules/social_features/social_content_block/src/ContentBuilder.php
modules/social_features/social_content_block/src/ContentBuilderInterface.php

In distro we have a `social_content_block.content_builder `service used in "Custom content list block" feature.
Unfortunately, if I want to decorate the service behaviour (for example, add a custom entity to "Custom content list block") I can't do it because `__construct() `method is declared in `\Drupal\social_content_block\ContentBuilderInterface` rather then in `\Drupal\social_content_block\ContentBuilder`
- Remove `\Drupal\social_content_block\ContentBuilderInterface::__construct()`
- https://www.drupal.org/project/social/issues/3427532
- https://getopensocial.atlassian.net/browse/PROD-28503
For developers:
- The service 'social_content_block.content_builder' is open for decoration.

Issue #3427532 by vnech: As a developer I should be able to decorate "social_content_block.content_builder" service

---

modules/social_features/social_content_block/src/ContentBuilder.php

When you creating a **Custom content list** block you get an error if switch options in **Sorting** field:
**Steps to reproduce**:
- Login as admin
- Go to _/block/add/custom_content_list_ page
- Chose "Event" in **Type of content** field
- Chose "Oldest -> Newest" in **Sorting** field
- Chose "Topic" in **Type of content** field
- AB: you will see error in **Sorting** field
Add` #process` callback function to `field_sorting` field to reassign values
- https://www.drupal.org/project/social/issues/3431288
- https://getopensocial.atlassian.net/browse/PROD-28328
Prevent wrong sorting option set on "Custom content list" block.

Issue #3431288 by vnech: Prevent wrong sorting option set on "Custom content list" block

---

modules/social_features/social_core/social_core.module
modules/social_features/social_core/src/Routing/RouteSubscriber.php

Content and Site managers see a bar with details and revisions on top of landing pages.
Those blocks should not appear there since they have no use.
We agreed to implement fix in `social_core_menu_local_tasks_alter()` and  hide the "Revisions" tab if the node doesn't have any revisions.
The reason why revoking individual permissions is not working is that they are not used in code for access to the revision tab. They are controlled by `View all revisions` permission, but revoking it will still not fix the issue.
Unfortunately `Administer content` permission is responsible for showing the tab. This is a very important permission that we can not remove at the moment but we will do it during the permission epic during the year.
- https://getopensocial.atlassian.net/browse/PROD-25225
- …

Issue #3417172: Hide revisions tab

---

composer.json

The custom color isn't be applied to logged user on Search page, a patch with fix was created at [#3427426](https://www.drupal.org/project/socialblue/issues/3427426)
Apply patch to fix SocialBlue theme bug
[PROD-28354](https://getopensocial.atlassian.net/browse/PROD-28354)
[#3431340](https://www.drupal.org/project/social/issues/3431340)
[#3427426](https://www.drupal.org/project/socialblue/issues/3427426)
**This errors isn't happen to all installation.**
N/A
The bug about custom-color on Search Page will be fixed.
N/A
N/A
[PROD-28354]: https://getopensocial.atlassian.net/browse/PROD-28354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Issue #3431340: Apply patch to fix SocialBlue theme bug

---

modules/social_features/social_follow_user/social_follow_user.links.menu.yml
modules/social_features/social_follow_user/src/Form/SocialFollowUserSettingsForm.php

The configuration page to enable Follow User from Social Follow User module is in Administrator menu, but, ins't in Dashboard Configuration menu.
The site-managers don't have a menu to access this page, only by url.
Add a menu for Configuration Follow User to Dashboard Configuration.
Menu should be: Dashboard -> Configuration -> Follow user settings
[PROD-28519](https://getopensocial.atlassian.net/browse/PROD-28510)
[#3427929](https://www.drupal.org/project/social/issues/3427929)
N/A
N/A
The Follow Uset Settings was added to Dashboard -> Configuration menu and it will be visible to site-manager user.
N/A
N/A
[PROD-28519]: https://getopensocial.atlassian.net/browse/PROD-28519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Issue #3427929: Add Configuration Page from Social Follow User to Dashboard Configuration Menu

---

modules/social_features/social_event/config/install/views.view.event_enrollments.yml
modules/social_features/social_event/config/update/social_event_update_121002.yml
modules/social_features/social_event/modules/social_event_max_enroll/social_event_max_enroll.module
modules/social_features/social_event/social_event.install
modules/social_features/social_event/social_event.tokens.inc
tests/behat/features/capabilities/event-an-enroll/event-max-enroll.feature
tests/behat/features/capabilities/event-management/event-management.feature
tests/behat/features/capabilities/event/eventenrollment.feature

In the view for enrollments we show the @total count from the summary result. Because this item amount is set at 12 it will never go higher than 12. 
Replace it with another token to get the correct count.
- Add a custom token and use the helper method getAllEventEnrollments to get the enrollment count.
- Also set the translatable text inside the token so we can properly do plural formatting.
- Replace this token in the view.
https://www.drupal.org/project/social/issues/3428255
We fixed an issue for events that had more than 12 people enrolled. On the event detail page it would always show 12 enrollments. This should now show correct total amount of enrollees. Also we fixed the plural grammar error when only 1 person has enrolled.

Issue #3428255: Event enrollments block shows incorrect amount of enrollees.

---

modules/social_features/social_embed/src/Plugin/Filter/SocialEmbedConvertUrlToEmbedFilter.php
modules/social_features/social_embed/src/Plugin/Filter/SocialEmbedUrlEmbedFilter.php

The error is coming from [modules/social_features/social_embed/src/Plugin/Filter/SocialEmbedConvertUrlToEmbedFilter.php · 12.2.1 · project / social · GitLab](https://git.drupalcode.org/project/social/-/blob/12.2.1/modules/social_features/social_embed/src/Plugin/Filter/SocialEmbedConvertUrlToEmbedFilter.php?ref_type=tags#L334) 
This is happening because there is no such class Error is included in use statements.
There is a PR [Issue #3421184: Fix incorrect URL embedding by VBaldych · Pull Request #3761 · goalgorilla/open_social](https://github.com/goalgorilla/open_social/pull/3761/files#diff-930ea15439126c4fd87c69f98415d34cc9788b3a00b8cecd11bf3e5d5ea9f651)  here shows that the class use Drupal\Core\Utility\Error; is present
But in [Issue #3421184: Fix incorrect URL embedding (05cd0361) · …

Issue #3421184: Unexpected error on Social embed

---

modules/social_features/social_activity/social_activity.module
modules/social_features/social_album/social_album.module
modules/social_features/social_book/social_book.module
modules/social_features/social_core/social_core.module
modules/social_features/social_event/social_event.module
modules/social_features/social_follow_content/social_follow_content.module
modules/social_features/social_follow_taxonomy/social_follow_taxonomy.module
modules/social_features/social_group/social_group.module
modules/social_features/social_landing_page/social_landing_page.module
modules/social_features/social_private_message/social_private_message.module
modules/social_features/social_profile/social_profile.module
modules/social_features/social_topic/social_topic.module
modules/social_features/social_user/social_user.module

After [#3418484](https://www.drupal.org/project/social/issues/3418484) some menus start to show to user without permission.
Add validation to check permission to the menu.
[PROD-28618](https://getopensocial.atlassian.net/browse/PROD-28618)
[#3433028](https://www.drupal.org/project/social/issues/3433028)
N/A
**Make test with diferent roles to check the permissions**
1. Notification Center
2. Social Album
3. Social Book
4. Invites
5. Social Events
6. Social Follow Content
7. Social Follow Taxonomy Term
8. Social Group
9. Social Landing Page
10. Social Page
11. Social Private Message
12. Social Profile
13. Social Topic
N/A
This will fix menu link showing for user without permissions.
N/A
N/A
[PROD-28618]: https://getopensocial.atlassian.net/browse/PROD-28618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVm …

Issue #3433028: Some menus are showing to the user without permission

---

modules/social_features/social_user/social_user.routing.yml
tests/behat/features/capabilities/account/my-settings-page.feature

Currently, there is no easy way for users to go to their settings page unless they know their User ID, given that the path to the original route is `/user/{user}/edit`. It makes the UX to be somehow degraded.
The solution is to create a custom route `/my-settings` which redirects the users to their settings page, so they don't need to think about it.
The same approach is already applied to other extensions (eg. `/my-invites` and `/my-events`).
- https://www.drupal.org/project/social/issues/3432109
- https://getopensocial.atlassian.net/browse/PROD-28573
N/A
N/A
N/A
N/A
N/A

Issue #3432109: Add new route `/my-settings` to redirect users to their settings page

---

modules/social_features/social_group/social_group.install

The Social Group is enable by default, but, some installation haven't bulk-action on people page to add to a group.
The code enabling the bulk-action was removed a couple version ago.
Comeback with the code, but add a validation to ignore installations with bulk-action already be enabled.
[PROD-28567](https://getopensocial.atlassian.net/browse/PROD-28567)
[#3436178](https://www.drupal.org/project/social/issues/3436178)
N/A
N/A
Add bulk user to group in be added and will be available for installation missing it.
N/A
N/A
[PROD-28567]: https://getopensocial.atlassian.net/browse/PROD-28567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Issue #3436178: Group bulk-action is not enable for everyone

---

modules/custom/activity_send/modules/activity_send_email/src/Plugin/EmailBuilder/ActivitySendEmailBuilder.php
modules/social_features/social_event/modules/social_event_managers/src/Form/SocialEventManagersAddEnrolleeForm.php

When processing activities such as creating a post in the stream it will send out emails. When there is no subject pre-defined it will will use the default `Notification from %site_name`, but the % placeholder when processed will surround the text with the HTML` <em class="placeholder">`. Since email subject html rendering can be different per email provider it can happen that this will show the HTML as raw.
Change the placeholder % to @ as this is similar to % but without the rendering of the HTML tag.
[PROD-28384](https://getopensocial.atlassian.net/browse/PROD-28384)
[#3428454](https://www.drupal.org/project/social/issues/3428454)
N/A
N/A
The Notification emails will stop to send <em> html tag at subject.
N/A
Notification from %site_name -> Notification from @site_name
[PROD-28384]: …

Issue #3428454: Email subject with <em> html tag

---

tests/behat/features/bootstrap/EntityTrait.php

This commit allows group reference data to be provided as a comma separated list of IDs or term names (mixing is allowed). This can now be used in tables for e.g. groups, topics and events. By putting this in the validate method we can use this everywhere.
This ensures we deduplicate the group title lookup so that we don't break on a pre-fetched value. Since we now do it by field type we no longer need to do it by field name.
```cucumber
Given groups:
| label |
| Cats  |
| Birds |
And groups:
| label   | field_related_groups |
| Dogs    | 1,Birds              |
| Snakes  | 1,2                  |
| Rabbits | Cats,Birds           |
```
Inspired by: [3394](https://github.com/goalgorilla/open_social/pull/3394)
[3436789](https://www.drupal.org/project/social/issues/3436789#)
N/A

Internal: Improve test fixture creation for group references

---

modules/social_features/social_event/modules/social_event_max_enroll/social_event_max_enroll.module
modules/social_features/social_event/social_event.tokens.inc
modules/social_features/social_event/src/EventEnrollmentStatusHelper.php

The enrollments count from Event page is showing all enrollments without check the status for invite or pending request.
Removed parameters to ignore status from events
[PROD-28692](https://getopensocial.atlassian.net/browse/PROD-28692)
[#3437440](https://www.drupal.org/project/social/issues/3437440)
N/A
Fixed the enrollments count from event page.
N/A
N/A
[PROD-28692]: https://getopensocial.atlassian.net/browse/PROD-28692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Issue #3437440: Block with enrollments from Event page is showing wrong count

---

cspell.words.txt
modules/social_features/social_core/config/static/views.view.message_123003.yml
modules/social_features/social_core/social_core.install

In a recent Open Social update the message module went from 1.4 to 1.5. This introduced a change in a view with update hook message_update_8105.
This assumes you have the views.view.message but in our case we noticed that some did not have it, likely due to a corruption in a past Open Social update. This causes the view to be partially created with just the parameters from the update hook. This can then cause a WSOD.
We need to re-import the view. Because not everyone might have this issue we also need to check if the view is corrupt before re-importing.
https://www.drupal.org/project/social/issues/3439399
Internal: We fixed an issue where the message module view would be corrupt as it did not exist and partially imported. This crashes the page with a WSOD. 
PS Which can be solved with a …

Issue #3439399: Message module view corrupt after update in some cases

---

modules/social_features/social_event/config/update/social_event_update_121003.yml
modules/social_features/social_event/config/update/social_event_update_121004.yml
modules/social_features/social_event/social_event.install

The social event update hook 121001 and 121002 are bugfixes to the view enrollments, but inside the expected config it contains some strings like use_more_text: 'All enrollments'
In some cases it can be that multilingual platform have this string in a different language. This causes the update to not be executed and the bug persists on the platform. Even though base strings should be english we should take this into account.
Remove the expected config to make sure they get executed.
Given this being an issue with language, config and update helper we acknowledge this won't run on 13.0.0, but given people need to first move to the latest 12.x version before going to 13 that should be acceptable. The fresh installed config, on 13, is already correct so it's merely the update hooks that …

Issue #3439600: Update hook social_event update hook 121001 and 121002 not executed because of language issues

---

composer.json

The Social Blue theme has a new Major version and some patch are outdated.
Remove outdated patches.
[PROD-29367](https://getopensocial.atlassian.net/browse/PROD-29367)
[#3442170](https://www.drupal.org/project/social/issues/3442170)
N/A
N/A
N/A
N/A
N/A
N/A
[PROD-29367]: https://getopensocial.atlassian.net/browse/PROD-29367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Issue #3442170: Remove outdated patch from Social Blue theme

---

modules/social_features/social_branding/config/schema/social_branding.schema.yml
modules/social_features/social_branding/social_branding.api.php
modules/social_features/social_branding/social_branding.info.yml
modules/social_features/social_branding/social_branding.links.menu.yml
modules/social_features/social_branding/social_branding.module
modules/social_features/social_branding/social_branding.permissions.yml
modules/social_features/social_branding/social_branding.routing.yml
modules/social_features/social_branding/src/Form/SocialBrandingFeaturesForm.php
modules/social_features/social_branding/src/Plugin/GraphQL/DataProducer/PreferredFeatures.php
modules/social_features/social_branding/tests/modules/social_branding_default_test/social_branding_default_test.info.yml
modules/social_features/social_branding/tests/modules/social_branding_default_test/social_branding_default_test.install
modules/social_features/social_branding/tests/modules/social_branding_default_test/social_branding_default_test.module
modules/social_features/social_branding/tests/modules/social_branding_empty_test/social_branding_empty_test.info.yml
modules/social_features/social_branding/tests/modules/social_branding_empty_test/social_branding_empty_test.module
modules/social_features/social_branding/tests/modules/social_branding_test/social_branding_test.module
modules/social_features/social_branding/tests/src/Kernel/GraphQL/BrandingGraphQLTest.php
phpstan-baseline.neon

Right now we don't have an easy way to influence the bottom bar features, while we do promise that.
This was done by implementing a patch, per environment which uses 
```
function hook_social_branding_preferred_features(): array {
return [
new PreferredFeature('home', 0),
new PreferredFeature('events', 1),
new PreferredFeature('groups', 2),
new PreferredFeature('search', 3),
new PreferredFeature('topics', 5),
];
}
```
But than changing that per environment.
We now provide a new admin form, currently no permissions are set, as it's for now Admin only (until we know every business requirement we need to provide it for SM, e.g. which preferred features are available, mandatory, how many etc)
So this form gives admins a way to deal with the bottom bar features for the App. 
Right now we use …

Internal: Add Configuration to influence the order of branding features

---

modules/social_features/social_group/social_group.install
tests/behat/features/capabilities/groups/groups-view-overview-filter.feature

Currently we have 4 types of Groups that we are now migrating to Flexible Groups:
<ul>
<li>Open Group</li>
<li>Closed Group</li>
<li>Secret Group</li>
<li>Public Group</li>
</ul>
The information about the type of these groups is very valuable and a group is immediately recognisable in teasers search and groups pages.
When moving these groups to Flexible groups we are going to loose this identity.
Everything will be identified as Flexible Groups and this will generate confusion and frustration for customers.
We want to mitigate this problem by creating and assigning "Group type" value to each of the newly migrated groups.
Add taxonomy terms in "Group types" vocabulary and assign to group during migration.
- https://www.drupal.org/project/social/issues/3438139
- …

Issue #3438139: Add "Group types" to groups migration

---

cspell.baseline.txt
modules/custom/social_lazy_loading/social_lazy_loading.info.yml
modules/social_features/social_core/social_core.install
modules/social_features/social_embed/social_embed.install
modules/social_features/social_embed/src/Plugin/Filter/SocialEmbedLazyFilter.php

We will remove the Social Lazy and Lazy module at Open Social 13, so we will add deprecated lifecycle to it.
We already use Drupal Core's native one for images (see https://github.com/goalgorilla/open_social/pull/3555) however we still have a way to lazy load iframes, using the embed module.
So we migrate the functionality from lazy to a new plugin within Social Embed.
The interesting part is the native browser `loading=lazy` attribute 
But we don't need a contrib module to have that, we just implement it ourselves.
Important note is that we set the weight to 999 to ensure this runs after the actual embed content.
Embed creates a different wrapper which will be replaced with an iframe, so we can't run it before, otherwise there is no iframe rendered yet.
It also works with the consent …

Issue #3440298: Deprecate Social Lazy Loading module

---

modules/social_features/social_user/config/schema/social_user.schema.yml
modules/social_features/social_user/social_user.install
modules/social_features/social_user/social_user.module
modules/social_features/social_user/src/Form/SocialUserPasswordForm.php

When the variable show_mail_in_messages is filled, an error is throwing when the accounts settings is save.
Account Settings page: /admin/config/people
Error: 'show_mail_in_messages' is not a supported key.
The show_mail_in_messages should be moved to Social User module and stop to use yaml configuration from core and/or contributte module.
[PROD-29296](https://getopensocial.atlassian.net/browse/PROD-29296)
[#3426460](https://www.drupal.org/project/social/issues/3426460)
N/A
N/A
The error to save Account Settings will be fixed.
Moved the config variable show_mail_in_messages from system.site to social_users.settings
N/A
[PROD-29296]: https://getopensocial.atlassian.net/browse/PROD-29296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Issue #3426460: Error to save Account Settings

---

modules/custom/social_lets_connect/modules/social_lets_connect_contact/social_lets_connect_contact.links.menu.yml

Update the review link now we don't use capterra anymore.
Update it to the new link
Internal link only; 
https://getopensocial.atlassian.net/browse/PROD-29431
Updated the link to Review Open Social.

PROD-29431: Change link to Review Open Social

---

.github/PULL_REQUEST_TEMPLATE.md

We have a big bunch of text in the PR that we're seemingly never using.
Remove the Definition of Done from the PR template.
N/a
N/a

Internal: Remove Definition of Done from Pull Request Template

---

modules/custom/social_language/social_language.install
modules/social_features/social_group/modules/social_group_invite/social_group_invite.install

Some installation has a record at config table to original language and it's wrong, because original language will get data from the content and other language should have a record for they data.
When this record exists, the core never get the right data, because config by translation has priorioty to be selected.
Create a hook-update to remove all extra record.
[PROD-27808](https://getopensocial.atlassian.net/browse/PROD-27808)
[#3441126](https://www.drupal.org/project/social/issues/3441126)
That error isn't happen for new installation, because probable it was a bug already fixed by community, so to reproduce we need to add a record directly to the database.
N/A
This will fix the bug related to group invite, where the user invited as mentioned as invitor.
N/A
N/A
[PROD-27808]: …

Issue #3441126: Language configuration create wrong to Original Language at group-type

---

modules/social_features/social_group/modules/social_group_request/social_group_request.module
modules/social_features/social_group/social_group.module
phpstan-baseline.neon

Field `field_group_type` in `flexible group` contains the taxonomy terms that could represent the group type (like in topics or events). If group have this taxonomy then it should be displayed instead of default group type.
Refactor code.
- https://www.drupal.org/project/social/issues/3444422
- https://getopensocial.atlassian.net/browse/PROD-29292
_Before:_
_After:_
Display group types on group teasers

Issue #3444422: Display group types taxonomy terms on group teasers

---

composer.json

The Drupal 10.2.6 was released and some patches start to throw error to apply.
Removed outdated patches.
[PROD-29516](https://getopensocial.atlassian.net/browse/PROD-29516)
[#3445166](https://www.drupal.org/project/social/issues/3445166)
N/A
N/A
N/A
N/A
N/A
N/A
[PROD-29516]: https://getopensocial.atlassian.net/browse/PROD-29516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Issue #3445166: Remove outdated patch from Drupal Core

---

modules/social_features/social_event/social_event.tokens.inc
modules/social_features/social_event/src/EventEnrollmentStatusHelper.php

The event page has an enrollments block with a counter of how many people enrolled. This counter is loading event enrollment entities which is unnecessary.
When there are a lot of enrolments to an event the page becomes unnecessarily slow.
Add a simple flag loading just the IDs. This way implementations from others will not be affected.
https://www.drupal.org/project/social/issues/3445409
N/a
N/a
The counter showing how many people were joining an event was loading an unnecessary amount of data. It now loads only what it needs.
N/a
N/a

Issue #3445409: Remove expensive entity loads for the event enrollments counter

---

modules/social_features/social_group/config/schema/social_group.schema.yml
modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install
modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
modules/social_features/social_group/src/Form/SocialGroupSettings.php
phpstan-baseline.neon
tests/behat/features/bootstrap/GroupContext.php
tests/behat/features/capabilities/groups/groups-view-overview-filter.feature

During the migration from old groups to "Flexible group" we have enable the field "Group type” for everyone.
In the backend we have a settings page _/admin/config/opensocial/social-group_ where we allow for SM to enable/disable group types:
In Open Social 13 we want to make Group types a default for everyone and we want to remove the option for SM to disable it.
- Remove redundant `social_group_type_required` setting from `social_group.settings`
- Always display "Type" field on group add/edit pages
- https://www.drupal.org/project/social/issues/3444432
- https://getopensocial.atlassian.net/browse/PROD-28732
n/a
Always display "Type" field on group add/edit pages
The setting  `social_group_type_required` is removed from `social_group.settings` configuration, no replacement.

Issue #3444432: Always display "Type" field on group add/edit pages

---

modules/social_features/social_group/modules/social_group_invite/src/Form/SocialBulkGroupInvitation.php
translations.php

In the 'Invite members to group' page: `group/ID/invite-members`
The copy for the Invite members feature in a group needs to be updated.
Change labels:
- Find people by name or email address → Invite any person inside or outside your community using their name or email
- You can enter or paste multiple entries separated by comma or semicolon → For multiple invitees separate each name or email with a comma
- https://www.drupal.org/project/social/issues/3445024
- https://getopensocial.atlassian.net/browse/PROD-25814
N/A
Before:
After:
Change labels of invitations to join a Group
N/A
N/A

Issue #3445024: Change labels of invitations to join a Group

---

modules/social_features/social_event/modules/social_event_addtocal/social_event_addtocal.module
modules/social_features/social_event/modules/social_event_addtocal/src/Plugin/SocialAddToCalendar/AddToICal.php
tests/behat/features/capabilities/event/add-to-calendar.feature

Rename iCal to iCalendar to match the full name and not the file extension.
Update copy of each calendar for the users following the copy provided:
- iCal → iCalendar
- Google Calendar → Google
- Office 365 Calendar → Office 365
- Outlook Calendar → Outlook
- Yahoo Calendar → Yahoo
- https://www.drupal.org/project/social/issues/3444628
- [PROD-27039](https://getopensocial.atlassian.net/browse/PROD-27039)
N/A
Update copy of calendar levels for the users.
N/A
N/A
[PROD-27039]: https://getopensocial.atlassian.net/browse/PROD-27039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Issue #3444628: Rename iCal to iCalendar

---

modules/social_features/social_search/social_search.install

In some occassions the solr server already existed, lets make sure we check that before creating.
to prevent
```
W: >  [error]  'search_api_server' entity with ID 'social_solr' already exists. 
W: >  [error]  Update failed: social_search_update_13000 
```
Check if the server doesn't exist yet.
https://www.drupal.org/project/social/issues/3445981
Code review will do, the test case happens in our QA checks.
Part of the release notes already, just a fix for 13.0.0 SOLR.

Issue #3445981: Solr: Ensure we only run the update hook if the server doesn't exist

---

modules/social_features/social_event/config/update/social_event_update_130001.yml
modules/social_features/social_event/social_event.install
modules/social_features/social_topic/config/update/social_topic_update_130001.yml
modules/social_features/social_topic/social_topic.install
tests/behat/features/capabilities/groups/flexible/groups-flexible-sidebar-blocks.feature

We received a bug report saying that some of our clients can't see the sidebar blocks "Upcoming events" and "Newest topics" in flexible groups.
As a result of a extensive investigation, we discovered that the issue is caused by 3 misconfigurations:
1. The visibility settings in the block is restricting it to some group types;
2. The contextual filter in the View has a validation criteria restricting the query to some group types;
3. The `social_course` module is [overriding some of the Views configs](https://git.drupalcode.org/project/social_course/-/blob/5.1.x/src/SocialCourseOverrides.php) affecting the query for those blocks.
We also discovered that this issue does not happen to fresh installations.
Since the config overriding (3rd item mentioned above) is already been taken care on …

Issue #3436013: Fix sidebar blocks display in flexible groups

---

modules/social_features/social_group/config/optional/views.view.group_managers.yml
modules/social_features/social_group/config/update/social_group_update_13007.yml
modules/social_features/social_group/social_group.install

In the new 13.0.0 update the group migration has taken place so some views have been altered to remove the open-closed group types.
But in the group managers block the filter has been changed incorrectly, now requiring only to have a profile to be group manager.
This is only for the block view and does not actually give them group manager permissions/role.
Change the filter from "or" to "and".
https://www.drupal.org/project/social/issues/3446480
Internal (as it's 13-Alpha): We fixed an issue where the group managers block would mark every joined member as manager.

Issue #3446480: Group manager block marking every joined member as manager

---

modules/social_features/social_group/config/install/views.view.newest_groups.yml
modules/social_features/social_group/config/update/social_group_update_13008.yml
modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
modules/social_features/social_group/social_group.install
modules/social_features/social_group/social_group.module

Follow up #3763
Remove redundant "Group type" filter on "/all-groups" page.
- https://www.drupal.org/project/social/issues/3421348
- https://getopensocial.atlassian.net/browse/PROD-29583
Remove redundant "Group type" filter on group overview.

Issue #3421348: Remove redundant "Group type" filter

---

modules/social_features/social_profile/social_profile.module

In PR #3799, we added a hook api from the registration module to not allow these organization fields to beadded to the registration.
We are reverting the same logic in this PR and it will be moved social_organization module.
https://www.drupal.org/project/social/issues/3445957
**Before**
**After**
We added the organizations profile fields to be used for the user registration page.
N.A
N.A

Issue #3445957: Organization field doesn't appear on registration field settings

---

tests/behat/features/capabilities/event/eventenrollment.feature

This test ensures that an event without an end date also properly shows as "passed" but we no longer allow events without end dates. The test step used doesn't validate that the created entity is valid, this is fixed in a future PR.
This is a follow-up to https://github.com/goalgorilla/open_social/pull/3880 which makes end-dates required but didn't remove this test coverage for a now unsupported state.
Remove the test steps, the remaining steps cover the scenario with an end date.
https://www.drupal.org/project/social/issues/3443501
https://getopensocial.atlassian.net/browse/PROD-25979
[Follow-up for existing release notes, no notes needed.]

PROD-25979: Remove obsolete test for event enrollment

---

modules/social_features/social_core/social_core.install
modules/social_features/social_event/modules/social_event_type/social_event_type.install
modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install
modules/social_features/social_profile/modules/social_profile_organization_tag/social_profile_organization_tag.install
modules/social_features/social_profile/social_profile.install
modules/social_features/social_tagging/social_tagging.install

Currently we allow Site Managers to create, edit and translate taxonomy vocabularies in the taxonomy overview page at `/admin/structure/taxonomy`
These actions are not supported by our frontend  so the changes applied to the vocabularies have no effect in the platform.
This generates confusion and it is hard to explain to Community Managers why this is happening.
We have decided to remove these unused options and present a more functional experience to our customers.
- Revoke permission `administer taxonomy` from the site manager.
- Grant permissions to `access taxonomy overview` and `create terms in` vocabularies.
- https://www.drupal.org/project/social/issues/3444592
- https://getopensocial.atlassian.net/browse/PROD-27327
N/A
N/A
Remove unsupported functionality for taxonomy …

Issue #3444592: Replace permission `administer taxonomy` with `access taxonomy overview` for SM

---

modules/social_features/social_private_message/src/Service/SocialPrivateMessageService.php

The `updateUnreadCount()` function in `SocialPrivateMessageService` is sometimes called multiple times during a request.
Apply simple static caching.
https://www.drupal.org/project/social/issues/3445902
N/a
N/a
Minor performance improvement for the private message feature.
N/a
N/a

Issue #3445902: Apply static caching to the SocialPrivateMessageService

---

modules/social_features/social_core/social_core.install

In #3885 we removed the administer taxonomy permission for SM.
This had some unwanted side effects.
Considering it already has been released we do it in another update hook to be kind to the community who are apparantly already using it. (From historical purposes probably also a good reference)
After fixing all the occurrences (like nationality / report reason) of taxonomy creation in the individual modules we can revoke this permission in the product again.
For now the PR #3885 still is fine, the added permissions aren't a problem, it's the removal of the administer taxonomy and us forgetting some of the vocabularies that we're relying on this permission for SM to be able to CRUD the terms in there. 
Once we have fixed all the individual vocabulary & term permissions for SM we can revoke …

Issue #3444592 - Revert removal of administer taxonomy permission for SM.

---

modules/custom/activity_send/modules/activity_send_email/src/EmailFrequencyBase.php
modules/custom/social_lets_connect/modules/social_lets_connect_usage/src/Plugin/ShareUsageDataPluginBase.php
modules/social_features/social_event/modules/social_event_addtocal/src/Annotation/SocialAddToCalendar.php
modules/social_features/social_event/modules/social_event_addtocal/src/Plugin/SocialAddToCalendar/AddToGoogle.php
modules/social_features/social_event/modules/social_event_addtocal/src/Plugin/SocialAddToCalendar/AddToICal.php
modules/social_features/social_event/modules/social_event_addtocal/src/Plugin/SocialAddToCalendar/AddToOutlook.php
modules/social_features/social_event/modules/social_event_addtocal/src/Plugin/SocialAddToCalendar/AddToYahoo.php
modules/social_features/social_event/modules/social_event_addtocal/src/Plugin/SocialAddToCalendarBase.php
modules/social_features/social_post/src/Plugin/views/area/SocialPostPostForm.php
phpstan-baseline.neon

The last Drupal upgrade start to throw some PHPStan warnings and to continue with the upgrade these warnings was added to be ignored by PHPStan.
The PHPStan ignore added can be check here: [https://github.com/goalgorilla/open_social/pull/3806/commits/14894189009...](https://github.com/goalgorilla/open_social/pull/3806/commits/1489418900977e73a6fb8f989af2ed20ed94fc57)
Fix these warnings and remove it from PHPStan ignore.
[PROD-28482](https://getopensocial.atlassian.net/browse/PROD-28482)
[#3432191](https://www.drupal.org/project/social/issues/3432191)
N/A
N/A
N/A
Fixed errors ignored from last Drupal upgrade.
N/A
N/A
[PROD-28482]: https://getopensocial.atlassian.net/browse/PROD-28482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Issue #3432191: Fix PHPStan warnings from Drupal upgrade

---

modules/social_features/social_core/social_core.install

Due to caching issues in the CKEditor, inline images added through the CKEditor were omitted from using the secret filesystem. However in the update path those images from the `file_managed` table were not excluded. This has caused `social_core_update_130002` to say that inline images that should be served by the private file system should be served by the secret file system. However, this is then invalid, causing issues.
This commit adds an update hook that reverts the incorrectly changed inline images. We can be sure that anything that matches was coming from private, since we didn't touch public images.

Hotfix: inline images converted to secret file system

---

modules/custom/activity_creator/src/Entity/Activity.php
phpstan-baseline.neon

One of our client has fatal error on "Notification center" (`/notifications`):
```
Error: Call to a member function getFlaggableType() on null in Drupal\activity_creator\Entity\Activity->getRelatedEntityUrl() (line 279 of profiles/contrib/social/modules/custom/activity_creator/src/Entity/Activity.php).
```
Add checks to prevent methods from calling on empty object.
- https://www.drupal.org/project/social/issues/3450914
- https://getopensocial.atlassian.net/browse/PROD-29719
Prevent fatal error on "Notification center" if flagging entity was accidentally deleted.

Issue #3450914: Prevent fatal error on "Notification center" if flagging entity was accidentally deleted

---

modules/social_features/social_follow_taxonomy/modules/social_follow_tag/social_follow_tag.module

We could see "followers count" in different views related to taxonomy, which is not correct.
Display "followers count" only for the followers count view mode.
- https://getopensocial.atlassian.net/browse/PROD-27339
- https://www.drupal.org/project/social/issues/3451029
N/A
N/A
Before this change, we could see "followers count" in different views related to taxonomy
Now, the "followers count" number is displayed only for the followers count view mode.
N/A
N/A

Issue #3451029: Display "followers counter" only for the followers_count view mode

---

modules/social_features/social_group/social_group.module

Group types translations are not visible in teasers and on group page.
Affected pages/view mods:
- teasers, search page, stream, overview, group page
In the `social_group_preprocess_group()`:
replace `$variables['group_type'] = $term->getName();`
with `$variables['group_type'] = \Drupal::service('entity.repository')->getTranslationFromContext($term)->label();`
- https://www.drupal.org/project/social/issues/3450999
- https://getopensocial.atlassian.net/browse/PROD-29648
N/A
Group types translations are now visible in teasers and group pages.
N/A
N/A

Issue #3450999: Group types translations are not visible in teasers and group page

---

modules/social_features/social_core/assets/css/preview-el.css
modules/social_features/social_core/assets/css/preview-el.scss

The user preview element on the group pages does not have a correct hover behavior.
Should reset styles that were added for avatar images and add an underline effect to the simple text.
- https://www.drupal.org/project/social/issues/3452925
- https://getopensocial.atlassian.net/browse/PROD-29773
Steps to reproduce 1
Steps to reproduce 2
Before:
After:
Improve hover behavior for the user preview element on the group pages.

Issue #3452925: Fix issue with preview popup element on the group pages

---

modules/social_features/social_core/social_core.install
modules/social_features/social_node/config/install/field.storage.node.field_files.yml

We have an incident related with secret:// filesystem and it became some unacessible files for all users.
Temporary solution is revert secret:// filesystem for field_file field.
[PROD-29716](https://getopensocial.atlassian.net/browse/PROD-29716)
N/A
N/A
Fixed access trouble with attachments from contents.
N/A
N/A
[PROD-29716]: https://getopensocial.atlassian.net/browse/PROD-29716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Revert secret:// to private:// from field_file field

---

modules/custom/grequest/grequest.services.yml
modules/custom/grequest/src/Plugin/Group/RelationHandler/GroupMembershipRequestPermissionProvider.php

When looking at the code of the grequest module in the latest alpha we see there are still issues for it to work with groups v2.
- Services are not correctly defined.
- Still reference to old group content relation
- Add the correct services definition for the relation.
- Remove the old unset of permissions as they don't exist anymore in that part.
Note: Even though we don't use all the services such as group operations (we have our own button there) it's good to have it in there for when we want to convert to the contrib grequest.
https://www.drupal.org/node/3452660
Internal: Fix for group v2 compatibility for the submodule grequest.

Issue #3452660: Grequest compatibility with group v2

---

composer.json

We've noticed there are still some references in the database with base field overrides these were coming from group_update_8022 and should be tackled in the group module accordingly.
Patch group and apply that patch here - issue at https://www.drupal.org/project/group/issues/3322761
https://www.drupal.org/project/social/issues/3454117
It's not easily reproducable, we have some existing sites.
Fixed an issue with CRUD of Group related entities (memberships / nodes)

Issue #3454117: use a post update hook to fix base field override references to GroupContent which is updated in v2 of Groups

---

modules/custom/entity_access_by_field/src/EntityAccessHelper.php

Unpublished events are visible to enrolled VU via URL.
Add check for enrolled users if the event is published or not.
- https://www.drupal.org/project/social/issues/3454115
- https://getopensocial.atlassian.net/browse/PROD-27870
N/A
N/A
User should not be able to access an unpublished event even if he is enrolled in it.
N/A
N/A

Issue #3454115: Deny access to unpublished events for enrolled users

---

modules/social_features/social_like/social_like.module

The title of this pop-up reads "Members who liked this Photo", it's not always correct in case we have only text posts without images.
Change the title of the Likes pop-up on posts to "Liked by", so it's more generic for all cases.
- https://getopensocial.atlassian.net/browse/PROD-26545
- https://www.drupal.org/project/social/issues/3452477
N/A
N/A
Change the title of the Likes pop-up on posts to "Liked by", so it's more generic for all cases.
N/A
N/A

Issue #3452477: Change the title of the Likes pop-up for posts

---

modules/custom/grequest/grequest.services.yml
modules/social_features/social_group/modules/social_group_request/social_group_request.install

When user sent request to join a group seems all works well but after a cron run email wasn't not sent and there is a following error message:
Also, Group manager role doesn't have access to approve/decline request to join a group and need to fix it as well
Looks like GroupMembershipRequestAccessControl relation handler is not used and we can safely remove it from grequest.services.yml file
- https://www.drupal.org/project/social/issues/3454680
- https://getopensocial.atlassian.net/browse/PROD-29861
N/A
Adding a new permission fixes access to the items on the membership-requests page and notification about new request
Fixes an error with sending an email about request to join group and fixes access to group request for GM
N/A

Issue #3454680: Error "GroupMembershipRequestAccessControl" not found

---

composer.json

Lock `drupal/search_api_solr` as we've now added a patch that fails on the next update https://www.drupal.org/project/search_api_solr/releases/4.3.4.
Instead of updating and removing the patch, that could cause quite some regression,  we are first locking it. 
This way we can unblock our PR's which are failing and we can perform the update later. 
That patch is released here: https://www.drupal.org/files/issues/2024-04-22/3434394-6--drupal_11_compatibility.patch 
https://getopensocial.atlassian.net/browse/PROD-29910
See that patches apply and everything is green. Considering we're using the same version no regression should take place.
None, internal.

Internal: Lock `drupal/search_api_solr`

---

modules/social_features/social_event/modules/social_event_managers/src/Plugin/views/field/SocialEventManagersViewsBulkOperationsBulkForm.php
modules/social_features/social_group/modules/social_group_invite/src/Plugin/views/field/SocialGroupInviteViewsBulkOperationsBulkForm.php
modules/social_features/social_group/src/Plugin/views/field/SocialGroupViewsBulkOperationsBulkForm.php
phpstan-baseline.neon

On an event's or group's "Manage members" tabs, when we select users in an event, it does not show how many users are selected. Also, count remained 0 on selections as well as on page refresh.
This was happening because we were calculating the total count is indifferent logic from VBO's own parent class. So, we are abopting the same solution across all the VBOForms used in Open Social.
https://getopensocial.atlassian.net/browse/PROD-29405
N.A
**Before**
Both _On selection_ and _On refresh_
**After**
_On selection_
_On refresh_
We have fixed a bug where the list of selected members in an Event or Group's "Manage Members" tab was not showing as well as not updating the count. Now, when you select a member, you will see in "Items selected" list and the count will also reflect the number of …

Issue #3454972: Enrolment & Invite pages in Manage Members in Events and Groups does show selected users

---

modules/social_features/social_group/modules/social_group_request/social_group_request.services.yml
modules/social_features/social_group/modules/social_group_request/src/EventSubscriber/RedirectSubscriber.php
modules/social_features/social_group/modules/social_group_request/src/Form/GroupRequestMembershipRequestAnonymousForm.php
phpstan-baseline.neon
tests/behat/features/capabilities/groups/flexible/groups-flexible-view-outsider-anonymous.feature

The intention of this route is that it's a callback for the join button, which works well. 
We never figured out what would happen if the user directly goes to the route. In this case, we will ensure that the flow gets started through the join button by
- Ensuring that we will redirect them to the group page if they go to the route directly.
- Write a fall back for the error, if the referer isn't there.
https://www.drupal.org/project/social/issues/3455025
We ensured the AN Group Request membership flow is fixed for the scenario that the modal frame URL is opened directly.

Issue #3455025: Fix type error when users directly goes to `social_group_request.anonymous_request_membership`

---

composer.json

The Social Blue theme has a new Major version and some patch are outdated.
- Update socialbase to 2.6.0
- Update socialblue to 2.6.0
- https://www.drupal.org/project/socialbase/releases/2.6.0
- https://www.drupal.org/project/socialblue/releases/2.6.0
- [PROD-29969](https://getopensocial.atlassian.net/browse/PROD-29969)
N/A
**SocialBase:**
- [#3417761: Replace non-existing classes according to group module upgrade to 2.x](https://www.drupal.org/project/socialbase/issues/3417761)
- [#3407006: Remove legacy group types](https://www.drupal.org/project/socialbase/issues/3407006)
- [#3455930: [UI] Remove extra `z-index` form the region content/content top](https://www.drupal.org/project/socialbase/issues/3455930)
- [#3456257: [UI] Improve position auth …

Updates: socialbase and socialblue themes to the 2.6.0

---

modules/social_features/social_core/config/schema/social_core.schema.yml
modules/social_features/social_core/src/Plugin/Field/FieldFormatter/ExternalIdentifierDefaultFormatter.php
modules/social_features/social_core/src/Plugin/Field/FieldType/ExternalIdentifierItem.php
modules/social_features/social_core/src/Plugin/Field/FieldWidget/ExternalIdentifierDefaultWidget.php
modules/social_features/social_core/src/Plugin/Validation/Constraint/ExternalIdentifierEmptySubfieldsConstraint.php
modules/social_features/social_core/src/Plugin/Validation/Constraint/ExternalIdentifierEmptySubfieldsConstraintValidator.php
modules/social_features/social_core/src/Plugin/Validation/Constraint/ExternalIdentifierExternalOwnerIdConstraint.php
modules/social_features/social_core/src/Plugin/Validation/Constraint/ExternalIdentifierExternalOwnerIdConstraintValidator.php
modules/social_features/social_core/src/Plugin/Validation/Constraint/ExternalIdentifierExternalOwnerTargetTypeConstraint.php
modules/social_features/social_core/src/Plugin/Validation/Constraint/ExternalIdentifierExternalOwnerTargetTypeConstraintValidator.php
modules/social_features/social_core/tests/modules/social_core_test_entity_provider/social_core_test_entity_provider.info.yml
modules/social_features/social_core/tests/modules/social_core_test_entity_provider/src/Entity/ExternalOwnerEntityTestProvider.php
modules/social_features/social_core/tests/src/Kernel/ExternalIdFieldTypeTest.php

As a developer I want a re-usable externalId implementation so that I can easily apply this to different entity types.
SCIM provides [the concept of externalId](https://datatracker.ietf.org/doc/html/rfc7643#section-3.1) which can be used to identify a resource with an identifier that is known to the SCIM client. This prevents the SCIM client from having to store a mapping between its internal data and our ID, instead putting that burden on us as a service provider.
Although not covered by SCIM itself, it provides various [recommendations for multi-tenancy](https://datatracker.ietf.org/doc/html/rfc7644#section-6) where multiple external systems may want to manage their own user data. Given our intention of targeting Enterprise users it’s likely that they’ll want to connect multiple systems …

PROD-29703: Provide external identifier field

---

modules/social_features/social_user/config/install/field.field.user.user.field_external_identifier.yml
modules/social_features/social_user/config/install/field.storage.user.field_external_identifier.yml
modules/social_features/social_user/config/update/social_user_update_13003.yml
modules/social_features/social_user/social_user.install

We need to implement `externalId` for user entity type. More info why this is needed here => https://github.com/goalgorilla/open_social/pull/3942
Add an external identifier field to the user entity. This field is locked, as it should not be managed via the UI, but rather by modifying the configuration. The field is provided without any settings and is, therefore, unusable by default. At least one target type needs to be specified by modifying the field storage configuration to ensure the field can be properly used.
Since the field is locked, target types can be managed by other modules by using for example [config_modify](https://www.drupal.org/project/config_modify) to allow specific target types
Example:
File: scim/config/modify/scim.field_external_identifier_consumer_target_type.yml …

PROD-29703: Add an external identifier field to the user entity

---

modules/social_features/social_content_report/social_content_report.install
modules/social_features/social_core/social_core.install
modules/social_features/social_profile/modules/social_profile_fields/social_profile_fields.install

Currently we allow Site Managers to create, edit and translate taxonomy vocabularies in the taxonomy overview page at `/admin/structure/taxonomy`
These actions are not supported by our frontend so the changes applied to the vocabularies have no effect in the platform.
This generates confusion and it is hard to explain to Community Managers why this is happening.
We have decided to remove these unused options and present a more functional experience to our customers.
- Revoke permission `administer taxonomy` from the site manager.
- Grant permissions to manage terms in all vocabularies.
- https://getopensocial.atlassian.net/browse/PROD-27327
- https://getopensocial.atlassian.net/browse/PROD-29643
- https://www.drupal.org/project/social/issues/3444592
N/A
N/A
Remove unsupported …

Issue #3456218: Revoke Administer taxonomy permission for SM

---

tests/behat/features/bootstrap/EntityTrait.php

validateEntityFields() is not correctly transforming date field values for datetime type "date" fields (it works as designed for "datetime" type only). To fix the issue correct date format is applied for date only fields.
[3445775](https://www.drupal.org/project/social/issues/3445775) (PROD-29315)
N/A
Create behat test step, that uses validateEntityFields method and validate date only field. 
Created entity will have empty date field as an result of wrong date format applied.
With this fix applied date field will be correctly transformed.
N/A
Improve tests.
N/A
N/A

Issue #3445775: validateEntityFields is not correctly transforming date

---

modules/custom/social_media_system/config/install/field.storage.media.field_media_file.yml
modules/custom/social_media_system/config/update/social_media_system_update_12103.yml
modules/custom/social_media_system/social_media_system.install

In version 12.0.0 `social_media_system` module was added as a helper module for all the default media configurations.
This module provides `field_media_file` which by default uses public uri_scheme.
This module provides field_media_file which by default uses public uri_scheme.
Later with https://github.com/goalgorilla/open_social/pull/3727 visibility was changed from public to private uri_scheme.
Summary of decision:
Out of the box, access to files is granted based on configuration - users have access to all media files.
Media items don't inherit access control from parents (https://www.drupal.org/project/drupal/issues/2984093) so 
this is why we want to use secret file system instead, so the URL isn't guessable and it's only provided if the media entity is rendered.
Complete discussions …

Issue #3452643: Change uri_scheme of field_media_file to secret

---

modules/social_features/social_activity/config/install/message.template.create_content_in_joined_group.yml
modules/social_features/social_activity/config/install/message.template.create_event_community.yml
modules/social_features/social_activity/config/install/message.template.create_event_gc.yml
modules/social_features/social_activity/config/install/message.template.create_event_group.yml
modules/social_features/social_activity/config/install/message.template.create_topic_community.yml
modules/social_features/social_activity/config/install/message.template.create_topic_gc.yml
modules/social_features/social_activity/config/install/message.template.create_topic_group.yml
modules/social_features/social_activity/social_activity.install
modules/social_features/social_activity/social_activity.tokens.inc
modules/social_features/social_group/modules/social_group_flexible_group/modules/social_flexible_group_book/config/optional/message.template.create_book_group.yml
modules/social_features/social_group/modules/social_group_flexible_group/modules/social_flexible_group_book/social_flexible_group_book.install

When a content has author change, the activity related with it continue showing first author and never be updated.
I created a new Token on Social Acitivty module to get current revision user. 
[PROD-25155](https://getopensocial.atlassian.net/browse/PROD-25155)
[#3456839](https://www.drupal.org/project/social/issues/3456839)
N/A
N/A
The error related to activities showing wrong author after the author from a content was updated, is fixed..
N/A
N/A
[PROD-25155]: https://getopensocial.atlassian.net/browse/PROD-25155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Issue #3456839: Different authors between content and activity

---

modules/social_features/social_comment/social_comment.tokens.inc
modules/social_features/social_follow_taxonomy/social_follow_taxonomy.tokens.inc
modules/social_features/social_group/social_group.tokens.inc
modules/social_features/social_like/social_like.tokens.inc
modules/social_features/social_mentions/social_mentions.tokens.inc

Currently in several notifications we use placeholders to show the entity bundle (Topic, Event, Comment etc). We force this placeholders to always be lowercase. This works well in english and most languages, but not in German for example where those terms should be displayed uppercase.
Add an alternative version of the same tokens with capitalized entity bundle label, so it can be used in German. The original tokens are kept the same.
Added variations for the tokens:
- [social_mentions:commented_entity_link_html:capitalized]
- [social_group:content_type:capitalized]
- [social_group:created_entity_link_html:capitalized]
- [social_comment:commented_content_type:capitalized]
- [social_comment:commented_entity_link:capitalized]
- [social_comment:commented_entity_link_html:capitalized]
- …

Issue #3453946: Add alternative token with capitalized entity bundle label

---

cspell.words.txt
tests/behat/features/capabilities/event/all-day-timezone.feature
tests/behat/features/capabilities/event/event-create.feature
tests/behat/features/capabilities/groups/flexible/groups-flexible-create.feature
tests/behat/features/capabilities/profile/edit-profile.feature
tests/behat/features/capabilities/profile/hide-profile-field-groups.feature

Due to wrong selection "Lviv oblast" behat tests are failing.
We need to rename "Lviv oblast" to "Lvivska oblast".
[3460756](https://www.drupal.org/project/social/issues/3460756)
N/A
N/A
N/A
Fix failing behat tests.
N/A
N/A

Issue #3460756: Fix behat tests for address

---

modules/social_features/social_user/social_user.info.yml

The dependency is there through social_profile, but social_user was also already relying on social_core in its code before. What is missing is to declare dependency explicitly. 
FUP of:[#3950](https://github.com/goalgorilla/open_social/pull/3950#issuecomment-2199398521)
Declare dependency explicitly. 
[3460734](https://www.drupal.org/project/social/issues/3460734)
PROD-29703
IOSAP-457
N/A
N/A
N/A
Explicitly define social_core as a social_user dependency. Although the dependency was previously established through social_profile and social_user already relied on social_core in its code, this change formalizes the relationship.
N/A
N/A

Issue #3460734: Define social_core as social_user dependency

---

tests/behat/features/bootstrap/GroupContext.php
tests/behat/features/capabilities/groups/flexible/groups-flexible-view-outsider-anonymous.feature
tests/behat/features/capabilities/groups/join/groups-join-direct.feature
tests/behat/features/capabilities/groups/join/groups-join-request-manage.feature
tests/behat/features/capabilities/groups/join/groups-join-request.feature

This commits adds test to document the behaviour of the "Request to Join" feature for flexible groups after discussing the behaviour with our PO and Designer.
The join functionality is moved to a new folder under "groups" in the testing structure. The outsider view test was previously modified to have a bit of test code around request to join and direct joining. This was moved to their own test so that the feature for viewing is really only for viewing and the joining features are separate.
The join functionality is not placed under flexible because after the group migration we're only left with a single group type. The functionality for other group-module-based things are different features.
https://getopensocial.atlassian.net/browse/PROD-30063

PROD-30063: Add test coverage for flexible group request to join

---

modules/social_features/social_group/modules/social_group_welcome_message/social_group_welcome_message.install

Some permission related to Social Group Welcome Message module was removed.
We think it's because this doesn't work together with our real time chat extension and someimtes manually these permissions are removed.
Created a hook-update to add the permission again if Social Chat module isn't enabled.
This means:
- if Chat is enabled, nothing changes.
- if it isn't, we enable the entire range of private message permissions, this way we ensure social private message is also working, if we only limit the permissions to what welcome message needs that might cause regression.
[PROD-28479](https://getopensocial.atlassian.net/browse/PROD-28479)
[#3460260](https://www.drupal.org/project/social/issues/3460260)
N/A
N/A
Fix the bug to add welcome message to Group.
N/A
N/A
[PROD-28479]: …

Issue #3460260: Missing permissions for social_group_welcome_message

---

modules/social_features/social_follow_taxonomy/modules/social_follow_tag/social_follow_tag.module

`anonymous` and `verified` users can see activities created by `message.template.update_node_following_tag` template even if they aren't content tags followers (reproducible on "Home stream" only).
Hide activities about changing content with followed tags for non-followers.
- https://www.drupal.org/project/social/issues/3427043
- https://getopensocial.atlassian.net/browse/PROD-29624
Hide not relevant activities about changing content with followed tags for non-followers.

Issue #3427043: Hide activities about following content tags for non-followers

---

modules/social_features/social_core/src/Plugin/Field/FieldType/ExternalIdentifierItem.php
modules/social_features/social_core/src/Plugin/Validation/Constraint/ExternalIdentifierUniqueExternalIdConstraint.php
modules/social_features/social_core/src/Plugin/Validation/Constraint/ExternalIdentifierUniqueExternalIdConstraintValidator.php
modules/social_features/social_core/tests/modules/social_core_test_entity_provider/src/Entity/ConsumerATestProvider.php
modules/social_features/social_core/tests/modules/social_core_test_entity_provider/src/Entity/ConsumerBTestProvider.php
modules/social_features/social_core/tests/src/Kernel/ExternalIdFieldTypeTest.php

With [#3457487](https://www.drupal.org/project/social/issues/3457487) ([#3942](https://github.com/goalgorilla/open_social/pull/3942)), social_external_identifier field type has been provided. This field type holds a value of external identifier id (external_id). External ID should be unique per entity and external owner, despite how many fields of type "social_external_identifier" entity have. 
Apply this rules by using constraint.
1. External ID should be unique per entity type (for example: external ID can be used only once per user entity).
2. External ID should be unique per all “social_external_identifier” fields (Unlimited amount of fields of type social_external_identifier can be added per one entity and even among all those fields External ID should be unique).
3. External ID …

Issue #3460849: Define external identifier id uniqueness

---

modules/social_features/social_event/modules/social_event_an_enroll/src/Plugin/ContentExportPlugin/ContentEventEnrolleesAn.php
modules/social_features/social_event/modules/social_event_type/src/Plugin/ContentExportPlugin/ContentEventType.php
modules/social_features/social_event/src/Plugin/ContentExportPlugin/ContentEventEnrollees.php
modules/social_features/social_tagging/src/Plugin/ContentExportPlugin/ContentTags.php
modules/social_features/social_topic/src/Plugin/ContentExportPlugin/ContentTopicType.php
phpstan-baseline.neon

It would be interesting for Site Managers to have further fields to enable greater filtering & analysis in the Content Export extension.
Add extra `ContentExportPlugins` for:
- Topic Type (empty if the content is not a Topic)
- Event Type (empty if the content is not an Event)
- Event Enrollees (number of enrollees with an account)
- Event Enrollees Anonymous (number of anonymous enrollees)
- Content Tags (all tags are listed, no parent-child reference necessary)
- https://getopensocial.atlassian.net/browse/PROD-28483
- https://www.drupal.org/project/social/issues/3457850
N/A
N/A
Add new fields for content export extension.

Issue #3457850: Add additional fields for content export

---

modules/social_features/social_core/assets/css/preview-el.css
modules/social_features/social_core/assets/css/preview-el.scss
modules/social_features/social_profile/modules/social_profile_preview/src/Service/SocialProfilePreviewHelper.php

According to the new implementation of the preview popup, the profile preview hover element has a lot of different behavior, resulting in many bugs.
Should add specific classes for the preview image and text elements. Improve the hover behavior of the profile preview elements.
- https://www.drupal.org/project/social/issues/3464394
- https://getopensocial.atlassian.net/browse/PROD-30055
- Enable the `social_profile_preview` module
- Hover on the user name or avatar
**Before:**
**After:**
The profile preview element has the correct behavior on the default and hover states.

Issue #3464394: Improve behavior of the profile preview popup

---

modules/social_features/social_event/asyncapi.yml

We want the AsyncAPI definitions to be co-located with the modules that produces the events. 
The first event "event create" was pushed to Cable Car because it was pending an script to [automatically aggregate all definitions into a single file](https://github.com/goalgorilla/cablecar/pull/1813). This PR moves it to `social_event` module.
Here's the workflow run that generates the final documentation after aggregating all definitions:
https://github.com/goalgorilla/cablecar/actions/runs/10149822534
https://getopensocial.atlassian.net/browse/PROD-30134
N/A
N/A
N/A
N/A
N/A
N/A

PROD-30134: Move AsyncAPI definition for "event create" event into the social_event module

---

modules/social_features/social_event/modules/social_event_type/social_event_type.module

As a user I should see the correct translations of event type terms everywhere on the site.
For examples, we have various event type terms configured on our platform. These terms also have the correct translations configured (for French, Italian) in the backend. Yet, in some parts of the site (e.g. stream, /community-events, etc.), these translations do not appear. French users see the original German strings.
In `social_event_type_preprocess_node()` use:
```
$event_type = \Drupal::service('entity.repository')->getTranslationFromContext($event_type);
```
- https://www.drupal.org/project/social/issues/3464971
- https://getopensocial.atlassian.net/browse/PROD-29850
N/A
Before:
After:
Fixes an issue with untranslated "Event types" field for Events
N/A
N/A

Issue #3464971: Event types are displayed in the default language

---

modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
modules/social_features/social_tagging/config/install/social_tagging.settings.yml
modules/social_features/social_tagging/social_tagging.install
modules/social_features/social_tagging/src/Plugin/Block/SocialGroupTagsBlock.php
modules/social_features/social_tagging/src/SocialTaggingOverrides.php
modules/social_features/social_tagging/src/SocialTaggingService.php
modules/social_features/social_tagging/src/SocialTaggingServiceInterface.php

Now we can allow or disallow tagging for all groups, but there may be cases where we need to disable tagging per group bundle, similar to nodes.
Modify the the getKeyValueOptions() function - delete condition by group, to return keys for group bundles, similar to nodes.
Also, update `hook_social_tagging_type_alter` to allow adding multiple group types, similar to nodes.
https://www.drupal.org/project/social/issues/3463318
https://getopensocial.atlassian.net/browse/PROD-30189
N/A
N/A
In this PR, the 'Group' option in the 'Social Tagging' settings was split into group bundles, similar to nodes. This change allows the ability to enable or disable tagging per group bundle, because if we want to create new group bundles in the future or if other modules will provide new group bundles - it will …

Issue #3463318: Implement the ability to tag groups based on specific bundles.

---

modules/social_features/social_user/social_user.install

On #3869 we moved a variable to a new structure, but one condition made some installation continue using other structure.
Recreate the hook-update with a new condition
[PROD-29296](https://getopensocial.atlassian.net/browse/PROD-29296)
[#3426460](https://www.drupal.org/project/social/issues/3426460)
N/A
This error should be forced or get a database with error.
N/A
The error to save Account Settings will be fixed.
N/A
N/A
[PROD-29296]: https://getopensocial.atlassian.net/browse/PROD-29296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Issue #3426460: Error to save Account Settings 

---

modules/social_features/social_profile/modules/social_profile_fields/src/Form/SocialProfileFieldsSettingsForm.php

In the module social_profile_field we have the option to add nicknames.
There is an issue that when you enable “unique nicknames” at the bottom, but don’t enable nicknames above it will crash during registration as it expects input.
The ideal situation would be that unique nicknames cannot be select if you don’t have nickname enabled.
Added the Unique Nickname field into a fieldset similar to Address fields and it should be visible only when the Nickname field is enabled.
[PROD-30230](https://getopensocial.atlassian.net/browse/PROD-30230)
[#3465292](https://www.drupal.org/project/social/issues/3465292)
N/A
N/A
Changed the Nickname and Unique Nickname behavior to keep the integrity and avoid to enable Unique Nickname field without Nickname field.
N/A
N/A
[PROD-30230]: …

#3465292: The Unique Nickname field is enabled without Nickname field

---

modules/social_features/social_core/src/EdaDummyHandler.php
modules/social_features/social_core/src/SocialCoreServiceProvider.php
modules/social_features/social_event/social_event.services.yml
phpstan-baseline.neon

We want the events for our Event Driven Architecture to live in the modules that own the objects that trigger the events. For example `social_event` is responsible for the creation and management of events in our CMS and thus should be responsible for triggering EDA events related to events. 
However, we want the actual code that publishes all our events to live in Cable Car since we expect this to be a SaaS only feature (as it requires dedicated infrastructure). Because the event generating code lives in the distribution and building an EDA event may have a slight performance cost, we don’t want to distribution users to incur this cost unnecessarily.
Replace all EDA Handlers with dummies if there is no Publisher using the ServiceProvider. …

PROD-29620: Replace all EDA Handlers with dummies if there is no Publisher

---

modules/social_features/social_core/social_core.module

In the PR https://github.com/goalgorilla/open_social/pull/3517 we decided to hide Revision tabs for Groups.
After update to Group 2 the group roles marked as **Admin role** are automatically granted all permissions in the group. By default, the roles set as admin in Open Social are: Administrator, Content manager and Site manager.
That means those roles will automatically have the permission "**_Revisioning: View all revisions_**", which is the one checked in order to enable the Revisions tab. So even though the `new_revision` config is set to `FALSE` for all group types, users in those roles will always see the tab.
Force hiding the Revisions tab the same way we do for nodes in `hook_menu_local_tasks_alter()`. The tab should be hidden if the config `new_revision` is disabled and there is …

Issue #3464499: Hide Revisions tab for groups

---

modules/custom/social_language/social_language.services.yml
modules/custom/social_language/src/PathProcessor/SocialLanguagePathProcessor.php

For multilingual sites, users can't see content (topic, event, group, etc) in languages other than the current user language. For example, if a user with "Dutch" language tries to visit a topic that has only "English" version user gets "Page not found" exception. The expected behavior is that the user should be able to visit "English" version of the topic (because, for example, a user can see topic teasers in "/all-topic" page).
- Redirect users to the content `default language` version if it exists;
- Override `\Drupal\social_language\PathProcessor\AliasPathProcessor`;
- https://www.drupal.org/project/social/issues/3464465
- https://getopensocial.atlassian.net/browse/PROD-29925
Prevent "Page not found" on the content pages that don't have current language translation.

Issue #3464465: "Page not found" on the content pages that don't have current language translation

---

modules/social_features/social_group/config/schema/social_group.schema.yml
modules/social_features/social_group/src/Form/SocialGroupSettings.php

On `/admin/config/opensocial/social-group` a Site Manager can grant users the possibility to create groups.
This feature is supposed to be targeted for Verified users but in the current implementation Authenticated users are affected too.
Change the copy in group settings, to be clear, that only verified users can create a group if settings are enabled.
- https://getopensocial.atlassian.net/browse/PROD-28703
- https://www.drupal.org/project/social/issues/3466883
N/A
Change the copy in group settings, to be clear, that only verified users can create a group if settings are enabled.

Issue #3466883: Fix copy in group settings to "Allow verified users to create new groups"

---

modules/social_features/social_group/modules/social_group_flexible_group/modules/social_flexible_group_book/social_flexible_group_book.install

The PR https://github.com/goalgorilla/open_social/pull/3948/files contains a typo in the flexible_group_book update hook where it tries to retrieve the config create_book_group. This does not exist and needs to be message.template.create_book_group. This is now crashing the update hook.
Correct the typo
https://www.drupal.org/project/social/issues/3456839
A typo has been fixed in retrieving a config for the social_flexible_group_book crashing the update hook.

#3456839: Flexible group book update hook 13002 incorrect due to typo and crashing.

---

modules/custom/social_path_manager/social_path_manager.module

When creating a custom path alias, users currently can set the alias to an internal path, eg. `/modules/custom/my_custom_module/custom.js`.
When a users visit a node with this path alias, instead of showing the actual node data it will try to access the file instead.
Add a custom validation function that disallow to set path alias that starts with a reserved Drupal path or a path that points to an actual file on the server itself.
https://www.drupal.org/project/social/issues/3468174
1. Create a new topic
2. Set the path alias to /modules/custom/my_custom_module/custom.js
3. Make sure that the actual path exist and that the file is actually there.
4. Try to visit this URL
5. You should be prompted to download this file.
Added additional validations to path field to disallow to set path …

Issue #3468174: Path alias can be set to an internal file path

---

modules/social_features/social_core/src/Plugin/Validation/Constraint/ExternalIdentifierUniqueExternalIdConstraintValidator.php

When a field with the type social_external_identifier is updated for an existing user a database error appears.
Use entity type object and get id from it, instead of a static string.
https://www.drupal.org/project/social/issues/3468529

Issue #3468529: Update constraint to be able to use for users

---

composer.json

The new version of Social Blue is using old version from Social Base and it is broken the system.
Lock Social Blue at 2.6.2 version
[PROD-30212](https://getopensocial.atlassian.net/browse/PROD-30212)
N/A
N/A
N/A
Rollback the Social Blue to old version to fix an error.
N/A
N/A
[PROD-30212]: https://getopensocial.atlassian.net/browse/PROD-30212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PROD-30212: Lock the Social Blue at 2.6.2 version

---

modules/social_features/social_core/social_core.module

In the issue [#3464499: Hide the Revisions tab for groups](https://www.drupal.org/project/social/issues/3464499) we hid the Revisions tab for all group pages. But it's still being displayed when accessing the Manage members page. The problem is that this route does not return the complete $entity object. Instead it returns the entity id.
Make sure the `$entity` object is complete for this route as well, so that the Revisions tab is hidden.
- https://www.drupal.org/project/social/issues/3468340
- https://getopensocial.atlassian.net/browse/PROD-30391
N/A
N/A
Hide Revisions tab from Manage members page in the group if revisions are disabled.
N/A
N/A

Issue #3468340: Hide Revisions tab from Manage members page in the group

---

modules/social_features/social_core/social_core.module
modules/social_features/social_event/social_event.install
modules/social_features/social_event/social_event.module
modules/social_features/social_group/social_group.install
modules/social_features/social_group/social_group.module

When creating a new group or event, I change the country field to none. When I go to edit the content, the country field keeps popping back with the default value.
Remove the code filling the default value and start to use the behavior from Address about default value.
So I added two submit function to copy the country default value when it is saved or updated and I added an hook-update to copy the value to old installation.
[PROD-27371](https://getopensocial.atlassian.net/browse/PROD-27371)
[#3466386](https://www.drupal.org/project/social/issues/3466386)
N/A
N/A
Fixed the bug about fill default value from Country field on Event and Group all time.
N/A
N/A
[PROD-27371]: https://getopensocial.atlassian.net/browse/PROD-27371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwI …

Issue #3466386: Country field keeps popping back on edit content

---

modules/custom/activity_creator/src/Service/ActivityCreatorBatchActivityDeletion.php

Attempt to delete a user who has a lot of related activities causes the error:
- Allow to change batch size for activities deletion during user cancellation in `settings.php`.
- Decrease default batch size for activities deleted during user cancellation.
- https://www.drupal.org/project/social/issues/3469681
- https://getopensocial.atlassian.net/browse/PROD-29647
_Notice: The issue is reproducible for instances with limited memory resources._
Allow to change batch size for activities deletion during user cancellation to prevent errors with memory size.

Issue #3469681: Allow to change batch size for activities deletion during user cancellation

---

modules/social_features/social_profile/src/SocialProfileTagService.php

Profile tag translations are not displayed in filters and user information.
Use translated versions of profile tags on user profiles and filters. 
- https://getopensocial.atlassian.net/browse/PROD-24372
- https://www.drupal.org/project/social/issues/3469391
N/A
N/A
If there are translations, profile tags on user profiles and filters will be displayed in the current language. 
N/A
N/A

Issue #3469391: Fix profile tag translation

---

modules/social_features/social_user/social_user.module
tests/behat/features/capabilities/account/verified-user.feature
translations.php

We need to change the copy of the user account settings to make sure the end user understands what the settings do and how they affect behavior on the site.
Change the copy to:
- Registered users are verified immediately → New users automatically get the Verified User role assigned
- New users will be required to validate their email address prior to logging into the site, and will be assigned a system-generated password. With this setting disabled, users will be logged in immediately upon registering, and may select their own passwords during registration. -> New users will be required to confirm their email address via an account activation email prior to logging in. With this setting disabled, users will be logged in immediately upon registering, and may select their own passwords …

Issue #3470967: Account Settings - Copy improvements

---

modules/social_features/social_content_report/social_content_report.module

SM received a notification about inappropriate content but not an email.
Allow users with `view inappropriate reports` permission to view flagging entities. This solves the related problem of sending emails with information about a user's report. Email can be sent only in cases if a receiver has view access to a related entity.
- https://getopensocial.atlassian.net/browse/PROD-29770
- https://www.drupal.org/project/social/issues/3468336
_SM can now receive emails about inappropriate content._

Issue #3468336: SM can receive emails about inappropriate content

---

modules/social_features/social_group/src/Plugin/Block/GroupHeroBlock.php

The GroupHeroBlock lacks a user cache context. As a result, when a group admin adds a member to a group with "Group members only (secret)" visibility, the block does not appear for the new member until the cache is cleared.
Add cache context by user for the "GroupHeroBlock" block.
- https://www.drupal.org/project/social/issues/3472091
- https://getopensocial.atlassian.net/browse/PROD-30483
N/A
Before:
After:
N/A
Add cache context by user for the "GroupHeroBlock" block.
N/A

Issue #3472091: Add cache context by user for "GroupHeroBlock" block

---

modules/social_features/social_group/src/Plugin/Block/GroupHeroBlock.php

Follow up for: https://github.com/goalgorilla/open_social/pull/4057
The GroupHeroBlock lacks a user cache context. As a result, when a group admin adds a member to a group with "Group members only (secret)" visibility, the block does not appear for the new member until the cache is cleared. But adding `user` cache context could create some performance issues, so we need to add cache context only by _"user group permission"_.
Add cache context by _"user group permission_" for the "GroupHeroBlock" block.
- https://www.drupal.org/project/social/issues/3472091
- https://getopensocial.atlassian.net/browse/PROD-30483
Before:
After:
Fix block caching for new Group members
Add cache context by user for the "GroupHeroBlock" block.

Issue #3472091: Change cache context of "GroupHeroBlock" block from user to user group permissions

---

modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
tests/behat/features/capabilities/groups/flexible/groups-flexible-group-manager-block.feature

Verified user (member and non member of the group) can always see the Managers block on the about page regardless of the join method
Remove restriction for the block_list_managers in hook_block_access to display it regardless of the join method. So, users with access to the "About group" page will have an access to that block as well
- https://www.drupal.org/project/social/issues/3471613
- https://getopensocial.atlassian.net/browse/PROD-30140
N/A
- Display "Group managers" block for VU on the about page regardless of the join method
N/A
N/A

Issue #3471613: Display "Group managers" block regardless of the join method

---

composer.json
modules/social_features/social_user/src/Form/SocialUserLoginForm.php

The password edit field name is not meaningful for screen reader users. It happens because the "Password" field wrapper also contains the "Forgot password?" link.
Move the "Forgot password?" link to a separate wrapper.
- https://www.drupal.org/project/social/issues/3472528
- https://getopensocial.atlassian.net/browse/PROD-30325
Before:
After:
Password edit field name is now meaningful for screen reader users.

Issue #3472528: Move the "Forgot password?" link to separate wrapper

---

modules/social_features/social_swiftmail/social_swiftmail.module

When the event manager sends bulk emails to anonymous enrollees these receivers don't see their own names on emails.
Symfony Mailer moves all parameters to a new property, so we should get the context from it if possible.
See `\Drupal\symfony_mailer\Plugin\EmailBuilder\LegacyEmailBuilder::createParams()`
- https://www.drupal.org/project/social/issues/3473583
- https://getopensocial.atlassian.net/browse/PROD-30024
_Before:_
_After:_
_Anonymous event enrollees see their names in emails._

Issue #3473583: Anonymous event enrollees see their names in emails

---

modules/social_features/social_tagging/config/modify/social_tagging.default_permissions.yml

It's not possible to create taxonomy items of Content tags when the Taxonomy Access Fix module is enabled.
I created a configuration-modify to apply when the Taxonomy Access Fix module is enabled to add default permission.
[PROD-30610](https://getopensocial.atlassian.net/browse/PROD-30610)
[#3473138](https://www.drupal.org/project/social/issues/3473138)
N/A
N/A
Fix permission related to Social Tagging module and Taxonomy Access Fix module to create term for Content Tags
N/A
N/A
[PROD-30610]: https://getopensocial.atlassian.net/browse/PROD-30610?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Issue #3473138: Add default permission for Content Tags based in Taxonomy Access Fix

---

modules/social_features/social_tagging/social_tagging.module
modules/social_features/social_tagging/src/Form/SocialTaggingSettingsForm.php

After implementing the feature [Allow disable/enable tagging per group bundle](https://www.drupal.org/node/3465212), a bug appeared: filters for 'Social Tags' disappeared from the 'All groups' view.
In the file `social_tagging.module`, we have a hook `social_tagging_form_views_exposed_form_alter` that checks if filters are allowed for a view. The following code is present: `'views-exposed-form-newest-groups-page-all-groups' => ['group']`. However, the 'Placement ID' group no longer exists. It should be updated to a list of all available 'Placement IDs' for existing group bundles.
- https://www.drupal.org/project/social/issues/3474659
- https://getopensocial.atlassian.net/browse/PROD-30651
before:
After:
The filters on "All groups" page were fixed.

Issue #3474659: Fix filters for "All groups" view

---

modules/custom/social_language/social_language.services.yml
modules/custom/social_language/src/PathProcessor/SocialLanguagePathProcessor.php

Follow up #3995 
Redirect users to the canonical URL if alias can't be detected.
- https://www.drupal.org/project/social/issues/3464465
- https://getopensocial.atlassian.net/browse/PROD-28352
Fix redirect to the content if the alias can't be detected on multilingual sites.

Issue #3464465: Prevent "Page not found" for non-translated content pages

---

modules/social_features/social_emoji/assets/js/social_emoji_picker.js
modules/social_features/social_emoji/social_emoji.module

In a multilingual website, when the module social_emoji is enabled, the placeholder in the emoji picker is not translatable even though the string Search is already translated.
1. Add a new language
2. Translate the string "Search"
3. Install the module `social_emoji`
4. Go to the Stream page
5. Open the emoji picker form
You should see the placeholder "Search" is still not translated.
Override the property in the plugin instance to render the translated string in the input form by getting its value from`drupalSettings`.
- https://www.drupal.org/project/social/issues/3474231
- https://getopensocial.atlassian.net/browse/PROD-30714
N/A
The string should be translated.
Add ability to translate the emoji picker search input.
N/A
N/A

Issue #3474231: Translate the emoji picker search input

---

modules/social_features/social_profile/config/install/views.view.newest_users.yml
modules/social_features/social_profile/config/update/social_profile_update_130002.yml
modules/social_features/social_profile/social_profile.install

Users with Blocked status are displayed on the All Members page (`/all-members`).
Update the views `/all-members` to hide blocked user.
https://getopensocial.atlassian.net/browse/PROD-30586
- Create a user and set it blocked
- Access /all-members
- See that blocked users are not showing
Hide all blocked users from the view all members (/all-members).

PROD-30586: Hide blocked users in /all-members views.

---

cspell.words.txt
modules/custom/social_eda/social_eda.info.yml
modules/custom/social_eda/src/Types/Address.php
modules/custom/social_eda/src/Types/DateTime.php
modules/custom/social_eda/src/Types/Entity.php
modules/custom/social_eda/src/Types/Href.php
modules/custom/social_eda/src/Types/User.php
modules/social_features/social_event/src/EdaHandler.php
modules/social_features/social_event/tests/src/Unit/EdaHandlerTest.php
phpstan-baseline.neon
tests/composer.json

While working on [PROD-30133](https://getopensocial.atlassian.net/browse/PROD-30133): Implement test coverage for "event create" story we came across the following issue: The event-related components are in `open_social`, but their dependencies (e.g. data types) are in `cablecar`. It made it impossible to successfully run the tests in the Distro, and would possibly bring new issues in the future.
To address this issue, we decided to:
- Move `social_eda` module into `open_social`
- Keep `social_eda_dispatcher` in `cablecar` as a stand-alone module
https://getopensocial.atlassian.net/browse/PROD-30684
N/A
N/A
N/A
Internal.
N/A
N/A
[PROD-30133]: https://getopensocial.atlassian.net/browse/PROD-30133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PROD-30684: Reorganize the Social EDA modules to make all components compatible with Distro

---

composer.json

New socialbase has been released where #3473257 has been merged.
Remove the patch from the distro.
https://drupal.org/node/3473257
Removed outdated patch after socialbase theme got updated.

Internal: Remove outdated patch after new socialbase theme release

---

composer.json

The profile page already have hyperlink at Profile Tags and other tag fields, when the user click on it, the user will redirect to users search page applying Profile Tags as filter.
That same behaivor should be added for Expertise and Interests tags on Profile page.
Add link to Expertise and Interest tag on profile page.
[PROD-30669](https://getopensocial.atlassian.net/browse/PROD-30669)
[#3475568](https://www.drupal.org/project/socialblue/issues/3475568)
N/A
N/A
Add hyperlink at Expertise and Interest tag on Profile page to users search page filter by tag clicked on profile page.
N/A
N/A
[PROD-30669]: https://getopensocial.atlassian.net/browse/PROD-30669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Issue #3475568: Add hyperlink to Expertise and Interests profile tags

---

modules/social_features/social_profile/config/install/views.view.newest_users.yml
modules/social_features/social_profile/config/update/social_profile_update_130002.yml

In the https://github.com/goalgorilla/open_social/pull/4067 we added config updates but with UUID null. This can cause issues like
8192: mb_strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/core/lib/Drupal/Core/Config/Entity/Query/Condition.php line 39
Remove the UUID: null
https://www.drupal.org/project/social/issues/3475825
Removed config UUID from a new view update for that was introduced in #3475825

Issue #3475825: Remove the UUID null as it can cause issues when config has no UUID

---

composer.json
tests/behat/features/capabilities/comment/comment-delete.feature
tests/behat/features/capabilities/event/event-delete.feature
tests/behat/features/capabilities/post/post-delete.feature
tests/behat/features/capabilities/post/post-group.feature

Metatag branch 2.x introduced `$renderer->executeInRenderContext()` which breaks the standard propagation and avoid the batch to run when we try to delete a single post.
Patching metatag to process a standard rendering/propagation if a batch is set.
https://www.drupal.org/project/metatag/issues/3476944
https://getopensocial.atlassian.net/browse/PROD-30481
- Create a post from a group
- Delete that post - you will see the batch page
- Go to home page -> the post is deleted.
Fix a bug introduced by metatag 2.x thats prevent batch to run on hook_entity_delete

PROD-30481: Add patch to metatag to fix non-execution of the batch for single entity deletion

---

modules/custom/social_eda/src/Types/Application.php
modules/social_features/social_core/social_core.api.php
modules/social_features/social_core/social_core.module
modules/social_features/social_event/asyncapi.yml
modules/social_features/social_event/social_event.module
modules/social_features/social_event/src/EdaHandler.php
modules/social_features/social_event/src/Event/EventEntityData.php
modules/social_features/social_event/tests/src/Unit/EdaHandlerTest.php

This pull request introduces the new EDA event "event publish" which is dispatched to the Kafka topic `com.getopensocial.cms.event.publish`. The event is triggered on `hook_social_core_event_published`, a new custom hook also provided by this PR;
```
{
"id": "62d4fc19-88b1-4e33-a82c-47657696388b",
"source": "/admin/config/system/cron/jobs/scheduler_cron/run",
"type": "com.getopensocial.cms.event.publish",
"time": "2024-10-03T13:36:41Z",
"data": {
"event": {
"id": "c42d8ff9-a2a4-4e79-8312-d3ecb8bb1af5",
"created": "2024-10-03T13:36:41",
"updated": "2024-10-03T15:36:17",
"label": "xzczxc",
"visibility": "community",
"group": null,
"author": {
"id": …
```

PROD-30875: Implement "event published" event for the EDA

---

modules/social_features/social_event/asyncapi.yml
modules/social_features/social_event/social_event.module
modules/social_features/social_event/src/EdaHandler.php

This pull request introduces the new EDA event "event unpublish" which is dispatched to the Kafka topic `com.getopensocial.cms.event.unpublish`. The event is triggered on `hook_social_core_event_unpublished`.
```
{
"id": "9c71e8d6-52ec-4ddf-bfa6-bcbbeb816302",
"source": "/node/29/edit",
"type": "com.getopensocial.cms.event.unpublish",
"time": "2024-10-03T13:36:41Z",
"data": {
"event": {
"id": "c42d8ff9-a2a4-4e79-8312-d3ecb8bb1af5",
"created": "2024-10-03T13:36:41",
"updated": "2024-10-04T16:39:51",
"status": "unpublished",
"label": "xzczxc",
"visibility": "community",
"group": null,
"author": {
"id": "b0dc9a92-7e00-425d-a307-e6fb8418a69b",
"href": {
"canonical": …
```

PROD-30876: Implement "event unpublished" event for the EDA

---

modules/custom/social_eda/src/Types/ContentVisibility.php
modules/social_features/social_event/asyncapi.yml
modules/social_features/social_event/src/EdaHandler.php
modules/social_features/social_event/src/Event/EventEntityData.php
modules/social_features/social_event/tests/src/Unit/EdaHandlerTest.php

Currently the visibility in the eventCreate event is a string, this is not correct according to the specification, it should be an object.
Implement a specific type for the visibility that will return the object that is according to the specifications.
https://getopensocial.atlassian.net/browse/PROD-30226
```
"type": "groups",
"groups": [
"3bc51523-4f40-459c-887c-056432fe17cd"
],
"roles": []
},
```

PROD-30226: Implement the visibility options as an object for the EDA

---

modules/social_features/social_user/social_user.routing.yml
modules/social_features/social_user/src/Controller/SocialUserController.php
phpstan-baseline.neon
tests/behat/features/capabilities/account/my-profile-page.feature

Add a redirect from /my-profile path to /user/{user-id}/stream (stream page) of current user. It will smoth the user-experience.
Created a route for logged user and add a redirect to stream page of logged user.
[PROD-30752](https://getopensocial.atlassian.net/browse/PROD-30752)
[#3477759](https://www.drupal.org/project/social/issues/3477759)
N/A
**Non logged user**
**Logged user**
N/A
Created /my-profile path and redirect the logged user to stream page when they try to access the new route.
N/A
N/A
[PROD-30752]: https://getopensocial.atlassian.net/browse/PROD-30752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Issue #3477759: Add a redirect to stream page of logged user from /my-profile path

---

modules/social_features/social_group/modules/social_group_default_route/src/EventSubscriber/RedirectSubscriber.php
modules/social_features/social_group/modules/social_group_flexible_group/config/install/group.role.flexible_group-anonymous.yml
modules/social_features/social_group/modules/social_group_flexible_group/config/install/group.role.flexible_group-verified.yml
modules/social_features/social_group/modules/social_group_flexible_group/config/update/social_group_flexible_group_update_130006.yml
modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.info.yml
modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install
phpstan-baseline.neon
tests/behat/features/capabilities/groups/flexible/groups-flexible-page-access.feature
tests/behat/features/capabilities/groups/flexible/groups-flexible-sidebar-blocks.feature
tests/behat/features/capabilities/groups/flexible/groups-flexible-view-outsider-authenticated.feature
tests/behat/features/capabilities/groups/flexible/groups-flexible-view-outsider-verified.feature

Users currently experience inconsistent access to group information, allowing non-members to view the stream and members page. This issue necessitates the creation of a new role, "Verified User (outsider)" to ensure proper permissions.
1. Create a `Verified User (outsider)` group role for the Flexible group
2. Revoke `view group stream page` and `view group_membership relationship` permissions for AU, AN and VU user
Sub-PR:
- https://github.com/goalgorilla/open_social/pull/4120
- https://www.drupal.org/project/social/issues/3477793
- https://getopensocial.atlassian.net/browse/PROD-28608
With this story we want to make sure a user can not access the stream and members page of any  group with any visibility if they are not members of the group.

Issue #3477793: As a user I can not access the stream and members tab in any Flexible group I am not a member of

---

modules/social_features/social_content_report/config/modify/social_content_export.add_vbo_actions_from_content_report.yml
modules/social_features/social_follow_content/config/modify/social_content_export.add_vbo_actions_from_follow_content.yml

The fields related with Social Follow Content and Social Content Report modules was being created by third module, so it was removed from there and should be added here using Config Modify module.
Create config-modify file to create fields relate to Social Follow Content and Social Content Report module at VBO.
[PROD-30645](https://getopensocial.atlassian.net/browse/PROD-30645)
[#3475042](https://www.drupal.org/project/social/issues/3475042)
N/A
N/A
Add VBO actions to be available when the  Social Content Export is enabled.
N/A
N/A
[PROD-30645]: https://getopensocial.atlassian.net/browse/PROD-30645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Issue #3475042: Create VBO Options with Config Modify module

---

modules/social_features/social_event/social_event.module
modules/social_features/social_event/src/EdaHandler.php
modules/social_features/social_event/tests/src/Unit/EdaHandlerTest.php

This pull request introduces the new EDA event "event removed" which is dispatched to the Kafka topic `com.getopensocial.cms.event.delete`. The event is triggered on `hook_ENTITY_TYPE_delete()`.
An example of the payload:
```
{
"id": "893a6d20-e982-40b6-9253-d585b025c931",
"source": "/node/25/delete",
"type": "com.getopensocial.cms.event.delete",
"time": "2024-09-30T14:08:38Z",
"data": {
"event": {
"id": "b2b88fb5-5bd9-4508-b63b-8d95eed628c1",
"created": "2024-09-30T14:08:38",
"updated": "2024-10-03T13:26:46",
"status": "removed",
"label": "Event test 2",
"groups": [],
"roles": []
},
"group": null,
"author": {
"id": "b0dc9a92-7e00-425d-a307-e6fb8418a69b",
"href": { …
```

PROD-30877: Implement "event removed" event for the EDA

---

modules/social_features/social_group/modules/social_group_invite/config/optional/views.view.social_group_user_invitations.yml
modules/social_features/social_group/modules/social_group_invite/config/update/social_group_invite_update_13004.yml
modules/social_features/social_group/modules/social_group_invite/social_group_invite.install
modules/social_features/social_group/social_group.views.inc

During the group v2 update we forgot to update all the table references in the user group invite view. This causes the view to show a broken handler. 
For some reason it didn't break functionally.
Update the tables for the membership count in the user group invite view to be compatible with group v2
None - For customers nothing actually changes as the functionality itself was not broken.
https://www.drupal.org/project/social/issues/3482245
Functional:

Issue #3482245: User group invite view has old group v1 references breaking the handler

---

composer.json

PR https://github.com/goalgorilla/open_social/pull/4117 was merged but didn't pass all the checks yet causing the main branch to fail now.
https://github.com/goalgorilla/open_social/actions/runs/11571789354/job/32210701334
Revert the change.
X
X
X

Internal: Revert PR 4117 for better_exposed_filter dependency update

---

modules/custom/social_eda/src/Types/Application.php
modules/social_features/social_event/src/EdaHandler.php
modules/social_features/social_user/asyncapi.yml
modules/social_features/social_user/social_user.module
modules/social_features/social_user/social_user.services.yml
modules/social_features/social_user/src/EdaHandler.php
modules/social_features/social_user/src/Event/UserEventData.php
modules/social_features/social_user/tests/src/Unit/EdaHandlerTest.php

This pull request introduces the new EDA event "user created" which is dispatched to the Kafka topic `com.getopensocial.cms.user.create`. 
The event is triggered on the following conditions:
- When the user profile is inserted we send the event unless SCIM provisioning is enabled or unless "approval is required by administrator" is configured and this was a self sign-up
- When SCIM provisioning is completed
- When the account is approved by the administrator
```
{
"id": "53117d0c-72d3-4946-b3af-046d734d1060",
"source": "/admin/people/create",
"type": "com.getopensocial.cms.user.create",
"time": "2024-10-09T18:50:53Z",
"data": {
"user": {
"id": "60bb3249-0a59-4422-b899-87f05a3887c2", …
```

PROD-29995: Implement EDA event for when a user completes the process for account registration

---

modules/social_features/social_user/asyncapi.yml
modules/social_features/social_user/social_user.module
modules/social_features/social_user/src/EdaHandler.php
modules/social_features/social_user/src/Event/UserEventDataLite.php
modules/social_features/social_user/tests/src/Unit/EdaHandlerTest.php

> [!CAUTION]
> This PR depends on #4143
This pull request introduces the new EDA event "user logs in" which is dispatches to the Kafka topic `com.getopensocial.cms.user.login`.
```
{
"id": "3f20068e-c6e2-4bc5-89c7-a2e91164656a",
"source": "/user/login",
"type": "com.getopensocial.cms.user.login",
"time": "2024-10-24T12:15:59Z",
"data": {
"user": {
"id": "3cd53a66-b86a-41b4-8225-66eed5bb5fe3",
"created": "2024-10-24T12:15:59",
"updated": "2024-10-24T12:15:59",
"firstName": "",
"lastName": "",
"email": "devel@getopensocial.com",
"roles": [
"administrator"
],
"address": {
"label": "", …
```

PROD-30974: Implement "user logs in" event for the EDA

---

composer.json

The Views ef Fieldset module was update automaticly to major version because it isn't locked in our composer file, this new version isn't be tested by us and it's incompatible if current patches.
Look the Views ef Fieldset module on old version and keep the patches as old version as well.
Internal: Locked the Views ef Fieldset module on old version
N/A
N/A
N/A
N/A

Issue #348563: Lock Views ef Fieldset module on 1.7.0 version

---

modules/social_features/social_event/asyncapi.yml
modules/social_features/social_event/social_event.module
modules/social_features/social_event/social_event.services.yml
modules/social_features/social_event/src/EdaEventEnrollmentHandler.php
modules/social_features/social_event/tests/src/Unit/EdaEventEnrollmentHandlerTest.php
phpstan-baseline.neon

Currently we don't have the eventEnrollmentCreate event.
Create an eventEnrollmentCreate event based on the specification.
Example of the payload:
```
{
"id": "889ef7bf-db9e-4ae4-80bf-a4a8519a12cf",
"source": "/node/32/all-enrollments/add-enrollees",
"type": "com.getopensocial.event_enrollment.create",
"time": "2024-11-04T08:07:26Z",
"data": {
"eventEnrollment": {
"id": "db320b4f-9ee1-413f-a748-3f4f288c8fe1",
"created": "2024-11-04T08:07:26",
"updated": "2024-11-04T08:07:26",
"status": "approved",
"event": {
"id": "862d01ad-7c9f-4864-a1ca-c479adf52886",
"created": "2024-11-04T07:46:40",
"updated": "2024-11-04T07:46:55",
"label": "Test",
"groups": [],
"roles": []
}, …
```

PROD-30972: Implement "user enrolls to event" event for the EDA

---

composer.json

Looking forward to keep our theme compatible with D11, the socialbase has a new patch to make bootstrap compatible with D11.
Install patch from #3484629 to be compatible with D11.
Make our theme compatible with D11.
[PROD-30822](https://getopensocial.atlassian.net/browse/PROD-30822)
[#3484629](https://www.drupal.org/project/socialbase/issues/3484629)
N/A
N/A
[PROD-30822]: https://getopensocial.atlassian.net/browse/PROD-30822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PROD-30822: Add bootstrap patch for Drupal 11 compatibility

---

modules/social_features/social_private_message/social_private_message.module

When the user go to the following page as admin you will see a Block button at the top of the content. The button can be used to block user from sending you private messages.
The button is being added by an hook-entity-view from Private Message module, so create a new hook-entity-view to remove the Block button.
The block button from user stream page will be removed.
[PROD-31118](https://getopensocial.atlassian.net/browse/PROD-31118)
[#3484615](https://www.drupal.org/project/social/issues/3484615)
N/A
N/A
N/A
[PROD-31118]: https://getopensocial.atlassian.net/browse/PROD-31118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Issue #3484615: Remove block button from Private Message using hook-entity-view

---

modules/social_features/social_event/social_event.module
modules/social_features/social_event/src/EdaEventEnrollmentHandler.php
modules/social_features/social_event/tests/src/Unit/EdaEventEnrollmentHandlerTest.php

Currently we don't have user cancels enrollment to the event.
Add this event.
Example payload:
```
{
"id": "a63b41f9-eaa1-4c7c-8bd5-b1062ca7a253",
"source": "/node/33",
"type": "com.getopensocial.event_enrollment.cancel",
"time": "2024-11-04T08:58:44Z",
"data": {
"eventEnrollment": {
"id": "3f07b8d0-15b9-439f-90eb-232aa664d080",
"created": "2024-11-04T09:58:44",
"updated": "2024-11-04T09:58:44",
"status": "approved",
"event": {
"id": "75cc1fef-677b-455a-8d0e-266c6e575dcf",
"created": "2024-11-04T09:44:55",
"updated": "2024-11-04T09:45:08",
"label": "Test Cancel",
"groups": [],
"roles": []
},
"group": null,
"author": { …
```

PROD-30973: Implement "user cancels enrollment to event" event for the EDA #4142

---

modules/social_features/social_user/asyncapi.yml
modules/social_features/social_user/social_user.module
modules/social_features/social_user/src/EdaHandler.php
modules/social_features/social_user/tests/src/Unit/EdaHandlerTest.php

> [!CAUTION]
> This PR depends on #4156
This pull request introduces the new EDA event "user is unblocked" which is dispatches to the Kafka topic `com.getopensocial.cms.user.unblock`.
```
{
"id": "b675caa4-b272-4d0d-9a54-b4092832e146",
"source": "/user/11/edit",
"type": "com.getopensocial.cms.user.unblock",
"time": "2024-11-01T14:10:26Z",
"data": {
"user": {
"id": "44fc433a-da2f-11e5-b5d2-0a1d41d68578",
"created": "2024-11-01T14:10:26",
"updated": "2024-11-04T14:49:09",
"displayName": "Alisonnn Hendrix",
"firstName": "Alisonnn",
"lastName": "Hendrix",
"email": "drupal_social+alisonhendrix@goalgorilla.com",
"roles": [
"verified"
],
"timezone": …
```

PROD-30977: Implement "user is unblocked" event for the EDA

---

phpstan-baseline.neon

This PR fixes the PHPStan errors recently merged into `main`: https://github.com/goalgorilla/open_social/actions/runs/11743894946/job/32717905178?pr=4163

Internal: Fix PHPStan errors

---

modules/social_features/social_user/asyncapi.yml
modules/social_features/social_user/social_user.module
modules/social_features/social_user/src/EdaHandler.php
modules/social_features/social_user/tests/src/Unit/EdaHandlerTest.php

This pull request introduces the new EDA event "user delete" which is dispatches to the Kafka topic `com.getopensocial.cms.user.delete`.
```
{
"id": "7ad93ebc-d8b1-4e98-9d69-1c9299e87c8e",
"source": "/batch",
"type": "com.getopensocial.cms.user.delete",
"time": "2024-11-01T14:10:26Z",
"data": {
"user": {
"id": "a8c4e812-ef52-11e5-9ce9-5e5517507c66",
"created": "2024-11-01T14:10:26",
"updated": "2024-11-01T14:10:26",
"displayName": "benflorez",
"roles": [
"sitemanager",
"verified"
],
"timezone": "Europe/Amsterdam",
"href": {
"canonical": "http://cablecar.localhost/user/14/home"
}
},
"actor": {
"application": null,
"user": {
"id": …
```

PROD-30979: Implement "user delete" event for the EDA

---

modules/social_features/social_user/asyncapi.yml
modules/social_features/social_user/social_user.module
modules/social_features/social_user/src/EdaHandler.php
modules/social_features/social_user/src/Event/UserEventEmailData.php
modules/social_features/social_user/tests/src/Unit/EdaHandlerTest.php

Currently we don't have an EDA event that fires when the user updates their email setting.
Implement the EDA event.
Example payload:
```
{
"id": "7ee7fa08-9020-41f9-a568-8299a92cd99b",
"source": "/user/2/edit",
"type": "com.getopensocial.cms.user.settings.email",
"time": "2024-07-04T05:52:01Z",
"data": {
"user": {
"id": "44fc2486-da2f-11e5-b5d2-0a1d41d68578",
"created": "2024-07-04T05:52:01",
"updated": "2024-11-07T07:27:04",
"displayName": "Susan Williams",
"roles": [
"verified"
],
"href": {
"canonical": "https://opensocial.ddev.site/user/2/home"
}
},
"actor": {
"application": null,
"user": {
"displayName": …
```

PROD-31206: Implement EDA event for when a user's settings and email address are updated

---

modules/custom/group_core_comments/assets/js/group_core_comments.js

When enabling [Group Core Comments support](https://github.com/goalgorilla/open_social/tree/main/modules/custom/group_core_comments) module a verified user who isn't a group member will see the block with a suggestion to join a group which the current content belongs. 
Unfortunately, the **"View group"** button in the block doesn't work (nothing happens on click).
Add `once()` to `group_core_comments/group_core_comments` library to make the **"View group"** button work.
_Before:_
_After:_
Fixed the "View group" button and popup in the comments section of content added to the group.
- https://www.drupal.org/project/social/issues/3486730
- https://getopensocial.atlassian.net/browse/PROD-31191

Issue #3486730:  "View group" button is broken in "group_core_comments" module

---

modules/custom/social_eda/config/install/social_eda.settings.yml
modules/custom/social_eda/config/schema/social_eda.schema.yml
modules/custom/social_eda/social_eda.info.yml
modules/custom/social_eda/social_eda.links.menu.yml
modules/custom/social_eda/social_eda.permissions.yml
modules/custom/social_eda/social_eda.routing.yml
modules/custom/social_eda/src/Form/SettingsForm.php
modules/social_features/social_event/src/EdaEventEnrollmentHandler.php
modules/social_features/social_event/src/EdaHandler.php
modules/social_features/social_event/tests/src/Unit/EdaEventEnrollmentHandlerTest.php
modules/social_features/social_event/tests/src/Unit/EdaHandlerTest.php
modules/social_features/social_user/asyncapi.yml
modules/social_features/social_user/src/EdaHandler.php
modules/social_features/social_user/tests/src/Unit/EdaHandlerTest.php

Although we had separate variables for event types and topics, both were using the same value. After internal meeting, we decided to update the Kafka topic names.
- Add a config form to set the community namespace. There's also a new permission to access this form;
- Update Kafka topic names;
- Update unit tests
> [!WARNING]  
> Although the topic name ends with `.v1`, this code still does not support more than 1 versions of the payload, as we may not need this anytime soon. When this requirement arrives we can implement it.
N/A
- https://getopensocial.atlassian.net/browse/PROD-31167
N/A
The payload can be viewed on http://localhost:8080.
N/A
N/A

PROD-31167: Implement updated Kafka topics and set a default namespace

---

modules/social_features/social_group/modules/social_group_default_route/social_group_default_route.module
modules/social_features/social_group/modules/social_group_default_route/src/GroupLandingTabManager.php
modules/social_features/social_group/modules/social_group_default_route/src/GroupLandingTabManagerInterface.php
modules/social_features/social_group/modules/social_group_default_route/src/SocialGroupDefaultRouteRedirectService.php

The option list should be changed dynamically if the corresponding checkbox is enabled - "Discussion", "Tasks", etc.
Add an AJAX callback to refresh the option list when the field set as a condition in the 'Landing Tab' plugin is triggered.
Implemented dynamic option list of group tab management.
https://getopensocial.atlassian.net/browse/PROD-31120
https://www.drupal.org/project/social/issues/3481367
Need to test with modules from Cablecar with changes from https://github.com/goalgorilla/cablecar/pull/2238

PROD-31120: Implement dynamic option list group tab management

---

modules/social_features/social_group/social_group.services.yml
modules/social_features/social_group/src/GroupStatistics.php
phpstan-baseline.neon

In the database we have table "group_relationship_field_data" which is the data table for group content entities. In this table, we can see the columns type, group_type and plugin_id.
The pattern for the group membership type is usually `<group_type>-<plugin>`. The type (column) is limited to 32 characters, and for example closed_challenge-group_membership (33 characters) is just too long.
Group includes a way to generate names that fit the limits imposed by Drupal core, and it does this consistently in its own code. However, this means that where a `<bundle>-<plugin>` concatenation would exceed the limit, it instead converts it to 'group_content_type_' . md5($preferred_id) and truncates it. This is done in GroupRelationshipTypeStorage::getRelationshipTypeId. The problem is that our code …

Issue #3298886: Fix group statistics count method

---

modules/social_features/social_group/src/Plugin/views/argument/UserUid.php

In the database we have table "group_relationship_field_data" which is the data table for group content entities. In this table, we can see the columns type, group_type and plugin_id.
The pattern for the group membership type is usually <group_type>-<plugin>. The type (column) is limited to 32 characters, and for example closed_challenge-group_membership (33 characters) is just too long.
Group includes a way to generate names that fit the limits imposed by Drupal core, and it does this consistently in its own code. However, this means that where a <bundle>-<plugin> concatenation would exceed the limit, it instead converts it to 'group_content_type_' . md5($preferred_id) and truncates it. This is done in GroupRelationshipTypeStorage::getRelationshipTypeId. The problem is that our code is …

Issue #3487220: Fix user group list

---

modules/social_features/social_album/social_album.group_landing_tabs.yml
modules/social_features/social_group/modules/social_group_default_route/social_group_default_route.api.php
modules/social_features/social_group/modules/social_group_default_route/social_group_default_route.module
modules/social_features/social_group/modules/social_group_default_route/social_group_default_route.services.yml
modules/social_features/social_group/modules/social_group_default_route/src/Controller/SocialGroupDefaultRouteController.php
modules/social_features/social_group/modules/social_group_default_route/src/EventSubscriber/RedirectSubscriber.php
modules/social_features/social_group/modules/social_group_default_route/src/GroupLandingTabManager.php
modules/social_features/social_group/modules/social_group_default_route/src/GroupLandingTabManagerInterface.php
modules/social_features/social_group/modules/social_group_default_route/src/SocialGroupDefaultRouteRedirectService.php
modules/social_features/social_group/modules/social_group_flexible_group/modules/social_flexible_group_book/social_flexible_group_book.group_landing_tabs.yml
modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
modules/social_features/social_group/social_group.group_landing_tabs.yml

Currently, the Group Tab Manager module allows managers to select a wide range of options. In this story, we want to clean up these options to align with what we allow.
Acceptance Criteria:
- As a group creator, I can select only the allowed tabs for non-members in the tab manager options:
1. About
2. Albums
3. Books
4. Discussions (provided by module from Cablecar)
5. Events
6. Files  (provided by module from Cablecar)
7. Tasks (provided by module from Cablecar)
8. Topics
- As a group creator, I can select only the allowed tabs for members in the tab manager options:
1. About
2. Stream
3. Albums
4. Books
5. Discussions (provided by module from Cablecar)
6. Events
7. Files (provided by module from Cablecar)
8. Members
9. Tasks (provided by module from Cablecar)
10. Topics
- An option is …

Issue #3481367: Enhance group tab management

---

modules/social_features/social_user/asyncapi.yml
modules/social_features/social_user/social_user.module
modules/social_features/social_user/src/EdaHandler.php
modules/social_features/social_user/tests/src/Unit/EdaHandlerTest.php

Currently we don't have an EDA event that fires when the user updates their locale setting.
Implement the EDA event.
Example payload:
```
{
"id": "7ee7fa08-9020-41f9-a568-8299a92cd99b",
"source": "/user/2/edit",
"type": "com.getopensocial.cms.user.settings.email",
"time": "2024-07-04T05:52:01Z",
"data": {
"user": {
"id": "44fc2486-da2f-11e5-b5d2-0a1d41d68578",
"created": "2024-07-04T05:52:01",
"updated": "2024-11-07T07:27:04",
"email": "test@test.com"
"displayName": "Susan Williams",
"roles": [
"verified"
],
"href": {
"canonical": "https://opensocial.ddev.site/user/2/home"
}
},
"actor": {
"application": null,
"user": {
"id": …
```

PROD-31207: Implement an EDA event for when a user changes its locale information

---

modules/social_features/social_user/social_user.module
modules/social_features/social_user/src/EdaHandler.php
modules/social_features/social_user/tests/src/Unit/EdaHandlerTest.php

This pull request introduces the new EDA event "user pending" which is dispatches to the Kafka topic com.getopensocial.cms.user.pending.
```
{
"id": "b539b771-3a50-41b0-b96d-4c54d6ae1f39",
"source": "/user/register",
"type": "com.getopensocial.cms.user.pending",
"time": "2024-11-18T13:53:27Z",
"data": {
"user": {
"id": "1c03fa99-1ee4-47fa-981d-9290a8fc2155",
"created": "2024-11-18T13:53:27",
"updated": "2024-11-18T13:53:27",
"status": "pending",
"displayName": "dsds",
"firstName": "",
"lastName": "",
"email": "dsdsds@sd.com",
"roles": [
"verified"
],
"address": {
"label": "",
"countryCode": "",
"administrativeArea": "",
"locality": …
```

PROD-31314: Implement "user is pending" event for the EDA

---

modules/social_features/social_content_report/config/install/views.view.report_overview.yml
modules/social_features/social_content_report/config/update/social_content_report_update_130003.yml
modules/social_features/social_content_report/social_content_report.install
modules/social_features/social_content_report/src/Controller/ReportController.php
modules/social_features/social_content_report/src/Plugin/views/field/LinkReportClose.php

Reported content cannot be seen or deleted from the Report Overview Page by a Site Admin role. Please see the attachment, there is no option to delete and also when clicked on the view comment it doesn't direct to the comment, the user stays at the page.  If we try to delete the reported content from the post itself, it gives the following message and do not delete.  {"message":"The "comment" parameter was not converted for the path "/ajax_comments/{comment}/delete" (route name: "ajax_comments.delete")"}  Reported contents can only be deleted from content overview page.
Rework the reports page to add a delete option, filters and fix errors on the view action.
The destination parameter was removed from action links because it breaks a redirect that exists on routes. 
The Reports page …

PROD-31065: [IOSA-SUP] Reported content cannot be seen or deleted from the Report Overview Page

---

modules/social_features/social_group/modules/social_group_flexible_group/asyncapi.yml
modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.services.yml
modules/social_features/social_group/modules/social_group_flexible_group/src/EdaHandler.php
modules/social_features/social_group/modules/social_group_flexible_group/src/Event/GroupEntityData.php
modules/social_features/social_group/modules/social_group_flexible_group/src/Types/GroupMembershipMethod.php
modules/social_features/social_group/modules/social_group_flexible_group/src/Types/GroupVisibility.php
modules/social_features/social_group/modules/social_group_flexible_group/tests/src/Unit/EdaHandlerTest.php
phpstan-baseline.neon

Currently we don't have an EDA event that fires when a group is created.
Add the new event
Payload:
```
{
"id": "70e9f519-a3d0-421f-bf42-659a08c4191f",
"source": "/group/add/flexible_group",
"type": "com.getopensocial.cms.group.create",
"time": "2024-11-21T15:11:46Z",
"data": {
"group": {
"id": "1bd53650-0316-4713-a8da-bdffd14c539f",
"created": "2024-11-21T15:11:46",
"updated": "2024-11-21T15:11:46",
"label": "Test",
"roles": []
},
"contentVisibility": {
"type": "community"
},
"membership": {
"method": "request"
},
"type": "27aaa381-4322-4096-9cfa-63d4df67d538",
"author": {
"href": {
"canonical": …
```

PROD-31232: Implement "group create" event for the EDA

---

composer.json

Tugboat build fails for the distro
```
warning] Undefined array key "preprocess functions" Registry.php:702
In Template.php line 401:
An exception has been thrown during the rendering of a template ("array_dif  
f(): Argument #2 must be of type array, null given") in "__string_template_  
_ad3d9d102e6e5ac33b7a4ec7da7ccf70" at line 1.                                
In Registry.php line 702:
array_diff(): Argument #2 must be of type array, null given  
```                                                               
Apply patch from the issue https://www.drupal.org/project/drupal/issues/3460773
https://getopensocial.atlassian.net/browse/PROD-31404

PROD-31404: Add patch to fix Tugboat building issue

---

modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install

The social_group_flexible_group_update_130006 was failing because of an already existing "verified" role.
The config name of the group role could be hashed if the length of the name is longer than 32 symbols, so we can't check configs by name, so we should check if such a role exists by GroupRole entity properties.
Internal.
- https://www.drupal.org/project/social/issues/3477793
- https://getopensocial.atlassian.net/browse/PROD-28608

Issue #3477793: Fix social_group_flexible_group_update_130006 update

---

translations/nl.po

When using NL language on an event, the public link to see all members is broken due to wrong translation. 
Update the translation of the link.
Fixing a bug that breaks the NL translation of the public link to see all registered people of an event.
https://getopensocial.atlassian.net/browse/PROD-31219
- Turn on `social_langue`
- go to `/admin/config/regional/language` add Dutch
- select Dutch as default
- go to an event with some registered people
- the link `Alle aanmeldingen` should be working.

PROD-31219: Update broken NL translation

---

modules/social_features/social_group/src/Plugin/views/argument/UserUid.php

#4183 
Was cherry-picked to 12.4.x but contains fixes using Group version 2 changes, that isn't part of 12.4.x only 13.x so we can't cherry-pick this.
This caused:
```
Drupal\Core\Database\DatabaseExceptionWrapper: Exception in User Groups[groups]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'gc.plugin_id' in 'where clause': SELECT "groups_field_data"."created" AS "groups_field_data_created", "groups_field_data"."label" AS "groups_field_data_label", "groups_field_data"."id" AS "id", "flagging_groups_field_data"."id" AS "flagging_groups_field_data_id" FROM "groups_field_data" "groups_field_data" LEFT JOIN "flagging" 
```
For those on 12.4.x
Revert the commit just from 12.4.x, it is valid for 13.x
I've reverted it as an additional commit, to ensure we can explain our reasoning in …

Issue #3490022 - Revert #4183 from `12.4.x` to fix `Column not found: 1054 Unknown column 'gc.plugin_id'`

---

modules/social_features/social_event/src/EdaEventEnrollmentHandler.php
modules/social_features/social_event/tests/src/Unit/EdaEventEnrollmentHandlerTest.php

When deleting users, we are getting this error from EdaEventEnrollmentHandler
When deleting users there is a code that cleans up event and event enrollment as well for the user, the issue is that event gets deleted before the enrollments, which is causing this error.
Fixed an issue when deleting a user would cause a WSOD error.
https://getopensocial.atlassian.net/browse/PROD-31252

PROD-31252: Error on EdaEventEnrollmentHandler while deleting users

---

composer.json

The automated quality checks are not running correctly anymore due to the patches for url_embed not applying anymore. As they seem to be applied in a wrong order.
Combine the patches so we don't have to worry about the order.
None, internal
https://www.drupal.org/project/social/issues/3491068

Issue #3491068: combine patches for #2761187, #3386579, #3386590 to avoid composer failing to apply patches due to order

---

modules/social_features/social_group/modules/social_group_flexible_group/asyncapi.yml
modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.module
modules/social_features/social_group/modules/social_group_flexible_group/src/EdaHandler.php
modules/social_features/social_group/modules/social_group_flexible_group/tests/src/Unit/EdaHandlerTest.php

Currently we don't have an EDA event that fires when a group is updated.
Create a new event for this.
Payload:
```
{
"id": "d1b7cf62-8901-49e6-b7f4-c01926323be1",
"source": "/group/25/edit",
"type": "com.getopensocial.cms.group.update",
"time": "2024-11-22T13:57:34Z",
"data": {
"group": {
"id": "7c2163c1-28bc-4d6d-b90e-bd1ecc77af7f",
"created": "2024-11-22T13:57:34",
"updated": "2024-11-22T14:14:00",
"label": "2uoeuTesteueouu",
"type": "public",
"roles": []
},
"contentVisibility": "community",
"membership": {
"method": "request"
},
"type": "27aaa381-4322-4096-9cfa-63d4df67d538",
"author": {
"href": {
"canonical": …
```

PROD-31337: Implement group update event for EDA

---

modules/social_features/social_activity/modules/social_activity_filter/src/Plugin/views/display/FilterBlock.php
modules/social_features/social_group/social_group.services.yml
modules/social_features/social_group/src/CurrentGroupService.php
modules/social_features/social_group/src/Tests/Unit/CurrentGroupServiceTest.php
modules/social_features/social_post/modules/social_post_photo/src/Plugin/Block/PostPhotoBlock.php
modules/social_features/social_post/modules/social_post_photo/src/Plugin/Block/PostPhotoGroupBlock.php
modules/social_features/social_post/modules/social_post_photo/src/Plugin/Block/PostPhotoProfileBlock.php
modules/social_features/social_post/social_post.info.yml
modules/social_features/social_post/social_post.module
modules/social_features/social_post/social_post.services.yml
modules/social_features/social_post/src/Hooks/SocialPostFormHooks.php
modules/social_features/social_post/src/Plugin/Block/PostBlock.php
modules/social_features/social_post/src/Plugin/Block/PostGroupBlock.php
modules/social_features/social_post/src/Plugin/Block/PostProfileBlock.php
modules/social_features/social_post/src/Test/Unit/SocialPostFormHooksTest.php
phpstan-baseline.neon
social.info.yml

As outlined in our decision record, we have identified the need to integrate Hux instead of relying on traditional hooks for managing interactions and events within our software. The use of hooks, while functional, has led to limitations in scalability, maintainability, and flexibility. 
We will migrate from the current hook-based implementation to Hux. The Hux library offers a more modern and modular approach for handling events, making the system easier to maintain and extend in the long term.
Blog post on how to: https://www.previousnext.com.au/blog/hux-alternative-to-hooks
Drupal seems to go the same way: https://www.drupal.org/node/3442349
https://getopensocial.atlassian.net/browse/PROD-30967
Creation of a `current group service` to fetch the current group service from the context.

PROD-30967: Hux implementation

---

modules/social_features/social_user/social_user.module

In social_user_user_logout(), we used User::load() to load the current user entity. It turns out the previously imported class was `Drupal\social_user\Entity\User` instead of `Drupal\user\Entity\User`.
Properly import both classes.
N/A
https://getopensocial.atlassian.net/browse/PROD-31497
N/A
You should not see the exception.
N/A
N/A

PROD-31497: Fix error while logging out the platform

---

modules/social_features/social_email_broadcast/social_email_broadcast.services.yml
modules/social_features/social_email_broadcast/src/ViewsBulkOperationsActionProcessorDecorator.php
modules/social_features/social_event/modules/social_event_an_enroll/src/Plugin/Action/SocialEventAnEnrollSendEmail.php
modules/social_features/social_event/modules/social_event_managers/social_event_managers.module
modules/social_features/social_event/modules/social_event_managers/src/Plugin/Action/SocialEventManagersSendEmail.php
modules/social_features/social_group/social_group.module
modules/social_features/social_group/src/Plugin/Action/SocialSendEmail.php
modules/social_features/social_group/src/Plugin/views/field/SocialGroupViewsBulkOperationsBulkForm.php

In https://github.com/goalgorilla/open_social/pull/3905 we added the ability to prevent sending emails on bulk operation for groups and events if a user is unsubscribed from these email receiving.
On the group "manage members" page, the group manager can send an email collectively to selected users.
The problem is that if the group has a large number of members (> 100), then choosing the "select all" option, only a part of users will receive the email (this part is always equal to the number of pager).
If select all users and send bulk email:
_Before_:
_After_:
_Before_:
_After_:
Fix the wrong users number during bulk email sending
- https://www.drupal.org/project/social/issues/3490695
- https://getopensocial.atlassian.net/browse/PROD-31389
**EB**: You should see correct numbers during …

Issue #3490695: Wrong users number on bulk email sending

---

modules/custom/activity_viewer/src/Plugin/views/filter/ActivityPostVisibilityAccess.php
modules/social_features/social_group/src/Entity/Access/SocialGroupAccessControlHandler.php

The site-managers is not able to see the content in groups that they are not part of. So as for now, the group membership kind of outweighs the site manager status, which should not be the case.
We are using 'bypass group access' permission from group module and it was removed after version 2, check [#3259076](https://www.drupal.org/project/group/issues/3259076)
So I changed the validation to check group-permission from logged user.
Fixed access from site-manager at group contents without be part of them.
[PROD-31123](https://getopensocial.atlassian.net/browse/PROD-31123)
[#3487312](https://www.drupal.org/project/social/issues/3487312)
N/A
N/A
N/A
[PROD-31123]: https://getopensocial.atlassian.net/browse/PROD-31123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …

Issue #3487312: Site managers can't see content of groups they are not part of

---

composer.json
modules/custom/social_graphql/graphql/open_social.graphqls
modules/custom/social_graphql/tests/src/Kernel/SocialGraphQLTestBase.php

Updates the requirements on drupal/graphql to permit the latest version.
Replace #4073

PROD-31109: Feature/graphql 4.9.0

---

modules/social_features/social_group/src/GroupStatistics.php

In https://www.drupal.org/project/social/issues/3489147 we reverted a plugin-id method for group v1, but the actual commit was bigger than the supplied patch, introducing another group v2 table name.
Revert the method to group v1
We decided to revert the PR for branch 12.x to ensure that the issue is still resolved into 13.x and does not break 12.x.
https://www.drupal.org/project/social/issues/3491376

Issue #3491376: Revert group statistics v2 table for v1

---

composer.json

This PR bumps the version of `data_policy` module to 2.0.4, which contains translation bugfixes.
https://www.drupal.org/project/data_policy/releases/2.0.4
- [#3492268: "Inform Block" entity body should be translatable](https://www.drupal.org/project/data_policy/issues/3492268)
https://getopensocial.atlassian.net/browse/PROD-22012
"Inform Block" config entity fields are translatable.

PROD-22012: Bump version of "data_policy" to 2.0.4

---

modules/social_features/social_group/modules/social_group_flexible_group/config/install/group.role.flexible_group-outsider.yml
modules/social_features/social_group/modules/social_group_flexible_group/config/install/group.role.flexible_group-verified.yml
modules/social_features/social_group/modules/social_group_flexible_group/social_group_flexible_group.install
modules/social_features/social_group/modules/social_group_flexible_group/src/Subscriber/Route.php
modules/social_features/social_group/modules/social_group_invite/src/Controller/SocialGroupInvitationController.php
modules/social_features/social_group/modules/social_group_invite/src/Controller/SocialGroupInvitationOperations.php
modules/social_features/social_group/modules/social_group_invite/src/Routing/RouteSubscriber.php
modules/social_features/social_group/modules/social_group_request/social_group_request.install
modules/social_features/social_group/modules/social_group_request/src/SocialGroupRequestConfigOverride.php

The change is based on permissions, so the ability to join a group should be removed from the AU Outsider role.
This improvement should be applied by default when a new platform is set up and should also apply to all existing platforms.
Expected Behavior:
- **As an AU, I cannot join an Open-to-Join group**: The "Join" button is not visible to AUs.
- **As an AU, I cannot request to join a Request-to-Join group**: The "Request to Join" button is not visible to AUs.
- **As an AU, I cannot see the Invite-Only button**: The "Invite Only" button is not visible to AUs.
- **As an AU, I cannot be invited to join a group**: AU users are not included in the list of invitees.
- **As an AU, I cannot be added directly as a member of a group**: AU users do not appear in the list when someone tries to …

Issue #3490462: Revoke "Join group" and "request group membership" from Authenticated (outsider) group role

---

modules/social_features/social_group/modules/social_group_default_route/social_group_default_route.api.php
modules/social_features/social_group/modules/social_group_default_route/src/SocialGroupDefaultRouteRedirectService.php

When the group type provides hook_social_group_default_route_group_types and the default route for non-members is inaccessible for AN user, and a route alias has been generated for it, an infinite redirect occurs.
Disable redirection for inaccessible default routes, and ignore hardcoded default routes provided by `hook_social_group_default_route_group_types` if this route isn't a "Landing Tab" option.
Internal: Fix group redirection for unsupported routes
- https://www.drupal.org/project/social/issues/3492536
- https://getopensocial.atlassian.net/browse/PROD-31504
Need to test with a DB dump containing old data (groups with created aliases), without the 'social_group_default_group' module enabled.

Issue #3492536: Disable group redirection for unsupported routes

---

modules/social_features/social_core/assets/css/admin-dialog.css
modules/social_features/social_core/assets/css/admin-dialog.scss
modules/social_features/social_core/social_core.libraries.yml
modules/social_features/social_core/social_core.module

The dialog popup does not change the height if this popup contains details element.
Improve the `max-height` style of the dialog popup via jQuery only on the admin pages.
Improve dialog popup height on the admin pages in cases when many form elements are displayed.
- https://www.drupal.org/project/social/issues/3491855
before:
after:

Issue #3491855: Improve max-height style of the dialog popup on the admin pages

---

modules/social_features/social_event/modules/social_event_an_enroll/src/Plugin/views/field/SocialEventAnEnrollViewsBulkOperationsBulkForm.php
modules/social_features/social_event/modules/social_event_managers/src/Plugin/views/field/SocialEventManagersViewsBulkOperationsBulkForm.php
modules/social_features/social_group/src/Plugin/views/field/SocialGroupViewsBulkOperationsBulkForm.php
modules/social_features/social_user_export/social_user_export.install
modules/social_features/social_user_export/social_user_export.permissions.yml
tests/behat/features/capabilities/administration/check-export-users-to-csv.feature

When all the CSV fields in admin/config/opensocial/export aren't checked, the CSV export action should not appear in the group or event manage members views .
The export CSV actions should not be displayed if we have disabled all the user fields in the config.
Fixed an issue where CSV export members action was available in the group/event manage members field, even if all the CSV fields were disabled by the SM in the configuration options of CSV export module.
- https://www.drupal.org/project/social/issues/3490604
- https://getopensocial.atlassian.net/browse/PROD-28635
1. Enable social_user_export, social_group_members_export modules
2. Go to /admin/config/opensocial/export
3. Disable everything
4. Go to any group
5. In Manager Members tab you will see "Export" in actions

Issue #3490604: Remove CSV export button in group and event manage members view when all CSV plugins options disabled by SM

---

config/optional/node.type.book.yml
modules/social_features/social_book/social_book.install

When a topic or event are added to a Group, this information is visible in teasers and node page.
For book pages this information is missing.
Add general metadata info to book pages as well.
Updated the book display so it shows the author and group information on teaser and full view modes.
**Before:**
**After:**
- https://www.drupal.org/project/social/issues/3490130
- https://getopensocial.atlassian.net/browse/PROD-19343
Note: For teasers to work, you need this change:
- https://www.drupal.org/project/socialbase/issues/3490131#comment-15875719**
1. Create a new topic and set it as part of the group
2. You should see the author information and the information that its part of a group below the title
3. Enable social_book and social_flexible_group_book modules
4. Create a new book and …

Issue #3490130: I want to see that a Book page is part of a Group

---

composer.json

Looking to forward to be compatible with Drupal 11 we need to bump Symfony Mailer module to 1.5 as minimal version.
Update Symfony Mailer module to 1.5 version as minimal.
Symfony Mailer release notes:
- https://www.drupal.org/project/symfony_mailer/releases/1.2.1
- https://www.drupal.org/project/symfony_mailer/releases/1.3.0-beta1
- https://www.drupal.org/project/symfony_mailer/releases/1.3.0-beta2
- https://www.drupal.org/project/symfony_mailer/releases/1.3.0-rc1
- https://www.drupal.org/project/symfony_mailer/releases/1.3.0-rc2
- https://www.drupal.org/project/symfony_mailer/releases/1.3.0-rc3
- https://www.drupal.org/project/symfony_mailer/releases/1.2.2
- https://www.drupal.org/project/symfony_mailer/releases/1.3.0
- https://www.drupal.org/project/symfony_mailer/releases/1.3.1
- …

PROD-31114: Bump Symfony Mailer module to 1.5 as minimal version

---

modules/social_features/social_album/social_album.module

When album feature is disabled, the existing and new album is still available when a picture is posted in the general stream, user stream, group stream:
- Hide field_album in the post form when feature is disabled on the stream pages (general stream, user stream, group stream)
- Fixed issue with displaying albums in the post when feature is disabled
- https://www.drupal.org/project/social/issues/3493522
- https://getopensocial.atlassian.net/browse/PROD-31434
N/A
N/A
N/A

Issue #3493522: Album still available in stream post when disabled

---

modules/social_features/social_group/modules/social_group_request/social_group_request.links.task.yml

The 'Membership Requests' tab, provided by the group_pending_members view, is missing from the group page's local tasks menu. The tab works only on the URL pattern group/{}, but in our case, many modules override or modify the canonical group path, causing this tab to be missed.
The 'Membership Requests' tab is added by the `group_pending_members` view, but it works only for the URL pattern `group/{}` (since the view's URL is `group/{}/membership-requests`). It retrieves routes based on this URL pattern and uses the first route from the results as the base route for the tab (which should be the Group entity route). However, when additional modules are enabled (e.g., `social_challenges`, `social_group_default_route`), they may override the group route path. As a result, the group route may …

Issue #3493489: Add "Membership" request link

---

composer.json
modules/social_features/social_editor/config/install/editor.editor.basic_html.yml
modules/social_features/social_editor/config/install/editor.editor.full_html.yml
modules/social_features/social_editor/config/install/editor.editor.mail_html.yml
modules/social_features/social_editor/config/update/social_editor_update_13002.yml
modules/social_features/social_editor/social_editor.info.yml
modules/social_features/social_editor/social_editor.install

After update CKEditor from 4 to 5 version we lost the fullscreen functionality, so it should be available again for all CKEditor fields.
Install [CKEditor 5 Plugin Pack](https://www.drupal.org/project/ckeditor5_plugin_pack) module and enable it for all editor.
Add fullscreen mode to all text-editors.
[PROD-30681](https://getopensocial.atlassian.net/browse/PROD-30681)
[#3492865](https://www.drupal.org/project/social/issues/3492865)
N/A
- Open some editors with CKEditor and check fullscreen button
N/A
N/A
[PROD-30681]: https://getopensocial.atlassian.net/browse/PROD-30681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Issue #3492865: Install fullscreen plugin on CKEditor 5

---

modules/social_features/social_group/src/Hooks/SocialGroupOperationHooks.php
modules/social_features/social_group/tests/src/Unit/SocialGroupOperationHooksTest.php

Probably due to the group update, on the groups overview page it is possible can see the links Nodes and Media in the list of available operations.
Those links are not expected to be there and they even give access denied currently.
We want to hide them/remove them from there
Hide Nodes and Media options from Operations from group list pages using hook_entity_operation_alter.
Note: Looking forward to D11 we will use HUX instead of hook on module file.
The  options Nodes and Media aren't be available anymore on group list page "/admin/group".
[PROD-27612](https://getopensocial.atlassian.net/browse/PROD-27612)
[#3493372](https://www.drupal.org/project/social/issues/3493372)
N/A
N/A
N/A
[PROD-27612]: https://getopensocial.atlassian.net/browse/PROD-27612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3M …

Issue #3493372: Hide operation items (Nodes and Media) from group list page

---

modules/social_features/social_profile/modules/social_profile_fields/social_profile_fields.install

The path field should be hide after: https://github.com/goalgorilla/open_social/pull/4139, but the Nationality taxonomy continue with this field.
Create a hook-update to hide path field
Improved the user-experience to create taxonomy-terms, some unnecessary fields was hide.
N/A
N/A
N/A

Issue #3476285: Hide path field from Nationality taxonomy

---

modules/social_features/social_node/social_node.module
modules/social_features/social_node/social_node.services.yml
modules/social_features/social_node/src/EventSubscriber/NodeQueryAccessAlterSubscriber.php

> [!CAUTION]
> [!NOTE]  
Replace `node grants` with query alters for nodes with `public` and `community` visibilities.

Issue #3458767: Replace node grants for "public" and "community" visibilities

---

modules/social_features/social_group/social_group.services.yml
modules/social_features/social_group/src/EventSubscriber/NodeQueryAccessAlterSubscriber.php

> [!CAUTION]
> [!NOTE]  
Replace `node grants` with query alters for nodes with `group`  visibilities.

Issue #3458767: Replace node grants for "group" visibility

---

modules/custom/activity_viewer/src/Plugin/views/filter/ActivityNotificationVisibilityAccess.php
modules/custom/activity_viewer/src/Plugin/views/filter/ActivityPostVisibilityAccess.php
phpstan-baseline.neon

> [!CAUTION]
> [!NOTE]  
Replace `node_access` table queries with node query access in custom views filters.

Issue #3458767: Replace "node_access" in custom views filters

---

modules/social_features/social_album/config/install/views.view.albums.yml
modules/social_features/social_event/config/install/views.view.events.yml
modules/social_features/social_event/config/install/views.view.upcoming_events.yml
modules/social_features/social_event/config/update/social_event_update_130005.yml
modules/social_features/social_event/social_event.install
modules/social_features/social_event/tests/src/Kernel/GraphQL/QueryEventTest.php
modules/social_features/social_featured_content/config/install/views.view.featured_content_reference.yml
modules/social_features/social_featured_content/config/update/social_featured_content_update_13001.yml
modules/social_features/social_featured_content/social_featured_content.install
modules/social_features/social_group/config/optional/views.view.group_events.yml
modules/social_features/social_group/config/optional/views.view.group_topics.yml
modules/social_features/social_group/config/update/social_group_update_13014.yml
modules/social_features/social_group/modules/social_group_flexible_group/modules/social_flexible_group_book/config/install/views.view.group_books.yml
modules/social_features/social_group/modules/social_group_flexible_group/modules/social_flexible_group_book/config/update/social_flexible_group_book_update_13003.yml
modules/social_features/social_group/modules/social_group_flexible_group/modules/social_flexible_group_book/social_flexible_group_book.install
modules/social_features/social_group/social_group.install
modules/social_features/social_topic/config/install/views.view.latest_topics.yml
modules/social_features/social_topic/config/install/views.view.topics.yml
modules/social_features/social_topic/config/update/social_topic_update_130004.yml
modules/social_features/social_topic/social_topic.install
modules/social_features/social_topic/tests/src/Kernel/GraphQL/QueryTopicTest.php

> [!CAUTION]
> [!NOTE]  
Remove the redundant "Content access" filter from views. 

Issue #3458767: Remove the redundant "Content access" filter from views

---

composer.json
modules/social_features/social_embed/src/Plugin/Filter/SocialEmbedUrlEmbedFilter.php

Bump URL Embed module to 3.0-beta2 to be compatible with D11
Update URL Embed module to 3.0-beta2
URL Embed release notes:
- https://www.drupal.org/project/url_embed/releases/3.x-dev
- https://www.drupal.org/project/url_embed/releases/3.0.0-alpha1
- https://www.drupal.org/project/url_embed/releases/3.0.0-alpha2
- https://www.drupal.org/project/url_embed/releases/3.0.0-beta1
- https://www.drupal.org/project/url_embed/releases/3.0.0-beta2
[PROD-31161](https://getopensocial.atlassian.net/browse/PROD-31161)
N/A
N/A
N/A
[PROD-31161]: https://getopensocial.atlassian.net/browse/PROD-31161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PROD-31161: Bump URL Embed 3.0-beta2

---

modules/social_features/social_event/modules/social_event_max_enroll/social_event_max_enroll.module

The enrollment limit label should not be visible when the limit is disabled.
Add condition and check if the `Enable maximum number of event enrollments` setting is disabled and hide the `Enrollment limit` option on the event create form.
**Before:**
**After:**
When the Event enrollment limit is disabled the user does not see the field or the label of the enrollment limit in the event
- https://www.drupal.org/project/social/issues/3495014
- https://getopensocial.atlassian.net/browse/PROD-31507

Issue #3495014: Fix display of the field and the label of the enrolment limit in the event

---

composer.json

Drupal 10.2 is EOL and doesn't receive security updates anymore.
Yesterday a security announcement was made
https://www.drupal.org/sa-core-2025-003
https://www.drupal.org/sa-core-2025-002
https://www.drupal.org/sa-core-2025-001
Since we still support Open Social 12, we should make it secure.
We don't want to upgrade Open Social 12 from Core 10.2 > 10.3 in a patch release without proper testing, so for now add a patch for minimal impact.

Issue #3508033: Add patch to fix Drupal Core issues

---

composer.json

Drupal released a security update for sa-core-2025-004
https://www.drupal.org/sa-core-2025-004
Drupal 10.2 is EOL and doesn't receive security updates anymore.
Yesterday a security announcement was made
https://www.drupal.org/sa-core-2025-004
Since we still support Open Social 12, we should make it secure.
Added a patch to fix sa-core-2025-004
https://www.drupal.org/project/social/issues/3514353

Issue #3514353: Add patch to fix sa-core-2025-004
